### PR TITLE
rtmp-services: Add Instagram

### PR DESCRIPTION
**Pull request by 350d**
Instagram Live RTMP server as service added

### CODE REVIEW

**Comment by jp9000** [comment]
You need to either update your previous pull request, or close it.

Your commit title should also be "rtmp-services: Add Instagram".  I would recommend reading this document before contributing in the future:  https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst

Additionally, I want you to tell me how one streams on instagram, and whether the stream key needs to be changed every time you stream or any little details like that.

**Comment by 350d** [comment]
@jp9000 Jim, thank you for your corrections. I will check and update title. Service key can be requested via instagram hidden API from [here](https://github.com/mgp25/Instagram-API/blob/master/examples/liveBroadcast.php). I've builded simple interface [here](https://instafeed.me/rtmp/) (No any login/passwords stored on server) if needed. Key needs to be updated on every stream.

**Comment by jp9000** [comment]
Unfortunately, I don't want to fool users in to thinking instagram is actually available as a streaming service, only to find that the only way to do it is via some third-party web page that uses one of instagram's hidden APIs.  Until it's more publically available, I would prefer it if people who used this method just used the custom server section instead.

**Comment by star104** [comment]
hey Vladimir is there a trick to getting the interface you posted working?

**Comment by 350d** [comment]
@radiostorm try one more time, I've updated proxy list.

**Pull request closed without merging**
