### PR TITLE
win-dshow: Fix memory leak caused by using incorrect API

### LINKED ISSUE #4367: [win-dshow/ffmpeg-decode] Memory leak caused by using incorrect API
## Platform

Operating system and version: WIN10 64bit
OBS Studio version: 26.1.2
OBS Log file: none

## Expected Behavior

After choosing video format for camera source between MJPG and H264, memory usage should not be more and more.

## Current Behavior

After choosing video format for camera source between MJPG and H264, memory usage is being more and more.

## Steps to Reproduce

1. connect a camera whose video format includes MJPG and H265, such as Logitch C920.
2. add camera source and open property window.
3. choose video format as MJPG;
4. choose video format as H265;
5. repeat (3) and (4), we can find memory usage is being more and more, and it won't reduce anly more.

## Additional information

**file:** https://github.com/obsproject/obs-studio/blob/master/plugins/win-dshow/ffmpeg-decode.c
**function:** ffmpeg_decode_free
**desc:** While freeing decode->hw_frame and decode->frame, we should use av_frame_free() instead of av_free(). Otherwise, memory leak happen.

### PR DESCRIPTION
**Pull request by wangshaohui1314**
### Description

This fixed #4367. While freeing decode->hw_frame and decode->frame, we should use av_frame_free() instead of av_free(). Otherwise, memory leak happen.

### Motivation and Context

Memory leak will happen while switching video format for camera between MJPG and H264.

### How Has This Been Tested?

Tested on windows 10 works fine

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please review our [Contributing document](https://github.com/obsproject/obs-studio/blob/4a890e1da9a27003c796527b4a603312514e9eac/CONTRIBUTING.rst), particularly the [commit guidelines](https://github.com/obsproject/obs-studio/blob/4a890e1da9a27003c796527b4a603312514e9eac/CONTRIBUTING.rst#commit-guidelines).

The correct prefix for this commit is "win-dshow".

You can amend the commit locally and force push to your fork and it will update this PR.

**Comment by RytoEX** [comment]
To fixup multiple commits like this, you can do the following.

1. Start an interactive git rebase of the two most recent commits.
```
git rebase -i HEAD~2
```

This opens up your default text editor.  Each commit is shown on its own line.  The word "pick" before each commit means "use this commit".

2. Replace the second "pick" with "fixup" or "f".
3. Save the file in your text editor.
4. Close the text editor.
5. Force push to your fork.
```
git push -f \<remote_name>
```

Git rebase can seem complex and scary, but it's very useful.

**Comment by wangshaohui1314** [comment]
> To fixup multiple commits like this, you can do the following.
> 
> 1. Start an interactive git rebase of the two most recent commits.
> 
> ```
> git rebase -i HEAD~2
> ```
> 
> This opens up your default text editor. Each commit is shown on its own line. The word "pick" before each commit means "use this commit".
> 
> 1. Replace the second "pick" with "fixup" or "f".
> 2. Save the file in your text editor.
> 3. Close the text editor.
> 4. Force push to your fork.
> 
> ```
> git push -f \<remote_name>
> ```
> 
> Git rebase can seem complex and scary, but it's very useful.

done. 
thank you ~

**Comment by RytoEX** [comment]
I checked these changes against the FFmpeg documentation, and the documentation seems to agree with these changes.  FFmpeg documentation is currently available for FFmpeg 4.1 and trunk, though not for 4.2 or 4.3.

The [FFmpeg 4.1 docs for av_frame_alloc](http://ffmpeg.org/doxygen/4.1/group__lavu__frame.html#gac700017c5270c79c1e1befdeeb008b2f):
> AVFrame* av_frame_alloc ( void )
> Allocate an AVFrame and set its fields to default values.
> 
> The resulting struct must be freed using av_frame_free().

The members `hw_frame` and `frame` of struct type `ffmpeg_decode` are of type `AVFrame` and init'd with `av_frame_alloc()` in `ffmpeg_decode_init()`.

**Comment by wangshaohui1314** [comment]
API comment of av_frame_alloc() says that we must free its memory by av_frame_free().

Allocate an AVFrame and set its fields to default values.
The resulting struct must be freed using av_frame_free().

**Comment by RytoEX** [comment]
> 
> 
> API comment of av_frame_alloc() says that we must free its memory by av_frame_free().
> 
> _Allocate an AVFrame and set its fields to default values. The resulting struct must be freed using av_frame_free()._

Yes, that's what I said above.

**Comment by wangshaohui1314** [comment]
av_free will only invoke free() for AVFrame.
av_frame_free() will also free some fields of AVFrame.

This is the reason which causes memory leak.

**Review by notr1ch — APPROVED** [review]

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
