### PR TITLE
Feature/watcher

### PR DESCRIPTION
**Pull request by dioptre**
### Description
This adds a watcher plugin with a queue/playlist.

### Motivation and Context
I'm using it for enqueuing videos in a directory auto-generated by an external system.

### How Has This Been Tested?
It's been built and tested only in Linux (the build scripts are only for linux too). It uses pthreads and linux fs functionality so can only be used in linux atm.

### Types of changes
I added a new plugin (I didn't want to break the existing ffmpeg one). We can always merge them later down the track.

### Checklist:
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
Personally I don't think this belongs as a core plugin. As you've pointed out, there is a lot of code duplication with obs-ffmpeg which creates a high maintenance cost. Merging this in means we're committing to maintaining it and with it also being Linux only, that's something I think few people will be interested in working on. The plugin also solves a pretty uncommon use case - not many users will benefit from this being a core plugin vs something they could install themselves if needed.

I'd suggest keeping this in your own repository and listing it on our plugins forum at https://obsproject.com/forum/list/obs-studio-plugins.35/

**Comment by dioptre** [comment]
You do what you want @not1rch! Let me know if ppl find it useful. I made this as I needed it and it didn't exist :)

**Comment by dioptre** [comment]
I just added directory queuing on load. I still think it'd be useful for most people @notr1ch . Having the opinion that people will be happy with a single track player is like saying people wouldn't need spotify/itunes/winamp etc.

**Comment by RytoEX** [comment]
I agree with @notr1ch that this fits better as a third-party plugin than as a core feature.

**Comment by Fenrirthviti** [comment]
Can you provide more details on how exactly this is used, and what you can do with it? It might help the justification point. As it stands I'm not sure I understand how this even works. You say it's being used with another third-party tool, is that a requirement? Will someone have to build an external tool to even utilize this in the first place?

**Comment by dioptre** [comment]
@Fenrirthviti it loads a directory of files and then plays them (think of the ffmpeg plugin but it can play a list). If the directory is empty, or after the images are played, you can send new videos to the queue by just placing them in that directory.  Also (personally this is how I'm using it) If you set the maximum queue length to 0, and place a file in the directory being watched you can broadcast samples near realtime just by placing a media file in the directory being watched. I think a lot of artists and creators will find it super useful, and I couldn't imagine why it didn't exist, which is why I made it.

**Comment by Fenrirthviti** [comment]
Thanks for the clarification. 

I think the concept of the feature itself is fine, we've had plenty of requests for something like this. However, not being cross platform, and not being integrated in to the existing OBS plugin are your two biggest problems right now. If this can be updated to be cross-platform, and integrated in to the existing media source, I think it would be much more likely to be accepted.

That aside, you seem to have deleted parts of the checklist on the PR template, and this PR doesn't conform to our contributing standards. If nothing else, you will need to update this PR to follow our guidelines.

**Comment by dioptre** [comment]
No worries, I'm really time poor. If you want it, you're welcome to share it with the community. It's a shame that people want it and they won't get it. The purpose of having a build pipeline specifically for linux exists so that people can get this functionality early. The purpose of forking, is so someone can then take it and add macOS or whatever to it. I'm not going to add support for systems I don't use. Someone else can.

Perhaps someone with more time can take what I've done and test it on another OS, or add some spaces in the code... Any matter it's here, though likely to be lost to gatekeepers by the sounds of it.

**Comment by Fenrirthviti** [comment]
As notr1ch mentioned, this PR in its current state is a heavy maintenance cost for a feature that we don't really see people asking about very often. Merging things in this state, when they are not conforming to the project's standards (or even just following the contribution guidelines at all), is not about "gatekeeping" a feature, it's about make sure that the code we merge is maintainable. I hope you are able to understand this.

If you are unable to clean up the PR any time soon, then feel free to open a new PR when you have had the time to do so. The code will remain available here for anyone to search for later.

**Comment by dioptre** [comment]
Well if you want me to add some spaces and run through the code guidelines I'm happy to do it, but not at the expense of someone saying I have to add Mac or Windows support. I don't even own a windows machine. How ridiculous. If it's taken as is I'll put the work in to get the code cleaned to your liking, but only if it's going to be accepted.

**Comment by Fenrirthviti** [comment]
Nobody said you had to do that to get accepted. I said that it would help your chances, considering this is a very specific solution for a very specific issue, and then it's further niche by being for the platform with the least amount of overall users.

Frankly, this feels like a drive-by PR that fixed a problem specific to you, without any concern for other users or the maintainers of the project. You deleted parts of our template, clearly did not read the contribution guidelines, and are being combative when asked to fix up the PR to our standards.

I suggest you take the time to read the contribution guidelines for projects you submit code to in the future, and try to be more understand when communicating with members of those projects.

https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst

**Comment by dioptre** [comment]
Being able to queue files seems very niche you might be indeed right. Should have stuck with the single wav file player in windows 3.1.

The code I wrote is not specific to me. I don't even use the directory loading functionality. I built it for the community. But perhaps that was a mistake.

Unfortunately as mentioned I am time poor. So I am short. I just have little or no time to deal with gatekeepers, or for formatting code in 80 spaces when the code is already auto formatted by the worlds most widely used IDE atm. I would have hoped people who might know the code best might spend the 10 minutes getting the spaces in the places they want. But no point in doing that, put the PR in the trash. :)

Good luck with the project.

**Pull request closed without merging**
