### PR TITLE
UI: Improve macOS performance by disabling Qt colourspace conversion

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
This patch reduces OBS' idle CPU usage by about 40-50% by removing the need to do expensive colourspace conversions for drawing the UI.

### Motivation and Context
Profiling on macOS showed a high amount of calls made to colour conversion methods by Qt. The underlying issue (according to comments made in a Qt ticket I found https://bugreports.qt.io/browse/QTBUG-47660) seems to be that each time "the Qt backingstore is pushed to macOS, each pixel is color-rescaled by macOS" and also "macOS converts the 32 bit/pixel pixmap supplied by the Qt backingstore to a 64 bit pixmap, each time the backingstore is flushed to the screen".

Due to retina screen resolutions being default on macOS (and 10-bit colour on 5k iMacs), the size and bit-depth of these bitmaps is effectively "damn big", hence high CPU usage for these operations.

The simple fix as suggested by the last comment was to make Qt use a default sRGB colourspace, disabling conversions altogether.

Do note that the issue identified in https://github.com/obsproject/obs-studio/issues/2841#issuecomment-630991956 still persists, even with the associated Qt fix applied (or alternative building OBS with Qt 5.15.1) - while the high CPU usage for colour conversions (quite probably the high usage of "syscalls" as mentioned in https://github.com/obsproject/obs-studio/issues/2841#issuecomment-701941696) should be removed, we're back to `QBackingStore::flush -> Qimage::copy` eating lots of CPU compared to Windows.

### How Has This Been Tested?
* OBS built on macOS via Xcode and profiled with and without fix to check if CPU usage actually went down consistently

### Types of changes
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Trying to wrap my head around this a bit...

According to the comments from the linked QTBUG:
> For best speed, the patch does the right thing. IMHO, I think this should be the default.

> The default is still the color space that NSWindow automatically picks up from its screen, which effectively means no color matching.

and [one of the associated commits](https://github.com/qt/qtbase/commit/e6498362fde937259295e9b2ddbe9b59136f47ba):

> By default Qt tries to avoid potentially costly color matching by
> not assigning an sRGB color space to our backingstore, even if
> that's what we in practice fill it with.
> 
> We used to do this by assigning the display's color space, which
> effectively opts out of color matching, similar to the old behavior
> of the device RGB color space (which nowadays implies sRGB).
> 
> By picking up the color space from the NSWindow instead, we allow
> the user to override the color space to trigger color matching,
> for example by explicitly setting it to NSColorSpace.sRGBColorSpace.
> 
> NSWindow will fall back to the screen's color space if the window
> doesn't have one set.

This change seems like it would explicitly trigger color matching to occur.  Maybe I'm confusing color matching and colorspace conversion?  Just trying to verify we're making the right change here.

**Comment by PatTheMav** [comment]
As OBS/Qt does not spend lots of time on converting colour on every frame drawn to the screen (which was very obvious when profiling the app) I’d say yes - with the patch most time is spent on media decoding/rendering of the preview (OpenGL draw calls). As soon as there is audio the meters seem to blow everything out the water besides actual encoding though.

I agree that this requires another pass, as it doesn’t help users with Mac Minis as those don’t have built-in screens (which default to sRGB).

I can’t tell _why_ it behaves this way, but in profiling OBS it defaulted to the costly behaviour without this change.

**Comment by PatTheMav** [comment]
I did some additional tests and was able to reproduce the following stack trace by removing the patch/return early:

OBS_Stack_Without_Patch

With this patch this whole stack is gone, but I also can't explain why - I added additional log output for testing and at least on OS level the colourspace of the screen as well as the one of OBS' window are set to the same value. Once I again I have no idea why forcing it to "sRGB" instead removes this automatic conversion. (The default colourspace on my iMac is just called "iMac" as well).

I did another test with a locally-built Qt 5.15.1 and in that version the patch is not needed, this expensive stack never occurs.

**Comment by WizardCM** [comment]
Would it be worth version-gating this code then, or is it fine?

**Comment by PatTheMav** [comment]
I'd probably just test it once we update Qt to 5.15.1 in obs-deps and remove it again when we update the workflow to use that version (which automatically affects the macOS build script as well).

I had no issues with 5.15.1 in my tests, so we might as well do the Qt update for macOS before Windows does (again).

Release-wise it might make sense to couple it with whichever other performance gains Jim might be able to get with the stack traces I gave him.

**Pull request merged**
