### PR TITLE
CI: Update macOS image to macOS 12

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update the macOS image used on GitHub Actions from macOS 11 to macOS 12.

### Motivation and Context

Use the latest Xcode and macOS SDK. Unblock #5875 by allowing CI to produce builds using the macOS 12.3 SDK and ScreenCaptureKit.

### How Has This Been Tested?

CI is the test. CI must return all green for macOS builds before this can be merged.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — APPROVED** [review]
made sure the artifact still works (it does) (honestly though, there wouldn't be any reason why it shouldn't).
lgtm.

**Comment by PatTheMav** [comment]
While we're changing that line, might make sense to remove the array and specify it as a simple string (I think that's what the schema prefers as well).

**Review by PatTheMav — APPROVED** [review]
Apart from the comment above, looks fine to me.

Generated artefact ran without issues and compatibility versions were correctly set on the binary:

```
minos 11.0
sdk 12.3
```

(`minos` is 11 because I need to use the M1 build).

**Comment by RytoEX** [comment]
> While we're changing that line, might make sense to remove the array and specify it as a simple string (I think that's what the schema prefers as well).

If you mean changing `[macos-12]` to `macos-12`, then we should probably change those for all other instances other than the macOS jobs. Though, I don't think it makes any difference functionally. Since there are other places where this syntax is used, I'd prefer to just clean that up separately at some point if needed.

**Pull request merged**
