### PR TITLE
flatpak: Install CMake config files

### LINKED ISSUE #6556: Flatpak builds don't ship CMake files
### Operating System Info

Other

### Other OS

Flatpak runtime

### OBS Studio Version

Git

### OBS Studio Version (Other)

Latest Flatpak build from master

### OBS Studio Log URL

--

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

The Flatpak builds should ship CMake files, to allow building plugins with it as the runtime.

Most notably:
- `LibObsConfig.cmake`
- `obs-frontend-apiConfig.cmake`

### Current Behavior

The CMake files are not shipped. OBS 27.2.4 shipped `LibObsConfig.cmake`, but now it's also absent in the `master` builds.

### Steps to Reproduce

1. Download and install the latest Flatpak build from `master`
2. Run `flatpak run --command=find com.obsproject.Studio//master /app/lib/cmake -name "*.cmake"`
3. It errors out while it should print the CMake files paths

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by rmnvgr**
### Description

Add a post-install command to the OBS module that installs the `obs_libraries` component, which provides CMake config files.

### Motivation and Context

CMake config files are required for building OBS plugins with the Flatpak as a runtime.

Builds from the `master` branch stopped shipping the `LibObsConfig.cmake` file, and never shipped the `obs-frontend-apiConfig.cmake` file.

Fixes #6556 

### How Has This Been Tested?

Built locally, the resulting Flatpak ships the following CMake config files:

- `/app/lib/cmake/libobs/libobsConfig.cmake`
- `/app/lib/cmake/libobs/libobsConfigVersion.cmake`
- `/app/lib/cmake/libobs/libobsTargets.cmake`
- `/app/lib/cmake/libobs/libobsTargets-release.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiConfig.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiConfigVersion.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiTargets.cmake`
- `/app/lib/cmake/obs-frontend-api/obs-frontend-apiTargets-release.cmake`

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Using a cmake command like this is not a good idea because we can't predict if the flatpak-builder change how cmake is used.
Today it is `.` it can be changed in the flatpak-builder code.

@PatTheMav is trying to automate the installation of `obs_libraries` on Linux builds, which could be a better solution.

**Comment by PatTheMav** [comment]
FWIW that's how I would've solved this originally as well, but then I don't know as much about Flatpak internals. 😄

**Comment by tytan652** [comment]
> FWIW that's how I would've solved this originally as well, but then I don't know as much about Flatpak internals.

Same but since we use the `cmake-ninja` buildsystem, we can end up with a broken manifest because flatpak-builder change where the cmake commands are executed.

**Comment by rmnvgr** [comment]
> FWIW that's how I would've solved this originally as well, but then I don't know as much about Flatpak internals. smile

Well I have another problem: I would have changed this in CMake, but I'm not familiar with it :sweat_smile: 

> Same but since we have Flatpak that use the `cmake-ninja` buildsystem, we can end up with a broken manifest because flatpak-builder could change where the cmake commands are executed.

Changing where the post-install commands are run would likely break not only OBS, but most Flatpak out there, so it'd be safe to assume this behavior won't change.

Although I do agree, this is not the cleanest solution, having the build system install them itself would be better, but again I'm not familiar enough in CMake to propose something else.

**Comment by tytan652** [comment]
> Changing where the post-install commands are run would likely break not only OBS, but most Flatpak out there, so it'd be safe to assume this behavior won't change.
> 
> Although I do agree, this is not the cleanest solution, having the build system install them itself would be better, but again I'm not familiar enough in CMake to propose something else.

I want to precise that this PR provides a clean solution, if we assume that flatpak-builder behavior won't change. 

@GeorgesStavracas, what do you think of this ?

**Comment by rmnvgr** [comment]
> if we assume that flatpak-builder behavior won't change.

I asked the Flatpak team on their Matrix channel, and their answer has been unequivocally "[yes](https://matrix.to/#/!RfXaBjokqHAbzZrgHz:matrix.org/$03UGzGQF4-loG2DiDg-BysG_fzCEW2-q-j4ZjGZjM-0?via=matrix.org&via=gnome.org&via=kde.org)".

**Review by GeorgesStavracas — APPROVED** [review]
I'm fine with this. At some point I want to experiment with Meson, but this PR should cover our backs as long as we're using CMake.

**Pull request merged**
