### PR TITLE
mac-videotoolbox: CBR, CRF and Simple Mode (on Apple Silicon)

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Adds three major improvements for the mac-videotoolbox hardware encoder:
- CBR on Apple Silicon / macOS 13+
- CRF on Apple Silicon
- Simple mode on Apple Silicon (Simple Mode Streaming is only available for macOS 13+)

Essentially, this combines and adjusts #6537, #5913, and #6599.

Defaults are changed to CBR if it's available, and as such existing setups change. However,
we determined that this is acceptable (and intentional to some degree), since in most of
the cases where ABR (until now the only option) was used CBR is preferable.

For simple mode recordings, the numbers used are still very much up to change. The intention
is to do more testing to find values that roughly match to what x264 delivers, however that will
take some time and should not block this PR from getting reviewed and/or merged.

Settings UI screenshots:
image
image
image

### Motivation and Context

The PRs above all conflict with each other and had to be adjusted by us anyways.
Hence it was decided that we combine them into one PR.

### How Has This Been Tested?

macOS 13 Beta 2

Advanced mode:
- Used CBR to stream to a popular streaming site.
- Used CRF with different values to record.

Simple mode:
- Used streaming to stream and confirmed it correctly used CBR.
- Used both recording qualities and confirmed that the quality values are correctly set.

This PR has the "Seeking Testers" label to produce CI artifacts, but please keep in mind
that since GitHub Actions does not yet offer Xcode 14, these artifacts will not contain
CBR, even if you're running macOS 13. If you want to test CBR, you need to compile it
manually for the time being.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

Closes #6537 
Closes #5913
Closes #6599

### CODE REVIEW

**Comment by gxalpha** [comment]
For the record, I did confirm that CBR works with Rosetta.

**Comment by CarrotCodes** [comment]
I've been trying this out (on commit `da76ea8`, macOS `Version 13.0 Beta (22A5295h)`, Mac Studio) today for the hardware CBR support, and it generally works great, but I also saw one confusing thing:

I changed the encoder to "hardware", streamed, and came back and switched it back to "software", and the "encoder preset" got blanked out:

Screenshot 2022-07-11 at 14 46 56

**Comment by gxalpha** [comment]
@CarrotCodes are you on an Intel or Apple Silicon Mac?

**Comment by CarrotCodes** [comment]
> @CarrotCodes are you on an Intel or Apple Silicon Mac?

Apple Silicon

**Comment by gxalpha** [comment]
Did you build yourself or did you use CI builds?

**Comment by CarrotCodes** [comment]
> @CarrotCodes could you retry with the updated commits?

I followed the same steps as last time and it correctly kept the `faster` setting for me 👍 

Screenshot 2022-07-11 at 21 53 26

**Comment by matthewbrandt** [comment]
As a streamer on Mac who uses an e-GPU, this is a REALLY welcome change that will hopefully finally allow me to have a true CBR of 6000kbit! 
For my understanding - will I need to wait for 28.0.0 to get access to this feature, or will it be released in an earlier version?
Thank you :)

**Comment by gxalpha** [comment]
@matthewbrandt Due to limitations outside of our control, this will only be available on Apple Silicon hardware encoders. As you’re using an eGPU I assume you’re on Intel, in which case this unfortunately will not work for you. In general, it will be available with OBS 28, which is planned to be the next major release.

**Comment by RustySly** [comment]
hey there! today I built the commit (e27f90f) using macOS 13 beta 3 and Xcode 14 beta. I'm just unable to use CBR without getting highly pixelated video. ABR also produces low quality image with limiting the bitrate. my settings are as in the attached image. when I check the stats window it shows 16000 kb/s correctly but the end result is garbage.
Screenshot 2022-07-14 at 03 19 14

**Pull request merged**
