### PR TITLE
libobs: Add support for many more color formats

### PR DESCRIPTION
**Pull request by Xaymar**
Adds many new color formats for use in OBS Studio and plugins, which can be used to directly control the data type and data width, instead of relying on potentially bad formats for the data uploaded. For example, a half float (GS_RG16F) is less precise than the new unsigned short mode (GS_R16G16_UNORM). The main objective here is to increase the flexibility of the gs backend to allow plugins to rely on libobs without having to fall back to hack-ish workarounds, like I currently have to do in obs-stream-effects. 

Additionally a fix is included for GS_R8G8, which was of type GL_R16 and GL_UNSIGNED_SHORT, despite being a two channel texture. This resulted in corrupted uploads when actually using the texture, and a lack of a green channel when used as a rendertarget format.

### Format Descriptions:
- UNORM: Unsigned Normal, in shader has a value of 0.0f to 1.0f.
- SNORM: Signed Normal, in shader has a value of -1.0f to 1.0f. -1.0f is represented twice in binary, so each positive and negative side is identical in accuracy.
- FLOAT: Floating Point Value, any floating point value that can be represented by a half float or single float.
- UINT: Unsigned Integer, any value above 0 and below byte/short/int.
- SINT: Signed Integer, any value between byte_min/short_min/int_min and byte_max/short_max/int_max.
- For plugins that need to use sRGB, some UNORM variants also come with an UNORM_SRGB alternative, which uses the Driver/Hardware to decode sRGB to "RGB".

### ToDo:
- [x] Fix apply_swizzle
- [x] Convert already existing types into aliases of existing enum entries.

### CODE REVIEW

**Comment by jpark37** [comment]
Maybe it would be better to assign enum values in terms of current identifiers where they are equal. One example is that apply_swizzle seems to be broken now, but that function wouldn't need to be updated if A8_UNORM was implemented in terms of A8.

Without having vetted the new list of formats, keeping the list minimal may help avoid formats that may not be supported on all GPUs, and/or possibly don't exist in other API backends that are yet to be implemented. I can see the rationale for wanting access to more formats and not adding as requested one-by-one though.

The GS_R8G8 fix for GL seems like it should be taken regardless.

**Comment by Xaymar** [comment]
> Maybe it would be better to assign enum values in terms of current identifiers where they are equal. One example is that apply_swizzle seems to be broken now, but that function wouldn't need to be updated if A8_UNORM was implemented in terms of A8.

Figured I had forgotten at least one thing.

**Comment by Xaymar** [comment]
I've adjusted the PR to no longer have duplicate types, instead these are aliases to the original enum entries now. This should fix all incorrect checks for now.

> keeping the list minimal may help avoid formats that may not be supported on all GPUs ... and/or possibly don't exist in other API backends that are yet to be implemented

If OBS truly aimed to keep the list minimal to only have formats that are supported on all GPUs, the only format in that list should be R8, RG8, RGBA8. Which is kind of a ridiculously heavy restriction on capabilities that are available on the majority of devices.

As it is right now, plugins have to make sure that they are compatible with the majority of devices themselves anyway, as OBS does not provide any full graphics or sound engine to work with that could handle incompatibilities automatically. Nor that I really wish for it in the first place, as those engines usually come with a large amount of restrictions.

> ... keeping the list minimal may help avoid formats that may not be supported on all GPUs

UNORM and FLOAT types are supported on all GPUs, though not necessarily up to 32-bit. Older GPUs may limit themselves to 16-bit, due to half width floating point being the only supported type.

SNORM, UINT and INT and modern types which should be available on most DirectX 11 hardware, and OpenGL 4.4 and newer. Most cards that support TYPELESS also support SNORM UINT INT and other vendor specific types.

**Comment by dionney** [comment]
This seams to break Xcomposite capture on linux. What ever window I choose, I receive an endless stream of :

error: glCopyImageSubData failed, glGetError returned 0x502
error: device_copy_texture (GL) failed

This is on Mesa 19.1, RX 580.

**Comment by Xaymar** [comment]
I have partially reverted the aliased types, which should fix Xcomposite capture on linux.

The change introduces a slight difference between DirectX and OpenGL for the unsized types GS_RGBA, GS_BGRA and GS_BGRX:

* DirectX treats GS_RGBA as GS_R8G8B8A8_UNORM, GS_BGRA as GS_B8G8R8A8_UNORM and GS_BGRX as GS_B8G8R8X8_UNORM.
* OpenGL treats GS_RGBA, GS_BGRA and GS_BGRX as different types.

In normal operation this shouldn't make a difference, but one should not rely on being able to copy from a GS_RGBA texture to an GS_R8G8B8A8_UNORM texture.

**Comment by dionney** [comment]
Confirm changes works for me.

**Comment by jpark37** [comment]
Instead of copying, it seems like the window texture could be bound directly with a shader that handles border/crop. That may eliminate the need to diverge between D3D and GL.

**Comment by Xaymar** [comment]
Rebased the commit onto 24.0.0rc1 and fixed the accidental removal of Alpha support in DXT1.

**Comment by Xaymar** [comment]
After a bit of thought, I've come to the conclusion that this PR doesn't really solve the problem I had initially, and only adds extra load to the already overworked solo maintainer Jim. It would be much better to expose the IDirect3DDevice, IDirect3DDeviceContext and OpenGL context information than to force these features into OBS, which, as Jim stated several times before, "is not a 3D engine".

Therefore, I am closing this PR in favor of a different future PR to expose the 3D context information to plugins instead.

**Comment by jp9000** [comment]
Thank you, it's likely the same conclusion I would have come to.

Yea, I have to apologize for all the PR delays, I have been overworked and we need more maintainers.  I'm going to be doing nothing but pull requests this month and probably next month.  The 24 release has been a lot of work, and we still have at least one hotfix to release, so as soon as I get that out of the way I'm going to get back to it and get everything cleaned up.  I'm going to be moving towards primarily maintaining rather than coding, and I'm going to hopefully at some point train additional maintainers.

**Pull request closed without merging**
