### PR TITLE
UI: Add media controls

### PR DESCRIPTION
**Pull request by cg2121**
This also modifies libobs and obs-ffmpeg.

This is a replacement for https://github.com/obsproject/obs-studio/pull/1314

This makes the media source have feature parity with the VLC source.

TODO:
- [x] Get play/pause button to work
- [x] Add playlist support
- [x] Split into seperate commits
- [x] Fix memory leak
- [x] Bug when setting source to always be active
- [x] Backwards compatible with previous media sources
- [x] Control VLC source
- [x] Use svg icons

### CODE REVIEW

**Comment by SuslikV** [comment]
> ...
> [ ] Deprecate VLC Source

What?!!

**Comment by dodgepong** [comment]
The VLC source was only added as a stop-gap to easily add playlist support. But adding a second source type to play videos is just silly. We only need one source type to play videos, so we'd prefer to add playlist support to the regular media source.

**Comment by cg2121** [comment]
Playlist support has now been added, and I got the play/pause button to work. I have also deprecated the VLC source.

**Comment by SuslikV** [comment]
I just want to warn you, that the vlc was too long as the stop-gap, so its more like feature now. It was suggested couple of times as network (IP cameras) source input in obs.

**Comment by Fenrirthviti** [comment]
Deprecation might be a bit premature, as the media playlist is not the only reason to use VLC source. It is still a bit more stable with network streams than the media source. Media source does not recover gracefully from connection hiccups, and it can lead to situations where it doesn't recover at all and playback stops/freezes. With media controls, a "Restart" option would help with this, but I would say until we can solve the network stream issues (or improve the situation) we should leave the VLC source available.

That said, this is a huge step forward to deprecation. The network stuff can be discussed separately.

**Comment by WizardCM** [comment]
I made a custom build with this last night, and my existing Media sources were no longer pointing to anything. I had to manually select the file again.

**Comment by jp9000** [comment]
1. VLC source should not be deprecated.  It has more features than we can provide with the media source.
1. What I'd prefer is a new source called the "Media Playlist".  I dislike the idea of trying to cram the playlist functionality in to the current media source, though maybe others have different opinions.

**Comment by Fenrirthviti** [comment]
I agree with @cg2121. The presentation of how files are added to VLC source is easy to understand, and should work fine for media source as well. Users actually prefer the way you add files to VLC source over media source in general, and the workflow there is simple.

Can you provide a screenshot of the playlist feature as implemented in this PR?

**Comment by cg2121** [comment]
Here's a picture of the new media source properties. It is basically the same as the VLC source.
Screenshot from 2019-04-10 20-04-48

**Comment by c3r1c3** [comment]
I also agree with @cg2121 and @Fenrirthviti about media source upgrades vs. a new media playlist source.

**Comment by cg2121** [comment]
Everything works great now. Testing and feedback would be greatly appreciated.

**Comment by DDRBoxman** [comment]
@cg2121 how hard would it be to add a text field in the player controls that shows the name of the current file being played?

**Comment by dodgepong** [comment]
Does the "Previous" button go back to the beginning of the current video file? I just want to make sure there's an easy/clear way for people to "restart" a media file.

**Comment by scrapyst** [comment]
One feature that i think it is important for media sources is the ability to enable audio monitor before its on PGM. If you are connected to a PA system you need the sound to play immediately

**Comment by cg2121** [comment]
Update:
I increased the performance by not relying on polling for everything in the control widget. I updated the code to use callbacks instead.

**Comment by zikaeroh** [comment]
I went and fixed the merge conflicts just to see if this stuff works, and it does. Is there anyway that this can be fixed up to make it in? I'd love to see this in OBS proper (so I don't have to maintain a fork).

**Comment by cg2121** [comment]
I have now rebased to master and applied clang formatting.

**Comment by Coestar** [comment]
I have run into an issue using scene stinger transitions with the latest version of this branch.  When the transition is triggered during a scene change, it will only fully play the transition video the first time after either OBS is freshly opened or after the transition settings have been opened and closed.  After that, the transition video will not play properly on subsequent scene changes.  A few frames can be seen, but the video abruptly stops after that.  Also, even during the first successful transition, random frames from the middle of the transition video seem to be shown before the transition video plays through normally.  This seems to happen after the video completes as well.  I have included examples and logs below.

OBS Studio 23.2.1
Transitions playing normally
------------------------------------
Clip: https://streamable.com/81nbz
Log: https://pastebin.com/jP1vYNS2

OBS Studio 23.2.1-52-g1a1bcbc6
Transitions not playing normally
------------------------------------
Clip: https://streamable.com/h7vk2
Log: https://pastebin.com/8YGkjcF5

Transition Video File
------------------------------------
https://www.dropbox.com/s/y5ge5wixf69wxwq/rock_transition_general_rc04.webm?dl=1

If there's anything else I can provide that would be helpful, please let me know.

**Comment by WizardCM** [comment]
@cg2121 Friendly reminder, this PR seems to have some merge conflicts due to recent merges.

**Comment by cg2121** [comment]
I've now rebased it to master.

**Comment by Baa14453** [comment]
I'd just like to add, the VLC source has always supported Subtitles in the source file if they are set as the default subtitle. Recently controls were added to enable and disable subtitles and also select the subtitle track:
image

Worth considering if your aim is to deprecate it eventually.

**Comment by WizardCM** [comment]
Friendly bump: this PR has new merge conflicts.

**Comment by jp9000** [comment]
Yes, we do need media controls in some form or another.  That's been true for ages.  However, I have a few issues with this pull request.  Firstly, there are way too many tangentially related changes in the pull request making it highly unpleasant to review.  They are all somewhat related to each other, yes, that much is true, and I can understand the motivation behind it, "well, I was going to change the media source to use playlists anyway, therefore it makes sense to just do it in this pull request and put everything together to reduce the workload", but the problem is that this just needlessly increases the size of the pull request and makes it more painful to review.  It does not make things more helpful to put it all in to a single pull request, and it would be more helpful to make each pull request more focused on one specific major change at a time, while trying to minimizing unrelated changes as much as possible.

Secondly, I'm not entirely sure how I feel about the placement and location of media controls.  It's probably already been stated, but I wonder if we need to have them in a different location, perhaps we should probably take in to consideration the source context menu pull request by DDRBoxman (https://github.com/obsproject/obs-studio/pull/1838), and whether we want media controls to be accessible that way.  (That pull request has also not necessarily been decided upon either I might add)

Back to the primary frustration I have with this pull request however: the fact that it adds media controls to applicable sources while also changing the media source to use playlists in the same pull request.  The playlist with the media source is something which we (or at least I) am not sure about how exactly we want to do yet.  We definitely want to reduce the necessity of the VLC source, but we have not really come to a consensus on how we want to do that yet.

So basically the media controls part of the pull request become put on hold because now we're sort of debating, "well, should we just use a playlist right off the bat, can we make it so the playlist is an option in the media source instead of necessarily being the default, *should* there be a playlist in the media source itself or should it be a new source", all of which we do not have consensus on and have disagreements over.  So basically this just ends up hurting the pull request because now we're stuck on the only-tangentially-related change in the PR.

So here is what I want you to do: I want you to make RFCs for both of those things, separately.  When an RFC is approved, then feel free to begin work on it so we can all come to a reasonable consensus on how this should be made.

In the future, please avoid combining multiple things in to the same pull request however, and if you ever unsure, feel free to ask about it or make an RFC and let's get it sorted.

Additionally, if you ever wonder even for the slightest moment "are these changes that we want or that will be agreed upon", don't start working on the code, instead make an RFC and let's get the idea sorted out first.

Communication is key before starting changes, that way you don't necessarily put a tremendous amount of time in to some work you do only to just have it declined because you either didn't necessarily have thorough discussion on how a change should be, or you combined multiple things in to the same pull request at once.  Perhaps I myself should have realized this sooner.  There's a lot of improvement that is needed all around, even for myself.  I feel like I should have realized or pointed this out sooner.  It's just difficult because I have so much going on at any given time.  It's a bit frustrating that I am unable to adequately spend significant time on every single thing sometimes.

**Comment by renerlemes** [comment]
How to use this version?

**Comment by Baa14453** [comment]
> How to use this version?

Download the builds here: https://github.com/obsproject/obs-studio/actions/runs/101066040
It's in testing so report feedback on this new PR here: https://github.com/obsproject/obs-studio/pull/2886

**Comment by fbosman** [comment]
Hi
I like these media-control, thank you!
However the timer seems to be wrong:
I add a mp3-source with a length of 1:45 and the controls see 3:00.
image

**Comment by dodgepong** [comment]
Can you upload the MP3, by any chance?

**Comment by fbosman** [comment]
Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 6 jun. 2020 om 20:36 heeft Ben Torell <notifications@github.com> het volgende geschreven:

﻿
Can you upload the MP3, by any chance?

**Comment by dodgepong** [comment]
If you tried to attach the MP3 to your email, it didn't get posted on Github. Try hosting it somewhere like Dropbox or Google Drive and link it here.

**Comment by fbosman** [comment]
The mp3: https://rkjohannesdedoper-my.sharepoint.com/:u:/g/personal/frans_jddoper_nl/EdUzUyWsBZ5LisbtaHCy1hEB3z-PK0ZcN_rzLNF75oT0LQ?e=5ix7h1

**Comment by dodgepong** [comment]
Interestingly, the OneDrive web player shows it as 3:01 as well, but playback ends after 1:45.

FFmpeg seems to think it's 3:01 too, but it's making an estimate (`Estimating duration from bitrate, this may be inaccurate`):
```
$ ffmpeg -i 10_SLOTLIED\ 01-45.mp3
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[mp3 @ 0x7fffc19ab4e0] Skipping 35 bytes of junk at 32.
[mp3 @ 0x7fffc19ab4e0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '10_SLOTLIED 01-45.mp3':
  Metadata:
    encoded_by      : Amadeus Pro
  Duration: 00:03:01.35, start: 0.000000, bitrate: 46 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 46 kb/s
```
I wonder if this got encoded strangely in a way that is giving FFmpeg problems. I wonder if we could fall back on the ID3 tag if FFmpeg gives this response?

From [this SuperUser post](https://stackoverflow.com/questions/10437750/how-to-get-the-real-actual-duration-of-an-mp3-file-vbr-or-cbr-server-side) I decided to try out `sox` (with `libsox-fmt-all`) and got this output:
```
$ sox 10_SLOTLIED\ 01-45.mp3 -n stat
sox WARN mp3-util: MAD lost sync
Samples read:           4660973
Length (seconds):    105.690998
Scaled by:         2147483647.0
Maximum amplitude:     1.000000
Minimum amplitude:    -1.000000
Midline amplitude:    -0.000000
Mean    norm:          0.225938
Mean    amplitude:     0.000191
RMS     amplitude:     0.298351
Maximum delta:         0.289874
Minimum delta:         0.000000
Mean    delta:         0.019937
RMS     delta:         0.027971
Rough   frequency:          658
Volume adjustment:        1.000
```
That is the right duration, though the `sox WARN mp3-util: MAD lost sync` message is curious. [According to this thread](https://sourceforge.net/p/sox/mailman/message/36349150/), "That means the mp3 decoder didn't find a frame sync code where it expected one.  This could be due to file corruption or simply a trailing ID3 tag." So that would indicate some sort of encoding problem.

I don't know if this is a problem exclusive to MP3 files, and I don't know if using `sox` is an appropriate replacement since I think it does a full decode of the file to get that information. Maybe a full decode is really not a big deal on modern systems, and worth ensuring proper durations. Perhaps we should go FFmpeg duration => Fallback to ID3 duration => Fallback to sox duration. Is that overkill?

**Comment by BenSa0112** [comment]
Hi, will this be added to official OBS Version?

**Comment by Fenrirthviti** [comment]
> Hi, will this be added to official OBS Version?

You can follow progress on this feature in a newer pull request here: https://github.com/obsproject/obs-studio/pull/2886

**Comment by PeterAkakpo** [comment]
with the playlist feature ,please don't forget to add the ability to skip to a particular playlist index. say PlayItem (5) to play the sixth item in the playlist

**Comment by PeterAkakpo** [comment]
I propose a mouse move preview on the trackbar to show the frame at the track bar mouse position

**Pull request closed without merging**
