### PR TITLE
libobs-metal: Add new Metal renderer.

### PR DESCRIPTION
**Pull request by mntone**
**This PR need #956.**

Add new Metal renderer for macOS. Metal is low level graphics API, and supports from OS X El Capitan. But, macOS Sierra only is avaiable because OS X El Capitan doesn't support [MTLPixelFormatDepth16Unorm](https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatdepth16unorm). In my computer its renderer is good performance in both default and studio mode.

Display Capture is not implemented. I try to copy data from IOSurface to MTLTexture. But, in this way, it was awful performance. I think new display capture for Metal, or something new.

I want to get feedback and advice of this renderer.

### CODE REVIEW

**Comment by jp9000** [comment]
Hi mntone, thank you for spending the time to write this, though could you specify why this renderer was implemented?  It should not technically have any performance improvements over OpenGL.

**Comment by RytoEX** [comment]
@mntone
Hi!  I just wanted to check in since we haven't heard from you in a while.  Could you please explain the benefits of this renderer over the OpenGL renderer?  Can you also explain why this is useful to have in OBS?  Thanks!

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by asquelt** [comment]
would that potentially fix https://obsproject.com/mantis/view.php?id=847 ?

**Comment by jp9000** [comment]
No -- that's a vsync-related issue.  I have a possible fix in the works for that particular issue which is unrelated to this.

**Comment by ROCKNROLLKID** [comment]
Don't know if this is still open for discussion, but doesn't low level apis, like Metal/Vulkan/Direct x12, also have a drastic reduction is CPU overhead? So wouldn't using Metal/Vulkan/Direct x12 allow OBS to consume less CPU while maintaining the same, or even better, performance?

**Comment by jp9000** [comment]
Not necessarily -- Metal/Vulkan/DX12 are designed to allow you to more effectively thread your graphics calls.  This mostly applies to triple-A game engines which render a lot of things at once with many transforms and in large batches; not so much simpler graphics programs.  It has less to do with consuming less CPU, and more to do with using that CPU and GPU more effectively across multiple threads for graphics-related purposes.

In traditional DirectX (up to version 11) and OpenGL, more than one thread cannot really use the graphics context at the same time.  In DirectX 12, Vulkan, and presumably Metal, you're able to do graphics processing on many threads at once rather than confining all graphics-related processing to a single thread.

OBS' rendering is not particularly complex, and does not require a heavy combination of CPU and GPU processing at the same time.  Most of the time it's just rendering squares to draw textures, where as a game is rendering complex meshes, animations, terrain, meanwhile processing things like physics and other such calculations related to the game.  For that reason, a single thread dedicate to graphics processing is more than enough, as the graphics thread is predominantly just fillrate; it does not do any particularly heavy CPU-related processing, nor does it need to draw multiple things at the same time.

For that reason, a DirectX12/Metal/Vulkan renderer for OBS doesn't really make sense.  I do need to write a capture method for Vulkan, but in terms of OBS' rendering backend, using these APIs would give no real benefit unless there was some specific feature in that API that would be useful specifically to what we're doing.  For example, if Metal provided a desktop capture method or something that you couldn't get otherwise.

Hopefully that made sense.  I'm still waiting to hear back from mntone.

**Comment by jp9000** [comment]
I am grateful that you spent so much time working on this, but I do not know why it was implemented.  I'm going to close it for now to clear up the pull request list, but please re-open this pull request when you have time to discuss this again.

**Comment by PatTheMav** [comment]
With macOS Mojave pushing people to use Metal (as Quartz now runs on Metal only and Mojave drops support for non-Metal compatible Macs) and OpenGL's drivers not being updated by Apple, this pull request looks like an important step to take. I guess that's why it's reopened? 👍🏻👍🏻

**Comment by Janisku7** [comment]
as all those options to come with Metal/Vulkan/DirectX12 come with other beneficts too in OBS for use.

**Comment by SirBryan** [comment]
@jp9000 (Jim), would switching to a Metal renderer be a faster fix to the low FPS issue in Studio Mode (see https://obsproject.com/mantis/view.php?id=847#c3154)?  At least for Sierra/High Sierra/Mojave?   

I might try building it to see...

**Comment by jp9000** [comment]
Deferring to the new branch for this.

**Pull request closed without merging**
