### PR TITLE
UI: Don't show native popup for YouTube auth message box

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

The native popup has the problem that it doesn't work for links, leaving us with an unclickable text where a link should be. Qt 6.6 has an option to disable the native dialog, so let's add this to make the link clickable again.

### Motivation and Context

With the native messagebox, the link is unclickable:
image

This PR restores the previous behavior: 
image

### How Has This Been Tested?

macOS 14
Previous behavior is back, the link is now clickable.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Bit of a hack but works on my machine: https://github.com/derrod/obs-studio/commit/4763b27d668eb21533cb4c3f359e856c0def13e9

**Comment by tw20160623** [comment]
Hello, can you help me cancel my subscription? thanks

Rodney ***@***.***> 於 2023年9月10日 週日 13:27 寫道：

**Comment by tw20160623** [comment]
Hello, could you help me cancel sending messages through email? thanks

W T ***@***.***> 於 2023年9月10日 週日 13:56 寫道：

**Comment by gxalpha** [comment]
@derrod Honestly that's just the better solution. Adjusted it a bit to retain the original attribute state just in case.

@tw20160623 you clicked "Subscribe" in the top right of the page, there is an unsubscribe button now. See this article for further information: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions. Please contact GitHub support if you need further help with that.

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
