### PR TITLE
Add piczel.tv server to OBS defaults

### PR DESCRIPTION
**Pull request by gburgwardt**

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please squash your commits.

**Comment by gburgwardt** [comment]
Apologies, not sure how I can go about doing that with gitlab's UI.

From [what I've read](https://blog.github.com/2016-04-01-squash-your-commits/) it looks like whoever merges it can squash while accepting the merge.

**Comment by RytoEX** [comment]
@gburgwardt 
Hi!  Yes, the maintainer can squash commits on merge, but we generally like to make pull requests as minimal-effort as possible.  Generally, it's a bad idea to use the GitHub web UI by itself to create pull requests, because you cannot edit commits and you end up with extra merge commits.

A few things:

1. What is Piczel.tv?
2. Use one commit to make this change instead of multiple commits.
3. Please read [this project's commit guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidlines), and format your commit message appropriately.

**Comment by gburgwardt** [comment]
Agreed, I can close this commit if you prefer. 

1. An art/games streaming site (to keep it short) - we compete with Picarto.tv, people keep stumbling over there not being an option in the obs server dropdown for us so figured I'd put in a pull request, and I've bungled it haha.

2. Web UI problems. I'll make a new commit, sorry about that.

3. Done, fwiw.

**Pull request closed without merging**
