### PR TITLE
plugins: Add reload file every N-ms text-freetype2

### PR DESCRIPTION
**Pull request by inflex**
In addition to existing modified-status reload options, this change
gives the ability to instead force the reloading of a text file
source every N-ms (from 100ms) rather than attempting to test for
the file-modified status.

Existing behaviour has been preserved by default.  Feature has to
be explicitly enabled by selecting the 'Load on Interval' flag.

Additional translations required for LoadInterval and
LoadOnInterval text.

Usage case:
   During recording of electronics work, we it's often required to include multimeter data on screen which typically updates at 2~10Hz rate, with the default 1Hz update rate the faster multimeter data transitions can be missed entirely (ie, recording will show [say] 0.00V... 0.00V,  but there was a 3.42V reading at the 500ms point that gets missed).  

  1 second updates do at first seem timely enough and reasonable initially but empirically we've found that too many things done seem to happen within 200~600ms range and are missed.

   Example of the usage in OBS with YouTube - https://youtu.be/wSpVDkX7zro?t=14m21s

### CODE REVIEW

**Comment by VodBox** [comment]
Not necessarily something you'd have to implement, but an idea could be to have load_interval be invisible, and assign a modified callback to the load_on_interval bool to reveal load_interval when it's enabled. That way, you're not shown an option unless it'll actually do something.

obs-ffmpeg-source has examples of this, with it's [callback for is_local_file](https://github.com/jp9000/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L121) that reveals and hides option depend on local or remote media.

Purely just a suggestion though, one extra int wouldn't add too much to the UI as is, so may be unnecessary.

**Comment by inflex** [comment]
@VodBox perfectly reasonable suggestion, I was contemplating on it, just wasn't quite sure how to implement it; I'll look at the suggested source.

**Comment by inflex** [comment]
Sorry about all the post-PR-submission commits.

**Comment by jp9000** [comment]
Please include the use case.

**Comment by inflex** [comment]
Any ideas/progress on this PR?  Just thought I'd bubble it up.

**Comment by jp9000** [comment]
I understand you may personally need things like this -- but I am hesitant to try to fill every single niche edge case on the main repository.

**Comment by inflex** [comment]
All good. If it ever expands out of niche at least it exists pre-prepared.

**Pull request closed without merging**
