### PR TITLE
UI: Disable Multitrack Video by default

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Disable Multitrack Video (Twitch Enhanced Broadcasting) by default.

### Motivation and Context

Noticed in testing that this was on by default in all cases. This is a behavior change that would suddenly and without warning change streaming settings for any users configured to stream to Twitch, such as increasing the amount of bandwidth used.

### How Has This Been Tested?

Built and ran locally on Windows 11.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by derrod — APPROVED** [review]
Migration and other stuff (data usage consent, etc.) needs to be figured out before we set this as default.

**Comment by Fenrirthviti** [comment]
Agree on this change. This *has* to be an explicit opt-in from a legal standpoint anyway.

**Review by Fenrirthviti — APPROVED** [review]

**Comment by Sean-Der** [comment]
This commit also fixes all other outputs. Currently in master if I try to stream I get

image


When I cherry-pick this commit it works again.

**Comment by RytoEX** [comment]
> This commit also fixes all other outputs. Currently in master if I try to stream I get

You can just manually disable Enhanced Broadcasting in Settings -> Stream which should have the same effect in the meantime.

**Pull request merged**
