### PR TITLE
UI: Use OBS locale for YouTube categories API

### PR DESCRIPTION
**Pull request by derrod**
### Description

If a language or country is not set in the YouTube channel data, we should fall back to the OBS locale rather than `en-US`.

### Motivation and Context

YouTube Category names were not locallised unless the channel had a default language assigned (apparently automatically by YouTube). Furthermore the country or region requires manual configuration by the user otherwise it will also be unset.

### How Has This Been Tested?

Set OBS language to something other than `en-XX` and verified that the categories now are in that locale's langauge.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Converted to draft since there are some edge cases in OBS' current locales like `kab-KAB` or `bem-ZM` that will result in an API error about an unsupported language. In those cases we should fall back to en-US again.

**Comment by derrod** [comment]
Alright changed this to use `QLocale().name()` instead to simplify things a little (OBS sets the Qt default locale on startup). Additionally the code now will also fall back to `en-US` if YouTube returns an `unsupported(Language|Region)Code` or `invalid(Language|Region)Code` error.

**Review by Gol-D-Ace — APPROVED** [review]
Functionality wise this is looking good here.
My channel is without a set locale and categories use the lang
Screenshot_20210831-193007-218
Screenshot_20210831-193103-712
uage set in OBS.

**Comment by derrod** [comment]
Something to note: Certain categories are only available with some regions. For instance "Nonprofits & Activism" will not be shown for `en-GB` or `de-DE` but only for `en-US`. With the current implementation that issue is somewhat bypassed as long as the channel does not have any region set. But if it does (which I suspect might be the case for #5226) then categories may be missing, even though they are available on the YouTube website.

**Comment by derrod** [comment]
In this latest iteration I've removed the language and country parameters entirely and hardcoded the "US" region.

For the full explanation, here's the code comment I wrote:
```cpp
	/*
	* All OBS locale regions aside from "US" are missing category id 29
	* ("Nonprofits & Activism"), but it is still available to channels
	* set to those regions via the YouTube Studio website.
	* To work around this inconsistency with the API all locales will
	* use the "US" region and only set the language part for localisation.
	* It is worth noting that none of the regions available on YouTube
	* feature any category not also available to the "US" region.
	*/
```

Using the language from YouTube didn't make sense to me, since it appears to be whatever YouTube automatically determines based on your channel description. But respecting the user's choice makes more sense than relying on some automagic.

**Pull request merged**
