### PR TITLE
obs-text, text-freetype2: Change default font size to 256

### PR DESCRIPTION
**Pull request by cg2121**

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Personally i dont feel this should be merged without better texture handling. This will cause many sentence length text fields to just not render with no reasonable way for the user to figure out what is wrong.

**Comment by kkartaltepe** [comment]
Went back and re-tested master and I take that back, its probably pretty safe. On my system with 16k textures I can do ~400 words or 2k characters on 256pt. That is probably fine for almost every usage of raw text source I can think of.

Even on my low power intel machine i can get 16k and a browsing of https://people.freedesktop.org/~imirkin/glxinfo/#v=Mesa%2017.1.0 suggests 8k is a pretty reasonable minimum expectation. and 200 words/1k characters seems acceptable for me.

**Comment by jp9000** [comment]
I want to ensure backward/forward compatibility with this one.  If you change the default and someone was using the default, then suddenly their text is going to be larger when they update.

**Comment by cg2121** [comment]
Yeah, backwards compatibility doesn't quite work with this after some testing.

**Comment by WizardCM** [comment]
Oh damn, that's.. a bummer. Maybe an update in a version in-between where it writes the default to the saved value? I'm actually not sure what a good solution would be.

**Comment by cg2121** [comment]
This can be merged after #2073 is merged.

**Comment by cg2121** [comment]
Closing again until a migration system is implemented.

**Comment by Xaymar** [comment]
Regarding config migration, in Stream Effects and FFmpeg Encoders I use the plugins version to mark the configuration, and call a function that goes through the necessary transformations for each new version. Since these two plugins are built with libobs, it could look like this:

```
static void convert_config(obs_data_t* data) {
    uint64_t version = (uint64_t)obs_data_get_int(data, "version");
    switch (version) {
        case 0: // Unversioned or user modified.
            if (!obs_data_has_user_value(data, "keyhere"))
                obs_data_set_int(data, "keyhere", 36);
        // more cases... and then the final break
            break;
    }
    obs_data_set_int(data, "version", LIBOBS_API_VER);
}

// somewhere in update or load
convert_config(data);
```

This setup provides an easy way to progress through version migrations, while allowing certain freedom to change things as long as a new libobs version is released.

**Pull request closed without merging**
