### PR TITLE
Add display capture via Windows Graphics Capture

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Add Windows Graphics Capture option to Display Capture on Windows.

### Motivation and Context
WGC can capture desktop across adapters, and seems to hitch less than DXGI capture somehow.

### How Has This Been Tested?
- Verified DXGI/WGC and monitor switches.
- Tested monitor switches via source toolbar for DXGI and WGC.
- WGC rebuilds fine after forced device loss.
- WGC window capture continues to work correctly.
- Yellow border is disabled on insider build when compiled with insider SDK.
- Desktop PC captures display connected to secondary GPU.
- (Externally tested) Laptop captures display connected to secondary GPU.
- (Externally tested) WGC hitches less than DXGI.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
> (Externally tested) DXGI hitches less than DXGI.
Typo?

**Comment by jpark37** [comment]
> > (Externally tested) DXGI hitches less than DXGI.
> 
> Typo?

Fixed.

**Comment by WizardCM** [comment]
I have tested this change on both my Surface Book 2 (Intel / NVIDIA dual-GPU, single monitor) and my primary gaming machine (NVIDIA, quad-display setup) and everything works perfectly. Yellow border is correctly disabled on Insider builds.

I can confirm that the numbering of displays is different between DXGI & WGC - but WGC and GDI match Windows Settings, so I think it's fine.

Thank you thank you thank you for working on this, it'll solve so many issues for laptop users. We can work on adding a new 'Auto' option for laptops once border removal is a little more standard. In the meantime, maybe a "(recommended for laptops)" in the Method dropdown would be useful?

**Comment by henke37** [comment]
I don't see any code to decide when to use this new capture method. Are there any situations where this should/shouldn't be the default?

**Comment by WizardCM** [comment]
> I don't see any code to decide when to use this new capture method. Are there any situations where this should/shouldn't be the default?

At the moment - anyone who isn't on a laptop shouldn't be using it. WGC still has the yellow capture border, including for full-desktop, and it still enables software cursor.

**Comment by jpark37** [comment]
Updated and shortened the labels a bit.

**Comment by energizerfellow** [comment]
> Thank you thank you thank you for working on this, it'll solve so many issues for laptop users. We can work on adding a new 'Auto' option for laptops once border removal is a little more standard. In the meantime, maybe a "(recommended for laptops)" in the Method dropdown would be useful?

I agree there needs to be a "Auto" or "Default" option in the pulldown that automatically selects WGC if >1 GPUs are detected on 19H1+. This should also be the default for maximum out of the box user experience on laptops and users plugging monitors into motherboard video in combination with a discrete GPU (quite common, sadly...).

As for the "(recommended for laptops)", I don't think that reads well and is actually more confusing for the user. I'd have a 3rd menu option with a dynamic label of "Default ([selected method])" where Default dynamically changes to WGC if >1 GPUs are detected on 19H1+ or any number of GPUs for 21H1+ (or whatever build of Windows this goes live in).

I'd also like to see a checkbox option like "Enable capture security warning border (available on Windows 10 19H1 and above)" that's both checked and greyed out on 19H1 - 21H1, then changeable and unchecked for 21H1+. A mouseover tooltip noting the API-level restriction of forced-enabled border on 19H1-21H1 would be recommended here as well.

I know there's a (very, very...) vocal minority who rail about the yellow border, but Microsoft put it there and enabled it by default for very good security-related reasons. Commercial and academic users of OBS would very likely like to enable the border when they push out configs.  Window Capture should also be updated accordingly. Given traffic we see in the support Discord, it seems to be a bit under 10% of users who have issue with the yellow capture border relative to the large number using WGC for things like Chrome capture.

**Comment by jp9000** [comment]
> I agree there needs to be a "Auto" or "Default" option in the pulldown that automatically selects WGC if >1 GPUs are detected on 19H1+.

I'd prefer it detect whether it's a laptop rather than detect multiple GPUs. This is primarily a laptop problem.

**Comment by energizerfellow** [comment]
> I'd prefer it detect whether it's a laptop with multiple GPUs rather than just detect multiple GPUs. This is primarily a laptop problem.

Is is even possible to detect a laptop at a technical level in Windows?

True multiple discrete GPU PCs are a "1% of the 1%" situation in the modern era, so there's basically a 99% chance that if there's >1 GPU, it's a laptop or all-in-one PC.

The multiple GPU + display capture situation is even more fun in the era of Thunderbolt as the mapping of which GPU to which display is effectively a random number generator.

**Comment by dodgepong** [comment]
> Is is even possible to detect a laptop at a technical level in Windows?

You can detect if a GPU is a mobile GPU.

**Comment by mufunyo** [comment]
> Is is even possible to detect a laptop at a technical level in Windows?

Generally speaking, "If it has a battery, it's a laptop" is probably an acceptable axiom. A very very tiny amount of users might have a UPS connected to their desktop PC which might cause it to get incorrectly detected as a laptop.

**Comment by energizerfellow** [comment]
> You can detect if a GPU is a mobile GPU.

All-in-one desktop PCs using mobile hardware are very much a thing, especially in Apple land. HP in particular seems to have a thing for them. NUC-style mini PCs with dGPUs to go with the iGPU are increasingly a thing too (and use mobile hardware SKUs...).

> Generally speaking, "If it has a battery, it's a laptop" is probably an acceptable axiom. A very very tiny amount of users might have a UPS connected to their desktop PC which might cause it to get incorrectly detected as a laptop.

The USB connection on my APC SmartUPS shows up as a laptop battery in Windows, as just one example.

**Comment by mufunyo** [comment]
> The USB connection on my APC SmartUPS shows up as a laptop battery in Windows, as just one example.

Yeah, that's what I was referring to in my "very very tiny amount of users" example. :p

**Comment by energizerfellow** [comment]
> > The USB connection on my APC SmartUPS shows up as a laptop battery in Windows, as just one example.
> 
> Yeah, that's what I was referring to in my "very very tiny amount of users" example. :p

That said, the people who do legitimately have something like 2x+ RTX 30-series GPUs in their PC are also the users most likely to have an external UPS (that's reporting as a battery in Windows). You'd be looking at a Venn diagram of two overlapping circles.

Also remember that both SLI and CrossFire are effectively dead and gone at this point.

Speaking of, anybody test this on an actual SLI/CrossFire setup yet?

**Comment by henke37** [comment]
I think the correct logic would be as simple as "is the adapter OBS is running on different from the one being in charge of the monitor being captured", no?

**Comment by jp9000** [comment]
> I think the correct logic would be as simple as "is the adapter OBS is running on different from the one being in charge of the monitor being captured", no?

Oh, yea.

**Comment by jpark37** [comment]
Added an Automatic setting to select WGC if the HMONITOR is not in the DXGI output enumeration for the device. Seems to work on my two-GPU PC with monitors attached separately.

Also got rid of the double monitor list, show/hide nonsense. Just enumerate all monitors always.

**Comment by exeldro** [comment]
The merge is missing documentation changes

**Comment by jpark37** [comment]
> The merge is missing documentation changes

Can you be more specific? I don't think we have documentation for individual plugins. Did something specific rot?

**Comment by exeldro** [comment]
sorry commented on the wrong PR

**Comment by Awesome38** [comment]
Duplicate of #[Stripchat ](https://stripchat.com)

**Comment by RytoEX** [comment]
> 
> 
> I think the correct logic would be as simple as "is the adapter OBS is running on different from the one being in charge of the monitor being captured", no?

Unfortunately, the [test suggested above](https://github.com/obsproject/obs-studio/pull/4140#issuecomment-767894317) does not work on laptops with a single display.

If Display Capture is set to Auto, it will always select DXGI because the display is enumerated on whichever GPU OBS is set to run on.  See logs attached at the end of this comment for examples of running OBS on my iGPU (Intel HD 630) versus my dGPU (NVIDIA GeForce GTX 1060).

After some discussion with @WizardCM and @jpark37 , we think the best way to automatically detect the vast majority of laptops is to check if the GPU adapter count is greater than 1 _and_ use [Win32 GetSystemPowerStatus](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getsystempowerstatus) to check if a system battery exists (BatteryFlag, see https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status).  This should allow us to catch laptops that cannot use DXGI Display Capture when running on the dGPU.

[2021-03-11 04-04-52.txt](https://github.com/obsproject/obs-studio/files/6122163/2021-03-11.04-04-52.txt)
[2021-03-11 04-10-17.txt](https://github.com/obsproject/obs-studio/files/6122164/2021-03-11.04-10-17.txt)

**Comment by wangshaohui1314** [comment]
@jpark37   Is this an incorrect index ?

**Comment by jpark37** [comment]
Seems fine to me. Index 0 is METHOD_DXGI. Index 1 is METHOD_WGC. If WGC is not supported, I want to disable WGC. Is the behavior wrong?

**Comment by exeldro** [comment]
It is wrong, index 0 is AUTO, index 1 is DXGI, index 2 is WGC
Just tested it in my debug environment to confirm

**Comment by jpark37** [comment]
When did METHOD_AUTO sneak into the image? :P

Should be an easy fix.

**Comment by SekiBetu** [comment]
finally!! the black screen issue fixed!! nice job!! 🎉

**Pull request merged**
