### PR TITLE
CI: Update deps to 2024-08-08 release

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Notable changes:
 * deps.ffmpeg: Enable Media Foundation
 * deps.ffmpeg: Update nv-codec to 12.2.72.0
 * deps.macos: Use correct CMake vars for libajantv2
 * deps.macos: Add SIMD Everywhere to macOS deps
 * deps.windows: Add SIMD Everywhere to Windows deps
 * deps.windows: Update VPL to v2.12.0

### Motivation and Context

Unblock:
* #10902
* #11060
* #10961

### How Has This Been Tested?

I have not done full tests with OBS Studio against these deps.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
> CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
    Could NOT find FFnvcodec: Found unsuitable version "12.2", required range
    is "12.0.0.0...<12.2.0.0" (found

Also update the required range to include FFnvcodec 12.2 in a separate commit.

**Comment by derrod** [comment]
> Also update the required range to include FFnvcodec 12.2 in a separate commit.

That won't work because of the backwards compatibility hack, as previously mentioned #10536 is required for the new version.

**Comment by RytoEX** [comment]
> > Also update the required range to include FFnvcodec 12.2 in a separate commit.
> 
> That won't work because of the backwards compatibility hack, as previously mentioned #10536 is required for the new version.

I'm seeing that now, which is _very_ unfortunate, because that makes this deps update a breaking change that I cannot simply land to unblock those PRs.

**Review by derrod — APPROVED** [review]

**Comment by RytoEX** [comment]
Given that these deps are built with newer MSVC, the SVT-AV1 issue(s) _may_ be resolved here as well.

**Pull request merged**
