### PR TITLE
rtmp-services: Update Mixcloud

### PR DESCRIPTION
**Pull request by matclayton**
### Description

Updating Mixcloud Service settings to be more compatible

### Motivation and Context

We're seeing a number of users repeatedly using settings which cause problems, so this addresses those and provides better defaults

### How Has This Been Tested?

Followed convention, these are also known best configurations on Mixcloud (I work there and lead that team)

### Types of changes

Amending Mixcloud services configuration to be more compatible with our infrastructure

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [ ] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
> these are also known best configurations on Mixcloud

To be clear, these changes will restrict users such that they will _only_ be able to stream at the listed resolutions and framerate (unless they explicitly disable the restriction on OBS's side). Is that the goal?

**Comment by matclayton** [comment]
Yes that is the goal. Technically we can ingest 1080p, but given we transcode down its a waste of resources for all involved. Also 60fps causes cpu throttling and buffering of the live show, so this is the really critical one to merge.

Just to confirm though, if a user has 1080p setup by default then chooses Mixcloud as a destination, will this change them to 720p, or will it throw an error until they correct the settings?

**Comment by matclayton** [comment]
I've just confirmed how OBS handles this and I can confirm this is the behaviour we're after.

**Comment by matclayton** [comment]
Thanks for merging! Has it also been deployed to the web servers? I was just checking this, and it didn't appear to take effect on a fresh install.

**Pull request merged**
