### PR TITLE
UI: Add mute checkbox to Advanced Audio Properties

### PR DESCRIPTION
**Pull request by ruggi99**
### Motivation and Context

In my context I want to know if a specific source is muted even if it isn't showing in the final mix. This because I have scenes where media file start automatically and I want to know if the source is muted or not before making it visible.
With Studio mode enabled I can't get what I want.

### How Has This Been Tested?

Tested on Windows 10 Pro. Downloaded artifact form Actions on my fork.
Muting / unmuting either from Audio Mixer or Advanced Audio Properties works well.

I don't know if this should be documented, please let me now.

Attached screenshot below
Cattura

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I'd vote this should use the same speaker/mute icon from the Audio Mixer. Outside of that, I'm not against this idea - I just worry about how much wider this dialog becomes.

**Comment by ruggi99** [comment]
I agree with you @WizardCM but for me this option is also important because the advanced audio properties can be left open and therefore I have an overview of the audio sources.

Look at how much space the Status column takes but I don't know why. Don't know if that space exists only in my case.

I would like to hear some opinions on this

**Comment by mufunyo** [comment]
> Look at how much space the Status column takes but I don't know why. Don't know if that space exists only in my case.

I would guess that is because some translations have longer words than others, and it the next needs to fit in all localisations.

**Comment by ruggi99** [comment]
> I would guess that is because some translations have longer words than others, and the next needs to fit in all localisations.

Yes, I see. I thought that columns would automatically take up the necessary space in the current translation

**Pull request closed without merging**
