### PR TITLE
Add Superpeer to streaming services list

### PR DESCRIPTION
**Pull request by fatihacet**
[Superpeer](https://superpeer.com) allows creators to do paid live streams with their audience

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please properly fill out the PR template. In the future, do not delete it.

**Comment by fatihacet** [comment]
@Fenrirthviti sorry, I thought it's not relevant to my PR since it's just a simple service config change.

Let me know if you want me to fill it anyways.

Thanks!

**Comment by Fenrirthviti** [comment]
The template includes directions for service updates, which this PR is not conforming to.

**Comment by derrod** [comment]
Also consult the service submission guidelines: https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines

**Pull request closed without merging**
