### PR TITLE
Set error message for NVENC, AMF, and QSV with P216/P416

### LINKED ISSUE #8665: P416 color format is not compatible with HDR
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

29.1.0-beta1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/Fu8UvOyHJM0v9Gvf

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Normal output 4:4:4 16bit/10bit video

### Current Behavior

"OBS does not support 8bit output of Rec.2100"

### Steps to Reproduce

1. Settings > Adanced > Color Format > P416 (I would prefer to use P410, but OBS does not have this. As far as I know, NVENC will automatically convert P416 to P410)
2. Settings > Adanced > Color Space > Rec.2100
3. Add Display Capture Source
4. Start Recoding

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

If P216 or P416 color formats are selected with NVENC, AMF, or QSV, these color formats were not explicitly handled, so the switch statements would end up in the default case. If the user had also selected a Rec. 2100 color space, this would result in the strange error message:
> OBS does not support 8-bit output of Rec. 2100.

This message is confusing and does not correctly reflect the chosen settings. Let's explicitly handle the P216/P416 cases and provide a more accurate error message.

----

An alternative wording/approach such as with #8811 and #8812 could be taken instead, if preferred.

### Motivation and Context

Fixes #8665

### How Has This Been Tested?

Tested locally on Windows 10 with NVENC.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Added a commit to also handle these cases in AMF. If we'd prefer to split that into a separate PR or change the implementation, that can be done.

**Comment by RytoEX** [comment]
Added a commit to also handle these cases for QSV.

**Comment by gxalpha** [comment]
> An alternative wording/approach such as with https://github.com/obsproject/obs-studio/pull/8811 and https://github.com/obsproject/obs-studio/pull/8812 could be taken instead, if preferred.

I have no particular preference on the wording here vs in #8812 but I think they should at least match, so if this wording here is preferred I'd go ahead and adjust #8812 to match.

**Comment by RytoEX** [comment]
> > An alternative wording/approach such as with #8811 and #8812 could be taken instead, if preferred.
> 
> I have no particular preference on the wording here vs in #8812 but I think they should at least match, so if this wording here is preferred I'd go ahead and adjust #8812 to match.

For my part, this was the original code draft I'd had, so I went with it because it was quickest for me to toss into a PR yesterday. I also couldn't determine if "high-precision color formats" was a universally understood term or if we'd made it up, so I kept my original wording pending further discussion.

**Review by notr1ch — APPROVED** [review]

**Comment by RytoEX** [comment]
Off-thread discussion indicates that this is good to merge as-is. We can adjust or align error messages later.

**Pull request merged**
