### PR TITLE
Fix Codec Compatibilty Check

### PR DESCRIPTION
**Pull request by derrod**
### Description

Unfortunately FFmpeg's check is too unreliable, so just use a hardcoded list instead *sigh*.

### Motivation and Context

Don't want people to be able to select invalid combnations (e.g. AV1 in MOV).

### How Has This Been Tested?

Checked that correct codecs are now marked as invalid.

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Well, at least it'll be easy to enable AV1 for MPEG-TS once that's in... 😅

**Comment by derrod** [comment]
On second thought, this should fall back to the ffmpeg check for codecs that we don't ship to avoid breaking some third-party plugins that add additional encoders.

> Not necessarily asking for this to be solved in this PR, but would it make sense to think about consolidating this with the code in obs-ffmpeg that handles some of this?

Not sure what you're referring to.

**Comment by Conan-Kudo** [comment]
> > Not necessarily asking for this to be solved in this PR, but would it make sense to think about consolidating this with the code in obs-ffmpeg that handles some of this?
> 
> Not sure what you're referring to.

There are codec filters in obs-ffmpeg-hls-mux.c and obs-ffmpeg-mpegts.c as part of obs-ffmpeg.

**Comment by energizerfellow** [comment]
Neither [MPEG-TS](https://www.iso.org/standard/83239.html) nor [HLS](https://developer.apple.com/documentation/http_live_streaming/http_live_streaming_hls_authoring_specification_for_apple_devices) appear to support Opus in their spec sheets, so Opus should be probably be removed for those.

While TS doesn't support LPCM, [M2TS supports LPCM (and AAC)](https://exiftool.org/TagNames/M2TS.html) due to Blu-ray (more info on [HD](http://www.disc-group.com/wp-content/uploads/2011/05/Blu-Ray-4-LogicalAudioVisual-867KB.pdf) and [UHD](https://docplayer.net/48882577-White-paper-blu-ray-disc-read-only-format-ultra-hd-blu-ray-audio-visual-application-format-specifications-for-bd-rom-version-3.html)) and can be created by FFmpeg. Adding M2TS should probably be a separate PR, however.

**Comment by derrod** [comment]
Seems like FFmpeg is perfectly happy to mux Opus into HLS but I suspect at least Apple devices won't support that, so I'll remove it.

**Comment by norihiro** [comment]
Nitpick: The commit description has 73 characters in a line. Could you fix it?

**Comment by Conan-Kudo** [comment]
Shouldn't `hevc` be filtered out if `ENABLE_HEVC` is disabled?

**Comment by derrod** [comment]
> Shouldn't `hevc` be filtered out if `ENABLE_HEVC` is disabled?

Doesn't really matter here and would just make things uglier.

**Pull request merged**
