### PR TITLE
obs-text: Speedup text updates

### PR DESCRIPTION
**Pull request by Meerkov**
Description
Speedup TextSource update from file.

Motivation and Context
Simplify complex code, and provides speedup for endusers.

How Has This Been Tested?
Compiled and tested. No noticeable problems.

Types of changes
Code cleanup.

Checklist:
 [X]  My code has been run through clang-format.
 [X]  I have read the contributing document.
 [X]  My code is not on the master branch.
 [X ]  The code has been tested.
 [X]  All commit messages are properly formatted and commits squashed where appropriate.
 [X]  I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
I'm also very interested in speeding-up the text but unfortunately there is a scenario that the plugin failed to update it's text.

1. At time 1.1s, the file is updated. The mtime becomes `1.1` but rounded to `1`.
2. At time 1.4s, the plugin detects the change, load the file and set `file_timestamp` = `1`.
3. At time 1.8s, the file is updated again. The mtime is `1.8` but rounded to `1`.
4. At time 2.4s, which is just 1s later, the plugin check the mtime and will see mtime is not changed.

We should also check the time in resolution less than 1s.

**Comment by kkartaltepe** [comment]
Much like #1192 and #1566 there isnt a ton of desire to increase the polling rate upstream.

You can still work around this on a per source basis via scripts like https://gist.github.com/kkartaltepe/861b02882056b464bfc3e0b329f2f174 or by recompiling a source. I think a change actually enabling directory watching in windows would be more likely to get in than polling (maybe).

**Comment by Meerkov** [comment]
Currently if your file changes every second, it will still read the file once per second. However the first read is delayed by one second for no reason.

This change doesn't change the number of polls, but rather fixes the 1 second delay *after* the poll.

**Comment by kkartaltepe** [comment]
Currently the design is intended behavior per #955

**Comment by Meerkov** [comment]
Respectfully, I disagree that this is working as intended. #955 should never have been marked fixed, as the solution there does not solve the bug in question. See the similar issue in #3012. OBS does not support polling text more than 1x per second, so it's impossible that #955 solves the problem of changing the file twice in the same second.

**Comment by kkartaltepe** [comment]
> OBS does not support polling text more than 1x per second, so it's impossible that #955 solves the problem of changing the file twice in the same second.

It solves the issue of not seeing the most recent version of a file because obs does not poll more frequently than 1x per second. (Since the PR was written and tested by the person with the issue its hard to say it doesnt fix the issue)

Considering the timeline for the issue the previous PR fixes:
0.0) write(1)
0.5) OBS ticks, reads the file, (old sets Update, proposal displays "1")
0.9) write(2)
1.5) OBS ticks (old reads sets "2", proposal cannot detect change due to 1s resolution on os_stat)

**Comment by Meerkov** [comment]
Sure, I see what you are saying. The previous patch was added as a fix to the precision issue of using mtime.

So then use mtime_ns. The previous fix is the wrong fix to solve that problem.

**Comment by kkartaltepe** [comment]
Feel free to use higher resolution timetstamps to avoid this issue, I dont think anyone is particularly beholden to using platform agnostic code in gdi-text.

Yes we are also aware of the timestamp resolution on FAT32. But no one has complained about that unlike the issue on NTFS where we received a PR for the fix. It was even the first comment on this PR about how it caused a regression in that behavior.

**Comment by Meerkov** [comment]
Sure, I'm happy to withdraw this pull request given it would cause a regression. Larger fixes need to be in place before this hack can be removed.

**Pull request closed without merging**
