### PR TITLE
libobs-d3d11: Do not allow Alt+Enter interception

### PR DESCRIPTION
**Pull request by SuslikV**
Prevent DXGI from responding to an Alt+Enter sequence.

Fixes: https://obsproject.com/mantis/view.php?id=1200

### CODE REVIEW

**Comment by SuslikV** [comment]
I can say that from the web interface you can do only limited amount of github moves. Interesting that rebase and commits edit during merge operations leads to fake results - it is not visible original style and mistakes of the programmer. It reduces number of steps that were performed to went to the final result - and this changes price of the work, and cast shadow to amount of work that was done. Just my thoughts about everything.

**Comment by jp9000** [comment]
I modified the commit message and comment slightly just to be a bit more clear.  Merging shortly.

**Comment by jp9000** [comment]
(Also make sure to squish your commits in the future)

**Comment by SuslikV** [comment]
It's my style. I can do mistakes and be rough.

**Pull request closed without merging**
