### PR TITLE
UI: Remove "Return" hotkey for renaming source and scene on macOS

### LINKED ISSUE #3044: Can't Rename Scenes After Creating Them
When I click the '+' button on the bottom of the Scenes box and Type a Name for the Scene, then add my sources to the scene, then later decide I want to use a different name for the scene, I highlight the scene name and right click and select Rename from the popup menu.  The text does become editable and I type the new name and press the return key.  At that point the name goes back to the original name and is not renamed as it should have been.  The only thing I can do to get around this is to recreate the entire scene using the correct name in the first place and then delete the old one I no longer need.

I only have 1 Scene Collection
Using MacOS Catalina 10.15.5 - All Updates
Mackbook Pro (2017 - 15Inch - 3.1 Ghz Quad Core i7 - 16GB Ram)
OBS Studio 25.0.8 (64-Bit) - Downloaded Main Installer
VLC 3.0.10 - 64 Bit
Latest Version of Final Cut Pro

### PR DESCRIPTION
**Pull request by mtippett**
Fixes #3044.  Existing behavior hooks enter to always enter the "EditSceneName" or matching Source entry.

Confirmed with @admshao that this is likely an error and is fine to be removed unless there is UI guidelines that indicate otherwise.

### CODE REVIEW

**Comment by WizardCM** [comment]
Please fill in the PR template.

**Comment by unknowndomain** [comment]
As a macOS use I strongly object to this removal as a solution to fixing a bug. 

I'm not sure that the HIG should always be the golden reference as to the only way to do things. 

Ever place you can rename something in macOS Finder being the primary example, but there are others. You can navigate up and down to select a file then press enter to edit and enter to save.

**Comment by mtippett** [comment]
@unknowndomain I agree.  I could only find "finder" as the example of an inline edit, which I'm assuming is likely historic rather than best practice.   In terms of how obs-studio has implemented the hooks, the only real way to remove the existing broken behavior is to unhook the "Return" hotkey while editing and then rehooking it after the change has been made.

Open for other suggestions.

**Comment by unknowndomain** [comment]
There is already a work around, press command and enter, not ideal but it works.

Other products do have this behaviour, off the top of my head. Final Cut Pro X

Is the solution to this not to track whether the editing is happening right now and to disable new editing when enter is pressed using some kind of variable like 'alreadyEditing'.

**Comment by unknowndomain** [comment]
Examples:
- Final Cut Pro X (Projects + Videos Browser)
- Notes (Sidebar)
- Calendar (Sidebar)
- Contacts (Sidebar)
- Font Book (Sidebar)
- Keynote (Text boxes)

I do believe this kind of interface should follow this pattern.

**Comment by mtippett** [comment]
I'll need to dive back into the code and explore a bit more.  The hook in window-basic-main.cpp takes the `Return` key for everything.   There might be some approaches with QT that will allow for ignoring the Hotkey event through an event handler.  I'll look into it a bit more over the next couple of days.

**Comment by unknowndomain** [comment]
Whats odd is this behaviour works fine within Windows 10.

**Comment by RytoEX** [comment]
To be clear, is this an issue with a Qt shortcut key causing an edit event to fire before saving the new item name and _not_ an issue with OBS hotkeys?  The use of the word "hotkeys" had me wanting clarity.  Has anyone checked the Qt issue queue to see if this is a known issue in Qt itself for QAction shortcuts?

> Whats odd is this behaviour works fine within Windows 10.
@unknowndomain Actually, on Windows 10, hitting the F2 key on a scene in the scene list before confirming the name change will revert it back to its original name.  The same behavior does not occur on sources with the F2 key, likely because it has a lot of custom event handling.

**Comment by unknowndomain** [comment]
To be clear @RytoEX I meant that it has the same OS matching rename hotkey

**Comment by mtippett** [comment]
@RytoEX to allow me to dig deeper into this, do you have any pointers to the event handling code?  New to QT and obs-studio but willing to take this to the end.  However, I'm happy to keep digging myself.  I'll keep the PR open and provide updates on this (and clean up the PR structure).

**Comment by PatTheMav** [comment]
I'd guess it usually works because "rename" is not a global event, but an event available for the currently selected item (e.g. for the examples @unknowndomain mentioned, renaming is available in the context menu of a selected sidebar item, but not a global action).

Such context-based event handlers can of course switch their action based on state, so if the item is in the state "editing" the enter key will result in a different event. If that event handling is currently done globally for the whole window that might make things messy of course.

**Comment by unknowndomain** [comment]
I would say that this feels like something that is one of the disadvantages of Qt and macOS getting further and further away from having anything like Native UI support.

**Comment by PatTheMav** [comment]
Qt actually has a subset of functionality that uses only native controls, but it's somewhat limited last I checked. I don't see this as an issue with Qt and more an issue of architecting the functionality just right.

**Comment by unknowndomain** [comment]
Sorry I meant the wider issue that OBS is and will increasingly look more and more like it doesn't fit in the macOS world as we move to Big Sur over the next 18 months and beyond.

**Comment by dodgepong** [comment]
Are you volunteering to reimplement the UI?

**Comment by unknowndomain** [comment]
@dodgepong Is that comment really necessary? I was responding to a conversation, not complaining. What I was thinking is how much work is involved in maintaining macOS like feel.

**Comment by dodgepong** [comment]
Maybe I was misinterpreting your comment. We get people complaining about how OBS doesn't look like a native Mac app, but there's good reason for that, and I generally would rather people get over the aesthetics and focus more constructively on making things actually work better.

**Comment by unknowndomain** [comment]
I agree, I spend several hours a week helping out on macOS support for the project every week so I’m not about to start giving the devs a headache! 

❤️

**Pull request closed without merging**
