### PR TITLE
libobs/util: Add FreeBSD and Dragonfly support in os_get_executable_path_ptr()

### PR DESCRIPTION
**Pull request by khng300**
### Description

FreeBSD and Dragonfly uses sysctl(3) for querying system information such as process stats. This change implements FreeBSD and Dragonfly support for os_get_executable_path_ptr().  

### Motivation and Context

To implement proper FreeBSD supports.

### How Has This Been Tested?

Tested on FreeBSD by checking if issue mentioned in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245299 goes away. Not tested on Dragonfly.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by RytoEX** [comment]
Just to make sure we're all on the same page.  This is meant to address #2622, correct?

**Comment by khng300** [comment]
> Just to make sure we're all on the same page. This is meant to address #2622, correct?

Yes

**Comment by emaste** [comment]
It definitely addresses the root cause on FreeBSD behind #2622, although it'd still be a good idea to report errno from readlink (even though with this patch applied readlink isn't being used on FreeBSD).

**Comment by emaste** [comment]
With this change I tested recording successfully on my laptop, running `FreeBSD nazar 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r359488: Tue Mar 31 13:13:49 EDT 2020     emaste@nazar:/usr/obj/usr/home/emaste/src/freebsd-svn/head/amd64.amd64/sys/GENERIC  amd64`

**Comment by notr1ch** [comment]
Looks good to me, only minor thing is the commit title is too long and doesn't meet the [50 / 72 requirements](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidelines).

**Comment by khng300** [comment]
Reduced the number of lines of boilerplate code and addresses @notr1ch points.

**Pull request merged**
