### PR TITLE
UI: Shorten Stats labels wording

### PR DESCRIPTION
**Pull request by SuslikV**
Allow smaller Stats dialog window and make clearer the readings.

The minimum width of the Stats window was limited by header labels width. Stats window has docked variant now but its minimum size is too huge because of the mentioned labels.

**Before**
obs Stats before

**After**
obs Stats after

### CODE REVIEW

**Comment by SuslikV** [comment]
Let me reword something too.

**Comment by dodgepong** [comment]
While shortening the label is nice for keeping things compact, it makes the label less descriptive. Can we also get a tooltip for some of these labels, and a (?) icon that users can hover for them to see what these labels mean?

**Comment by ntoff** [comment]
The time to render frames is commonly called "frame time" if you wanted to use that, instead of "render frame"

**Comment by SuslikV** [comment]
@dodgepong Tooltips are quite possible. What info should be in the tips? Just info what parameter means?
About the `(?)` in docking pane - not sure that you'll want to see it there.

@ntoff let's wait when someone votes up your suggestion :) I placed it here first, but then, I look at it from the other's view perspective - and it doesn't give any tip to the end user about the parameter itself. Also, it is not last frame time (which is usually used to build the graphics of possible rendering lag) but average, more close to "Render 1 Frame".

The "Lost Packets" is inaccurate here, but I think it points in the right direction if you want to find the root of the issue (in case you have not stable connection or network overload).

**Comment by dodgepong** [comment]
Some tooltip suggestions:

* CPU Usage: "The amount of your CPU that OBS is using."
* Free Disk Space: "The amount of space remaining on the desk you have selected for recording."
* RAM Usage: "The amount of system memory being consumed by OBS."
* FPS: "The number of frames that OBS is currently rendering every second."
* Frame Time (instead of Render Frame): "The average amount of time it is taking OBS to render a single frame."
* Rendering Lag: "The number of missed frames due to rendering lag."
* Encoding Lag: "The number of frames skipped due to encoding lag."
* Dropped Frames (instead of Lost Packets -- "dropped frames" is nearly common parlance at this point): "The number of frames dropped due to insufficient network connectivity."
* Transmitted: "The total amount of data transmitted during this output session."
* Bitrate: "The number of bits per second currently sent through the output."

As for the (?) thing, this is a quick mockup of what I sort of had in mind:

Screen Shot 2019-04-01 at 11 30 13 AM

It's probably not 100% necessary but it's a nice visual way to communicate to users that there is more information available about these things if they are confused. No idea how possible that is in Qt.

**Comment by SuslikV** [comment]
@dodgepong I see it slightly different, like:

- CPU Usage: "The amount of your CPU that OBS is using right now."
- Free Disk Space: "The amount of space remaining on the disk you have selected for OBS recordings."
- RAM Usage: "The amount of system memory being consumed by OBS."
- FPS: "The number of frames that OBS is currently rendering every second."
- Frame Time Avg. (ok, but averaging should be mentioned): "The average amount of time OBS takes to render a single frame. Averaging window is 1 second."
- Rendering Lag: "The number of missed frames due to rendering lag in relative to total number of produced frames."
- Encoding Lag: "The number of frames skipped due to encoding lag in relative to total number of frames attempted to encode."
- Packet Loss (that it; it is all about network): "The number of frames dropped due to network congestion, or sometimes due to poor quality connection, in relative to total number of frames attempted to send over the network."
- Transmitted: "The amount of data produced by OBS and passed through the output."
- Bitrate: "The number of bits per second currently sending through the output."

Is it acceptable?

`(?)` - is possible, but we will get bloat UI (that is intended to be shown constantly, by the way). So, I'm personally against it.

**Comment by Fenrirthviti** [comment]
While this is a good stop-gap, I would prefer to see the stats window be more modular, with the ability to show/hide each data point. Many users would only be interested in, say, the dropped/lagged/skipped frames, and none of the other data.

Perhaps allow adding as a custom dock widget, and at the time of creation, have a selection of the stats you wish to show in the specific dock, or a settings icon somewhere where they can be toggled on/off.

That said, this should help the people who are using the stats as a dock currently.

**Comment by SuslikV** [comment]
@Fenrirthviti right-click menu. Per label settings for CPU - Lag, and per column for the Status - Bitrate labels. Is this how you want to see it?

**Comment by Fenrirthviti** [comment]
No, I would prefer an actual button like a settings cog icon or similar rather than a context menu. Context menus are "hidden" and unless you know you can do it or accidentally right click, you would never know it was there.

**Comment by SuslikV** [comment]
Maybe the _Reset_ button with menu (same to Studio Mode quick transitions buttons). I really don't want to add another UI element. Stat should be short and efficient. Anyway it is for another PR.

**Comment by SuslikV** [comment]
Error at line 103.
Maybe I will look how to concatenate the strings in the right way later. If it needed at all...

**Comment by SuslikV** [comment]
Probably I will change my mind when this: https://github.com/obsproject/obs-studio/commit/739072fdcb2cc1e4f8998913c136619c0e64544a will be reverted.

I'm 100% sure, if two widgets will be merged into 2 tabs by accidental dragging - no one will know how to untab them back into two separate (not closable!) docks.

**Comment by jp9000** [comment]
Replaced by #1806

**Pull request closed without merging**
