### PR TITLE
Make drag and drop insensitive to file extension case

### LINKED ISSUE #4236: Drag and drop ignores file extension with caps.
## Platform

Operating system and version: Windows 10
OBS Studio version: 26.1.1 (64 bit)

## Expected Behavior

When an image with a fille extension which is in capitals is dropped into the window it should show up.

## Current Behavior

Currently when an image with a capitalised file extension is dropped nothing is shown on screen.

## Steps to Reproduce

1. Rename an image file to use capitals for the file extension
2. Drop image onto screen
3.
4.

## Additional information

The file extensions  [1] are not being santitised [2] . After looking at the code, I also tried it with a video with the extension renamed to use caps, this video failed to load yet using small casing it loads. 
Three possible fixes for this issue which I assume effects all media types. One possilbility is to include the upper cap version in the array of extensions, second it to sanitise the extension before the strcmp. However the issue with this is that the code using a pointer to constant char so a copy would need to be made and then sanitised. Thirdly to use a platform specific function (POSIX strcasecmp, MS stricmp) to compare the extensions.

[1] https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/window-basic-main-dropfiles.cpp#L17
[2] https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/window-basic-main-dropfiles.cpp#L247

### PR DESCRIPTION
**Pull request by bershanskiy**
### Description
Fixes #4236.
Makes OBS support drag and drop of files with capitalized file names. This one-liner was suggested by @WizardCM in [this comment](https://github.com/obsproject/obs-studio/issues/4236#issuecomment-778775619).

### Motivation and Context
When people drag and drop into OBS files with capitalized extensions in the names, these files do not show up in OBS (and no explanation is provided). People with systems set to hide file extensions might get confused. (Other programs typically can handle capitalized file names.)

### How Has This Been Tested?

I verified existence of the bug prior to this change:
 1. Dropped file called Untitled.png in OBS - it appeared in the scene
 2. Dropped file called Untitled.PNG in OBS - *nothing happened* - bug

Then I created the patch and verified that it works as expected:

 1. Dropped file called Untitled.png in OBS - it appeared in the scene
 2. Dropped file called Untitled.PNG in OBS - it appeared in the scene

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by notr1ch — APPROVED** [review]

**Comment by bershanskiy** [comment]
Is there anything I should do to advance this PR?

**Comment by WizardCM** [comment]
> Is there anything I should do to advance this PR?

Go through the checklist at the bottom of your PR, including the contributing guidelines. Once you've done each, click the checkbox to mark it as done.

**Comment by bershanskiy** [comment]
Thanks for the reply! I did follow the checklist and tested the change.

**Comment by jp9000** [comment]
Hi there, I've fixed the commit message, but in the future, please read through our contributing guidelines. Our commits usually have a prefix, and that is outlined in the contributing guidelines. I know it's a pain to have to read through everything, but please, in the future make sure to read through it.

**Pull request merged**
