### PR TITLE
UI: Fix source ref bug causing crash on exit

### LINKED ISSUE #3310: [Crash] Crash on exit when dragging and dropping scenes
## Platform
Operating system and version: Happens on all OSes
OBS Studio version: 25.0.8 (also happens on latest master)

## Expected Behavior
OBS shouldn't crash.

## Current Behavior
Sometimes will cause OBS to crash on exit.

## Steps to Reproduce
1. Start with fresh OBS
2. Keep Scene 1 empty
3. Create Scene 2
4. Add a source to Scene 2 (source has to not have audio with it)
5. Drag and drop the second scene to the top and then drag and drop it back at the bottom
6. Exit OBS
7. OBS crashes

## Crash Log
[crash.txt](https://github.com/obsproject/obs-studio/files/5113448/crash.txt)

### PR DESCRIPTION
**Pull request by Programatic**
### Description
Fixes bug that would cause a crash on exit when drag and dropping scenes.

### Motivation and Context
Fixes #3310 

### How Has This Been Tested?
Tested it on my machine, as well as others.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Can confirm this fixes the crash.

**Review by WizardCM — APPROVED** [review]

**Review by RytoEX — APPROVED** [review]
I also confirm that this fixes the crash from #3310 in my testing.

@cg2121 Did you mean #3310 instead of #3394?

**Comment by cg2121** [comment]
@RytoEX yep, meant to be #3310.

**Comment by jp9000** [comment]
Big cheer to @Programatic for solving this longstanding ref issue.

**Pull request merged**
