### PR TITLE
libobs: Fix crash when name is null

### PR DESCRIPTION
**Pull request by Chensiyy**
### Description

Crashed when name is NULL.  Just Fixed it.

### Motivation and Context

The second parameter of strcmp can not be NULL.

### Types of changes

Bug fix

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
Where would a NULL name be passed in?

**Comment by Chensiyy** [comment]
> Where would a NULL name be passed in?

In the function update_async_texrender of obs-source.c.

The return value of select_conversion_technique maybe null.

**Comment by notr1ch** [comment]
Under what situation would that happen? `select_conversion_technique` covers all possible `video_format` enums. In any case, silently ignoring the error and continuing execution results in `update_async_texrender` executing with a NULL `gs_technique_t`, potentially introducing further bugs or corruption.

In general I prefer illegal API usage to cause crashes or other "noisy" errors rather than silently continue and possible introduce further difficult-to-diagnose bugs or corruption.

**Comment by jp9000** [comment]
As @notr1ch stated, could you provide steps to reproduce this specific case? That would be helpful so I could understand the context behind this change.

**Comment by Chensiyy** [comment]
I actually encountered this crash. 
I made an obs plugin for playing video such as ffmpeg_source plugin. 
It will show some text tips when the video frame decoded error, and the text tips rendered in a RGBA texture.
Sometimes it will crash at the point which I modified.

**Comment by notr1ch** [comment]
It sounds like your plugin is the root cause of the bug then, perhaps you are setting an invalid `video_format` value. We would need to see the code to know for sure, but if that's the case then PR fixes the wrong thing.

**Pull request closed without merging**
