### PR TITLE
UI: Fix Hotkeys background and Tweak font color on hovering

### PR DESCRIPTION
**Pull request by TianQiBuTian**
### Description

Fix Hotkeys background to same as `QGroupBox`.
Tweak Hotkeys font color on hovering to make the font more visible.
Before:
before
After:
after
### Motivation and Context

Fix Hotkeys UI bug.
### How Has This Been Tested?

Open Hotkeys settings and hover the mouse on the font.
### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
@Warchamp7 your thoughts on this?

**Comment by PatTheMav** [comment]
Discussed this off thread - the change as-is introduces visual errors (i.e. the scrollbar background is placed inside the hotkey widget).

The correct approach would be to change the actual widget hierarchy and the choice of colour also does not meet accessibility requirements for contrast.

Please adjust the PR to meet these requirements.

**Comment by TianQiBuTian** [comment]
Update:
update

**Comment by PatTheMav** [comment]
Closing this because a proper fix for this would require changing the widget hierarchy and changes to the style sheets themselves will not be sufficient to achieve the desired goal.

**Pull request closed without merging**
