### PR TITLE
UI: Add ability to theme preview outline colors

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This adds the ability for themes to style the preview outline, crop, hover outline and handle colors.
Screenshot from 2019-08-04 04-37-54
Screenshot from 2019-08-04 04-47-33

### Motivation and Context
Themes should be able to set these colors as well.

### How Has This Been Tested?
This has been tested on Linux. It should work on other operating systems as well.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
I can confirm this works correctly on Windows 10. Looks good!

**Comment by jp9000** [comment]
Not sure how I feel about this one.  I'd prefer not to change the preview color scheme too much.  I'm going to pass on this one.

**Comment by Fenrirthviti** [comment]
I think this would be a great feature to have, and can really tie in the themes look and feel. Strongly suggest reconsidering this one!

**Comment by WizardCM** [comment]
I agree with Fenrir on this one. It's optional, and is only customized on Rachni in this PR.

**Comment by VodBox** [comment]
I also agree that this PR should be reconsidered. Themes that are going for a cohesive look across the whole program should be able to control things like this. As long as we keep the default the same and clear, there shouldn't be any problems.

**Pull request closed without merging**
