### PR TITLE
UI, libobs: Add hotkey test button to settings

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Add a execute button to the hotkey settings page. 
image

### Motivation and Context
To be able to test hotkeys while in the hotkey settings.

### How Has This Been Tested?
On windows 64 bit opened the hotkey settings page and show, hide source and switch scenes.

### Types of changes

- New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
How is having an execute button more useful than the user just pressing the hotkey themselves?

**Comment by exeldro** [comment]
@dodgepong pressing the hotkey does not work while the hotkey settings is open. Setting the hotkey, closing the settings, pressing the hotkey, opening the settings again and clearing the hotkey to see what each hotkey does takes a lot of time.

**Comment by dodgepong** [comment]
Then is this a case where the hotkey descriptions aren't clear enough such that people don't understand what the hotkeys would do before they are pressed? I guess I'm confused, I've literally never heard of anyone requesting this.

**Comment by exeldro** [comment]
A case I use it:
I have 1 source capturing the scoreboard of a game. That source I have multiple times each cropped 1 part of the score to display it nice on screen. If I wan't to hide the time part I have to test each source with the same name to see which is the timing to give it a hotkey.
image

**Comment by dodgepong** [comment]
I would argue, then, that the real solution here would be to come up with a way to differentiate the sources in the list, rather than add a button for testing a hotkey. A hotkey testing button strikes me as a solution to a problem that shouldn't exist in the first place.

**Pull request closed without merging**
