### PR TITLE
Preparations for Portals + PipeWire camera, part 2

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
### Description

This is the second batch of commits from https://github.com/obsproject/obs-studio/pull/6669, rebased on top of `master` and adjusted to the most recent changes.

The biggest change that this round of preparations introduce is making the PipeWire code able to handle async sources. There are no actual async sources that use PipeWire, but this is such a big change that I reasoned it's better reviewed independently from the next - and even bigger - reworks.

There should be no functional changes to the screencapture code.

### Motivation and Context

I don't want code reviewers crying in a corner when reviewing the PipeWire camera merge request, so let's go incremental and chop choppy and handle this massive amount of code in digestible chunks :slightly_smiling_face: 

### How Has This Been Tested?

- Run OBS Studio on Linux
- Add a PipeWire capture of any kind
- It should continue to work as it used to before

### Types of changes

 - Tweak (non-breaking change to improve existing functionality)

 - Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Penwy** [comment]
Ubuntu 22.04
libpipewire 0.3.48
kernel 5.19.0-43-generic

No regression noticed as of latest commit.
Fixes #9049

**Comment by dimtpap** [comment]
Would you like me to start working on a version of #6207 that uses the wrappers?

**Comment by GeorgesStavracas** [comment]
> Would you like me to start working on a version of https://github.com/obsproject/obs-studio/pull/6207 that uses the wrappers?

Eventually, but I don't think it's worth investing that time on *this* iteration of the wrappers. I think it'll be worth for you to rebase on top of a (future) part 3 of the PipeWire cleanups, but I'm still working on it.

**Comment by GeorgesStavracas** [comment]
Let's go \o/

**Pull request merged**
