### PR TITLE
[WIP] deps/libobs/UI: Add MIDI hotkey support

### PR DESCRIPTION
**Pull request by Andersama**
Adds MIDI events as hotkeys.

Note: RtMidi.h is modified, for whatever reason I'm not having luck w/ CMakeLists.txt on Windows to include winmm (any help appreciated)

### CODE REVIEW

**Comment by Andersama** [comment]
Yeah I saw that, didn't have much luck w/ it. I think I'm missing something else here's a bit of console feedback from when Midi's supposed to start up. Without the pragma comment (whether cmake uses winmm or winmm.lib) I get this.
image

**Comment by Alex-Dash** [comment]
It is cool, but there is still some work to be done.
For example, you can't control the volume or speed of particular transition. 
For some functions you can check @lebaston100 and his MidiToOBS solution.

**Comment by Andersama** [comment]
@Alex-Dash this pr was just for treating MIDI events as hotkeys. I'm in the process of setting up OBS in such a way that the MIDI messages can be used to control properties / sliders, that'll be a future PR.

**Comment by DDRBoxman** [comment]
This definitely needs a proper UI outside of the hotkey settings so closing for now until we are ready to tackle that.

**Comment by bushwookieee** [comment]
i’ve unsubscribed several times. yet i’m still recieving emails.

**Comment by WizardCM** [comment]
@bushwookieee You've likely been unsubscribing from individual threads, not the whole project.

Step 1: Sign in to https://github.com
Step 2: Visit http://github.com/obsproject/obsstudio
Step 3: On the top right, click "Unwatch" and select "Not watching" - example https://imgur.com/b9bm7NN

**Pull request closed without merging**
