### PR TITLE
UI: Include sceneitem locked state in copy-paste

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

When copy-pasting a source, so far it would always be unlocked. We already copy other attributes like whether the source is visible, so it makes sense to also include the locked state in there.

### Motivation and Context

Noticed that the status of whether a source is visible is copy-pasted, but not whether it's locked.

### How Has This Been Tested?

macOS 14
Copy-pasted with "Paste (Existing)" and "Paste (Duplicate)" and confirmed that a locked source would be locked when pasted.
Added new and existing sources via the dialog to confirm they were still always unlocked (since that code was modified).

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by GeorgesStavracas — APPROVED** [review]
Makes sense from a UI / UX perspective

**Comment by PatTheMav** [comment]
While I'm not inherently opposed to this change, I'd be amiss not to notice that the current behaviour mimics that of Photoshop and other layer-based applications I'm aware of, where copying a locked layer creates a duplicate layer that is unlocked automatically (the purpose of the copy being able to make changes).

At least that's what I expect when copying a locked layer/element in an application mimicking that paradigm.

**Comment by gxalpha** [comment]
bump on the above @Warchamp7 @GeorgesStavracas

**Comment by Warchamp7** [comment]
> While I'm not inherently opposed to this change, I'd be amiss not to notice that the current behaviour mimics that of Photoshop and other layer-based applications I'm aware of, where copying a locked layer creates a duplicate layer that is unlocked automatically (the purpose of the copy being able to make changes).
> 
> At least that's what I expect when copying a locked layer/element in an application mimicking that paradigm.

I am generally in agreement with Pat here. I think in the majority of scenarios if not all, when a scene item is copied and pasted it's because someone wants to manipulate the copy. The current behaviour of not copying the lock status is therefore preferred.

**Pull request closed without merging**
