### PR TITLE
Create and upload AppImage for Linux

### PR DESCRIPTION
**Pull request by probonopd**
Create and upload continuous [AppImage](http://appimage.org/) builds to the GitHub Releases page.

This is a new attempt at https://github.com/obsproject/obs-studio/pull/1565, this time using the existing xenial build configuration and not touching any of the existing build scripts but adding an additional one for AppImage. I hope this addresses your concerns @jp9000.

__PLEASE NOTE:__ For this to work, you need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

### CODE REVIEW

**Comment by juvester** [comment]
AppImage would be quite nice to have imho.

If you want to be extra unobtrusive you could even put the AppImage build under `allow_failures` tag in the build matrix. From Travis-CI [docs](https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail):

> You can define rows that are allowed to fail in the build matrix. Allowed failures are items in your build matrix that are allowed to fail without causing the entire build to fail. This lets you add in experimental and preparatory builds to test against versions or configurations that you are not ready to officially support.

```YAML
matrix:
  include:
    # macOS build
    # regular linux build
  allow_failures:
    # AppImage linux build
```

**Comment by probonopd** [comment]
An AppImage for testing can be downloaded at
https://github.com/probonopd/obs-studio/releases/continuous

**Comment by probonopd** [comment]
@jp9000 may I kindly ask you for your review before the OBS source code changes so much that this will run into merge conflicts aganin. Thank you.

**Comment by DDRBoxman** [comment]
Just tried on ubuntu 19.04 and the icons don't show up.

Screenshot from 2019-07-20 20-55-58

**Comment by probonopd** [comment]
Thanks for testing @DDRBoxman. Apart from the icons, is the functionality working for you?

**Comment by Illutorium** [comment]
On "19.04" at LiveDVD it's doesn't help... even if be come to Install Shaders as "i965-va-driver-shaders" and "intel-media-va-driver-non-free" when Would be was think of Support "VAAPI" but not on Portable? -> "https://www.phoronix.com/scan.php?page=news_item&px=OBS-Studio-23.0-Released" - but on 18.10: Still fails to Recording of Advanced Settings.

**Comment by probonopd** [comment]
Hello @Illutorium please describe what you are trying to do, and on which hardware you are trying to do it. I can use the OBS AppImage just fine, in fact I have already published a few screencasts on YouTube using it.

**Comment by probonopd** [comment]
Here are two high-profile Linux users and podcasters talking about various application delivery formats for Linux and why they would like to have a OBS AppImage:



[](https://t.co/G77DsFgDl4?amp=1)

**Comment by Heufneutje** [comment]
It seems like you did something wrong in git as this PR now modifies over 1000 files.

**Comment by jp9000** [comment]
Yea I think something went wrong there.  That doesn't look quite right.

**Comment by probonopd** [comment]
Indeed some type of Git merge issue. I was trying to update my long-standing PR to make it up-to-date with the OBS master.

**Comment by jp9000** [comment]
If you need help, let me know.

**Comment by jp9000** [comment]
You know, actually nevermind, I'm just not interested.  I just have too much going on right now and I don't want to deal with it.  I have way too much going on and I can't make everyone happy.  Maybe when I get some extra maintenance help I can take a look at it again.

**Pull request closed without merging**
