### PR TITLE
UI: Show a message in the empty source list

### PR DESCRIPTION
**Pull request by DDRBoxman**
Re-implementation of #1451

Thanks @WizardCM !

### CODE REVIEW

**Comment by dodgepong** [comment]
IMO the best way to handle this is to teach the user how to add a source. I think it should direct the user to click the + button to add a source (with an arrow pointing at the button?).

**Comment by DDRBoxman** [comment]
Removed the ability to click the empty layout box

**Comment by DDRBoxman** [comment]
@WizardCM background color should be fixed now too

**Comment by DDRBoxman** [comment]
Screen Shot 2019-03-21 at 12 26 18 AM

**Comment by DDRBoxman** [comment]
Screen Shot 2019-03-21 at 12 28 41 AM

**Comment by exeldro** [comment]
Does this also show when you have view -> toolbars-> listboxes disabled? The text is not correct in that case. Maybe mention the right click option to add sources?

**Pull request closed without merging**
