### PR TITLE
UI: Link Qt::DBus on FreeBSD

### PR DESCRIPTION
**Pull request by emaste**
As with Linux we need to link Qt::DBus on FreeBSD now that there's a HighContrastEnabled implementation that makes use of it.

Fixes: 41ba8bdfdd02 ("UI: Add HighContrastEnabled implementation fo...")

### Description
Link Qt::DBus on FreeBSD

### Motivation and Context
41ba8bdfdd02 added a HighContrastEnabled implementation which makes use of DBus, and updated UI/cmake/os-linux.cmake to link Qt:DBus. os-freebsd.cmake needs the same change.

### How Has This Been Tested?
Built-tested on my laptop.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by emaste** [comment]
With this change obs builds and runs on my FreeBSD 15 laptop. I'm not sure about the build failures in FreeBSD CI just yet.
obs

**Comment by emaste** [comment]
> I'm not sure about the build failures in FreeBSD CI just yet.

It seems to just be the case that CI is running with `-Werror` and my local build is not. I have the following warning counts:
```
 326 implicit conversion loses integer precision: '<type>' (aka '<type>') to '<type>' [-Wshorten-64-to-32]
   2 indirection of non-volatile null pointer will be deleted, not trap [-Wnull-dereference]
   1 comparison of integers of different signs: 'int' and 'uint_fast8_t' (aka 'unsigned int') [-Wsign-compare]
   1 code will never be executed [-Wunreachable-code]
   1 'PySys_SetArgv' is deprecated [-Wdeprecated-declarations]
```

**Review by derrod — APPROVED** [review]

**Review by tytan652 — APPROVED** [review]
LGTM

**Review by RytoEX — APPROVED** [review]
Looks good to me, and fixes an oversight in 41ba8bdfdd02762ea72fd72dc0d05cf6357a7241 (#9653).

**Pull request merged**
