### PR TITLE
UI: Show splash screen while initialising

### PR DESCRIPTION
**Pull request by WizardCM**
### Description
Introduces a splash screen to display during the various stages of OBS startup.

Includes current loading state & OBS version number.

Note the splash screen displays on whichever monitor the user's mouse is on during initial load, not always their main display.

**Note:** the splash image & all messages are not final.

**To do:**
- [ ] Position splash screen based on last-known OBS window position rather than cursor
- [ ] Replace splash image with a better one
- [ ] Look into loading messages from translations (first, see what stage the language is determined)
- [ ] Add handling for plugins to display progress on each being loaded
- [ ] Verify that the splash screen doesn't appear if the user has `--minimise-to-tray`
- [ ] Finalise messages
    - [ ] Make sure no potentially-long-running steps have been missed
    - [ ] Remove unnecessary steps/messages
    - [ ] Finalise wording

### Motivation and Context
Primarily, this is for users who have large scene collections, a lot of hotkeys, or a slow drive, to provide a visual cue that OBS _is_ starting up. It can also provide the user some insight into what may be causing OBS to take longer to load.

### How Has This Been Tested?
Open OBS.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by mufunyo** [comment]
Personally I'd want the splash screen to be positioned in the middle of wherever the OBS Window would appear after it's done loading, so let's say I have OBS in the bottom right corner on my secondary monitor, that's where the splash screen would show up too.

**Comment by unknowndomain** [comment]
It might be nice to have a progress bar that takes the number of steps and fills in that fraction of the bar for each, presumably the progress bar could have an easing function on it to make it progress more smoothly than jump... jump... 

I think this is a really good idea, i'd suggest also adding a little icon next to the version number if the version is outdated. If this would be slow to do, it could perhaps feed of a `updateavailable` flag somewhere from last launch?

**Comment by matoi974** [comment]
I'm more interested in what kind of impact does this change have on start-up times. Have you measured the total time it takes between launching obs64.exe and seeing its main window, before and after this change?
Also, are you respecting the `--minimize-to-tray` launch option? Would be weird to see a banner after explicitly asking *not* to see anything.

**Comment by Xaymar** [comment]
Alternative design suggestion: Make it a bit smaller, as there really isn't a lot of information to actually present here. Something like this, just with better visual design:

image

Edit: Raw files: 
[design-test-splash.zip](https://github.com/obsproject/obs-studio/files/5699514/design-test-splash.zip)

**Comment by mufunyo** [comment]
Disagree. A splash screen should "splash". The initial design is fine.

**Comment by WizardCM** [comment]
Closing this for now until I have more time to work on it & adapt to feedback I've collected.

**Pull request closed without merging**
