### PR TITLE
Migrate pipewire-capture to linux-pipewire

### PR DESCRIPTION
**Pull request by columbarius**
### Description

Migrates the PipeWire based pipewire-capture from the linux-capture plugin to the linux-pipewire plugin.

### Motivation and Context

PipeWire has to be initialized and deinitialized. Doing the deinitialization twice causes obs to segfault. To avoid this move both into the same plugin.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

Requires and contains [#5377 ](https://github.com/obsproject/obs-studio/pull/5155)

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
For the translations, even though they are (I think?) being just pulled out of the linux capture plugin localization files, we'll still want only the English localization file, and the translations will need to be submitted through CrowdIn to avoid breaking the process. Sorry for the hassle!

**Comment by columbarius** [comment]
Ok dropped the translations.

**Comment by tytan652** [comment]
PR related to PipeWire should be merged in this order (1 and 2 are interchangeable):
1. #5394, to prepare the addition of other PipeWire related sources/outputs.
2. #5383, to prepare the addition of PipeWire based virtual camera.
3. #5377, to add the virtual camera

So, this PR will not need and have no need to depend on another PR.

**Comment by columbarius** [comment]
Will change the order of this MRs after the next obs release. There are still some changes in the pipewire capture which might conflict with this MR.

**Comment by columbarius** [comment]
Adapted for the CMake rework #5155

**Comment by columbarius** [comment]
Rebased onto master and ready from my side.

**Review by GeorgesStavracas — APPROVED** [review]
We can finally land this \o/

**Comment by GeorgesStavracas** [comment]
Hold on; I didn't check in detail, but looking at the build log of the Flatpak run, I don't see the `linux-pipewire` plugin being installed. @columbarius could you please double check that? I can't dig deeper right now

**Comment by columbarius** [comment]
> I don't see the `linux-pipewire` plugin being installed.

With `flatpak-builder fp-build CI/flatpak/com.obsproject.Studio.json` the lib was created in `./files/lib/obs-plugins/linux-pipewire.so`. 

Check the artifact after CI also included linux-pipewire.so and screencast worked.

**Review by GeorgesStavracas — APPROVED** [review]
Yup, turns it it's right there in the logs

**Comment by columbarius** [comment]
Thanks for merging. Let's get the PipeWire train rolling!

**Pull request merged**
