### PR TITLE
UI: Add collapsible groups to hotkeys

### PR DESCRIPTION
**Pull request by Andersama**
Adds collapsible groups to hotkey settings.

See (and thanks to) #1580

### CODE REVIEW

**Comment by dodgepong** [comment]
Does the Dark theme not get labels on the boxes?

If you apply a filter, does it automatically expand boxes that contain matches?

**Comment by Andersama** [comment]
@dodgepong that was a bit of a gaff on my part I uploaded the wrong gif, unfortunately this broke the filter*, I'm working on getting it back to a working state.

**Comment by WizardCM** [comment]
Note: Fider request for this here https://ideas.obsproject.com/posts/236/make-hotkey-subsections-collapsible-in-settings

**Comment by DDRBoxman** [comment]
I'm going to close this, @Fenrirthviti proposed a promising UI for a hotkey overhaul and I think it will end up being much cleaner in the long run.

**Pull request closed without merging**
