### PR TITLE
win-mf:fix windows compile error

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by wanhongqing123** [comment]
fix windows compile error

**Comment by wanhongqing123** [comment]
> Forgive me for being a bit forward, but why on earth would you enable the plugin in the first place? It's deprecated for a pretty good reason.

oh I want to compare the x264 and Qsv.

**Comment by wanhongqing123** [comment]
> h

and why deprecated the Qsv

**Comment by jp9000** [comment]
> and why deprecated the Qsv
QSV isn't deprecated, we use the obs-qsv plugin for that

**Comment by wanhongqing123** [comment]
> > and why deprecated the Qsv
> 
> QSV isn't deprecated, we use the obs-qsv plugin for that

oh get,    the pull request can be closed

**Comment by jp9000** [comment]
Sorry for the trouble! We would definitely recommend using the obs-qsv plugin instead if you were just enabling this to use QSV 🙂

**Comment by wanhongqing123** [comment]
> Sorry for the trouble! We would definitely recommend using the obs-qsv plugin instead if you were just enabling this to use QSV 🙂

ok, thank you.

**Comment by Azvf** [comment]
> Forgive me for being a bit forward, but why on earth would you enable the plugin in the first place? It's deprecated for a pretty good reason.
May I ask what's the cause of deprecating it. I was thinking about implementing it as a general hw encoding solution on windows and found an article of a gstreamer dev said  "a Media Foundation implementation could be as powerful as the vendor specific APIs, because Media Foundation uses vendor implementations underneath". I was qutie curious about the reason, hope you can shed a light on me.

**Comment by wanhongqing123** [comment]
你的邮件已收到，我会尽快的回复你

**Pull request closed without merging**
