### PR TITLE
mac-videotoolbox: Default to High profile

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Changes the default profile of the VT H.264 encoder to High.
HEVC stays at main.

### Motivation and Context

[R1ch's stream analyzer](https://r-1.ch/analyzer/) got mad at me for using the main profile.
We really should be using High in Simple Mode, I consider current behavior to be a bug.

### How Has This Been Tested?

Tested that recordings using the simple Apple H.264 streaming encoder use the High profile now (whereas before it was Main) by throwing the file into MediaInfo.
Tested that x264 recordings using the stream encoder in simple mode use the High profile both before and after.
Checked manually (by looking at the code) that both NVENC and AMF already use High.

Tested that HEVC recordings using the simple Apple HEVC streaming encoder still use the Main profile (which is correct for HEVC).

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by derrod — COMMENTED** [review]
The "proper" solution is probably to change the default at in https://github.com/obsproject/obs-studio/blob/master/plugins/mac-videotoolbox/encoder.c#L1331

See NVENC for example which conditionally uses "high" for AVC and "main" for everything else:

https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L434-L435

**Comment by gxalpha** [comment]
> The "proper" solution is probably to change the default

You think so? This would change every existing setup (although it probably wouldn't matter too much).

**Comment by derrod** [comment]
I'm not sure it would affect existing setups unless this is one of those cases where OBS doesn't save your settings unless you change them from the default. Shouldn't break anything either though even if it does change.

**Comment by gxalpha** [comment]
It is indeed one of those cases where defaults aren't saved.
I guess you're right though, there's virtually no reason for anyone to use main for H.264 these days.

**Pull request merged**
