### PR TITLE
obs-filters: Cleanup warnings

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

Remove unused domain code. Fix const complaint.

### Motivation and Context

Warnings make reviewing code less appealing.

### How Has This Been Tested?

It compiles.

### Types of changes

Trivial

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by emaste** [comment]
`const uint8_t **` change LGTM

We should probably use the `DOMAIN_MIN` and `DOMAIN_MAX` values (or at least check and warn/fail if they're not 0,0,0 and 1,1,1)?

**Comment by RytoEX** [comment]
Aren't the DOMAIN_MIN and DOMAIN_MAX changes here duplicating some of the work in #2551?

**Comment by emaste** [comment]
Indeed, it looks like https://github.com/obsproject/obs-studio/pull/2551/commits/3aef198921c9b43df95cc97f0f226ee85c6c2600 + the `const` change from this PR is what's needed.

**Comment by kkartaltepe** [comment]
I thought all the cute lut PRs had come in actually. SGTM closing this one out.

**Pull request closed without merging**
