### PR TITLE
obs-ffmpeg, win-dshow, deps/media-playback: Use recommended API for AVCodecContext

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

Use `avcodec_free_context()` to replace `avcodec_close`

### Motivation and Context

```
 * @note Do not use this function. Use avcodec_free_context() to destroy a
 * codec context (either open or closed). Opening and closing a codec context
 * multiple times is not supported anymore -- use multiple codec contexts
 * instead.
 */
int avcodec_close(AVCodecContext *avctx);
```

### How Has This Been Tested?

test using ffmpeg-nvenc on Windows

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Seems we also still use this in the following places:

https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c#L128

https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c#L332

https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/deps/media-playback/media-playback/decode.c#L116

However, in other places we place this behind a version check. I'm unsure if that's necessary as even Ubuntu 18.04 succeeded in building:

https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/libobs/graphics/graphics-ffmpeg.c#L75-L79

**Comment by walker-WSH** [comment]
> Seems we also still use this in the following places:
> 
> https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c#L128
> 
> https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c#L332
> 
> https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/deps/media-playback/media-playback/decode.c#L116
> 
> However, in other places we place this behind a version check. I'm unsure if that's necessary as even Ubuntu 18.04 succeeded in building:
> 
> https://github.com/obsproject/obs-studio/blob/a8ecf3c8f2c2c28624a01249d3ec8b6435198009/libobs/graphics/graphics-ffmpeg.c#L75-L79

I am on vocation now. 
will you help modify others if need ？

**Review by jpark37 — CHANGES_REQUESTED** [review]

**Review by jpark37 — APPROVED** [review]

**Comment by Arthus** [comment]
Nit from some whose first PR hasn't even been merged yet. :)
Maybe the typo in the commit message can be fixed? Pretty sure it should rather be

> obs-ffmpeg: Use recommended API for ffmpeg-nvenc

**Comment by walker-WSH** [comment]
@WizardCM @jpark37 

I have changed all coded where `avcodec_close` is called, checking `LIBAVFORMAT_VERSION_INT`.

**Comment by jpark37** [comment]
This check is for FFmpeg 3.1, which we already require. It is safe to remove the old path if the new path makes logical sense.

**Comment by walker-WSH** [comment]
> This check is for FFmpeg 3.1, which we already require. It is safe to remove the old path if the new path makes logical sense.

done

**Pull request merged**
