### PR TITLE
UI: Add YouTube Chat Dock

### PR DESCRIPTION
**Pull request by derrod**
### Description
Adds a chat dock for YouTube, since the youtube chat URL is not static it is added as a placeholder until a broadcast is started.

As we cannot login in CEF (Google *sometimes* blocks that) the chat input is hidden via custom CSS.

Pre-broadcast placeholder:
2021-08-16_13-34-17_lrC8RI

Chat after starting broadcast:
2021-08-16_13-33-48_LGhcpN

### Motivation and Context
People want chat.

### How Has This Been Tested?
Started streams, ended streams, had streams locked to private by youtube claiming their team looked at it when in reality some third-rate machine learning algorithm just doesn't like black screens with no sound.

### Types of changes

- New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
It would be appreciated if somebody could confirm this working on macOS/Linux and no compile errors happening on those platforms when the browser source is not compiled.

**Comment by Gol-D-Ace** [comment]
> It would be appreciated if somebody could confirm that this is working on macOS/Linux and no compile errors are happening on those platforms when the browser source is not compiled.

Tried building on Linux without browser source and didn't notice any issues.

**Comment by Gol-D-Ace** [comment]
Also seems to work correctly on xorg (no docks on Wayland)
Screenshot_20210816-152849-896

**Comment by gxalpha** [comment]
> It would be appreciated if somebody could confirm that this is working on macOS/Linux and no compile errors are happening on those platforms when the browser source is not compiled.

Compiles with `-DBUILD_BROWSER=OFF` on macOS without issues.

**Comment by derrod** [comment]
Rebased on 4ef2a79a1985ba9366f15b41382b20e35cb72e97 to fix merge conflicts.

In rebasing I also discovered a bug with private scheduled broadcasts that I fixed.

**Comment by derrod** [comment]
Rebased again on f131c0c36b1114a296673bc1e2e830eede323b12 to resolve merge conflict.

**Pull request merged**
