### PR TITLE
obs-ffmpeg: Fix NVENC async usage pattern

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Fix async API usage problems reported by NVIDIA.

### Motivation and Context
Apparently future drivers aren't going to be as lenient.

### How Has This Been Tested?
Recorded a video with NVENC. Used temporarily logging to verify event waits were being called at expected times.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
Waiting for NVIDIA to validate the changes are good.

**Comment by jpark37** [comment]
Probably better to merge this preemptively than wait for NVIDIA.

**Comment by derrod** [comment]
I'm fine with merging it by end of Monday if Nvidia hasn't responded until then so it makes it into 28.0 at least. If it turns out to not work we'll have the inevitable hotfix:tm: to revert.

**Comment by WizardCM** [comment]
This breaks simple output mode NVENC H.264 recording.

Repro steps:
1. Create a new Profile
2. Start Recording (assuming your PC defaulted to NVENC)
3. Stop recording. It never stops.

**Pull request merged**
