### PR TITLE
UI: Add Custom Browser Panels

### PR DESCRIPTION
**Pull request by Andersama**
Adds dialog to add / remove / configure browser panels.

### CODE REVIEW

**Comment by SuslikV** [comment]
`#include "ui_cefwidgetdialog.h"` - shouldn't be here.

Is this interactive page? You can interact with it? Is it really needed in OBS?

**Comment by dodgepong** [comment]
Is it possible to make the default size of the widget bigger?

**Comment by gazugafan** [comment]
After seeing the Twitch and Mixer chat docks, I was expecting to see custom webpage docks next. This would be amazing. Really hope it gets merged in!

One thought for an improvement: add a field for custom CSS, the same way you can with Browser sources?

**Comment by ludalex** [comment]
Can we get this merged? I think this would be game changer for a lot of streamers, especially the ones that use Streamlabs/StreamElements and want to add the event list without compromising for SLOBS/OBS.Live.

**Comment by neico** [comment]
This would allow me to use the full Restream.io title configuration (with game fields) instead of the stripped down embedded one currently used for "Stream Information".
Of course I hope that the embedded one eventually gains that ability too, but until then...
And opening an extra browser window just to have that is over-complicating things.

**Comment by Aluminite** [comment]
Still waiting...

**Comment by gazugafan** [comment]
Have you seen this, @jp9000? It would be a ridiculously convenient feature to have, and it seems like it's basically ready to go. Really hopeful it gets merged in :)

**Comment by burritosoftware** [comment]
Still waiting, this will be very useful for putting in the Streamlabels dashboard into OBS (which Streamlabs doesn't want you to know about, you can go to this link for the exact same dashboard :) https://streamlabs.com/dashboard/recent-events)

**Comment by dliuproduction** [comment]
Following, this would be great to have

**Comment by burritosoftware** [comment]
Followup: @jp9000 have you seen these browser docks? Would be very useful! :)

**Comment by Fenrirthviti** [comment]
We have seen this PR and will review when time allows. Repeated comments asking us to check the PR are not necessary.

**Comment by jp9000** [comment]
Superseded by #2015

**Pull request closed without merging**
