### PR TITLE
UI:Properties view

### PR DESCRIPTION
**Pull request by nikola3211**
### Description

Added spacing to QHBoxLayout

### Motivation and Context

Some elements are overlapping on MAC due to 
no spacing in QHBoxLayout.

https://github.com/obsproject/obs-studio/issues/7758

### How Has This Been Tested?

Tested on MAC only.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are properly formatted and commits squashed where appropriate.
- [ x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Warchamp7** [comment]
Please post before and after screenshots if you're able

**Comment by nikola3211** [comment]
Hi, 
Here are before and after screenshots:
BBD53B79-1B81-4571-8092-CC03CA4D82C7
BD8CC017-09C9-4704-9E6B-0BD3F21DD692

**Review by gxalpha — COMMENTED** [review]
I arrived at a similar fix when looking into this a while back, the problem is that the problem appears to be exclusive to macOS. This leads me to believe that there's some kind of Qt issue which imo we should investigate first.
Also, changing this for every OS will probably add unnecessary spacing on other platforms - if it does (some screenshot of Windows or Linux would be nice), this should be ifdef-guarded to macOS only (but again, I'd be more happy about an investigation into what *actually* happens here on Mac).

**Comment by nikola3211** [comment]
Example 2 on this link:
https://cpp.hotexamples.com/examples/-/QHBoxLayout/setContentsMargins/cpp-qhboxlayout-setcontentsmargins-method-examples.html
and quick google search showed me that many people have issues with QHBoxLayout  on Mac vs Win or Linux.
Seems to me that this is OS related. I can ifdef-guard it if you want?

**Comment by WizardCM** [comment]
Yes, please guard this change to limit it to macOS. Otherwise, looks like a good fix.

**Comment by RytoEX** [comment]
For reference, on Windows 11 right now, it looks like this:
image

With this PR, without guarding the change to affect macOS-only, it looks like this:
image

**Comment by nikola3211** [comment]
On windows the box is also aligned properly. It seems that the box layout adds that tilt. When I tested this by adding help on another bool, it also shifted to the right a bit. I should look into that too.

**Comment by nikola3211** [comment]
I've spent some time on this. Only solution I've found is to add box containers on all the checkboxes, so that they all shift a bit to the right, everything else I tried didn't work. If you want I can push those changes or we can leave it as it is.

**Review by gxalpha — COMMENTED** [review]
I'm fine with this but would like a TODO comment that the root cause needs further investigation.

**Comment by norihiro** [comment]
The first word after the prefix in the commit title should be a present-tense verb.
I'd like to suggest something like `UI: Fix ... on properties view`. Please replace `...` with something suitable word.

**Comment by nikola3211** [comment]
@gxalpha  Shall we close this?

**Comment by gxalpha** [comment]
Please see the comment above: https://github.com/obsproject/obs-studio/pull/9759#issuecomment-1806839734
Also please squash your commits together into one and force-push to this PR's branch.

**Comment by nikola3211** [comment]
Done.

**Comment by norihiro** [comment]
I'm sorry that we need a space between `:` and `Fix`.

**Comment by nikola3211** [comment]
No problem, I didn't know.

**Comment by nikola3211** [comment]
@gxalpha Is this ok to merge now?

**Review by gxalpha — APPROVED** [review]
seems fine to me

**Pull request merged**
