### PR TITLE
obs-ffmpeg: Support lack of Psycho Visual Tuning

### PR DESCRIPTION
**Pull request by jpark37**
### Description
For new NVENC, warn if PVT is requested, but unsupported by the GPU.

For old NVENC, if PVT is enabled when FFmpeg failure occurs, retry
without PVT.

### Motivation and Context
NVENC failure is a bad user experience.

### How Has This Been Tested?
Breakpoint inspection. I don't actually have a failing card, so it would be good to have someone else verify that.

EDIT: Flaeri says it works.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by flaeri** [comment]
works on my machine. https://obsproject.com/logs/S8XY2FJ1Gxb5B1j2
Tested Lossless rate control with PVT enabled. Successfully tried without, and recording was produced, and had content.

**Comment by flaeri** [comment]
After force-push (v2), all seems to still work well on my gtx 1070.
https://obsproject.com/logs/L-TAsZuzVzjvnTv3

* lossless PVT jim-nvenc, fallback works
* lossless PVT ffmpeg, fallback works
* lossless no PVT jim-nvenc, fires a "nvEncInitializeEncoder Failed 8, still works fine
* lossless no PVT ffmpeg, works fine, no error message.
* VBR with/without PVT still works fine, no extra error messages.

**Comment by RytoEX** [comment]
I've linked this to #4785 and pinged there for testers.

**Comment by guihkx** [comment]
I know I'm late to the party, but just confirming that that it works on my GTX 660 on Linux! :)

```
info: ---------------------------------
info: [NVENC encoder: 'simple_h264_recording'] settings:
	rate_control: CQP
	bitrate:      0
	cqp:          23
	keyint:       250
	preset:       hq
	profile:      high
	width:        1920
	height:       1080
	2-pass:       false
	b-frames:     2
	psycho-aq:    1
	GPU:          0

[h264_nvenc @ 0x5633a2fdd940] The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
[h264_nvenc @ 0x5633a2fdd940] Temporal AQ not supported
[h264_nvenc @ 0x5633a2fdd940] No capable devices found
warning: [NVENC encoder: 'simple_h264_recording'] avcodec_open2 failed, trying again without Psycho Visual Tuning
[h264_nvenc @ 0x5633a2fdd940] Using global_quality with nvenc is deprecated. Use qp instead.
info: libfdk_aac encoder created
info: libfdk_aac bitrate: 192, channels: 2
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/gui/2021-06-07 02-15-30.mkv'...
info: Output format name and long_name: matroska, Matroska
info: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/gui/2021-06-07 02-15-30.mkv' stopped
info: Output 'simple_file_output': stopping
info: Output 'simple_file_output': Total frames output: 499
info: Output 'simple_file_output': Total drawn frames: 512
info: ==== Recording Stop ================================================
info: libfdk_aac encoder destroyed
```

Thanks a lot, guys <3

**Pull request merged**
