### PR TITLE
Deps/CI: Update to Qt 5.14.2

### PR DESCRIPTION
**Pull request by EwoutH**
_This is a draft pull request for public review and CI testing._

### Description
- Updates Qt from 5.10.1 to 5.14.2 on Windows
- Updates Qt from 5.14.1 to 5.14.2 on macOS

### Motivation and Context
Unifies Qt version on macOS and Windows. For Windows the minor version jump also improves scaling behavior on high DPI displays, among other improvements

### How Has This Been Tested?
 - Waiting on some upstream uploads before proper testing can be done

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### To-do
 - [ ] Wait for updated `Qt_5.14.2.7z` package to be uploaded on https://cdn-fastly.obsproject.com/downloads/
 - [ ] Wait for update on [qt.rb](https://github.com/obsproject/obs-studio/blob/master/CI/install-dependencies-osx.sh#L32)
 - [ ] Perform testing

@DDRBoxman Could you review this PR and upload the necessary Qt packages if ok?

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
The reason we haven't updated is that many plugins will cease to function if we update Qt. We will also need a significant amount of testing before updates can be complete, this is not just a simple dependency update. We have not updated for good reason due to the amount of verification and testing that will need to be done.

**Comment by EwoutH** [comment]
Thanks for the quick reply! With the recent release of OBS 25.0 and thus a long window before the next major release this would be a good moment to start the migration. If not possible with current roadmap/resources, I understand.

**Comment by dodgepong** [comment]
Ideally the amount of time between releases is not that long, but regardless, if you're able to put some good testing into 5.14, that would be appreciated.

**Comment by energizerfellow** [comment]
If the downloads on the Resources section of the OBS forum are anything to go by, the following account for, in order, the fast majority of 3rd-party plug-in usage with 30K+ downloads:

- obs-ndi
- OBS-VirtualCam
- Free NohBoard
- Input Overlay
- obs-websocket
- StreamFX
- Advanced Scene Switcher
- OBSCurrentSong
- OpenVR input plugin  (not very popular anymore?)

My anecdotal experience on the OBS Discord server and places like /r/twitch definitely seems to backup these numbers.

If we take a bit of 80/20 Pareto principle approach to this, I figure that as long as we work with the authors of the above plug-ins to make sure they are ready for a new version of Qt, the vast majority of OBS plug-in users will be good to go.  We just need to make it *very* clear in the release notes they need to update plug-ins.

**Comment by Xaymar** [comment]
StreamFX does not use Qt at the current time, as the obs-frontend-api does not have a cmake export package file. [I'm working towards making that work though, and then StreamFX will link against whatever Qt version the latest release build of OBS was built against.](https://github.com/obsproject/obs-studio/pull/2650)

The StreamFX plugin breaking on newer releases is actually very much expected. I don't think I had a single major OBS version increase where the plugin didn't suddenly do things that it didn't do before.

**Comment by EwoutH** [comment]
Should close #2634.

@DDRBoxman Could explain how the `Qt_5.10.1.7z` is compiled and zipped? I see two binaries, one for 32-bit and one for 64-bit. Which components of Qt need te be included? Only the GUI or more?

Would be nice if we could make the Qt-package easily update-able for future changes (Qt 5.15 had some HDR improvements for example.

**Comment by RytoEX** [comment]
> Should close #2634.
> 
> @DDRBoxman Could explain how the `Qt_5.10.1.7z` is compiled and zipped? I see two binaries, one for 32-bit and one for 64-bit. Which components of Qt need te be included? Only the GUI or more?
> 
> Would be nice if we could make the Qt-package easily update-able for future changes (Qt 5.15 had some HDR improvements for example.

@EwoutH Last I checked, Jim builds Qt himself for Windows and we use zips of that.  It's possible that has changed, but that's what I remember from the last time I dug into updating Qt.

**Comment by DDRBoxman** [comment]
Latest releases should be on 5.15.2
 https://github.com/obsproject/obs-studio/issues/3752

**Pull request closed without merging**
