### PR TITLE
xdg-data: Add to dotdesktop a desktop action to use obs with wayland

### PR DESCRIPTION
**Pull request by tytan652**
### Description

It adds desktop actions to the dotdesktop file:
- One which only launch OBS
- One which launch OBS with QT_QPA_PLATFORM=wayland

~The only issue here is translation or the actions name, this is why it's a draft~
Note: The Wayland action will appear even on X11 Gnome session

Some feedback to improve this are welcome.

OBS-dotdesktop

### Motivation and Context

Since Qt5 decide to default to x11, I created a way to launch it with Wayland without the use of a terminal

### How Has This Been Tested?

I put the new dotdesktop to `~/.local/share/applications/` and check my activity tab since I'm under Gnome.
And try to launch both action under Wayland.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Vainock** [comment]
_The only issue here is translation or the actions name_

What exactly is the issue?

The tool that is used to pull the translations and to generate the AUTHORS file now also includes adding translations for the Comment and GenericName fields. I can also add support for your 2 strings after the PR was merged, so the 2 new strings also receive translation.

**Comment by tytan652** [comment]
@Vainock actually the dotdesktop file is manually translated in french and a little in russian. There is no automation about the translation for the dotdesktop file. So my PR will only put english sentences when showing the menu like in the screenshot.

**Comment by Vainock** [comment]
Okay.

The translation for this file is already "automated" since a few weeks (and also available on Crowdin), so new translations will be added for many languages and the old French and Russian translations removed/updated during the next translation update. If this PR gets merged I will also implement support for these strings, you do not have to do anything on that.

**Comment by tytan652** [comment]
@Vainock Okay, so I put it out of draft

**Comment by tytan652** [comment]
Qt doesn't use Wayland with only Gnome because of [this](https://bugreports.qt.io/browse/QTBUG-68636) and it seems this limitation will maybe be removed when Wayland 1.20 is out. Because the bug is only on gnome-shell.

**Pull request closed without merging**
