### PR TITLE
Add HLS streaming output

### PR DESCRIPTION
**Pull request by ushadow**
### Description

Adds an [HLS](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07) streaming output option based on the FFmepg's HLS muxer output.

#### obs-ffmpeg changes
Adds a new `ffmpeg_hls_muxer` `obs_output_info` struct. This new output is verify similar to the existing `ffmpeg_muxer` `obs_output_info` struct, except for a different start function. Within this start function:
- sets the HLS ingestion URL from service's URL and stream key settings
- sets HLS segment duration option `hls_time` based on key frame interval duration
- sets `http_user_agent` to "libobs/<OBS_VERSION>"  

#### Services changes
Adds a new service for "YouTube - HLS" in services.json. Adds support for a new more_info_link field in services.json.

#### UI changes
In both auto configuration and basic settings UI, adds a new "More Info" button next to the Service combobox if more_info_link is set in the service settings. This allows services to optionally provide more information on how to use their services.

YouTube - HLS service option

### Motivation and Context

HLS live streaming is supported by a number of platforms. It is a generic output method. FFmpeg has an HLS option as a muxer output: https://ffmpeg.org/ffmpeg-formats.html#hls-2. If a URL is specified, it will stream the output to the destination. Akamai has a [specification](https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-6A14ED6D-0A23-4122-AB60-64A49B6628B5.html) for HLS ingestion as well. Many hardware encoders support HLS output. YouTube also supports HLS ingestion for live streaming and its [specifications](https://developers.google.com/youtube/v3/live/guides/hls-ingestion) are compatible with others.

HLS can support next generation codecs that RTMP does not. Newer codecs can offer much better compression relative to
H.264, allowing users to stream with higher quality for a given bitrate, or stream with the same quality while using a lower bitrate decreasing buffering.

Currently one can do HLS streaming output using OBS by setting FFmpeg HLS option in the recording output settings with a URL output path, and starting to record. This is a bit convoluted though. This PR makes the HLS streaming output option more user friendly and more accessible. Also see [RFC](https://github.com/obsproject/rfcs/pull/26).

### How Has This Been Tested?

- Tested on macOS Mojave 10.14.6 against the YouTube HLS service.
- Verified the stream health is good. 
- Verified the segment duration changes after setting key frame interval.
- Verified "More Info" button works correctly in both Auto-Configuration Wizard and basic Settings. 

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
It might make sense to also set the `ignore_io_errors` option for ffmpeg, otherwise ffmpeg would likely kill the output when uploading a single segment or playlist fails, rather than dropping that segment and contiuing to stream.

The ffmpeg documentation has this to say:
> **-ignore_io_errors**
> Ignore IO errors during open, write and delete. Useful for long-duration runs with network output.

**Comment by ushadow** [comment]
@derrod That's a good point. We'll add `ignore_io_errors` option.

**Comment by sperok** [comment]
Using the existing OBS output>recording functionality if the encoder frame rate is too low Youtube will fail for a viewing client, forcing them to restart their browser to recover. The broadcaster is not notified and no error is logged. Can this be improved with the development subject to this RFC? Possibly with a warning about YT dropping frames.

**Comment by ushadow** [comment]
@sperok I tested YouTube - HLS streaming option with 10 FPS, and it seems to be working fine.

**Comment by sperok** [comment]
We do live sports at 4k60. 10fps is a nice data point but not close to
being useful. Unfortunately our production system is currently locked down
and can't be used for full bandwidth testing.

**Comment by ushadow** [comment]
@sperok Based on your earlier comment, I thought you had problems with low frame rate, so I tested 10 FPS. But YouTube - HLS should work with 60 FPS as well.

**Comment by sperok** [comment]
@ushadow - The issue we have is that the OBS or uplink bandwidth may have intermittent failures. OBS may encounter encoding issues resulting in failure to send frames at the expected rate. Unexpected network congestion may also reduce effective frame rate. When this happens the end user gets a bad experience. YouTube will tell them "The video is no longer available". They can recover by refreshing their browser, but we as the broadcaster through OBS do not get any notification and may be blind to the issue.

**Comment by derrod** [comment]
I tested this for a bit but for some reason I get a significant amount of encoder lag while using HLS output (note that encoder lag is a broad term in OBS and may also indicate issues with the muxer, rather than the encoder). Everything works perfectly fine however when switching back to RTMP. This also seems to be worse when using Nvenc hardware encoding compared to x264.

Stopping the stream also does not work after being live for a few minutes, OBS gets permanently stuck on "Stopping Stream..." and I've had one occurence where the output bitrate dropped to 0 and OBS stopped sending data. This maybe be the result of an ffmpeg error that isn't handled.

Finally the output should not leak the stream key to the log file.

**Comment by ushadow** [comment]
@derrod Thanks for the feedback! We'll look into these issues. Did you test on Windows? What resolution, bitrate and key frame interval did you use? We haven't encountered OBS permanently stuck on "Stopping Stream" issue so far.

**Comment by derrod** [comment]
Yeah I'm on Windows.

I was using 1440p60 and 1080p30 resolutions, with 25 Mbps bitrate and a 2 second keyframe interval. I used the veryfast/superfast presets with x264 on a fairly static scene to make sure there's no actual encoding bottleneck happening.

Dropping the bitrate seemed to reduce the number of frames that were "dropped" but still had that issue. Again this doesn't seem to be an issue with RTMP or when using the ffmpeg command line directly to push out a 6 Mbps video file via HLS.

**Comment by ushadow** [comment]
@derrod I wonder if it's because the obs-ffmpeg-mux.c implementation is not very efficient, and if obs-ffmpeg-output.c implementation might be better.

**Comment by ushadow** [comment]
@derrod Do you check the encoding lag based on the following log?
info: Video stopped, number of skipped frames due to encoding lag: 1162/34816 (3.3%)

I suspect there might be a bottleneck in writing to the pipe if the pipe capacity is full. The obs-ffmpeg-mux.c implementation runs FFmpeg muxer as a separate process. We can try to add a buffer and create another thread to write to pipe so that it doesn't block the encoder thread.

**Comment by derrod** [comment]
@ushadow I used the OBS stats window (view->stats) to monitor encoding lag while streaming but yes that also results in that log entry.

I'm not too familiar with the internals of the ffmpeg muxing process but that could be right. It would explain why a higher bitrate results in worse performance at least.

**Comment by ushadow** [comment]
Hmm, HLS streaming is not working after merging with master.

**Comment by ushadow** [comment]
Fixed HLS streaming by setting stream->codec->time_base.

**Comment by ushadow** [comment]
Hi, we have removed the stream key in the loggings and added threading logic to prevent skipped frames. Our testings show the number of skipped frames is comparable with RTMP now.

**Comment by derrod** [comment]
Thank you, I hope I can get around to testing it for a bit later today or tomorrow.

**Comment by jp9000** [comment]
Oh I see there's congestion handling. I'll check this out.

**Comment by ushadow** [comment]
Synced with master and resolved conflicts.

**Comment by jp9000** [comment]
Thanks. Some of these commits might need squashing.

**Comment by ushadow** [comment]
@jp9000 Sure, I can squash the commits. Do you prefer one commit per module?

**Comment by jp9000** [comment]
One commit per module is fine for now.

A good way to think about commits is let's say for example that you're making changes, and you realize you need to rearrange/refactor functions/structures in order to accommodate your change better (like where you move a structure into a header file). You'd want a commit for that refactor first by itself, then you'd want the actual changes you want to do to it in another commit after that. That way, it prevents the rearrange/refactoring from becoming "white noise" to your change. To make good commits, it's more about making each commit as readable as possible to the reviewer, so the reviewer has the whole picture clearly, but with as little unrelated interference/whitenoise going on as possible -- like in the refactor example. It also makes it better when bisecting bugs. You usually want each commit to have as few specific changes and readable as possible, while still also being as complete as possible, if that makes sense. If you have commits that fixes up an issue in a prior commit, you'd want to squash them back in to that commit. And if you have too many separate changes in a commit that's causing it to be hard to see what's going on in the diff (white noise), it's usually best to split. It's all about making each diff for the commit as clean and as efficient as possible. That way it reduces the possibility of review error, and improves the ability to spot bugs or bisect for bugs later.

Sorry, hope I'm not sounding picky. You don't necessarily have to do those things this time around, mostly just something to keep in mind for the future. Just conveying what seems to work best in my experience.

**Comment by ushadow** [comment]
@jp9000 Thanks for the explanation! I squashed the commits. That makes sense. I didn't think about you look at each commit separately. I was just looking at the PR as a whole.

**Comment by jp9000** [comment]
It seems okay so far, but I'm going to attempt to test the frame drop code. It'll be interesting to see how the ffmpeg-mux subprocess handles it.

**Comment by Gol-D-Ace** [comment]
Hi
I gave this a try yesterday and today.

After less than 2 minutes I see the Kbps dropping to 0 and OBS starts to dropping frames. The connection indicator (square) stays green the entire time.

I tried this with different Encoders (x264, NVENC, QSV) and see no difference in behavior.

Switching to RTMP instantly stops this behavior.

**Comment by ushadow** [comment]
@Gol-D-Ace Thanks for testing. I haven't seen this behavior before. I have only tested on macOS though. Are you testing on Windows?

**Comment by Gol-D-Ace** [comment]
Yes this is on Windows 10 Pro x64 2004

**Comment by ushadow** [comment]
@jp9000 Seems like with the merged changes, the stream key is printed in the log when I tested. Should stream key be filtered regardless of whether DEBUG_FFMPEG is defined or not?

**Comment by ushadow** [comment]
@Gol-D-Ace I'll try to test on windows as well.

**Comment by jp9000** [comment]
@ushadow Sorry about that if so, I'll check it out.

**Comment by jp9000** [comment]
Just for the record, the only thing I changed was the printable string stuff a little bit (removing redundant checks), almost everything I did was just split commits.

**Comment by jp9000** [comment]
Ah wait, if you're on on macOS then it's possible you're seeing the output of the obs-ffmpeg-mux subprocess -- I can't see that on windows. I'll check to make sure that's not doing that as well.

**Comment by Gol-D-Ace** [comment]
Gave this now also a try on Linux (Ubuntu 20.04) and there it's working fine for me.

I notice the streamkey there as well but only in the terminal that shows the uploads of the ts files.

**Comment by jp9000** [comment]
Yea, it's because of the obs-ffmpeg-mux subprocess. That doesn't get output on Windows so I never saw it. I'll fix it because that was my fault.

**Comment by jp9000** [comment]
I added a cmake variable for debugging the ffmpeg-mux subprocess (particularly on Windows): https://github.com/obsproject/obs-studio/commit/18486853a55ae8842b80633d645abb234a279416 -- to enable, just set the DEBUG_FFMPEG_MUX variable to enabled. It will also enable the DEBUG_FFMPEG macro in the ffmpeg-mux subprocess, and on Windows, it will show the console window of the ffmpeg-mux subprocess while it's active.

Strangely, I'm not getting disconnects. I also did not reproduce the issue where it shows the stream key -- in the ffmpeg-mux subprocess I still do not see the stream key, it replaces it with `{stream_key}`. I'll test on macOS as well shortly, maybe it's more reproducible there.

**Comment by RytoEX** [comment]
I can confirm that streaming via HLS results in the stream dropping to 0 kbps within a minute.

**Comment by jp9000** [comment]
I sort of figured it out, apparently if the FFmpeg logging is off on Windows (the line where I put the FFmpeg logging in the DEBUG_FFMPEG ifdef), it causes it to fail. If it's on, it works fine. This is very strange. That explains why the problem didn't appear until after I split the commits.

It's a good hint but I don't have a theory behind it yet other than the fact that it has something to do with FFmpeg's logging, possibly combined with the fact that on Windows, it runs in a separate isolated subprocess console that doesn't normally get stdout.

**Comment by WizardCM** [comment]
I second Jim's findings on this. Windows 10:

* **Without** the DEBUG_FFMPEG_MUX variable enabled, stream drops to 0 kbps within seconds.
* **With** the DEBUG_FFMPEG_MUX variable enabled, stream works as it should. Tested for >2 minutes.

**Comment by jp9000** [comment]
Well I have a fix for now: https://github.com/obsproject/obs-studio/commit/0b24b3ae1413785a892bdb58dd661170999e59d1

I have no idea why it requires a logging function to be set in order for it to work on Windows, but it does. My original intention with adding the DEBUG_FFMPEG macro was so it wouldn't spam the output needlessly every time, but it seems HLS (at least on Windows) needs an FFmpeg logging function to be set in order to function.

**Comment by jp9000** [comment]
https://github.com/obsproject/obs-studio/commit/0b24b3ae1413785a892bdb58dd661170999e59d1 also fixes the issue with the stream key being output to the terminal on non-Windows systems when running via the terminal (that was the bug you were seeing @ushadow, sorry about that)

So the issues with it should be fixed. Apologies for causing troubles there.

**Comment by Gol-D-Ace** [comment]
Looking good now on Windows as well with Jim's fixes on master.

**Comment by ushadow** [comment]
Thank you for the fixes @jp9000 !

**Comment by jp9000** [comment]
No problem! Sorry for the trouble, that was my fault.

**Comment by JocPro** [comment]
Now that we got HLS working, can we remove the harcoded blacklist for HEVC in the streaming encoder selection? I tested it with Youtube and it works fine.

**Comment by dodgepong** [comment]
Not until we're clear of licensing concerns.

**Pull request merged**
