### PR TITLE
linux-capture: Add libdrm dependency check

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

We require libdrm for its header so add the cmake module and header path
to the build. We don't need to link libdrm though so we dont add it to
libraries.

### Motivation and Context

Some users might fail to build due to missing deps if they dont have this library installed. See #5325

### How Has This Been Tested?

Compiles and checks the module on my machine.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by GeorgesStavracas — APPROVED** [review]
I thought this would be pulled by PipeWire's pkgconf, but I was wrong. Thank you for fixing it!

**Comment by GeorgesStavracas** [comment]
The Flatpak job is also happy with this change :+1:

**Comment by PatTheMav** [comment]
Moving forward, could we please not merge PRs that add/change build-level stuff that uses outdated CMake patterns?

The finder doesn't create proper targets for the library, like so:

```
  if(NOT TARGET Libdrm::Libdrm)
    if(IS_ABSOLUTE "${LIBDRM_LIBRARIES}")
      add_library(Libdrm::Libdrm UNKNOWN IMPORTED)
      set_target_properties(Libdrm::Libdrm PROPERTIES IMPORTED_LOCATION
                                                      "${LIBDRM_LIBRARIES}")
    else()
      add_library(Libdrm::Libdrm INTERFACE IMPORTED)
      set_target_properties(Libdrm::Libdrm PROPERTIES IMPORTED_LIBNAME
                                                      "${LIBDRM_LIBRARIES}")
    endif()

    set_target_properties(
      Libdrm::Libdrm PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                "${LIBDRM_INCLUDE_DIRS}")
  endif()
```

The library then needs to be added using `target_link_librares(linux-capture PRIVATE Libdrm::Libdrm)` (though the target can probably be used instead of the variable as-is, linux-capture annoyingly uses _both_ `target_link_libraries` and `add_library`. Both files are also not formatted using `cmake-format`.

CMake scripts are code. Treat it with the same care.

**Comment by kkartaltepe** [comment]
Libdrm the library is not a dependency and very much should not be linked.

**Comment by PatTheMav** [comment]
Linking an interface library just adds the interface include directory to the target. Thus `target_link_library` is the correct way with interface libraries.

**Comment by kkartaltepe** [comment]
Got it, I hope you are not too frustrated but I didnt want to dig in your PR to figure out how to do this and assumed you would know better :)

**Comment by PatTheMav** [comment]
Not at all - just trying to pave the way to good practices early. I already adopted the change. 👍🏻

**Pull request merged**
