### PR TITLE
obs-filters: Add 9 slice border filter

### PR DESCRIPTION
**Pull request by DDRBoxman**
Filter that uses 9 slice scaling to add non distorted borders to arbitrarily sized sources.

https://en.wikipedia.org/wiki/9-slice_scaling

Expects input images to be in the android 9 slice format:
https://developer.android.com/studio/write/draw9patch

slice

### CODE REVIEW

**Comment by DDRBoxman** [comment]
Example 9 patch image that gets loaded here. Note the black border showing padding 
/ content bounds. https://github.com/obsproject/obs-studio/blob/f953ab680a6e32dea297d8ae93a68044662e6833/plugins/obs-filters/data/cool2.9.png

**Comment by DDRBoxman** [comment]
screen_shot_2019-01-28_at_6 54 28_pm

another example of the filter being used (source is scaled), placed next to the image that was loaded.

**Comment by SuslikV** [comment]
Usage is very limited. It has no repeat, only stretching. CSS allows repeat, stretch and round for the border images for example.

In case this is optional filter (until now it is not), why not to add the options?..

**Comment by DDRBoxman** [comment]
I'm going to close this and maybe rework it into a plugin. It's probably a little silly to include this in core.

**Pull request closed without merging**
