### PR TITLE
cmake: check empty OBS_MODULE_LIST and OBS_SCRIPTING_MODULE_LIST on macOS 

### PR DESCRIPTION
**Pull request by quink-black**
# Description

Check empty OBS_MODULE_LIST and OBS_SCRIPTING_MODULE_LIST before use them, since empty list leads to add_dependencies() failure.

# Motivation and Context

Don't fail when -DENABLE_SCRIPTING=OFF.

# How Has This Been Tested?

On MacOS, tested with -DENABLE_SCRIPTING=OFF and -DENABLE_SCRIPTING=ON.

# Types of changes

* Bug fix (non-breaking change which fixes an issue) 

# Checklist:
 
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [contributing document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
Please make sure to fill out the PR template instead of deleting it.

**Comment by RytoEX** [comment]
I've converted this to a draft until the PR template is filled out and details are provided. What platform do you observe this behavior on? What is the error message?

**Review by PatTheMav — APPROVED** [review]
Looks fine to me, having an empty list evaluate to an empty string (and thus to `false`) is a bit of implicit CMake sorcery, but I'll allow it.

Note that the same check should be added for `OBS_MODULE_LIST` as well, preferably in a separate PR.

**Comment by RytoEX** [comment]
> Looks fine to me, having an empty list evaluate to an empty string (and thus to `false`) is a bit of implicit CMake sorcery, but I'll allow it.
> 
> Note that the same check should be added for `OBS_MODULE_LIST` as well, preferably in a separate PR.

Is there a more correct/modern method? If so, we should probably just use that.

**Comment by PatTheMav** [comment]
> > Looks fine to me, having an empty list evaluate to an empty string (and thus to `false`) is a bit of implicit CMake sorcery, but I'll allow it.
> > Note that the same check should be added for `OBS_MODULE_LIST` as well, preferably in a separate PR.
> 
> Is there a more correct/modern method? If so, we should probably just use that.

Not really, there is a more convoluted method of using the `list` function to return the actual length of the list into a parameter, followed by a numerical `> 0` check on that. But CMake lists are in essence just semicolon-separated strings, so checking for string length is as good.

**Comment by WizardCM** [comment]
Please validate using cmake-format, and once you've pushed the fix I'll merge this.

**Comment by gxalpha** [comment]
This PR breaks macOS builds on both my local build as well as CI (plugins don't get copied over into the app bundle anymore at all).
I think it should get reverted for now.

**Pull request merged**
