### PR TITLE
enc-amf: Reinstate AMF 1.4.14 with driver version check

### PR DESCRIPTION
**Pull request by jpark37**
### Description
This should avoid us having to support old AMD drivers. Error messages from out-of-process validation should also be propagated correctly now.

The new driver requirement excludes Windows 8 entirely. People with AMD cards should still be able to use OBS on Windows 8, but they won't be able to use AMF.

This adds support for Navi cards.

### Motivation and Context
AMF branch was stalled because of stability issues, but the driver check and error fixups should put us in a better position to either have fixed them, or leave issues that are more reasonable to triage. That's the hope at least.

### How Has This Been Tested?
Breakpoint inspection. AMF gracefully fails to load on my NVIDIA PC with AMD drivers installed, and I was able to record a video with AMF on my Vega. Someone may want to give WIndows 8 a spin though...

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Xaymar** [comment]
> AMF fails to load gracefully on my NVIDIA PC with AMD drivers installed.

Are you running a multi-GPU setup?

**Comment by jpark37** [comment]
No, I just left the AMD drivers installed when I swapped cards.

**Comment by Xaymar** [comment]
> No, I just left the AMD drivers installed when I swapped cards.

That should just cause the AMF plugin to fail in the test, what was the actual behavior you saw? It should just refuse to load the plugin.

**Comment by jpark37** [comment]
Yes, it failed to load as expected; nothing out of the ordinary. It's the log output that I reported in https://github.com/obsproject/obs-amd-encoder/pull/385. I'm about to switch cards, and make sure I can still record videos with AMF.

**Comment by Xaymar** [comment]
There's a pending 2.6 release once my hardware leaves RMA hell on Saturday for testing.

**Comment by jpark37** [comment]
Seems to work on my Vega.

**Comment by jpark37** [comment]
Assuming the checks complete, I think this is ready to go.

**Comment by Xaymar** [comment]
@WizardCM 2.6 should fix or work around most of the issues. Next OBS update though definitely needs a patch note entry to state the removed support for drivers older than 19.9.2 and Windows 8.

**Pull request merged**
