### PR TITLE
obs-ffmpeg: add multiple replay buffer time limits

### PR DESCRIPTION
**Pull request by TheDark**
### Description
Added the option to specify how much of the time buffer should be saved.
This is only achievable via script for now. It's a valid first step, as
it allows to define multiple hotkeys for multiple durations.

The way it works is via the supplied lua scripts, which can be duplicated
and modified to support more lengths:
lua script time config

The script adds a hotkey to the configuration, with a description of
what the length is:
hotkeys description

### Motivation and Context
Sometimes we need a replay buffer several minutes long.
Other times we only need a few seconds. This allows just that.
Implements a feature request from the Ideas page: https://ideas.obsproject.com/posts/263/multiple-replay-buffer-hotkeys-with-different-time-length

### How Has This Been Tested?
Tested on Windows 10 64bit with the most recent updates.
OS and hardware shouldn't affect the changes as all that was
changed is how much of the replay buffer is saved to disk.
If anything, it's less stressful on the hardware.

Testing was done by leaving the replay buffer running and
occasionally saving different lengths of it to disk. Specific
lengths used were 15 minutes/500MB (total regular replay
buffer duration), 20 seconds and 180 seconds (via lua script).

No problems were detected.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Wouldn't it be better to have the time configurable in the script itself, rather than being hardcoded and requiring that an end-user modify the code directly to adjust the timing. It would be better if the script allowed adding a new hotkey for a custom duration rather than needing to load a separate script for each value desired.

That aside, you will need to squash your commits and update the commit titles appropriately. This should probably be broken up in to two commits, one for the ffmpeg change, and the other for the scripts themselves (which should be prefixed with `frontend-tools` as that is where scripts are located).

**Comment by dodgepong** [comment]
I kind of don't like the idea that this has to be handled via a script to begin with. Ideally, of course, we could have multiple replay buffer outputs, but that's a bit beyond where our outputs UI is right now. That said, I don't know how comfortable Jim will be with including what strikes me as a bit of a hack in the OBS core codebase.

**Comment by TheDark** [comment]
> It would be better to have the time configurable in the script itself, rather than being hardcoded and requiring that an end-user modify the code directly to adjust the timing.

Seems obvious now that you mention it 🙄 I'll look into it in the weekend!

> It would be better if the script allowed adding a new hotkey for a custom duration rather than needing to load a separate script for each value desired.

My goal is to not need a script at all, but this was the fastest way I found to test it without learning to code the UI, and it worked so well I decided to share. I haven't looked too deep into scripting, and I'm not sure how dynamic I can make the script configuration UI, but I'll look into that too.

> That aside, you will need to squash your commits and update the commit titles appropriately. This should probably be broken up in to two commits, one for the ffmpeg change, and the other for the scripts themselves (which should be prefixed with `frontend-tools` as that is where scripts are located).

Will do 🙂

> I kind of don't like the idea that this has to be handled via a script to begin with.

Neither do I. The good news is that it is perfectly possible to do it via the application UI and all be handled without scripting. All it needs is some UI coding, which I'm not comfortable with (yet) and hence I didn't do it (yet).

> I don't know how comfortable Jim will be with including what strikes me as a bit of a hack in the OBS core codebase.

Calling it a hack seems a bit too harsh to me 😅 I'd call it adding functionality to the scripting capabilities of OBS (for now 😁)

Thanks for the comments 😀 I'll be back! 😎

**Comment by TheDark** [comment]
Progress: no more scripts needed, working on getting it fully integrated in OBS
replay buffer configuration page

**Comment by TheDark** [comment]
Progress: no more scripts needed, working on getting it fully integrated in OBS
replay buffer configuration page

**Comment by jp9000** [comment]
I actually think script is appropriate.  The reason why is because OBS has to be set to a value larger than these values to begin with for this to work.  It's inherently scuffed solution for lack of better term, and there is not much else you can do about it.  This change can only be used to reduce the current save size, so if the user has the replay buffer set to like 15 seconds, they would not be able to use either of these.  If these features shipped with OBS by default, users would be completely confused at why they didn't work in some cases.  I just don't like the idea of having a feature that requires another feature be set to above a specific value.

Therefore, having this be a script is an acceptable solution because it sort of implies that it's extending the feature beyond its intended use in a way.

**Comment by dodgepong** [comment]
IMO, the most _ideal_ solution is to allow users to add multiple outputs, where each output could be its own replay buffer. Obviously that requires the fabled outputs UI overhaul first, though it would also presumably consume more RAM as well.

**Comment by jp9000** [comment]
So do you feel we should just close this until that point then?

**Comment by TheDark** [comment]
> I actually think script is appropriate. The reason why is because OBS has to be set to a value larger than these values to begin with for this to work.

I am limiting the spinbox max value to the value set above, plus the option is called "extra", plus I am checking the list when saving options to make sure no "extra" values larger than the full Replay Buffer value are present, and warn about it if there are. Do you think that isn't enough for most users to understand how it works? 

> Therefore, having this be a script is an acceptable solution because it sort of implies that it's extending the feature beyond its intended use in a way.

The script way is half done and is a lot less work than integrating this into the application, but personally I would prefer it to be integrated.

> IMO, the most ideal solution is to allow users to add multiple outputs, where each output could be its own replay buffer. Obviously that requires the fabled outputs UI overhaul first, though it would also presumably consume more RAM as well.

Multiple replay buffers outputs would (as I understand it) take not only more RAM but also more processing. I was pleasantly surprised to learn that the implementation of multiple RB lengths without further stress on the system was possible (kudos for that! 🙂). Actually, kudos for OBS in general! 😁

While multiple outputs may be useful in some (I'd think) more advanced scenarios, the idea here is a simpler one: to have multiple Replay Buffer save times, as is described in the Ideas link above. This achieves that, be it via scripts or integrated into the app.

I've been using the initial script version for a few days and I'll keep using it. It's a useful feature for me, and it probably would be for (I'd dare to say many, or at least a few) others, and I would love to share it. Whether it's a temporary panacea or a feature for the long run is up to you! 😄

**Comment by jp9000** [comment]
> Do you think that isn't enough for most users to understand how it works?

Never underestimate most user's ability to not understand something.

**Comment by TheDark** [comment]
> Never underestimate most user's ability to not understand something.

I did expect that answer 😅

**Comment by dodgepong** [comment]
> So do you feel we should just close this until that point then?

Up to you. I feel like features buried exclusively inside scripts are the most difficult-to-find features in OBS, and the original scripts were only ever added as examples and not really intended to plug holes in actual functionality. If we merge the script version, then for most people the feature might as well not exist. The main thing it buys us is that it gives us an answer for people asking about the feature, so that they can at least do _something_. I'm just worried that, if this exists, it would demotivate a more comprehensive solution in the future. There's nothing so permanent as a temporary solution.

**Comment by TheDark** [comment]
Ok, it's all working, scripts and config. I just fail hard at git sometimes :P

> The main thing it buys us is that it gives us an answer for people asking about the feature, so that they can at least do _something_.

Yes. 100x yes.

> I'm just worried that, if this exists, it would demotivate a more comprehensive solution in the future.

I think a "more comprehensive solution" is not something that would replace what this does, but a fulfillment of other requirements.

I will keep using this version both because I have a need for the feature, and to test it to make sure I didn't do something stupid.

Thanks for your time ;)

**Comment by jp9000** [comment]
No, I'm closing this until we get a better outputs framework in the UI.   I really don't want to mess with this much code for something that we'll just end up changing later.  We allow too much technical debt as it is.  I don't mind some of the functions inside of the plugin to make your script possible, but I don't want to be messing with the UI or adding the scripts themselves.

**Comment by dodgepong** [comment]
Would it be appropriate, then, to request a PR for just the changes that would make the script possible, then have TheDark submit the script to the resources section of the forums?

**Comment by jp9000** [comment]
Yes, I apologize.  Feel free to make a pull request for the internal changes that allow the script to be possible.

For the time being though, I would prefer not having the other changes.  I feel like we probably shouldn't be adding scripts either if we can avoid it, as the current ones are really meant more to be examples.  Plus every time we add a script we have to maintain it, and then people start making pull requests for them to change them, and it can just become a bit of a nuisance.

**Comment by TheDark** [comment]
I totally understand. I will open a new PR tonight with only the script bindings.

**Pull request closed without merging**
