### PR TITLE
UI: Convert properties to tabbed interface

### PR DESCRIPTION
**Pull request by cg2121**
TODO: 
- ~~Try to add hotkeys tab~~
- ~~Fix segfault when opening and closing properties multiple times~~
- ~~Add interface for scenes and transitions~~
As a byproduct, transitions now have filters.
screenshot from 2018-04-07 04-13-14

### CODE REVIEW

**Comment by dodgepong** [comment]
This is very cool, I've been wanting something like this for a while. My main concern is whether it's clear enough to users that the General and Filters tab affect all sceneitems for that source, whereas the Transform tab only affects the selected sceneitem? Is there a UX concern there, or am I just paranoid?

**Comment by c3r1c3** [comment]
This would be an excellent opportunity to express that difference @dodgepong, but as to details, you how Jim is about the interface.

**Comment by WizardCM** [comment]
Some sort of split, maybe? Or a second layer of tabs at the top of the window? Or move the General/Filters/etc tabs to the bottom (up-side down) and put two tabs to choose between global/this scene in the current spot.

Image

**Comment by SuslikV** [comment]
It is no way good, all this tabs. The preview on top is not the best thing and you reduces the space for properties even more by these tabs. The tabs should cover all properties (interlacing, filtering, transition overriding etc.).

What purpose for this? Fast access to functions? Or just reminder that filter exist for the source? Then it is not the best place where it shown.

**Comment by WizardCM** [comment]
Primary purpose is discoverability, and secondary purpose is to lower the number of things in right click menus. Lots of people don't know about Transform, because they don't use the right click menu.

**Comment by SuslikV** [comment]
Toolbar? It always visible if not hidden. Also, tabs is scrollable on Windows with mouse even without keyboard focus. And this behavior wouldn't be changed soon.

**Comment by cg2121** [comment]
The hotkeys tab is now finally added.

**Comment by WizardCM** [comment]
@cg2121 Looking good! I explored the PR today, here's what I found:

Crash traceback
* **In Simple mode, if you enable the replay buffer, attempting to open properties for any source or scene will crash OBS, complaining about the hotkeys enum**
* Personally, I think source hide/show hotkeys should appear both in a scene's hotkeys tab, and the relevant source's. I like them being in a consolidated location (ie the scene) and visible specifically in that source's properties. Groups should also contain all hotkeys for themselves and any child sources
* Double clicking a source opens the properties, but double clicking a scene does not. Properties also seems to be missing from the dropdown for a Scene
* The Source/scene hotkeys tab is not a scrollable container, so a scene with a lot of sources will result in a really tall properties window that cannot be made smaller, even if the hotkeys tab isn't open
* The height of the source properties window is now defined entirely by hotkeys or by transform, whichever's taller
* The height of the properties does not reset if you switch from a tall scene with lots of sources, to a source with few hotkeys
* Transform shortcuts available in the right click menu like Reset, Rotate, Flip, _ to screen should be added to the Transform tab
* There should be a message in the Hotkeys screen of Settings to let the user know that majority of their hotkeys have moved to a more... logical location
* If no hotkeys are available for a source/scene, the tab should either be disabled, or when switched to, should display a message similar to the general tab which can sometimes say "No properties available"
* Would it be possible to move the Game capture source's SLI/Crossfire option should be moved to the Advanced tab, as well as the Video Capture Device's Color Space/Range & Video Format? I'd vote for a "advanced" property that can be set for each.. property, making it relatively dynamic, and a way for plugins to set their own sources' properties to advanced if needed
* How hard would it be to make the preview in properties inherit the capabilities of Interact if a source can be interacted with? One less window for the user to open, and everything in one place
* The default themes will need to be updated to visibly show disabled tabs, as proven by the Properties window for an Audio source, Transform/Advanced are disabled
* Why does an Audio source added via Settings -> Audio have Transform and Advanced tabs (even if disabled), while a Transition does not? Feels inconsistent. I'd vote they all show all possible tabs even if they're not relevant, as long as the user can tell they're disabled

Overall, _love_ how consolidated everything feels, and just how much more discoverable certain aspects are. Not to mention how much cleaner the Hotkeys window looks with just global hotkeys in it - man it's beautiful. Awesome work!

**Comment by cg2121** [comment]
I've done a bit of a refactor of this PR. @WizardCM I've implemented most of things you suggested. Still can't figure out the crash when enabling the replay buffer.

This is what the interface currently looks like:
screenshot from 2018-08-28 23-11-05

**Comment by Andersama** [comment]
Some examples of some weird stretching of widgets:



For scenes I'd suggest not listing all of the show / hide keys at least not w/o some break / label. Also it feels a bit off that the show / hide hotkeys don't show up in the source's list of hotkeys.

**Comment by cg2121** [comment]
I will close this because the code is very sloppy and has several issues. A redo of properties is currently planned anyway.

**Comment by cg2121** [comment]
I have reopened this because I fixed the replay buffer bug and fixed the memory leak I was getting. I also cleaned up the code a bit.

**Comment by cg2121** [comment]
I have now rebased to master and applied clang formatting.

**Comment by cg2121** [comment]
Update:
I've simplified the code further by using stacked widgets for the tabs.

**Comment by cg2121** [comment]
I've now removed the hotkeys tab to simplify the code. I think it is better to have hotkeys all in one place. The hotkeys should also be redesigned in the settings.

**Comment by WizardCM** [comment]
Friendly bump: there are merge conflicts.

**Comment by skeletonbow** [comment]
One suggestion I'd like to offer, is if it doesn't already do this please make it so that when the window itself is resized, the default split between the preview pane and the properties underneath divide the additional space between the preview and the properties so that if a user maximizes the window or stretches it to see a long list of properties and be able to manipulate them, some or all of the extra space is actually given to the properties portion and not all to the preview pane like it is in current versions of OBS.  Also would be a friendly user experience to have a draggable divider line between preview and properties with a remembered state between invocations of popping up the properties.

**Comment by cg2121** [comment]
Closing for now in favor of #1838. The goal of this is to make finding stuff easier, the context bar PR also accomplishes that. This will be reconsidered in the future.

**Pull request closed without merging**
