### PR TITLE
UI: Add support for external plugins linking to the frontend API

### LINKED ISSUE #2625: [BUG] Doesn't install obs-frontend-api.h
summary of the issue in the Title above -->

## Platform
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.1

## Expected Behavior
Install obs-frontend-api.h

## Current Behavior
Doesn't install obs-frontend-api.h for users to be able to use lib/libobs-frontend-api.so

## Steps to Reproduce
Try to compile obs-websocket with obs-studio installed from a package, and it would fail with a missing header.

### PR DESCRIPTION
**Pull request by Xaymar**
### Description
Adds support for external plugins that wish to link to the frontend API by simply importing the CPack package into their project, instead of relying on manually dynamically linking.

This PR is similar to #2635, with the exception that this also adds the CMake files and a .pc file. The goal is to fix #2625 completely.

### Motivation and Context
Got tired of writing manual os_dlopen, os_dlsym, os_dlclose code. Allows me to add things to the Tools menu without doing that.

### How Has This Been Tested?
* In progress.
* 2020-04-05T06-17 Packaged format is as expected.
* 2020-04-05T08-26 [It works!](https://cdn.xaymar.com/private/2020-04-05/2020-04-05T10-25-49_obs64_CoarseCloudyHeifer.png)

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Xaymar** [comment]
Tested and confirmed working with StreamFX. Was able to add an entry to the Tools menu and react to clicks on it.

**Comment by yurivict** [comment]
> and a .pc file

.pc file isn't installed.

**Comment by Xaymar** [comment]
You're right, I still have to add this section to the cmake:
```
if(UNIX AND NOT APPLE)
	set(DEST_DIR "${CMAKE_INSTALL_PREFIX}")
	foreach(LIB "obs" "rt")
		set(PRIVATE_LIBS "${PRIVATE_LIBS} -l${LIB}")
	endforeach()
	CONFIGURE_FILE("libobs.pc.in" "libobs.pc" @ONLY)
	install(FILES "${CMAKE_CURRENT_BINARY_DIR}/libobs.pc" DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig")
endif()
```

**Comment by yurivict** [comment]
@Xaymar How to use it for ```obs-frontend-api```?

I tried ```find_package(obs-frontend-api/obs-frontend-api REQUIRED)``` and it failed:
```
  Could not find a package configuration file provided by
  "obs-frontend-api/obs-frontend-api" with any of the following names:

    obs-frontend-api/obs-frontend-apiConfig.cmake
    obs-frontend-api/obs-frontend-api-config.cmake
```

**Comment by Xaymar** [comment]
You use `find_package(obs-frontend-api REQUIRED)` or directly include it `include("${obsPath}/obs-frontend-api/obs-frontend-apiConfig.cmake")`. Take a look at how StreamFX does it: https://github.com/Xaymar/obs-StreamFX/blob/master/CMakeLists.txt#L349

**Comment by yurivict** [comment]
Currently ```${LIBOBS_LIBRARIES}``` substitutes libraries.

But ```lib/cmake/obs-frontend-api/obs-frontend-apiConfig.cmake``` still defines ```set(OBS_FRONTEND_API_LIBRARIES libobs)```.

Adding ```${OBS_FRONTEND_API_LIBRARIE}``` doesn't lead to finding this lib.

**Comment by Xaymar** [comment]
> Adding ${OBS_FRONTEND_API_LIBRARIE} doesn't lead to finding this lib.

You have a typo there.

**Comment by yurivict** [comment]
> You have a typo there.

It doesn't work without the typo too.

**Comment by Xaymar** [comment]
> It doesn't work without the typo too.

Ah I see what you mean now, I've fixed it. The .pc file should also now be installed properly, though I have no system on which I could actually test if it works. 

Currently the CMake config file also assumes that you already have a find_package(libobs), as I don't know how find_package(libobs) behaves inside of another find_package.

**Comment by Xaymar** [comment]
Closing this as #2635 was merged.

**Pull request closed without merging**
