### PR TITLE
UI: Add 4th aux audio input device

### PR DESCRIPTION
**Pull request by ePirat**
This PR adds another aux input device to the GUI.

### CODE REVIEW

**Comment by Heufneutje** [comment]
You may only want to change the en_US locale, as the other locale files will be overwritten by CrowdIn.

**Comment by ePirat** [comment]
Thanks for having a look at my PR.

> As @Heufneutje said above, please remove the changes to the locale files (other than en-US.ini). 

Done

**Comment by jp9000** [comment]
I'll allow it this time, but four is the max I will go for this.  I'm going to clean up the merge conflicts and then manually merge.  You'll see "close via [commit]".

**Comment by ePirat** [comment]
Thanks!

**Pull request closed without merging**
