### PR TITLE
UI: Reorganise control dock buttons

### PR DESCRIPTION
**Pull request by unknowndomain**
### Description
Removes the exit button per #2751 and also separates the studio and settings buttons from the output controls per feedback in #2751.

Screenshot 2020-04-24 at 23 20 49

### Motivation and Context
- The button is redundant because this is available through the file menu, title bar and system hotkeys.
- Users might accidentally click the exit button.
- The new layout separates the remaining functions as:
  1. Output controls
  2. Settings

### How Has This Been Tested?
Built and ran OBS on macOS Catalina.

### Types of changes
UI tweaks

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
While adding a small space between these buttons is probably not a bad idea, I don't like them being snapped to the top/bottom like that. It does not look good, IMO.

**Comment by unknowndomain** [comment]
@Fenrirthviti I can see where you are coming from, however realistically the default height of these docs and to be fair likely most people's experience of them is that it's quite short.

I feel like adding only a small gap will run the risk of looking centred for some reason, or perhaps being almost centred but not quite.

A horizontal rule could be used but I don't see that UI paradigm elsewhere in OBS's interface.

To be fair it looks better when you have the Exit button still...

Screenshot 2020-04-24 at 23 12 46

_Note: I was hovering the Exit button here by accident when I did the screenshot, it wouldn't be highlighted normally but I can't be bothered to recompile, I just had this screenshot laying about._

**Comment by dodgepong** [comment]
I think it looks fine snapped to the top/bottom, personally.

I do want to see what it looks like with Replay Buffer enabled, though.

**Comment by unknowndomain** [comment]
Helpfully, due to the way this appears to have been implemented it does the right thing.

Screenshot 2020-04-24 at 23 50 57

**Comment by Fenrirthviti** [comment]
I've had time to let this sit, and I think it's fine, no further complaints.

**Comment by PatTheMav** [comment]
I'm appreciate this - however by the same logic couldn't we also remove the "Settings" button, as settings are available from the menu-bar as well (and on macOS per the system-wide default shortcut `CMD+,`).

**Comment by Warchamp7** [comment]
I'm fine with this gap being added (I effectively tried to pull off the same effect on my Yami theme) but I think removing the Exit button is out of scope for this PR

**Comment by Warchamp7** [comment]
Closing this as it's on my review list and we have ongoing discussions right now to completely do away with the Controls dock and I don't think this is a necessary stepping stone towards that.

**Pull request closed without merging**
