### PR TITLE
rtmp-services: Add GamePlank

### PR DESCRIPTION
**Pull request by nocodedweb**
### Description

Added a new streaming service, GamePlank, to the RTMP services list.

### Motivation and Context

Just adding the new streaming service to the RTMP services list.

N/A

N/A

### How Has This Been Tested?

Reviewed, parsed JSON successfully in browser as well as jsonlint.com, and copied JSON files over to my OBS installation and successfully tested live stream.

Dell Inspiron laptop, Windows 11.

Reviewed, parsed JSON successfully in browser as well as jsonlint.com, and copied JSON files over to my OBS installation and successfully tested live stream.

### Types of changes

New feature (non-breaking change which adds functionality)
Added a new streaming service, GamePlank, to the RTMP services list.

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch. ("rtmp-services-gameplank" branch)
- [x] The code has been tested. (parsed JSON successfully in browser)
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Are you an official representative of GamePlank?

**Comment by nocodedweb** [comment]
Hello, yes I am.

**Comment by nocodedweb** [comment]
> Are you an official representative of GamePlank?

Hello.  Yes, I am.

**Comment by RytoEX** [comment]
Per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines#general-rules--requirements) under "General Rules & Requirements":
> 4. If your service is available to the public, some adoption should be visible to warrant the inclusion in OBS

Upon further review, this service appears to only have one user, which does not meet our criteria for inclusion.

**Comment by nocodedweb** [comment]
> Per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines#general-rules--requirements) under "General Rules & Requirements":
> 
> > 4. If your service is available to the public, some adoption should be visible to warrant the inclusion in OBS
> 
> Upon further review, this service appears to only have one user, which does not meet our criteria for inclusion.

How many users / how much engagement would you like to see before I resubmit this request again?

**Pull request closed without merging**
