### PR TITLE
UI: Add transition override to transitions dock

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This adds the per-scene transitions to the transitions dock, so that they are not just in the context menu.

Screenshot from 2023-05-28 01-37-10

### Motivation and Context
Better UI

### How Has This Been Tested?
Set per-scene transitions on different scenes.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Some comments from the UX discussion:

 - [ ] Rename the dock title to "Transitions"
 - [ ] Add a subtitle for the global transitions, named tentatively "Default transition"

@Warchamp7 requested being included here

**Comment by WizardCM** [comment]
My biggest UX concern here is that the Transitions dock is very much not tied to a scene in any visual way, so just having two dropdowns with a transition name is super confusing. I'm not even sure if renaming the section to something like "Transition Override for '<scene>'" would be enough.

Additionally, I thought that there was a hope to move the Studio Mode controls (the center area) to the Transitions dock? Or is the plan to put it in a separate dock named Quick Transitions and move the gear that contains a bunch of Studio Mode settings into the Settings window?

**Comment by Warchamp7** [comment]
> Additionally, I thought that there was a hope to move the Studio Mode controls (the center area) to the Transitions dock? Or is the plan to put it in a separate dock named Quick Transitions and move the gear that contains a bunch of Studio Mode settings into the Settings window?
>

I don't think I've ever taken any swings at the studio mode controls

> My biggest UX concern here is that the Transitions dock is very much not tied to a scene in any visual way, so just having two dropdowns with a transition name is super confusing. I'm not even sure if renaming the section to something like "Transition Override for ''" would be enough.
> 

That's the main purpose of adding an additional label for more context.

---

With the new extra controls added here, I'd like to avoid layout shifting by not having the Duration input field disappear for Cut/Stinger and instead be disabled with either no value listed, or 0ms / Automatic respectively

**Comment by cg2121** [comment]
Updates:
- Set the title of the transitions dock to "Transitions"

- Added "Default" label to global transition
- Added "Current Scene" label to transition override
- These are different than suggested because I feel like they are clearer to users what they are

- Disabled the transition duration, instead of hiding it, when transition is a cut
- Disabled the transition override duration when transition is a cut or none

Screenshot from 2023-01-24 05-49-57

**Comment by Warchamp7** [comment]
> * These are different than suggested because I feel like they are clearer to users what they are

Can we go with the originally proposed labels please

**Comment by cg2121** [comment]
Updated it to use the suggested text. My only concern now is that it makes the dock too big.

Screenshot from 2023-05-28 01-37-10

**Comment by cg2121** [comment]
Closing, as this makes the dock too big. Will reopen if a better UI for this can be made.

**Pull request closed without merging**
