### PR TITLE
UI: Ignore scroll on QComboBoxes and QSpinBoxes when not in focus

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

In OBS, dropdown lists as well as number input fields (SpinBoxes) have the behaviour that if the mouse is hovering over them, scrolling with the mouse wheel will change the current selection.

This PR removes that behaviour when the box isn't focused by using a custom subclass that was introduced for exactly that in #1811 - only that that PR changed it for just the source properties view and nothing else.
The new behaviour is what Fenrir requested in https://github.com/obsproject/obs-studio/discussions/4980#discussioncomment-966815 - it doesn't work when unfocused, clicking on it will enable hoverscroll as before.

This PR expands that to all instances of `QComboBox` and `QSpinBox` in OBS (except decklink-captions, where I couldn't get the header to point to the correct file, and when I did, the post-compilation dylib linker failed).

Third-party plugins are not affected. If we wanted to get a truly universal behaviour on this which includes those, I suspect patching QT would be the only option, which I honestly think is overkill, though should be possible - but it wouldn't apply to Linux, right?

Commits have been made separately for each area of OBS, so that in case it does break something in the future (which I don't expect), they could be reverted individually.

### Motivation and Context

This "hoverscroll" is unintuive and potentially dangerous behaviour. See discussion #4980

### How Has This Been Tested?

Compiled with CI and tested on Windows 11 and macOS 12
As expected, hoverscroll now only works when first clicking on the dropdown menu / spin box. (info for testers: Mac versions of OBS (and perhaps QT) didn't have hoverscroll over QComboBoxes in the first place, there only QSpinBoxes are affected.)

No testing on Linux.

### Types of changes

- Somewhere between `Bug Fix` and `Enhancement`, depends on the point of view

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
Actually, converting to draft - I noticed the same I wrote also applies to QSpinBoxes (and QScrollWheels), I'll add those as well

**Comment by gxalpha** [comment]
Added QSpinBoxes and one missing QSlider, tested under both macOS and Windows

**Review by Warchamp7 — APPROVED** [review]
Can't speak to the code implementation but from the UX side I approve this change

**Comment by WizardCM** [comment]
What should be our preference for this going forward - should this be applied to all QCombo/QSpin, or only ones that'd appear within scrollable containers to avoid accidental changes. I personally don't think this needs to be applied to all outright.

**Comment by gxalpha** [comment]
That is directed at @Warchamp7, right?
Also I’ll fix the conflicts merge commit when I’m home

**Comment by WizardCM** [comment]
More of a general question to frequent contributors. By always using the same custom widget, when a developer adds a new combo or spin box & uses existing code as reference, it'll be clear to them that they should use the custom one. At the same time, the custom widget isn't really _necessary_ everywhere, it's just good for consistency (and adds an extra consideration to PR review).

**Comment by WizardCM** [comment]
Heads up, there are merge conflicts.

**Comment by gxalpha** [comment]
Ok so, some time has passed since l made this PR, and circumstances have changed:

We now have an official Flatpak distribution, which means that we can have our own deps on all platforms - this makes me
want to reconsider the idea of patching QT instead. That way, contributors wouldn't need to use the custom classes,
which means that in any ui file change reviewers wouldn't always have to check for the use of those classes. This would
ensure consistency across OBS - all of it: A patched QT would mean that even plugins would automatically use them. If
plugin creators want to use them right now, afaik they need to copy the source files to their plugin, which just adds more
things in the project.

However, the reason I'm writing this here is that l'd like some initial opinions first before actually starting to work on it,
since it might be a somewhat bigger undertaking (not yet sure how big).

**Pull request closed without merging**
