### PR TITLE
UI: Add high frame rates (120, 144, 240) to general video properties

### PR DESCRIPTION
**Pull request by FBirth**
### Description
I added higher frame rates 120, 144 and 240 fps as defaults in the device properties for macOS. The higher framerates are only shown if the capture device supports them.

Device with max. 120 fps
grafik

Device with max. 240 fps
grafik

### Motivation and Context
Newer capture devices from Elgato and other support capturing at these high framerates.
Currently only standard frame rates up to 60 fps are shown plus the highest possible framerate reported by the devices.
If a device supports 240 fps 144 and 120 fps were not shown in the list.

### How Has This Been Tested?
I connected a UVC capture card capable of 240 fps. It showed all the standard frame rates plus 240 fps.
After my change also 120 and 144 fps were shown. I tested preview and capturing from the device at trhe high frame rates and found no issues.
macOS

### Types of changes
Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
We generally consider anything above 120 to be unsupported (on-your-own territory). I doubt this will get merged as-is.

**Comment by derrod** [comment]
Specifically for consoles you might want to add 119.88 (i.e. 59.94 * 2) as that's what they will be using rather than actual 120.

**Comment by FBirth** [comment]
> Specifically for consoles you might want to add 119.88 (i.e. 59.94 * 2) as that's what they will be using rather than actual 120.

@derrod, should I replace 120 with 119.88 or rather keep both?

**Review by derrod — APPROVED** [review]
Seems fine to me.

**Comment by gxalpha** [comment]
The two commits are doing the same, simply adding different values, correct? If so, could you squash them together?

**Pull request merged**
