### PR TITLE
Fix CMake Warning and tweak Linux install_headers

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Fix this warning:
```
CMake Warning (dev) at cmake/Modules/ObsHelpers.cmake:43 (install):
  Target obs-frontend-api has PUBLIC_HEADER files but no PUBLIC_HEADER
  DESTINATION.
Call Stack (most recent call first):
  cmake/Modules/ObsHelpers_Linux.cmake:10 (_setup_binary_target)
  UI/obs-frontend-api/CMakeLists.txt:39 (setup_binary_target)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

And add EXCLUDE_FROM_ALL to Linux install_headers, because even without it we still need to run `cmake --install . --component obs_libraries`

### Motivation and Context

Fix a warning, and tweak something.

### How Has This Been Tested?

Try to build a `-git` package (with my own PKGBUILD) which use `cmake --install . --component obs_libraries`, header are there.

And Cmake no longer throw the warning.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
What's the impact on Windows? Does it create stray header files in the runDir?

**Comment by RytoEX** [comment]
> What's the impact on Windows? Does it create stray header files in the runDir?

We might have to run it on CI to find out, as I think the issue was previously CI only.

**Comment by RytoEX** [comment]
> What's the impact on Windows? Does it create stray header files in the runDir?

No stray files from CI builds, at least.
image

**Review by RytoEX — APPROVED** [review]
Looks good to me. @PatTheMav ?

**Comment by PatTheMav** [comment]
I haven't tested the changes locally, but looks fine to me.

**Comment by PatTheMav** [comment]
> Hmm. I must have missed this when previously checking: image image
> 
> It seems that this creates an "include" directory inside the rundir per config. While harmless, this might need a follow-up.

That's what I expected and why I asked for review on Windows.. 😂

**Comment by RytoEX** [comment]
> > Hmm. I must have missed this when previously checking: image image
> > It seems that this creates an "include" directory inside the rundir per config. While harmless, this might need a follow-up.
> 
> That's what I expected and why I asked for review on Windows.. 😂

I might have just skimmed straight past the top-level rundir and gone to bin since that's what we had previously checked.

**Pull request merged**
