### PR TITLE
obs-filters: Add panic hotkeys to delay filters

### PR DESCRIPTION
**Pull request by Andersama**
Adds a panic hotkey to async and gpu delay filters.

### CODE REVIEW

**Comment by WizardCM** [comment]
For those who feel the description is insufficient, this feature is basically related to https://ideas.obsproject.com/ideas/33/add-a-shortcut-to-clear-the-buffer-before-it-leaves-obs-to-prevent-streaming-bad-things 

I do worry about UX and discoverability for this kind of feature, but have no idea what the best way to expose it would be.

**Comment by notr1ch** [comment]
The GPU delay filter is meant for minor sync adjustments, it's not really suitable for a dump buffer. It buffers raw video data, so if someone uses a capture card this new default of 20 seconds requires over 4 GB of VRAM and would likely cause major issues for users with lower end GPUs.

I think the correct place to implement this would be the delay buffer, where already encoded video packets can be dumped instead.

**Comment by Andersama** [comment]
@notr1ch the video frames are stored locally on the cpu, but you're right, it's quite hefty in terms of memory consumption. As for the right place to implement this, I went w/ the already existing filters, although I would definitely consider the delay buffer as well.

**Comment by jp9000** [comment]
I do not think this is the best way to approach this problem right now.  I like the idea of having panic keys, but right now, there are issues with hotkeys on filters (see my comment on #1508 for more details).

I really do not want to do this right now.  This is a solvable problem, but I think the issues with hotkeys on filters needs to be taken care of before we start proposing hotkeys for filters.

Besides, I don't really want to modify the GPU/async delay filters to do this.  I think it might be more ideal as a separate filter or something.  But right now, let's put this aside for more important priorities.  Wait until after the clang-format processing before continuing any new proposals for this.

**Comment by akii0008** [comment]
Hi! Pardon the necro-bumping here, but it's been a few years. Is there any update on this PR? I'd love to see this feature in OBS

**Comment by dodgepong** [comment]
To show your support for this feature, vote for it on our ideas page: https://ideas.obsproject.com/posts/33/add-dump-button-functionality-to-obs

That said, this PR won't be re-opened. It would have to be implemented a different way.

**Pull request closed without merging**
