### PR TITLE
UI: Add Filter Presets

### PR DESCRIPTION
**Pull request by VodBox**
Right Click Menu
Button Menu + Dialog

### CODE REVIEW

**Comment by VodBox** [comment]
A problem with this commit as-is, is that I had to come up with icons myself, and it's hard to tell which should be load and which should be save.

Icons

Currently, the one on the left is load, and the one on the right is save.

**Comment by dodgepong** [comment]
Worth noting that the "OFP" files are just JSON files, sort of an arbitrary file designation to help distinguish them from other random JSON files that may be on a user's system.

**Comment by DDRBoxman** [comment]
Would it make sense to move load / save over to the properties panel section?

I think that might help with the context of the icons.

**Comment by VodBox** [comment]
Closing this because I'm not happy with the way I implemented this, and I would need to rewrite it. I may write an RFC on how best to handle presets for individual filter, and how to handle things for multiple filters.

**Pull request closed without merging**
