### PR TITLE
rtmp-services: Add Mixcloud

### PR DESCRIPTION
**Pull request by WizardCM**
### Description
A music-focused streaming service https://www.mixcloud.com/

### Motivation and Context
Their official stream setup guide suggests connecting via "Custom". https://help.mixcloud.com/hc/en-us/articles/360013022760

### How Has This Been Tested?

Verified the streaming URL matches the official Help page

### Types of changes

* New service

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
Are we certain that this list of servers is comprehensive? What if they have recommended settings? I'm not sure we should be adding services like this on their behalf.

**Comment by Fenrirthviti** [comment]
We should not be adding services to the lists ourselves. If Mixcloud wishes to be listed, they are welcome to open a PR.

As a note because we had discussed this, but it isn't logged anywhere public, one of the biggest issues with service the way they are currently handled is that we don't have any good way of validating that service PR additions or updates are from the actual service itself. This is a perfect example of that lacking control.

**Comment by matclayton** [comment]
Hey,

Mixcloud co-founder here, we’d love to be listed, and will pull together a PR. We want to add a few custom params, to help reduce some of our server load, which is why we haven’t done this yet.

I’ve got a patch locally, but the server didn’t appear when I compiled OBS, an correct in thinking these are pulled in remotely? Is there any documentation we’re missing on this?

Mat

**Comment by Fenrirthviti** [comment]
Correct, there is an update check that pulls in the services.json file from our servers. You can disable this update check in a local build, but I admit I don't recall exactly how to do that.  Service PRs when they are merged (assuming it is just services.json being updated and not a full integration) do not need a full release to be populated to OBS.

**Comment by WizardCM** [comment]
@matclayton You can disable the cmake flag `CHECK_FOR_SERVICE_UPDATES` (set it to false) in your local build, which should stop our system overriding your local changes.

**Comment by matclayton** [comment]
New PR: https://github.com/obsproject/obs-studio/pull/3022 Whats the best way to proceed with this? 

I didn't manage to get the CHECK_FOR_SEVIVE_UPDATES flag working, any advice on how to check this?

**Pull request closed without merging**
