### PR TITLE
UI: Fix problem with Yes/No message box buttons not translated

### PR DESCRIPTION
**Pull request by shiina424**
### Description

Fixed Yes/No message box buttons not translated.

I refer to this commit.
https://github.com/obsproject/obs-studio/commit/522f5cdf3b733575c865ef43ad81f6f5fa5e92bc

If this is incorrect, we would appreciate it if you could correct it.

| English |  Japanese |
| ------------- | ------------- |
| Are you sure you want to reset the UI? | UIをリセットしてもよろしいですか？ |
| Resetting the UI will hide additional docks. You will need to unhide these docks from the Docks menu if you want them to be visible.<br><br>Are you sure you want to reset the UI? | UIをリセットすると追加のドックは非表示になります。表示したい場合ドックメニューからこれらのドックを表示する必要があります。<br><br>UIをリセットしてもよろしいですか？ |
| Yes | はい |
| No | いいえ |

Before
Before Yes No

After
After Yes No

### Motivation and Context

I want to display translations.

### How Has This Been Tested?

Tested on my fork's CI.
Use Windows 11 22H3

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — APPROVED** [review]
Looks fine at first glance. I believe there may be more QMessageBox's that we have to clean up in the future but this by itself is okay I think.

**Review by RytoEX — APPROVED** [review]
This seems fine.

**Review by RytoEX — CHANGES_REQUESTED** [review]
On second glance at the commit message, please be sure to use a present tense verb, as our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/fd65a1404c228340ed53bbb4137db5180a1e8a6e/CONTRIBUTING.rst#commit-guidelines) mention.

**Review by RytoEX — APPROVED** [review]
Seems fine.

**Pull request merged**
