### PR TITLE
blacklist change

### PR DESCRIPTION
**Pull request by kolya25**
### Description

My graphics card is NVIDIA GT 740M has nvenc and i want to use it.
[proof](https://github.com/obsproject/obs-studio/issues/2234)

### Motivation and Context

i want to build a project using github action because i have difficulties with the build documentation on lunux

### Types of changes

changed the blacklist of graphic cards in ffmpeg

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
As explained in the previous posts, we are not interested in removing these GPUs from the blacklist, as they are not only very old, but unsupported by NVIDIA. You are welcome to remove/modify the list in your own local builds if this support is necessary.

**Comment by kolya25** [comment]
> As explained in the previous posts, we are not interested in removing these GPUs from the blacklist, as they are not only very old, but unsupported by NVIDIA. You are welcome to remove/modify the list in your own local builds if this support is necessary.

I know I just want results github action

**Comment by kolya25** [comment]
so I can’t get the result of the github action as suggested in the comment? https://github.com/obsproject/obs-studio/issues/2234#issuecomment-827599962
@Fenrirthviti

**Comment by Penwy** [comment]
You can get it by running it on your own repo, you don't need to create a pull request on the obsproject repo for that.

**Comment by kolya25** [comment]
> You can get it by running it on your own repo, you don't need to create a pull request on the obsproject repo for that.

Thanks for the advice, I didn't know about this. I'll try to set this up in my own project. Sorry for this confusion.

**Pull request closed without merging**
