### PR TITLE
win-capture: Destroy duplicator when interface is invalid

### PR DESCRIPTION
**Pull request by Bl00drav3n**
### Description

In situations where a mode change, or switching DWM on and off occurs,
the duplication interface becomes invalid, and a new interface must be
created.

### Motivation and Context

Up until now, OBS always tried to reuse a previously created interface, even though it became invalid. This caused the display capture to fail until you restart the app.

### How Has This Been Tested?

Tested on Windows 10 with recent .zip dependency package, Intel i7-7700K, NVIDIA GTX 970, 16GiB RAM. I tested my change on the "The Surge 2", which uses a Vulkan renderer, so can't be captured by OBS gamecapture as of now. Display capture works with this change, with the restriction that when you tab out, it takes OBS a few seconds to reacquire the interface, as the code is waiting for the reset-threshold to be met.

### Types of changes

Bug fix

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jpark37** [comment]
There's already a duplicator destroy in the false path immediately outside of the function. Is someone holding an extra ref?

**Comment by Bl00drav3n** [comment]
Yes you are right.. After further testing, the issue seems to arise when you have two different scenes that each have their own display source. Each scene increases the refcount by 1, but the destroy() only happens in the active scene, so the refcount will never reach 0 unless you switch through all scenes.

**Comment by RytoEX** [comment]
This should actually have a prefix of "libobs-d3d11" for the PR and commit since the file changed resides there rather than in the "win-capture" code.

**Comment by Bl00drav3n** [comment]
Oh I just noticed that, sorry! Should I keep this PR open? I don't see a quick solution for this problem.

**Comment by Fenrirthviti** [comment]
You can just force-push the changes. In the future, you should not use the master branch for PRs as it will make it easier to manage.

**Pull request closed without merging**
