### PR TITLE
cmake: Fix dylibbundler path for case-sensitive partition

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Fix a dylibbundler path issue with case-sensitive partition.

### Motivation and Context

I made a VM to test some changes on macOS with a case-sensitive partition and I found this issue.

### How Has This Been Tested?

With this fix it does use dylibbundler rather than skipping it because of not being inside a `macos` folder.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
I'd rather have the folder renamed to lowercase "macos" to make it single case only and avoid any complications.

**Comment by tytan652** [comment]
I did it this way because it's the only iteration of `bundle/macos`. The other way require to change more files.

**Comment by RytoEX** [comment]
Let's just merge this then to fix the breakage and make the other change afterward.

**Comment by PatTheMav** [comment]
Fine by me.

**Pull request merged**
