### PR TITLE
rtmp-services: Add DTube

### PR DESCRIPTION
**Pull request by gluneau**
Livestreaming now available on DTube

See announcement: https://steemit.com/dtube/@heimindanger/dtube-0-8-the-grand-upgrade-is-finally-here-dtv-dtalk-vip-system-etc

### CODE REVIEW

**Comment by gluneau** [comment]
@jp9000, is it good to go?

How do we get the `"common": true,` entry?  Any particular criteria measured?

Thanks.

**Comment by Chiitoo** [comment]
With regards to 'common', here are some thoughts on that (albeit from a while ago, I suspect not much, if anything, has changed): https://github.com/obsproject/obs-studio/pull/577#issuecomment-234386514

(If I'm mistaken, someone will hopefully chime in.  :])

**Comment by derrod** [comment]
Please check the [Contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidlines) and/or previous changes to rtmp-services and adjust your commit message accordingly.

As has already been mentioned the `common` tag is pretty arbitrary and large overhauls of the entire output configuration UI are planned for the major updates following version 22. Seeing as your site has exactly zero live streams and viewers right now it certainly does not need to be marked as "common".

**Comment by RytoEX** [comment]
@gluneau 
Hi!  You still need to update the commit subject line to comply with [this project's commit guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidelines).  Prefix the commit subject with the component being modified, use a properly capitalized present tense verb, and a short descriptive message (50 characters or less).  This would suffice:
```
rtmp-services: Add DTube
```

You can update the commit subject line by amending the commit locally and then doing a force push to overwrite the commit already present here.

**Pull request merged**
