### PR TITLE
Decklink: preview out support

### PR DESCRIPTION
**Pull request by DDRBoxman**
Putting this here for anyone who wants to play around with it. Once again probably another throw away UI PR.

### CODE REVIEW

**Comment by localteampartners** [comment]
When building I get this error:

[ 96%] Linking CXX shared module decklink-ouput-ui.so
Error copying directory from "/Users/****/documents/projects/obs/obs-studio/UI/frontend-plugins/decklink-output-ui/data" to "/Users/****/documents/projects/obs/obs-studio/build/rundir/RelWithDebInfo/data/obs-plugins/decklink-ouput-ui".
make[2]: *** [UI/frontend-plugins/decklink-output-ui/decklink-ouput-ui.so] Error 1
make[2]: *** Deleting file `UI/frontend-plugins/decklink-output-ui/decklink-ouput-ui.so'
make[2]: Target `UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-ouput-ui.dir/build' not remade because of errors.
make[1]: *** [UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-ouput-ui.dir/all] Error 2

**Comment by DDRBoxman** [comment]
@localteampartners try just sticking an empty text file in /Users//documents/projects/obs/obs-studio/UI/frontend-plugins/decklink-output-ui/data

**Comment by localteampartners** [comment]
@DDRBoxman That worked. Thanks!

**Comment by localteampartners** [comment]
@DDRBoxman  I was able to load obs and the UltraStudio Mini monitor was found. When I click on start output I get this error in the terminal: 

info: decklink: Starting output...
Could not obtain the IDeckLinkKeyer interface

If I click start output obs crashes

**Comment by DDRBoxman** [comment]
Make sure you don't have any of the keyer options enabled.

**Comment by DDRBoxman** [comment]
@localteampartners if the disable keyer stuff doesn't fix it let me know, there might be a bug with non keyer devices.

**Comment by localteampartners** [comment]
Keying is disabled. Never could get output. Will keep testing.

**Pull request merged**
