### PR TITLE
UI: Feature/multiview vu meter

### PR DESCRIPTION
**Pull request by mate1213**
### Description

Design on the multiview:
image
Settings:
image

### Motivation and Context

In multiview I want to see the audio output.
[FR](https://ideas.obsproject.com/posts/1349/vu-metter-on-multiview)

### How Has This Been Tested?

Manually.
Scenarios:
- Try out different resolutions, on different machines, with different preview size settings.
- Enable/Disable audiometer display while the multiview open.
- Change selected track while multiview open.
- If there are no audio playing, show the default scale with levels -Inf.
- If track has no data, fall back to stereo.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
Please fill out the PR template, explaining your changes and motivation. Make sure to include screenshots.

Additionally, please clean up the commit history by squashing commits together if you can (although that not as important *right now*, I recognize this is still marked as draft).

**Comment by mate1213** [comment]
Hi,
This meant to be a draft only :D Yes I will fill everything out. Thanks to noticed.
It's just to see what do I have to change :D
Do I have to ping you, when it's done?
Br, Máté

**Comment by derrod** [comment]
Some screenshots would be nice.

**Comment by mate1213** [comment]
> Some screenshots would be nice.

I've put some in the description, as requested.

**Comment by mate1213** [comment]
> Please fill out the PR template, explaining your changes and motivation. Make sure to include screenshots.
> 
> Additionally, please clean up the commit history by squashing commits together if you can (although that not as important _right now_, I recognize this is still marked as draft).

Except the squash commits, I think filled out everything.
I still need to do some fine tuning. I needed to add new files, but I'm not sure what additional steps do I have to do to work correctly in the repo. (Regarding the .sln generation, and CMAKE files)

**Comment by Warchamp7** [comment]
There is currently [an open RFC](https://github.com/obsproject/rfcs/pull/59) for making more significant changes to the OBS multiview. I consider this feature a significant enough of an addition to be part of that process.

As such I am going to close this PR for now, but please feel to add your voice and any other feedback to the RFC discussion in the meantime.

**Comment by mate1213** [comment]
@Warchamp7  Okay, I've already mentioned this there. And made these changes in mind that could be easily port into that. :D
Can I mention this PR there, like a possible implementation?

**Pull request closed without merging**
