### PR TITLE
cmake: Remove WITH_MESSAGE from obs-qsv11

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Removes the `WITH_MESSAGE` parameter from `add_obs_plugin(obs-qsv11)`.

### Motivation and Context

https://github.com/obsproject/obs-studio/commit/7d578c5cfb334d41aaa81cd00c1f1df5fbe8688e added `WITH_MESSAGE`.
This annoyed me because on macOS the module is obviously unavailable whatever you do, and the `add_custom_target` call leaves this confusing empty top-level target in the generated project:

Bildschirmfoto 2024-08-17 um 20 03 02

I don't see any value in `WITH_MESSAGE` here.

### How Has This Been Tested?

Reran cmake, target gone.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
@gxalpha `WITH_MESSAGE` is needed to list the plugin as disabled in the CMake logged summary which is the value.

Removing it is not the right fix.

**Comment by gxalpha** [comment]
Imo "needed" is a bit of a stretch, seeing that all other modules that are exclusive to other operating systems are just fine without it.

**Comment by tytan652** [comment]
"needed" is not a stretch when you want to provide a visual feedback that the module is not enabled.

I did not say that showing up on macOS is good, but I think the feedback on the correct platform because of architecture mismatch is needed.

**Comment by gxalpha** [comment]
> "needed" is not a stretch when you want to provide a visual feedback that the module available on the platform is not enabled. [...] I think the feedback on the correct platform because of architecture mismatch is needed.

RIght, and I disagree. I think it should be fairly obvious that if you're compiling on ARM or similar the QSV module can't be built.

**Comment by tytan652** [comment]
It is not obvious, libvpl is (or became) buildable on ARM64, it's the driver part (e.g. vpl-gpu-rt) that have issues to build…

QSV being architecture-bound is not obvious.

**Comment by PatTheMav** [comment]
I agree that no status should be printed as it's expected that a given module is not available for any platform not explicitly listed.

I don't fully remember what my intent behind `WITH_MESSAGE` was (could be that it was a bone thrown at FreeBSD) but my current thinking would be to limit it to the case of a platform match with an architecture mismatch (e.g. a Windows-only module that is also x64 only).

One could also argue that the "disabled modules" list should only print the names of modules _explicitly_ disabled by the user and not just modules that are automatically/implicitly not available (e.g. specifically `obs-qsv11` on macOS).

**Review by RytoEX — APPROVED** [review]
The obs-qsv11 plugin is not ever expected to be available on macOS. Not showing a message for it is fine.

**Pull request merged**
