### PR TITLE
Improve locales

### PR DESCRIPTION
**Pull request by Vainock**
Changed "CrowdIn" to "Crowdin". "CrowdIn" is wrong.

Removed the 2 spaces because, because I have not really an idea why there are written there. It looks pretty bad.

FilenameFormatting.TT:
- Removed "\n	name or abbreviation" because there is no variable given, also I haven't found this description in the list http://www.cplusplus.com/reference/ctime/strftime/.
- "ISO 8601 offset from UTC or timezone" -> "ISO 8601 offset from UTC in timezone"

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
Little oops there.
I'm in contact with the PR author so this is nothing to worry about too much thankfully (otherwise I wouldn't have tried to do this on his branch).

**Comment by DDRBoxman** [comment]
Can you revert the filename formatting changes and update the commit message to match the guidelines https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidelines

**Comment by Gol-D-Ace** [comment]
This is how the original looks like in OBS.


And here with your change.

%z should be worded like in your example to ISO 8601 offset from UTC **in** timezone


For your other changes...

Decimal refers to the decimal number system. This means **decimal digits**, decimal mark and for negative numbers a minus sign.

This isn't referring to the number being a whole/integer.

Other number systems would be for example Binary or Roman.

**Comment by Gol-D-Ace** [comment]
@DDRBoxman 
This is how it looks now:



If I remember correctly, this doesn't need to be prefixed, because it's just touching locales. 
@jp9000 might correct me on this though.

**Pull request merged**
