### PR TITLE
CI: Fix flatpak-builder-lint action

### PR DESCRIPTION
**Pull request by tytan652**
### Description

`jq` does not return zero if the array does not exist but an empty output

### Motivation and Context

Stop the action tab becoming more red

### How Has This Been Tested?

Here (I will temporarily push a commit to trigger errors/warnings )

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Flatpak CI still fails because of a likely upstream issue…

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by PatTheMav** [comment]
This PR doesn't make sense to me - if you pass an empty string to `jq` it will also return just nothing with a `0` return code.

`echo $test | jq -r '.some | length'` with `test` being an empty string yields return code `0`, the same happens if `test` is not even defined. Does this require a particular version of `jq`? 

Also if the field is truly optional, then we should use `jq`'s optional syntax:

`jq -r ' .someOptionalArray // ["default", "values"] | length'` though even with a non-existing key `jq` will usually return just the actual value `0` then.

**Comment by PatTheMav** [comment]
Also a lot of the shell script code can be simplified by using `jq`'s built-in functionality:

`echo "<JSON_STRING"> | jq -r '(.warnings // [] | try map("::warning:: " + . + " found in the Flatpak ARTIFACT")) + (.errors // [] | try map("::error:: " + . + " found in the Flatpak ARTIFACT "))' | jq -r '.[]'` will print any warning or error found already pre-composed as a GitHub actions output.

You can pipe this output to `while read -r log_line; do echo "${log_line}"; done <<< "$(<THE JQ CALL)"` to have it automatically printed then.

**Comment by tytan652** [comment]
*Ignores the two previous message as the actual is minimal*

**Comment by tytan652** [comment]
@PatTheMav, this PR is a fix not a re-write. It is out of question that it becomes one.

Also your proposition add complexity, and this is wrong for maintainability.
This action is a simplish bash script, not a `jq` one.

**Review by RytoEX — APPROVED** [review]
Seems fine to fix the immediate issue. We'll consider further adjustments in the future as needed.

**Pull request merged**
