### PR TITLE
image-source: change color source default color to d1d1d1

### PR DESCRIPTION
**Pull request by matoi974**
### Description

Changes the default color for color source to #d1d1d1.

### Motivation and Context

The default color can trigger photosensitivity in users suffering from it; the new color should reduce or avoid the trigger.

### How Has This Been Tested?

Flashed the new color in my own face, it not nearly as painful as flashing a full #ffffff white without precautions. I haven't actually compiled obs-studio with this change.

### Types of changes

 - Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Note: The reason there's a "v2" of this source, is that any user who has an existing Color Source and they didn't change the colour from white, your change will change their colour source the next time they load. You will need to write a v3 in the code, same way v2 was done.

**Comment by togetherbeer** [comment]
if this is desired, i can volunteer / test a patch that adds v3 leaving existing sources alone.

**Comment by togetherbeer** [comment]
when the OS has dark mode activated, maybe we should consider something darker, like #222222 as the default color?

**Comment by matoi974** [comment]
For some reason I wasn't receiving notifications for this.

> if this is desired, i can volunteer / test a patch that adds v3 leaving existing sources alone.

@togetherbeer Yes please!

> 
> 
> when the OS has dark mode activated, maybe we should consider something darker, like #222222 as the default color:
> 
I'm fine with anything that isn't a photosensitivity trigger. I'll close this if I see a PR to fix this issue with image source.

**Pull request merged**
