### PR TITLE
enc-amf: Update to latest

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Pull in latest AMF plugin changes.

Starting in draft status because I don't know what the process is for bumping up this plugin.

### Motivation and Context
Want the sYCC changes, so it will be ready to go when OBS rounds out support. Also want the warning fixes I made a while back.

### How Has This Been Tested?
Recorded 601 and 709 videos, and they played back fine.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Xaymar** [comment]
> Starting in draft status because I don't know what the process is for bumping up this plugin.

Usually publish a version on the obs-amd-encoder repository, then pull in that version tag. Also make sure to have the latest translation files from Crowdin (@Gol-D-Ace used to PR those IIRC).

**Comment by Xaymar** [comment]
See 2.7.0 tag

Note: Upstream build failure is due to there being no stable tagged obs-studio version to link against and CI relying on prebuilt libobs packages to build. The plugin should work fine when included in master obs-studio.

**Comment by jpark37** [comment]
i'm not a fan of the clang-format changes. i had Chromium depot_tools in my PATH because of their Windows build instructions, and their version of clang-format causes the OBS build to fail. had to revert my PATH and blow away my build folder to get things working again, and i probably can't build Chromium in this state.

**Comment by jp9000** [comment]
I am probably not going to merge this until the google depot tools issue is resolved.  We need to be able to google depot tools in conjunction to building OBS.

**Comment by Xaymar** [comment]
Using outdated tools for the sake of building something else which has no need for a globally modified path isn't exactly the goal. I'll add a version check though, so in the case the chromium doesn't straight up say it has a newer version everything should still work.

**Comment by Xaymar** [comment]
See current master commit.

**Comment by jpark37** [comment]
Still fails with C:\src\depot_tools in PATH.

```
1>------ Build started: Project: enc-amf-test_CLANG-FORMAT, Configuration: Debug x64 ------
1>clang-format: Formatting enc-amf-test...
1>Problem while looking for clang-format in Chromium source tree:
1>Could not find checkout in any parent of the current path.
1>Set CHROMIUM_BUILDTOOLS_PATH to use outside of a chromium checkout.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1.
```

**Comment by Xaymar** [comment]
Those are not errors from clang-format or the file itself, those look like chromium is shipping a proprietary wrapper around clang-format. Unfortunately I can't support that as it is impossible to detect.

**Comment by mufunyo** [comment]
> Those are not errors from clang-format or the file itself, those look like chromium is shipping a proprietary wrapper around clang-format. Unfortunately I can't support that as it is impossible to detect.

So the obvious solution is to get rid of the automatic clang-format during the build process.

**Comment by jp9000** [comment]
I realize that this is technically not your fault, but do you think you could give up on the automatic formatting part of the process?  Or at least make it only perform it when being built independently rather than as a part of OBS?

**Comment by jp9000** [comment]
Another sensible approach to solving this problem is to make this functionality a cmake variable that's off by default.

**Comment by Xaymar** [comment]
I've made it optional, which defaults to on in a non-native build and off in a native build. While I don't agree with the reasoning at all (by modifying PATH you should know what the fuck you're doing), I feel like I'm talking against a wall and that wall will not budge no matter what I say.

**Comment by jpark37** [comment]
It looks like the clang changes are gone? I think this should be okay to merge.

**Comment by Xaymar** [comment]
I've force removed them as I no longer maintain the plugin and there was no need to add extra workload to the new maintainers.

**Pull request merged**
