### PR TITLE
UI: Add status icons for recording and streaming

### PR DESCRIPTION
**Pull request by Bennik2000**
### Description
Add status icons for recording and streaming in the statusbar at the bottom of the window.

This is how the status bar looks like now:

Screenshot_5

#### Default dark theme
Dark_inactive

Dark_active

Dark_paused

#### Rachni theme
Rachni_inactive

Rachni_active

Rachni_paused

#### Acri theme
Acri_inactive

Acri_active

Acri_paused

### Motivation and Context
This PR implements [this](https://ideas.obsproject.com/posts/131/status-icons-for-recording-and-streaming) idea from the ideas page.

It makes the current recording/streaming status more visible.

### How Has This Been Tested?
This has been tested on Windows 10 with the available themes (Dark, Rachni, and Acri).

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
How does this look when recording is paused? My instinct would be to change the circle to a pause icon, and flash it.

**Comment by Bennik2000** [comment]
I was not aware that the recording can be paused but I will loook further into this and add a pause symbol.

**Comment by Bennik2000** [comment]
This is how it would look like: 
Screenshot_8


What do you mean with "flashing it"? Like how would you imagine the flashing animation?

**Comment by dodgepong** [comment]
Like, a blinking pause light, toggling on and off every second or so, between green and gray.

**Comment by Bennik2000** [comment]
Now the pause icon is flashing between green and yellow (I chose yellow because the tray icon is also colored yellow).

**Comment by WizardCM** [comment]
Minor request outside of implementation: could you minify/strip the SVGs? They look to contain Inkscape attributes and other unnecessary tags.

**Comment by Bennik2000** [comment]
Thats right Inkscape adds a few extra tags. I exported it without these tags and now the files are a bit smaller

**Comment by paddymazz** [comment]
Great work @Bennik2000 👍 Thank you for taking on board the suggestion and getting this implemented!

**Comment by chrisspiegl** [comment]
Congrats @Bennik2000 for getting this merged this quickly. What a lovely improvement ❤.

**Pull request merged**
