### PR TITLE
UI: Remove lock & vis checkbox classes

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This removes the lock & visibility checkbox classes in favor of using dynamic properties.

### Motivation and Context
Less files to worry about.

### How Has This Been Tested?
Went through every theme and made sure everything looked correct.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by cg2121** [comment]
Turns out we still need the mute checkbox, as it is tristate and uses custom code. Updated this PR to just remove the visibility and lock checkboxes.

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by Warchamp7** [comment]
I'd like to follow more in line with the phrasing used for styling widgets like QToolButtons, which is `toolButton`. As such I suggest the following for the property names:

- `visibilityCheckbox`
- `lockCheckbox`

**Comment by cg2121** [comment]
Updated PR based on suggestions by @Warchamp7

**Review by Warchamp7 — APPROVED** [review]
Approved from my side at least. Will need to ensure no other unforeseen side effects.

Is it possible for plugins to have been using the custom widgets for example?

**Comment by Lain-B** [comment]
I don't think plugins have been using those particular custom widgets. I hope.

**Comment by Lain-B** [comment]
Actually even if they were, they'd probably have to duplicate the files or something anyway. So I'll just merge it.

**Comment by exeldro** [comment]
Plugins have been using copies of those widgets, those will lose the icons they get from the theme, but I can do a small change in my plugins to fix that and support this change.
Custom themes will also need an update to support this change.

**Pull request merged**
