### PR TITLE
UI: Add "H.264" to simple hardware encoders

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Hopefully stops people from assuming other video compression standards
are usable from these settings.

### Motivation and Context
People were assuming NVENC setting could be used for HEVC.

### How Has This Been Tested?
- [x] Verified all GUI string locations.
- [x] All diffs have been breakpoint debugger inspected to behave as expected.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jp9000** [comment]
The recording part is fine, but for streaming we may have to check to see what services support it and remove it from the streaming encoder list if they don't support HEVC.

We could merge this as-is while HEVC is disabled by default, although having a supported codec list for each service will probably be important when they support AV1 too.

**Comment by Gol-D-Ace** [comment]
Is this respecting that for example Pascal (10xx) cards do not support bframes?

I noticed that while trying advanced output mode that bframes are enabled by default which will result in an error message.

**Comment by jpark37** [comment]
I'm starting to think that adding HEVC to simple mode is anything but.

What if I just update the GUI strings for the existing hardware encoders in the list to point out that they are H.264? I'm just trying to resolve the confusion that a hardware encoder might implicitly choose a codec when it doesn't, which multiple early testers of HDR have incorrectly assumed.

**Comment by jpark37** [comment]
This change just modifies the strings a little.

**Comment by Fenrirthviti** [comment]
Just to throw in my opinion, I think keeping HEVC in the advanced section is going to be fine. I would prefer we didn't expose it to regular users, both from a support standpoint, and a personal standpoint of not wanting to push a morally-bankrupt licensed encoder.

Users who are looking for the option and know what HEVC is are typically going to have a better understanding on what it is and how to use it in the first place. Simple mode users just want to stream, and don't care about the technical minutiae of encoder choice past "works" and "doesn't work"

**Comment by jpark37** [comment]
We may not want users to venture into advanced settings to use HDR, but I think we're looking at a more extensive reshuffling of settings if that's a goal.

**Pull request merged**
