### PR TITLE
Remove slideshow limitations

### PR DESCRIPTION
**Pull request by DarkDust**
### Description

This pull request improves the existing slideshow implementation to get rid of the current limitation in the number of images it can play back. As a side-effect, the memory consumption has been reduced.

Additionally, the way randomization is done has been changed and thread-safety is improved.

### Motivation and Context

Currently, the image slideshow has limitations on how many images it can actually show. This depends on the size of the _decompressed_ images in memory and typically only supports a few dozen images. I wanted to have a slideshow with several hundred images.

My current implementation already includes improvements due to feedback via [Mantis ticket 1621](https://obsproject.com/mantis/view.php?id=1621). It is now now in a state that is ready to use and needs final feedback on what needs to be further improved in order to be merged into the project.

### How Has This Been Tested?

I did a 3h long stream last week (slideshow for a DJ set). No memory leaks, no crashes.

Testing was done on a MacBook Pro (Retina, Mid 2012), 2.7 GHz Intel Core i7, macOS 10.14.6.

#### User-visible changes

* The image slideshow can now play an arbitrary number of images.
* Memory usage is reduced to the amount needed for a few of the images in the list (preloading, caching).
* The way random image playback works has changed.
    * Before: the next image was just randomly picked from the file list. There was modulo bias and since the next image was picked at random, it was possible for some images to show up multiple times and some not at all in a certain amount of time.
    * Now: the images are placed in a queue which is shuffled. Once the end of the queue is reached, it's shuffled again. This ensures that each image is played once per loop. I think this is more what people expect with random playback (play the list in a random order).

#### Additional changes

* Thread-safety is improved.
    * Several functions have been augmented with assertions to check whether the lock is held or not. This is done both to ensure that the code is not accidentally called in an unintended way but also as a hint for future developers.
* A preloading and caching thread has been introduced.
    * Images are loaded on this thread on-demand and in advance. Images that are no longer needed to be in the cache are evicted here.
    * Other threads signal the need to re-manage the cache content via an event.
* There is now the list of files to show as configured by the user (`file_paths`) and a playback list (`file_queue`) which may be shuffled if random playback is requested.
* `cur_item` now references the position in `file_queue`.

#### Known issues

* Making changes to the slideshow settings with several hundred images may stall OBS for some time.
    * This issue already existed in the previous implementation but probably wasn't that visible due to the stop after the memory limit was reached.
    * All images are loaded once to determine `cx` and `cy`. I don't know whether we could offload this to another thread and then tell OBS about the changed width/height once the process is done.
* The code does not yet cope well with images that were deleted from disk after they were added to the slideshow.
    * It should recover after the tick has moved to the next image index that can load its image.
    * A better solution is probably to remove the image from the queue (but not from the file list).
* When the tick occurs and the image has not yet been loaded, the transition is deferred.
    * This is a design limitation/feature. I'm not happy with the way it's done (`retry_transition`) but wasn't able to come up with a better way yet.
    * The absolute time when each transition is supposed to happen should not change due to this deferment.

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by mufunyo** [comment]
>   * Now: the images are placed in a queue which is shuffled. Once the end of the queue is reached, it's shuffled again. This ensures that each image is played once per loop. I think this is more what people expect with random playback (play the list in a random order).

This method of randomisation runs the risk of showing the same image twice at the seam of two queues (last image of the last queue, first image of the new queue). If you instead implement a rolling history of images already shown, you can still satisfy your first requirement (play each image at least once) while also preventing showing duplicates. This will mostly be noticeable with smaller lists of let's say up to 14 images or so.

**Comment by DarkDust** [comment]
> This method of randomisation runs the risk of showing the same image twice at the seam of two queues (last image of the old queue, first image of the new queue). If you instead implement a rolling history of images already shown, you can still satisfy your first requirement (play each image at least once) while also preventing showing duplicates. This will mostly be noticeable with smaller lists of let's say up to 14 images or so.

Thank you for the feedback, I understand the problem you're referring to. However, I don't yet understand your proposed solution, can you elaborate?

**Comment by mufunyo** [comment]
Sorry, I wrote "instead", but later realised that for the slideshow to stay random, you do still want to keep a bag (queue) to select images from, so the history augments the system you already wrote.

Basically, you keep a rolling history of the last _n_ images shown (where _n_ mostly depends on preference and how many images are in the slideshow - the larger your history, the less random your selection becomes, but if _n_ is too small, you still get repeats), and if the randomly chosen image from the bag exists in the history, you re-roll the RNG to select a different image from the bag, and if necessary repeat until you find one that was not in the history, show the image in the slideshow, and add it to the history.

**Comment by jp9000** [comment]
This should have been an RFC first.  I haven't looked at it yet, but just a forewarning, because so many have tried to modify this file and have done a poor job at it because they try to "fix" the slideshow improperly, do not be surprised if I decline.  I am going to be extremely picky about how this is done.  This is the single source in the entire program that makes me upset.  Everyone wants something out of it so badly, it's like it's their mission in life to have a billion images on the slideshow at once.

**Comment by dodgepong** [comment]
I'll take the blame for this being a PR instead of an RFC. OP had already done the work on it, and then asked me how he should submit it to get it considered for inclusion, and I said either PR or RFC. I wouldn't have suggested a PR if the work hadn't already been done, but given the sordid history of this source, an RFC probably would have been better to begin with.

**Comment by kkartaltepe** [comment]
Somewhat of a drive-by, but does not solve the idiots adding 1-billion files to slow drives (didnt trace but appears to still decode all files added, required 1GB of VRAM for me compared to steady state when rendering of about 400MB) making obs take days to start up or add a directory/Image stalling rendering.

**Comment by DarkDust** [comment]
Sorry for not understanding proper protocol yet, I had the feeling an RFC would be more about core features while this is "just" doing modifications to a plugin. I have no problem with you guys being picky and telling me what/how to improve. My main goal is simply to have a slideshow that can show a few hundred images. While I already have that, works for me, I would also like to have others benefit from it as well.

Should I open an RFC to discuss the design?

**Comment by dodgepong** [comment]
I think yes, go ahead and do that, and close this PR. Then when the RFC is accepted, you can create a new PR, referencing the RFC, and including the changes.

**Comment by jp9000** [comment]
I apologize, I didn't want to make it seem like I was upset, I'm just frustrated because of the slideshow itself.  It's not anyone's fault, it's certainly not your fault, it's not like you could have known.  The slideshow just has a bad history.  The entire design of slideshow probably has to be changed so it doesn't use sources internally or something.  I'm not even sure.  Every single thing about the slideshow source makes me upset.

**Comment by DarkDust** [comment]
@jp9000 No harm done, it was clear to me you're frustrated about the code.

I'm willing to invest time to deliver a good solution. Will write a detailed RFC today or tomorrow.

**Comment by DarkDust** [comment]
[RFC #17](https://github.com/obsproject/rfcs/pull/17)

**Pull request closed without merging**
