### PR TITLE
UI: Rename Default theme to System

### PR DESCRIPTION
**Pull request by cg2121**
The system theme was named Default even though the default theme is Dark.
This addresses that by renaming Default.qss to System.qss. I've made it
backwards compatible so users already using this theme are not affected.

The theme list now shows up as:
-System
-Dark (Default)
-Acri
-Rachni

I have also made it so that you can specify the default theme in the
UI config file.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
Note that the light theme is more using the base OS styling and isn't a proper light theme. For example if compiled with the 10.14 sdk with newer QT on osx it will be dark (and styled poorly) if the OS is in dark mode.

Not sure if the solution is to name it something like "OS style" or to actually build a proper light theme

**Comment by dodgepong** [comment]
I do think we need a proper Light theme in addition to the "OS Style" theme.

**Comment by SuslikV** [comment]
Not required. Say, that you wanna see here "By manufacturer..."
The current wording is OK. It is just short from Default Style. That's all.

**Comment by WizardCM** [comment]
I'd personally name it "System" rather than "Light".

**Comment by cg2121** [comment]
I have now renamed it from Light to System.

**Comment by jp9000** [comment]
I notice you've renamed the qss file.  This will result in cases where System.qss exists alongside an old Default.qss file.  Have you tested to see what happens in that case?

**Comment by cg2121** [comment]
I have now changed it to if Default.qss is found, it will be ignored.

**Pull request merged**
