### PR TITLE
Explicitly close RTMP socket on send error

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Explicitly closes the RTMP socket if `send()` returns an error.

### Motivation and Context
Some `send()` errors such as a timeout with no data sent are not fatal, but librtmp will still shut down the connection on an error. During shutdown, librtmp attempts to send an `FCunpublish` message which would usually not make it to the service since the socket has been torn down due to the error. But depending on the type of `send()` error, the `FCunpublish` message could actually make it through to the remote side and cause it to think a clean shutdown occurred, disabling features like "disconnect protection".

### How Has This Been Tested?
Not tested but Seems Good™

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jdeng89** [comment]
Did some initial testing with the same process used to initially repro this bug and no longer seem to be able to repro. Will do a rebuild with both this and the extended logging to confirm later this week and will attach afterwards

**Comment by jdeng89** [comment]
I re-tested this again with additional RTMP logging and could not re-produce the issue. Below is the OBS log.

https://obsproject.com/logs/fAeHv2aFZ6IUE041

**Comment by RytoEX** [comment]
That sounds like as much confirmation as we're likely to get. I don't know how else we might test this.

**Comment by tt2468** [comment]
The underlying bug is timing-based and also depends on the network conditions that caused the send error, so reproduction of the bug is not expected to be reliable.

**Comment by notr1ch** [comment]
To clarify on the "not tested" part, I can't trigger the error condition but I believe this code to be the proper solution to the problem. This shouldn't be able to make the problem any worse than it already is - the socket is being closed regardless during shutdown after the error, this just makes it more explicit and earlier. I'm confident that merging this will be fine.

**Pull request merged**
