### PR TITLE
UI + libobs: Fix Various Accessibility Feedback Issues

### PR DESCRIPTION
**Pull request by VodBox**
### Description

This PR makes the following changes:
- Adds an accessibility menu to Settings which contains:
  - Options to override mixer and preview border colors with a preset or with your own custom colors
  - An option to have audio notifications for successfully ran hotkeys
- Changes the line style on the cropped selection border to a dashed line.
- Changes the recording and streaming inactive status bar icons to have a slash to indicate inactivity.

obs64_2021-07-05_15-52-38
obs64_2021-07-05_15-53-25

Note that these changes will not correctly build on CI until the Qt deps we use are updated to include Qt5Multimedia.

### Motivation and Context

These changes help users who are color-blind, are blind or have low vision, to be able to have alternative feedback options for states or actions in the program. There are still more places in the program that lack adequate feedback for one or more disabilities, but this is just a start to fixing some of those issues.

### How Has This Been Tested?

This has been tested on Windows 10 x64 by cropping various scene items, by confirming that the options in the accessibility menu each reflect a change in colors in the program, and that verifying that an appropriate sound is played when a hotkey performs an action successfully.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Good news: https://github.com/obsproject/obs-deps/pull/60 already includes QtMultimedia for macOS.

Bad news: Audio cue playback is buggy on macOS, with interruptions on UI state changes (easily reproducible by triggering recording via hotkey), also some clipping that sound like playback buffer issues.

**Comment by jp9000** [comment]
Seems there are still some build issues. I think it mostly has to do with QtMultimedia.

**Comment by VodBox** [comment]
> Seems there are still some build issues. I think it mostly has to do with QtMultimedia.

Correct. At this stage, there needs to be updates to CI and to the deps used during CI to make this PR build without errors.

**Comment by SuslikV** [comment]
Why Qt and not the media source (and monitoring device) in each scene?

**Comment by WizardCM** [comment]
> Why Qt and not the media source (and monitoring device) in each scene?

Because this PR is a UI enhancement (the UI is powered by Qt). Sources & monitoring are designed for things that are part of the user-created scene, not for UI.

**Comment by VodBox** [comment]
Additionally, with media sources and monitoring there is added layers of abstraction towards outputting the audio, which can result in unpredictable and noticeable latency. The Qt functions also provide a convenient API to just provide the file and play it immediately in an event slot.

**Review by RytoEX — CHANGES_REQUESTED** [review]
One nit.

**Comment by VodBox** [comment]
Audio hotkey acknowledgement has been removed from this PR, as the other changes are good, but we will have to consider how to handle QtMultimedia with Qt 6 going forward before we get the feature in.

**Review by RytoEX — COMMENTED** [review]
I think the various "on_choose1_clicked" could have more descriptive names, but I won't block on that. Will add Seeking Testers and re-run CI.

**Review by RytoEX — APPROVED** [review]
Does what it says on the tin. The only issue I've observed is that if sometimes when I grab a source and drag it around the canvas quickly, the source rendering appears to tear a bit. I reproduced this with a color source, usually while shaking it rapidly left-to-right. It doesn't occur every time. However, I consider this to be a minor issue, and I would not block on this. It would be ideal if that could be resolved before merging though.

Should get @Warchamp7 's approval before merging.

**Comment by RytoEX** [comment]
@Warchamp7 approved off-thread. Merging.

**Comment by meiko0212** [comment]
I tried this feature in Nightly builds.
When I use "True Peak" for the "Peak Meter Type", the dB written in "Accessibility" does not match the dB written in "Audio Mixer".

Sample Peak / True Peak (maybe)
-60 to -20dB / -60 to -13dB
-20 to -9 dB / -13 to -2dB
-9 to 0dB / -2 to 0dB

image

**Comment by SuslikV** [comment]
In OBS itself these zones named _Nominal_, _Warning_ and _Error_ - that is not easy to translate.

In docs, the "true-peak" these levels according to ITU-R BS.1770, Annex 2 are known as:
Permitted Maximum Level (PML) = -1.0 dBFS, recommended -1 dB Full Scale (EBU R128)
Alignment Level (AL) = -18 dBFS, recommended 1:8 of max possible value (EBU 68-2000)

Because OBS doesn't follows the standards (in this part) it is better to switch to something simple and universal, easy to translate, for example - "lower zone", "middle zone", "upper zone". And usually, this kind of indicators named "bars" not the "bands".

If not to follow the standards (and **in my opinion** much easier to understand):
"Volume Indicator (Lower Zone)"
"Volume Indicator (Middle Zone)"
"Volume Indicator (Upper Zone)"

Note.
It is wise to use the "above the target level", "below the target level" when working with signals.

**Pull request merged**
