### PR TITLE
 obs-scripting: Allow passing python methods as callbacks

### PR DESCRIPTION
**Pull request by Penwy**
### Description

When adding an object as callback, obs-scripting-python requires the
object to be of function type, which excludes bound method objects, 
although they are perfectly valid as callback objects.

This changes the type check in functions that add script callbacks so 
that bound methods pass it.

### Motivation and Context

There's no technical impossibility for bound methods to be used as 
callbacks, not allowing them to be used as such only removes potential 
functionality from python scripts.

### How Has This Been Tested?

This has been tested, on Ubuntu 22.04, by using the script linked below, and 
verifying  that the bound methods it requests to set as callbacks are correctly 
added, triggered and removed.
[method_callback.zip](https://github.com/obsproject/obs-studio/files/11495058/method_callback.zip)

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
Please remove a space at the beginning of the commit message.

**Comment by Penwy** [comment]
I'm sorry, which commit message?
I don't see where exactly there is an extraneous space.

**Comment by norihiro** [comment]
> I'm sorry, which commit message?

It's b711f1c.
The title line has a white space at the beginning.
```patch
- obs-scripting: Allow passing python methods as callbacks
+obs-scripting: Allow passing python methods as callbacks
```

**Comment by Penwy** [comment]
Sorry for that, I had missed it. Thanks.

**Comment by PatTheMav** [comment]
While this might seem to work on the face of it, it has one major issue:

Bound methods are not "stable" memory-wise and OBS internally uses pointers to the actual Python function objects to maintain its list of callbacks. This works well for functions defined in the module: Their PyObject is created once when the script is parsed and are "stable" for the entire lifetime of the script object.

Bound methods are created on demand, which has unfortunate consequences, as exhibited by your script:

The memory address of `obj1.frontend_callback` in the `script_load` block might be `0x11f97cc80`. The memory address of `obj1.frontend_callback` in the `script_unload` block is `0x11f97ce80`.

So from the point of view of `libobs`, these are two entirely different functions:

* The function _added_ as a callback is not removed
* The function _removed_ as a callback was never added

The only reason this works is that we mark all callbacks as removed when a script is unloaded. So the next time a signal is emitted, `libobs` will try to call the _added_ callbacks, but remove them because they were marked as "removed".

When it comes to just calling bound functions, this difference in memory addresses (Python will generate new bound method objects as needed) is not an issue. Alas `libobs` uses these addresses to identify functions and keep track of them and bound methods generate too much "garbage" data.

So from my POV we can't merge this because it already does lead to unexpected consequences with the provided test case and might lead to even more issues and quirks script developers might not expect (see also https://github.com/obsproject/obs-studio/issues/8290 which has the same core issue).

Scripting in OBS was designed with short and simple scripts and module-level functions, OOP and bound methods are out of scope as such (at least as far as using them for interactions with `libobs` directly).

**Pull request closed without merging**
