### PR TITLE
UI: Add always on top checkbox to projector context menu

### PR DESCRIPTION
**Pull request by Bennik2000**
### Description
Add a simple checkbox to the context menu of a projector or the multiview window.

grafik

### Motivation and Context
The projector windows (especially the multiview projector) are very useful. Having them always on top is useful and this checkbox provides a way to toggle this feature without opening the settings dialog.

Also reported on the idea page [here](https://ideas.obsproject.com/posts/848/always-on-top-option-for-multiview-window)

### How Has This Been Tested?
Tested it with multiple projectors (fullscreen and windowed) on Windows 10. This won't likely affect other areas of code or break other functionality.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
If I'm reading this correctly, this uses the existing system setting, and will affect all projectors, yes? I wonder if we'd need to make the wording a bit clearer.

**Comment by Bennik2000** [comment]
Yes, this checkbox affects all projectors

**Comment by cg2121** [comment]
I would suggest making the context menu checkbox for the current projector only, so individual projectors can override the global setting.

**Comment by Bennik2000** [comment]
Now, the global "always on top" setting is used. As soon as the user checks or unchecks the checkbox it overrides the global setting. 
The "always on top" state gets saved when OBS is closing and is loaded at startup

**Pull request merged**
