### PR TITLE
cmake: Generate PDB files for Release builds

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Add /Zi and /DEBUG:FULL to enable PDBs. /DEBUG alters /OPT defaults, so manually set them back.

### Motivation and Context
I hear the shipping versions of OBS are built with RelWithDebInfo. I think it makes sense to have both build configurations, RelWithDebInfo for iterating on optimized builds, and Release for actual release with full optimizations. We can't debug user crash dumps without symbols, so that's where this change comes in.

Comparing RelWithDebInfo and Release build configurations on Windows, it looks like the three differences:

Debug symbols (implied settings in [brackets]):
RelWithDebInfo: /Zi (CL) and /debug, [/OPT:NOREF, /OPT:NOICF] (LINK)
Release: [/OPT:REF, /OPT:ICF] (LINK)

Inlining:
RelWithDebInfo: /Ob1 (CL)
Release: /Ob2 (CL)

Incremental linking:
RelWithDebInfo: /INCREMENTAL (LINK)
Release: /INCREMENTAL:NO (LINK)

With or without this change, RelWithDebInfo a bit more bloated because of less aggressive inlining than Release according to VMMap: 203192 KB -> 199592 KB

### How Has This Been Tested?
Verified settings and symbol resolves in VS for exe, dll, and lib projects. CPU% in OBS and Task Manager didn't seem to move. There doesn't appear to be any effect in terms of code size when comparing snapshots with VMMap.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Xaymar** [comment]
I'm confused for why this is necessary, given that if you want symbol files you'd normally build RelWithDebInfo, and if you don't want them you'd build with Release. Is there even a point to having RelWithDebInfo (literally "Release With Debug Info") when changing Release to also have Debug Info?

Edit: Wouldn't it just be better to add the optimized settings to RelWithDebInfo instead?

**Comment by jpark37** [comment]
"I think it makes sense to have both build configurations, RelWithDebInfo for iterating on optimized builds, and Release for actual release with full optimizations. We can't debug user crash dumps without symbols, so that's where this change comes in."

Some settings can take a long time to build, e.g. /LTCG, or sometimes you might want to trade off speed for easier debug, as CMake does with /Ob1 vs. /Ob2. I also think CMake's stance that Release builds don't need symbols is really weird. Who puts code into production that they can't debug?

**Comment by kkartaltepe** [comment]
"We can't debug user crash dumps without symbols, so that's where this change comes in."

Users are using builds provided by us, for which we already have symbols, and in-fact everyone has symbols since they are part of the distribution. So I'm not sure what you mean here?

**Comment by jpark37** [comment]
I meant that if we want to start handing out the Release build instead of RelWithDebInfo build, which is what I assume is being given, then the Release build would be better off with symbols built.

**Comment by kkartaltepe** [comment]
This seems more like a misunderstanding of cmakes, albeit gcc flavored, terms. Of course if we wanted to use Release, what would you suggest for Linux and Mac distributions? Should they amend the Release flags to build Debug symbols as well? This is precisely what RelWithDebInfo is for "I want a release build with debug symbols".

If you feel RelWithDebInfo has insufficient optimizations turned on then why not just PR for adding the optimizations you feel appropriate instead of breaking the cmake semantics further between windows and all other platforms?

**Comment by jpark37** [comment]
I haven't verified first-hand, but I've read that on Clang/GCC, CMake builds RelWithDebInfo using -O2 and Release with -O3. I think the most straightforward read of these two configs is that RelWithDebInfo is meant for quicker developer iteration, and Release is a slower-building and harder-to-debug config meant for production use.

I set up the PR this way because I see it as more of an abuse to promote RelWithDebInfo for production than make Release viable by adding debug symbols. Given that OBS uses the standard CMake build types, ideally the Release config should be the one modified into shipping state for all platforms.

**Comment by jpark37** [comment]
I'll revisit build settings another day. It'll probably look a lot different than this change.

**Comment by GoodayTH** [comment]
Thank you this issue very help for me

**Pull request closed without merging**
