### PR TITLE
libobs-winrt: Handle exception of winrt and reset WGC if need.

### PR DESCRIPTION
**Pull request by wangshaohui1314**
### Description

Handle exception of GraphicsCaptureSession::IsCursorCaptureEnabled .

### Motivation and Context

Lost logic to handle exception.

### Types of changes
Bug fix (non-breaking change which fixes an issue

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by jpark37 — COMMENTED** [review]
Have you seen this code throw? I don't want to add unnecessary error handling. We have already checked that cursor capture is supported via capture_cursor.

**Comment by wangshaohui1314** [comment]
> Have you seen this code throw? I don't want to add unnecessary error handling. We have already checked that cursor capture is supported via capture_cursor.

Yes, I received an exception here whose OS version is : 
Windows Version: 10.0 Build 19041 (revision: 508; 64-bit)

**Comment by jpark37** [comment]
What's the HRESULT?

**Comment by wangshaohui1314** [comment]
> What's the HRESULT?

HRESULT is 0x800706ba

**Comment by jpark37** [comment]
Are you doing something strange? I don't know of anyone else who is reporting this.

**Comment by wangshaohui1314** [comment]
> Are you doing something strange? I don't know of anyone else who is reporting this.

No, just choose a window and select "WGC capture mode".
Besides, this exception only appeared once and cann't be reproduced.

**Comment by jpark37** [comment]
We probably don't want to just log and ignore. This should propagate upwards, and we may want to reset the capture if we encounter this.

**Comment by wangshaohui1314** [comment]
> propagate upwards

It seems no logic about pushing exception from libobs-winrt and resetting winrt in window/monitor plugin.
Do you mean I should add return bool for _winrt_capture_show_cursor_ and reset winrt object while ticking sources ?

**Comment by wangshaohui1314** [comment]
@jpark37 

While reviewing obs_queue_task, I find a bug.
About _obs_reset_video->obs_free_video->circlebuf_free(&video->tasks)_, before freeing video->tasks, we must run all tasks saved in it.

For example, for duplicator-monitor plugin and window plugin, their destroy operation are both posting to graphics thread by  _obs_queue_task(OBS_TASK_GRAPHICS, real_destroy_func, plugin_ptr, false)_.
The async-task are saved in obs_core_video::tasks. However, obs_reset_video may be called when user modify video settings.

**Comment by jpark37** [comment]
> It seems no logic about pushing exception from libobs-winrt and resetting winrt in window/monitor plugin.
> Do you mean I should add return bool for _winrt_capture_show_cursor_ and reset winrt object in video_tick ?

Yes, we should return a bool from that function.

**Comment by jpark37** [comment]
I don't know anything about the task setup. Maybe @jp9000 can answer that.

**Comment by wangshaohui1314** [comment]
@jp9000   
If you think this commit is OK, I will create a PR.
https://github.com/wangshaohui1314/obs-studio/commit/3f11830aeaa0dfbb7d5ee4b90ca5409ba8b644bf

**Comment by jpark37** [comment]
I think task changes should be a separate PR.

Were you going to modify video_tick to use the return value?

**Comment by wangshaohui1314** [comment]
> I think task changes should be a separate PR.
> 
> Were you going to modify video_tick to use the return value?

Yes, task change will be in another PR. But I am not sure if my commit is good enough until JIM reviews.

I am looking at code in duplicator-monitor and window plugin, it is easy to check return value for cursor interface. But how 
about other interfaces of libobs-winrt? It seems not good enough to do reset job after checking _winrt_capture_show_cursor_. 

How about add _"**bool need_reset**_" in _struct winrt_capture_ ?
_need_reset_ should be set with true in libobs-winrt wherever it is necessary, checked in video_tick before resetting.

**Comment by wangshaohui1314** [comment]
> I think task changes should be a separate PR.
> 
> Were you going to modify video_tick to use the return value?

I commited the code without adding "bool need_reset".

**Comment by jpark37** [comment]
You can combine into one commit for the cursor fix. The changes are codependent; we can't build each commit individually.

I have a few more changes that I would like, but I don't want to describe them all. Just look at this commit: 216dda826e501bb2811aa76b9f92809dca16ccb5

I can either make a new PR, or you can copy the changes into yours, whichever you prefer. Let me know if you have any questions.

**Comment by wangshaohui1314** [comment]
> You can combine into one commit for the cursor fix. The changes are codependent; we can't build each commit individually.
> 
> I have a few more changes that I would like, but I don't want to describe them all. Just look at this commit: [216dda8](https://github.com/obsproject/obs-studio/commit/216dda826e501bb2811aa76b9f92809dca16ccb5)
> 
> I can either make a new PR, or you can copy the changes into yours, whichever you prefer. Let me know if you have any questions.

Please make a new PR included my change. I am being familiar with git ~~~

**Comment by jpark37** [comment]
Created PR #4668.

**Comment by wangshaohui1314** [comment]
> Created PR #4668.

Now should I close this PR ?

**Comment by jpark37** [comment]
Yeah, that's fine. I would create a new one for the task changes.

**Pull request closed without merging**
