### PR TITLE
libobs: Fix crash when plugins delete properties in callback

### PR DESCRIPTION
**Pull request by ujifgc**
If a plugin removes a property when processing 'modified' property callback, OBS WILL CRASH.

### Description

This commit moves callback processing to after iterating over properties, thus removing the chance to crash OBS.

### Motivation and Context

Example of offending plugin: obs-source-record

Offending code: https://github.com/exeldro/obs-source-record/blob/76da992729ef6d6ed2f691235ca0e086127f2716/source-record.c#L1035-L1055

### How Has This Been Tested?

After applying the change OBS no longer crashes when loading the plugin settings.

### Types of changes

I have changed `obs_properties_apply_settings_internal` to put all properties with callbacks in a temporary array.

After iterating through properties `obs_properties_apply_settings` calls every callback from the temporary array.

The official API of `obs_properties_apply_settings` remains unchanged.

Reference to the change that might have introduced the crash: https://github.com/obsproject/obs-studio/commit/78aa4e03dca62c3e1439cae2eade1c6d247c8a78

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
This is an interesting one, deleting items from a list while it's being iterated over is generally not a great idea, even before 78aa4e03dca62c3e1439cae2eade1c6d247c8a78 this could result in crashes if the current item were deleted so that `p = p->next` would have read from free'd memory.

One way to restore the previous behaviour would be to manually fix up the `tmp` pointer after the callbacks:
```c
if (tmp != p->hh.next)
    tmp = p->hh.next;
```
But perhaps deferring the callback like this is a better option.

**Comment by ujifgc** [comment]
@derrod I agree that changing the list while iterating through it is a bad thing. But right now the API documentation here https://docs.obsproject.com/reference-properties#c.obs_property_set_modified_callback2 states that modifying the list in the callback is expected. I have not found in the current coddebase where the return value of the callback is checked. I assume the check is just not implemented right now.

**Comment by PatTheMav** [comment]
Given that the properties can be changed while iterating over them, using a "stable" copy for iteration is the right approach. I did wonder if there are unforeseen consequences when a properties' callback is called _after_ a prior callback removed the property entirely, but that's where the crash would happen, so I don't think anybody might have relied on that behaviour.

It _does_ mean that such callbacks will still be executed though, which might be considered a side-effect.

**Review by Lain-B — APPROVED** [review]
I'm going to tentatively approve these changes, but one thing I will tell you is that it's probably better to make a property invisible than to delete it. That's what I typically did on all the core obs plugins (v4l2 being the exception, but I didn't write that one). It's not great, and that's my fault due to the way I programmed the properties system, but it's probably the safer than actually deleting a property.

I shouldn't have allowed property removal. But oh well, cat's out of the bag for now. I'll probably just deprecate the removal function or something at some point.

**Pull request merged**
