### PR TITLE
rtmp-services: Add PolyStreamer service

### PR DESCRIPTION
**Pull request by jcward**
### Description

Added the new [polystreamer.com](https://polystreamer.com) multi-streaming service to the **services.json** file, and incremented the version number in the accompanying **package.json** file.

### Motivation and Context

PolyStreamer is an new multi-streaming service (like restream or castr), and it'd be awesome if it was a built-in selection in OBS. :+1: 

### How Has This Been Tested?

I validated the JSON, and built OBS and tested streming to the service from the UI dropdown:

Selection_999(1541)

Selection_999(1543)

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format). **Seems not applicable to my JSON changes**
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst). **I have, but didn't see any reference to services.json**
- [x] My code is not on the master branch. **I branched from master, and PR'd to master -- is this correct?**
- [x] The code has been tested. **Yes, see screenshots above**
- [x] All commit messages are properly formatted and commits squashed where appropriate. **I believe so**
- [ ] I have included updates to all appropriate documentation. **I'd be happy to - I don't think that applies.**

### CODE REVIEW

**Comment by dodgepong** [comment]
> I have read the contributing document. **I have, but didn't see any reference to services.json**
> All commit messages are properly formatted and commits squashed where appropriate. **I believe so**

The contributing document also provides guidelines for formatting commit names. This commit name does not conform to those guidelines (too long, missing prefix, not in present tense). Please fix the commit name and force push (i.e. do not include a fixup commit -- the PR should end up with exactly 1 commit).

> My code is not on the master branch. **I branched from master, and PR'd to master -- is this correct?**

Yes, this is correct.

**Comment by jcward** [comment]
@dodgepong - thanks for the direction, done.

**Comment by dodgepong** [comment]
Thanks.

Also, you don't need to set anything for `alt_names`, that's only used when renaming a service. Since this is a new service, it's not necessary.

**Comment by jcward** [comment]
Ok, no alt_names, and I updated the service name to include the `.com` suffix (seems helpful, and looks like other web-based services do.)

**Comment by dodgepong** [comment]
> I updated the service name to include the .com suffix (seems helpful, and looks like other web-based services do.)

Up to you. I recommend using whatever your actual branding is.

**Pull request merged**
