### PR TITLE
obs-webrtc: Require libdatachannel 0.20 or newer

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Since now we rely on a stable version, we can now set a minimum requirement for libdatachannel in CMake.

### Motivation and Context

Error out, if an older version is used.

### How Has This Been Tested?

Replaced the number with 0.21 and CMake complained.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Seems fair. @PatTheMav ?

**Comment by PatTheMav** [comment]
> Seems fair. @PatTheMav ?

Yeah I see no obvious issues with this as long as the CMake package properly provides its version number.

**Comment by RytoEX** [comment]
> > Seems fair. @PatTheMav ?
> 
> Yeah I see no obvious issues with this as long as the CMake package properly provides its version number.

As far as I know, libdatachannel does have a version set in its CMake `project` call.

**Comment by tytan652** [comment]
For context, when obs-webrtc was added libdatachannels 0.19 alpha was returning 0.18.
Now that we are on a stable version we can set a minimum version.

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
