### PR TITLE
rtmp-services: Update to the SermonAudio entry

### PR DESCRIPTION
**Pull request by astudios123**
We have a new back-end to the SermonAudio webcasting system which required a new URL and now allows for increased bitrates.

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I understand that this is a simple change, but in the future please do not ignore the template. we would prefer that it be properly filled out, and it would avoid the below issues:

Your commit title is incorrect. It should have the prefix for `rtmp-services:`. 
Additionally, you did not update the `package.json` version number which is required for any updates to rtmp services.

**Comment by Fenrirthviti** [comment]
Also, please include the old name under `alt_names` as seen here:

https://github.com/obsproject/obs-studio/blob/master/plugins/rtmp-services/data/services.json#L585-L587

This will avoid breaking backwards compatibility and ensure that users receive the new ingest URLs.

**Comment by Fenrirthviti** [comment]
Code changes look good, just need to squash the commits now and this can be merged.

**Comment by astudios123** [comment]
Sorry. But I've never used Git before. Is this something you can do for me .. please?

**Pull request merged**
