### PR TITLE
vlc-video: Support subtitle track up to 1000

### PR DESCRIPTION
**Pull request by jjm2473**
### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
Please fill out the PR template and run clang-format on your code.
The prefix doesn’t need ˋplugins/ˋ, it can just be ˋvlc-videoˋ

**Comment by jp9000** [comment]
Hi there, please specify context for what happened to prompt this PR. I assume that you encountered tracks with arbitrary track numbers? I'm fine with the change if so, but I'd like you to verify the context.

**Comment by jjm2473** [comment]
> Hi there, please specify context for what happened to prompt this PR. I assume that you encountered tracks with arbitrary track numbers? I'm fine with the change if so, but I'd like you to verify the context.

Some movies has over 10 subtitle tracks, I can't select target track (No.15) from GUI, but I tried edit `.json` config file, it works.

**Comment by jjm2473** [comment]
> Please fill out the PR template and run clang-format on your code. The prefix doesn’t need ˋplugins/ˋ, it can just be ˋvlc-videoˋ

Sorry, I have not such envirentment to compile or test it. I will improve the commit.

**Review by RytoEX — APPROVED** [review]
While an ideal solution might use libvlc to detect and list valid subtitle tracks, this resolves an issue with a one-line change that is seemingly harmless.

**Pull request merged**
