### PR TITLE
Cherry Picks for 29.1.2

### PR DESCRIPTION
**Pull request by derrod**
### Description

Potential cherry-picks for 29.1.2:

Pull requests:
- https://github.com/obsproject/obs-studio/pull/8875
- https://github.com/obsproject/obs-studio/pull/8891
- https://github.com/obsproject/obs-studio/pull/8892 (minus editorconfig changes)
- https://github.com/obsproject/obs-studio/pull/8894
- https://github.com/obsproject/obs-studio/pull/8900
- https://github.com/obsproject/obs-studio/pull/8901
- https://github.com/obsproject/obs-studio/pull/8830
- https://github.com/obsproject/obs-studio/pull/8826
- https://github.com/obsproject/obs-studio/pull/8905
- https://github.com/obsproject/obs-studio/pull/8885
- https://github.com/obsproject/obs-studio/pull/8933
- https://github.com/obsproject/obs-studio/pull/8923
- https://github.com/obsproject/obs-studio/pull/8927
- https://github.com/obsproject/obs-studio/pull/8937
- https://github.com/obsproject/obs-studio/pull/8814
- https://github.com/obsproject/obs-studio/pull/8917 
- https://github.com/obsproject/obs-studio/pull/8944 
- https://github.com/obsproject/obs-studio/pull/8897
- https://github.com/obsproject/obs-studio/commit/a12d5812af59197ed36dd068abadf9b50d0295d5
- https://github.com/obsproject/obs-studio/commit/40ce466f4dd6356d8a42a0cc20ea13c5833a41d3
- https://github.com/obsproject/obs-studio/commit/192d33ce860aea1354d33282925200aeb21981fe
- https://github.com/obsproject/obs-studio/pull/8975

The translation cleanups are perhaps debatable but they won't do any harm either.

### Motivation and Context

Want to get hotfix out, especially for #8905, #8923, #8900, and #8901

### How Has This Been Tested?

N/A

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
https://github.com/obsproject/obs-studio/pull/8917 and the first commit from https://github.com/obsproject/obs-studio/pull/8897 (once merged) would also be good.

**Comment by TianQiBuTian** [comment]
Maybe need to update the translation files and clean up obsolete translations.

**Review by RytoEX — APPROVED** [review]
As this is cherry-picking previously reviewed bug fix PRs, this should be fine.

**Comment by Lain-B** [comment]
requesting inclusion of a12d5812af59197ed36dd068abadf9b50d0295d5, 40ce466f4dd6356d8a42a0cc20ea13c5833a41d3, and 192d33ce860aea1354d33282925200aeb21981fe

**Comment by RytoEX** [comment]
> requesting inclusion of [a12d581](https://github.com/obsproject/obs-studio/commit/a12d5812af59197ed36dd068abadf9b50d0295d5), [40ce466](https://github.com/obsproject/obs-studio/commit/40ce466f4dd6356d8a42a0cc20ea13c5833a41d3), and [192d33c](https://github.com/obsproject/obs-studio/commit/192d33ce860aea1354d33282925200aeb21981fe)

Added.

**Comment by RytoEX** [comment]
Also added #8975. My approval still stands.

**Pull request merged**
