### PR TITLE
libobs: Additionally use SetThreadDescription if possible

### PR DESCRIPTION
**Pull request by henke37**
It's the better way to declare thread names, but you need Windows 10, version 1607 to use it.

### Description
Use the `SetThreadDescription` function to register the thread name.

### Motivation and Context

Using the `SetThreadDescription` function lets the entire system know about the thread name, not just a currently attached debugger.

### How Has This Been Tested?
Built my own version of obs and ran it. Checked that the new code runs. Verified that the function has the intended effect by manually skipping the legacy code and watching the thread list in the debugger.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jpark37** [comment]
This function is marked WINAPI in the header. This might not work on 32-bit Windows without it.

**Comment by henke37** [comment]
Which function? `SetThreadDescriptor`? It's fetched using `GetProcAddress` so that the code just skips calling it if it's not available.

**Comment by jpark37** [comment]
Yes, SetThreadDescriptor. If you cast it to a function pointer with the wrong calling convention, I don't think that will work right on the 32-bit build. __stdcall is ignored by the x64 compiler, so you won't see any problems there.

**Comment by henke37** [comment]
You should've said the magic word "calling convention" and I would've fixed this yesterday. But sure, it only took a couple of minutes to figure out where calling conventions go in the function pointer syntax.

**Pull request merged**
