### PR TITLE
UI: Clarify message info

### PR DESCRIPTION
**Pull request by SuslikV**
Makes it clear how to perform the suggested action to disable the
bandwidth test mode.

### CODE REVIEW

**Comment by Vainock** [comment]
This change is not needed because you already know how to enable the test mode and by that also how to disable it again.

**Comment by SuslikV** [comment]
Maybe.

**Comment by Fenrirthviti** [comment]
I also agree this is an unnecessary change.

**Comment by SuslikV** [comment]
So, nobody is interested in it. OK, I will close it in few days.
It's insignificant change in comparison of what we already have in obs ^_^

**Pull request closed without merging**
