### PR TITLE
UI: Batch remux and drag/drop support on remux dialog

### PR DESCRIPTION
**Pull request by nleseul**
This changes the remux dialog to support a collection of input/output
pairs, presented as a QTableView. Standard Qt icons are used to indicate
the state of each entry during a remux operation. Drag/drop support is
added to populate the list quickly. Both Dark and Rachni themes are
updated to make QTableView look reasonable.

Relevant text is added in the localization files. The Remux.FileExists
string has been removed and replaced with a Remux.FileExistsWithPath
string that includes the specific file being indicated.

### CODE REVIEW

**Comment by nleseul** [comment]
I'll attach a screenshot that I previously posted on the forum of what the updated dialog ends up looking like. 

obs studio batch remux

I renamed that one localization string on the assumption that this will flag the string as needing to be retranslated by localizers, rather than having other translations just continue to blindly use the old string without the path included. No idea if that's the best practice for the localization workflow, though; please let me know if I should just edit the existing string in place.

**Comment by SuslikV** [comment]
By small changes to:
https://github.com/jp9000/obs-studio/blob/master/libobs/media-io/media-remux.c#L228

like this:
```
AVDictionary *dict = NULL; //muxer params

//set fastwrite for mp4/mov format only, exact match...

if ((RemuxDialogFastWriteCheckBoxON) &&
    (strcmp(job->ofmt_ctx->oformat->name, "mp4") ||
    strcmp(job->ofmt_ctx->oformat->name, "mov"))) {

		ret = av_dict_set(&dict, "movflags", "faststart", 0);
		if (ret < 0) {
			blog(LOG_ERROR, "media_remux: Error to set
					muxing keys: %s", av_err2str(ret));
		}
}

ret = avformat_write_header(job->ofmt_ctx, &dict);

av_dict_free(&dict);
```

and new checkbox in remux UI it will be possible to add _fastwrite_ to all remuxed mp4/mov files.

What do you think?

**Comment by SuslikV** [comment]
Right now it doesn't support multiple files selection (only drop) and lacks combobox to convert all files to specific format.

Tools button's design is bad. The window min width is too large. Last two - is my IMHO.

**Comment by jp9000** [comment]
I'm sorry for not having responded to this sooner -- I'm juggling a number of different things on the project and so pull requests often get delayed.  I'm going to try to respond more promptly to pull requests in the future.

The pull request is a great first step.  The way you designed it to browse files and automatically add new values is pretty much exactly how it should be done.  However, there are a number of issues with this proposed change:

1.) On the top of the list box, there are three sections:  the first section is a tiny little blank space, the second section is "OBS Recording", and the third section is "Target File".  That section on the left seems unused, and should be removed.

2.) I can't help but feel there needs to be the ability to mux directories, or at least select multiple files in the file open box.  Otherwise this isn't much of a "batch" remux because you have to continually select each file manually.  This makes it tedious to use on many files.

Please let me know if you are willing and have time to fix these issues or not.

**Comment by nleseul** [comment]
Not a problem... I haven't had much time to think about this for a while either. 

To your points:

1. You're referring to the column header for the status column on the left? I'm not sure if QTableView gives you any way to hide the header for a single column... even if it did, is a blank dark gray space better than a blank light gray rounded rectangle?<br/><br/>As an alternative, what do you think about making that column wider so a header label like "Status" will fit there? That would at least help clarify the purpose of that column to the user, at the cost of a bit of unused space around the square-ish icons.

2. The intended workflow is for users to add multiple files to the dialog with drag/drop. It's true that multi-selection wouldn't be a terrible thing to support as well, but it's a bit architecturally complex to do with my current implementation (each entry's "Browse" button is owned by an item delegate and just knows how to modify the text field associated with it). I can try and come up with a way of inserting new rows in response to a browse button, if you think it's important.<br/><br/>Regardless, you are correct that even with drag/drop, dropping directories doesn't work properly right now. I'll definitely look into fixing that.

**Comment by jp9000** [comment]
If you're unable to remove that left column then that's okay.  I think the key important thing is just that users need to be able to select/add multiple files at least.

**Comment by nleseul** [comment]
Fair enough. I just got done with my refactor of this code, so the PR should now be updated with those changes. If I've done everything right, it should now support multi-selection in the file dialog as well as drag/drop of directories. I've also cleaned up the code a lot and streamlined the UI a bit as follows:

* It now has both "Clear all" and "Clear finished" buttons
* The "Remux" button now changes to a "Stop" button during an operation, so you can interrupt the process without closing the window and starting over
* The "Close" button has been removed, since it's redundant to the window's "X" and doesn't really add enough to justify the space it takes up, in my opinion.

**Comment by jp9000** [comment]
Well, actually the close button is useful because on Linux, because unfortunately on Linux there is no X button like on windows/mac.

**Comment by nleseul** [comment]
Someone actually made a Linux window manager with no standard way to close a window? Wow. 

Well, it's easy enough to add back; the PR is updated. Still wish I could resize those buttons so the important one stands out more, but Qt Designer's layout tools weren't cooperating very well with me when I tried it.

**Comment by jp9000** [comment]
It's gnome 3, the most common one.  You can close it via right-clicking on the title bar and closing there, but otherwise it's nice to have the buttons available.

**Comment by WizardCM** [comment]
A few notes after running a small test myself (I dragged 5 files across to the dialog)
* If any of the files already exist, it gives you a Yes/No dialog to continue, and if you click "No" there's no way to easily tell which of those files caused the conflict - maybe a 'Skip this file' kind of button would be handy for a future iteration?
* It's a little unclear how to individually remove files as the buttons aren't revealed on hover. Not sure if most users would notice/care, though.
* The default Target File field (in my test) showed a backslash before the filename, inconsistent with the original path:
D:/User/Videos/Stream VoD/2017-06-02 20-38-32.mkv -> D:/User/Videos/Stream VoD\2017-10-05 12-47-22.mp4

Overall though - looking good!

**Comment by jp9000** [comment]
I know it's taken me a long time to finally get to reviewing this, so I'm going to fix up the merge conflicts and code styling issues for you in this particular case.  I also changed it so that it automatically starts editing the first value so the user knows they can edit/add items a bit more easily (just a minor user experienced improvement).  But you did a superb job with this.  Thank you for making it, and apologies for taking a while to get to it -- it was just a lot of code to review so sometimes I put things on the backburner.

Merging with those changes shortly -- you will see "closed via [commit]"

**Comment by nleseul** [comment]
No problem! Thanks for taking care of it.

**Pull request closed without merging**
