### PR TITLE
CI: Crowdin Synchronization

### PR DESCRIPTION
**Pull request by Vainock**
### Description

This adds 2 GitHub Actions that streamline the synchronization and localization process between this repository and the Crowdin project.

Features of the 'Download Action':
- Updates all translations in the main repository and all 3 submodules that include translateable content (obs-browser, obs-vst & enc-amf).
- Updates the `AUTHORS` file with both Git contributors and translators.
- Updates the translations of the `UI/xdg-data/com.obsproject.Studio.desktop`.
- Updates the `UI/data/locale.ini`: New languages need 60% to be added, languages with less than 30% will be removed.

Note: The GitHub Action only pushes submodule changes to the main repository if it is even with the main repository to prevent other commits from being implemented without knowing. The translation updates would still get pushed to the submodules, but will be left there waiting for a version bump.

Features of the 'Upload Action':
- Updates the English locales on Crowdin.

**Required Repository Secrets:**
- `CROWDIN_SYNC_CROWDIN_PAT` for authorizing with the Crowdin API. Go to https://crowdin.com/settings#api-key to generate one (needs to come from the owner or a manager).
- `CROWDIN_SYNC_GITHUB_PAT` for pushing changes to the submodules. Get it from https://github.com/settings/tokens. It requires access to `public_repo` and has to come from a person with push access to the main repository and the 3 submodules (obs-browser, obs-vst & enc-amf).

Code: https://github.com/obsproject/crowdin-synchronization

### Motivation and Context

Reduce the amount of manual steps, people and time required for releasing a new version.

_If in some future the release process is automated, it would even allow automated translation updates for release builds._

### How Has This Been Tested?

Download:
https://github.com/crowdin-sync-testing/obs-studio/commit/3d49472066c6a03c93a388ce76f9b02a6c3a564f triggered via https://github.com/crowdin-sync-testing/obs-studio/runs/4014006430?check_suite_focus=true

Upload:
https://github.com/crowdin-sync-testing/obs-studio/runs/4021661956?check_suite_focus=true triggered via https://github.com/crowdin-sync-testing/obs-studio/commit/d3cf4c9e294eb1c2346e6ae4130fdf95c64b1925

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I've only ever seen the button to "Rerun all jobs" - what does the UI look like for manually triggering a job on a commit in the main repo? Additionally, I wonder if this'd be better suited as something that creates a PR so it can be double checked.

**Comment by Vainock** [comment]
If there is a workflow in the repo with a manual step, you have to select the workflow and then click on "Run Workflow". It then looks like the following: (taken from my mobile)


Making a PR instead of a direct commit would be a fairly easy change. I'm open for that.

**Comment by WizardCM** [comment]
Oh, as a side note I'm also going to put in a vote to **definitely** have the repo for the translator owned by obsproject.

**Comment by RytoEX** [comment]
Setting this to Draft while we consider the following:

> I can understand if you don't want to give some code you don't control access to your repositories. If that's the case, the only solution would be to give you this control by making a copy of my repository and linking the GitHub Action to the new url.

What does this offer us over the existing Crowdin integrations, such as their GitHub Action?
https://support.crowdin.com/github-crowdin-action/

**Comment by Vainock** [comment]
The Crowdin GitHub Action does not provide all the features this repository requires. It does not update
- the AUTHORS file with its translators and Git contributors
- the [com.obsproject.Studio.desktop file](https://github.com/Vainock/obs-studio/blob/master/UI/xdg-data/com.obsproject.Studio.desktop)
- translations in submodules

And a custom action also allows features that are not required but nice-to-have:
- remove language files from removed languages
- remove source-equal translations (reason: see above)

Crowdin's Action also creates one commit for all changes every 24h per language.

**Comment by Vainock** [comment]
@RytoEX 
I'm right now planning to also automate the upload process of the en-US.ini source files, which means I would like to have 2 GitHub Actions hosted in one repository, one for updating the translations on GitHub and the other for updating the source files on Crowdin. If you create a repository in the obsproject org it should be called something like 'localization' to represent the whole process. I would then like to submit a PR with the structure and code for both actions.

Keeping the whole localization process in a single repository allows code sharing between the 2 GitHub Actions.

**Comment by Vainock** [comment]
https://github.com/Vainock/crowdin-synchronization

As already mentioned in the previous message, this now includes the full sync process between Crowdin and OBS Studio. Everything was tested countless times locally and [in my fork](https://github.com/VainockOrg/obs-studio/actions).
The upload process to the Crowdin project was also tested with a private Crowdin project that had the same structure as the OBS Studio Crowdin project.

Please tell me how to continue from here on (and if you are even still interested).

**Comment by WizardCM** [comment]
Thank you for all your efforts so far. I'm personally very interested in getting this officially going - to confirm, as of today's update we only need to fork the `crowdin-synchronization` repo, correct?

**Comment by Vainock** [comment]
Correct. It includes obs-translation-updater in the form of the download directory.

**Comment by Fenrirthviti** [comment]
We are certainly interested in this, but are still hard at work on the v27.1 release, finalizing all the things that were not quite ready for v27. This certainly has been something we've talked about and want to include, thank you for your patience until we have time to look!

**Comment by WizardCM** [comment]
As the first step, I've forked your repo to the OBSProject org [here](https://github.com/obsproject/crowdin-synchronization). I plan on doing a code review sometime this week.

**Comment by notr1ch** [comment]
I took a quick look over the code. One concern I have is that it seems to write to files with the contents of the ZIP downloaded from Crowdin without verifying the `zipEntry.entryName` is well-formed (filename is xx-yy.ini, correct path, no `../` etc). Should the ZIP be compromised through a Crowdin breach, this may allow arbitrary overwriting of files in the repository.

**Comment by Vainock** [comment]
> I took a quick look over the code. One concern I have is that it seems to write to files with the contents of the ZIP downloaded from Crowdin without verifying the `zipEntry.entryName` is well-formed (filename is xx-yy.ini, correct path, no `../` etc). Should the ZIP be compromised through a Crowdin breach, this may allow arbitrary overwriting of files in the repository.

Fixed: https://github.com/obsproject/crowdin-synchronization/pull/2
This makes the Action only commit specified files instead of all.

**Comment by Vainock** [comment]
Updated the code and PR description to reflect all recent changes. Still leaving this as a draft because the code hasn't been reviewed.

**Comment by dodgepong** [comment]
I have added both repository secrets as requested.

**Pull request merged**
