### PR TITLE
UI: Reintroduce faster theme switching

### PR DESCRIPTION
**Pull request by cg2121**
### Description
Based on (was reverted):
https://github.com/obsproject/obs-studio/commit/08cee21158c1f43956210418dd99ab763a90d2a2

This simplifies the faster switching code, as setting an empty
stylesheet resets it to default.

### Motivation and Context
Faster theme switching is a much better experience.

Simplifies https://github.com/obsproject/obs-studio/commit/08cee21158c1f43956210418dd99ab763a90d2a2

### How Has This Been Tested?
Tested on Ubuntu 22.04, with QT 6.2.4.

Switch themes and made sure things were indeed faster. Also tested with #7116 

### Types of changes
 - Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
> Switch themes and made sure things were indeed faster.

Tested on what platforms? Please be specific.

**Comment by cg2121** [comment]
> > Switch themes and made sure things were indeed faster.
> 
> Tested on what platforms? Please be specific.

Updated to include platform

**Comment by Fenrirthviti** [comment]
This will need testing on macOS and Windows before it can be safely merged.

**Comment by WizardCM** [comment]
Verified this works great in conjunction with #7118 on macOS and Windows. It significantly speeds up theme switching, and doesn't break overall styling.

It does reintroduce the one weird quirk I spotted previously which is that the QSlider QSS gets cleared, and I still can't find the cause of that.

**Review by WizardCM — APPROVED** [review]

**Pull request merged**
