### PR TITLE
CI: Build improved dylibbundler from source (handles @loader_path)

### PR DESCRIPTION
**Pull request by SCG82**
### Description

Handles @loader_path so all plugins (including obs-outputs.so) can be included instead of being managed individually. Added option for less verbose output.

### Motivation and Context

Removes need to check for changes in dependencies for plugins which weren't able to be included in current version of dylibbundler (obs-outputs.so).

### How Has This Been Tested?

Verified that OBS app bundle libraries all had correct install names & rpaths.

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jp9000** [comment]
I don't think this is necessary.  If we really needed something like this it should be a script, not something we build.

Besides, I don't really know if I see the value in this.  It's not like we have problems with build times even on macOS.

**Comment by SCG82** [comment]
> I don't think this is necessary. If we really needed something like this it should be a script, not something we build.
> 
> Besides, I don't really know if I see the value in this. It's not like we have problems with build times even on macOS.

The benefit of this version is not failing on dependencies which contain paths with @loader_path (such as mbedtls)

**Comment by jp9000** [comment]
We're not having those problems though.  I'm confused.

**Comment by SCG82** [comment]
> We're not having those problems though. I'm confused.

I'm guessing the reason line 42 of `CI/install/osx/buildApp.sh` is commented
Screen Shot 2019-12-16 at 6 24 42 PM
and lines 40-48 are added to `./CI/before-deploy-osx.sh`
Screen Shot 2019-12-16 at 6 25 30 PM
is because
Screen Shot 2019-12-16 at 6 42 56 PM
when trying to run with obs-outputs.so included in the list of files to fix up for dylibbundler.

**Comment by jp9000** [comment]
You know it's kind of strange, OBS appears to be able to make mac releases just fine without this.  Could you explain why that is and what this PR actually fixes?

**Comment by SCG82** [comment]
> You know it's kind of strange, OBS appears to be able to make mac releases just fine without this. Could you explain why that is and what this PR actually fixes?

Well actually, OBS 24.0.2 was missing the Qt library `iconengines/libqsvgicon.dylib`, which caused OBS (in systems with Qt installed) to load two sets of Qt binaries into the same process.
Screen Shot 2019-12-18 at 1 40 14 AM

In order to have a fully self-contained app bundle, every dependency (recursively) that isn't included by macOS (/usr/lib or /System/Library) needs to be copied inside the app bundle with install names changed for itself `install_name_tool -id` and all dependent libs `install_name_tool -change`.

The current method OBS is using is certainly an improvement. @DDRBoxman added a very useful search path argument (#2125) to https://github.com/auriamg/dylibbundler resulting in fewer dylibs needing to be manually fixed.
Screen Shot 2019-12-18 at 1 12 51 AM

 dylibbundler crashes if `obs-outputs.so` is included in the list of files to fetch dependencies and fix up.

dylibbundler-crash

I patched dylibbundler to correctly handle @loader_path, allowing obs-outputs.so to be included, eliminating the need to manually fetch & fix required dependencies (which may be different from those hand-patched in the script unless using the exact same version of all dependencies).

**Comment by Fenrirthviti** [comment]
If this is a patched binary, why are you not just submitting the patch to the dylibbundler code base instead of ours? This is a very strange pull request as we can't even easily review your patch.

**Comment by SCG82** [comment]
> If this is a patched binary, why are you not just submitting the patch to the dylibbundler code base instead of ours? This is a very strange pull request as we can't even easily review your patch.

I have and it has been merged (https://github.com/auriamg/macdylibbundler/pull/45 & https://github.com/auriamg/macdylibbundler/pull/46)

**Comment by jp9000** [comment]
I'm glad to see that.  I guess that means this pull request is a bit redundant then, no?

How about we don't merge this PR, and instead figure out some way to use the original directly, or maybe, just fix things up manually until the point in which the upstream's availability is finally present on CI servers?

**Comment by jp9000** [comment]
Because I've got to be honest with you, I don't want this PR preferably.  I'd prefer pretty much anything else.

**Comment by SCG82** [comment]
Yes, of course. I'll close the PR.

**Comment by jp9000** [comment]
I apologize for the trouble, and thank you for being patient with it.  I just felt really uncomfortable with having to include a binary or recompile a fork of another build tool.  I want to emphasize how much I appreciate you going to the lengths of submitting your changes in to the upstream so we didn't have to take that route.

**Comment by SCG82** [comment]
> I apologize for the trouble, and thank you for being patient with it. I just felt really uncomfortable with having to include a binary or recompile a fork of another build tool. I want to emphasize how much I appreciate you going to the lengths of submitting your changes in to the upstream so we didn't have to take that route.

No need to apologize. I actually agree with you.

**Pull request closed without merging**
