### PR TITLE
30.0 hotfix cherry picks

### PR DESCRIPTION
**Pull request by derrod**
### Description

Cherry picks for the first 30.0 hotfix.

PRs included:
- https://github.com/obsproject/obs-studio/pull/9803
- https://github.com/obsproject/obs-studio/pull/9806
- https://github.com/obsproject/obs-studio/pull/9845
- https://github.com/obsproject/obs-studio/commit/3e6797ca5bfe445381d721e407163b70b8de6d1e
- https://github.com/obsproject/obs-studio/pull/9866
- https://github.com/obsproject/obs-studio/pull/9880
- https://github.com/obsproject/obs-studio/pull/9881
- https://github.com/obsproject/obs-studio/pull/9879
- https://github.com/obsproject/obs-studio/pull/9875

### Motivation and Context

Bugs.

### How Has This Been Tested?

?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Also worth including:
* https://github.com/obsproject/obs-browser/pull/429

**Review by PatTheMav — APPROVED** [review]

**Comment by RytoEX** [comment]
Working through approvals on which PRs/commits are okay to cherry-pick. Current status:
* [x] https://github.com/obsproject/obs-studio/pull/9803 ✅
* [x] https://github.com/obsproject/obs-studio/pull/9806 ✅
* [x] https://github.com/obsproject/obs-studio/pull/9845 ✅
* [ ] https://github.com/obsproject/obs-studio/commit/3e6797ca5bfe445381d721e407163b70b8de6d1e ❓ 
* [x] https://github.com/obsproject/obs-studio/pull/9866 ✅
* [x] https://github.com/obsproject/obs-studio/pull/9880 ✅
* [x] https://github.com/obsproject/obs-studio/pull/9881 ✅
* [ ] https://github.com/obsproject/obs-studio/pull/9853 ❓
* [x] https://github.com/obsproject/obs-studio/pull/9879 ✅
* [x] https://github.com/obsproject/obs-studio/pull/9875 ✅

Potential PRs to include (depending on feedback & merge to master):
* [ ] https://github.com/obsproject/obs-studio/pull/9884 ❓
* [ ] https://github.com/obsproject/obs-studio/pull/9894 ❓
* [ ] https://github.com/obsproject/obs-studio/pull/9840 ❓
* [ ] https://github.com/obsproject/obs-studio/pull/9813 ❓
* [ ] https://github.com/obsproject/obs-browser/pull/429 ❓

**Comment by RytoEX** [comment]
Let's leave #9853 out and then merge what we have rather than worrying about adding more stuff to the PR. We can make additional cherry-pick PRs as needed.

**Comment by RytoEX** [comment]
Let's cherry-pick #9840 (bug fixing a feature new to 30) and leave the rest for later. We'll handle submodule updates separately.

**Pull request merged**
