### PR TITLE
libobs: Fix crash when calling missing files functions on a source with invalid context data

### PR DESCRIPTION
**Pull request by tt2468**
### Description

Checks that a source's context data is valid before attempting to run the actual missing files check.

### Motivation and Context

Crash bad!
I found this when building OBS on one machine and installing the deb package on another.

### How Has This Been Tested?

Tested on Ubuntu 20.04
Without fix: Crash in vlcs_missingfiles during OBS load
With fix: Issue is logged with a warning and OBS loads fully without crashing.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
I don't think this is the right place for a fix, as every source would theoretically have to implement the same thing. The missing files system should not be calling in with a null pointer.

I think a better fix is to change `obs_source_valid` to `data_valid` in `obs_source_get_missing_files` and related functions.

**Comment by tt2468** [comment]
> I don't think this is the right place for a fix, as every source would theoretically have to implement the same thing. The missing files system should not be calling in with a null pointer.
> 
> I think a better fix is to change `obs_source_valid` to `data_valid` in `obs_source_get_missing_files` and related functions.

Good idea. Updated!

**Comment by notr1ch** [comment]
Due to the implementation change, the PR / commit would also need a new title / description as this isn't related to the vlc source any more.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please update the commit message as well, per @notr1ch's request.

**Comment by tt2468** [comment]
@RytoEX @notr1ch Done. Apologies for the wait boys, had to be away from home for the day then I was running on almost no sleep, so it took some time for me to be back on my PC.

**Review by notr1ch — APPROVED** [review]

**Pull request merged**
