### PR TITLE
Show accurate path in Crash dialog

### PR DESCRIPTION
**Pull request by Bennik2000**
Closes obsproject/obs-studio#2290

### Description
The crash dialog displayed the following message even when OBS-Studio runs in portable mode:
> Woops, OBS has crashed!
> Would you like to copy the crash log to the clipboard?  (Crash logs will still be saved to the %appdata%\obs-studio\crashes directory)

Now the message contains the actual path of the crash dump:
> Woops, OBS has crashed!
> Would you like to copy the crash log to the clipboard?  (The crash log will still be saved to [path to crash directoy]\Crash 2020-03-16 22-43-23.txt)

Screenshot_3

### Motivation and Context
This closes issue #2290 
Under some circumstances the displayed path of the crash directory is wrong. Then it is hard to find the crash dump.

### How Has This Been Tested?
It was tested on a Windows machine. 
I forced OBS-Studio to crash by executing code which throws an exception.
Tested in the portable and not portable version.
This change should not affect other code in the repository

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Bennik2000** [comment]
Seems that my clang setup is not correct. I will fix it and reopen a PR.

**Comment by WizardCM** [comment]
As long as it's in the same branch, any changes you make to the branch will be reflected in the PR. No need to close/reopen. :)

**Comment by Fenrirthviti** [comment]
Just a ping that this need to be cleaned up before it can be considered for merging. Squash your commits and validate the clang-format is running properly.

**Comment by Bennik2000** [comment]
This was my first PR sorry for this and thanks for reminding. 
I did squash the commits and clang-format is running without errors.

**Pull request merged**
