### PR TITLE
UI: Improve source texts in en-US.ini

### PR DESCRIPTION
**Pull request by Vainock**
Add improved versions of a few source texts.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
You did not follow the appropriate contribution guidelines here, and the content of the PR is not the greatest. You're changing case on comment lines for no reason, `Consider using fewer video settings` doesn't make any sense, and the change to `NoNameEntered.Text` is entirely unnecessary as your proposed change is the exact same thing with different words.

The only change here I agree with is the `Basic.PropertiesWindow.Confirm`

At the least, you will need to update your commit title to include "UI:"

**Comment by Vainock** [comment]
I have updated the case of the comments only for consistency, not really important, I know. Have you problems with this?
I have chosen "The name is required." for _NoNameEntered.Text_ because it's chlarifys the message behind the text much more. You told that you only agree with _Basic.PropertiesWindow.Confirm_, and what is with the hours, minutes and seconds?

**Comment by SuslikV** [comment]
`Basic.PropertiesWindow.Confirm` syntax is broken.

These changes is not required, I think.

**Comment by Heufneutje** [comment]
Yeah the grammar on the confirm text is weird. "Do you want to save them now?" would probably be better.

**Comment by Vainock** [comment]
Yes, you are right. To write only "Want" seems not very correct.

**Pull request closed without merging**
