### PR TITLE
cmake: Detect environment variables for service configuration in CMake presets

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Allows OAuth configuration and other environment-based variables be detected and used in CMake presets.

### Motivation and Context
This makes the use of repository secrets set as environment variables in CI runs easier to work with, as they are directly adapted by the CMake preset and used in the build configuration.

### How Has This Been Tested?
Tested on separate fork to check for proper masking of repository secrets in GitHub Actions output.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
I assume that if you have manually set these in a user preset or via command line parameters it'll overwrite whatever is set in this base preset?

**Comment by PatTheMav** [comment]
> I assume that if you have manually set these in a user preset or via command line parameters it'll overwrite whatever is set in this base preset?

At least in my tests, that's what it does. Cache variables defined on the command line overrule any preset, followed by user presets and then default presets.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nit: oAUTH -> OAuth

**Comment by PatTheMav** [comment]
> Nit: oAUTH -> OAuth

Oh that one slipped through.

**Review by RytoEX — APPROVED** [review]
Seems fine.

**Pull request merged**
