### PR TITLE
UI: Disable downscale filter setting for same resolutions

### PR DESCRIPTION
**Pull request by gxalpha**
Disables the downscale filter dropdown menu when base and output
resolution are the same.

### Description

Disables the downscale filter dropdown menu in the settings when base and output
resolution are the same.

image
image

This only needs to be in `on_outputResolution_editTextChanged` and not in baseResolution, since changing the base resolution will always change the output resolution as well (or at least trigger the event).

### Motivation and Context

When base and output resolution are the same, the Downscale Filter doesn't get used.
This can lead to confusion amongst unexperienced user, wondering what the setting is for.
Suggestion from Discord.

### How Has This Been Tested?

macOS 12 beta 6, compiled and run.

As soon as one of the resolutions gets changed and they are the same, the menu gets disabled, and re-enabled once they are different.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I think disabling might confuse users - they'll ask "why can't I change it" rather than "why do I have to set one". What if we hid it altogether?

**Comment by Fenrirthviti** [comment]
Can the option text in the disabled drop down just be changed to say something like "Filter disabled with matching resolutions"?

**Comment by Warchamp7** [comment]
The dropdown shouldn't be hidden here because it is not contextual on the other setting, it's just not applicable in some cases.

Fine with also changing the text to something like above or "No downscaling"

**Comment by gxalpha** [comment]
> Can the option text in the disabled drop down just be changed to say something like "Filter disabled with matching resolutions"?

Would it still be disabled?

**Comment by Fenrirthviti** [comment]
Yes, I would expect it to switch to disabled state, and the text change to inform why it's disabled.

**Comment by mufunyo** [comment]
> Fine with also changing the text to something like above or "No downscaling"

I'd suggest the wording "Resolutions match".

**Comment by gxalpha** [comment]
I added the text:
image
What I do is add an element to the combolist which has the data of the selected element and that select said element. This means that when the data gets saved, it still is the same as it was before. When changing to different resolutions, it just reload the QComboList.

**Comment by gxalpha** [comment]
I reworked the logic a little to not rely on magic numbers and addressed the comparisons. Also put everything into one function to not have repetitive code.

Fyi, the magic numbers I relied originally on are from here:
https://github.com/obsproject/obs-studio/blob/4681e10fdf7b46acd93ed2cad1133ba2fb3ed6e3/UI/window-basic-settings.cpp#L1550-L1557
I left it how it is (only moving it into the if-clause), but it isn't particularly beautiful either.

**Pull request merged**
