### PR TITLE
README.rst: Use High DPI Discord Badge

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Replaces the official Discord Badge with one from shields.io, which is higher DIP compared to the official one.

### Motivation and Context

The current badge looks kind of out of place:

image

I think this looks way better: 

image

### How Has This Been Tested?

Looked at the README on GitHub
### Types of changes

- Documentation (a change to documentation pages) (I guess?)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I'm noticing the online count is consistently 150+ lower on the shields variant than the official counts on the embed & the existing badge.

**Comment by RytoEX** [comment]
Too late, but:
> Replaces the official Discord Badge with one from shields.io, which is
higher DIP compared to the official one.

DIP -> DPI

I'm a little uncomfortable using an unofficial shield for a variety of reasons, but I don't know if any of those reasons would have been sufficient to not merge this.

**Comment by Fenrirthviti** [comment]
I guess the question would be how the badge is being generated, and what data shields.io is storing or collecting, if anything, but I share the same discomfort I can't quite quantify or decide if it's worth worrying about.

**Comment by gxalpha** [comment]
> what data shields.io is storing or collecting

I mean, all of the data is public, and when a user clicks on the link, it doesn't get redirected via shields.io but directly from GitHub to Discord.
To add, they're open source on [GitHub](https://github.com/badges/shields).

Though I totally see why relying on some random provider can feel uncomfortable.
If it helps (and you feel like it's worth the effort (personally I don't think it is)), you could also [host the server yourself](https://github.com/badges/shields/blob/master/doc/self-hosting.md).

**Pull request merged**
