### PR TITLE
linux-v4l2: Add setting to change color range

### PR DESCRIPTION
**Pull request by DougTy**
Previously, the V4L2 video capture source on Linux was hard coded to use partial colour range only.
This commit adds a setting so the user can change that easily to "full" if needed.

The default is to use partial colour range, so this won't change anything unless the user explicitly goes in and selects full. I've tested this to work on Arch with an Elgato Cam Link.

I've also found a mantis issue for this:
https://obsproject.com/mantis/view.php?id=1180

Please let me know if I've done something wrong or if something needs revision.
Thanks.

### CODE REVIEW

**Comment by yerAWeeGit** [comment]
Yes, yes! I've been spending ages messing about with ffmpeg in order to capture full range and am having tremendous issue with the audio sync, but OBS doesn't have such issues and this is all that's stopping me from using it. The timing of this feels too perfect. If this goes through, when might it be available?

**Comment by kkartaltepe** [comment]
> If this goes through, when might it be available?

A better question for your package maintainer. If you are on arch you could just use the git package probably. Otherwise you would be better off compiling it in with this PR patched in.

A couple lines over the 80c limit it looks like.

**Comment by yerAWeeGit** [comment]
@kkartaltepe I don't need it immediately - just for a project later in a few months. What I'll do is wait it out for a bit and if this doesn't seem to be getting anywhere I'll look into compiling a build with this included.

**Comment by ChAoSWK** [comment]
works great for me

compiled in ubuntu 18.4 with all deps and now getting better, clearer image with my hdmi grabber

Thx for that patch

**Comment by yerAWeeGit** [comment]
@ChAoSWK How did you compile it? I tried following the instructions at https://github.com/obsproject/obs-studio/wiki/Install-Instructions#debian-based-build-directions but if I install it in `/usr` it complains about missing locales (it also screws up permissions, so my system won't boot until using a live CD to fix it) and if I install it in its own directory I get `error while loading shared libraries: libobs-frontend-api.so.0: cannot open shared object file: No such file or directory`.

**Comment by ChAoSWK** [comment]
@yerAWeeGit 

i am really not an expert, so i struggled many hours with that...


I made a clean install of ubuntu 18.04lts
apt-get update && apt-get upgrade

then dl the files with this patch included as zip
extracted it and
one after one apt-get all depending packages. these were about 20-30

I used only the portabe mode of this guide:

mkdir build && cd build
  cmake -DUNIX_STRUCTURE=0 \
          -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" ..
  make -j4 && make install

cmake told one after other the missing deps

be careful with the ffmpeg. I thought apt-get or manual compiling ffmpeg will work, but the trick is to dl / apt-get the parts told in the ( )

for example libavtools or other, i dont know it actually and have no pc at the time to verify.
but be sure you dont waste time with correct installing and getting ffmpeg - you need the single dependencies.

After cmake tells that averyting is fine (repeat the cmake step everytime and get the deps) you can "make" it.

After successfully make  and make install you get a bin/64 directory and inside youll find the executable obs

for me it works perfectly

**Pull request merged**
