### PR TITLE
UI: Correct custom property implementation

### PR DESCRIPTION
**Pull request by SuslikV**
1. Fixes an issue when custom theme has no info about the preview
background color, the preview's display background may be rendered
with random color.
2. Adds Projector display background color customization instead of
hardcoded black. Now if source larger than the display's height or
width, the remaining space for the Fullscreen Projector filled with
the preview's display background color from the theme.

The Projector's background, if it defer from the Display's background
color may be specified via:
```
OBSProjector {
qproperty-displayBackgroundColor: ... ;
}
```
record that is placed after the `OBSQTDisplay` section in the theme
file (qss).

3. The usage of the `* [themeID="..."]` in themes was not versatile - 
this is selector _for any child object that has `themeID` property_.
In obs, all Projectors (see https://github.com/obsproject/obs-studio/commit/ea851b13512ca5420b2ce46aff3fa01cbc56a869 ) has no parent and thus the property
never applies to projectors despite it derived from the display class.

More versatile usage is
`*[themeID="..."]` (no space specified)
like _for any object that has `themeID` property_.

This also fixes it.

4. Adding one more property dynamically ('themeID') to the OBSQTDisplay
class not required because another property already set in the header
file (`displayBackgroundColor`). Unneeded overheat removed.

### CODE REVIEW

**Comment by SuslikV** [comment]
Hope it's final one...

**Comment by dodgepong** [comment]
If you need to update a pull request, you can just squash and force-push, no reason to close and re-submit the PR.

**Comment by SuslikV** [comment]
I'm using web form...

**Comment by dodgepong** [comment]
I see. Well, if you get the chance, I highly recommend and strongly suggest you learn how to use git on your local machine at some point to make use of all of its functionality, not to mention allowing you to use your code editor of choice.

**Comment by SuslikV** [comment]
It is required to install all development software, I see no sense to install only git. And my PC slow as hell with all this development stuff (even if just installed, I think it is because of number of small files). Sorry, if it makes too many letters to your mail boxes.

**Comment by dodgepong** [comment]
Does this mean you're not testing your changes on a local build before pushing?

**Comment by SuslikV** [comment]
Not always.

**Pull request merged**
