### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by marcobiedermann**
Optimize images without losing any quality using [ImageOptim](https://imageoptim.com/)

image

I optimize images automatically, I highly recommend using a service like [ImgBot](https://github.com/apps/imgbot)

### CODE REVIEW

**Comment by jp9000** [comment]
I'm sorry, but I really am not that concerned with this.  Thank you however.

**Comment by marcobiedermann** [comment]
@jp9000 
I know that is might have a lower impact but in my opinion having a more optimized version of what you have before without any quality loss is always a win.
Of course you can be very opinionated about that.
Your call

**Comment by w136111526** [comment]
Why can't I load it when I'm adding an image source?

**Comment by Fenrirthviti** [comment]
@w136111526 This is not an appropriate place to ask for support, Please use the forums or Discord instead.

**Pull request closed without merging**
