### PR TITLE
libobs: Fix thread-safe issue for audio monitor

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

Modify tips:
1. _obs_source_set_monitoring_type_ may be called from different threads， such as UI thread and _WASAPISource::ReconnectThread_;

2. _audio_monitor::playback_mutex_ lost destroy logic;

3. it is better to request "_playback_mutex_" in _audio_monitor_free_.

### Motivation and Context

for thread-safe

### How Has This Been Tested?

Switch audio monitor (on & off) from UI frequently.
At the same time, disconnect and connect audio device frequently to make sure WASAPISource::ReconnectThread can be called.

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Could you explain why you closed this?

**Comment by walker-WSH** [comment]
> Could you explain why you closed this?

In the past，set.monitor.type will be called from connect thread of wasapi，which is out of UI thread. 

now that code has been removed，so there no longer exist mult-thread issue now

**Comment by walker-WSH** [comment]
> Could you explain why you closed this?

In the past，set.monitor.type will be called from connect thread of wasapi，which is out of UI thread. 

now that code has been removed，so there no longer exist mult-thread issue now

**Comment by walker-WSH** [comment]
Oh，my commit for audio_monitor_free seems useful.

maybe it should be retained

**Pull request closed without merging**
