### PR TITLE
UI: Add settings reset button

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This adds a reset button in the settings dialog to reset the current tab to its default settings.

Screenshot from 2023-02-16 15-13-55

### Motivation and Context
Currently there is no way to reset the settings to defaults.

### How Has This Been Tested?
Clicked the reset button to make sure the settings were set to the defaults.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
For clarification here, when you say "the settings" you are referring specifically to general settings, correct?

I'm not sure putting the reset button in the larger dialog is correct here, unless it's expected to work in every tab in settings. Many of the other tabs are already controlled by scene collections and profiles, so there might be a small conflict/overlap here in user expectations.

**Comment by cg2121** [comment]
Works for whatever the current tab is.

**Comment by prgmitchell** [comment]
Tested with a few different collections and all works as expected. People often ask how to reset their settings in the support channels and the only current solution is to create a new profile. This of course isn't ideal when someone only wants to reset one part of their settings. I can see what Fenrir is saying considering the "Apply" button in the same section of the UI would apply all settings, not just the settings on that tab. I personally don't see this as an issue for the user experience as the confirmation dialog makes it clear what is happening and what exactly is being reset.

**Comment by Fenrirthviti** [comment]
Screenshots of said dialog in the PR description would be useful then, as I didn't even know there was a confirmation based on the information provided.

**Comment by WizardCM** [comment]
I'm personally not sold on this feature. While the UI provides no way to reset settings, it can be done by deleting the `global.ini` or creating a new Profile (depending on the tab). Additionally, we don't often have users request the ability to reset to default.

**Comment by WizardCM** [comment]
Thinking about this further, personally the only areas that would benefit strongly from a Reset button are the Advanced "Video" and "Recording" sections. Users experiment with colour settings and filename formatting, and have no clear way to revert to something functional. Every other setting has much clearer default values, either a "Default" item in the dropdown or a blank field as default.

**Comment by GeorgesStavracas** [comment]
As per today's discussion, Settings needs a bigger reorganization and by the time it happens, this PR will probably not apply. Also, this direction for Defaults is not consensus. Let's discuss how we handle resetting defaults further in the context of updating the Settings dialog.

**Pull request closed without merging**
