### PR TITLE
Service integration restream chat

### PR DESCRIPTION
**Pull request by SoftwareArchitector**

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Why have you opened a second PR? Is there something wrong with #1662?

**Comment by SoftwareArchitector** [comment]
No, the second PR contains additional functions (firtst PR is only
authorization for restream service, second - restream chat after
authorization)

пн, 18 февр. 2019 г., 17:29 Joel Bethke notifications@github.com:

**Comment by dodgepong** [comment]
Okay, but you didn't need to open a second PR to add a second commit. If you look at the Commits tab, you'll see this PR includes both 6b73307540aca04907217b5b475f08bddba10d57 and c660e374818ff989e9d0563bb16478c71c5fb6ee, whereas #1662 just has 6b73307540aca04907217b5b475f08bddba10d57. The better thing to do would have been to update the original PR with the new commit, but I suppose now that this PR exists, we can close #1662 in favor of this one.

**Comment by SoftwareArchitector** [comment]
Ok, I got it, thank you


пн, 18 февр. 2019 г., 17:42 Ben Torell notifications@github.com:

**Comment by jp9000** [comment]
This was closed unintentionally

**Comment by jp9000** [comment]
I'm not sure how/why this was closed but please re-open.

**Comment by jp9000** [comment]
Ah wait, I see.  This was closed because I just deleted the service integration branch, because I had merged the service integration branch.

Could you please change these via our master branch and make a new pull request?

**Comment by SoftwareArchitector** [comment]
Ok, I will do.

ср, 6 мар. 2019 г. в 02:22, Jim <notifications@github.com>:

**Pull request closed without merging**
