### PR TITLE
obs-amf: Enables a pipeline for texture-based encoding with AMF.

### PR DESCRIPTION
**Pull request by OvchinnikovDmitrii**
### Description
Adds h264 and hevc texture-based encoders that work via AMF. They are available for selection in advanced settings and does not affect existing AMF encoders.

### Motivation and Context
To increase the encoding speed.

### How Has This Been Tested?
Hardware: Radeon RX Vega 64 | AMD
Operating System: Windows  ver. 1809
I recorded the video using new encoders and different settings, and checked the result

### Types of changes
New feature
Performance enhancement

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
This should probably be submitted as a PR to https://github.com/obsproject/obs-amd-encoder rather than adding a second copy of AMF.

**Comment by Xaymar** [comment]
This seems to be missing a software fallback for encoding, so it would only work on single-GPU configurations.

**Comment by dodgepong** [comment]
Any chance to can submit this as a PR to the submodule instead? It's impossible to tell what's actually changed about the plugin by looking at this diff.

**Comment by jp9000** [comment]
I think there's a misunderstanding of what's going on here. The duplicated code appears to be the AMF library. I think this is a completely separate plugin otherwise. So you can't just modify the existing plugin. I think there's also confusion because there's some similar code that might've been partly copied from the plugin, which also cause confusion. I'll have to look it over it to see what's going on here, sans the AMF library.

**Comment by OvchinnikovDmitrii** [comment]
> This seems to be missing a software fallback for encoding, so it would only work on single-GPU configurations.

This plug-in selects the same GPU as the one selected for other OBS workload – so frames could stay in video memory. It will work in multi-GPU configuration if the selected GPU is AMD’s.
Not sure if rerouting to SW ffmpeg encoder does make sense here – parameters could not match.
Probably it would be beneficial to add support for CPU memory input as an option. I could do it with a separate patch.

**Comment by OvchinnikovDmitrii** [comment]
> I think there's a misunderstanding of what's going on here. The duplicated code appears to be the AMF library. I think this is a completely separate plugin otherwise. So you can't just modify the existing plugin. I think there's also confusion because there's some similar code that might've been partly copied from the plugin, which also caused confusion. I'll have to look it over it to see what's going on here, sans the AMF library.

Yes, you're right. Thank you!

**Comment by WizardCM** [comment]
Apparently superseded by #4538

**Pull request closed without merging**
