### PR TITLE
UI: Fix capitalization of 'OBS' and 'RTMP'

### PR DESCRIPTION
**Pull request by Vainock**
### Description
"obs" -> "OBS"
"rtmp" -> "RTMP"

### Motivation and Context
Consistency and correctness is good!

### How Has This Been Tested?
/

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
If I recall correctly, these are both describing specific types:
* rtmp_output
* obs_video_info

I think the messages they were based on are similar, though those might have only been logged and not translated. It may be the case that we'd want to correct these for use in the UI, though I originally opted not to correct them. Will defer to @Warchamp7 .

**Comment by Warchamp7** [comment]
If we're presenting this error to the user, it should be presented appropriately with correct capitalization.

**Comment by RytoEX** [comment]
> If we're presenting this error to the user, it should be presented appropriately with correct capitalization.

Technically, the "correct capitalization" is:
* [rtmp_output](https://github.com/obsproject/obs-studio/blob/9d88b632ae0ad720093be22eecac37f8d1d78843/UI/multitrack-video-output.cpp#L156)
* [obs_video_info](https://github.com/obsproject/obs-studio/blob/9d88b632ae0ad720093be22eecac37f8d1d78843/UI/multitrack-video-output.cpp#L293-L296)

Because they are object/variable types. Otherwise, if we want to assert that "descriptive text should not be technical/literal", then yes, this is probably better for user-facing dialog/UI text.

**Review by RytoEX — APPROVED** [review]
Seems fine.

**Pull request merged**
