### PR TITLE
rtmp-services: Update Steam

### PR DESCRIPTION
**Pull request by Linnun**
### Description

Steam now automatically selects the closest available server
Also refer to: https://steamcommunity.com/broadcast/upload

### Motivation and Context

Steam now automatically selects the closest available server. There is no more need for the region selection

### How Has This Been Tested?

Ran a couple successful test broadcasts on Windows 10

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please update the commit title to reflect our commit guidelines, per the contributing doc.

**Comment by Linnun** [comment]
> Please update the commit title to reflect our commit guidelines, per the contributing doc.

I tried to do that, but I think it created some additional commits. If you know how to fix this without re-forking and re-building this, please let me know.

**Comment by Vainock** [comment]
You will have to squash the commits to one single commit.

**Comment by RytoEX** [comment]
> ### Description
> 
> Steam now automatically selects the closest available server
> Also refer to: https://steamcommunity.com/broadcast/upload

Is there official documentation somewhere from Steam/Valve about this change?  Or is that page the official documentation?

When I load that page, I just see this error.
> k_EResultNoMatch (42)
image

If I click "Create RTMP Token", I get this error:
> Settings update failed! - "Access is denied (15)"
image

----

As for the extra commits, using `git rebase` and squashing the extra commits is what you would do, as Vainock said above.

Something like this should work:
```
$ git rebase -i '51f3cd9^'
```

Your default text editor will open.  Mark the extra commits as "squash"/"s" or "fixup"/"f".  Save and close the text editor.

Then do this:
```
$ git push -f origin
```

**Comment by Linnun** [comment]
Thank you, I was able to rebase it, and think it is correctly squashed into one commit now. You learn somethin new everyday :) One note for possible future searchers though: `git rebase -i '51f3cd9^'` did not work for me and returned some fatal error. I ended up using `git rebase -i head~2` then, which worked fine.


As for your Steam errors: I think normal users can not use external streaming tools to broadcast their gameplay to stream. AFAIK this feature is only meant for partnered developers to broadcast their developer streams to the store page of their games. So judging from your error messages I guess you might not have an account with those privileges.

There also is a documentation for this broadcasting feature for developers, but it hasn't been updated to reflect this 'universal' rtmp server yet. Previously Steam would guess a good rtmp server for you based on your IP address. Since this documentation is very easy to find with Google, I guess I can share the link to it: https://partner.steamgames.com/doc/store/broadcast/setting_up

**Comment by Gol-D-Ace** [comment]
From what I remember you need to be part of the steam broadcasting group.

I'm not a developer on steam and can start broadcasts.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please format the commit message appropriately and use the "rtmp-services" prefix.  See the [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidlines) from our [CONTRIBUTING document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) for more details.

Please increment the version number in `plugins/rtmp-services/data/package.json`.

For examples on modifying rtmp-services, please check out [successfully merged PRs for rtmp-services](https://github.com/obsproject/obs-studio/pulls?q=is%3Apr+is%3Amerged+rtmp-services).  Please feel free to ask questions if you have any.

**Comment by Gol-D-Ace** [comment]
Looks fine to me now.

**Pull request merged**
