### PR TITLE
plugins: Add oss-audio input support

### PR DESCRIPTION
**Pull request by khng300**
### Description

This PR introduces oss-audio as a audio source plugin.

### Motivation and Context

This plugin enables audio capturing support on platforms which uses OSS as sound interface such as FreeBSD, without the use of any kind of ALSA or PA shims.

### How Has This Been Tested?

I tested the changes on my desktop with a jack cable connected to a laptop.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please squash your commits and update the commit title so that `Add` is capitalized.

**Comment by khng300** [comment]
> Please squash your commits and update the commit title so that `Add` is capitalized.

Done

**Comment by emaste** [comment]
This change only affects FreeBSD (and DragonFly BSD); there's no support in OBS for other OSS-using operating systems and I suspect that will remain the case. I've tested it successfully on FreeBSD.

**Comment by khng300** [comment]
Now it tries to support the channels and speed provided by the opened audio engine (It's a virtual device on FreeBSD normally) instead of some hard-coded values.

**Comment by dch** [comment]
@jp9000 this is a fantastic contribution - is there any chance of a new release / git tag soon, so we can get this new code into the FreeBSD ports tree? I've streamed successfully today and it's *great*.

**Comment by khng300** [comment]
Currently I think it is okay to pull the changes as individual patches to
the ports :)

**Comment by dch** [comment]
done, https://reviews.freebsd.org/D25097 waiting on test builds to finish

**Pull request merged**
