### PR TITLE
Add "Area" scale filter

### PR DESCRIPTION
**Pull request by jpark37**
This new scale filter computes pixels by weighing the coverage area of
source pixels over the target pixel. This algorithm works well for both
upsampling and downsampling, but was mainly designed to upscale
high-quality low-resolution sources like RGB/HDMI retro consoles. I've
heard of people using odd workarounds like scaling up to very high
resolutions before scaling back down to preserve pixel shartpness. This
algorithm directly addresses this use-case in a much more direct
fashion.

The Area scale filter does a better job of preserving the thickness of
thin features than the Point filter.

The Area scale filter does not look at source pixels that lie outside
of the target pixel, leading to a much sharper image than Bilinear,
Bicubic, and Lanczos filters.

Unlike the other filters, there is additional code to weigh pixels in a
perceptual space (CIELUV), which may provide better results in some
circumstances.

libobs: Add GPU effect, and wire up scene serialization.

obs-filters: Add Area as an option for scale_filter.

UI: Add Area as an option for both scene items, and canvas downscaling.

### CODE REVIEW

**Comment by jpark37** [comment]
#1713 impacts how the color interpolation for this algorithm is implemented.

**Comment by jpark37** [comment]
These changes are no longer dependent on #1713, and can go in without.

This is going to blend in gamma space like all the other scale filters. They can all be adjusted to linear at once later, possibly by #1713. There was discussion on that PR were I felt CIELUV gave better-looking results, but it was definitely not producing better results on several provided test images, so I am on the linear train now.

**Comment by SuslikV** [comment]
About consoles:
https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms

Area filter has very limited usage by the way.

**Comment by jpark37** [comment]
Well, everyone's taste is different. I don't like the artificially smooth look that most pixel-art enhancement algorithms provide.

**Comment by SuslikV** [comment]
"Area" here named by the http://entropymine.com/imageworsener/pixelmixing/ algorithm? Same to FFmpeg and others?

**Comment by jpark37** [comment]
Yes, it looks like the same algorithm. I came up with it on my own, but couldn't find a standard name when I tried to searched for it. I thought it was going to get trashed from the URL, but it seems like a pretty fair take.

Skimming the code, FFmpeg appears to switch over to bilinear for their area algorithm when upscaling, but in OBS, Area and Bilinear give very different results. I have not looked at their downsampling algorithm, but I would suspect it's the same from the name.

**Comment by SuslikV** [comment]
Here, I was asking just because I'm going to translate the option (localization). Not a big deal about the FFmpeg for my case.

I mentioned some strange behavior of the implementation here:
https://github.com/obsproject/obs-studio/commit/5c16a96770619ab7726e3239e4de67a286a797a3#commitcomment-32746947

**Comment by jpark37** [comment]
Sorry, I should have tested the downscale path better. Made a PR to remove that option here: #1750

**Comment by kkartaltepe** [comment]
For reference here is the comparison image from the forum thread where this was proposed.
https://i.imgur.com/XVk6IjP.png

and in case it dies the forum post: https://obsproject.com/forum/threads/new-scale-filtering-mode-area-averaging.77590/

**Pull request merged**
