### PR TITLE
Revert "cmake: Align Product Name and Bundle Name on macOS"

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

This reverts commit 9f66c23825e41807c56f3a865d1c1462fa7ff73b.

This commit caused a crash in CEF on startup for many users. Let's just revert it asap for now and worry about the minor problem it was solving another time. Although according to https://github.com/obsproject/obs-studio/issues/9871#issuecomment-1815205387%3E that original issue may have been fixed in macOS anyways so I'm not worried about it.

Incidentally it also causes a problem I was having (but couldn't debug because of a lack of time) where the build folder needed cleaning before each rebuild or otherwise code signing was failing.

### Motivation and Context

People report this crash on 30.0.1 and I don't like crashes.

### How Has This Been Tested?

In my setup, which was also effected by this crash (which I only noticed a few days ago), it no longer crashes.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
If this is a temporary change, maybe we should only push it to the release branch and do a proper fix on masteR?

**Comment by gxalpha** [comment]
I think pushing only to release branches is a bad habit that we shouldn’t do.
Also I don’t necessarily consider the revert to be temporary, as per https://github.com/obsproject/obs-studio/issues/9871#issuecomment-1815205387 the underlying problem may have been fixed in macOS 14.2 anyways so it should go away by itself.

**Comment by PatTheMav** [comment]
What is the reason that this could fix the crash? I don't see any reason (yet) how this would influence anything regarding CEF.

Also the change was logically correct because if the application is named "OBS Studio" the bundle needs to be named the change and us renaming the bundle to just "OBS.app" is actually wrong.

**Comment by PatTheMav** [comment]
Just thinking about it, I understand what the issue is - the helper apps need to be named "OBS Studio Helper" instead of "OBS Helper" obviously. Stupid oversight.. 🤣

**Review by PatTheMav — APPROVED** [review]
Now that I understand the root cause I'm fine with reverting this - app bundle name and file bundle name are "OBS" and we should assume that this is the name used in the menu bar.

_If_ it displays "OBS Studio" that would be the error in macOS, but the expected result is for it to be called just "OBS".

**Pull request merged**
