### PR TITLE
rmtp-services: Update odysee.com

### PR DESCRIPTION
**Pull request by iamflorencejay**
### Description

I forgot that it is on beta, so I just update the header for this one.

### Motivation and Context

My motivation for this is of course, the growing family of LBRY and odysee, as well as the devs.

### How Has This Been Tested?

I've tested it using OBS on ubuntu 20.04

### Types of changes

Changes for just a title. from Odysee to Odysee (Beta)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Like it was said in your previous #4617 
>It seems this was merged by accident. At this time, we require that additions to rtmp-services be made by official representatives from the service being added. As such, this merge has been reverted. Thank you for understanding

You should at least give a  prove that representatives of Odysee approved this PR.

**Comment by tytan652** [comment]
Also your commits are not properly formatted and squashed where appropriate

**Comment by iamflorencejay** [comment]
@tytan652 my bad.

**Comment by iamflorencejay** [comment]
@tytan652 now it is updated

**Comment by tytan652** [comment]
You seem to have forgot to add `--force` to your push command.

**Comment by iamflorencejay** [comment]
@tytan652 im new to git though :<

**Comment by tytan652** [comment]
[How to use git push force the right way](https://www.datree.io/resources/git-push-force)

[A Beginner’s Guide to Squashing Commits with Git Rebase](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec)

**Comment by iamflorencejay** [comment]
@tytan652 done

**Comment by derrod** [comment]
As per #4617 we require new services to be submitted by representatives of a service, since that doesn't appear to be the case I'm closing this.

**Pull request closed without merging**
