### PR TITLE
obs-outputs: Update librtmp with upstream patches

### PR DESCRIPTION
**Pull request by jumoog**
from git://git.ffmpeg.org/rtmpdump but adopted to obs code formating

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please check the [contribution](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) guidelines, your commit titles are incorrect and need to follow the project standards.

Your previous PRs have followed the correct format, for reference: https://github.com/jumoog/obs-studio/commit/cc69ec16ec77d91676fdbec13329d51a678958bb

**Comment by Fenrirthviti** [comment]
Also, can you please explain the motivation for this change? From the changes, it seems like these would only affect a code path where OBS is receiving a stream, which we currently don't use librtmp for.

**Comment by jumoog** [comment]
even we dont use it its a good idea to merge upstream security fixes

**Comment by Fenrirthviti** [comment]
Can you please explain what this is fixing? I don't completely disagree, but if this code section is unused and doesn't affect us, there's no point in merging it.

**Pull request closed without merging**
