### PR TITLE
libobs,UI: Support HLG nominal peak level

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Previously hard-coded for 1000 nits.

HLG output uses MovieLabs-recommended procedure.

- If peak luminance is greater than 1000, use maxRGB EETF to 1000.
- Otherwise, don't tonemap.
- Then use normal HLG conversion procedure with gamma 1.2 (1000 nits).

### Motivation and Context
We need the nominal peak level for accurate HLG conversions.

### How Has This Been Tested?
Tested round-trip for 400/1000/10000 nit levels, recording and playback. Checked value sanity in RenderDoc shader debugger.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
Draft until I sort out he peak normalization step.

**Comment by jpark37** [comment]
Found the other hard-coded 1000.f spots.

**Comment by AMejiaDolby** [comment]
@jpark37 I'm very excited to see HDR support coming to OBS.  I'd like to reach out to you about your work to offer you resources if you would like some help.  Email is in in my profile.

**Comment by Ollyhun** [comment]
Hi everyone like my photos myself #6472

**Pull request merged**
