### PR TITLE
UI: Add undo/redo for "Add existing source"

### LINKED ISSUE #5091: Add existing source lacks undo/redo
### Operating System Info

Other

### Other OS

macOS 12.0

### OBS Studio Version

Git

### OBS Studio Version (Other)

also 27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/-i4NquFkCmrfFNpa

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Undo should remove a source that has been added via "Add Existing"

### Current Behavior

When adding an existing source, no undo/redo gets created.
If any other action was taken before that and undo gets triggered, that action will get undone, the source stays where it is.

### Steps to Reproduce

1. Add existing source
2. No undo available

### Anything else we should know?

It's completely missing in the code, see:
https://github.com/obsproject/obs-studio/blob/a9352985c797a3a0fe75ae8ba89013f30dc4b5ab/UI/window-basic-source-select.cpp#L225-L230
On "Add New", there is the appropriate action created and added to the stack.
https://github.com/obsproject/obs-studio/blob/a9352985c797a3a0fe75ae8ba89013f30dc4b5ab/UI/window-basic-source-select.cpp#L247-L259
I linked the important bits of the code here to save whoever wants to fix this a minute.

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Adds an undo/redo action for the "Add existing source", which previously
was missing.

Overall mimics the behaviour of the undo/redo, including the scene-switching to the scene that is affected when undo/redo-ing).

### Motivation and Context

Fixes #5091 

### How Has This Been Tested?

macOS 12 beta 5, compiled and run

Undo/Redo works, on redo the source reappears on the correct scene.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Warchamp7** [comment]
Discussed on Discord was the idea that this should not switch scenes unless the user is in studio mode

**Comment by gxalpha** [comment]
This would require some deeper change of how sources are created.
Also I saw WizardCM disagree with that opinion on Discord, and would like to at least have settled on how this should behave before.

Basically, I'd argue this is out of scope of this PR.

**Comment by jp9000** [comment]
I'm confused, why would that be out of the scope for the PR? Because it's directly in the PR

**Comment by gxalpha** [comment]
Warchamps comment didn't just address this PR, but also the current behaviour of undo/redo of "Add New" (about which the discussion on Discord was. https://discord.com/channels/348973006581923840/374636084883095554/877550288553254922).
I do know that some of what this PR does would get changed, but with this one my idea was to keep it consistent with Add New. Otherwise, Add New would change the scene, and Add Existing wouldn't, which I think would be confusing.

If you want me to, I could do everything here, but that would basically be a different PR from what it is now.

**Comment by Warchamp7** [comment]
Undo/redo of Add New switching scenes should be addressed separately but my understanding of the code paths here means that  undo/redo of Add existing would be within the code and scope of this PR adding the functionality

**Comment by gxalpha** [comment]
(Discussed on Discord)
image

**Pull request merged**
