### PR TITLE
deps/media-playback and win-dshow: Prioritize CUDA HW decoder (for 8K playback)

### PR DESCRIPTION
**Pull request by moocowsheep**
### Description

8K60 files would not play back at full rate in media source on Windows on Nvidia cards, due to D3D11VA and DXVA2 not being able to decode fast enough. This pull request puts CUDA decoder at highest priority, to enable high resolution / frame rate file decode at full speed.

### Motivation and Context

I have only been able to play back 8K HEVC video files on MacOS at full speed...this brings the Windows version at feature parity.

### How Has This Been Tested?

I tested the media source with HW Decode on 2 Windows machines, one with an Nvidia L4 and one with an Nvidia ADA 6000. This does not appear to affect any other code.

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Could you provide some profiling results of using CUDA decode versus d3d11 with your 8k60 video?

**Comment by tt2468** [comment]
What about d3d11 is slower than CUDA, to where using CUDA is the difference between being able to play 8k60 or not? Have you investigated the decode and GPU download stages to determine where the actual performance degradation is occuring?

**Comment by notr1ch** [comment]
CUDA tends to use parts of the GPU that are also used by by other things like games so the performance impact needs extensive testing. I think this should be scoped so that only affected videos use CUDA, or as an advanced option only.

**Comment by moocowsheep** [comment]
Doing investigations and then going to resubmit properly. The CUDA decoder uses the nvdec, (I don't believe it uses the CUDA cores, it's a misnomer) but I'll get more info on the actual performance implications.

**Comment by Fenrirthviti** [comment]
In the future, you can just force push your branch and the PR will update so you don't have to create a new one.

This is one reason why we request PRs not from the master branch of a fork :)

**Comment by moocowsheep** [comment]
Duly noted :) I'm a bit of a GitHub novice! Fixing all for the next one

**Comment by naieto** [comment]
> Doing investigations and then going to resubmit properly. The CUDA decoder uses the nvdec, (I don't believe it uses the CUDA cores, it's a misnomer) but I'll get more info on the actual performance implications.
That's why not all NVIDIA cards with CUDA cores can decode h265. Although some ffmpeg filters such as scaling, overlay, etc., use CUDA.

**Pull request closed without merging**
