### PR TITLE
CI: Bump Flatpak actions to v6

### PR DESCRIPTION
**Pull request by kbdharun**
### Description

- Bumped the version of `flatpak/flatpak-github-actions/flat-manager` from `v5` to [`v6`](https://github.com/flatpak/flatpak-github-actions/releases/tag/v6)
- Bumped the version of `flatpak/flatpak-github-actions/flatpak-builder` from a specific commit to [`v6`](https://github.com/flatpak/flatpak-github-actions/releases/tag/v6) as requested below.

### Motivation and Context

Improved Flatpak compatibility, caching & restore support, and more verbosity come with this version.

### How Has This Been Tested?

This PR hasn't been tested, but the action runs can be checked below or on the Actions tab.

### Types of changes

Tweak (non-breaking change to improve existing functionality)
 Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Note; That bumping the version is not a priority since we don't need verbose mode.

And we already  bumped to a commit hash for new caching feature.

**Comment by kbdharun** [comment]
> And we already bumped to a commit hash for new caching feature.

Great, Thanks for the info.

**Review by tytan652 — CHANGES_REQUESTED** [review]
- The prefix of the commit name must be `CI:`.
- Don't only bump flat-manager, bump flatpak-builder to v6 too.

PS: Just in case, don't open another PR, just force push your branch.

**Comment by kbdharun** [comment]
> * The prefix of the commit name must be `CI:`.
> * Don't only bump flat-manager, bump flatpak-builder to v6 too.
> 
> PS: Just in case, don't open another PR, just force push your branch.

I will do it in a couple of minutes, Thanks for the review.

**Comment by RytoEX** [comment]
The commits between our pinned commit and the current v6 commit include updates to `@actions/core` that we will probably want on CI sooner rather than later. Will revisit this early next week.

**Pull request merged**
