### PR TITLE
UI: Add new theme Yami

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
This is a new theme designed with the intent of replacing the current default dark theme.

Feedback and issues with the theme itself are welcome below. Discussion of this theme actually replacing Dark as the default should take place on the RFC

obs64_2020-04-22_11-13-26

obs64_2020-04-22_11-13-33

obs64_2020-04-22_11-19-52

obs64_2020-04-22_11-13-42

obs64_2020-04-22_11-19-14

obs64_2020-04-22_11-14-29

obs64_2020-04-22_11-18-13

obs64_2020-04-22_11-18-44

### Motivation and Context
Compared to the default Dark theme this new theme has a larger font size, more space around elements to let them breathe, and a better color heirarchy to improve both readability and usability.

The Dark theme, while very compact, is also incredibly cramped and overwhelming visually, especially for newer users.

### How Has This Been Tested?
Checked all windows and dialogs of OBS

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
Overall, I think it looks nice!

My biggest concern is the reduced density of the Sources and Scenes panels. We already have people struggling to organize those panels, and making them less dense would serve to exaggerate that problem.

**Comment by matoi974** [comment]
Everything is too spaced-out and large for my taste. Even navigating Settings > General involves excessive amounts of scrolling. Maybe a separate "High-DPI" version is in order, as a temporary workaround for the current DPI scaling issues?

Untitled

**Comment by dodgepong** [comment]
A small philosophical note: I wouldn't call the Dark theme "cramped" -- I might call it "dense", or more favorably, "compact". "Cramped" suggests there's not enough space to show everything you want to show, and I feel like this proposed theme is more likely to suffer from that than a compact theme like Dark. That said, I understand that being more spread out might also make the program seem more approachable.

What I'd really like to see is some more widespread opinion from lay users about what they prefer in a UI. And maybe it might be worthwhile to have both a "Comfortable" and a "Compact" version of this theme, because in terms of colors it seems pretty neat.

**Comment by Warchamp7** [comment]
> A small philosophical note: I wouldn't call the Dark theme "cramped" -- I might call it "dense", or more favorably, "compact". "Cramped" suggests there's not enough space to show everything you want to show, and I feel like this proposed theme is more likely to suffer from that than a compact theme like Dark. That said, I understand that being more spread out might also make the program seem more approachable.
> 
> What I'd really like to see is some more widespread opinion from lay users about what they prefer in a UI. And maybe it might be worthwhile to have both a "Comfortable" and a "Compact" version of this theme, because in terms of colors it seems pretty neat.

I do suggest the renaming of Dark to "Compact" in my [RFC for changing the default theme](https://github.com/obsproject/rfcs/pull/23)

I would not be opposed to also recoloring Dark to match this if we decided to go that route, to have two different "size" options of this scheme



> Everything is too spaced-out and large for my taste. Even navigating Settings > General involves excessive amounts of scrolling. Maybe a separate "High-DPI" version is in order, as a temporary workaround for the current DPI scaling issues?
> 
> Untitled

I think this is a perspective thing. I would argue that on Dark theme things are not spaced out enough, rather than this theme being too spaced out.

I also think that power users (See: people savvy enough to browse this PR) are likely to trend towards preferring a compact and dense UI. This theme is targeted towards the average user, and improving the UX for them. Having elements clustered as close together as they are in Dark is poor design imo

**Comment by Codex-** [comment]
Also it's worth noting in @matoi974 s, the checkbox aren't rendering and content is being cut on the right.

**Comment by Warchamp7** [comment]
> Also it's worth noting in @matoi974 s screenshot, the checkbox aren't rendering and content is being cut on the right.

The checkboxes have since been fixed

**Comment by mufunyo** [comment]
Just to add my two cents: I dislike tinted UIs because in a dark environment it causes chromatic adaptation which causes you to see colours incorrectly (in the case of a blue UI like this, correctly white balanced colours will seem tinted too warm because your eyes are adapted to the blue tint). Davinci Resolve does this too, but has an option in the settings to use a neutral grey instead for the aforementioned reason.

**Comment by Warchamp7** [comment]
> Just to add my two cents: I dislike tinted UIs because in a dark environment it causes chromatic adaptation which causes you to see colours incorrectly (in the case of a blue UI like this, correctly white balanced colours will seem tinted too warm because your eyes are adapted to the blue tint). Davinci Resolve does this too, but has an option in the settings to use a neutral grey instead for the aforementioned reason.

I think this is a rather minor criticism in the grand scheme of things, but I would say a point in favour of keeping at least one greyscale theme around for sure

**Comment by unknowndomain** [comment]
Both myself and @mufunyo have come up with the same point independently here and in the RFC about this issue and it feels like we've been dismissed as minor issue which shouldn't be addressed.

Perhaps if we flip this on it's head, what is the reason to change the default theme colour?

**Comment by Warchamp7** [comment]
> Both myself and @mufunyo have come up with the same point independently here and in the RFC about this issue and it feels like we've been dismissed as minor issue which shouldn't be addressed.
> 
> Perhaps if we flip this on it's head, what is the reason to change the default theme colour?

This is why I have a PR for the theme itself, and the RFC for changing the default.I think it's a good concern for the default theme, but not for this theme specifically. 

Plainly, I think it's generally good design to have a bit of color in greys, but Yami may go too far. Acri is rather greyscale but still has a tiny bit of blue in there.

I'm sorry if it seemed dismissive over on the RFC; I think it's a very good point, I'm just not sure if it's a **decisive** one against the default being tinted.

Perhaps Yami can be this blue scheme, and we can simply update Dark to have the same tweaks but be grayscale and without the padding increases. That's a discussion for the RFC

I'm going to explore that today probably

**Comment by Warchamp7** [comment]
I've reduced the padding slightly per feedback, though things are still larger and spaced apart more than the existing Dark theme. I think this is a change that should be made in general, and looks better.

Here's how Yami looks currently, I will update my PR with the changes shortly

image

As for the default theme RFC I created, I've made a greyscale version of Yami and will be amending the RFC to suggest that one be used

image

But let's keep this issue focused on the blueish Yami theme specifically for now

**Comment by Fenrirthviti** [comment]
Definitely like the latest version.

**Comment by PatTheMav** [comment]
Just tested this on macOS and the paddings and sizes don't seem to align as neatly as in Windows:

Yami Theme macOS

**Comment by Warchamp7** [comment]
Converting back to draft until I'm able to debug this on Mac somehow

**Comment by Warchamp7** [comment]
Things are now in a state where I'm feeling pretty good about the overall styling of elements, focus states, hover states, etc.

Contrast has been adjusted since the previous pictures both as a general improvement, and also tested against WebAIM for accessibility.

Once I am back home, I'll be testing on my Mac as well to make sure things are good there but otherwise I **think** is ready for wider testing.

https://user-images.githubusercontent.com/1554753/175757370-67e7292b-6fb1-4065-bd3b-6c32131bb6b6.mp4

A reminder note that once "final", this will be changed to the default theme and I think the general agreement is that Acri 
and Rachni will be updated to be color swaps of Rachni, a light version will be added, and a greyscale version will be added. The current Dark theme will be retained for at least a short time to a deprecated "legacy" or "compact" theme in some fashion.

**Comment by tytan652** [comment]
Here is how it looks on Linux just set the theme.
Note: The white border is on all theme.
Thanks_linux

**Comment by SuslikV** [comment]
Please, use **em** and **ex** unit instead of **px** whenever it is possible. Just to keep UI high-DPI compatible.

**Comment by tytan652** [comment]
Adding `QT_STYLE_OVERRIDE=Windows` when running seems to fix some issues. Thanks Qt to apply some stylesheet that nobody wants.

Thanks_Qt

**Comment by Warchamp7** [comment]
> Please, use **em** and **ex** units instead of **px** whenever it is possible. Just to keep the UI high-DPI compatible.

I attempted to convert Yami to non-px units at one point, but somewhere down the stylesheet line, em and ex depend on a font size that can only be defined in px

https://doc.qt.io/qt-5/stylesheet-reference.html#length

**Comment by SuslikV** [comment]
> I attempted to convert Yami to non-px units at one point, but somewhere down the stylesheet line, em and ex depend on a font size that can only be defined in px

Egg or chicken? Did you ever tried to think why it _is_ in **px**?
It OK to have the single start point.

**Comment by tytan652** [comment]
> Here is how it looks on Linux just set the theme.
> Note: The white border is on all theme.
> Thanks_linux png

Found the issue on Linux, the Plasma default theme Breeze also provide a Qt style plugin.
On non-Plasma DE, this plugin add a frame to QDockWidget.
Those frames are not stylable with QSS because those are drawn with QPainter.

- <https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezestyle.cpp#L1555>
- <https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezehelper.cpp#L457>

So Flatpak install is always affected because the KDE Runtime provide Breeze, and Linux systems with Breeze installed are also affected for non-Flatpak install.

**Comment by WizardCM** [comment]
> On non-Plasma DE, this plugin add a frame to QDockWidget.

To expand on @tytan652's comments - in my testing this border is also added on Plasma DE, and cannot be disabled.

I'm hoping there's some way we can override the Breeze .kcfg to disable `DockWidgetDrawFrame`.

**Comment by Warchamp7** [comment]
Given the above issue only affects certain Linux version/install methods, I'm gonna consider it a non blocker for merging.

As of my latest commit, I am done styling everything and informally declaring this "Ready".

After a bit more testing just to be sure, this is good for a squash+ merge.

**Comment by Warchamp7** [comment]
> The "menuIconSmall" change is controversial.
> 
> The cog button in transitions has menu role, the Studio Mode cog also has menu role.

Transitions menu is fixed.

**Comment by SuslikV** [comment]
The DARK theme has no icons (the cog) in Studio Mode, the Audio Mixer missing it too.

Or dark not planned, anymore?

**Comment by lextra2** [comment]
It is beautiful. Thank you very much!

**Pull request merged**
