### PR TITLE
Potential 27.2 backports

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Should (and that's an if, not a when) a 27.2.5 happen, these are the fixes I'd propose for backporting from master.
Includes some smaller fixes (like with the display affinity) and crashes (mainly on Linux).

[obs-deps#102](https://github.com/obsproject/obs-deps/pull/102) should definitely also be included should it get merged, imo.

### Motivation and Context

There was some discussion about a potential 27.2.5 recently. While it's not given that such a release will happen, having everything ready to go in the release branch makes sense.

I also think that in the future we should cherry-pick changes into the release-branch immediately after merging a PR into master (if a PR is a crash fix or simple bug fix and considered to be worthy of being included in a patch release), that way we won't have to go through the history later.

### How Has This Been Tested?

The changes have of course all been tested in their respective PRs, but this as a whole has not yet been tested.
Needs testing with CI artifacts.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

This PR includes #6376.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
[libobs-opengl: Use gl helpers in create_dmabuf_image](https://github.com/obsproject/obs-studio/pull/6399/commits/4c2a0676ccb59465dd5222ab8edccaf3720847a8) is already requested in another backport PR.

**Comment by gxalpha** [comment]
I intentionally added it here as well.
As I alluded to in the PR description, I'm personally not a big fan of having any backport PRs in general, let alone multiple (which is why I also added it to this PR) - they might get buried amongst the other PRs, changes aren't in the same order as on master, and if we merge some but not others there's a chance we'll lose track of which changes were already considered and which weren't etc.
Though if we think having multiple backport PRs is fine, I guess I could remove it here.

**Comment by RytoEX** [comment]
I personally need a lot of convincing to change dependencies in patch/bugfix releases.

**Comment by gxalpha** [comment]
> I personally need a lot of convincing to change dependencies in patch/bugfix releases.

That's a fair point. My reasoning (at least for obsdeps/102) would be "the earlier we can fix the broken docks the better, because as it is they're just unusable". The other ones aren't that important, we can probably ignore them.

**Comment by WizardCM** [comment]
@gxalpha Please drop the merged commit of dmabuf changes and we'll merge this.

**Comment by gxalpha** [comment]
done

**Comment by tt2468** [comment]
Going to close this since it's not looking like a 27.2.5 is likely right now.

**Comment by ogmkp** [comment]
That was a good idea, I'm writing my own backport because the new 28.0 beta 1 brings too many new features too fresh to be integrated in production.

**Pull request closed without merging**
