### PR TITLE
Use property suffixes for units everywhere

### PR DESCRIPTION
**Pull request by Vainock**
### Description
Use suffixes for units where not already applied. Suffixes have only been commonly used in the Settings, but this makes them consistent in all instances. 

### Motivation and Context
UX and consistency.

### How Has This Been Tested?
By observing the properties influenced by the changes. (only Windows)

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Commit title will need to be updated. I'm not sure if it would make more sense as separate commits, since each of these changes is for a different plugin, or just as a single commit that touches everything.

**Comment by WizardCM** [comment]
Unsure if I prefer 's' or 'secs'. I assume the downside of the latter is it would have to be translated.

**Comment by Fenrirthviti** [comment]
Is using the full "seconds" not viable? Hard to tell without screenshots how it might look.

**Comment by Fenrirthviti** [comment]
Using "secs" as an abbreviation of a full English word seems wrong to me, and looks off. I actually prefer the full seconds here. Likely will need @Warchamp7 to weigh in from a UX standpoint.

**Comment by RytoEX** [comment]
The SI unit of time is seconds and is abbreviated as "s". I am fine with using "s" as the unit suffix in the UI, but will defer to @Warchamp7 .

**Review by RytoEX — APPROVED** [review]
Here are some examples of this change in action.

Image Slideshow Source before:
image

Image Slideshow Source after:
image

x264 encoder before:
image

x264 encoder after:
image


At a glance, the rest of the changes seem fine.

**Comment by pkviet** [comment]
I'll weigh upon using SI units too. This would avoid localization issues.

**Comment by Warchamp7** [comment]
I am good with this change and with the usage of abbreviations 👍

**Comment by RytoEX** [comment]
Per @Warchamp7 's approval above, will merge.

**Comment by SuslikV** [comment]
One is left:
https://github.com/obsproject/obs-studio/blob/ab62c9c615bb08bdeddafce32341738959098586/UI/data/locale/en-US.ini#L971
(Custom FFmpeg Output)

**Pull request merged**
