### PR TITLE
CI: Enable main workflow to run on merge queue items

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Enable the main GitHub Actions workflow to run on merge queue (merge group) items. Let's try running merge queues with actual workflows.

### Motivation and Context

Let's try out merge queues for some limited parallelism.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

### How Has This Been Tested?

It hasn't, but this change looks correct.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I don't know if simply adding this item first to a merge queue will make them all use the workflow. Might need to merge this first to get merge queue items to actually run, but I'm willing to experiment on this.

**Comment by derrod** [comment]
> I don't know if simply adding this item first to a merge queue will make them all use the workflow. Might need to merge this first to get merge queue items to actually run, but I'm willing to experiment on this.

Since merge queue first rebases on the target branch and then runs I imagine that would not work. So this would probably have to be in master first.

**Review by derrod — APPROVED** [review]

**Comment by RytoEX** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues:
> The merge queue creates temporary branches with a special prefix to validate pull request changes. The changes in the pull request are then grouped into a merge_group with the latest version of the base_branch as well as changes ahead of it in the queue.

Not sure if that means they all run together or they run individually and then are checked for conflicts with each other.

**Comment by derrod** [comment]
Mh I see, yeah that *might* work but I might also not want to risk it :p

**Comment by RytoEX** [comment]
> Mh I see, yeah that _might_ work but I might also not want to risk it :p

Fair enough. Will merge this first.

**Pull request merged**
