### PR TITLE
GS/GL Shenannigans (Prep for obs-browser hwaccel on Linux ?)

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Disclaimer: This is graphics code, do not consider that I know what I am doing.

- ~~Enable gs_shared_texture_available on all platforms, only Linux was missing which mainly use DMA-BUF.~~
  - ~~obs-browser relies on it to enable hardware accel~~
- Relax OpenGL texture format copy check
  - It allows to copy `_UNORM` to their non-`_UNORM` counterpart since CEF sends texture with SRGB.

### Motivation and Context

Enable https://github.com/tytan652/obs-browser/tree/linux_hwaccel_2 to work without doing weird stuff like https://github.com/tytan652/obs-browser/commit/1ca22d27067df11c448aaa9b08ded40710dc80c6 or other in https://github.com/tytan652/obs-browser/tree/linux_hwaccel

### How Has This Been Tested?

Just built and ran OBS with this PR and my second hwaccel browser branch and their is no more SRGB gamma issues.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

- Documentation (a change to documentation pages)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
This is used to guard access to `device_texture_open_shared`, which we do not and will never have on linux. It should be safe to simply always assume dmabuf is available on linux platforms.

And really every backend except windows opengl would report true, so maybe we should move the remaining 3 uses of this function behind windows if-def's instead of trying to make it more generally available?

**Comment by tytan652** [comment]
I can remove the gs_shared_texture_available changes, if there is no issue hard-coding it to true on the obs-browser side.

**Comment by kkartaltepe** [comment]
We already depend on `EGL_EXT_image_dma_buf_import_modifiers`, if the platform doesnt support it obs wont load anyway. This isnt a problem with nvidia. If you wanted a better check would need to actually manage the modifier format lists like we do in pipewire which again is not something a simple "texture_sharing_enabled" is going to be useful for.

**Review by WizardCM — APPROVED** [review]
Looks to be the same change as D3D.

**Review by Lain-B — APPROVED** [review]
Although this could be dangerous if used incorrectly, this is generally fine because the underlying memory layout should be identical, so if a use case calls for it, this is something I am *probably* fine with.

**Pull request merged**
