### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran a series of lossless compression algorithms to make the images smaller. Total reduction of 652,389 bytes.

Example here: https://pastebin.com/MTtcVck2

### CODE REVIEW

**Comment by ivan2340** [comment]
is it worth doing this for 600kb? this could increase decoding time for those images, leading to worse performance

**Comment by Peppernrino** [comment]
I'm not sure I understand how this could increase decoding time... Are you thinking like matrices or whatever? The images don't have like, extra things added to them... all of the compression is live in the images. They're not packed like a .zip or anything.... if that's how you're thinking of it. :)

There ARE techniques you can use to preview images at lower quality, say, on a website while the full image is loading... but that's not what is happening here.

**Comment by jp9000** [comment]
I can't help but feel it's very unlikely that decode times could be impacted any significant extent.  Image decode times are not particularly a concern.

**Comment by ivan2340** [comment]
Might be unlikely, but why risk the possibility of the performance being impacted (at all) for 600kb? Just my 2 cents

**Comment by ivan2340** [comment]
if something is compressed more it will inevitably take longer to decompress, that's my understanding. A zip file takes longer to read than a Raw file, raw is only slower once you exhaust the bandwidth of your storage and/or anything else in the pipeline, with images this small this is a non issue tho, we might be talking about microseconds here, all I'm saying is that IMO having any additional latency at all just to save 600k is not worth it.

**Comment by Peppernrino** [comment]
I already explained how this wasn't like a .zip file. I don't think you're actually reading what I'm typing... :\

**Comment by ivan2340** [comment]
Sorry I missed that part, most of my argumentation is still valid though. If there is any difference in decoding time it's miniscule anyways, but 600kb aren't much either, that's what I'm saying :D

**Comment by Peppernrino** [comment]
There isn't anything to "unpack", per se. That's what I'm trying to tell you. lol. If it were a pixmap or something, you'd have a point, as the math inside the file would be changed (I would still change it to more efficient math anyway)... but with this, it's just a change in bit depth, frame size, creation date... stuff like that. "Lossless" compression. The resulting files could be nothing but easier on a system. :)

**Comment by ivan2340** [comment]
I see, now I understand :D also read a bit through the Truepng docs, then it's probably fine, especially if both the optimizers and the library that's reading the images in obs are PNG-spec compliant, sorry for the misunderstanding.

**Comment by Peppernrino** [comment]
All good, friend. :)

**Comment by jp9000** [comment]
600kb isn't really worth it for having to write 138 delta patches for when I make the update.  Much of this is probably just image file metadata, which is fine to have.  It's just insignificant relative to modern computing power, and it doesn't change the uncompressed size in memory, just the size on disk, which makes the changes even less significant.

**Pull request closed without merging**
