### PR TITLE
libobs/util: Add %s string replacement for unix time

### PR DESCRIPTION
**Pull request by tt2468**
### Description
Adds %s which replaces the keyword with the current unix epoch time.

The %s keyword is common in languages like PHP and Python, and even
some C implementations, but it is not standard so this is a fallback.

### Motivation and Context
There is not currently a good way to parse recording filenames with scripts, and also not a timezone-agnostic format available. Unix epoch time is an effective and commonly used method of portraying time.

Requested by a friend who needed it.

### How Has This Been Tested?
Added %s to my recording format and it gets replaced with UNIX time.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Vainock** [comment]
It would make sense for the translation of this string to convert it into many smaller pieces, but that's probably not possible to implement in a 'clean' way.

**Comment by norihiro** [comment]
Is there any concern the newly added format is conflicting with existing `%ss`?

**Comment by tt2468** [comment]
> Is there any concern the newly added format is conflicting with existing `%ss`?

On linux, it does not appear to. Will test on windows though.

**Comment by tt2468** [comment]
Indeed it is unaffected on Windows 10.

**Comment by norihiro** [comment]
> > Is there any concern the newly added format is conflicting with existing `%ss`?
> 
> On linux, it does not appear to. Will test on windows though.

I just concerned the case a user want to add `s` followed by `%s`. Maybe it’s not so important for most cases.

**Comment by tt2468** [comment]
> > > Is there any concern the newly added format is conflicting with existing `%ss`?
> > 
> > 
> > On linux, it does not appear to. Will test on windows though.
> 
> I just concerned the case a user want to add `s` followed by `%s`. Maybe it’s not so important for most cases.

Well in that case it would qualify as the `%ss` macro. Using an escape `\` should work fine.

**Pull request merged**
