### PR TITLE
CI: Create AppImage

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/).

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
The resulting AppImage does not run properly, e.g., on Clear Linux OS:

```
user@host ~/Downloads $ ./OBS-git.ea50599-x86_64.AppImage 
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
error: Failed to load locale
info: == Profiler Results =============================
info: run_program_init: 3172.4 ms
info:  ┗OBSApp::AppInit: 2019.77 ms
info:    ┗OBSApp::InitLocale: 2016.82 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: =================================================
info: Number of memory leaks: 1
```

It seems like it is trying to load its resources from `share/obs/obs-studio/locale/en-US.ini` relative to the user's current working directory, rather than from a location relative to the main executable itself.

**Comment by kkartaltepe** [comment]
While always interesting, there have been numerous issues from the people who already attempted and distributed other containerized formats, with less issues then this current PR has.

These containerized formats are designed to limit permissions of the containerized application. However due to the nature of OBS it often needs high privileged access, thus running into all the walls that containers are designed to put up.

**Comment by probonopd** [comment]
Which is why AppImage is a great match, as it does _not_ run in a sandbox or otherwise restrict the application.

**Comment by kkartaltepe** [comment]
> No root needed

Suggests it is running in a pid namespace. Which does restrict access.

**Comment by probonopd** [comment]
Well, it means that unlike deb or rpm, which need root rights to get the application installed, the AppImage format does not need this. It does _not_ mean that you can't run an AppImage with root rights, if you so desire/need.

**Comment by ElectronicWar** [comment]
OBS issues are tracked on Mantis: https://obsproject.com/mantis/
Developers can be reached directly on the OBS discord, found at https://discord.gg/obsproject

**Comment by kkartaltepe** [comment]
I see, can you also explain the qt repository you are adding? And the rest of the workarounds in the new script?

**Comment by probonopd** [comment]
> can you also explain the qt repository you are adding?

The Qt that comes with Ubuntu 14.04 has a bug in that it tries to load the platform plugins from the wrong location (relative to the user's current working directory, rather than from a location relative to the Qt being used). This has been resolved in more recent versions of Qt. The beineri ppa is a very reliable source for recent Qt versions compiled on older Ubuntu releases, and has been around for years.

> And the rest of the workarounds in the new script?

Let me go through it:

```
# Make sure the Qt from the beineri repository (see above) is used
export LD_LIBRARY_PATH=/opt/qt59/lib/x86_64-linux-gnu:/opt/qt59/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/opt/qt59/lib/pkgconfig:$PKG_CONFIG_PATH
export PATH=/opt/qt59/bin:$PATH

# Build the application
cd ./build
make -j$(nproc)

# Install the application into a directory called "appdir" which is going to become an AppDir
# http://rox.sourceforge.net/desktop/AppDirs.html
make DESTDIR=appdir -j$(nproc) install ; find appdir/

# Make sure the contents of the AppDir do not depend on anything outside of the AppDir
# that cannot be resolved
find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq

# Get linuxdeployqt, a tool which will finalize the AppDir and convert it to AppImage
wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"

# Since linuxdeployqt is an AppImage itself, we need to make it executable
chmod a+x linuxdeployqt-continuous-x86_64.AppImage

# Make sure nothing is interfering with the correct operation of linuxdeployqt
unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH

export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file

# Use linuxdeployqt to bundle ("deploy") dependencies into the AppDir
./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs

# We need to patch the RPATH of one library using patchelf, and since patchelf is contained inside
# linuxdeployqt-continuous-x86_64.AppImage, we extract that to be able to use it from there
./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract ; export PATH=./squashfs-root/usr/bin:$PATH # Get patchelf

# Patch the RPATH of one library using patchelf (for the other libraries, linuxdeployqt does this automatically)
patchelf --set-rpath '$ORIGIN' appdir/usr/lib/libobs-opengl.so.0 # This is loaded by obs with dlopen(), so linuxdeployqt can't know about it

# Finally, convert the AppDir into a self-mounting AppImage
./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

# Upload the AppImage
# TODO: The next line should be replaced by a native upload mechanism defined in .travis.yml,
# e.g., using https://github.com/probonopd/uploadtool
curl --upload-file OBS*.AppImage https://transfer.sh/OBS-git.$(git rev-parse --short HEAD)-x86_64.AppImage
```

**Comment by probonopd** [comment]
On IRC https://github.com/obsproject/obs-studio/wiki/Install-Instructions#linux-portable-mode-all-distros was pointed out. To be investigated.

**Comment by probonopd** [comment]
If I extract the AppImage, `cd` to `usr/` inside the AppDir, then I do not get this error.

But another one:

```
user@host ~/Downloads $ ./OBS-git.ea50599-x86_64.AppImage --appimage-extract

user@host ~/Downloads $ cd squashfs-root/usr/

user@host ~/Downloads/squashfs-root/usr $ ../AppRun 

Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
info: CPU Speed: 1971.744MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 3816MB Total, 666MB Free
info: Kernel Version: Linux 4.19.5-665.native
info: Distribution: "Clear Linux OS" 26600
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.3
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS ea50599 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
info: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 19.0.0-devel, shading language 4.50
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: ---------------------------------
info:   Loaded Modules:
info: ---------------------------------
info: ==== Startup complete ===============================================
error: Encoder ID 'obs_x264' not found
error: Failed to get properties for encoder '' (ffmpeg_aac)
error: Could not enumerate any AAC encoder bitrates
error: Failed to create aac streaming encoder (simple output)
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 1710.1 ms
info:  ┣OBSApp::AppInit: 3.666 ms
info:  ┃ ┗OBSApp::InitLocale: 1.386 ms
info:  ┗OBSApp::OBSInit: 192.19 ms
info:    ┣obs_startup: 13.471 ms
info:    ┗OBSBasic::OBSInit: 120.774 ms
info:      ┣OBSBasic::InitBasicConfig: 0.47 ms
info:      ┣OBSBasic::ResetAudio: 0.227 ms
info:      ┣OBSBasic::ResetVideo: 119.54 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0.011 ms
info:      ┣OBSBasic::InitHotkeys: 0.081 ms
info:      ┣obs_load_all_modules: 0.057 ms
info:      ┗OBSBasic::ResetOutputs: 0.167 ms
info: obs_hotkey_thread(25 ms): min=0.09 ms, median=0.145 ms, max=5.104 ms, 99th percentile=5.104 ms, 100% below 25 ms
info: audio_thread(Audio): min=0.018 ms, median=0.021 ms, max=0.172 ms, 99th percentile=0.172 ms
info: obs_graphics_thread(33.3333 ms): min=0.035 ms, median=0.04 ms, max=4.229 ms, 99th percentile=4.229 ms, 100% below 33.333 ms
info:  ┣tick_sources: min=0 ms, median=0.001 ms, max=0.007 ms, 99th percentile=0.007 ms
info:  ┣output_frame: min=0.033 ms, median=0.036 ms, max=4.218 ms, 99th percentile=4.218 ms
info:  ┃ ┗gs_context(video->graphics): min=0.033 ms, median=0.036 ms, max=4.218 ms, 99th percentile=4.218 ms
info:  ┃   ┣render_video: min=0.021 ms, median=0.024 ms, max=4.077 ms, 99th percentile=4.077 ms
info:  ┃   ┃ ┗render_main_texture: min=0.017 ms, median=0.02 ms, max=4.063 ms, 99th percentile=4.063 ms
info:  ┃   ┗gs_flush: min=0.001 ms, median=0.001 ms, max=0.125 ms, 99th percentile=0.125 ms
info:  ┗render_displays: min=0.001 ms, median=0.001 ms, max=0.009 ms, 99th percentile=0.009 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.157 ms, median=25.261 ms, max=30.185 ms, 93.6508% within ±2% of 25 ms (0% lower, 6.34921% higher)
info: obs_graphics_thread(33.3333 ms): min=33.223 ms, median=33.334 ms, max=33.44 ms, 100% within ±2% of 33.333 ms (0% lower, 0% higher)
info: =================================================
info: Number of memory leaks: 270
```

**Comment by probonopd** [comment]
As was pointed out on IRC `info:   Loaded Modules:` should not be empty. It is not loading its modules.

**Comment by probonopd** [comment]
So, I guess that using `-DUNIX_STRUCTURE=0` and doing a `chdir()` before executing the `obs` binary will get it working.

But is it the cleanest way to go?

**Comment by probonopd** [comment]
```
user@host ~/Downloads/squashfs-root/usr $ ldd lib/obs-plugins/obs-* | grep not | sort | uniq
	libavcodec.so.57 => not found
	libavdevice.so.57 => not found
	libavformat.so.57 => not found
	libavutil.so.55 => not found
	libfdk-aac.so.0 => not found
	libjansson.so.4 => not found
	libobs.so.0 => not found
	libswscale.so.4 => not found
	libx264.so.152 => not found
```

**Comment by kkartaltepe** [comment]
thanks for the work on getting it working, now we will need to test on some other common distributions as the documentation suggests and find someone to maintain the appimage.

**Comment by probonopd** [comment]
This is the same AppImage on Ubuntu 18.04:

**Comment by probonopd** [comment]
This is the same AppImage on elementary OS 5.0 Juno:

**Comment by probonopd** [comment]
This is the same AppImage on openSUSE Tumbleweed:

**Comment by probonopd** [comment]
This is the same AppImage on Xubuntu 16.04:

**Comment by probonopd** [comment]
This is the same AppImage on Manjaro:

**Comment by probonopd** [comment]
This is the same AppImage on Netrunner 17.03:

**Comment by probonopd** [comment]
This is the same AppImage on Pop! OS 17.10:

**Comment by probonopd** [comment]
This is the same AppImage on Deepin Linux 15.5:

**Comment by probonopd** [comment]
This is the same AppImage on Maui Linux 2.1:

**Comment by probonopd** [comment]
This is the same AppImage on Linux Mint 18.1:

**Comment by probonopd** [comment]
When trying a screen capture:

```
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/me/2018-12-03 02-09-50.flv'...
share/obs/obs-plugins/obs-ffmpeg/ffmpeg-mux: error while loading shared libraries: libavcodec.so.57: cannot open shared object file: No such file or directory
warning: [ffmpeg muxer: 'simple_file_output'] os_process_pipe_write for packet data failed
```
Argh, there seem architecture-dependent binaries to be hiding in `usr/share/obs/obs-plugins/`... not sure whether this is even [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) compliant.

```
me@host ~ $ ldd /tmp/.mount_OBS-gi7o01ja/usr/share/obs/obs-plugins/obs-ffmpeg/ffmpeg-mux
	linux-vdso.so.1 =>  (0x00007fff4afd7000)
	libavcodec.so.57 => not found
	libavutil.so.55 => not found
	libavformat.so.57 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc5a8a8c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d172d27000)
```

**Comment by probonopd** [comment]
Sure enough, recording works now. :+1:

**Comment by juvester** [comment]
Nice!

I tested it on Ubuntu MATE 18.04 and one thing I noticed is that the Tools menu is missing these entries: Automatic Scene Switcher, Output Timer, Scripts. These are normally available in the .deb version from OBS PPA.

I believe it has something to do with `frontend-tools.so` not being loaded:
```
info: ---------------------------------
error: os_dlopen(././././lib/obs-plugins/frontend-tools.so->././././lib/obs-plugins/frontend-tools.so): libobs-scripting.so: cannot open shared object file: No such file or directory

warning: Module '././././lib/obs-plugins/frontend-tools.so' not loaded
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
```
Other than that all the basic stuff seemed to be working fine: Recording, Screen Capture, Window Capture, VLC Video Source, webcam, mic, etc.

**Comment by SuslikV** [comment]
There is very limited number of cases where need to use OBS on linux.

Because of the wrapper any new build cannot be considered as test-build.

**Comment by probonopd** [comment]
> There is very limited number of cases where need to use OBS on linux.

What do you mean by this? There are many Linux users who would appreciate being able to download the most recent version of OBS Studio right from its download page (myself included).

> Because of the wrapper any new build cannot be considered as test-build.

What do you mean by this? I don't understand. Please elaborate.

**Comment by probonopd** [comment]
When running with `LD_DEBUG=libs`, getting some

```
error: symbol lookup error: undefined symbol: obs_module_unload (fatal)
error: symbol lookup error: undefined symbol: obs_module_post_load (fatal)
error: symbol lookup error: undefined symbol: obs_module_name (fatal)
error: symbol lookup error: undefined symbol: obs_module_author (fatal)
```

What might be causing this?

**Comment by computerquip-streamlabs** [comment]
> 
> 
> When running with `LD_DEBUG=libs`, getting some
> 
> ```
> error: symbol lookup error: undefined symbol: obs_module_unload (fatal)
> error: symbol lookup error: undefined symbol: obs_module_post_load (fatal)
> error: symbol lookup error: undefined symbol: obs_module_name (fatal)
> error: symbol lookup error: undefined symbol: obs_module_author (fatal)
> ```
> 
> What might be causing this?

When we load plugins, it search for those symbols in order to initialize the plugin. I'm guessing it's trying to load some plugin that fails to find to find those specific functions.

**Comment by probonopd** [comment]
Thanks @juvester. The latest commits should fix this (by deploying all plugin dependencies and by bundling Python).

**Comment by SuslikV** [comment]
About the Linux usage, (statistics from the obs support forum, average of threads and messages)

**Windows** `89.12 %` (33070t 131177m)
**Mac** `8.01 %` (2990t 11720m)
**Linux** `2.87 %` (1004t 4459m)

------------------

About the test-builds:

> `...upon each git push...`

your application itself has 133 opened issues as I see.

**Comment by probonopd** [comment]
@SuslikV this pretty closely reflects OS market shares, which means that OBS has pretty much the same popularity among Linux users as it has among Windows users.

screenshot_2018-12-04_19-43-11

Source: https://media.ccc.de/v/ASG2018-174-2018_desktop_linux_platform_issues/

> your application itself has 133 opened issues as I see.

I don't quite understand what you mean by this.

**Comment by jp9000** [comment]
Thank you for the pull request -- if this pull request is a work-in-progress, please make sure to specify that it's a work in progress, that way I can know that your commits aren't finished/renamed/squashed for merge.

If this pull request is finished, please make sure to adhere to our guidelines for making commits and pull requests, please make sure to read these two links:

https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst and
https://obsproject.com/blog/how-to-contribute-to-open-source

**Comment by jp9000** [comment]
If the pull request is finalized, please squash any relevant commits, and please rename them so that they adhere to our commit guidelines.  I.E. for this pull request, it modifies the CI files primarily.  Modifications to files that are in the CI directory are prefixed with "CI: ".  Also, any commits that solely exist to "fix" previous commits need to be squashed in to the commits they are fixing.

**Comment by probonopd** [comment]
If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

I don't know how to squish the commits (as the author) that are in an already-existing PR.

**Comment by juvester** [comment]
> I don't know how to squash the commits (as the author) that are in an already-existing PR.

Just do git rebase and then force push to the same branch you originally pushed (probonopd:master in this case). GitHub will update the PR accordingly.

**Comment by TheMuso** [comment]
On Sat, Dec 08, 2018 at 09:42:10AM AEDT, probonopd wrote:
> I don't know how to squish the commits (as the author) that are in an already-existing PR.

Interractively rebase against origin/master, and you will see how you can squash commits together in the comments below the list of commits you want to rebase/edit etc.

Once done, use git push -f to force-update the branch. The pull request will automatically update on github.

**Comment by jp9000** [comment]
We're going to test this out a bit on various setups: might be a week or two if that's okay.

**Comment by probonopd** [comment]
@jp9000 I think the latest build failure is unrelated to my changes, please restart the build.

**Comment by pkviet** [comment]
Hi,
i've reviewed the appimage with several debian based distros (stretch, mint, ubuntu, last versions). It's working really well and should prove useful to linux users.
The only issue I found is that scripting is broken. Both python and lua.
The logs show that the obs-python module is not loaded; I thought that lua was checking Travis log, it does build so I don't know why it is not working.

**Comment by probonopd** [comment]
How exactly can I test to make sure that scripting really works as intended? (Sorry, I have never used OBS scripting so far.)

**Comment by pkviet** [comment]
go to Tools Menu > scripts : click on + ; there are some demo scripts; one is a python script which loads text from a url (you need to create a text source first; try a url which is text only); other demo scripts are lua. You can also find scripts in here: https://obsproject.com/forum/list/scripts.28/
You can ping on discord if you want some help

**Comment by probonopd** [comment]
OBS Studio is trying to load `obslua.so` from absolute paths determined at compile-time in `/usr`, and from `./` which is the current working directory. Neither will work in the case of AppImage. Instead, OBS Studio should be loading it from a path relative to the main binary, i.e. `(the direcotry of the main binary)/../lib/obs-scripting/`.

```
me@host:~$ find squashfs-root/ | grep obsl
squashfs-root/usr/lib/obs-scripting/obslua.so

me@host:~$ strace -f squashfs-root/AppRun 2>&1 | grep obslua.so
[pid  7456] openat(AT_FDCWD, "./obslua.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  7456] openat(AT_FDCWD, "/usr/local/lib/lua/5.1/obslua.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  7456] openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/lua/5.1/obslua.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  7456] openat(AT_FDCWD, "/usr/lib/lua/5.1/obslua.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  7456] openat(AT_FDCWD, "/usr/lib/obs-scripting/obslua.so", O_RDONLY) = -1 ENOENT (No such file or directory)
	no file './obslua.so'
	no file '/usr/local/lib/lua/5.1/obslua.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/obslua.so'
	no file '/usr/lib/lua/5.1/obslua.so'
	no file '/usr/lib/obs-scripting/obslua.so'
```

**Comment by probonopd** [comment]
Please try https://transfer.sh/14SdEw/OBS-git.6dba6e7-x86_64.AppImage now. It should contain a workaround for the scripting.

**Comment by pkviet** [comment]
Scripting is indeed fixed, both python and lua; good job !
Would you consider Bazukas suggestion to include browser source ?
This would be quite useful.

**Comment by pkviet** [comment]
probono: check this discussion https://github.com/obsproject/obs-browser/issues/141
Jim's obs-browser requires two linux fixes to work which are discussed there.

**Comment by probonopd** [comment]
I was able to run obs-browser with no issues at all when using the OBS Studio AppImage, like this:

```
mkdir -p "$HOME/.config/obs-studio/plugins"
tar xf linuxbrowser0.5.2-obs21.1.2-64bit.tgz obs-linuxbrowser/
mv ./obs-linuxbrowser "$HOME/.config/obs-studio/plugins/"
```

**Comment by probonopd** [comment]
Endless OS

**Comment by Illutorium** [comment]
obsonhdmisstickwithlubuntu18dot10
So why aren't be included "VAAPI" hardware Encode?
Then if OBS can be rend hardware on to Windows {Intel Quick Video Sync|Marketing in Technically} so Why on VAAPI can't be encode for OBS?

**Comment by kkartaltepe** [comment]
On my 18.04 Ubuntu system the latest app image linked on this issue provides the ffmpeg VAAPI option. (the test used to check for VAAPI support is here 
https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg.c#L175

However on my system actually initializing the VAAPI codec fails.
```bash
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
[AVHWDeviceContext @ 0x25a8d60] Failed to initialise VAAPI connection: -1 (unknown libva error).
```
This is on intel hardware, and the device initilizes fine when run from 22.0.3 normally.

**Comment by probonopd** [comment]
Seems to be a known issue: https://github.com/intel/media-driver/issues/235#issue-341600240. Apparently the OBS Studio build is compiled against `i965_drv_video.so` that ships with Ubuntu 14.04, because this is currently the oldest still-supported distribution release. Unfortunately Intel seems to have broken backward binary compatibility since, which means that applications compiled against the old version will no longer run on newer systems. 

I don't know what is the best cause of action here. Can we disable it altogether? Libraries that break backward compatibility are not something I am keen on supporting.

**Comment by probonopd** [comment]
Funny fact is, nothing in the AppImage seems to be hardcoding `__vaDriverInit_0_32`. I can't find the string in the whole AppImage. Also, nothing hardcodes `i965_drv_video`. So _something_ must be loading this stuff, but I don't know _what_...

**Comment by kkartaltepe** [comment]
This is implemented entirely in ffmpeg, so its not related to anything obs is compiled against. strictly the version of ffmpeg used.

**Comment by probonopd** [comment]
Let's decide how to best proceed once we have collected some feedback on https://github.com/obsproject/obs-studio/pull/1565#issuecomment-450043972 from Intel users. I'd assume that people who know how to use hardware encoders might have the library installed locally, so that we should give preference to the local one if it exists. We sill need to ship something (a shim?) in the AppImage for those systems on which the Intel libraries are not installed, otherwise the application will not even launch.

**Comment by kkartaltepe** [comment]
What you are seeing when it doesnt start is the failure of ffmpeg to find its required libva dependency (because you compiled against an ffmpeg with `libva`). OBS itself has no direct dependency on libva and works perfectly without it. You can check yourself that `obs` executable has no direct dependency with `objdump` the libva requirement comes from `libavcodec`.

You dont see those symbols in any files because they are stored directly in the drivers. The drivers dynamically load the required symbols in some hellish mess. At least if amd drivers are anything to go by.

**Comment by probonopd** [comment]
> The drivers dynamically load the required symbols in some hellish mess. 

Looks like it ;-)

So ideally we would not bundle anything that has to do with the Intel drivers and let the system figure that part out. However, if I delete `libva.so.1` from the AppImage then I get the error shown above. Hence my idea to make some shim library that satisfies the linker if the library is not on the system. So that OBS will at least launch.

**Comment by kkartaltepe** [comment]
Well if you delete the library from the appimage then the linkages are still screwed by the packaging process. So im not sure what was expected from just deleting it. Can you exclude it like libgl?

**Comment by probonopd** [comment]
> Can you exclude it like libgl?

Then the application will not even launch on systems that don't have this library, e.g., on systems that don't even have any Intel GPU.

**Comment by kkartaltepe** [comment]
I think you are confused about what libva is. It is the library implementing the VA-API, which is platform agnostic. (libva the library is mostly maintained by intel however).

This issue may also affect AMD and Nvidia (or other implementers of the VA-API interface) if they take the same tact and perhaps only support certain versions.

**Comment by kkartaltepe** [comment]
Well, you may have qualms about putting libva. But it ships on the debian live CD. I leave it up to you to see what of your many distros include it by default even on a live CD.

This library going to be on almost any laptop or other low power device as without it you cannot watch hardware accelerated video on AMD or Intel hardware, and most nvidia hardware uses it as well. Requiring users of the appimage to have it on their system would help them if only because it finally allows their video players to use the hardware decoders they likely were not using before.

But i dont feel the need to impress this any further its not my decision to make what needs to be supported if contributors want to take on owning the appimage.

**Comment by probonopd** [comment]
Note to self, need to 

> see what of your many distros include it by default even on a live CD.

Everyone's experience appreciated.

**Comment by jp9000** [comment]
This doesn't work with xenial, breaks our CI, and has conflicts.  if someone wants to attempt to fix this, then I'm giving it a few more weeks.  if no one's interested by then, I'm closing it, and if someone really wants it they can resubmit it.  I don't know what to do with it otherwise.

**Comment by jp9000** [comment]
You know what, I'm just going to close this.  If someone wants to take a crack at getting this working, resolving the conflicts, and making it so it doesn't break our CI, then please by all means resubmit.  I really don't want this sitting on the PR list unresolved with no activity any longer.

**Comment by probonopd** [comment]
@jp9000 

> This doesn't work with xenial

What do you mean by this? Binaries built on xenial should run on later distributions, and this AppImage certainly does (I had tested it above)

> breaks our CI

Forgive me if I don't remember whether this has been detailed somewhere, but can you concisely point me to what exactly it breaks?

> and has conflicts

The conflicts must have happened since I had sent the PR. 

I am happy to continue putting effort on this, but only if the project is genuinely interested in having an AppImage.

**Comment by Gol-D-Ace** [comment]
The CI is using now Xenial.
The script needs to be adjusted to be compatible with a build server running Xenial.
Also we not only have Travis but also AppVeyor and Azure.

This should ideally work with all platforms or only affect one CI service.

**Comment by probonopd** [comment]
> The CI is using now Xenial.

I think I can use that for making the AppImage too, but the AppImage will not be able to run on trusty anymore.

> Also we not only have Travis but also AppVeyor and Azure.

These are not being used for Linux, right? AppImage is only concerned with Linux.

**Comment by Gol-D-Ace** [comment]
Considering that Trusty is EOL that doesn't seem too bad.
All CI services will do a Linux build and should therefore not get broken by your changes.

**Comment by probonopd** [comment]
> All CI services will do a Linux build and should therefore not get broken by your changes.

Thanks for the explanation, I was not aware of this. Can you give me a hint as to why one would want to build for Linux on more than one CI service? Just asking out of curiosity. (For building the AppImage, Travis CI is certainly sufficient, so it would be OK to run the AppImage generation only there.)

**Comment by probonopd** [comment]
@jp9000 can you give me a concrete list of what needs to be done so that this will be re-considered for merging? I am willing to put time into this, but only if there is a real chance of getting it merged, eventually.

**Comment by probonopd** [comment]
> I am happy to continue putting effort on this, but only if the project is genuinely interested in having an AppImage.

Seems like one must "donate" 10,000 USD like Red Hat who got a Flatpak promptly.

https://www.gamingonlinux.com/2021/12/red-hat-donates-10k-to-obs-studio-flatpak-to-be-official-for-linux/

This smells.
Badly.

**Pull request closed without merging**
