### PR TITLE
 win-capture: Capture animated cursors

### PR DESCRIPTION
**Pull request by SuslikV**
Add ability to capture/draw animated Windows cursors (mouse pointers).
Fixes issue when animated cursor was captured as static image by
Window Capture source.

Fixes: https://obsproject.com/mantis/view.php?id=1233

### CODE REVIEW

**Comment by SuslikV** [comment]
Animation in the mouse pointer for Display Capture source (at least under the win10) is out of scope by this PR.

**Comment by SuslikV** [comment]
I should mention, that this feature was never asked (I didn't found any related requests but mine) on the obs forum or anywhere else.

**Comment by jp9000** [comment]
Do you have an example where this is something that you'd sort of deem as necessary or important to have?  Just out of curiosity.  The solution feels so complex to solve -- is it really worth it?

**Comment by SuslikV** [comment]
Actually, I was looking into how cursor capture works in obs (in attempt to resolve the crash issue that time to time may happen in OBS Studio - https://obsproject.com/mantis/view.php?id=996) and thus, I made attempt to reproduce the issue. During this attempts I noticed that cursors scaled wrongly, I tried to fix it (https://github.com/obsproject/obs-studio/pull/1284). But still unable to reproduce the issue, then I noticed, that animated cursors not captured, I tried to fix it... Now I see, that there was optimization in textures caching by texture size.

So, it is more like theoretical feature. It deviates from the main goal I had, but nobody do it, as I see. It is optional, by the way.

As for further improvements (shadow, trail, locator etc.) - I think, who doing 1:1 capture, can use the capture card.

One more thing, while working with this code I found another issue: https://obsproject.com/mantis/view.php?id=1242
All this is small things, and I doubt that you'll see major fix from me to the OBS Studio in the future.

**Comment by SuslikV** [comment]
**68** PRs on the list..! I should close it for some time. There is no sense to keep the features for so long in development. Let's prioritize simple fixes.

**Pull request closed without merging**
