### PR TITLE
rtmp-services: Add Nimo TV

### PR DESCRIPTION
**Pull request by dgeibi**
### Description

Add ingest list for Nimo TV

### Motivation and Context

Limit the maximum bitrate to improve service quality.

### How Has This Been Tested?

Tested on Windows 10 and Mac OS X 10.15.3.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Alex--wu** [comment]
It's just a list of servers added to the .json file. The same list from this PR: https://github.com/obsproject/obs-studio/pull/2618

**Comment by Fenrirthviti** [comment]
These changes are duplicated from #2618, why was this opened? Closing for now.

**Comment by Alex--wu** [comment]
@Fenrirthviti Sorry I made you misunderstand this pull request. I asked @jp9000 to help review https://github.com/obsproject/obs-studio/pull/2618 , he reply because this PR not only add servers to the .json file but also added an "auto" option which complicates things. 

So we want to separate the PR to two PRs : 1.this one is to just add server to the json file. 2. https://github.com/obsproject/obs-studio/pull/2618 to add the "auto" option.

**Comment by Alex--wu** [comment]
@Fenrirthviti @notr1ch If we want to close the https://github.com/obsproject/obs-studio/pull/2618 but keep this https://github.com/obsproject/obs-studio/pull/2793 one open, what should we do?

**Comment by Fenrirthviti** [comment]
Go ahead and close the other one.

**Comment by dgeibi** [comment]
closed #2618

**Pull request merged**
