### PR TITLE
obs-ffmpeg: Update AMF SDK to v1.4.29

### PR DESCRIPTION
**Pull request by rhutsAMD**
### Description

Updated AMF SDK headers to v1.4.29.0.

### Motivation and Context

Updating to AMF SDK v1.4.29.0 affects OBS in the following ways:
   - Smart Access Video support for the AVC / HEVC / AV1 encoders
   - New options for the AV1 encoder

### How Has This Been Tested?

Tested on Windows 10 with a GPU + APU setup.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Conflict with #6927.

**Comment by RytoEX** [comment]
The AMF include files with this PR do not appear to be identical to those in the AMF v1.4.29 tag.

**Comment by rhutsAMD** [comment]
Thanks for catching that @RytoEX, I now included the updated core/ headers as well.

**Comment by RytoEX** [comment]
> Thanks for catching that @RytoEX, I now included the updated core/ headers as well.

Thanks. The files appear to match now.

**Pull request merged**
