### PR TITLE
UI: Fix locale key for fragmented tooltip

### PR DESCRIPTION
**Pull request by shiina424**
### Description

Fixed problem with fragmented MOV/MP4 tooltip not display.

Up to Version 29.1 beta1 → Tooltip is displayed.
Version 29.1 beta2 or later → Tooltip is not displayed. (broken)

If this is incorrect, we would appreciate it if you could correct it.

 - Before (Launch 30.1 beta2 normally and check tooltip)

https://github.com/obsproject/obs-studio/assets/24505855/149e2717-c58b-448c-92e4-a3f3f22fa4c6

 - After (Exit 30.1 beta2, change the translation key and check the tooltip again)

https://github.com/obsproject/obs-studio/assets/24505855/669cc495-9191-44a2-a326-8ab2537aeace

### Motivation and Context

I want to display translations.

### How Has This Been Tested?

I opened the translation file and changed the strings to confirm.
Use Windows 11 22H3

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Presumably broken by commit https://github.com/obsproject/obs-studio/commit/5a375defa8a6d11e1ad83ae96148ce57b33e87df.
cc @derrod

**Comment by derrod** [comment]
> I'm not sure if changing the key is more or less disruptive than fixing the key in code.

The key is the internal format identifier, changing that or special-casing fmp4 is probably going to be more annoying. I think crowdin is smart enough to detect renamed keys?

**Review by derrod — APPROVED** [review]

**Comment by RytoEX** [comment]
> > I'm not sure if changing the key is more or less disruptive than fixing the key in code.
> 
> The key is the internal format identifier, changing that or special-casing fmp4 is probably going to be more annoying. I think crowdin is smart enough to detect renamed keys?

I think it can? I always forget if it can or not.

**Review by RytoEX — APPROVED** [review]
Discussed off-thread. Since this is already broken, it's better to get this working moving forward, despite the potential disruption to localization.

**Pull request merged**
