### PR TITLE
win-capture: Fix cursor position for DPI-scaled game capture

### PR DESCRIPTION
**Pull request by bertiebaggio**
### Description

Game capture of DPI-scaled windows draws the cursor at the wrong
location in preview and output at present. See #5229

This fix adds a property to game capture sources to let the user define
the cursor DPI scaling they are using.

gc_properties_wscale

The default for this is 100 (%), which is a cursor DPI scaling factor of 1- ie no change to cursor for anyone who leaves this on default. In the screenshot above, I have it set to 175 to match my scaling factor.

### Motivation and Context

This issue potentially affects users who enable Windows scaling. At present, the best workaround is to either:
 - disable cursor capture (suboptimal as that loses cursor in output)
 - disable Windows scaling or run monitor at a lower resolution

See [#5529](https://github.com/obsproject/obs-studio/issues/5229) for examples of how the cursor appears at present vs how it should appear.

This has been the source of queries on the forum in the past; search results pointing to these reference an old option now removed to 'force scaling', a potential source of confusion.

### How Has This Been Tested?

I have tested this by applying different scaling factors in Windows (up to 300%) and manually verifying that the cursor appears where it should in OBS preview.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

Last item is N/A to know knowledge as I could not find documentation pertaining to game capture properties. However, if accepted this option should be documented on the user guide wiki.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
This might have been discussed outside this PR, but is there a reason we're not just reading the DPI scaling values of the system and applying those? I'm not sure I like the idea of this having to be a manual, conscious choice a user has to know a) exists and b) what it means. This should be automated as much as possible.

**Comment by bertiebaggio** [comment]
> This might have been discussed outside this PR, but is there a reason we're not just reading the DPI scaling values of the system and applying those? I'm not sure I like the idea of this having to be a manual, conscious choice a user has to know a) exists and b) what it means. This should be automated as much as possible.

Agreed that it should be as seamless as possible, definitely. However, it doesn't seem to be as straightforward as simply reading system scaling values.

1. Scaling can be different on a per-monitor basis, so we would have to match game to monitor. I'm not familiar enough (read: not familiar at all) with the Windows API to say for sure, but based on what I found I think it could be.

2. Scaling can be overridden on a per-application basis, to manually specify whether it should be the game handling scaling, or Windows. To actually get scaled output, a user invariably has to select the latter. I am unsure whether this can be queried at an API level, I haven't found anything which suggests it can be (yet).

Example:

highdpioverride

3. Thirdly and perhaps most vexingly: not all games exhibit the behaviour when when scaled!

The proposed system would let a user choose if cursor position scaling should be applied, by selecting 100 or their chosen value.  If the first two issues are solvable it may be doable to reduce the option to a boolean toggle, but I think there would still need to be an option.

**Comment by bertiebaggio** [comment]
The fixes proposed in #5235 look promising in early tests and may be applicable here! Given the issues mentioned with other methods of trying to get the DPI [mentioned in my latest comment on #5529](https://github.com/obsproject/obs-studio/issues/5229#issuecomment-912895804), this may be a good way forward.

I am happy to incorporate that here and squash if desired :)

**Comment by jpark37** [comment]
> I am happy to incorporate that here and squash if desired :)

Using the DPI context rather than adding a toggle would be better if it works. I can update my PR if you want, or you can copy/adapt my change, whichever you would prefer.

**Comment by jpark37** [comment]
I updated #5235 to fix the game capture cursor.

**Comment by RytoEX** [comment]
As far as I can tell, this was superseded by #5235, so I'm going to close this. If I'm mistaken, please let me know, and we can consider reopening this.

**Pull request closed without merging**
