### PR TITLE
rnnoise: Use __builtin_trap() instead of *(int*)0=0;

### PR DESCRIPTION
**Pull request by emaste**
### Description
Compilers may omit `*(int*)0=0` - use `__builtin_trap()` instead. I am not sure if `__builtin_trap()` is available in all compilers relevant to OBS-studio, but will check the CI results.

If `__builtin_trap()` is not available we could use Clang's other suggestion `*(volatile int*)0=0;`, add some `#ifdef`ery, or use `abort()` perhaps.

### Motivation and Context
Building on FreeBSD, the system compiler (Clang 14) emitted a warning:

```
[224/423] Building C object plugins/obs-filters/CMakeFiles/obs-filters.dir/rnnoise/src/rnn.c.o
/home/emaste/src/obs-studio/plugins/obs-filters/rnnoise/src/rnn.c:105:6: warning: indirection of non-volatile null pointer will be deleted, not trap [-Wnull-dereference]
     *(int*)0=0;
     ^~~~~~~~
/home/emaste/src/obs-studio/plugins/obs-filters/rnnoise/src/rnn.c:105:6: note: consider using __builtin_trap() or qualifying pointer with 'volatile'
```

### How Has This Been Tested?
Build tested on FreeBSD.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
This a old bundled deps, building a upstream rnnoise package may be a solution rather than relying on this bundled deps.

**Comment by RytoEX** [comment]
This looks like you're making a change to the RNNoise dependency itself. I'd prefer if any such patches were submitted upstream instead of in-tree.

**Comment by emaste** [comment]
Assuming the rnnoise github repo is up to date the issue still exists there. Will follow up there.

**Comment by emaste** [comment]
Ah, already reported there years ago https://github.com/xiph/rnnoise/issues/6

**Comment by emaste** [comment]
Recent upstream pull request: https://github.com/xiph/rnnoise/pull/205

**Comment by emaste** [comment]
The issue is addressed upstream as of https://github.com/xiph/rnnoise/commit/5c375a61487f13bad596068c481d24d985b3689a

**Pull request closed without merging**
