### PR TITLE
rtmp-services: added OnlyFans.com streaming service

### PR DESCRIPTION
**Pull request by lorskun**

### CODE REVIEW

**Comment by dodgepong** [comment]
Please also increase the version number in package.json.

**Comment by lorskun** [comment]
Ok
Version number increased.

**Comment by Fenrirthviti** [comment]
You'll also need to squash those commits. You can use `git rebase -i` to merge them.

**Comment by lorskun** [comment]
Is done. One commit.

**Comment by jp9000** [comment]
I changed your commit message.  Commit messages need to be present tense, not past tense.

**Comment by lorskun** [comment]
Thanks. Now I know.

**Pull request merged**
