### PR TITLE
Windows ARM64 Support

### PR DESCRIPTION
**Pull request by tommyvct**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jp9000** [comment]
In the future, you don't need to recreate a PR -- you can just force push to the branch the PR is set to.

**Comment by tommyvct** [comment]
`ftl-sdk` diff 1
``` diff
diff --git a/ftl_app/main.h b/ftl_app/main.h
index 0a9bae8..3adc1cf 100644
--- a/ftl_app/main.h
+++ b/ftl_app/main.h
@@ -39,6 +39,7 @@
 #define WIN32_LEAN_AND_MEAN 1
 #include <stdio.h>
 #include <stdlib.h>
+#define _WINSOCKAPI_
 #include <windows.h>
 #include "win32/xgetopt.h"
 #else
```

`ftl-sdk` diff 2
``` diff
diff --git a/libftl/gettimeofday/gettimeofday.c b/libftl/gettimeofday/gettimeofday.c
index 08f03fd..f25ce73 100644
--- a/libftl/gettimeofday/gettimeofday.c
+++ b/libftl/gettimeofday/gettimeofday.c
@@ -45,6 +45,7 @@

 #ifdef _WIN32
 #include <Windows.h>
+#include <WinSock2.h>

 /* FILETIME of Jan 1 1970 00:00:00. */
 static const unsigned __int64 epoch = ((unsigned __int64)116444736000000000ULL);
```

**Comment by tommyvct** [comment]
> In the future, you don't need to recreate a PR -- you can just force push to the branch the PR is set to (unless it was the master branch. Using master branch is generally not wise and it'd be a good reason to recreate the PR)

Thanks for that, it was on `master` last time.

**Comment by RytoEX** [comment]
Why do `std::min` and `std::max` need to have the namespace removed?  Why do the parameter names for `gs_perspective` need changed?  Why are the other changes necessary?

Please explain the changes and the reasons for them.

**Comment by tommyvct** [comment]
> Why do `std::min` and `std::max` need to have the namespace removed?  Why do the parameter names for `gs_perspective` need changed?  Why are the other changes necessary?
> 
> Please explain the changes and the reasons for them.

There are some symbol conflicts in VS and it's preventing the whole thing from compiling.

Changing them is only a temporary measure to get it working.

**Comment by tommyvct** [comment]
According to https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included, I should use `#define NOMINMAX` instead of getting rid of `std::`.
I will revert related changes later.

**Comment by tommyvct** [comment]
What a rebase hell....

**Pull request closed without merging**
