### PR TITLE
UI: Add "Fit window to content" to windowed projectors

### PR DESCRIPTION
**Pull request by Scrxtchy**
### Description
Adds a feature to the Projector window. An addition has been made to the context menu of both the standard projector and multiview window, allowing *most* of the borders to be removed (1px margin of error)
 
image
image

Code has been reused from the display helpers (*GetScaleAndCenterPos*)to calculate the desired difference between the window size and the size of the rendered content.

### Motivation and Context
I do not believe anyone has asked for this as a feature on any ticket tracker. I implemented this based on a feature that exists in the software *scrcpy*, which contains a  function to resize the window to the content display area. I believe that there would be a number of users who would appreciate this addition, as it provides a quick and painless method removing the dead-space in the window.

### How Has This Been Tested?
I have tested this on all outputs of the projector object (Fullscreen, Window, Window Multiview).
The feature works correctly on both versions of the window, and is properly not available when in either fullscreen mode or when the window is maximised

It has been tested on a Windows 10 environment. I believe this should be adequate as the feature is not platform specific

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by VodBox** [comment]
Another option that would be good to have that's related to this, would be to set the projector size to a multiple of the source size (1.5x, 2x, 3x, etc). This would be good for things like retro games which get captured at their original resolutions but you'd like a preview that scales nicely (although this may require an additional change to set the scale filtering used on the projector, so it can be set to Point).

**Comment by Scrxtchy** [comment]
A last minute addition managed to get through VS' clang-format, this has been amended.
The term on the context menu "Optimise window size" has also been altered after a discussion with Matt, and is now "**Resize to original size**". Any other suggestions are welcome

**Comment by Scrxtchy** [comment]
> Another option that would be good to have that's related to this, would be to set the projector size to a multiple of the source size (1.5x, 2x, 3x, etc).

I believe a fider ticket exists for a feature similar to this
https://ideas.obsproject.com/posts/250/windowed-projector-sizing-options

**Comment by notr1ch** [comment]
I would maybe call this "Size to content" as "original size" as a bit ambiguous - it could mean the original size of the projector when it was opened for example.

**Comment by Scrxtchy** [comment]
this is something I had also considered, but couldn't think of a better term to replace it with
image
I will most likely amend it to that in some time

**Comment by Scrxtchy** [comment]
Talking with Matt still. I have changed the menu to read _"Resize to content size"_
We also considered using the term *match* in the string, but I also don't want to add long strings into a context menu.

**Comment by RytoEX** [comment]
I hate to chime in further on the choice or wording, but I believe the more common verb for this functionality is "fit", so "Fit to content" is what I'd prefer to see.

**Comment by jp9000** [comment]
"Fit to content" doesn't feel like the right wording, because the window itself contains the content and not the other way around.

**Comment by gerapeldoorn** [comment]
This is awesome, exactly what I need. However, the option doesn't actually work for me. (it doesn't change the windowed projector size)

**Comment by Scrxtchy** [comment]
Still functioning for me

**Comment by gerapeldoorn** [comment]
I'm sorry, I misunderstood this feature. I assumed that this was resize the window to the native output dimensions.

For instance, if the canvas resolution is 1280×720 that that would be decisive the output window. Instead, is removed any black bars around it.

It's working as designed for me as well. Resize to canvas resolution would be very useful for me as well. :)

**Comment by Scrxtchy** [comment]
> Resize to canvas resolution would be very useful for me as well. :)

This actually has been a feature discussed in the past. I attempted an implementation but didn't quite get it right. I would like to return to it one day

**Pull request merged**
