### PR TITLE
libobs: Show plugin search paths in log

### PR DESCRIPTION
**Pull request by norihiro**
### Description

This commit add log lines that shows `bin` and `data` paths to search plugins.

### Motivation and Context

Some users try to install a plugin from zip file and possibly make a mistake to expand the plugin into wrong location.
In other case, some users installed OBS Studio to unusual locations or installed multiple locations on Windows, which causes executable installer to take unexpected install path.
When a plugin is installed by a user but not shown up, there is no way to support the user from the log file. The new log lines should be helpful to find the plugin is installed in the correct location.

### How Has This Been Tested?

OS: Fedora 34
Output of the log with this change is as below.
  https://obsproject.com/logs/195if0CMVjtI6JTa

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I would say this is probably only an issue on Linux where certain containers will limit or customize search paths.

**Comment by norihiro** [comment]
> I would say this is probably only an issue on Linux where certain containers will limit or customize search paths.

Usually deb package is provided for Ubuntu so that it is not an issue for Linux.
I mainly experienced support requests for macOS.

**Comment by WizardCM** [comment]
macOS search paths are always the same, so this logging would provide no insight to someone in support channels. Users should not be putting third party plugins into OBS.app at all.

**Comment by norihiro** [comment]
Thank you, WizardCM. I should reconsider this PR. Maybe documentation should be the better place.

**Pull request closed without merging**
