### PR TITLE
Add multi-service WebRTC to fully functional OBS 24.0.1

### PR DESCRIPTION
**Pull request by SCG82**
### Description

Add WebRTC output to Janus WebRTC Server, Wowza Streaming Engine, and Millicast WebRTC Streaming platform (https://www.millicast.com). Set CMake option BUILD_WEBRTC=ON to build with WebRTC output. WIthout that option set, the WebRTC outputs/services are not included in obs-outputs/rtmp-services. The UI adds a "Room" field above Username (below Key), and two combo-boxes (drop down) for "Codec" and "Protocol" below Auth Password. Based on https://github.com/CoSMoSoftware/OBS-studio-webrtc.

Requirements:
* OpenSSL 1.1
  - [Windows](https://mfcobs.com/download/openssl/openssl_1_1_0k.zip)
  - Mac: brew install openssl@1.1
* WebRTC 75/76

WebRTC library (place in WEBRTC_ROOT_DIR/lib):

- [Windows](https://mfcobs.com/download/webrtc/75/webrtc.lib)
- [Mac](https://mfcobs.com/download/webrtc/76/libwebrtc.a)

WebRTC headers (extract in WEBRTC_ROOT_DIR):

- [Windows](https://mfcobs.com/download/webrtc/75/webrtc-75-headers-win.zip)
- [Mac](https://mfcobs.com/download/webrtc/76/webrtc-76-headers-mac.tar.gz)

See https://github.com/SCG82/obs-webrtc for detailed build instructions for the WebRTC library. Args used: `use_rtti=true is_debug=false is_official_build=true libcxx_abi_unstable=false rtc_use_h264=true use_openh264=true proprietary_codecs=true ffmpeg_branding="Chrome" rtc_include_tests=false rtc_build_examples=false rtc_build_tools=false`

Building example (macOS):
`brew install openssl@1.1`
recursively clone repo, create build directory and change into it. export all deps (eg OBSDEPS, QTDIR, etc).
`cmake -DBUILD_WEBRTC=ON -DDepsPath=$OBSDEPS -DQTDIR=$QTDIR -DVLCPath=$VLCDIR -DX264_INCLUDE_DIR=$X264 -DCEF_ROOT_DIR=$CEF -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1b -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1b/lib -DWEBRTC_ROOT_DIR=$WEBRTC ..`

Screen Shot 2019-08-05 at 5 16 48 AM
Screen Shot 2019-08-05 at 5 16 58 AM

### Motivation and Context

Next generation very low latency livestreaming, especially as Flash becomes deprecated and HTML based replacements often have noticeable increase in latency.

### How Has This Been Tested?

Compiled using BUILD_WEBRTC=ON which resulted in a fully functional OBS + WebRTC outputs (all WebRTC platforms tested). Compiled without setting BUILD_WEBRTC, which results in a normal OBS build. This specific PR only tested on macOS, but the fork it was pruned from has been extensively tested on macOS (WebRTC 76) and Win 10 (WebRTC 75).

Pre-built binaries of my obs-webrtc fork (same underlying framework):

-[Windows](https://mfcobs.com/download/cosmo/OBS-WebRTC-Installer.exe)
-[Mac](https://mfcobs.com/download/cosmo/OBS-WebRTC.pkg)

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
We use mbedtls for SSL, and I am reasonably sure this PR will not be accepted with a redundant SSL library addition. Is it possible to update this to use mbedtls instead?

Small nitpick but `base` is not a category I have seen used before. Probably best to rename the commit as `cmake, gitmodule:` for prefix as I have seen used in the past for consistency.

Lastly, because this is a fairly large PR (over 7k lines of code), it will not be until after the next major release (and possibly longer) until we will have time to do a proper full review. The PR has been acknowledged, so please allow us time for a full review.

**Comment by SCG82** [comment]
I'll look into adapting websocketpp for mbedtls

**Comment by dodgepong** [comment]
It's worth noting that we don't use OpenSSL because it is not compatible with GPLv2.

**Comment by SCG82** [comment]
Please contact me to obtain credentials for testing Janus, Wowza, and/or Millicast.

**Pull request closed without merging**
