### PR TITLE
linux-v4l2: Selective stream restart

### PR DESCRIPTION
**Pull request by ioangogo**
### Description

This PR adds a basic check to see if the v4l2 stream requires a restart. This is primarily implemented on the basis of the fact that the options requiring a restart have values stored in the v4l2_data structure. A restart is only needed if any of the values have changed since the last update.

It also groups the camera controls into a property group and removes them every time the camera is changed to ensure the controls are for that camera only. This does add a string that may need translation

### Motivation and Context

This was primarily done because it was bugging me, but it also resolves issue #2621

### How Has This Been Tested?

Basic changing of camera settings to ensure it restarts on stream detail changes and also switching between cameras to ensure that the controls changed correctly. Tested with the laptops built in camera and my C920. I would like some further testing with other cameras.

uname output: `Linux IoansThinkpad 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux`
Hardware: `Lenovo ThinkPad T450 i5-5200U RAM 12gb`

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by ioangogo** [comment]
Camera controls are also now placed in a group for visual separation, but also to enable the removal of the property when the camera is changed 
image

**Comment by kkartaltepe** [comment]
Thanks for working on this, it seems like the right direction.

However changing camera controls still results in a re-init (it looks like `v4l2_settings_changed` is called when resolution and framerate are reset, so it always resets the device).

**Comment by ioangogo** [comment]
Ooops, forgot to test that, just pushed a commit that should fix it

**Comment by kkartaltepe** [comment]
Works well on my system now.

**Comment by ioangogo** [comment]
there is a weird issue where the FPS is capped to 30fps on some cameras and that confuses the logic. But that is for a separate PR

**Comment by ioangogo** [comment]
I need to work out something with the `Leave Unchanged` setting, so i feel like this is still a bit WIP

**Pull request merged**
