### PR TITLE
NVENC error handling improvements

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
This copies the result of `nvEncGetLastErrorString` to the last encoder error instead of only writing it to the log file. This makes it user-visible, which should help users diagnose and solve the problem.

Also strips off leading colons from NVENC error strings as these can look odd given our format string. An example of such an error:

`::NV_ENC_TWO_PASS_FULL_RESOLUTION is only supported multipass encoding on this architecture.`

Additionally handles `NV_ENC_ERR_NO_ENCODE_DEVICE` with the unsupported device message and blacklists a GeForce MX350 variant.

### Motivation and Context
While the full error message in the log file is useful, it's not really visible to users. Showing it in the encoder failure message box should help users solve the problem.

### How Has This Been Tested?
Not tested very well as I couldn't easily trigger error conditions on my GPU, code seems OK though?

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by flaeri** [comment]
Seems to be working fine for me. Some examples that I could think of:

1. Too many encodes running
image

2. Resolution too high
image

3. Incorrect GPU chosen
image

**Comment by RytoEX** [comment]
Any other specific items you'd like to try to verify @notr1ch ?

**Comment by notr1ch** [comment]
Seeing the error in the dialog like that makes me wonder if we should remove the function call information, users may begin to read the error text and immediately give up as soon as it starts looking too technical. Perhaps adding a couple of newlines between the parts could help too.

**Comment by RytoEX** [comment]
> Seeing the error in the dialog like that makes me wonder if we should remove the function call information, users may begin to read the error text and immediately give up as soon as it starts looking too technical. Perhaps adding a couple of newlines between the parts could help too.

Move the technical parts to the bottom, if possible?

**Comment by notr1ch** [comment]
I honestly don't think the technical info is useful at all in the message box, it still gets sent to the log file for developers to review. I'm worried that exposing too much technical information will still confuse users regardless of where we position it. How about something like this:

> NVENC Error: Frame dimension greater than the maximum supported value (NV_ENC_ERR_INVALID_PARAM)

On another note it also seems the GPU selection error has regressed at some point, that used to give explicit feedback telling the user to set their GPU index back to 0. I'll see if I can fix that in this PR too.

**Comment by notr1ch** [comment]
Some more updates: GPU index error is now visible again, `NV_ENC_ERR_NO_ENCODE_DEVICE` is handled with a nicer error message and a GeForce MX350 variant without NVENC was added to the unsupported devices list.

**Comment by RytoEX** [comment]
Do you need re-tests for this?

**Comment by notr1ch** [comment]
I don't think so, as long as everyone is happy with the new error format `NVENC Error: text (error code)` I think this is good to go.

**Review by RytoEX — APPROVED** [review]
Perfect is the enemy of done. Looks good to me.

**Pull request merged**
