### PR TITLE
UI: Bunch of RAII stuff

### PR DESCRIPTION
**Pull request by cg2121**
### Description
- Add auto release for refs that don't have them
- Remove disconnect signals for OBSSignal
- Add RAII wrappers for volume meters, faders and properties
- Use BPtr for chars that don't have it

### Motivation and Context
WIth RAII, resources are automatically managed.

### How Has This Been Tested?
Went through the entire program with my setup to see if there were any bugs or memory leaks.
More testing on other setups would be appreciated.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by BlockArchitech — COMMENTED** [review]
Looks awesome!

I've actually been wanting this for a little bit now. Here's to hoping it gets merged.

**Comment by WizardCM** [comment]
There are merge conflicts.

**Comment by tt2468** [comment]
While I think the OBS*AutoRelease wrappers covered a certain amount of ground that this PR does, there looks to still be viable improvements here.

**Comment by cg2121** [comment]
Closing as this PR is just too big. With it being this big, it needs a lot of testing, and auto releasing objects sometimes have unintended consequences. Since there are no memory leaks, that are obvious, this isn't that necessary at the moment. In the future, I just make smaller PRs with these changes, as they will be a lot easier to test.

**Pull request closed without merging**
