### PR TITLE
UI: Add screenshot button to scene/source toolbars

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This adds a screenshot button to the scene and source toolbars.

Screenshot from 2021-08-19 17-59-05

### Motivation and Context
Before, the screenshot actions were buried in the context menus.

### How Has This Been Tested?
Clicked buttons to make sure the screenshot were taken.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by cg2121** [comment]
The icons have been updated by suggestion by @Warchamp7 

Screenshot from 2021-08-19 17-59-05

**Review by Warchamp7 — APPROVED** [review]

**Comment by WizardCM** [comment]
Heads up, there are merge conflicts.

**Comment by cg2121** [comment]
Merge conflicts fixed.

**Comment by cg2121** [comment]
Closing this, in favor of the screenshot button in the top tool bar with #6421.

**Pull request closed without merging**
