### PR TITLE
obs-x264: Repeat SPS & PPS for every key frame

### PR DESCRIPTION
**Pull request by wongfei2009**
It is necessary to get SRT output working with SRT gateway properly, because downstream video decoders might miss the first key frame.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
I assume this change is compatible with the SRT rewrite in https://github.com/obsproject/obs-studio/pull/2665

Please confirm.

**Comment by pkviet** [comment]
hello,
can you provide details on which srt server does it fixes issues with ?
I had already tested this setting and retested following this PR but I didn't see any difference w/ my test servers (wowza, nimble, ...).
It's certainly a parameter we want to set to true w/ mpegts but hard coding it to true will impact everything, for instance recording output where it's non requited.
So I disagree with what you propose. Rather move it above the parsing of x264opts and keep default to false; the srt user will have to set it to true manually in the x264opts text box.
Or if you feel inclined, you could force the option to true when detecting srt or udp.
That will require some more UI work than your current quick fix.

**Comment by wongfei2009** [comment]
The most typical workflow is the streaming platform is waiting to receive, before OBS starts sending the first frame.

But if you use the newly added OBS SRT output with https://www.haivision.com/products/srt-gateway/ or https://aws.amazon.com/mediaconnect/. 

You typically expect the OBS start sending the SRT output, before the downstream systems connect. That becomes very problematic.

I think it's much better to have the default to be true, since OBS is a tool focus on streaming. Repeat SPS/PPS in every key frame is typically enabled in streaming. Because it allows decoder to join the stream at any time and it is more resilient to error. 

Re your recording file case, imagine for whatever reasons the first frame is corrupted. The whole video file will become non-decodable if only first frame contains SPS/PPS.

**Comment by pkviet** [comment]
> The most typical workflow is the streaming platform is waiting to receive, before OBS starts sending the first frame.
> 
> But if you use the newly added OBS SRT output with https://www.haivision.com/products/srt-gateway/ or https://aws.amazon.com/mediaconnect/.
> 
Mediaconnect supports zixi, rist, rtp but I didn't see support for SRT.

> You typically expect the OBS start sending the SRT output, before the downstream systems connect. That becomes very problematic.
> 

OBS can be set to `mode=listener`. Did you try ? 

> I think it's much better to have the default to be true, since OBS is a tool focus on streaming. 

srt is NOT the main protocol used.
Anyway, this discussion is probably not necessary anymore:
- check this branch : 
https://github.com/pkviet/obs-studio/commits/srtfix4
This sets to true for srt/udp (non rtmp) automatically.
- check also my other PR which rewrites the srt output:
[https://github.com/obsproject/obs-studio/pull/2665](https://github.com/obsproject/obs-studio/pull/2665)

**Comment by wongfei2009** [comment]
Yes, sorry, I wrongly quoted AWS MediaConnect.

The srtfix4 will solve the problem I see. Thank you.

**Comment by Fenrirthviti** [comment]
Closing this as #3083 is more comprehensive of a fix.

**Pull request closed without merging**
