### PR TITLE
UI: Upgrade stream key link to button in Wizard

### PR DESCRIPTION
**Pull request by JohannMG**
### Description

Follow up to previous pull request https://github.com/obsproject/obs-studio/pull/2145
The wizard has a stream link URL as well. Adding the URL button in the
wizard to match. Additionally, fixing a few  errors in the UI layout
and spacing where items were not padded.

Before: 
Screen Shot 2019-12-17 at 1 07 52 PM

After: 

Screen Shot 2019-12-17 at 2 44 13 PM

### Motivation and Context

Matches UI of previous changes and fixes a button layout issue. 

### How Has This Been Tested?

Yes. 
MacOS 10.14.6
MacBook Pro

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Could you also adjust the service selection text and box to line up left justified with the `Please enter your stream information` and `Stream key` text?

**Comment by JohannMG** [comment]
Let's circle back to the other layout issues in another diff? There's a lot
of little issues in here and I didn't want to snowball tracking them all
down in this diff.

**Comment by energizerfellow** [comment]
I don't like how the stream key field is abbreviated with the buttons on the same horizontal plane. The streak key field should be long enough to visually show the entirety of the stream key with the Show and Get Stream Key buttons below the stream key text field.

**Comment by JohannMG** [comment]
Truncated stream key fields are standard (not just in this UI or app)
because keys are pasted in nearly every scenario.

Most stream keys are long enough that even moving this button down wouldn't
show the entire key.

You can also see the discussion in the PR referenced above on having the
button in line or not and in line was decided on that surface as well.

Possibly we change this later but this matches other apps right now.

**Comment by JohannMG** [comment]
[ FYI I'll be out Dec 21 and more or less offline until 2020 ]

**Comment by JohannMG** [comment]
Any blockers here?

**Comment by jp9000** [comment]
I'm sorry, I thought you were coming back to address the issues Fenrir had pointed out.

The only thing I see is that you use QTStr with some URLs.  I think you might have misunderstood and thought it was used to create a QString, but it's actually used to look up string translations, not to create a string.  You shouldn't need to even create a QString directly, just assigning a normal C-string should automatically convert it to a QString.  So you can just do `qstr = "https://bla.com";` and that should be perfectly fine.

**Comment by jp9000** [comment]
Additionally I agree that the fact that the edit box is small is not that big of a deal.  We can always just increase the size of the dialog or something to compensate later.

**Comment by JohannMG** [comment]
Okay. 
Todo for this PR: 
 - fix URLs using QStr 
- Also fix usage of QStr in [window-basic-settings-stream.cpp](https://github.com/obsproject/obs-studio/blob/111a7ecaea99fa1e9ec290bde51d0898307c3928/UI/window-basic-settings-stream.cpp#L219)

Definitely on the radar but not in this diff: 
- Fix various Wizard layout issues including like what Fenrir pointed out. 

Will do possibly later 
 - Change stream key box size. 

Sound good?

**Comment by jp9000** [comment]
Sounds good.

**Comment by JohannMG** [comment]
Okay. 
 - Updated to not use the QStr macro
 - Rebased onto last master 

I hope everyone had a chill new years break.

**Comment by JohannMG** [comment]
Updates were done: Good to merge?

**Comment by jp9000** [comment]
Yep.  Thanks!

**Pull request merged**
