### PR TITLE
Automatically fix the black screen problem with OBS running on the power saving GPU

### PR DESCRIPTION
**Pull request by Bennik2000**
### Description
Display an error message when the game capture doesn't work because OBS is running on a different GPU than the game. Provide a button to switch from the integrated GPU to the performance GPU from within OBS. 
Screenshots of this feature are in the PR comments.

### Motivation and Context
[Info message on laptop black screen issue](https://ideas.obsproject.com/posts/838/info-message-on-laptop-black-screen-issue)
It detects if game capture or monitor capture fails because OBS is running on the wrong GPU. Then a button is displayed which allows the user to do the windows settings to change the GPU as described [in the forum](https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/). 
The "laptop black screen issue" is very common and this feature helps the user to fix it. The support team will get fewer requests related to this issue.

### How Has This Been Tested?
I tested it on my PC (_Intel Core i7-8705G GPUs: Intel HD 630 / Radeon RX Vega M GL_)
Tried to capture a game running on the dedicated GPU while OBS is on the integrated GPU and vice versa. 
Tried to capture a display while OBS is running on the dedicated GPU. 
In all cases the error message was displayed and the button fixes the issue.

### Types of changes

- New feature (non-breaking change which adds functionality)

- Breaking change (fix or feature that would cause existing functionality to change)
  Added `video_get_error` to `obs_source_info`. Existing code is not affected but this is a struct in the core of OBS, thus I consider this as a breaking change.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
When this gets closer to completion, can you provide some screenshots of how this looks in action?

**Comment by Bennik2000** [comment]
Sure, I will provide screenshots.
For now it doesn't output something on the screen but I can detect if this situation occurs

**Comment by Bennik2000** [comment]
This is an early screenshot of the messagebox:
grafik

The button on the left will change the graphic settings automatically.

The button in the middle will link to the forum [post](https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/).

The left button will close the dialog.

**Comment by Bennik2000** [comment]
This is the state right now:

grafik

When pressing the "Try to fix" button and it succeeds then this message is shown: 

grafik

After restarting OBS the Issue is gone and no error message is shown.

**Comment by energizerfellow** [comment]
I would replace "most" with "many" on the multi-GPU hardware. Office-grade iGPU hardware outnumbers discrete GPU in units shipped, generally speaking.

This UI/UX needs to account for two black screen scenarios:
- Game Capture
- Display Capture

From what I've seen in the wild, most, if not the vast majority, of new-to-OBS users will try adding Display Capture before Game Capture because in their mind they're trying to capture "their display". The concept that Game Capture could be different or even exist never occurs to them.  Since OBS usually starts up on the performance GPU, Display Capture ends up being blank.

The Display Capture on, specifically, could use some kind of verbiage about being only for general productivity applications and not games.

The real fun is that Minecraft (or was it Roblox?) is now coded to run on the iGPU by default, plus has some fun hooking behavior around borderless fullscreen vs exclusive fullscreen.  Minecraft/Roblox + multi-GPU laptop is effectively a daily support issue and could use both programmatic testing and a separate wiki page just for that specific combo.

**Comment by WizardCM** [comment]
> The real fun is that Minecraft (or was it Roblox?) is now coded to run on the iGPU by default

I personally think this is actually related to the bug with the NVIDIA Control Panel not working in Windows 10 1909. Minecraft likely used the same API to force Java to run on the high performance GPU, but as the function is broken (which is why we recommend the Settings method), and when that broke, Minecraft started running on the iGPU. I doubt this is on purpose.

**Comment by Bennik2000** [comment]
Now OBS checks game capture and display capture. 
It works well on my laptop, can someone test how this behaves on a desktop PC?

**Comment by Warchamp7** [comment]
This could use some adjustments to the wording but I am a fan of this feature overall

**Comment by dodgepong** [comment]
If I'm reading this right, does this mean that you're assuming that, if game capture fails, it must be because of a GPU adapter issue, and then shows the error? Surely we can be smarter about what the error actually is, and give a better response depending on the error?

**Comment by Fenrirthviti** [comment]
Unfortunately, the error messages we get from capture failure are extremely ambiguous at the best of times. I don't think there's any errors that are only caused by a single thing we can programmatically respond to. I have concerns about showing the error for capture failure as a popup. This should be some kind of image in the overlay when capture has failed or stopped (See: how streamlabs has implemented this). That is a much better user experience overall, IMO, than having a popup with a bunch of text they likely won't read and will just dismiss. The current wording is too long and technical, and most users will just randomly click a button to dismiss it which might lead to issues.

**Comment by Bennik2000** [comment]
@dodgepong thats right. Right now it assumes that when a game capture error occurs it must be because of the adapter issue. I did not find a way to find out why a capture error occurs. 
However the implemented error reporting functionality lets you distinguish between different types of errors and it also supports errors from other sources than game capture (when the source implements it).

@Fenrirthviti the end user probably cancels the dialog and does not know the root cause, thats true. However, if we can detect if the game and OBS are running on different GPUs a "fix" button could be placed somewhere.

**Comment by Fenrirthviti** [comment]
Don't take this as a rejection as I'm not the one who decides if things are merged, but I just want my opinion logged.

I don't really like this implementation. I am 100% in favor of the concepts, but I don't like how this implementation is being done. Popups are awful and a horrible user experience. There's a reason they are so rarely used in modern applications. If we had a proper user feedback system this wouldn't be an issue, but I don't want to bog down this request with could-be's either.

I would much rather see this implemented as some kind of "fallback" image displayed in the source when capture fails, with directions on how it might be corrected. We can maybe add the "fix this" button in the game capture properties instead, and leave directions to double click the source, press "switch gpu" or whatever we want to call it. As an example of what I'm talking about, Streamlabs shows this graphic when there is no game being captured: slcapture

Obviously we can make it less generic (and maybe even allow users to set it to their own image).

All that said, I could just be the crazy one here. :)

**Comment by Bennik2000** [comment]
I am open for feedback and I like your idea with of a placeholder image when the game capture fails. 
Right now I would implement it like this: 
1. Display a fallback image when a source fails to capture
2. In the properties window display some sort of warning or description of the issue (not a popup but a red text below all properties)
3. In the properties window of the source provide a "fix this" button to try to fix the issue right from OBS

**Comment by Bennik2000** [comment]
Here is an update with the current state:

I removed the popup and display a short error message when the game capture (or display capture) failed.

grafik


The error message is not always displayed when a source renders a black screen. It is hard to get the root cause of a failed capture but these are the methods used to determine a failed capture because of the wrong GPU:  
- For the game capture it assumes an error when the call to `init_shtex_capture` or `init_shmem_capture` fails
- For the display capture (the `duplicator-monitor-capture.c`) it assumes an error when it failed to create the duplicator

Moreover the error message is only displayed when two or more GPUs are available.

The "Change GPU" button toggles the gpu power profile to use the high performance or the power saving gpu.


The error message does not solve all problems but it helps the user to fix the common "black screen on laptops" issue on their own.

**Comment by energizerfellow** [comment]
You may want to revise the wording to something like "This may be because OBS Studio is not currently running on the same GPU as the application you are trying to capture".

**Comment by Bennik2000** [comment]
@energizerfellow Thanks!

The wording of the help texts is like this: 
For the game capture: 
> _OBS is not able to capture this application.
This may be because OBS Studio is not currently running on the same GPU as the application you are trying to capture._  

For the monitor capture:
> _OBS is not able to capture this display.
 This may be because OBS Studio is not currently running on the same GPU the display is connected to._

**Comment by Mister36MN** [comment]
So a couple things on this from another support person perspective - 

 - This is absolutely the most common issue, and while there is no easy solution, THANK YOU for putting this in, since it certainly helps.

- I'm coming at this mostly from the display capture side, as that's the majority of issues, turning on OBS for the first time and popping in display capture. I obviously don't want to diminish your work here, but I almost think that's the only side it should show up. Now if you have made it so it is able to cleanly say that it's not capturing a game because the game is running on the wrong GPU, that's great. Is there still the possibility of it having a false positive for that?

- I know some people will have issues with pop-ups. I personally don't think they are bad per-se; my initial idea for the display capture on laptop problem is a huge info box that shows up when you add a display screen source for the first time explaining why it doesn't work and what to do/ use (game capture/window), so your relatively small one seems a lot better. Also reading through stuff again it seems the pop-up was actually removed, so that's alright.

At this point I would need to see it in action to entail more feedback. Essentially what I am looking for here is "New user turns on OBS on laptop, sees "display capture" and uses it because it's simple, and they are shown something as to why it's not working and what would be a better idea (game/window) then the option to change it if they still want. In the end, I am always of the impression that for most laptop users, they need game and window capture if they have a 2nd High-perf GPU.

**Comment by Bennik2000** [comment]
> Is there still the possibility of it having a false positive for that?

Yes there is a possiblility that the error message pops up even if OBS is on the correct GPU. However I was not able to reproduce this using my tests. I do not know any way to determine to which GPU a display is connected to or on which GPU a game is running. The information from the drivers are very sparse. However, a few false positives can be sorted out by checking certain other conditions (e.g. if only one GPU is available OBS is already running on the correct one).

> At this point I would need to see it in action to entail more feedback

You can download a build from [here](https://github.com/Bennik2000/obs-studio/actions/runs/92425974). I'd love to hear more feedback. Maybe you can reproduce a false positive. Then I could improve the checks for the root cause.

**Comment by mufunyo** [comment]
> I do not know any way to determine to which GPU a display is connected to or on which GPU a game is running.

You can use Windows Management Instrumentation (WMI) to determine physical device topology (the same data source that Device Manager pulls from). On my laptop, for instance, my display is listed as the child of my integrated GPU (and the discrete GPU has no children). I'm not sure how helpful it will actually be in practice to know which GPU a display is connected to, though.

**Comment by Bennik2000** [comment]
Current state: 
OBS detects if game capture or monitor capture fails. If there are more than one GPUs, an error message will be displayed in the properties window of the source (With a button to fix the issue. As described above)
If monitor capture fails the messge is only displayed when OBS runs on a different GPU than the monitor is connected to.

**Comment by dodgepong** [comment]
Honestly, if we have the ability to detect when a game is being run on a different GPU, or if OBS is trying to capture a window/monitor on a different GPU, I would _much_ rather we silently fall back to a slower cross-GPU capture method rather than show a box telling the user to change their GPU. The program should "just work", even if "working" means working slowly. We can notify the user about the potential optimization later on, perhaps through some sort of notification system. But overall I really don't like the pattern of telling users to change their GPU. Yes, that is the "best" solution, but it's technically demanding for people with low computer knowledge and a major pain point for new users.

**Comment by WizardCM** [comment]
Closing in favour of #4140 as it's a more seamless solution (and has been merged). Thank you for your efforts!

**Pull request closed without merging**
