### PR TITLE
cmake: Remove outdated osxbundle files

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

These files have been superseded by files in CI/scripts/macos. They are no longer used, and keeping them around creates confusion and makes people think they are still used. Let's remove them to prevent further confusion.

### Motivation and Context

Prevent contributors from trying to solve an issue by modifying these files.

### How Has This Been Tested?

I haven't tested this, but @PatTheMav had previously confirmed to me that these files should not be used anymore.  CI should be able to build successfully without these.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I think removing these means that these can also be removed:
* cmake/helper_subdir/CMakeLists.txt
* cmake/helper_subdir

And this section from cmake/Modules/ObsHelpers.cmake:
https://github.com/obsproject/obs-studio/blob/63bcc54b32bccdf0b5f79d1b6a0719e301bb7194/cmake/Modules/ObsHelpers.cmake#L114-L123

**Comment by PatTheMav** [comment]
Yeah that whole stuff wasn't used in ages.

**Comment by RytoEX** [comment]
> 
> 
> Yeah that whole stuff wasn't used in ages.

Including the additional stuff I linked to?  I'm pretty sure all of that is safe to remove.

**Comment by PatTheMav** [comment]
> > Yeah that whole stuff wasn't used in ages.
> 
> Including the additional stuff I linked to? I'm pretty sure all of that is safe to remove.

For bundling only resources contained in `CI/scripts/macOS/` are used, the old shell script and cmake functions haven't been used for a long time (iirc the prior build scripts even took over that duty).

You'd also need to remove this line in the main `CMakeLists`:

https://github.com/obsproject/obs-studio/blob/dc2b00a4dd6669447742500ecd90ef8c3e0c342f/CMakeLists.txt#L280

**Comment by RytoEX** [comment]
> You'd also need to remove this line in the main `CMakeLists`:

Yep, mentioned that in edits to my earlier comment.  I figure I should just put it all in one PR to prevent further confusion.

**Comment by RytoEX** [comment]
I've removed the files and sections mentioned in [my earlier comment](https://github.com/obsproject/obs-studio/pull/4556#issuecomment-822496896).

**Comment by MrBenFTW** [comment]
This merge is what was causing my issue!

I am trying to build manually for M1, using cpack. but you have removed osxbundle and so now I have cpack errors

**Comment by MrBenFTW** [comment]
By undoing your merge manually I was able to use cpack and pack a M1 build 
image
image

Left = Intel 
Right = M1 Custom build

**Comment by PatTheMav** [comment]
Packaging with CPack hasn't been supported in a very long time and the associated files (removed with this PR) were heavily outdated as well - if you look at the build script as well as the CI workflow you'll find how we prepare and fixup the app bundle (e.g. using `dylibbundler` to gather dependencies).

**Comment by MrBenFTW** [comment]
> (e.g. using `dylibbundler` to gather dependencies).

The reason I am manually running cmake and cpack is because I am using self built dependencies and not the pre built ones. The build script uses prebuilt dependencies, is there a way to tell it not to?

**Comment by MrBenFTW** [comment]
This is what I get if I use the `-d` option 

```
benmitchell@Scylla obs-studio % ./CI/full-build-macos.sh -b -p -d
  + Fetching OBS tags...
[OBS-Studio] Run CMAKE for OBS...
-- OBS_VERSION: 27.0.0-rc5-1-g924d9a7d9-modified
-- No Native SSE2 SIMD Support - Using SIMDE
-- Failed parsing FFmpeg avcodec version
-- Failed parsing FFmpeg avdevice version
-- Failed parsing FFmpeg avutil version
-- Failed parsing FFmpeg avformat version
-- Scripting: Luajit supported
-- Python support not found.
-- Command "/tmp/obsdeps/bin/swig -swiglib" failed with output:

CMake Error at deps/obs-scripting/CMakeLists.txt:94 (include):
  include called with wrong number of arguments.  include() only takes one
  file.


CMake Error at /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FindSWIG.cmake:99 (message):
  Command "/tmp/obsdeps/bin/swig -swiglib" failed with output:

Call Stack (most recent call first):
  deps/obs-scripting/obslua/CMakeLists.txt:13 (find_package)


CMake Error at deps/obs-scripting/obslua/CMakeLists.txt:14 (include):
  include called with wrong number of arguments.  include() only takes one
  file.


CMake Error at deps/obs-scripting/obslua/CMakeLists.txt:29 (SWIG_ADD_LIBRARY):
  Unknown CMake command "SWIG_ADD_LIBRARY".


-- Configuring incomplete, errors occurred!
See also "/Users/benmitchell/obs/obs-studio/build/CMakeFiles/CMakeOutput.log".
See also "/Users/benmitchell/obs/obs-studio/build/CMakeFiles/CMakeError.log".
benmitchell@Scylla obs-studio %
```

**Comment by PatTheMav** [comment]
In your case it's probably easiest to also use the `-s` switch, which skips building OBS. It should only create an app bundle (and with `-p` provided the disk image).

As long as the script finds a successfully compiled OBS in the default locations (you can specify a different `BUILD_PATH` env variable iirc), it should work.

**Pull request merged**
