### PR TITLE
More 30 cherry-picks

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Cherry-picks commits from master that aren't on release/30.0 yet but probably should be.
In particular, the commits from the following PRs:
- https://github.com/obsproject/obs-studio/pull/9726
- https://github.com/obsproject/obs-studio/pull/9763
- https://github.com/obsproject/obs-studio/pull/9762
- https://github.com/obsproject/obs-studio/pull/9710
- https://github.com/obsproject/obs-studio/pull/9768
- https://github.com/obsproject/obs-studio/pull/9730
- https://github.com/obsproject/obs-studio/pull/9747
- https://github.com/obsproject/obs-studio/pull/9742

Pending questions: #9747 is also marked with the milestone, but not a bug fix. Should that be included as well?
Same with #9742, but that's only a cleanup which isn't really needed (unlike we want branches to not diverge too much).

### Motivation and Context

Would like to see the mac-virtualcam fix in the next RC, and creating a PR increases the chance of that happening.
Included the other bug fixes while I was at it.

### How Has This Been Tested?

macOS 14, clean-rebuilt the branch and ran.
Made sure the essentials (recording, streaming, basic sources) still work.
All the commits have been tested as part of their original PRs.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Please include these in the appropriate order:
* #9710 (https://github.com/obsproject/obs-studio/commit/48e239b74daf814856c328cea49080ef4a93ced9)
* #9747 (https://github.com/obsproject/obs-studio/commit/d017cb67180b935574bf9265b81ba0a45c247f21)
* #9742 (https://github.com/obsproject/obs-studio/commit/ba4467199c576d977092fd0e6e84f9a4f62159e9)

> Pending questions: #9747 is also marked with the milestone, but not a bug fix. Should that be included as well?
> Same with #9742, but that's only a cleanup which isn't really needed (unlike we want branches to not diverge too much).

#9747 will be helpful for troubleshooting/support purposes and is trivial.
#9742 is a trivial code cleanup that only affects macOS.

**Review by RytoEX — APPROVED** [review]
Looks good to me. I still want #9767 to eventually make it to the release/30.0 branch, but that need not hold this up.

**Comment by RytoEX** [comment]
#9767 (https://github.com/obsproject/obs-studio/commit/20ffdda89a4590dc0e44f6a2f703abda9b4a2d45) has been merged, so please add that as well.

**Comment by gxalpha** [comment]
Added

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
