### PR TITLE
rtmp-services: Add SharePlay.tv

### PR DESCRIPTION
**Pull request by nickg-sp**
### Description

Add [SharePlay.tv](https://www.shareplay.tv) to rtmp services list.

### Motivation and Context

Add support for "SharePlay.tv" in rtmp services.

### How Has This Been Tested?

Local Build & CI Build

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please update the commit message, but this is otherwise approved.

**Comment by katahtonic** [comment]
Hi, is this something that we (as SharePlay devs) have to do before the merge is executed? just want to make sure you're not waiting on us for this

**Comment by Fenrirthviti** [comment]
Yes, your commit message does not follow our guidelines. It should be something like `rtmp-services: Add SharePlay.tv` instead.

**Comment by katahtonic** [comment]
Please let us know if there are further issues, we'll happily modify as needed.

**Comment by RytoEX** [comment]
> Please let us know if there are further issues, we'll happily modify as needed.

It must be as @Fenrirthviti wrote originally:
```
rtmp-services: Add SharePlay.tv
```

Commit message titles are in present tense, as mentioned in our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/6af9ae6c87fabfde662fb468d93ea3941ca11656/CONTRIBUTING.rst#commit-guidelines).

**Review by RytoEX — CHANGES_REQUESTED** [review]
> Please let us know if there are further issues, we'll happily modify as needed.

The commit message must be as @Fenrirthviti wrote originally:
```
rtmp-services: Add SharePlay.tv
```

Commit message titles are in present tense, as mentioned in our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/6af9ae6c87fabfde662fb468d93ea3941ca11656/CONTRIBUTING.rst#commit-guidelines).

Also, do not end a commit message subject with punctuation.

**Comment by katahtonic** [comment]
Thank you for clarification. We've updated to the desired formatting

**Comment by katsacca** [comment]
Hi there, we've updated to the desired formatting. Please let me know if there are any further requirements and we'll rectify it promptly.

**Comment by katahtonic** [comment]
Hi there, we've updated to the desired formatting. Please let me know if there are any further requirements and we'll rectify it promptly.

**Comment by Drkcyber** [comment]
@RytoEX @WizardCM @Fenrirthviti Hi guys just checking in to see if everything requested has been met or does our team still needs to do anything else to meet your commit standards.

**Comment by RytoEX** [comment]
@Drkcyber @katahtonic @nickg-sp I'd like to ask for a little patience. We're in the middle of beta testing OBS Studio 30.1 as well as many other tasks. Services updates are handled as time allows. This has been assigned to me, so it _will_ get done at some point, but for now my time is prioritized towards OBS Studio 30.1 related tasks. Thank you for your understanding.

**Review by Fenrirthviti — APPROVED** [review]

**Review by RytoEX — APPROVED** [review]
Build failure is unrelated. In the future, do not submit multiple commits in a single PR to make additional changes after first submitting. Instead, just amend the existing commit and force push.

**Pull request merged**
