### PR TITLE
UI: Fix missing tab in locale

### PR DESCRIPTION
**Pull request by Vainock**
Without this tab, the descriptions aren't on the same level.

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
Maybe I'm blind but I don't see an issue here.
Screenshot_20190531-230056~01

**Comment by Vainock** [comment]
Have you also the newest build with the newest en_US? I have tested it and there occured the issue...

**Comment by Vainock** [comment]
The newest version looks like this:
image

**Comment by Gol-D-Ace** [comment]
You tested the RC
I tried a master build.

**Comment by Vainock** [comment]
Yeah, there was a change in this text, and sorry for the typo.

**Comment by jp9000** [comment]
This is what I get with your PR:
obs64_2019-06-01_18-04-16

Without it, it looks normal and the position is correct.  There's something else going on here.

**Comment by Vainock** [comment]
Is it somehow possible that the tabs will be formatted based on the display size and other informations? Because I do it on a little laptop thats not 1080x1920:
1 tab:
1Tab
2 tabs:
2Tab
3 tabs:
3Tab

It's completely unexplainable for me...

**Comment by jp9000** [comment]
I definitely am not sure what's going on here.  If I were in your position and had that problem I probably would have made the PR too.  I'm just not sure why you're getting different results than us however.

**Pull request closed without merging**
