### PR TITLE
Disable dynamic bitrate support for NVENC and QSV

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Unfortunately NVENC and QSV tend to crash or freeze after after multiple bitrate changes. Users with dynamic bitrate enabled experience a random encoder freeze which manifests as OBS dropping to 0kb/sec and disconnecting and it's not at all obvious that dynamic bitrate is the cause.

Disable it for now until we can figure out if there is any workaround or bug on our end.

### Motivation and Context
Users having their streams drop to 0kb/sec for no obvious reason is not good.

### How Has This Been Tested?
Trivial change to mark the encoders not compatible. Was not tested.

### Types of changes

- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
I disagree with this change - dynamic bitrate itself isn't at fault, nor is our encoder implementation. The encoders themselves simply don't like frequent bitrate changes (especially at large intervals).

The best solution would be to slow how often the bitrate can change on hardware encoders.

**Comment by MattyFresh68** [comment]
> I disagree with this change - dynamic bitrate itself isn't at fault, nor is our encoder implementation. The encoders themselves simply don't like frequent bitrate changes (especially at large intervals).
> 
> The best solution would be to slow how often the bitrate can change on hardware encoders.

I 2nd this thought.

**Comment by SuslikV** [comment]
The forum had one thread that mentions the crash under the similar conditions:
https://obsproject.com/forum/threads/please-help-rtmp-send-error-live-from-youtube-falling.146733/
it is more like the encoding fails on 4-th (or 5-th, or more) bitrate change.

**Comment by notr1ch** [comment]
I've done some additional debugging on this. DBR with hardware encoders is indeed flawed, every bitrate change event has a chance to freeze the encoder due to thread re-entrancy issues. So it's pure luck if it's working for anyone in its current state.

I will make an additional PR soon to revert this change and commit a proper fix.

**Pull request merged**
