### PR TITLE
rtmp-services: Add LiveXP streaming service

### PR DESCRIPTION
**Pull request by streamdealer**
### Description
Add LiveXP streaming service

### Types of changes
Add new streaming service
Update rtmp-sevices version of services.json

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Can you please provide the service main URL so that this can be tested before merging? Thanks!

**Comment by streamdealer** [comment]
> Can you please provide the service main URL so that this can be tested before merging? Thanks!

I already tested the settings.
Service url - https://livexp.com/

**Comment by streamdealer** [comment]
@Fenrirthviti is everything ok with the pull request?

**Comment by Fenrirthviti** [comment]
I have been monitoring this site for a full week now, since this PR was submitted. During that time, I have not seen anyone past a single QA engineer streaming to it. It is my recommendation that we do not include this in OBS. Users can still enter the RTMP URL manually by using custom rtmp service, and will still be able to use OBS. At such time where this service gains a sufficient userbase to warrant consideration of inclusion in OBS, feel free to submit a new PR.

**Pull request closed without merging**
