### PR TITLE
docs: Add property functions

### PR DESCRIPTION
**Pull request by CodeYan01**
### Description

Add undocumented property functions.

`obs_property_text_monospace` only having an effect on multiline
text properties were something I noticed by testing myself, so
correct me if I'm wrong.

### Motivation and Context

Missing documentation for functions

### How Has This Been Tested?

Built and viewed locally. 

### Types of changes

 - Documentation (a change to documentation pages)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Some odd line breaks, but otherwise seems fine. @gxalpha ? @WizardCM ?

**Comment by CodeYan01** [comment]
> Some odd line breaks
like which ones? If you are referring to line breaks like this:
image
it should not have an effect on the actual output, but I'm open to moving the line breaks to where they should be.

**Comment by RytoEX** [comment]
> > Some odd line breaks
> 
> like which ones? If you are referring to line breaks like this: image it should not have an effect on the actual output, but I'm open to moving the line breaks to where they should be.

Yes. I was just wondering why they are line wrapped at something lower then 80 or 100 characters (whatever is commonly used in the documentation). It seemed like an odd choice when there should already be a specified column limit.

**Comment by CodeYan01** [comment]
I sorta fixed the line breaks. There isn't really any established column limit in the docs that I'm aware of, and different documentation files have different limits, especially considering the function declarations that aren't even wrapped.

**Comment by PatTheMav** [comment]
@RytoEX probably good to merge, haven't seen any objections from others yet.

**Comment by RytoEX** [comment]
> Add undocumented property functions. In the `obs_properties_add_button`, I replaced `description` with `text` because there's no such param.

This change doesn't seem to be present here anymore.

> Please check the description I put for `priv`, since I can't test it myself since it's not accessible in python scripting.

This change doesn't seem to be here either.

> `obs_property_text_monospace` only having an effect on multiline text properties were something I noticed by testing myself, so correct me if I'm wrong.

The commit adding `obs_property_text_monospace` says that it was added for multiline text and the `if` block where it is checked is within an `if` for `type == OBS_TEXT_MULTILINE`, so this seems correct.
https://github.com/obsproject/obs-studio/commit/62504dc651c75996890cdb1c3a43bc99cafa5768

**Comment by CodeYan01** [comment]
PR description updated, commit description is just the title so there's nothing to update. 

Those changes are indeed gone now, as another PR already fixed those.

Thanks for confirming the info about multiline.

**Review by RytoEX — APPROVED** [review]
Looks good to me.

**Pull request merged**
