### PR TITLE
obs-webrtc: Improve error messages on HTTP failure

### PR DESCRIPTION
**Pull request by jech**
### Description

Log the libcurl-provided error message when libcurl fails.

### Motivation and Context

Without the libcurl error message, it is very difficult to debug issues.

### How Has This Been Tested?

Against [Galene](https://galene.org)

### Types of changes

Adds logging.

### Checklist:
* [x]  My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
* [x]  I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
* [x]  My code is not on the master branch.
* [x]  The code has been tested.
* [x]  All commit messages are properly formatted and commits squashed where appropriate.
* [x]  I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Please fill in the PR template, read our [contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) (your commit title is incorrectly formatted), and fix the clang-format failure.

**Comment by jech** [comment]
> Please fill in the PR template, read our [contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) (your commit title is incorrectly formatted), and fix the clang-format failure.

Done.

**Comment by tt2468** [comment]
The CURL documentation for `CURLOPT_ERRORBUFFER` suggests explicitly initializing the first byte of the error array: `errbuf[0] = 0;`

Did you determine this to not be necesssary? I think we should use `char error_buffer[CURL_ERROR_SIZE] = {};` to initialize the array as all null.

**Comment by jech** [comment]
> The CURL documentation for `CURLOPT_ERRORBUFFER` suggests explicitly initializing the first byte of the error array: `errbuf[0] = 0;`

Done.

> Did you determine this to not be necesssary?

I believe this is only required in order to remain compatible with libcurl versions older than 7.60.0.

**Review by tt2468 — APPROVED** [review]

**Pull request merged**
