### PR TITLE
obs-ffmpeg: Implement QVBR for AMF encoders

### PR DESCRIPTION
**Pull request by flaeri**
### Description
Implement QVBR rate control for all AMF encoders. Also fixes an incorrect if check for rate control on line 1457. Switch UI from bitrate to CQ/QP value (no bitrate needed for QVBR).

When the new rate controls were added, nothing was done to acommodate this rate control, which requires a "quality value". This change makes the rate control usable. ref: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Rate%20Control%20Methods#quality-based-variable-bitrate-qvbr

#### NOTE
The scale goes in the opposite direction of what one might expect. Low values produce low qualty (6 would be poor), high values are high quality (say 46). The scale goes from 1-51 (same as CQP)

### Motivation and Context
Want rate controls avaliable to the users to work correctly.
Fixes https://github.com/obsproject/obs-studio/issues/8237

### How Has This Been Tested?
Log: https://obsproject.com/logs/niar4afkeX5CvbzG

Tested H264 texture and fallback encoder, using a low values (low quality), and a high values (high quality). Both produce expected output, and does not lag.

HEVC unfortuantely does not work for me. It will throw an error on release, master and with this PR. Also does not work in AMDs example code/software (TranscodeHW). I believe this is an issue that lies with AMD. Once fixed upstream, it should in theory work fine (I hope). See open issue: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/366

HEVC works for some users, and I got help from MattyFresh in the discord, and got confirmation that it works, and the Quality level is correctly set (low value, small file etc). Log: https://obsproject.com/logs/B1Mqgfe23OZr3AUq

I cannot test AV1, as I do not have a capable chip, and I would ask people with compatible hardware to help me confim that it works as expected.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by flaeri** [comment]
Forgot one thing.
Fixes https://github.com/obsproject/obs-studio/issues/8237

**Comment by flaeri** [comment]
I got some help from MattyFresh to check HEVC QVBR on their chip, and apparantly it works for them.
https://obsproject.com/logs/B1Mqgfe23OZr3AUq

**Comment by RytoEX** [comment]
On an RX 6600M, on the previous stable drivers (31.0.12029.10015 / 22.11.2), I get the following when selecting QVBR:
```
[texture-amf-h265: 'advanced_video_recording'] Failed to set property 'HevcRateControlMethod': AMF_INVALID_ARG
[texture-amf-h265: 'advanced_video_recording'] Failed to set property 'HevcQvbrQualityLevel': AMF_INVALID_ARG
```
The recording happily continues anyway.

On the current stable drivers (31.0.14033.1012 / 23.2.2), the recording starts without those logged warnings, but the recording did take a few seconds to actually start.

**Review by RytoEX — APPROVED** [review]
Seems fine.

**Pull request merged**
