### PR TITLE
UI: Fix theme leak

### PR DESCRIPTION
**Pull request by pkviet**
### Description
This fixes leaks when loading and switching themes.

### Motivation and Context
Leaks are bad.
This leak was detected with Visual Leak Detector.

### How Has This Been Tested?
Run obs with VLD; check that the leak is gone after changing a theme.

### Types of changes
 - Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
Is there a reason `themeMeta` is part of `OBSApp`? As far as I can tell, the only place it is used is within `OBSApp::SetTheme`, so there doesn't appear to be a need to keep it around after the function exits.

**Comment by pkviet** [comment]
Good point, i'll move the delete then

**Comment by notr1ch** [comment]
I was thinking more about removing it from the class and having it as a local stack variable.

**Comment by pkviet** [comment]
updated to follow @notr1ch advice; this is much cleaner, thx !

**Comment by pkviet** [comment]
> I was thinking more about removing it from the class and having it as a local stack variable.

Ah i see. I'll let Matt fix that since he authored that code. 
Dunno what's the reason indeed to have the var in the whole class.

**Comment by pkviet** [comment]
Changed to a unique_ptr; we'll see if Matt was thinking of using the var elsewhere in future code.

**Pull request merged**
