### PR TITLE
obs-ffmpeg: Fix nvidia compat ver missing definition

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Description
Some nvidia compat definitions were missing, this change adds them

### Motivation and Context
nvidia encoder on some machines may fail to start

### How Has This Been Tested?
I have test on windows 10 19045.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
None of these define a different version than what's in the currently supported NVENC headers.

**Comment by wanhongqing123** [comment]
你的邮件已收到，我会尽快的回复你

**Comment by RytoEX** [comment]
As @derrod has said, none of these should be necessary. Are you actually running into a specific issue without these defined? I've double checked and none of these struct versions has changed between SDK 11.1 and 12.1.

**Comment by wanhongqing123** [comment]
I found that some definitions use Compat, and some still use definitions in NVIDIA header files. I think this will make the file more confusing, so I think it is better to unify it. If the driver version is the same as the version on the actual machine, use Compat, otherwise use the definition in the NVIDIA driver @RytoEX @derrod

**Comment by RytoEX** [comment]
> I found that some definitions use Compat, and some still use definitions in NVIDIA header files. I think this will make the file more confusing, so I think it is better to unify it. If the driver version is the same as the version on the actual machine, use Compat, otherwise use the definition in the NVIDIA driver @RytoEX @derrod

It really doesn't matter. The struct versions haven't changed, so this is effectively a no-op.

**Comment by derrod** [comment]
Closing as per above, this is pointless.

**Pull request closed without merging**
