### PR TITLE
UI: Change advanced networking strings 

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This changes "Enable new networking code" to "Enable network optimizations"

### Motivation and Context
This makes the option less confusing.

### How Has This Been Tested?
Nothing to test, just a string change.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
We should likely also change the `low-latency mode` wording as well.

@notr1ch might have a suggestion on a better phrasing for that. There's confusion that enabling it will lower latency of the stream from OBS, when that is not the intended result.

**Comment by notr1ch** [comment]
If we're OK with using a technical name for it (it is an advanced option after all), "Enable TCP Pacing" might be more appropriate.

**Comment by Fenrirthviti** [comment]
We can add a hover description as well with that and I think that's sufficient. Could you write a small description for that?

**Comment by notr1ch** [comment]
> Attempts to make RTMP output friendlier to other latency-sensitive applications on the network by regulating the rate of transmission. May increase the risk of dropped frames on unstable connections.

**Comment by cg2121** [comment]
I've now changed the low latency string to "TCP pacing" and added a tooltip.

**Comment by Fenrirthviti** [comment]
Sorry to nitpick, but can it be "Enable TCP Pacing" for consistency with other options across OBS?

**Comment by cg2121** [comment]
I've now changed it to "Enable TCP pacing"

**Pull request merged**
