### PR TITLE
UI: Enforce Fusion Qt style on Linux

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Found the issue on Linux, the Plasma default theme Breeze also provide a Qt style plugin.
This plugin add a frame to QDockWidget.
Those frames are not stylable with QSS because those are drawn with QPainter.
- https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezestyle.cpp#L1555
- https://github.com/KDE/breeze/blob/4222e8e83ae870ffb1ccc3c02775681322f62b88/kstyle/breezehelper.cpp#L457

Flatpak install is always affected because the KDE Runtime provide Breeze, and Linux systems with Breeze installed are also affected for non-Flatpak install

So to avoid this the base style is enforce to the Qt default style on Linux: Fusion.

Screenshot made with #2778 

Without the PR:
Thanks_Qt_and_Breeze

With the PR:
Thanks_Fusion

### Motivation and Context

I want Yami to be nice on Linux and Qt doesn't want me to be happy.

### How Has This Been Tested?

- Run without the commit: frames around docks
- Run with the commit: no frames around docks

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by SuslikV** [comment]
Maybe stupid question... Will work the QApplication setStyle QStyleFactory create("Fusion") sequence for OBS only, but not for every Qt application installed in the system? I don't like the global env vars.

**Comment by tytan652** [comment]
> Maybe stupid question... Will work the QApplication setStyle QStyleFactory create("Fusion") sequence for OBS only, but not for every Qt application installed in the system? I don't like the global env vars.

This will try to apply Fusion over Breeze by "merging" them because the base style is already Breeze. To avoid Breeze to be used as base style this env var is unfortunately necessary.

**Comment by WizardCM** [comment]
While I overall agree with this change due on limitations in the Qt API, the only downside of this change is that for users who use the System theme, it may no longer look like their system if a custom style is applied automatically.

**Comment by tytan652** [comment]
The `System` theme on Linux:
- Will be Breeze or Fusion in Flatpak, so this change is minor on Flatpak
- Is expected to generate bizarre style and to not work really well with dark system theme (like OBS icons still black).

We could:
- Keep `System` and consider it as a Fusion style
- Remove the `System` theme on Linux build
- Rename it to Fusion on Linux

**Comment by jp9000** [comment]
If this affects KDE only, is there a way to only turn this on when KDE is active? Or do we need to have this on gnome as well?

**Comment by tytan652** [comment]
This issue is related to Breeze Qt style plugin which is DE-agnostic, it will affect:
  - every Flatpak installation because of the KDE Runtime.
  - every user that have Breeze installed and use it on their system as Qt default Style.

So the only way is to enforce Qt's default: Fusion. User can still override it if they want to on non-Flatpak install.

**Comment by jp9000** [comment]
Ah okay, I think I misunderstood originally then. Linux is definitely not my expertise.

**Comment by dimtpap** [comment]
This is how Yami looks for me without this PR
image
and then with this PR
image

**Comment by GloriousEggroll** [comment]
This commit causes OBS to not follow Gnome's theming if breeze is installed.

Here is my setup:
> I'm using GNOME
> I have the breeze packages installed because Kdenlive needs them to display properly
> I launch OBS with this commit -- my theme is in dark 
Screenshot from 2022-07-25 22-13-59
mode but OBS's bar is bright white:

If I revert the commit, OBS behaves:
Screenshot from 2022-07-25 22-25-13

**Comment by tytan652** [comment]
Breeze have nothing to do with that, you are actually defaulting to Qgnome (`QT_STYLE_OVERRIDE=gnome`) another Qt Style made by Fedora IIRC which seems to manage the decoration bar theme.

Qt doesn't provide a way to avoid breeze if this is installed and will be used. The only solution to always avoid Breeze is to enforce Fusion.
I don't even know if other Qt Style "break" OBS themes.

The user still can set `QT_STYLE_OVERRIDE` and OBS will not override it. Feel free to used that.

**Comment by GloriousEggroll** [comment]
thanks for the tip -- i resolved this by removing:
qgnomeplatform-qt5
qgnomeplatform-qt6 
from my system after your tip

**Comment by tytan652** [comment]
The Breeze Qt style is DE-agnostic, son it's not a question of Boeing on Plasma or GNOME.

I'm on GNOME and I have this issue.

**Pull request merged**
