### PR TITLE
UI: Remove unnecessary loop in ClearListItems

### PR DESCRIPTION
**Pull request by craftwar**
clear() will delete all items

### CODE REVIEW

**Comment by jp9000** [comment]
Actually there should have been a comment in the code.  The reason why the item widgets are deleted manually like this is because ::clear() will cause them to delete via QObject::deleteLater(), which basically puts the deletions on the Qt queue to be deleted at a later time (and thus leaving internal OBS references dangling past their intended deletion point).  So to fix that, I deleted manually.  I can understand the misconception however -- there really should be a comment in the code.  I have no excuse for not having a comment there really.

**Comment by craftwar** [comment]
Will it delete the same item twice and make OBS in uncertain state?

**Comment by craftwar** [comment]
nvm, I will submit another patch. Still better than current one.

**Comment by jp9000** [comment]
Just to answer your question -- the item widget object uses references to sources.  So basically, to ensure that the references are released before the intended shutdown time, we have to explicitly delete the item widget on the spot.  It's very annoying and sort of an implicit funciton of Qt when it uses deleteLater() behind the scenes because it doesn't allow you to control the timing of the destruction/cleanup of objects.

When deleteLater() is used and you for example switch between scene collections, sources from the previous scene collection will still have references when you switch to the new scene collection.  When exiting obs, sources will still have dangling references waiting to be deleted with the item widget on the Qt queue when obs_shutdown() is called.  The item widget "deleteLater()" functionality of item views is very frustrating when you need references to be released immediately.

**Pull request closed without merging**
