### PR TITLE
UI: Implement system tray icon for when the recording is paused

### PR DESCRIPTION
**Pull request by Programatic**
### Description
Simply changes the tray icon to a paused symbol when the recording is paused.
image.

### Motivation and Context
It implements [this ideas request](https://ideas.obsproject.com/posts/633/pause-marker-on-the-obs-symbol-in-system-tray). It is just a nice quality of life change for people who use OBS to record and frequently use the hotkeys.

### How Has This Been Tested?
I tested it on my Windows 10 OS.
EDIT: Also tested on my linux OS. Running 5.4-rc1 with i3 gaps

### Types of changes

 - New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I'm not sure I like the green, can you update to show red or yellow for comparison? Those are what is typically used to indicate paused, not green.

**Comment by DDRBoxman** [comment]
Also it should probably be styled to match the active icon

https://github.com/obsproject/obs-studio/blob/master/UI/forms/images/tray_active.png

**Comment by Programatic** [comment]
@Fenrirthviti Yeah, I agree. I am no graphic designer but I tried a couple colors and didn't think they really stood out well enough. Anyways, here is yellow with @DDRBoxman's suggestion: 
image
Here is red: 
image

Personally, I think the yellow stands out much better between the 2 so I'll just push that.

**Comment by Xaymar** [comment]
Is it possible to change the red dot into a yellow pause symbol instead? I think that is supposed to be the original recording indicator, so it makes sense to modify that instead.

**Comment by Programatic** [comment]
I tried to do that initially, but it was way too small to properly distinguish (which is why I did the pause symbol over the whole icon). Maybe we could use a yellow dot instead? I'll update with a picture later when I get back.

**Comment by dodgepong** [comment]
This may sound silly, but could we make the pause icon blink while paused? That might make it a bit more noticeable.

**Comment by Programatic** [comment]
Ok, I added the icon to flash when it is paused. I am not really familiar with QTimer so if someone could just make sure I am not doing anything evil, that would be appreciated

**Comment by jpark37** [comment]
I think blinking goes against the style guideline to not flash the icon. I think having pause be a sub-icon would be better; maybe the subicons just need to be a little bigger?

Also I haven't looked at the qtimer change, but I just imagine it's much more likely to bug out than not having it, and if we end up showing the wrong icon for a situation, that could lead to very angry users.

**Comment by Programatic** [comment]
I can understand the not blinking, but what do you mean by a sub icon. I'm not exactly sure what you are describing

**Comment by jpark37** [comment]
Maybe something like this:
image

**Comment by Programatic** [comment]
Ohhh. Yeah, that's how I originally had it but it was hard to make out. I'll work on it and see if I can make it better. Also, I'll revert the blinking

**Comment by Programatic** [comment]
Ok, I took out the blinking with the QTimer. Also changed the image to:
image
This is on my Linux machine. If everything is good, then I will go ahead and squash the commits.

**Comment by COOLIGUAY** [comment]
If the replay buffer or streaming are started (or both) and you stop recording while it's paused, the new pause tray icon is still displayed.

It does not disappear until the replay buffer and streaming also stops.

Is this how it is intended to work?


image

image

image

Sorry if it is not the right place to make this comment.

**Comment by jp9000** [comment]
Perfectly fine to post it here.  Thanks for the report.

**Comment by jp9000** [comment]
Should be fixed now.

**Comment by COOLIGUAY** [comment]
Thank you Jim!

I have tried this with the last nightly:

Start Replay Buffer or Streaming
Start Recording
Pause Recording
And finally Stop Replay Buffer or Streaming

The recording is still paused, but icon changes to the obs recording logo.

image

**Comment by Programatic** [comment]
I'll fix this when I get back soon.

**Comment by gitalexhubuser** [comment]
How to speed up adding this feature? (icon pause\record)
It takes near 5 months :((

Now is 24.0.3

**Comment by Programatic** [comment]
Thos feature has already been merged and will probably be included in the next release. When that is, I'm not sure.

**Pull request merged**
