### PR TITLE
libobs: Optimize gain application w/ SSE instructions

### PR DESCRIPTION
**Pull request by Andersama**
Muliply 4 samples at a time w/ SSE.

### CODE REVIEW

**Comment by TheMuso** [comment]
Am I reading that changed code correctly, or is the volume multiplication being done twice in both circumstances, once using SSE, and then once without?

Secondly, I wonder whether it would make more sense to have a common public/exported method to do volume processing. The audio monitoring code also does volume processing, and all 3 monitoring implementations have their own code, PulseAudio's code being slightly different in that volume processing needs to be done for types other than float. Surely it would make sense to change all volume processing code to using one method which can then be optimized appropriately.

**Comment by TheMuso** [comment]
Ok, on second look I can see why the original code was left there.

My second query still stands about having one volume process method for all instances throughout obs.

**Comment by TheMuso** [comment]
Clearly I am not yet awake enough... I see those volume implementations are slightly different as well.

I'll just keep quiet. :)

**Comment by kkartaltepe** [comment]
Why is this necessary? I would expect any compiler to vectorize this code and a trivial example shows that GCC is highly likely to do such already.
https://godbolt.org/g/MV7Hv2

Is it actually the case that the real build of OBS does not vectorize this operation? (by not doing this we gain the added benefit of easily vectorizing using longer SSE instructions by simply targeting higher SSE/AVX compatibility levels, or allow downstream projects to do such without any code changes)

**Comment by Andersama** [comment]
From my playing around w/ this, the MSVC compiler was not optimizing these instructions, but I couldn't tell of any performance improvements. Guys in the discord brought those issues.

**Pull request closed without merging**
