### PR TITLE
Windows Graphics Capture support

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Users will now have the option of legacy window capture via BitBlt, or
Windows Graphics Capture, which is new to Windows 10.

There are two annoyances with the new capture method though. One is that
there is a bright, yellow border added to the original window (but not
the OBS view of it). The other is that the mouse cursor is always
captured, and we won't be able to capture without cursor until a later
version of Windows 10 is released.

It should also be noted that DPI scaling is now applied, which may
result in blurrier images caused by Windows rescaling.

### Motivation and Context
Works with hardware-accelerated Chrome. UWP apps also work with the new method.

### How Has This Been Tested?
Scenarios tested:

- Show/Hide
- Multiple WGC captures
- Multiple BitBlt captures
- Toggle between WGC and BitBlt settings
- WGC / BitBlt capture mix
- Can't select WGC on Windows 7 and Windows 10 1809, OBS handles WinRT module load failure gracefully.
- Can't select if OpenGL renderer is used.
- BitBlt fallback if window has WGC setting somehow
- Handle graphics thread recreation if video settings are touched with multiple WGC sources active
- Handle D3D device loss
- Handle window resize
- Handle window close and latch on reopen
- Hardware-accelerated Chrome (works on WGC [BitBlt implementation may be bugged])
- Netflix UWP app (works on WGC [BitBlt implementation may be bugged])

Using QPF markers for CPU measurement, WGC tends to be a bit more expensive than BitBlt and wider variance, maybe 200-800 us vs 300-500 us. The new PeekMessage loop is very cheap when empty, about 0.2 microseconds.

WGC appears to be a bit cheaper than BitBlt on GPU just looking at Task Manager percentage, but it's hard to tell with the noise.

Since this feature is optional, and there's not much I can do to optimize these OS functions, I'm not too concerned about performance.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jpark37** [comment]
Need to switch Windows SDK over to 10.0.18362.0 for this PR to build.

**Comment by derrod** [comment]
It would appear that the old image Azure CI is currently using does not contain the latest Windows 10 SDK. Could you try changing https://github.com/obsproject/obs-studio/blob/master/azure-pipelines.yml#L64 and https://github.com/obsproject/obs-studio/blob/master/azure-pipelines.yml#L64 to `windows-2019`?

**Comment by jpark37** [comment]
The windows-2019 image does not appear to have VS 2017 installed.

**Comment by derrod** [comment]
I noticed that the new capture method stops working when changing OBS' frame rate in the video settings. The yellow border is still shown but the frame within OBS stops updating.

**Comment by jpark37** [comment]
I hadn't realized OBS could recreate the graphics thread behind the sources backs until now. Added shenanigans handling, so changing video settings should work now.

**Comment by jpark37** [comment]
Obviously, testing can have a never-ending list of permutations, but I am satisfied that I more or less have the basics covered.

The only thing holding me back from switching this out of draft status is the build situation. At a minimum, we need VS 2017 + Windows 10 SDK 10.0.18362.0 to compile this PR, but maybe we should move up to VS 2019 if that makes things easier for Azure.

**Comment by Gol-D-Ace** [comment]
Getting the SDK available and being used by VS2017 is probably more pain than just switching to VS2019 which includes the newer SDK version.

**Comment by derrod** [comment]
Not sure if we're going to retire AppVeyor as well but for now we'd have to update it to the vs2019 image as well.

**Comment by jpark37** [comment]
Also, can we bump up to CMake 3.16? The recently added support for precompiled headers, and it reduces compile time for this PR from 6 seconds to less than a second.

**Comment by jpark37** [comment]
The obs executable project would also likely benefit from PCH. Takes about 100 seconds to compile single-threaded.

**Comment by jp9000** [comment]
It's fine to change the required cmake version -- as long as there are no issues with it of course.

**Comment by jpark37** [comment]
CMake 3.16 is fairly new (last week), so it's not available in standard repositories. Homebrew has 3.15.5, and Ubuntu 19.10 has 3.13.4 for example. Someone would have to install it on the builders manually if we want it sooner.

**Comment by jp9000** [comment]
Perhaps you could make it required for this specific module and not necessarily the entire project?

**Comment by jpark37** [comment]
What's "it"? Do you mean PCH on the libobs-winrt module, so we only have to update CMake for Windows, and defer Mac/Linux?

**Comment by jpark37** [comment]
The PCH change isn't in this PR by the way. It's in a separate stash for the moment, so that's not a blocker, just annoyingly slow to compile. We just need VS 2019 to make this PR work.

**Comment by jp9000** [comment]
Sorry, meant to say perhaps we could isolate the cmake requirement bump to this particular subproject (or at least windows somehow).  I would definitely prefer not to have to deal with linux/mac package issues.  That's pretty much all I was meaning

**Comment by jpark37** [comment]
I pushed the PCH change, and it's already isolated from the Mac/Linux builds since the entire libobs-winrt directory gets ignored. Just need to bump up VS and CMake for Windows.

**Comment by jpark37** [comment]
Judging from these two links, I think Azure will get CMake 3.16.2 just from creating a new VM image?

https://github.com/microsoft/azure-pipelines-image-generation/issues/754
https://chocolatey.org/packages/cmake

**Comment by jpark37** [comment]
Checks pass now. I guess I'll wait for @jp9000 to give the okay on VS 2019 before marking the review as ready.

**Comment by derrod** [comment]
An issue I noticed is that this capture method appears to disable the hardware cursor, meaning cusor movement will feel somewhat unresponsive (input lag). While not necessarily a big deal - on my 144 Hz monitor this is barely noticeable, on my 60 Hz one it is very apparent - I think that might be something for others to test and confirm.

**Comment by jp9000** [comment]
If the CI works then the SDK issue is fine for the record.

For the hardware cursor thing, that's very likely Microsoft's doing, not ours, we probably aren't in control of that.

**Comment by jpark37** [comment]
There's a commit in this PR to switch CI over to VS 2019. Is that fine?

**Comment by jp9000** [comment]
Yea, that's fine.

**Comment by jpark37** [comment]
K, I'll see in a few hours if there's something I can do about hardware cursor before I remove draft status.

**Comment by jpark37** [comment]
I couldn't repro the hardware cursor issue; it's always active for me.

**Comment by jp9000** [comment]
Although I don't have any lag either, I really doubt that it's anything in the source implementation anyway, I would expect it to be due to something happening internally as part of the capture in microsoft code.  Unless you have some cursor stuff in your code that you think would be the cause, but I doubt it.

It doesn't really matter too much though, because this probably shouldn't be treated like a complete replacement for normal window capture.  In my view, this is more important to us to capture windows that have been evading normal window capture, such as browser windows, microsoft store apps, office, or programs that run on chromium/cef/electon.

**Comment by jp9000** [comment]
This is just about perfect.  I'm probably going to add an "auto" option and make it the default for the capture method dropdown though, so it can automatically capture windows we'd previously been having problems with.  I feel like it should only be a few hours to make.  I'm considering modifying the text for the items in the drop-down as well so the function is a bit more apparent.

**Pull request merged**
