### PR TITLE
0001183: Add a keyboard shortcut to rename elements (scenes and sources) in OBS

### PR DESCRIPTION
**Pull request by wbo2017**
I change the "Rename" to "Rename(F2)
After the "Rename" entry, there is "F2" (as same as the "Delete" entry and "Del") which fit for the Scenario 2 and Scenario 4

### CODE REVIEW

**Comment by dodgepong** [comment]
This doesn't add a Rename shortcut, this just attempts to add a label to indicate what the hotkey is to rename a scene.

But you're changing the QStr label, not the text itself. If you want to change the text, then you'll need to change the localization. The only reason this "works" as you expect it to is because OBS's localization system can't find a locale string called "Rename(F2)" and defaults to showing the label text name. Thus, this will be wrong in localization.

But furthermore, this is entirely the wrong solution to the problem. I'm not 100% sure how this needs to be fixed (since the shortcut is actually defined under `OBSBasic::OBSBasic`), but perhaps that definition needs to be moved to inside the `addAction` method as one of the `QMenu.addAction` overrides here: https://doc.qt.io/qt-5/qmenu.html In that case you'd have to define a `QKeySequence` for the F2 shortcut. I'm not sure if this would conflict with the existing shortcut, though.

**Comment by wbo2017** [comment]
The Rename shortcut already exist on the code,which contain on the window-baisc-main.cpp

**Comment by dodgepong** [comment]
Right, I know. And presumably all you're trying to do is indicate to the user what the shortcut is set to? Kind of like the "Fullscreen Interface" menu item here:



But the solution proposed here doesn't use that functionality (which automatically aligns the hotkey text to the right side of the menu). Instead, you're just adding "(F2)" to the end of the menu item text. Not only is that the wrong solution to the problem, but the implementation here is wrong because it breaks localization.

**Comment by dodgepong** [comment]
Also it's worth noting that the shortcut is actually `Enter` on OSX, not `F2`.

**Comment by wbo2017** [comment]
Foe this situation, i need to detect the different OS and lable it according to that?

**Comment by jp9000** [comment]
As dodgepong stated, this is not how you add shortcuts to menu items.  Take some time to learn Qt's API for shortcuts assigned to actions before making a pull request.

Shortcuts are added via `QMenu::addAction`.  However, currently they aren't shown on specific operating systems due to a design change by Qt in 5.10.  So right now there's not much anyone can do about this until we update Qt and add the code for it, which I'll do in future versions, though for now we still use 5.10.

**Pull request closed without merging**
