### PR TITLE
UI: Redo settings icons

### PR DESCRIPTION
**Pull request by cg2121**
screenshot from 2018-12-19 14-09-40
screenshot from 2018-12-19 14-09-57

### CODE REVIEW

**Comment by MisterTeeXD** [comment]
Looks really good, great job 👍

**Comment by cg2121** [comment]
I switched the icons to the https://octicons.github.com/ set. These are MIT licensed.

**Comment by wallrik** [comment]
Looks really good. I just figured I'd throw a ball into court. Instead of replacing the current icons with their closest neighbor in this set, I'd love to see if there could be something even better.
I'm thinking of the **stream** and **output** icons. Since **output** is more about quality/speed settings, maybe it could have one of these? [Dashboard](https://octicons.github.com/icon/dashboard/), [Settings](https://octicons.github.com/icon/settings/), [Circuit board](https://octicons.github.com/icon/circuit-board/), [Media file](https://octicons.github.com/icon/file-media/) or [External link](https://octicons.github.com/icon/link-external/).
And **stream** could instead have the current [radio tower](https://octicons.github.com/icon/radio-tower/) or [broadcast](https://octicons.github.com/icon/broadcast/). Just a thought :)

**Comment by DDRBoxman** [comment]
@cg2121 do they provide SVG versions of those icons?

If they do that would be awesome, you'll have to look at some of what I've done in my context ui PR to get the dlls copied over
https://github.com/obsproject/obs-studio/pull/1447/files
cmake/Modules/CopyMSVCBins.cmake

Also might be worth bumping this up back to the size that the settings options were before, makes it easier to click on.

**Comment by DDRBoxman** [comment]
screen shot 2019-02-18 at 12 04 43 pm

Switched over to svgs and changed up two of the icons.

**Comment by cg2121** [comment]
I think the SVGs are a much better idea going forward. Are the new icons you are using from the same icon set as before?

**Comment by DDRBoxman** [comment]
Yup, same octicons icon set. I also modified one of them for the output icon.

**Comment by DDRBoxman** [comment]
Just leaving myself a note that this may need more dlls as I found out recently in a recent update to my context toolbar pr

**Comment by WizardCM** [comment]
**Warning**: During the v23 release we learned the updater didn't like @ symbols in filenames (or files starting with a dot)


After testing this, here's my feedback
* Because the icons don't have a fixed width of any kind, the "General" label doesn't line up with the rest of the options, and the icon is off-center
* I'd add a lot more padding around the icons, especially to the left and right. Double those at least, and then make sure the top and bottom are equal to them.
* I don't think the icon should dim for the currently focused page

**Comment by cg2121** [comment]
I have now fixed the general icon sizing. I had to use a different icon from the Open Iconic icon set. This set is also MIT licensed.

**Comment by cg2121** [comment]
I decided to go back to the origin Octicon gear icon because I thought it looked better. I edited it to make it fit.

**Pull request merged**
