### PR TITLE
CI: Run make with -j$(nproc)

### PR DESCRIPTION
**Pull request by tbodt**
### Description
make -j$(nproc)

### Motivation and Context
Moar threads for moar cores

### How Has This Been Tested?
I ran the script once

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jp9000** [comment]
Is there a reason why we might not have been doing this before? I'm actually surprised it wasn't already compiling nproc

**Comment by RytoEX** [comment]
> 
> 
> Is there a reason why we might not have been doing this before? I'm actually surprised it wasn't already compiling nproc

I can't think of one.  We'd apparently hard-coded -j4 into `CI/full-build-macos.sh`, and it was also hard-coded that way in `azure-pipelines.yml` beforehand.

https://github.com/obsproject/obs-studio/commit/4bcfe5e12c4b00f6ee8411b4bf62c85b6406598b

**Comment by PatTheMav** [comment]
No particular reason, I think I just copied it from the legacy scripts as-is. I planned to introduce the same change anyway, as obs-deps is using it already.

@tbodt Could you please apply the same change to our GitHub Actions workflow `main.yml` to keep both in sync?

**Comment by jp9000** [comment]
Oh woops, I did not see the main.yml part. Feel free to open another PR for that.

**Comment by PatTheMav** [comment]
I'll let @RytoEX have the honour.

**Comment by Gol-D-Ace** [comment]
Perhaps do the same for Linux CI
make -j$((\`nproc\`+1))` for the deluxe version

**Comment by PatTheMav** [comment]
Never mind, added it myself: https://github.com/obsproject/obs-studio/pull/3920/commits/815efdb9b96b158635f166d89e7a3a6f3101a355

**Pull request merged**
