### PR TITLE
docs: Remove block quotes

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Removes the indents that cause the text to be interpreted as block quotes.

### Motivation and Context

The block quotes looked like they are unintentional.
image

Imho this looks better.
image

### How Has This Been Tested?

Committed and checked that the quotes are gone

### Types of changes

- Documentation (a change to documentation pages)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
Actually, there are way more pages than the README
I'll add those as well

**Comment by Fenrirthviti** [comment]
lGTM, but not sure if the commit name is correct, previous updates have been CONTRIBUTING.rst: and README.rst: prefixes, but I'll leave that up to @jp9000

**Comment by gxalpha** [comment]
Yeah I agree they aren't perfect, I just wanted to prevent having 2 commits which seems unnecessarily many. On the other hand, it would look better on the GitHub page - if you want me to change it and split it up into 2 commits I'm happy to do that

**Comment by Fenrirthviti** [comment]
Discussed and it's fine as is.

**Comment by Marcolenox** [comment]
CODE_OF_CONDUCT

**Pull request merged**
