### PR TITLE
rtmp-services: Add LiveSpace

### PR DESCRIPTION
**Pull request by steve-livespace**
### Description
Added LiveSpace to rtmp-services list

### Motivation and Context
Adding our LiveSpace service for user convenience

### How Has This Been Tested?
Tested locally

### Types of changes
- Tweak (non-breaking change to improve existing functionality)
- Added a Streaming Service via additional JSON block and incremented version

### Checklist:
- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by Fenrirthviti — APPROVED** [review]

**Comment by RytoEX** [comment]
This PR has merge conflicts, so it cannot be merged as-is. Unfortunately, this PR also has maintainer edits disabled, so I cannot fix them myself.

**Comment by derrod** [comment]
> Thanks - I can fix it but can't commit here, nor know how to make it fixable for you - guess I have to resync my repo and do a new PR; sucks, as hope to salvage this one, as been months.

You just need to check this box at the right side of the screen:
checkbox

**Comment by RytoEX** [comment]
> Can I do that on existing PR, as not obvious how here, or maybe can convert to draft and try again? Or best to start over and redo a new PR using latest merged changes I saw you made today? Apologies for challenges.

You apparently cannot enable maintainer edits here because of a quirk with how GitHub handles PRs made by individuals from an organization repo:
https://github.com/orgs/community/discussions/5634

You either need to fix this PR up yourself, or open a new one that is fixed. I would recommend not opening a PR from an organization repo to avoid the problem above. I would also recommend that you:
1. Do not submit a PR from any fork's master branch.
2. Do not use merge commits to keep your branch up to date. Use `git rebase` instead.

**Comment by RytoEX** [comment]
Closing this PR as LiveSpace shut down on May 1, 2024.

https://about.live.space/post/thank-you
https://twitter.com/StreamLiveSpace/status/1780507581167141166

**Pull request closed without merging**
