### PR TITLE
linux-pipewire: Add support for GS_R10G10B10A2

### PR DESCRIPTION
**Pull request by columbarius**
### Description

This adds support for the R10G10B10A2 format to the pipewire-capture plugin.

### Motivation and Context

Wlroots supports 10bit formats and thus the portal implementation does export buffers with this format.

### How Has This Been Tested?

Configure an output with `render_bit_depth 10` in sway and use xdpw from the master branch.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by columbarius** [comment]
This MR needs some defines for the ubuntu lts versions, since 10 bit formats were only added in PipeWire 0.3.41 iirc. Will add those when this is confirmed to work.

**Comment by columbarius** [comment]
Tested this MR. Should be rerun later, it failed because ubuntu package servers were not available. Ready for review.

**Comment by tytan652** [comment]
Please drop the flatpak commit since we will switch to 22.08 based runtime (#7770).

**Comment by tytan652** [comment]
Last nitpik from me, the hide commit can be squashed with the first commit.

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by columbarius** [comment]
Btw. thanks for merging!

**Pull request merged**
