### PR TITLE
UI: Use themeID for red message in settings view

### PR DESCRIPTION
**Pull request by SuslikV**
Cut loose ends.

### CODE REVIEW

**Comment by SuslikV** [comment]
I think that empty labels as part of UI is not the best thing. They have real full size while text is empty.

While it is possible to change the role of the label later, in the code (for example the message type is not an "error", just "warning"), by changing the dynamic property ("themeID" that assigned in this PR) and refresh draw for the required widget . But it is still only workaround.

**Comment by Fenrirthviti** [comment]
Can you explain what this actually fixes? Or is this just a change for the sake of change?

From the looks of it, this change would require a theme to apply [themeID="error"] or it will not be styled at all, which is a terrible idea. All the current themes have this, but the defaults should not be messed with like this, and leaving it as is does not break anything.

**Comment by SuslikV** [comment]
If take into account https://github.com/obsproject/obs-studio/commit/fb4a29a751a92439f2040fdd56930584aafed262 then all parts should be fixed, I think. Yeah, I don't like it, you know. But it can be done in this way too.

Feel free to make other PR that will fix Acri theme. The mentioned one and some previous commits broke many things in themes. It is because of long development.

**Comment by SuslikV** [comment]
@Fenrirthviti , It looks like Acri theme was fixed recently (https://github.com/obsproject/obs-studio/commit/b58f5c7d4b86c64bda87b80380f49b57f8ff27fa).

**Comment by Fenrirthviti** [comment]
I've reviewed this change again, and in testing it looks like this is the best option for consistency's sake, as Qt does not like mixing styles set in code and QSS.

According to their recommendations, setting the "themeID" property and allowing the theme to style this would be the best option for now, until the settings UI can be revamped.

**Pull request merged**
