### PR TITLE
 rtmp-services: Update SharePlay recommendations

### PR DESCRIPTION
**Pull request by vasuais**
### Description

I have replace our service provider name as Shareplay.tv to SharePlay

image

### Motivation and Context
 I have changed the service provider a name. Because  my team decided to replace the service provider name

### How Has This Been Tested?
I have tested this scenario in my local system using obs-studio

### Types of changes
I have updating service provide name

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by vasuais** [comment]
> Also please check and use `alt_names[]` ([doc here](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines#full-list-of-available-properties)) if you want to change the name of the service.

I have updated OBS studio 27.2.2. But I'm not showing  Shareplay service provider in a provider list.
Please you can help me?

**Comment by Fenrirthviti** [comment]
Services are updated independently of releases. This will not be available until we make a new services file push.

**Comment by vasuais** [comment]
> Services are updated independently of releases. This will not be available until we make a new services file push.

Okey thanks.

**Comment by vasuais** [comment]
When will be shareplay live on OBS and what is your official email address to communicate

**Pull request closed without merging**
