### PR TITLE
UI: Change audio device string in settings

### PR DESCRIPTION
**Pull request by cg2121**
### Description
- Rename "Devices" to "Global Audio Devices" in audio section of settings 

### Motivation and Context
Makes it easier for users to understand what these items are.

### How Has This Been Tested?
Ran program to see if strings displayed properly.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I like #2 here, and I have no personal issues with #1 but I feel like there's going to be a lot of very loud opposition to it :)

**Comment by WizardCM** [comment]
> I like 2) here, and I have no personal issues with 1) but I feel like there's going to be a lot of very loud opposition to it :)

I second this.

**Comment by tt2468** [comment]
As @Fenrirthviti said, renaming preview/program would be a problem. There would be just as much (or more) confusion from people using OBS in the broadcast world as there would be for new users.

**Comment by dodgepong** [comment]
What about `Preview (Edit)` and `Program (Live)`?

**Comment by skeletonbow** [comment]
or Edit Preview / Live Program

**Comment by RytoEX** [comment]
Please also note that string changes require translation changes.  I don't think "Code Cleanup" is the appropriate classification for this, so I'm marking it as an Enhancement.

I'd suggest dropping the Preview/Program string changes from this until we have a firm consensus on how best to handle that and just focus on the audio devices change for now.

**Comment by cg2121** [comment]
I've now removed the edit/live string commit based on feedback.

**Pull request merged**
