### PR TITLE
Service Integration and UX Improvements (Work in progress)

### PR DESCRIPTION
**Pull request by jp9000**
This pull request:

- Improves the user experience for both the auto-configuration dialog and the stream page, removing the redundant "service type" option, and consolidates all services (including "custom") in to a single service-selection drop down.  In addition, instead of selecting "Show all" as a checkbox, it is now present in the drop-down at the bottom.
- Allows the ability to log in to services directly (at least ones that implement direct-login) instead of manually having to look up their stream key for the service.  Typically this is done via OAuth using a browser panel window.  Note that this is optional; the user can still enter a stream key if they wish it for stream key-based services.  If the browser plugin is not present, only stream key entry will be present.
- If the user chooses to log in to a service, that service can add custom user interface specific to that service.  For example, at the moment I've implemented it so that for twitch, the twitch chat window will pop up as a dockable window, and hopefully I will implement something to allow updating the stream game/title on the spot.  Eventually we'll have the same for other major services.

I am making this pull request for the purposes of discussion while I work on the feature.  All these things are subject to change, and feel free to discuss your opinions or what you would like to see.  Certain things are not finalized -- some of the code still needs refactoring as of this writing (there's still a fair amount of code duplication at the moment).  There are also some localization strings that have not been added.

A lot of these changes are also the result of a lot of R&D regarding utilizing CEF not just for the browser source, but also for optional user interface.  I finally have the browser working as actual optional in-program widgets, so this is a step forward towards relatively easy augmentation of the user interface in cases where it makes sense (like service integration).

### CODE REVIEW

**Comment by SuslikV** [comment]
Because of such huge change in OBS Studio is there any known security risks introduced by CEF integration?

**Comment by SuslikV** [comment]
"Connect Account (optional)" - I read this like: I can connect to as many accounts as I wish simultaneously. Maybe "Bind Account (optional)" is better naming of the option?

**Comment by jp9000** [comment]
Pages that this go to may as well be considered whitelisted.  OBS is not acting as a web browser, these are only specific pages we choose acting as UI elements.  Let's say they open a link in a chat window -- any external link they choose in say their chat window get redirected to their system browser, and not OBS itself.

**Comment by jhobz** [comment]
This is great! In addition to the identified usefulness of being able to update game/title directly from OBS, I think a big win would also be having a hotkey that generates a Stream Marker for use in highlighting.

**Comment by Scrxtchy** [comment]
> This is great! In addition to the identified usefulness of being able to update game/title directly from OBS, I think a big win would also be having a hotkey that generates a Stream Marker for use in highlighting.

Hmm, If the oauth tokens were easily picked up from API bindings, these could more easily people to add additional functionality like stream markers. You could do it right now with some scripting, but you'd need an oauth key handy, they aren't hard to get, it's just not going to be as pleasant compared to it being handled by OBS studio

**Comment by jp9000** [comment]
I would love to implement anything like that which could be useful.  It'd be nice if Twitch dashboard elements could be used as individual popouts, that way we wouldn't necessarily have to implement that ourselves, and Twitch could customize them however they please.

As for the normal API, I'm not sure how much the Twitch API exposes for features like that, I know they switched to GraphQL for their recent API, if it's available in the current OAuth standard then I'd invite people to implement it after merging.

**Comment by Scrxtchy** [comment]
The current situation with Twitch's API is kinda bonkers, Since there are a number of endpoints that aren't implemented on the new API, and even in production they have to resolve to using the old API (v5). Other than that, anything that does use the new API is a lot easier to manage.

For example, updating your current game still points to using Kraken (v5), this is also used on the mobile version of twitch, therefore this sounds like a chore 😒

**Comment by Scrxtchy** [comment]
The FFZ control centre doesn't work. 
It opens a tab within the desktop browser, where I do not use the extension
image

**Comment by jp9000** [comment]
CEF is programmed not to allow popup windows, so that's not entirely surprising.  I'm not sure how I feel about having popup windows within the program.

**Comment by Scrxtchy** [comment]
> CEF is programmed not to allow popup windows, so that's not entirely surprising. I'm not sure how I feel about having popup windows within the program.

It's a tough one because I don't think everyone as well wants the default configurations that come with these userscripts. For example, the recolouring of usernames
image

**Comment by jp9000** [comment]
Hm, I'll see what I can do.

**Comment by Scrxtchy** [comment]
Well, I could consider adding a settings pane for integration. Could allow users to disable the userscripts for running at all, as well as opening their settings. Only thing is I know you can easily open FFZ's settings from adding ?ffz-settings to your URL (https://github.com/FrankerFaceZ/FrankerFaceZ/blob/e3ab5d63a31c5a904ea05a8848cf9397ede82738/src/sites/twitch-twilight/index.js#L93), should work as long as the script is loaded. But BTTV is another story, they also have an option to open settings from chat, which displays their inline settings, but it doesn't work in the frames (https://github.com/night/BetterTTV/blob/8d5dda3951ae96fc9a97d25a8b5ca70432ae4ce6/src/modules/chat_settings/index.js#L45), could probably nicely ask @night to implement a param check into the extension (similar to ffz) to automattically open the bttv settings screen, as OBS should be able to just load these webpages in their own QWidget, as long as `localStorage` is shared between instances

**Comment by Scrxtchy** [comment]
Another addition to the twitch service integration is to easily run a stream to twitch inspector
image

**Comment by WizardCM** [comment]
The Auto-config wizard in the Tools menu already uses the bandwidth test mode. That's a good point though - I'd be curious what kind of integration https://inspector.twitch.tv/ supports. It'd allow us to show a streaming report using Twitch's own data.

**Comment by Scrxtchy** [comment]
I use it alongside OBS's stats window to do testing in a live environment. Means I'm outputting to a twitch ingest, but not broadcasting to a channel. Helps for debugging

**Comment by techkid6** [comment]
First off, I'm really excited to see this become part of OBS.  Secondly, will it be possible to support services which could have multiple stream keys?  For instance, YouTube can have multiple `liveBroadcast` objects, each with their own "bound" `liveStream`, where you would find a stream key.  Some more info on that is [here](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts) but being able to choose between different broadcasts on an account would be amazing.  Right now the `osb-service` API only seems to support `get_url` and `get_key`, implying a single key per service.

**Comment by jp9000** [comment]
Cleaned up commits and merged

**Pull request closed without merging**
