### PR TITLE
Configurable outline width (Freetype)

### PR DESCRIPTION
**Pull request by norihiro**
### Description

This pull-request adds configurable width of outline.

### Motivation and Context

Previously width of the outline was hard-coded 2px. With large font, outline was too thin.

There was a comment to improve outline and drop-shadow.
> Better/pixel shader outline/drop shadow

### How Has This Been Tested?

The change was tested under CentOS 8 x86_64.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
Question: Should this be configurable, or automatic based on the size of the text?

**Comment by norihiro** [comment]
Hi WizardCM,
Yes, user can configure the width of the outline. I have added properties to change the width of the outline. Also added color of the outline and shadow.

**Comment by tt2468** [comment]
My opinion would be that it should mirror as best as possible the functionality of its Windows counterpart.

Also great work, I've been waiting for this feature to be added for a long time now.

**Comment by dodgepong** [comment]
I agree that the implementation should probably match that of the Windows GDI+ source. For example, having separate vertical and horizontal width for the outline is probably too detailed -- just ask for one size and make it consistent, like a Photoshop stroke.

As for @WizardCM's question, it should not scale with font size. It should be whatever size the user says it should be. Besides, users will probably scale the source anyway, which will make the stroke size relative by default.

**Comment by norihiro** [comment]
The reasons that I put two settings of outline amount (vector and bitmap) are below.
- `FT_Outline_Embolden` makes edges more sharp. Please see bottom of `A` and bottom of `q`, for example. I felt it's not beautiful.
- `FT_Bitmap_Embolden` makes rectangular edge. The width becomes slightly bold on a round line such as `V` and `U`'
I thought it would be better for users to choose the method.
I can change to use `FT_Outline_Embolden` for vector-fonts if same interface as GDI+ is preferable.

2020-04-26T00-21-58

Btw, I noticed GDI+ provides opacity for outline and extents (maybe same as drop-shadow). I will add these feature as well.

**Comment by tt2468** [comment]
I would argue that familiarity is more important than an extra feature like this, but I think it comes down to what the ui looks like. Could you screenshot that?

**Comment by norihiro** [comment]
The new items on the property dialog is as below.
3 items following a check-box of Outline are new for Outline.
 - Outline width (vector)
 - Outline width (bitmap)
 - Color
1 item following a check-box of Drop Shadow is new for Shadow
- Color

ft2-outline-shadow

**Comment by tt2468** [comment]
Hmm yeah I think it might be best to combine vector and bitmap into one `size`.  Is it by chance possible to change opacity to further match GDI+?
image

Also is it appears to be cropping the edges of the outline. I assume that is a bug

**Comment by norihiro** [comment]
The two widths properties are merged into one as same as GDI+. Also added opacity properties for all 4 colors.
Regarding the cropping edge, it was there before this change. Do you want to bundle the bugfix with this pull-request? Even though it is cropped in property window, it can correctly displayed on a scene.
obs-outline-opacity

**Comment by dodgepong** [comment]
Thanks!

The crop issue can be handled by another PR.

**Comment by jp9000** [comment]
Unfortunately when I merged #2795 I really caused problems for this PR without realizing that would happen.  They were destined to conflict it seems, but this is kind of painful.  I'm sorry about that.

**Comment by norihiro** [comment]
I will take a look at the conflict.

**Comment by norihiro** [comment]
The conflict is solved.
I've tested it on CentOS 8 x86_64.

**Pull request closed without merging**
