### PR TITLE
build-aux: Update Flatpak CEF from 103/5060 to 127/6533

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Flatpak counterpart of #11213 

Reminder that https://github.com/obsproject/obs-browser/pull/450 (or an alternative) is required to avoid the shutdown crash with browser docks.

The CEF module is also modified to:
- Use the pre-built wrapper included in the tarball
- Preserve debug symbols inside its binaries
  - The copy done later by OBS Studio build-system will be split from its debug symbols

### Motivation and Context

Update CEF on the Flatpak and preserve CEF debug symbols which will be put in the `.Debug` Flatpak extension.

### How Has This Been Tested?

Build with CEF and debug symbols are generated and compressed.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tiberium-v** [comment]
Tested on x11 (i3 wm), via flatpak artifact without problems. Also, Custom Browser Docks Window are behaving normal

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by colingourlay** [comment]
Looking great on macOS (Sonoma) 14.6.1. Virtual camera has stopped working, but sources are all perfect. Tested recent Chromium features by using CSS `mask-image` to mask areas of the page with an local SVG `<mask>`. Flawless! Thank you so much for this update.

**Comment by RytoEX** [comment]
> Looking great on macOS (Sonoma) 14.6.1. Virtual camera has stopped working, but browser sources are all perfect. Tested recent Chromium features by using CSS `mask-image` to [mask areas of the page](https://stream-scenes.colin-gourlay.com/docked-ring?preset=synthwave) with an local SVG `<mask>`. Flawless! Thank you so much for this update.

As a note, this PR _only_ updates the Flatpak version. PR #11213 updates Windows and macOS.

**Comment by RytoEX** [comment]
This should now be unblocked by https://github.com/obsproject/obs-studio/commit/16011f7c297fed566ffa697ee3fd8e6318c08fa2.

**Review by RytoEX — APPROVED** [review]
LGTM

**Pull request merged**
