### PR TITLE
Iconography and list styles

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
### Description

Use a consistent icon style for all symbolic icons used by OBS Studio. 

Captura de tela de 2022-08-01 20-02-19

Adjust the empty state of the sources dock too.

Captura de tela de 2022-08-01 12-09-01

Make all relevant lists - sidebars of the filters dialog and the settings dialog, the source tree, and the scene tree - have slightly chunkier list items, and consistent 16px icons

Captura de tela de 2022-08-01 20-00-46

image

These icons are derived from the GNOME icon library. I've changed the fill colour to `#fefefe` for Dark theme icons, and `#000000` for embedded icons. If further icons are needed, they can be found at https://teams.pages.gitlab.gnome.org/Design/icon-development-kit-www/

### Motivation and Context

The icons used by OBS Studio have different and inconsistent styles between each other, which is slightly unpleasant. However, simply changing icons isn't enough, since they're used in inconsistent ways in different places - mainly lists. This PR addresses both.

### How Has This Been Tested?

 - Run the branch
 - Feel extra pleasure while using OBS

### Types of changes

 - Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
@Warchamp7 am I delusional?

**Comment by GeorgesStavracas** [comment]
This needs to be tested on Windows and Mac

**Comment by YuvalShor** [comment]
Tested on Windows, looks nice and neat.

Screenshots:

image
image
image
image

**Comment by GeorgesStavracas** [comment]
As per feedback, updated this PR with the following changes:

 * Revert the minus icon back to a trash icon
 * Use a different icon for the Output page in the Settings dialog

**Review by Warchamp7 — APPROVED** [review]
Gave Georges my feedback on Discord and it has been addressed

**Comment by feetstv** [comment]
> This needs to be tested on Windows and Mac

Here it is on macOS 13.

Screenshot 2022-08-06 at 16 45 54
Screenshot 2022-08-06 at 16 46 26
Screenshot 2022-08-06 at 16 46 51
Screenshot 2022-08-06 at 16 47 10

**Pull request merged**
