### PR TITLE
obs-ffmpeg: Remove duplicate "FFmpeg Options" locale

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

There are two separate locales for "FFmpeg Options", now there is only one.
Also moves the tooltip up to where the other source options are.

### Motivation and Context

Duplicate locales only cause extra code and work for translators.

### How Has This Been Tested?

macOS 12.4
Made sure for the source both the name and tooltip of the property are shown.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Vainock** [comment]
I prefer the version Jim already used in his PR: "Use to specify custom FFmpeg options. For example, \"level=5.2 profile=main\"."

Explains the formatting with a generic example and reduces the length of the sentence to a minimum. Same information much more compact and easier to read.

**Comment by RytoEX** [comment]
> I prefer the version Jim already used in his PR: "Use to specify custom FFmpeg options. For example, \"level=5.2 profile=main\"."
> 
> Explains the formatting with a generic example and reduces the length of the sentence to a minimum. Same information much more compact and easier to read.

The longer string has a specific use case to explain a specific usage in the media source. Options like level and profile may or may not work in that use case. I would not want non-working options to be reflected in that flow. The options described in the longer string are very specific for the flow in which they are used. I'm not sure they are actually interchangeable as suggested.

**Comment by gxalpha** [comment]
I agree with Ryan.
The options here are specifically for the ffmpeg source, while the ones in Jim's PR are for an encoder. The arguments used for an encoder ("level=5.2 profile=main") don't make sense for the source.

What I did do is move the string up to the other ffmpegopts like jim did as it probably makes more sense to have them together.
I'll also recommend in #6508 to add a `.Encoder` to the string to indicate that it isn't universal, just as this has a `.Source`

**Comment by RytoEX** [comment]
Was just typing this, but apparently moments too late. If I want to be pedantic, the key name should probably be: FFmpeg.Source.Options.Tooltip to indicate that it is specifically a tooltip for the FFmpeg Source's Options. I know there's a desire to match it to the existing FFmpegOpts key, but we don't need to have those match. It's not a big deal either way, so long as we don't get confused about its purpose in the future.

**Pull request merged**
