### PR TITLE
UI: Clean up Settings Output form

### LINKED ISSUE #4858: UI: audio track selection widgets misaligned in the Settings
### Operating System Info

Other

### Other OS

any OS

### OBS Studio Version

27.0.0

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

about:blank

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

_Settings>Output>Output Mode: Advanced>Recording tab>Audio Track_

The "Audio Track" selection widget shouldn't shift either horizontally nor vertically, despite the change of the "Recording Format" (flv/mp4).

### Current Behavior

When ever you select the:

- _Settings>Output>Output Mode: Advanced>Recording tab>Recording Format: flv_

the whole widget that holds radio buttons for the:

- _Settings>Output>Output Mode: Advanced>Recording tab>Audio Track_

shifts a bit to the bottom right.

### Steps to Reproduce

1. Open _Settings>Output>Output Mode: Advanced>Recording tab_
2. Select the "mp4" for the _Recording Format_ field
3. Remember position of the check boxes for the _Audio Track_ field.
4. Select the "flv" for the _Recording Format_ field
5. Notice that radiobuttons (instead of the checkboxes) drawn shifted to the bottom right and clipped from the bottom.

### Anything else we should know?

On the pictures below:
Yellow - is part of the `QWidget#recTracks` area (middle layer)
Green - is part of the `QStackedWidget#advRecTrackWidget` area (bottom layer)
Red - is part of the `QWidget#flvTracks > QWidget#horizontalLayoutWidget` area (upper layer)
The top layer is the currently shown widget itself.

obs adv rec track selection UI bug checkbox

obs adv rec track selection UI bug radiobutton

The issue was introduced in https://github.com/obsproject/obs-studio/commit/bab3391ce4b45eb0676696d20933b66ef1a9736b

The QStackedWidget:

https://github.com/obsproject/obs-studio/blob/e0edd753ad88230275441d60b3c1832acf1da0e7/UI/forms/OBSBasicSettings.ui#L2339

in its chexkbox part holds the widget with the QHBoxLayout (horizontalLayout_9) which margins set to 0 (not default!):

https://github.com/obsproject/obs-studio/blob/e0edd753ad88230275441d60b3c1832acf1da0e7/UI/forms/OBSBasicSettings.ui#L2349-L2362

while the radibuttons part holds the widget with the QHBoxLayout (horizontalLayout_24) which margins not set at all (so they are default/OS dependent). And the parent widget is shifted 9px by X axis:

https://github.com/obsproject/obs-studio/blob/e0edd753ad88230275441d60b3c1832acf1da0e7/UI/forms/OBSBasicSettings.ui#L2407-L2417

This causes inconsistency in the drawing of all Themes for OBS.

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
This is an overhaul of the UI markup for the Output pane of the Settings window

- Adds new frames around certain elements for a better element hierarchy
- Places the categories of settings into group boxes
- Moves the scroll area from on the entire page into the individual Advanced tabs themselves
- Adjusts margins on the various container frames so that all sections line up

I believe this PR also fixes #4858 

## Before
image

## After
image

## Before
image

## After
image

image
_The recording tab scrolled down doesn't hide the output mode dropdown, navigation tabs or recording type dropdown_

### Motivation and Context
The scrollbar being on the entire output page container meant that the six entries in the Audio tab could cause the other tabs to be scrollable for no reason. This also meant that scrolling down would scroll the top level dropdown and tab controls out of view.

### How Has This Been Tested?
Checked that all tabs still functioned as expected.
Checked that all toggles that add/remove warnings, or enable/disable certain controls still functioned correctly.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
To what extent is rescaling the output an encoder setting instead of a general output setting?

**Comment by derrod** [comment]
> To what extent is rescaling the output an encoder setting instead of a general output setting?

On a technical level? The rescaling happens using ffmpeg (swscale) which is independent of the chosen encoder, so it's not really an encoder setting. Everything in the "encoder settings" panel is also created at runtime based on properties whereas the other settings are static.

As for the PR itself the padding between the label and first line of properties looks a bit weird and is inconsistent with the rest of the program.

**Comment by Warchamp7** [comment]
> > To what extent is rescaling the output an encoder setting instead of a general output setting?
> 
> On a technical level? The rescaling happens using ffmpeg (swscale) which is independent of the chosen encoder, so it's not really an encoder setting. Everything in the "encoder settings" panel is also created at runtime based on properties whereas the other settings are static.

This

> As for the PR itself the padding between the label and first line of properties looks a bit weird and is inconsistent with the rest of the program.

Could you clarify what you mean?

**Comment by cg2121** [comment]
@Warchamp7 I believe @derrod is talking about the spacing between the groupbox title and the first item in it.

**Comment by Warchamp7** [comment]
> @Warchamp7 I believe @derrod is talking about the spacing between the groupbox title and the first item in it.

Hmm yeah, there's some weird stretching going on. I'm investigating

**Comment by Warchamp7** [comment]
Alright, I've improved the margins a bit.

I can't completely fix the encoder settings paddings, as it requires changes to the properties-view code itself, which means I'll have to adjust other areas where property views are used, so it'll be a separate PR

**Comment by WizardCM** [comment]
Heads up, there are merge conflicts.

**Comment by WizardCM** [comment]
Rebased on master. Things to double check before merging:

* [ ] Any new translation keys are referenced properly
* [ ] Tab order
* [ ] No unrelated changes in UI file

**Comment by SuslikV** [comment]
1) Screenshots are bad. Hard to compare. Set the same values into the fields.
2) Doubles in names. Hard to understand where you are right now. The "Stream" (main section), the "Streaming" (tab), the "Streaming Settings" (group).
3) Audio settings spread among the tabs. Hard to adjust and not to mess up. The Track selection is still not in the Audio tab.
4) Encoder type is far away from its internal adjustments. Hard to link the endoder's choice with the settings that lies far below it (and not in the same group).

Side note: the QFrame widget was intended to make visual decorations, literally the FRAMES. I have seen, recently, that it was used as a helper object in obs. It is not OK, but I can live with it.

**Comment by SuslikV** [comment]
@gxalpha Programming is about the rules and logic. No mood. Conversation can has a mood - it is OK. I have updated the comment above.

**Comment by SuslikV** [comment]
It is very unhandy to have a vertical scroll inside the vertical scroll (Settings>Output>Output Mode: Advanced>Recording tab>Encoder Settings). Double scroll screenshot:

obsv28yamithemesucks

The undesirable scroll element was added by new _setSizePolicy_ restrictions in the code.

**Pull request merged**
