### PR TITLE
build-aux: Work around oneVPL search path for Flatpak QSV

### PR DESCRIPTION
**Pull request by twelho**
### Description

With an Intel GPU, the QuickSync encoders fail to start in the Flatpak build:

```
info: [qsv encoder: 'advanced_video_recording'] debug info:
error: Failed to initialize MFX

 Specified object not found. /run/build/obs/plugins/obs-qsv11/common_utils_linux.cpp 140

 Specified object not found. /run/build/obs/plugins/obs-qsv11/QSV_Encoder_Internal.cpp 156
warning: [qsv encoder: 'msdk_impl'] Specified object/item/sync point not found. (MFX_ERR_NOT_FOUND)
warning: [qsv encoder: 'advanced_video_recording'] qsv failed to load
```

Tracing this back points to the `MFXCreateSession` call [in common_utils_linux.cpp](https://github.com/obsproject/obs-studio/blob/0e5007794836c31bebd46fb492776f38f84f0441/plugins/obs-qsv11/common_utils_linux.cpp#L137), implemented on `libvpl`'s side in [mfx_dispatcher_vpl.cpp](https://github.com/intel/libvpl/blob/79ef61b11790c70941cfa4d167b5d20d3a4e9744/libvpl/src/mfx_dispatcher_vpl.cpp#L132). Next, `CreateSession` fails in [mfx_dispatcher_vpl_loader.cpp](https://github.com/intel/libvpl/blob/79ef61b11790c70941cfa4d167b5d20d3a4e9744/libvpl/src/mfx_dispatcher_vpl_loader.cpp#L1551) due to `m_implInfoList` being empty. That list is populated by [`QueryLibraryCaps`](https://github.com/intel/libvpl/blob/79ef61b11790c70941cfa4d167b5d20d3a4e9744/libvpl/src/mfx_dispatcher_vpl_loader.cpp#L889), which in turn requires `m_libInfoList` to be populated. This happens [in `BuildListOfCandidateLibs`](https://github.com/intel/libvpl/blob/79ef61b11790c70941cfa4d167b5d20d3a4e9744/libvpl/src/mfx_dispatcher_vpl_loader.cpp#L428), which ultimately checks the following paths for the libraries, in from highest to lowest priority:

1. `ONEVPL_PRIORITY_PATH` environment variable
2. `LD_LIBRARY_PATH` environment variable
3. `/usr/lib/x86_64-linux-gnu`
4.  `/lib`
5. `/usr/lib`
6. `/lib64`
7. `/usr/lib64`
8. `ONEVPL_SEARCH_PATH` environment variable
9. `/opt/intel/mediasdk/lib`
10. `/opt/intel/mediasdk/lib64`

Thus, setting `ONEVPL_SEARCH_PATH=/app/lib` (where the libraries are actually installed in the Flatpak) resolves the issue. 

### Motivation and Context

Fixes https://github.com/obsproject/obs-studio/issues/9930 (why is this closed?) as well as the off-topic comments of https://github.com/obsproject/obs-studio/issues/9324 and https://github.com/obsproject/obs-studio/issues/9825.

### How Has This Been Tested?

Tested on the current release by appending `ONEVPL_SEARCH_PATH=/app/lib` to the environment variables via [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) with the QuickSync H.264 encoder in recording mode. The `MFX_ERR_NOT_FOUND` error is gone and the encoder starts successfully, producing valid recordings with different settings. My laptop takes a day to build OBS from source, will test this specific commit as soon as I can (update: tested and working).

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
OneVPL adopt a bad behavior by not relying on its install prefix which would add `/app/lib` to the list, so this is a workaround for a bug that needs to be fixed on Intel's upstream.

**Comment by tytan652** [comment]
As a quick review
- The commit name should use "workaround" rather than "fix", not relying on the given prefix at build time is a libvpl bug.
- The commit description should also explain that libvpl does not rely on it's own install prefix but on a mostly hard-coded list or library directories.
- An upstream issue about the non-use of the install prefix on Intel repo should be created.

**Comment by WizardCM** [comment]
Please look over the comments from Tytan above. Outside of that, this PR looks good to me.

**Comment by leodip** [comment]
I would love to see this merged. It should fix https://github.com/obsproject/obs-studio/issues/9930

**Comment by twelho** [comment]
> As a quick review
> 
>     * The commit name should use "workaround" rather than "fix", not relying on the given prefix at build time is a oneVPL/libvpl bug.
> 
>     * The commit description should also explain that libvpl does not rely on it's own install prefix but on a mostly hard-coded list or library directories.
> 
>     * An upstream issue about the non-use of the install prefix on Intel repo should be created.

Sorry for the delay, the feedback should now be addressed. The upstream issue can be found at https://github.com/intel/libvpl/issues/119.

**Pull request merged**
