### PR TITLE
UI: Add OnlyFans login form support and setting form in dock panel.

### PR DESCRIPTION
**Pull request by vitalybulganin**
### Description

I added a new feature, which helps OnlyFans's clients to login to their accounts without leaving the OBS, just open a login form inside the screen. After loggining in a client can see custom dock pane, which keeps useful infomation about stream.

### Motivation and Context

This feature helps our clients have more information about stream on their fingertips without leaving the software.

### How Has This Been Tested?

Tested manually on Windows 11, Ubuntu 22.04 and MacOS.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Please stop opening and closing PRs. Rebase and force push your commits as necessary on the same PR.

**Comment by Fenrirthviti** [comment]
I have some concerns about this PR.

First, please provide confirmation you are a representative of OnlyFans. You have submitted this using a generic email address.

Second, I have concerns about the domain being used for this (`https://obs.onlyfans.retloko.com/`), which to the best of my knowledge, appears to be a personal domain not tied to OnlyFans in any way.

**Comment by vitalybulganin** [comment]
> I have some concerns about this PR.
> 
> First, please provide confirmation you are a representative of OnlyFans. You have submitted this using a generic email address.
> 
> Second, I have concerns about the domain being used for this (`https://obs.onlyfans.retloko.com/`), which to the best of my knowledge, appears to be a personal domain not tied to OnlyFans in any way.

1. I am a software developer at Onlyfans. I was wondering, if you can provide some options which help me to prove it. For instance, I can send my contract or maybe something else? 
2. You are absolutely right. I had talk with our team about this question yesterday. Unfortunately, it was miscommunication and I thought that we are ready to make PR, but I our QA hasn't approved yet. Anyway, this domain is Onlyfans's one, but it uses for dev environment, not for prod. So, could you give me some advise how to the best way to fix this problem? I mean, should I close the PR or just wait for some time and make a new push after our backend will be deployed on prod.

**Comment by Fenrirthviti** [comment]
> 1. I am a software developer at Onlyfans. I was wondering, if you can provide some options which help me to prove it. For instance, I can send my contract or maybe something else?

Since this is dealing with authentication, a verification would be good to be sent to contact@obsproject.com.

> 2. You are absolutely right. I had talk with our team about this question yesterday. Unfortunately, it was miscommunication and I thought that we are ready to make PR, but I our QA hasn't approved yet. Anyway, this domain is Onlyfans's one, but it uses for dev environment, not for prod. So, could you give me some advise how to the best way to fix this problem? I mean, should I close the PR or just wait for some time and make a new push after our backend will be deployed on prod.

I will mark this PR as a draft, and it can be force-pushed later when it's ready. I'd recommend being more careful in the future and not submitted PRs that are not ready.

> To sum up: We decided to close the PR and make a new one from corporate account. I beleive it must be better for futher using in the future. I was appreciate, if it's possible to remove any referrences on our dev server from comments and history.
> 
> Thanks a lot

You can force push your changes, but unfortunately there's not really a way to completely remove those without intervention from GitHub once a PR is submitted.

**Comment by tt2468** [comment]
As I mentioned previously, stop closing and opening PRs. You can use git to force push your changes on the current branch in order to fix existing commits, or you can add fixup commits and squash them in this PR later. Reopening PRs constantly is very spammy.

**Pull request closed without merging**
