### PR TITLE
docs: Fix name of 4th vector of matrix4 t not w

### PR DESCRIPTION
**Pull request by bfxdev**
### Description

Documentation-only fix in the description of the fields of the `matrix4` structure: the 4th vector component is named `t` in the implementation and is currently documented as `w`.

### Motivation and Context

Motivation is mainly correctness of the documentation, and was noticed during the creation of a Lua script. Actually due to current implementation of Lua bindings, using the name `w` led OBS to crash.

### How Has This Been Tested?

No extensive test needed, documentation only.
The correctness of the information was tested in the script at https://github.com/bfxdev/OBS/blob/master/filter-bfx-cpc/filter-bfx-cpc.lua#L134
The information can be checked as well in https://github.com/obsproject/obs-studio/blob/master/libobs/graphics/matrix4.h#L33

### Types of changes

Documentation

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by bfxdev** [comment]
This is my first PR. I see now that some commit rules are not respected but could not be rolled back.

**Comment by Fenrirthviti** [comment]
You can perform a rebase to squash commits and fix up titles. The very nature of git is that everything can always be rolled back and modified.

https://www.git-tower.com/learn/git/faq/git-squash

**Comment by bfxdev** [comment]
Sorry I'm trying to rebase and squash commits but it gets worse and worse instead of reducing . I'll redo the PR from scratch. I fear something is broken in my repository now.

**Comment by bfxdev** [comment]
I plan to **delete my fork of obs-studio** to re-fork a clean repository. Does anything speak against it?

**Pull request closed without merging**
