### PR TITLE
UI: Use constant string as version string

### PR DESCRIPTION
**Pull request by craftwar**
### Description
Version string is always the same, should not be created in runtime. Use
macro to produce it as constant string in compilation.

### Motivation and Context
Reduce binary size obs64.exe from 3341312(156e2f3aeca12c88f6aa46434a372782d4662eec) to 3257344 bytes (82KB).

### How Has This Been Tested?
Run and verify correct version number is displayed in title.

### Types of changes

Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jpark37** [comment]
Have you tested the toStr() macro? I think it's going to return "LIBOBS_API_MAJOR_VER.LIBOBS_API_MINOR_VER.LIBOBS_API_PATCH_VER" instead.

OBS already defines STRINGIFY(x) in libobs/util/base.h

Maybe also make IsPortableMode() const since it's right next door.

**Comment by craftwar** [comment]
Apply jpark37's opinion. Fix code and make IsPortableMode() const.
Sorry I don't have build environment, I test CI build only.

**Comment by jpark37** [comment]
OBS_FULL_VERSION should be defined in terms of OBS_VERSION_NUMBER, not OBS_VERSION. The space before the parenthesis also appears to be missing.

**Comment by Xaymar** [comment]
Is OBS_VERSION_NUMBER supposed to be a string? That seems kinda unintuitive, given that the name contains NUMBER and it is actually a string.

**Comment by Yukeien** [comment]
I don’t think so, there many versions containing dots it would be more likely be a string. In other case we could probably just rename it for OBS_CURRENT_VERSION

**Comment by craftwar** [comment]
I make a change to reuse OBS_VERSION, redefine OBS_VERSION when HAVE_OBSCONFIG_H is not available. More intuitive and less code.

**Comment by jp9000** [comment]
> Reduce binary size obs64.exe from 3341312(156e2f3) to 3257344 bytes (82KB).

I appreciate the pull request, but this is not adequate motivation.

**Pull request closed without merging**
