### PR TITLE
Fixes to make OBS work on Catalina

### PR DESCRIPTION
**Pull request by DDRBoxman**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
URL with a test build artifact. Download build.zip
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=210

**Comment by dellyx0614** [comment]
click Preference is error. How to solve this problem?

**Comment by VKoskiv** [comment]
Just tested this build on my Catalina system.

OBS still crashes when clicking menu items. Here's what the crashed thread was doing:

```
0   com.apple.iokit.IOHIDLib      	0x00000000083f52af 0x83e8000 + 53935
1   com.apple.iokit.IOHIDLib      	0x00000000083f5e3c 0x83e8000 + 56892
2   com.apple.framework.IOKit     	0x00007fff36212dad IOHIDDeviceGetValue + 33
3   libobs.0.dylib                	0x00000001061d0b15 obs_hotkeys_platform_is_pressed + 181
4   libobs.0.dylib                	0x000000010620835d obs_hotkey_thread + 157
5   libsystem_pthread.dylib       	0x00007fff6a94dd76 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff6a94a5d7 thread_start + 15
```

I can reliably reproduce it by opening OBS and clicking the top bar menu icon twice.
It also seems to crash when switching active windows.

I couldn't get the project to build on my config, so I can't debug further myself.

**Comment by DDRBoxman** [comment]
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=237

This should fix a number of issues.

Lua support still needs a fix though.

**Comment by DDRBoxman** [comment]
This should fix Lua

https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=239

**Comment by DDRBoxman** [comment]
Should do a check on the objective c calls to make sure we aren't leaking memory

**Comment by DDRBoxman** [comment]
An additional heads up the build of dylibBundler included in this PR requires code from my branch. 

https://github.com/DDRBoxman/macdylibbundler

**Comment by DDRBoxman** [comment]
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=241

Should fix vst and x264

**Comment by DDRBoxman** [comment]
Looks like my bundler fix got merged :D

https://github.com/auriamg/macdylibbundler/pull/42

**Comment by DDRBoxman** [comment]
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=242

should fix another issue in vst

**Comment by DDRBoxman** [comment]
Fixes text source and adds additional deps for streamdeck

https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=248

**Comment by DDRBoxman** [comment]
Third party plugins will have to have paths updated.

This example fixes ndi and streamdeck
https://gist.github.com/DDRBoxman/d7b14c019a0471ba6f3b5ab0bd3f03e7

**Comment by DDRBoxman** [comment]
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=249

this should make sure libfdk actually gets packaged

**Comment by DDRBoxman** [comment]
https://dev.azure.com/ddrboxman/ddrboxman/_build/results?buildId=251

some quick fixes for the sparkle error, and plist version numbers

**Pull request merged**
