### PR TITLE
Fix loading Lua scripts on Linux through a refactor of how C path are added

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Try to fix the same issue as #10800 but more correctly, as the latter does not work on Linux system install.

This PR reverts #10800 and refactor how C paths are added to enable adding more than two paths.

### Motivation and Context

Fix loading Lua script on Linux.
 If you have a better approach (taking CMake 2 and 3 in mind), please feel free to supersede this PR.

### How Has This Been Tested?

Lua script loads with OBS install system-wide and relocatable.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by PatTheMav — COMMENTED** [review]
Does this affect Windows as well? If so this might need some quick testing on Win as well.

**Comment by tytan652** [comment]
> Does this affect Windows as well?

If you mean the issue for loading the script plugin, I don't think so since nobody reported it on Windows and CMake 3 on Windows is a thing since a while.

Code-wise, the same paths are added to Windows and macOS with or without the PR.
Linux needed a more specific one for CMake 3.

**Review by RytoEX — APPROVED** [review]
I've tested this on Windows against my Lua test script in Portable and non-Portable mode and it seems to continue to work on Windows.

As far as I can tell from reviewing the code, this looks okay.

**Comment by PatTheMav** [comment]
Sounds good to me then.

**Pull request merged**
