### PR TITLE
Update Readme.rst

### PR DESCRIPTION
**Pull request by Ishaan2053**
### Description
Updated the repository's readme.rst file and added the following changes:
- Added alt. text to all links
- Added OBS logo at the top
- Polished the document's appearance
- Rephrased some text

### Motivation and Context
- The readme file on the repo's main page required an overhaul. This PR improves the documentation for easier readability, improved appearance and better comprehension by beginners and advanced users alike.

### How Has This Been Tested?
 - NA

### Types of changes
 - Documentation

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
We have historically rejected third party attempts to simply "prettify" our readme, but this is the closest to an actual cleanup and improvement I've seen to far. Please squash your commits, and update the commit to follow our commit guidelines.

**Comment by Ishaan2053** [comment]
I sure can squash the commits into one. However, I have a question: Maybe this PR can be closed, and the commits can be squashed on your end? (something like the attached screenshot).

image

**Comment by Fenrirthviti** [comment]
I would prefer if you were to make the corrections if you want this to be accepted, especially given the fact that you have checked the box stating you read our guidelines, and that your commits were squashed and formatted correctly, when they were not. If you are unsure how to squash commits, there are plenty of resources available that can show you how.

**Comment by Fenrirthviti** [comment]
As this has not been updated per request, closing.

**Pull request closed without merging**
