### PR TITLE
Transformed x264 plugin into x265.

### PR DESCRIPTION
**Pull request by KOLANICH**
It doesn't work though, but IDK how to fix it. I am not really into codecs ... Feel free to finish the PR.

### Description
Adds x265 plugin.

### Motivation and Context
Currently there is no x265 support in OBS.

### How Has This Been Tested?
It wasn't. It doesn't work.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
For various reasons (mostly licensing), it is unlikely that OBS will ever support HEVC encoding (both hardware and software encoding).

Making a PR that appears to just be the x264 plugin with all mentions of "x264" replaced with "x265" and telling us to "finish it" for you certainly isn't going to help.

**Comment by jp9000** [comment]
`It doesn't work though, but IDK how to fix it. I am not really into codecs ... Feel free to finish the PR.`

Don't submit PRs that you have no intention of finishing yourself. It's rude towards the anyone who volunteers their time to work on this project. You basically copy and pasted the x264 plugin and used find and replace on the word "x264" and replaced it with "x265".

I don't want to see garbage submissions like this ever again.

**Comment by TurnOffNOD** [comment]
> 
> 
> For various reasons (mostly licensing), it is unlikely that OBS will ever support HEVC encoding (both hardware and software encoding).
> 
> Making a PR that appears to just be the x264 plugin with all mentions of "x264" replaced with "x265" and telling us to "finish it" for you certainly isn't going to help.

Hi, sorry for disturbing. But according to this webpage: https://www.videolan.org/developers/x265.html , x265 encoder is released under the terms of the GNU GPL.
Why is there licensing problems?

**Comment by dodgepong** [comment]
The licensing issues aren't with the code, but rather with the HEVC patents.

**Pull request closed without merging**
