### PR TITLE
libobs-opengl: Use PBO for macOS device_stage_texture as same as Linux

### PR DESCRIPTION
**Pull request by norihiro**
### Description

Previously glReadPixels was used to stage surface because Mac had annoying problem.
However, recent MacOS can stage surface as same as Linux code.
This commit removes a switch by __APPLE__ to use glReadPixels.

### Motivation and Context

The motivation of the PR is to improve a plugin [OBS Color Monitor](https://github.com/norihiro/obs-color-monitor), which uses the API `gs_stage_texture`. It is reported the plugin is slower in macOS on [a forum post](https://obsproject.com/forum/threads/obs-color-monitor.143375/#post-527166). The plugin needs to bring textures from GPU to process in CPU to monitor the color information after color correct filters are applied.
The PR should be beneficial for the other plugin [Source Record](https://github.com/exeldro/obs-source-record), which calls the API `gs_stage_texture` as well.

### How Has This Been Tested?

There is a same request on [Mantis 483](https://obsproject.com/mantis/view.php?id=483).Some improvement was reported on its description.
> To my surprise, it appeared to increase performance. According to Instruments, using the PBO-based implementation made the total amount of time spent in device_stage_texture drop from 8.6% to 3.5%. This is a pretty significant speedup.

I also tested with an old mac mini (Early 2009, OS X El Capitan 10.11.6) and it works.
Below is the related lines of a log.
```
CPU Name: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
CPU Speed: 2000MHz
Physical Cores: 2, Logical Cores: 2
Physical Memory: 3072MB Total
OS Name: Mac OS X (NSMACHOperatingSystem)
OS Version: Version 10.11.6 (Build 15G22010)
Kernel Version: 15.6.0
Browser Hardware Acceleration: true
Portable mode: false
OBS 26.1.2-modified (mac)
Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce 9400 OpenGL Engine
OpenGL loaded successfully, version 3.3 NVIDIA-10.0.52 310.90.10.05b46, shading language 3.30
```
I should comment that I didn't see rendering time improvement on my mac.
When I tested above, I temporarily added logs when reached the function and confirmed the new code is working.

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
  - I tested on MacOS 10.11.6, which is older than officially supported version. I'd like to suggest to test on latest OS as well.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.
  - I don't thinks this item is not applicable.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please follow our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/8ec73aea860d6ebb4b97d47201cf2784da8a9da2/CONTRIBUTING.rst#commit-guidelines) for your commit message.

Regarding the code itself, [Mantis 483](https://obsproject.com/mantis/view.php?id=483) also looked into changing this.

**Comment by norihiro** [comment]
I've fixed the message to follow 50/72 standard and capitalized the 1st letter. And also modified some text.
As @RytoEX commented, the ticket [Mantis 483](https://obsproject.com/mantis/view.php?id=483) is changing the same thing.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nitpick:  macOS

Please define "recent MacOS".  What does this mean?  10.15+?  10.13?  10.9?  Be specific.

I'll leave the actual functional review/testing to macOS devs.

**Comment by norihiro** [comment]
> Nitpick: macOS
Fixed.

> Please define "recent MacOS". What does this mean? 10.15+? 10.13? 10.9? Be specific.
Maybe, macOS >= 10.9 but I cannot find good reference which version can work. I revised to mention that current OBS Studio requires `OpenGL 3.3`.
The function glGetTexImage requires OpenGL >= 2.0. OS X 10.8 seems to support MacBook Late 2008, which support up to OpenGL 1.4, for example. Patch versions of OS X 10.8 was released until Aug/2015. On the other hand, the code to be removed by this commit was introduced at Feb/2014. Timeline looks consistent.

**Comment by PatTheMav** [comment]
I'll probably have to investigate what the root cause for the issue was and understand the context first - my OpenGL knowledge is rusty, so it might very well be that this is not needed any more, especially given our minimum requirement of macOS 10.13.

**Comment by RytoEX** [comment]
> > Please define "recent MacOS". What does this mean? 10.15+? 10.13? 10.9? Be specific.
> 
> Maybe, macOS >= 10.9 but I cannot find good reference which version can work. I revised to mention that current OBS Studio requires `OpenGL 3.3`.
> The function glGetTexImage requires OpenGL >= 2.0. OS X 10.8 seems to support MacBook Late 2008, which support up to OpenGL 1.4, for example. Patch versions of OS X 10.8 was released until Aug/2015. On the other hand, the code to be removed by this commit was introduced at Feb/2014. Timeline looks consistent.

That sounds like it lines up.  OBS Studio's original minimum OS version for OSX was 10.8 (see "[OBS Mac 0.2.4](https://github.com/obsproject/obs-studio/releases/tag/0.2.4)").

So others don't have to check git blame, the commit that introduced this in February 2014 being referenced is:  https://github.com/obsproject/obs-studio/commit/30af7dc211d401425173a0becf17f983085adece

**Comment by norihiro** [comment]
The commit message is revised to describe which macOS version should work.
The description of the PR is edited to describe further motivations who will have benefits.

**Comment by WizardCM** [comment]
Documenting for posterity - this was reverted in 9bd9513e944b649410d0e120405e66cc44ed3428. It seems this PR introduces poor performance on Monterey. The user reproduced it with a Decklink source in 4K.

**Comment by norihiro** [comment]
The poor performance was reported with this log on beta-test channel on Discord.
https://obsproject.com/logs/rdc31ek82dnwV4PM

After reverting, the user reported the performance issue was resolved.

The key logs are as below.
CPU and OS info:
```
19:01:23.151: CPU Name: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz
19:01:23.151: CPU Speed: 3200MHz
19:01:23.151: Physical Cores: 16, Logical Cores: 32
19:01:23.151: Physical Memory: 98304MB Total
19:01:23.151: OS Name: Mac OS X
19:01:23.151: OS Version: Version 12.0.1 (Build 21A559)
19:01:23.151: Kernel Version: 21.1.0
```
GPU:
```
19:01:23.233: Initializing OpenGL...
19:01:23.278: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon PRO W6800X Duo OpenGL Engine
19:01:23.279: OpenGL loaded successfully, version 4.1 ATI-4.7.29, shading language 4.10
```
Video settings:
```
19:01:23.380: video settings reset:
19:01:23.380: 	base resolution:   3840x2160
19:01:23.380: 	output resolution: 3840x2160
19:01:23.380: 	downscale filter:  Lanczos
19:01:23.380: 	fps:               60/1
19:01:23.380: 	format:            NV12
19:01:23.380: 	YUV mode:          709/Partial
19:01:23.380: NV12 texture support not available
```
Profile of graphics thread:
```
19:02:01.831: obs_graphics_thread(16.6667 ms): min=0.049 ms, median=16.825 ms, max=205.129 ms, 99th percentile=20.821 ms, 46.0633% below 16.667 ms
19:02:01.831:  ┣tick_sources: min=0 ms, median=0.023 ms, max=178.348 ms, 99th percentile=0.072 ms
19:02:01.831:  ┣output_frame: min=0.044 ms, median=16.281 ms, max=36.018 ms, 99th percentile=20.108 ms
19:02:01.831:  ┃ ┣gs_context(video->graphics): min=0.043 ms, median=14.692 ms, max=36.017 ms, 99th percentile=18.299 ms
19:02:01.831:  ┃ ┃ ┣render_video: min=0.015 ms, median=14.68 ms, max=36.009 ms, 99th percentile=18.25 ms
19:02:01.831:  ┃ ┃ ┃ ┣render_main_texture: min=0.013 ms, median=3.522 ms, max=29.59 ms, 99th percentile=4.869 ms
19:02:01.831:  ┃ ┃ ┃ ┣render_convert_texture: min=0.025 ms, median=0.067 ms, max=8.502 ms, 99th percentile=1.973 ms, 0.584163 calls per parent call
19:02:01.831:  ┃ ┃ ┃ ┗stage_output_texture: min=9.855 ms, median=11.19 ms, max=24.236 ms, 99th percentile=14.295 ms, 0.584163 calls per parent call
19:02:01.831:  ┃ ┃ ┣gs_flush: min=0.001 ms, median=0.001 ms, max=2.296 ms, 99th percentile=0.119 ms
19:02:01.831:  ┃ ┃ ┗download_frame: min=0 ms, median=0.002 ms, max=0.03 ms, 99th percentile=0.003 ms, 0.584163 calls per parent call
19:02:01.831:  ┃ ┗output_video_data: min=1.416 ms, median=1.548 ms, max=7.58 ms, 99th percentile=2.095 ms, 0.58371 calls per parent call
19:02:01.831:  ┗render_displays: min=0 ms, median=0.482 ms, max=21.244 ms, 99th percentile=1.28 ms
```

**Pull request merged**
