### PR TITLE
libobs: Extra callback when removing scene

### PR DESCRIPTION
**Pull request by sora-blue**
### Description

This small patch ensures media source to be removed when being removed with scene.

### Motivation and Context

This PR is to fix [issue #6145 ](https://github.com/obsproject/obs-studio/issues/6145).

### How Has This Been Tested?

The effect is tested on my computer running Windows 10 21H2 and it solves the problem.
But i'm not sure if extra codes are needed to prevent affecting other functions.

### Types of changes

Bug fix

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
As mentioned in https://github.com/obsproject/obs-studio/issues/6145 I'm not able to reproduce the issue, but maybe I'm mistaken and the issue is still present?

Please confirm or otherwise close the PR as it might not be needed anymore.

**Comment by sora-blue** [comment]
Hi there. I tested it with obs 30.0.0 on win11x64, and it seems still being a problem. But since it had been a year and half ago, the PR may need further debug.
image

**Comment by PatTheMav** [comment]
> Hi there. I tested it with obs 30.0.0 on win11x64, and it seems still being a problem. But since it had been a year and half ago, the PR may need further debug. image

What are the exact reproduction steps?

I tried adding the source with a show transition set to 5 seconds, then deleted the source while the transition was running. Both sources (media source and transition) were correctly removed then.

**Review by derrod — APPROVED** [review]
Commit message is maybe not the best, but I believe this change is correct as this callback should also enumerate the underlying source if it is active.

**Review by PatTheMav — APPROVED** [review]
The underlying issue is that in the case of a scene destruction some part of the program holds a reference to the media source (could be the UI thread, the source toolbar, or something else) which prevents it from being scheduled for destruction in the helper thread.

Ensuring that the enumeration callback runs even during a show transition seems to also lead to these references being released.

**Comment by sora-blue** [comment]
> What are the exact reproduction steps?
> 
> I tried adding the source with a show transition set to 5 seconds, then deleted the source while the transition was running. Both sources (media source and transition) were correctly removed then.

Here's a recorded reproduction process for it.
[](https://freeimage.host/i/JISE2Ub)

**Pull request merged**
