### PR TITLE
linux-v4l2: Fixup invalid id

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

Previous fix in #2547 altered id before they were handed off to
callbacks and v4l2 wont strip its own flags from ids resulting in
invalid ids in the ioctl.

Instead add cleanup section and jump all branches there before looping.

### Motivation and Context

Previous code results in invalid states being set and device reset loops after the first opening of obs.

### How Has This Been Tested?

I opened obs multiple times and slide sliders till my device reset. It was able to recover from resets now.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jhilliker** [comment]
issue & fix confirmed

**Comment by kkartaltepe** [comment]
User in support has also confirmed this resolves the issue safely.

**Comment by PeteDevoy** [comment]
I built from master branch this morning and was hitting the `v4l2` looping issue when opening the 'Properties' window for a USB webcam on Ubuntu 18.04.

I found this page so built from `kkartaltepe:v4l2-fix-for-real` it wasn't crashing instantly after opening the properties window like before but after adjusting the sliders for about one minute it did crash on the exposure slider:

```
info: v4l2-input: Stopped capture after 106 frames
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
error: v4l2-input: Unable to set format
error: v4l2-input: Initialization failed
info: v4l2-input: Start capture from /dev/video0
error: v4l2-input: Unable to open device
error: v4l2-input: Initialization failed
```

This PR does make the Properties window usable, just including my experience to let you folks know there may still be a bug there.  Please feel free to ping me if you want more info.

**Comment by kkartaltepe** [comment]
My device also resets (so slowly v4l2 source needs to reinitialize) when changing some sliders like zoom/pan/exposure. Did you find that your device didnt survive the reset and you had to restart obs/replug your device?

**Comment by PeteDevoy** [comment]
@kkartaltepe yes, exactly.  I tried to close OBS through the GUI and after a couple of minutes it did manage to close.  I reopened OBS but the webcam did not work until I replugged it.

**Pull request merged**
