### PR TITLE
frontend-tools: Add edit script button

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Add button "Edit Script" to the scripts window
image

### Motivation and Context
To make it easy to edit the scripts you use.

### How Has This Been Tested?
On windows 64 bit by loading some scripts and clicking the new "Edit Script" button.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
If I'm understanding this correctly, this is opening the script in the defined editor for that filetype?

**Comment by exeldro** [comment]
@Fenrirthviti Yes, it does

**Comment by Fenrirthviti** [comment]
I would prefer the button said "Edit Script" instead of the ambiguous "Open Scripts". With the word `Open` and the plural `Scripts`, I assumed this was opening the directory of where script files were at first glance. I had to look at the code to see what was actually happening. That aside, seems like a fine addition.

**Comment by jp9000** [comment]
This will open the file with whatever programs's associated with it, not necessarily an editor.  Is it unwise to assume it has the correct program association with the file extension?

**Comment by exeldro** [comment]
For opening log files the same kind of assumption is done. 
I think ”Open in OS assigned program for lua or python files" or something like that does not make it better.

**Comment by Fenrirthviti** [comment]
I agree. This paradigm is present in virtually any other application that uses it. If it opens in notepad, you're still editing the file, and notepad is a text editor so I don't think it's a concern.

**Comment by WizardCM** [comment]
Friendly bump: this PR has merge conflicts.

**Comment by PatTheMav** [comment]
Just rebased this and checked it locally - seems fine to me.

**Pull request merged**
