### PR TITLE
Revert "UI: Change default format for release builds to fMP4/fMOV"

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

This reverts commit 9488bb20b68ef2ca12a4f3eb040f56762c6f1447.

### Motivation and Context

This is currently a frequent support issue as Windows Media Player, Movies & TV, and File Explorer all cannot seem to handle fMP4 files correctly. Windows Media Player and Movies & TV will play the files fine, but no duration is listed and the applications cannot seek the file. File Explorer will simply not list the file's length/duration (the field is shown as having no set value). This was somehow not caught during a year's worth of beta and RC builds. The world just wasn't ready for this. =(

For the record, we have reported these issues to Microsoft.

### How Has This Been Tested?

I haven't tested this, but as this is a revert it should be fine. We've used the previous code for a year prior.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — COMMENTED** [review]
If the main consideration is "This doesn't work with the default OS media player and tools", imo this should be limited to Windows (and maybe Linux).
On macOS, QuickTime Player (the default video player) deals just fine with Fragmented MOV but it can't even play MKV, so on macOS we'd be going back to the situation that this PR tries to fix to Windows.

**Comment by RytoEX** [comment]
> If the main consideration is "This doesn't work with the default OS media player and tools", imo this should be limited to Windows (and maybe Linux). On macOS, QuickTime Player (the default video player) deals just fine with Fragmented MOV but it can't even play MKV, so on macOS we'd be going back to the situation that this PR tries to fix to Windows.

I'm not really willing to muck around with fine-tuning this for cherry-picking to 30.1.2. If someone wants to adjust this _after_ the revert, by all means.

**Review by Fenrirthviti — APPROVED** [review]
Approved. Something something video editors will cry.

**Comment by Fenrirthviti** [comment]
Also unless I'm missing something, this revert should still set the default to fMP4 on macOS?

**Comment by RytoEX** [comment]
> Also unless I'm missing something, this revert should still set the default to fMOV on macOS?
 
Seems that way.

**Pull request merged**
