### PR TITLE
Add option to use TCP for RTSP stream

### PR DESCRIPTION
**Pull request by stopforumspam**
### Description
Add option to use TCP for RTSP stream instead of RTSP only using UDP for the streaming transport

### Motivation and Context
obs-studio currently only supports the ffmpeg default UDP transport for RTSP.
Some feeds and cameras, in particular Ubiquiti IP cameras, can suffer from frame and stream corruption when using UDP.  
This was the motivation for this patch, to avoid having to use tunnels or proxies that convert the RTSP transport from UDP to TCP.
Ubiquiti support suggest that ffmpeg/vlc based clients use TCP instead of UDP when experiencing corruption.
This patch adds support for the `ffmpeg -rtsp_transport tcp` feature

### How Has This Been Tested?
I've tested this over a couple of days using Ubiquiti G3-flex and Ubiquiti G3-bullet cameras which were experiencing video corruption issues like that reported in https://github.com/obsproject/obs-studio/issues/3684
Testing ran under Visual Studio debugger to monitor for memory leaks, ffmpeg frame and stream processing reports, visible frame failures and stream interruption, and any TCP reconnection issues.  No issues were found

### Types of changes
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
I don't really agree with the design of this, protocol specific options shouldn't be showing up on every media source. 

A generic protocol options field is probably better that allows setting any of options without the UI becoming protocol-specific.

**Comment by stopforumspam** [comment]
> I don't really agree with the design of this, protocol specific options shouldn't be showing up on every media source.
> 
> A generic protocol options field is probably better that allows setting any of options without the UI becoming protocol-specific.

I thought about that as well but if you have two RTSP sources, one that you want TCP and the other UDP, then you cant unless you have it as a per source option.  I have a v4l2rtspserver and an Ubiquiti camera.  the first works fine on UDP, the camera needs TCP, hence why I configured it this way.

**Comment by notr1ch** [comment]
I meant more in the sense of a free-form text field "Protocol options: xxx" that allows users to add "rtsp_transport=tcp" for example, or any options relevant to the transport protocol in the URL.

**Comment by stopforumspam** [comment]
Maybe a free form field with some character delimiter, that allows you to pass any parameters to ffmpeg? They have to be parsed and added to the options but its possible  but this would allow a per media source option that allows the user to add any option to be added although I had no idea how that would impact obs
________________________________

**Pull request closed without merging**
