### PR TITLE
rtmp-services: Add BitChute

### PR DESCRIPTION
**Pull request by tanchute**
### Description

Incorporating BitChute into OBS-Studio's Ingest List

### Motivation and Context

This pull request aims to add BitChute (https://www.bitchute.com), a widely-used video sharing platform, to the ingest list of OBS-Studio. BitChute has established itself with a large user base over the years. Integrating BitChute into OBS-Studio will simplify the process for users to stream directly to BitChute.This pull request aims to add BitChute (https://www.bitchute.com/), a widely-used video sharing platform, to the ingest list of OBS-Studio. BitChute has established itself with a large user base over the years. Integrating BitChute into OBS-Studio will simplify the process for users to stream directly to BitChute.

### How Has This Been Tested?

**Testing Procedure**

* **JSON Validation**: Verified that the JSON files are correctly formatted and conform to the standards required by OBS-Studio.
* **Copy JSON Files**: Transferred the JSON files to \~/.config/obs-studio/plugin_config/rtmp-services on a Linux system, ensuring OBS-Studio can access the updated settings.
* **Settings Verification**: Confirmed that BitChute appears in the updated ingest list within the OBS-Studio settings menu.
* **Connection Testing**: Successfully connected to BitChute servers to ensure streaming functionality is operational.

image
image

### Types of changes

**New Feature**: This change introduces new functionality without breaking existing features.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tanchute** [comment]
Sorry, it's a bit of a mess. It should be good now.

Note
update version number and fix conflict

**Comment by Fenrirthviti** [comment]
Thank you for the submission, but BitChute does not currently meet our requirements to be listed in OBS.

**Comment by tanchute** [comment]
@Fenrirthviti 

Thank you for the feedback. Could you please let us know which specific requirement BitChute does not meet so we can address it?

**Comment by ScottCute** [comment]
Seems a bit sketchy @MasterKia is right, a lot worse content on Youtube and Twitch seems like we will never know the true reason lucky users do not need Bitchute in the list to be able to use OBS.

**Comment by Fenrirthviti** [comment]
The requirements are linked in the contributing guidelines.

https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines

**Comment by ScottCute** [comment]
> The requirements are linked in the contributing guidelines.
> 
> https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines

I can not seem to find that actual reason for this ? You support Youtube and Twitch why would this site be any different ??
Bitchute is part of the same industry bodies as Youtube and has the same governing bodies manage the content its allowed. 

Would you be able to give a actual reason for your decision ?

**Comment by ScottCute** [comment]
@Fenrirthviti I see now "we may deny a service for any reason." well played :)

**Pull request closed without merging**
