### PR TITLE
rtmp-services: Add Nimo TV

### PR DESCRIPTION
**Pull request by dgeibi**
### Description

- Add ingest list for Nimo TV
- Add support for Nimo TV "Auto" server

### Motivation and Context

- The ability to select a server based on user location.
- Limit the maximum bitrate to improve service quality.

### How Has This Been Tested?

Tested on Windows 10 and Mac OS X 10.15.3.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by notr1ch** [comment]
It looks like the `txpush` URLs are not valid.

```
Checking Nimo TV / Global:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / Global:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'Global:2'
Checking Nimo TV / asia,brunei darussalam:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,brunei darussalam:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,brunei darussalam:2'
Checking Nimo TV / asia,cambodia:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,cambodia:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,cambodia:2'
Checking Nimo TV / asia,hong kong:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,hong kong:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,hong kong:2'
Checking Nimo TV / asia,india:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,india:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,india:2'
Checking Nimo TV / asia,india:3: alpush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,indonesia:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,indonesia:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,indonesia:2'
Checking Nimo TV / asia,indonesia:3: alpush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,lao people_s democratic republic:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,lao people_s democratic republic:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,lao people_s democratic republic:2'
Checking Nimo TV / asia,malaysia:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,malaysia:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,malaysia:2'
Checking Nimo TV / asia,philippines:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,philippines:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,philippines:2'
Checking Nimo TV / asia,philippines:3: alpush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,singapore:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,singapore:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,singapore:2'
Checking Nimo TV / asia,thailand:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,thailand:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,thailand:2'
Checking Nimo TV / asia,thailand:3: alpush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,viet nam:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / asia,viet nam:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,viet nam:2'
Checking Nimo TV / asia,viet nam:3: alpush.rtmp.nimo.tv:1935
Checking Nimo TV / north america,mexico:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / north america,mexico:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'north america,mexico:2'
Checking Nimo TV / south america,brazil:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / south america,brazil:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'south america,brazil:2'
Checking Nimo TV / south america,peru:1: wspush.rtmp.nimo.tv:1935
Checking Nimo TV / south america,peru:2: txpush.rtmp.nimo.tv:1935
ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'south america,peru:2'
```

**Comment by Alex--wu** [comment]
> It looks like the `txpush` URLs are not valid.
> 
> ```
> Checking Nimo TV / Global:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / Global:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'Global:2'
> Checking Nimo TV / asia,brunei darussalam:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,brunei darussalam:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,brunei darussalam:2'
> Checking Nimo TV / asia,cambodia:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,cambodia:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,cambodia:2'
> Checking Nimo TV / asia,hong kong:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,hong kong:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,hong kong:2'
> Checking Nimo TV / asia,india:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,india:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,india:2'
> Checking Nimo TV / asia,india:3: alpush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,indonesia:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,indonesia:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,indonesia:2'
> Checking Nimo TV / asia,indonesia:3: alpush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,lao people_s democratic republic:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,lao people_s democratic republic:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,lao people_s democratic republic:2'
> Checking Nimo TV / asia,malaysia:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,malaysia:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,malaysia:2'
> Checking Nimo TV / asia,philippines:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,philippines:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,philippines:2'
> Checking Nimo TV / asia,philippines:3: alpush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,singapore:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,singapore:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,singapore:2'
> Checking Nimo TV / asia,thailand:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,thailand:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,thailand:2'
> Checking Nimo TV / asia,thailand:3: alpush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,viet nam:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / asia,viet nam:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'asia,viet nam:2'
> Checking Nimo TV / asia,viet nam:3: alpush.rtmp.nimo.tv:1935
> Checking Nimo TV / north america,mexico:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / north america,mexico:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'north america,mexico:2'
> Checking Nimo TV / south america,brazil:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / south america,brazil:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'south america,brazil:2'
> Checking Nimo TV / south america,peru:1: wspush.rtmp.nimo.tv:1935
> Checking Nimo TV / south america,peru:2: txpush.rtmp.nimo.tv:1935
> ERROR: Couldn't resolve 'txpush.rtmp.nimo.tv' for 'Nimo TV' / 'south america,peru:2'
> ```

Hello,

Could you re-check it please? I checked it on the https://www.whatsmydns.net/#CNAME/txpush.rtmp.nimo.tv and https://dnschecker.org/#A/txpush.rtmp.nimo.tv   . Both of them seems working fine. And I asked my colleague to test it in US. it also working. It seems like occasional DNS problem.

Anyway we opened a high priority case for our suppliers to check it. If you could provide your ip info it would be very helpful. :)

Alex WU,
NiMO TV

**Comment by Alex--wu** [comment]
@notr1ch Hello, could you please help review this? Thank you :)

**Comment by Alex--wu** [comment]
@notr1ch Hello, we use GSLB(Global Server Load Balancing) to control traffic amongst servers potentially dispersed across multiple geographies. These three hostname are three CDN suppliers，each of them has their own Global DNS Load Balancing.

However, not all the countries / areas has CDN PoPs, that's why we separate the server names. 
Anyway I will discuss it again with our Engineers.

**Comment by Alex--wu** [comment]
@notr1ch We change the default selection in the services.json file. Please check it. :)

**Pull request closed without merging**
