### PR TITLE
Update translations from Crowdin

### PR DESCRIPTION
**Pull request by Vainock**
### Description
Update translations from Crowdin for the 30.1.0 release.

### Motivation and Context
Crowdin's API is currently broken -> failing translation update action: https://community.crowdin.com/t/unable-to-list-blocked-users-via-api/6981/2

### How Has This Been Tested?
/

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Vainock** [comment]
I might force push further translation updates over the coming days as long as this PR isn't merged.

**Comment by RytoEX** [comment]
> I might force push further translation updates over the coming days as long as this PR isn't merged.

It will probably be merged within the next 12-24 hours.

**Review by RytoEX — APPROVED** [review]
This by itself seems fine.

I did noticed that there is a newly added locale set (kaa.ini, Karakalpak / Qaraqalpaqsha), and while it is copied to the OBS Studio build, it does not show up in the UI as an option.

Looking into that, I noticed that there are currently 52 languages in `UI/data/locale.ini` (the file the provides the list of available languages to select in Settings), but 74 different locale files in `UI/data/locale`. The last update to `UI/data/locale.ini` was two years ago by the Translation Updater (https://github.com/obsproject/obs-studio/commit/ac8dbf67be1ff7d3c137cc2484afc7a3b0624ee4). I am happy to update this file manually, but am wondering why the Translation Updater has not updated it since then. That issue is out of scope for this PR, but I wanted to document it somewhere.

**Comment by RytoEX** [comment]
> I did notice that there is a newly added locale set (kaa.ini, Karakalpak / Qaraqalpaqsha), and while it is copied to the OBS Studio build, it does not show up in the UI as an option.
> 
> Looking into that, I noticed that there are currently 52 languages in `UI/data/locale.ini` (the file the provides the list of available languages to select in Settings), but 74 different locale files in `UI/data/locale`. The last update to `UI/data/locale.ini` was two years ago by the Translation Updater ([ac8dbf6](https://github.com/obsproject/obs-studio/commit/ac8dbf67be1ff7d3c137cc2484afc7a3b0624ee4)). I am happy to update this file manually, but am wondering why the Translation Updater has not updated it since then. That issue is out of scope for this PR, but I wanted to document it somewhere.

I see now that this is based on locale translation progress, so this is probably fine. I didn't cross-check the language lists, but the check itself seems fine.
https://github.com/obsproject/obs-crowdin-sync/blob/30b5446e3b5eb19595aa68a81ddf896a857302cf/src/download.ts#L391

**Pull request merged**
