### PR TITLE
UI: Import Streamlabs Screen Capture source type

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Add support for importing the Screen Capture source type from Streamlabs scene collections. Since the Screen Capture source type is essentially an abstraction layer for Display Capture, Game Capture, and Window Capture, this adds some translation logic to translate Screen Capture sources into one of those source types.

Caveat:  since the target of the game capture subtype does not seem to be exposed, this does not specify a target process for that source.

That said, this should still be an improvement over failing to create a suitable source at all.

### Motivation and Context

We should support imports for as many source types as possible.

### How Has This Been Tested?

I've tested this with all three subtypes (Display, Game, Window) on my Windows 10 machine.  Could use additional testing for machines with multiple displays.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
> since the target of the game capture subtype does not seem to be exposed, this does not specify a target process for that source.

It would appear that the either use their [Auto game capture mode](https://github.com/stream-labs/obs-studio/pull/161), or "capture any fullscreen application" mode: https://github.com/stream-labs/obs-studio/blob/153051426200f79da21c7546a847ddc040672cef/plugins/win-capture/screen-capture.c#L462-L469

**Comment by RytoEX** [comment]
> 
> 
> > since the target of the game capture subtype does not seem to be exposed, this does not specify a target process for that source.
> 
> It would appear that they either use their [Auto game capture mode](https://github.com/stream-labs/obs-studio/pull/161), or "capture any fullscreen application" mode: https://github.com/stream-labs/obs-studio/blob/153051426200f79da21c7546a847ddc040672cef/plugins/win-capture/screen-capture.c#L462-L469

My assumption was the former.  I mostly meant that if they are using their auto game capture mode, then we have no way to know which application was detected.  In this case, it seems that it will import as "Capture any fullscreen application", which should be an acceptable step in the right direction, but let me know if more work needs to be done here.

**Comment by dodgepong** [comment]
I think "Capture any fullscreen application" is probably the least-bad fallback. Obviously it won't work for every case, but it's the closest analogue we have.

**Comment by RytoEX** [comment]
> 
> 
> I think "Capture any fullscreen application" is probably the least-bad fallback. Obviously it won't work for every case, but it's the closest analogue we have.

At the very least, this will create the appropriate source type (game capture) in the canvas location where it should be with our default settings. I'm not sure of anything else we could do here.

**Pull request merged**
