### PR TITLE
obs-text, text-freetype2: Add Enable Antialiasing option

### PR DESCRIPTION
**Pull request by Codex-**
### Description

This PR adds the option to disable antialiasing on font rendering. 

✅ Antialiasing is **Enabled** by default (the current behaviour).

### obs-text
image

The added option in the UI:
image

A scene with various text-gdi sources:
Before:
image

After:
image

A scene with a mixture of enabled and disabled:
image

### text-freetype2
The added option in the UI:
image

A scene with various text-freetype2 sources:
Before:
image

After:
image

A scene with a mixture of enabled and disabled:
image

### Motivation and Context

Some fonts are styled in such a way that antialiasing them makes them unreadable or look undesirable, these being mainly pixel fonts.

With antialiasing disabled, pixel fonts become clear and easy to read.

### How Has This Been Tested?

Tested with both regular and pixel fonts, enabling and disabling to ensure that live changes are made.

- Add a text-gdi source.
- Disable antialiasing.
- Restart OBS to ensure setting persists.
- Enable antialiasing.
- Restart OBS to ensure setting persists.

Create a scene with various combinations of text off and on.

These steps have been repeated now with freetype2.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by RytoEX** [comment]
How does this compare to behavior in the FreeType2 text source?

**Comment by Codex-** [comment]
> How does this compare to behavior in the FreeType2 text source?

Good question. I couldn't get any fonts to render using FreeType2 with OBS on Windows. I'll have to have another look on Manjaro.

From reading the FT API I should be able to achieve similar a similar AA option by experimenting with the `FT_Render_Mode` that is supplied to `FT_Render_Glyph` in `text-functionality.c`.

I would have thought it best to complete these changes as a separate pull request if I were to complete them though, to keep the contexts of the PR's clean.

**Comment by RytoEX** [comment]
FreeType2 sources in OBS work fine for me in Windows.

As I understand it, Jim wants the "Text (GDI+)" source (plugins/obs-text) and the "Text (FreeType 2)" source (plugins/text-freetype2) to maintain feature parity where possible, so feature additions to one should also be done on the other.  Given that it's essentially adding the same feature to the two text sources, I'd say both changes _can_ be made in the same PR, but they would need to be different commits with appropriate prefixes ("obs-text: ", "text-freetype2: ").  If you prefer, they can be submitted as separate PRs as you suggested.

**Comment by Codex-** [comment]
That's reasonable. Ftr this is what happens when I try to use freetype2 on windows:
image
Mixed results.

I made the changes to do some testing on linux but found that the generated output wouldn't run as it seems to fail to run streams and the locale generation doesn't run. I'll keep battling and see what I can do.

**Comment by RytoEX** [comment]
Works fine for me in the current Windows release.
image

**Comment by Codex-** [comment]
Not sure why it would differ, this is from the public release too, not my own build.
This is with Windows 10.0.18363 (1909).

There's a non-zero chance it doesn't like the fonts / isn't 100% compatible with TTF.

Regardless, digressions aside, i'll add the option into freetype2 and see what we can come up with.

**Comment by RytoEX** [comment]
If you can add the options, I'm sure someone else here can build and test.

**Comment by Codex-** [comment]
Have been looking at this for most of the day for freetype, it's turning out to be a large piece of work and requires  different scaling for populating the buffers. I'll keep looking but this will definitely be a seperate review.

freetype is proving to be a fickle beast.

**Comment by Codex-** [comment]
Update: After many headaches I have this option working with freetype. I've also identified the issue in Windows where freetype fails to load certain fonts, I'll be working on a fix for this separately and will make a PR for this.

I should have the freetype AA option feature completed in the next night or so :)

**Comment by Codex-** [comment]
@RytoEX added the commit with the changes for freetype2 :) apologies for the delays, had some friends review the changes and improved some things based on their feedback.

**Pull request merged**
