### PR TITLE
cmake: Fix win compile issue

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Description

- add the missing wasapi-notify.cpp wasapi-notify.hpp to wasapi legacy_check.cmake
- add the missing link libraries d3dcompiler to libobs-d3d legacy_check.cmake
### Motivation and Context

N/A
### How Has This Been Tested?

I am tested by cmake and msvc 2022 compiled.
### Types of changes

fix win compile issue
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by wanhongqing123** [comment]
fix win compile issue

**Comment by PatTheMav** [comment]
@RytoEX is it worth merging this or do we consider this superfluous given the planned obsolescence of the Windows legacy build path?

**Comment by wanhongqing123** [comment]
你的邮件已收到，我会尽快的回复你

**Comment by RytoEX** [comment]
> @RytoEX is it worth merging this or do we consider this superfluous given the planned obsolescence of the Windows legacy build path?

If they are legitimate fixes, then I'm fine with us merging them. However, as noted, the legacy build path is due for deprecation and eventual removal, and we should make sure to emit warnings in the CMake log about the deprecation and planned removal.

**Comment by PatTheMav** [comment]
> > @RytoEX is it worth merging this or do we consider this superfluous given the planned obsolescence of the Windows legacy build path?
> 
> If they are legitimate fixes, then I'm fine with us merging them. However, as noted, the legacy build path is due for deprecation and eventual removal, and we should make sure to emit warnings in the CMake log about the deprecation and planned removal.
> 
> That said, the commit message and PR title will need revised to comply with our commit guidelines.

That warning is implemented in the CMake update for Linux.

I honestly don't know why those changes are not contained in the legacy files, maybe overlooked when we recently updated something regarding the shader parsing/precaching on Windows.

**Comment by wanhongqing123** [comment]
Can it be merged? This change is just a compilation issue

**Comment by wanhongqing123** [comment]
Can it be merged? This change is just a compilation issue @WizardCM @PatTheMav @RytoEX

**Comment by wanhongqing123** [comment]
> > > @RytoEX is it worth merging this or do we consider this superfluous given the planned obsolescence of the Windows legacy build path?
> > 
> > 
> > If they are legitimate fixes, then I'm fine with us merging them. However, as noted, the legacy build path is due for deprecation and eventual removal, and we should make sure to emit warnings in the CMake log about the deprecation and planned removal.
> > That said, the commit message and PR title will need revised to comply with our commit guidelines.
> 
> That warning is implemented in the CMake update for Linux.
> 
> I honestly don't know why those changes are not contained in the legacy files, maybe overlooked when we recently updated something regarding the shader parsing/precaching on Windows.

Complete

**Comment by wanhongqing123** [comment]
> > > That said, the commit message and PR title will need revised to comply with our commit guidelines.
> > 
> > 
> > Complete
> 
> > cmake:fix win compile issue
> 
> And the commit message, please.

Complete

image

**Comment by wanhongqing123** [comment]
你的邮件已收到，我会尽快的回复你

**Comment by RytoEX** [comment]
To follow-up, what happened here was that I had, unfortunately, forgotten this PR existed. I went to go test the legacy CMake path to assist someone else, ran into this problem, debugged locally, wrote the patches, and had submitted a PR before someone reminded me this one did exist. It's been a busy year, and this just fell off my radar. My apologies.

**Pull request closed without merging**
