### PR TITLE
cmake: Install desktop files and icons on FreeBSD

### PR DESCRIPTION
**Pull request by vishwin**
### Description
Copy the desktop file and icon routine from `os-linux.cmake` so that FreeBSD gets these installed too.

### Motivation and Context
FreeBSD can generally run the same desktop environments that use these files as Linux. Without these files, icons and application launchers do not populate in these desktops. These files were previously installed prior to the CMake refactor here.

### How Has This Been Tested?
Built as usual on FreeBSD-CURRENT.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
cc @emaste

**Comment by norihiro** [comment]
commit f3e9b71dd has an invalid title text. The first word (`install`) should be capitalized.
> install desktop files and icons on FreeBSD

**Review by agility382499 — COMMENTED** [review]
Ok i

**Comment by emaste** [comment]
Commit message aside LGTM

**Review by PatTheMav — APPROVED** [review]

**Pull request merged**
