### PR TITLE
CI: Set default values for have* outputs in macos-codesigning action

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

The `provisioning` and `notarization` steps that set the `haveProvisioningProfile` and `haveNotarizationUser` outputs respectively only run if `haveCodesignIdent` has evaluated to true in the prior `codesign` step.
This means that if `haveCodesignIdent` is false, the other two outputs are left unset, evaluating their `value` expressions (and as such the output of the action) to empty instead of false. To mitigate that, we can just add a `|| 'false'` to set the value to false in case it isn't set.
Strictly speaking it's unnecessary for `haveCodesignIdent` as that always runs but to me it makes sense just to set it to all.

I found this issue in the [equivalent action](https://github.com/obsproject/obs-plugintemplate/blob/e3688b7491c52ef6e37ac59daa93e7cf4d9e2b28/.github/actions/setup-macos-codesigning/action.yaml) in obs-plugintemplate. As that action is basically a mirror from the obs-studio action, let's fix it here too.

As there are [more](https://github.com/obsproject/obs-studio/commit/401aa7933ac6e88680cd0fe46456da48c33b2d73) [changes](https://github.com/obsproject/obs-studio/commit/a2c0d4969aa35067455814d20cc87f9f9486c370#diff-aaf7b09bfa61dd42dd6ea034c5645697aecd139321722b6eddcfc2e9db9955a4) that didn't make it into the plugintemplate yet (but are needed there), I plan to update that after this PR has been merged.

### Motivation and Context

I noticed CI failures when updating a plugin to the current template's build system and CI setup without having signing and notarization secrets set (because I don't have any :p).

### How Has This Been Tested?

On CI on a plugin based on the template.

Run Before: https://github.com/gxalpha/obs-properties-dock/actions/runs/10829574145/job/30047436956
Run After: https://github.com/gxalpha/obs-properties-dock/actions/runs/10830053045/job/30048940631

Commit: https://github.com/gxalpha/obs-properties-dock/commit/c5807d3d1050201de9d415ccbcd7b688c528933b (ignore the deletion below, that was code from an unsuccessful earlier attempt).

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [N/A] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by PatTheMav — CHANGES_REQUESTED** [review]
It's probably simpler to just add

```bash
print 'haveProvisioningProfile=false' >> $GITHUB_OUTPUT
print 'haveNotarizationUser=false' >> $GITHUB_OUTPUT
```
in the `codesign` step's `false` branch.

As that conditional is also the reason why the `provisioning` and `notarization` steps will not run.

Coalescing to a `false` value in the outputs by default has the side-effect of providing valid outputs even if the action ends up in an undefined state, thus putting the entire workflow into undefined state.

**Comment by gxalpha** [comment]
I actually tried that initially (see the linked commit in the testing section), the problem is that those are in different steps. You would then have both `steps.codesign.outputs.haveProvisioningProfile` and `steps.provisioning.outputs.haveProvisioningProfile`, the latter still being unset.

**Comment by gxalpha** [comment]
Pushed a new version. Again tested on my plugin (https://github.com/gxalpha/obs-properties-dock/commit/dc5d7d01110049f84d7bea29b0dba51aedfa8b90).

**Review by PatTheMav — APPROVED** [review]
Looks correct logically. I guess if @gxalpha didn't comment otherwise it worked in his tests as well.

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
