### PR TITLE
cmake: Remove local files for checking threading support

### LINKED ISSUE #4884: Cross compilation to aarch64 fails with CMake Error: TRY_RUN() invoked in cross-compiling mode
### Operating System Info

Other

### Other OS

Void Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

at least 27.0.1 and 27.0.1

### OBS Studio Log URL

\-

### OBS Studio Crash Log URL

\-

### Expected Behavior

cross compilation to aarch64 finishes successfully

### Current Behavior

```
-- Found EGL: /usr/aarch64-linux-gnu/usr/include  
-- Found FFmpeg: /usr/aarch64-linux-gnu/usr/lib/../lib64/libavcodec.so (found version "58.91.100") found components: avcodec avdevice avutil avformat 
-- Found Libcurl: /usr/aarch64-linux-gnu/usr/lib/../lib64/libcurl.so  
-- Scripting: Luajit supported
-- Scripting: Python 3 supported
-- Found SWIG: /usr/bin/swig (found suitable version "4.0.2", minimum required is "2")  
-- Using system Jansson library
-- XCB[XCB]: Found component XCB
-- Found XCB: /usr/aarch64-linux-gnu/usr/lib/libxcb.so  found components: XCB 
-- Found X11_XCB: /usr/aarch64-linux-gnu/usr/lib/libX11-xcb.so  
-- Found Wayland: /usr/aarch64-linux-gnu/usr/lib/libwayland-client.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-server.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-egl.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-cursor.so   
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see /builddir/obs-studio-27.0.1/build/TryRunResults.cmake
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE  
-- Found FFmpeg: /usr/aarch64-linux-gnu/usr/lib/../lib64/libavformat.so (found version "58.45.100") found components: avformat avutil swscale swresample avcodec 
-- XCB[XINPUT]: Found component XINPUT
-- Found XCB: /usr/aarch64-linux-gnu/usr/lib/libxcb-xinput.so  found components: XINPUT 
-- XCB[XCB]: Found component XCB
-- XCB[COMPOSITE]: Found component COMPOSITE
-- XCB[DAMAGE]: Found component DAMAGE
-- XCB[DRI2]: Found component DRI2
-- XCB[GLX]: Found component GLX
-- XCB[RANDR]: Found component RANDR
-- XCB[RENDER]: Found component RENDER
-- XCB[SHAPE]: Found component SHAPE
-- XCB[SHM]: Found component SHM
-- XCB[SYNC]: Found component SYNC
-- XCB[XFIXES]: Found component XFIXES
-- XCB[XTEST]: Found component XTEST
-- XCB[XV]: Found component XV
-- XCB[XINPUT]: Found component XINPUT
-- XCB[XINERAMA]: Found component XINERAMA
-- Found XCB: /usr/aarch64-linux-gnu/usr/lib/libxcb-xinput.so;/usr/aarch64-linux-gnu/usr/lib/libxcb.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-composite.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-damage.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-dri2.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-glx.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-randr.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-render.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-shape.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-shm.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-sync.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xfixes.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xtest.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xv.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xinput.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xinerama.so   
-- Found PulseAudio - Audio Monitor enabled
-- Checking for modules 'gio-2.0;gio-unix-2.0'
--   Found gio-2.0, version 2.68.2
--   Found gio-unix-2.0, version 2.68.2
-- Using libavcodec for image loading in libobs
-- Found ZLIB: /usr/aarch64-linux-gnu/usr/lib/../lib64/libz.so  
-- Found Wayland: /usr/aarch64-linux-gnu/usr/lib/libwayland-client.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-server.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-egl.so;/usr/aarch64-linux-gnu/usr/lib/libwayland-cursor.so  found components: Client 
-- XCB[XCB]: Found component XCB
-- XCB[RANDR]: Found component RANDR
-- XCB[SHM]: Found component SHM
-- XCB[XFIXES]: Found component XFIXES
-- XCB[XINERAMA]: Found component XINERAMA
-- Found XCB: /usr/aarch64-linux-gnu/usr/lib/libxcb.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-randr.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-shm.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xfixes.so;/usr/aarch64-linux-gnu/usr/lib/libxcb-xinerama.so  found components: XCB RANDR SHM XFIXES XINERAMA 
-- Found Libv4l2: /usr/aarch64-linux-gnu/usr/lib/libv4l2.so  
-- Found UDev: /usr/aarch64-linux-gnu/usr/lib/libudev.so  
-- Checking for module 'jack'
--   Found jack, version 1.9.18
-- Found jack: /usr/aarch64-linux-gnu/usr/lib/libjack.so
-- Found ALSA: /usr/aarch64-linux-gnu/usr/lib/libasound.so (found version "1.2.4") 
-- Found LibVLC: /usr/aarch64-linux-gnu/usr/include/vlc  
-- Could NOT find Sndio (missing: Sndio_LIBRARY Sndio_INCLUDE_DIR) 
-- Sndio not found, disabling Sndio plugin
-- Found Libx264: /usr/aarch64-linux-gnu/usr/lib/../lib64/libx264.so  
-- Found FFmpeg: /usr/aarch64-linux-gnu/usr/lib/../lib64/libavcodec.so (found version "58.91.100") found components: avcodec avfilter avdevice avutil swscale avformat swresample 
-- Found FFmpeg: /usr/aarch64-linux-gnu/usr/lib/../lib64/libavcodec.so (found version "58.91.100") found components: avcodec avutil avformat 
-- Found MbedTLS: /usr/aarch64-linux-gnu/usr/lib/../lib64/libmbedtls.so;/usr/aarch64-linux-gnu/usr/lib/../lib64/libmbedcrypto.so;/usr/aarch64-linux-gnu/usr/lib/../lib64/libmbedx509.so  
-- Checking for module 'libftl'
--   No package 'libftl' found
-- Found Libspeexdsp: /usr/aarch64-linux-gnu/usr/lib/../lib64/libspeexdsp.so  
-- Configuring incomplete, errors occurred!
See also "/builddir/obs-studio-27.0.1/build/CMakeFiles/CMakeOutput.log".
See also "/builddir/obs-studio-27.0.1/build/CMakeFiles/CMakeError.log".
```

### Steps to Reproduce

1. cross compile from x86_64 for aarch64 (with glibc)

### Anything else we should know?

this issue happens here: https://github.com/obsproject/obs-studio/blob/dcd491541e5e6f68f57f7ab718badac2c01eb7c5/cmake/Modules/FindThreads.cmake#L87-L94

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

These local copies of CheckForPthreads.c and FindThreads.cmake override the ones included with CMake. These versions create CMake::Threads, but Qt6 expects Threads::Threads created by CMake 3.1+. These local versions seem to be based on old copies from CMake from late 2014 with some customizations. Let's just use the built-in ones that CMake ships.

cmake/Modules/CheckForPthreads.c
The OBS version is identical to this:
https://github.com/Kitware/CMake/blob/7a1b961de8b79416d168355e71f5af80fa4dbd02/Modules/CheckForPthreads.c

cmake/Modules/FindThreads.cmake
The OBS version is this, but with modifications:
https://github.com/Kitware/CMake/blob/cbd5db64851109c8cd8e633ed6b7b2ab88918f3e/Modules/FindThreads.cmake

Fixes #4884.

### Motivation and Context

Having Threads::Threads available is required to build with Qt6.  Removing these files means less custom code to keep track of.

### How Has This Been Tested?

I've built OBS on Windows 10 64-bit against both Qt5 and Qt6 after removing these files.  OBS seemed to run normally, but any extra testing, especially on other operating systems, would be appreciated.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Frustratingly, I just noticed that this failed to build on CI Ubuntu on my fork.  @kkartaltepe didn't this build for you locally?

**Comment by kkartaltepe** [comment]
Yea I got this error when building locally as well without Qt6 (it worked with Qt6 for whatever reason?). Manually linking pthreads worked for me (adding `-lpthread`), but doesnt seem very appropriate.

**Comment by RytoEX** [comment]
> 
> 
> Yea I got this error when building locally as well without Qt6 (it worked with Qt6 for whatever reason?). Manually linking pthreads worked for me (adding `-lpthread`), but doesnt seem very appropriate.

@kkartaltepe 
That's unfortunate.  My Ubuntu 20.04 VM locked up when trying to build against Qt5 with this change.  I haven't tried Qt6 on Ubuntu yet, but I'll put that on my list to check later.  Since it's UI components that seem to be producing build errors, I wonder if this is some bad interaction fixed in Qt 5.15 that exists in Qt 5.12?  What version of Qt5 did you try to build with?

This isn't urgently needed, as it's only "needed" for Qt6, which I don't see us using any time soon unless it provides some significant benefits.  I've marked this as a Draft for now to prevent accidental merging.

**Comment by kkartaltepe** [comment]
Im building against 5.15, I usually use arch.

I think the recommendation is to use the imported target everywhere and stop using `${THREADS_LIBRARIES}`. This patch onto your change makes it compile on my machine.

```diff
diff --git a/UI/CMakeLists.txt b/UI/CMakeLists.txt
index 4478e2b5c..911e9a717 100644
--- a/UI/CMakeLists.txt
+++ b/UI/CMakeLists.txt
@@ -46,6 +46,8 @@ configure_file(
 set(CMAKE_INCLUDE_CURRENT_DIR TRUE)
 set(CMAKE_AUTOMOC TRUE)
 
+find_package(Threads REQUIRED)
+
 find_package(Qt5Widgets ${FIND_MODE})
 find_package(Qt5Svg ${FIND_MODE})
 find_package(Qt5Xml ${FIND_MODE})
@@ -408,6 +410,7 @@ endif()
 
 target_link_libraries(obs
        libobs
+       Threads::Threads
        Qt5::Widgets
        Qt5::Svg
        Qt5::Xml
diff --git a/libobs/CMakeLists.txt b/libobs/CMakeLists.txt
index de9b414bc..eb442f9e1 100644
--- a/libobs/CMakeLists.txt
+++ b/libobs/CMakeLists.txt
@@ -536,9 +536,6 @@ target_compile_options(libobs
        PUBLIC
        ${ARCH_SIMD_FLAGS})
 
-target_compile_options(libobs
-       PUBLIC
-               "${THREADS_DEFINITIONS}")
 target_include_directories(libobs
        PUBLIC
                "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>"
@@ -551,8 +548,7 @@ target_link_libraries(libobs
                ${OBS_JANSSON_IMPORT}
                ${FFMPEG_LIBRARIES}
                ${ZLIB_LIBRARIES}
-       PUBLIC
-               ${THREADS_LIBRARIES})
+               Threads::Threads)
 
 install_obs_core(libobs EXPORT LibObs)
 install_obs_data(libobs data libobs)
```

**Comment by RytoEX** [comment]
Unfortunately, even with that patch it still fails to build on Ubuntu 20.04 with Qt 5.12.8 having followed our current build instructions.

**Comment by kkartaltepe** [comment]
Are you sure? I just compiled it on ubuntu 20.04/18.04/debian  10 (with my patch on top of your pr, by itself it's broken). And it seemed to work correctly.

**Comment by RytoEX** [comment]
Yeah, seems to have been something strange going on in my build environment.  It worked just now when I tried again.  Maybe OOM, as you suggested in Discord.  I got it building in Ubuntu 20.04 against Qt5 with your changes, though didn't test more than making sure OBS would run.

I'll try to retest OBS on Windows to make sure nothing has changed from my previous tests.  Testing on macOS would still be appreciated.

**Comment by RytoEX** [comment]
I've retested this with Qt5 on Windows and it still works fine for streaming and recording.  I'll retest Qt6 later.

**Comment by PatTheMav** [comment]
FWIW I did build tests with the built-in Threads finder on ElementaryOS and it compiled fine so far.

**Comment by RytoEX** [comment]
> 
> 
> I've retested this with Qt5 on Windows and it still works fine for streaming and recording. I'll retest Qt6 later.

Retested on Qt6 and it seems fine there too.  Should be safe for Qt5 and Qt6.

**Pull request merged**
