### PR TITLE
deps/media-playback: Fix possible negative duration

### PR DESCRIPTION
**Pull request by ePirat**
### Description
Ensure that get_estimated_duration does not calculate a negative
duration based on pts, but instead falls back to other estimations.

### Motivation and Context
In cases where some frames have no pts but following frames again have a pts that
could be smaller than the current estimated one, the `get_estimated_duration` function
could calculate a negative duration, which breaks other calculations in media.c.

This does _not_ solve that some files can trigger the assert in `mp_media_calc_next_ns`,
this can still happen.

### How Has This Been Tested?
Tested on macOS with various media files with OBS linked against ffmpeg master.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
> This does not solve that some files can trigger the assert in mp_media_calc_next_ns,
this can still happen.

You mean this one right? https://github.com/obsproject/obs-studio/blob/21f6d480ddc2bb7eb87836bb87a7d767e32d7e95/deps/media-playback/media-playback/media.c#L451

So you noticed that as well? I'm relived, thought that this might be particular to my machine. I had the debug assert happen 100% of the time when using an MP4 on a network drive and had to change my scene setup for debugging to "fix" it.

**Comment by ePirat** [comment]
@PatTheMav Yes exactly. Can you share a file with which you reproduce that? I am currently investigating the issue and having another file that triggers the issue would help to know if it's for the same reason as with the one I have here.

**Comment by PatTheMav** [comment]
I'll try and find some that triggers it and is shareable. IIRC any h264/aac encoded mp4 worked though as long as it was added from a SMB-connected network drive.

**Comment by ePirat** [comment]
The pts should not be affected by whether the file is accessed over smb or not, I just tried with a mp4 file on a mounted  network drive on Windows and I had no issues.

**Comment by jp9000** [comment]
Fixed it with f8cc3bfe01 -- see commit description for more details.

**Comment by PatTheMav** [comment]
Awesome, I ran into this issue using videos with _no_ audio stream, which also means no timestamps I guess.

**Comment by ePirat** [comment]
@jp9000 Thanks! That's indeed a better fix for this.

**Pull request closed without merging**
