### PR TITLE
UI: Fix file browser showing up when dir selected

### PR DESCRIPTION
**Pull request by cg2121**
Fixes: https://obsproject.com/mantis/view.php?id=1418

### CODE REVIEW

**Comment by jp9000** [comment]
I'm pretty sure QDir is not only for directories.  You might have to fix that check.

**Comment by cg2121** [comment]
It is working as intended.

**Comment by cg2121** [comment]
https://doc.qt.io/qt-5/qdir.html#exists-1

**Comment by jp9000** [comment]
Ah okay, my apologies.

**Pull request merged**
