### PR TITLE
DRAFT: linux-pipewire: Allow multiple stream implementations

### PR DESCRIPTION
**Pull request by columbarius**
### Description

Disentangle obs_pipewire and obw_pipewire_stream

### Motivation and Context

Currently the PipeWire Context cleanup is bound to the the Stream implementation. This would disentangle those to components. 

### How Has This Been Tested?

linux-pipewire should run as before. 

### Types of changes

 - New feature (non-breaking change which adds functionality) 

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by columbarius** [comment]
@GeorgesStavracas are you fine with this approach or should each type of plugin should have its own array to register instances?

**Comment by WizardCM** [comment]
Please elaborate on the motivation, as we're a bit unsure about the intent and goals behind this change.

**Comment by columbarius** [comment]
I'd like to rebase #5377, which shares the obs_pipewire struct and related code, but is not abstracted by obs_pipewire_stream. obs_pipewire currently tracks all streams and closes them on shutdown. The virtual camera plugin would introduce a obs_pipewire_outputstream struct, and it would be nice if this could also be tracked by obs_pipewire.

I see two options:
1. create a common struct with pointer and funcpointer to destructor and track every plugin with it
2. create an separate array in obs_pipewire for each plugin type.

**Comment by columbarius** [comment]
Found another solution. This is not longer required. Sorry

**Pull request closed without merging**
