### PR TITLE
UI: Add visibility transitions

### PR DESCRIPTION
**Pull request by cg2121**
This also modifies libobs.

This adds the ability for scene items to have transitions
when their visibility is toggled.

### CODE REVIEW

**Comment by cg2121** [comment]
vis-tr-demo

**Comment by SuslikV** [comment]
Is this also should become the part of the #1321?

**Comment by WizardCM** [comment]
Small note after a quick test - "None" doesn't seem to be an available option in the menu, inconsistent with scene transition overrides.

Tested this in an existing scene of mine. Configured a Luma Wipe onto a Video Capture source, tried hiding/showing the source - nothing happened. Then, changed the transition to a Fade, and immediately hit this:

Log:
```
private source '(null)' (wipe_transition) created
The thread 0x5988 has exited with code 0 (0x0).
The thread 0x283c has exited with code 0 (0x0).
private source '(null)' (fade_transition) created
private source '(null)' destroyed
Exception thrown: read access violation.
**mx** was nullptr.
```

Call Stack:
```
>	w32-pthreads.dll!pthread_mutex_trylock(pthread_mutex_t_ * * mutex) Line 67	C	Symbols loaded.
 	w32-pthreads.dll!pthread_mutex_destroy(pthread_mutex_t_ * * mutex) Line 58	C	Symbols loaded.
 	obs.dll!obs_source_destroy(obs_source * source) Line 596	C	Symbols loaded.
 	obs.dll!obs_source_release(obs_source * source) Line 632	C	Symbols loaded.
 	obs.dll!obs_source_create_visibility_transition(obs_source * source, obs_source * transition) Line 4198	C	Symbols loaded.
 	obs64.exe!OBSBasic::CreateVisibilityTransitionMenu::__l2::<lambda>(QAction * action) Line 940	C++	Symbols loaded.
 	[External Code]		Annotated Frame
 	obs64.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<bool>,void,std::_Binder<std::_Unforced,void <lambda>(QAction *) & __ptr64,QAction * __ptr64 & __ptr64> >::call(std::_Binder<std::_Unforced,void <lambda>(QAction *) &,QAction * &> & f, void * * arg) Line 130	C++	Symbols loaded.
 	obs64.exe!QtPrivate::Functor<std::_Binder<std::_Unforced,void <lambda>(QAction *) & __ptr64,QAction * __ptr64 & __ptr64>,1>::call<QtPrivate::List<bool>,void>(std::_Binder<std::_Unforced,void <lambda>(QAction *) &,QAction * &> & f, void * __formal, void * * arg) Line 241	C++	Symbols loaded.
 	obs64.exe!QtPrivate::QFunctorSlotObject<std::_Binder<std::_Unforced,void <lambda>(QAction *) & __ptr64,QAction * __ptr64 & __ptr64>,1,QtPrivate::List<bool>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 174	C++	Symbols loaded.
```

I was able to reproduce this every time following the same steps.

**Comment by cg2121** [comment]
@WizardCM could you see if the issue is fixed now?

**Comment by WizardCM** [comment]
@cg2121 Good news is, I'm no longer getting the crash. Bad news is, any source that I apply a transition to, no longer actually disappears when I toggle the visibility - which is what I was getting alongside the crash. Restarting OBS then correctly makes it invisible, and then toggling works - though I only tested it with a Cut. Restarting seems to reset the transition time, by the way.

I seem to now be having issues actually launching OBS after enabling a Luma Wipe transition with 700ms  on said webcam source and restarting. Will research further. Seems the scene collection gets loaded, but not much happens after that.

**Comment by cg2121** [comment]
@WizardCM the issues are hopefully fixed now, if you want to test again.

**Comment by WizardCM** [comment]
Flawless! Behaves as expected now - and restarting doesn't cause OBS to hang on launch. Awesome work! Only thing missing now is being able to remove transitions altogether from a source (the "None" option).

Second demo

**Comment by cg2121** [comment]
There is a bug in which I haven't been able to figure out. When you transition to blank on a source with audio, the audio stops just fine on the recording but can still be heard on the audio monitor, at least on Linux anyway.

**Comment by jp9000** [comment]
This is a very interesting way to approach this, however, I think it may be better to approach this at the scene item level rather than the source level -- as visibility technically applies to scene items currently rather than the sources themselves.  This feature is definitely doable however, but this proposal may need some significant reworking.  I'd love to get in sooner than later though.

**Comment by jp9000** [comment]
The way to solve this is via adding transition support in to scene items somehow or another -- this should not have to modify obs-source.c.  obs-scene.c would be the file that would need to be modified.  We would not want to make this a transition that is tied to a specific source, but a scene item.

**Pull request closed without merging**
