### PR TITLE
UI: Refactor Wizard Pages into encapsulated files

### PR DESCRIPTION
**Pull request by JohannMG**
### Description

Starts refactoring the AutoConfig wizard by moving AutoConfigStartPage and AutoConfigVideoPage into their own files and removes the UI builder component. The UIs are modified heavily by both the designer and their code counterparts which was fragile. This moves the pages to completely code with no visual changes. They are better encapsulated: the extracted classes removes knowledge of the Wizard's private variables from the Start and Video Page. 

Visually matches: 
Screen Shot 2020-08-03 at 4 51 45 PM
Screen Shot 2020-08-03 at 4 51 50 PM

### Motivation and Context

The wizard is now shown automatically when a use first uses OBS, I think it need to be polished and cleaning its writing will ease additional work later. 

### How Has This Been Tested?

MacOS 10.14 Mojave. 
CI running tests. 

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
   - Spacers that shouldn't be needed now removed. 

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by JohannMG** [comment]
Help in the CI issues would be appreciated: unsure what it's upset about. 

Screen Shot 2020-08-03 at 5 18 34 PM

**Comment by WizardCM** [comment]
Built locally, this seems to run fine on Windows. Not sure why CI is unhappy.

I do notice that with these changes, the window changes width when going from the first page to the second. Previously the window size would remain constant.

**Comment by 12345678kkmmxx** [comment]
-

**Comment by 12345678kkmmxx** [comment]
> - 

[](https://dev.azure.com/obsjim/obsjim/_build/results?buildId=4289&view=results)

**Comment by JohannMG** [comment]
> I do notice that with these changes, the window changes width when going from the first page to the second. Previously the window size would remain constant.
 
Will fix tomorrow when I have a moment. Let me know if you see anything else.

**Comment by JohannMG** [comment]
@WizardCM Fixed the size changing, pulling that out to shared constants to avoid this issue going forward as well.

**Comment by JohannMG** [comment]
It looks like the `Error MSB4035:` CI issue has been fixed in an 16.6.3 update and is specific to 16.6.0 which is what it's currently building with: `Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework`

Problem tracker: 
https://developercommunity.visualstudio.com/content/problem/1046515/visual-studio-2019-1660-microsoft-fakes-issue.html#:~:text=error%20MSB4035%3A%20The%20required%20attribute,is%20for%20the%20WindowsBase%20assembly.

16.6.3 was released on Jul 1

**Comment by RytoEX** [comment]
The Azure agent we use is using [Visual Studio Enterprise 2019 16.6.30320.27](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019), [which corresponds to VS 2019 16.6.5](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019), released on July 21, 2020.  GitHub Actions uses Azure behind the scenes, so it should also be using the same VS version (16.6.30320.27 / 16.6.5).

**Comment by JohannMG** [comment]
@RytoEX  Any idea what this issue is otherwise? 

Because when I look in build step I see: 
Screen Shot 2020-08-08 at 7 53 53 AM
...and that's the only lead I have on this issue. 

Maybe I'll kick off the builds again and then look again what I can find

**Comment by JohannMG** [comment]
Rebase.

**Comment by JohannMG** [comment]
There was a small error in UI/CMAKE
but that doesn't seem to be the issue ☹️

**Comment by RytoEX** [comment]
> Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
@JohannMG 

The various components of Visual Studio are versioned somewhat independently of the Visual Studio overall version.  This can be seen from the tables of components in the first link in my previous comment.  That said, I do not know what the version string quoted above is supposed to represent or why exactly the build is failing right now on CI.  The information I have available indicates that it shouldn't be failing in the way that it is.  It seems that CI works fine on regular commits made after this PR was submitted, so CI isn't broken for everything.

Interestingly, when I initially tested this locally with CMake 3.17.3, I did not find any empty Include attributes on CustomBuild elements from its generated files.  However, when I upgraded to CMake 3.18.1 just now (which is what CI uses), I found one exactly on Line 635 just as CI is complaining about.  There is also an empty Include attribute on Line 691.

Line 634-636:
```
  <ItemGroup>
    <CustomBuild Include="">
      <Message Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">Generating ui_AutoConfigStartPage.h</Message>
```

Line 690-692:
```
  <ItemGroup>
    <CustomBuild Include="">
      <Message Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">Generating ui_AutoConfigVideoPage.h</Message>
```

This appears to be because you deleted the .ui files for those pages, as the Include element would normally be something like "UI\forms\AutoConfigStreamPage.ui".  So some combination of removing those .ui files and changes between CMake 3.17.3 and 3.18.1 is causing CMake to generate a `build\UI\obs.vcxproj` file with empty Include attributes.

**Comment by JohannMG** [comment]
OH!! I see. I only checked additions and not the removals. That was daft.
I'll fix that up and rebase.

**Comment by JohannMG** [comment]
Eyyy! Thank you @RytoEX !!!

**Comment by RytoEX** [comment]
Minor nitpick:  the commit messages should say "refactor" rather than "refractor".

Also, this PR currently has merge conflicts due to recent merge activity.  Please resolve those conflicts.

**Comment by JohannMG** [comment]
@RytoEX Lol! oops. Can fix. That comet put telescopes on my mind I guess lol.

**Comment by JohannMG** [comment]
- Rebased
 - Commit Messages updated refractor -> refactor

**Comment by WizardCM** [comment]
Heads up: there are merge conflicts.

**Pull request closed without merging**
