### PR TITLE
rtmp-services: Update DLive to common

### PR DESCRIPTION
**Pull request by boisde**

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I have concerns adding this as a common service. Our data shows that this is not very widely adopted. Can you please provide the reasoning why you feel this should be listed as a common service? Do you have any usage statistics you are able to share?

Additionally, this contains many unrelated commits. Please remove or squash these commits. Be sure to read the [contribution guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) before making submissions to a project.

**Comment by charleswayn** [comment]
> I have concerns adding this as a common service. Our data shows that this is not very widely adopted. Can you please provide the reasoning why you feel this should be listed as a common service? Do you have any usage statistics you are able to share?
> 
> Additionally, this contains many unrelated commits. Please remove or squash these commits. Be sure to read the [contribution guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) before making submissions to a project.

Hey @Fenrirthviti ,
Thanks for asking. DLive currently has more than 70,000 active streamers who are using OBS, Streamlabs, and XSplit. PewDiePie, who is the largest Youtuber in the world, also exclusively streams on DLive and uses OBS. [https://finance.yahoo.com/news/pewdiepie-helps-dlive-increase-userbase-150047072.html](https://finance.yahoo.com/news/pewdiepie-helps-dlive-increase-userbase-150047072.html)
We would be happy to recommend OBS to our community if it's easier to locate. We have 5 million monthly active users and been growing very fast as we've only been around for 10 months.

**Comment by notr1ch** [comment]
Looking at the "browse" tab on DLive right now shows under 1000 viewers across all the channels, this is not what I would consider a "common" service. While there may be a few celebrity streamers bringing in high numbers, this doesn't justify adding the service as common as the ratio of streamers:viewers is low.

**Comment by DLiveTV-Tidy** [comment]
Thank you for taking the time to read through the following reasons why we feel DLive should be added to the list of common services in OBS.  DLive is the largest live streaming community on the blockchain.

**1) PewDiePie**

Announced in April 2019, PewDiePie announced that he will be using DLive as his exclusive live streaming platform.  This has not only brought DLive incredible growth, but existing streamers on other platforms are coming across to DLive daily.

ref: https://www.forbes.com/sites/billybambrough/2019/04/12/pewdiepie-is-edging-closer-to-bitcoin-and-crypto/
ref: https://finance.yahoo.com/news/pewdiepie-helps-dlive-increase-userbase-150047072.html
ref: https://variety.com/2019/digital/news/pewdiepie-dlive-live-streaming-lino-blockchain-1203183515/

**2) 2nd Largest Live Streaming Platform in Turkey**

DLive's growth has exploded in Turkey, where we are ranked as the 2nd largest live streaming platform.  We have multiple large Turkish streamers each achieving between 5k-25k viewers on their broadcasts.

ref: https://www.chip.com.tr/haber/dlive-online-yayincilikta-devrim-yaratiyor_78685.html

**3) Statistics**

Please see below a link to some public statistics for DLive, including TidyLabs which is a community project for streamers to use alerts on their stream.

ref: https://hypestat.com/info/dlive.tv
ref: https://www.alexa.com/siteinfo/dlive.tv
ref: https://tidylabs.stream (Alerts system for DLive - 31,000+ streamer accounts)

**4) "English" Content Creators who are now streaming on DLive.tv**

Moe Sargi - 1.9 Million YouTube Subs:
 - DLive Channel: https://dlive.tv/moesargi
 - YouTube Channel : https://www.youtube.com/user/DirtStarPranks/search?query=dlive

SamPepper - 317k YouTube Subs:
  - DLive Channel: https://dlive.tv/sampepper
  - YouTube Channel: https://www.youtube.com/user/16bitsam/featured

NoahFromYouTube - 1 Million+ YouTube Subs
 - DLive Channel: https://dlive.tv/NoahFromDlive
 - YouTube Channel: https://www.youtube.com/channel/UCP9314aIt_Ev_g4hhqg9mcA

NaDeXe - 26.1k Twitter followers
 - DLive Channel: https://dlive.tv/nadexe



**5) Community & Why DLive as a common service**

My position at DLive is "Head of Community (English).  DLive.tv is an incredibly Community focussed live streaming platform.  We have a team of dedicated Staff and Volunteers (DLive Guardians) to help not only moderate the platform, but to help new users set up their live streams with their preferred software (90% is OBS).

Speaking from experience, a lot of our new users are not finding "DLive" in the list of common services which inevitably is a stumbling block to starting their journey on DLive.tv

I feel that having DLive as a preferred service would not only improve our level of support, but add another level of validity for DLive and it's large growing community of streamers.

---

If you require anything else to make this happen, please do let me know :)


Kindest Regards


Tidy
Head of Community English
tidy@dlive.tv | DLive.tv

**Comment by DLiveTV-Tidy** [comment]
> Looking at the "browse" tab on DLive right now shows under 1000 viewers across all the channels, this is not what I would consider a "common" service. While there may be a few celebrity streamers bringing in high numbers, this doesn't justify adding the service as common as the ratio of streamers:viewers is low.

Hey notr1ch,

DLive will automatically **only** display the list of streamers that match your browser language, this is to improve regional engagement.  ie. a _French user would only see French streams without toggling the language drop down_.  I assume you were viewing English only.  The English speaking community is much smaller than our Turkish, but as you can see from the links above the growth is now happening outside of Turkey.

If you visit: https://dlive.tv/s/browse  you can see the total viewers for each category.  Once inside a category you can use the language select (top right) to change it to Turkish to see higher traffic streams.


Kindest Regards

Tidy
Head of Community English
tidy@dlive.tv | DLive.tv

**Comment by dodgepong** [comment]
Personally I'm not as interested in the number of viewers as I am interested in the number of actual streamers/creators, i.e. the number of people who would need to use OBS to stream on the site. The whole point of the common/uncommon split is to make it easier for the most common users to start using OBS without overwhelming them with a giant list of services they've never heard of. Determination of which services are popular or likely to be used by a given OBS user should be made based on the number of people actually using OBS, not the number of people watching someone else use OBS.

I have a very hard time believing that being on the "common" list has a significant marketing advantage, given that there have been services marked as "common" that we've had to remove for no longer being actually common (which means being marked as "common" didn't seem to help them stay popular).

While we don't have any formal telemetry from OBS, we do have some limited metrics we can still use to give us some idea of where different services call in relation to each other in terms of how much they are used by OBS users. According to those stats, DLive is in 12th place among OBS users in popularity, behind several other services that are also not marked as "common". I would personally estimate that the number of people streaming to DLive with OBS would have to at least triple in these metrics before it starts to get closer to being a peer with the current "Common" services.

If the problem you're having is more one of support than marketing (i.e. the real problem you're trying to solve is to make it easier for people to stream on your site, and the marketing value of being listed as common is secondary to that) then perhaps there may be other features coming to OBS in the future that will help solve that.

**Comment by DLiveTV-Tidy** [comment]
@dodgepong 

I personally agree about the number of new streamers over the CCU of the site, however based on the previous comments requesting information for viewer numbers, I did primarily address those concerns.

DLive is Community Orientated, meaning smaller streamers often get more exposure compared to other services.

Our home page system featured system does not primarily focus on "number of viewers", it may show a brand new streamer, or somebody who has 1-2 viewers - giving them extra exposure for their content.

The events we run on DLive are not just for the top CCU streamers - they are aimed for everybody, as a community.  This generates a lot of **new users** to the platform - and having DLive as a common name would really aid them when wanting to join in on these events.

**Past Events**

- https://community.dlive.tv/campaigns/events/

If you have any other questions, please do not hesitate to ask :)


Kindest Regards

Tidy
Head of Community English
tidy@dlive.tv | DLive.tv

**Comment by Fenrirthviti** [comment]
We are declining this PR for now. The current usage and growth of DLive has not shown it to be a commonly used service. Our data shows very low usage from users. In my region currently (as I believe you mentioned it only shows streams from your specific region, unless I misunderstood?) there is a very low count of active streamers and viewers (under 1000).

We are aware that discoverability is a problem in the application currently, and are working towards a solution with an addon library (or similar solution) that will allow services to be listed and installed as necessary. As part of this, we would like to allow URI handling so that a service could be registered/installed from a single click on the service website itself. We are still in the planning stages on this, but in the long run this will be a better solution.

**Pull request closed without merging**
