### PR TITLE
Audio-Channel-Matrix filter

### PR DESCRIPTION
**Pull request by BtbN**
This is NOT intended to be merged in its current form. It's a hack for our use case which I'd like to discuss on how to do it properly.

Basically, what we need/want for our online marathons is a way to separate various sources on the runners PC, to be able to mix them on our end individually.
What we figured would be the best option for this would be to just stuff them into multiple audio channels, and separate them again at our end.

This filter adds a _very_ rudimentary audio channel matrix, while ignoring things like user-friendliness(It's just an 8 bit number for each output channel determining the input matrix via the set bits in it), localization and style guidelines(for now?).

Now, this actually works surprisingly fine. The only issue we have so far is that if we move a source away from its primary channel(s), it will show as silent in the UI. Hence the second Hack-Commit, forcing the volume-meters to always show all audio bars.
I could not find any way to modify a sources channel count from a filter.

Any ideas for improvements are welcome. If this could be modified in a way it could actually be merged in a clean way, that would also be very nice.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
This PR doesn't follow our PR template (I understand that it's a draft, but please make sure to follow the template)

If this is intended to be a discussion on design and implementation details, it might be better to close this and submit it as an [RFC])(https://github.com/obsproject/rfcs) instead.

Additionally, there is already an audio matrix plugin, which can be found here and might offer some insight: https://github.com/Andersama/rematrix-filter

**Comment by BtbN** [comment]
Interesting, I was not aware of this plugin, and Google did not manage 
to direct me to it.
It seems to be technically doing mostly the same, with some minor 
implementation differences (I think my implementation is a bit more 
efficient and avoids an extra copy, at the expense of ever so slightly 
higher memory use).
And of course it has A TON more effort put into its UI.

However, it does not solve the issue that OBS itself will never display 
more channels than the source originally has, since there does not 
appear to be any way for a filter to change the number of channels/the 
speaker layout of the source it's operating on.
This is most likely purely a UI thing as well, since the extra channels 
are encoded just fine. Moving a stereo source from channels 1 and 2 to 3 
and 4 just makes it appear silent in the UI, because it only displays 
the first two channels.

**Comment by Fenrirthviti** [comment]
I have noticed that without any additional plugins If a device has more channels and the FR/FL (by default, I believe) channels are not outputting, the audio is played properly (downmixed to stereo) but the meters in OBS don't reflect it as the additional channels are hidden without OBS set to 5.1/7.1/etc. It's a fairly rare thing to encounter in the wild, I ran in to this with a BMD capture device that had improper channel assignments. The number of channels displayed in the UI should have no theoretical limit, just no way to expose or force a source to show a specific number of channels. Might be worth setting OBS to 5.1/7.1 (if it's not already) and see if that allows the additional channels to display properly, as that should adjust the "soft" cap on displayed channels.

**Comment by BtbN** [comment]
I have OBS currently set to 4.0, since we don't need more than 4 channels.
But unfortunately that does not increase the number of bars displayed for a source.

That's the reason I wrote the Hack-Patch https://github.com/obsproject/obs-studio/pull/3098/commits/d9fc47bebb4b64ae4a70ca2b4acba70d2e60f8a4
The number of bars displayed is determined by obs_volmeter_get_nr_channels, and in its current form in OBS, this gets the number of channels, or rather the speaker-layout, from the source in question, and then clamps that value between 1 and the configured number of output channels.

So no matter what you do to the actual audio data in a filter, obs_volmeter_get_nr_channels will only ever take the original source into account, and only use the configured channel number as a maximum.

**Pull request closed without merging**
