### PR TITLE
UI: Update Windows DLL blocklist

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Adds some additional DLLs to the blocklist based on reports in #8552:

- Bandicam: Freezes OBS preview when unhooking.
- VirtualMotionCapture: Old versions without Unity Capture fix.
- HolisticMotionCapture: All versions prior to today as there is no fixed version yet (also Unity Capture based).

### Motivation and Context
Freezing OBS is bad.

### How Has This Been Tested?
Untested, but strong evidence was presented in the issue showing the problems.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Would you say that this fixes #8552 ?

**Comment by style1925** [comment]
@RytoEX 

> Would you say that this fixes #8552 ?

May this receive the seeking testers label? 
I will check it.

**Comment by style1925** [comment]
> > @RytoEX
> > > Would you say that this fixes #8552 ?
> > 
> > 
> > May this receive the seeking testers label? I will check it.
> 
> Done. Rebuilding.

Thank you!

**Comment by style1925** [comment]
@RytoEX 
Artifacts has not been generated. 
Why is it not generated...?

スクリーンショット 2023-03-30 072538

**Comment by RytoEX** [comment]
> @RytoEX Artifacts has not been generated. Why is there a "seeking testers label" but it is not generated...?
> 
> スクリーンショット 2023-03-30 072538

There's a bug in the CI workflow that causes artifacts to not be generated if the PR was not submitted with the Seeking Testers label.

**Comment by style1925** [comment]
> There's a bug in the CI workflow that causes artifacts to not be generated if the PR was not submitted with the Seeking Testers label.

Thank you for informing me.

**Comment by notr1ch** [comment]
Here's a copy of obs64.exe with the changes applied for testing, replace the one in an existing install.

[obs64.zip](https://github.com/obsproject/obs-studio/files/11106961/obs64.zip)

**Comment by style1925** [comment]
> Here's a copy of obs64.exe with the changes applied for testing, replace the one in an existing install.
> 
> [obs64.zip](https://github.com/obsproject/obs-studio/files/11106961/obs64.zip)

The change looks fine to me.
Thank you!

You can watch a test on YouTube below.
https://youtu.be/wSnRa3Pcy8k

Test procedure
1. Check Device List in OBS Classic
2. Launch replaced obs64.exe
3. Check Bandicam
4. Scene Switching
5. Check Video Capture Devices
6. Exit OBS
7. Log File Check
```
17:57:04.011: Blocked loading of '\bdcam64.dll' 20 times.
17:57:04.011: Blocked loading of '\vmc_camerafilter64bit.dll' 4 times.
17:57:04.011: Blocked loading of '\holisticmotioncapturefilter64bit.dll' 4 times.
```

**Review by RytoEX — APPROVED** [review]
Looks good to me.

**Pull request merged**
