### PR TITLE
libobs/UI: Add Log Viewer

### PR DESCRIPTION
**Pull request by Andersama**
Adds a log viewer widget to the tools menu, keeps track of a number of
lines and/or entire log file.

### CODE REVIEW

**Comment by Andersama** [comment]
Dockable actually wouldn't be too difficult a change, it is indeed missing a title. I could definitely add a label. Also formatting the timestamps wouldn't be nearly as nightmarish as the syntax highlighter, just would need a single regex.

**Comment by SuslikV** [comment]
> ...
> * What if we used a monospace font, which I think would be consistent with the Script Log
>
> ...

the fonts should be chosen carefully in this case, because some symbols may be missing for different systems and languages (while source/devices may has unpredictable names).

**Comment by WizardCM** [comment]
A related ticket ("Show log window on startup) https://obsproject.com/mantis/view.php?id=555

**Comment by kkartaltepe** [comment]
> the fonts should be chosen carefully in this case, because some symbols may be missing for different systems and languages (while source/devices may has unpredictable names).

Have you tested this and actually experienced this issue? Qt should do font fallback on every platform, if not it should be relatively trivial to extend the font definition to fallback.

**Comment by SuslikV** [comment]
@kkartaltepe is not implemented yet - what to test? If you need example of how it fails in obs previously, take a look here: https://obsproject.com/mantis/view.php?id=1347

**Comment by kkartaltepe** [comment]
> @kkartaltepe is not implemented yet - what to test? If you need example of how it fails in obs previously, take a look here: https://obsproject.com/mantis/view.php?id=1347

That is the text source and not Qt rendered text. Which is why I asked, since I'm not aware of anywhere in our application where Qt renders text incorrectly like that, so I dont think it would be needed for a Qt widget displaying text.

**Comment by Fenrirthviti** [comment]
Few questions:

This this properly tail the log file?

If so, it can be assumed the the line setting is for showing last X lines?

I question the usefulness of hiding parts of the log if the log is being appropriately tailed/appended to the log window in real time. 

Expected behavior for these kinds of features would be to auto-scroll when the last line in the log is visible, and any kind of scroll back would pause the auto-scroll until you scroll back to the bottom of the window.

**Comment by Andersama** [comment]
@Fenrirthviti depending whether whole file is checked or not it'll either tail or read in the last X lines.

I did run into the scrolling issue before, I should revisit that. I didn't create an algorithm to append lines to the window, that was another thought I had when putting this together was that maybe the line count should be set via the size of the window since I'm not bothering to make any additional history scrollable.

**Pull request closed without merging**
