### PR TITLE
UI: Add ability to center items vertically/horizontally

### PR DESCRIPTION
**Pull request by cg2121**
This also modifies libobs.

### CODE REVIEW

**Comment by Vainock** [comment]
Very cool, but why have the two texts in the locale the same letter c for the keyboard mode? I mean the &C. (I don't know how to call this.)

**Comment by cg2121** [comment]
I now have removed the "&" because there already is a Flip Vertical and Flip Horizontal.

**Comment by Vainock** [comment]
No No No, it was correct to have the &s, but every letter can only be used one time per list. You could use e and n, but you have to look if all other entries in the list also don't use these letters. I have to use free letters.

**Comment by Vainock** [comment]
Have not seen your message. But I think to have shortcuts for every entry would be very good.

**Comment by Vainock** [comment]
What do you mean with "there already is..."? Already in list?, I can not find it.

**Comment by jp9000** [comment]
I fixed this a little bit:

1. You probably shouldn't add an enum to obs.h if it isn't used in libobs.  Instead I replaced this with an enum class above the functions you added related to centering.
1. The shortcuts for hoirizontal/vertical centering had Ctrl-D for a shortcut, which was already assigned to centering to screen.  Think you might have done that by accident.  Fixed that too.

**Pull request merged**
