### PR TITLE
obs-ffmpeg: Fix issue with fractional framerate and useBFrameAsRef

### PR DESCRIPTION
**Pull request by ArmstrongCN**
## Fix dts > pts when fps set to floating-point.

Steps to reproduce:
1、settings->video->Commons FPS values: 59.94
2、settings->output->Encoder: NVENC (new)

Fixing:
1、add a calculated dts at the begining: dts1 - delta
See also: https://github.com/FFmpeg/FFmpeg/blob/2e254bb897471b4a4db2b846947fc6c00faac3e6/libavcodec/nvenc.c#L1752 :nvenc_set_timestamp

## Fix dts > pts when using useBFrameAsRef == Middle(0x2)

Steps to reproduce:
1、hard-coded useBFrameAsRef=0x2. same things happened to FFmpeg.
```bash
ffmpeg -re -stream_loop -1 -i demo.mp4 -c:v h264_nvenc -c:a aac -r 59.94 -b:v 8M -bf 2 -b_ref_mode middle -f flv rtmp://localhost/live/demo
```
the warning
```bash
[flv @ 0000019a595ff040] Invalid DTS: 83 PTS: 33 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 200 PTS: 167 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 317 PTS: 284 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 434 PTS: 400 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 567 PTS: 517 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 684 PTS: 634 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 801 PTS: 767 in output stream 0:0, replacing by guess
[flv @ 0000019a595ff040] Invalid DTS: 918 PTS: 884 in output stream 0:0, replacing by guess
```

Fixing:
1、regenerate pts and dts
See also: https://github.com/FFmpeg/FFmpeg/blob/e750dc9de61b4534776f500e22d32a07c6425231/fftools/ffmpeg.c#L764

### CODE REVIEW

**Comment by jp9000** [comment]
I don't see the problem with fractional framerates and NVENC.  They're functioning properly as far as I can tell.  What negative effect is it that you're getting with them that you're trying to fix?

For `useBFrameAsRef`, we don't use that feature of NVENC.  There's no reason to write a fix for a feature we don't use right now.

**Comment by jp9000** [comment]
By the way, if that's the code that's needed to make `useBFrameAsRef` work properly, then I'll probably never implement it just for the record.

**Comment by ArmstrongCN** [comment]
I reproduce this problem with more than 5 computers.  
My devices: Win10 with GTX 1060 (6G) and newest driver 26.21.14.3039(2019/4/17). 

Maybe it's video card related?

Due to the smaller video pts, some players will drop frames, resulting in a motionless picture.

**Comment by ArmstrongCN** [comment]
I make a general approach to catch problematic timestamps and put them right by regenerating pts/dts. 
useBFrameAsRef is just a special case.

**Comment by jp9000** [comment]
Could you explain the fractional framerate issue in terms of what effects it's having on the output?

I would prefer not to merge the useBFrameAsRef stuff.  That code to regenerate timestamps is very unpleasant and it's not something we should have to do.  I just don't want that.

**Comment by jp9000** [comment]
Sorry, disregard last message.  I missed the part where you said the media players would drop frames, resulting in motionless picture.  I can't seem to reproduce that.  What video players?

**Comment by ArmstrongCN** [comment]
Using v1.2.0 [bilibili flv.js](https://github.com/bilibili/flv.js) as live stream player, it only renders the first I frame. Maybe it doesn't play well with malformed pts/dts. The lastest v1.5.0 can fix the timestamp before playing.

We use obs to stream to rtmp server, and the server dynamically reformat to flv for players. By minus delta timestamp, each player gets a stream with timestamp from 0. Player plays the live stream as a normal flv file. Everything follows the flv and h264 rules. 

There are too many details...

By the way, ffprobe will also complaint the dts.

No matter what, as a streamer, we should try the best to produce normalized stream.

**Comment by jp9000** [comment]
The first thing I did was check ffprobe with a fractional rate recording.  I didn't get any error though, hence why I'm puzzled.  What settings did you use specifically so I can reproduce?

**Comment by ArmstrongCN** [comment]
OS: Win10 x64
Video card: Win10 with GTX 1060 (6G)
Driver: latest 26.21.14.3039(2019/4/17)
OBS Version: 23.1.0

settings->output->advance->Encoder: NVIDIA NVENC H.264 (new)
settings->video->Common FPS Values: 59.94

=======
when turning fps from 60 to 59.94, the dts may larger than pts.

```bash
[flv @ 0x5599b4148d80] Invalid timestamps stream=0, pts=2136, dts=2152, size=5214
```
If we use integer fps, the pts and dts of I frames are the same.

**Comment by ArmstrongCN** [comment]
By the way, it's a live stream problem, and i test the commit with nginx rtmp module.

**Comment by jp9000** [comment]
I am not getting any problem from fractional framerate.  Do you have the `useBFrameAsRef` setting enabled on your fork or something?

These are the recording settings:
```
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60000/1001
	format:            NV12
	YUV mode:          601/Partial
```
```
[jim-nvenc: 'simple_h264_stream'] settings:
	rate_control: CBR
	bitrate:      6000
	cqp:          20
	keyint:       119
	preset:       hq
	profile:      high
	width:        1920
	height:       1080
	2-pass:       false
	b-frames:     2
	lookahead:    false
	psycho_aq:    true
```
and this is the result from ffprobe on the file:
```
Input #0, flv, from 'test.flv':
  Metadata:
    encoder         : Lavf57.84.100
  Duration: 00:00:08.81, start: 0.000000, bitrate: 5579 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt470bg/bt709/bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 6000 kb/s, 59.94 fps, 59.94 tbr, 1k tbn, 119.88 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 160 kb/s
```
I recorded to an FLV file to see if I could reproduce that same message, but no error messages were reported by ffprobe.  Additionally, ffprobe is the latest version.

**Comment by ArmstrongCN** [comment]
Adding debug output to jim-nvenc.c and obs-ffmpeg-output.c, I found that jim-nvenc didn't take part in local recording. And local recording rescales the timestamps for output file.

Add a debug log in jim-nvenc.c::nvenc_encode_tex#Line889

```c
if (enc->packet_data.num) {
               ....
               /* subtract bframe delay from dts */
		if (enc->bframes)
			dts--;
		info("packet timestamp error: %s, pts: %ld, dts: %ld",
			packet->pts < packet->dts? "true":"false",
			packet->pts, packet->dts);
               ....
}
```

we can see the timestamp sequence:
```
10:53:04.373: [jim-nvenc: 'streaming_h264'] packet timestamp error: false, pts: 0, dts: -1
10:53:04.388: [jim-nvenc: 'streaming_h264'] packet timestamp error: false, pts: 3003, dts: 1000
10:53:04.404: [jim-nvenc: 'streaming_h264'] packet timestamp error: true, pts: 1001, dts: 2001
10:53:04.423: [jim-nvenc: 'streaming_h264'] packet timestamp error: true, pts: 2002, dts: 3002
10:53:04.438: [jim-nvenc: 'streaming_h264'] packet timestamp error: false, pts: 6006, dts: 4003
10:53:04.455: [jim-nvenc: 'streaming_h264'] packet timestamp error: true, pts: 4004, dts: 5004
10:53:04.472: [jim-nvenc: 'streaming_h264'] packet timestamp error: true, pts: 5005, dts: 6005
10:53:04.488: [jim-nvenc: 'streaming_h264'] packet timestamp error: false, pts: 9009, dts: 7006
10:53:04.504: [jim-nvenc: 'streaming_h264'] packet timestamp error: true, pts: 7007, dts: 8007
```

**Comment by jp9000** [comment]
I verified that the initial DTS was incorrect for fractional framerates.  I switched the muxer to the "flv_output" muxer which is my own muxer to test rather than ffmpeg, and indeed the initial DTS was incorrect.  However, the equation you use was not what was necessary to fix it.  The line
```C
		packet->dts--;
```
was the problem because it assumed the time base of the packets were in frames.  For whole number framerates this was technically correct because it's supposed to be subtracting the numerator of the time base, which is always 1 for whole number framerates, but for 59.94, the numerator is 1001.  Switching it to
```C
		packet->dts -= packet->timebase_num;
```
solves the bug, and after doing so, the initial DTS now matches the old NVENC.

**Comment by jp9000** [comment]
It should now be fixed.  Additionally, I would prefer not to include the code that handles `useBFrameAsRef`.  I'd rather just never use that option if that's the code we'd have to execute.  It feels like we're "fixing" something that's broken with NVENC itself.  That doesn't feel like something that should be our responsibility to fix, and I'd prefer never to use that option as long as that continues to be so.

**Pull request closed without merging**
