### PR TITLE
cmake: Make QR-Code-Generator finder debug aware.

### PR DESCRIPTION
**Pull request by admshao**
### Description

Similar to NTV2 lib files we ship 2 different files for the Release and Debug builds so this makes the finder aware of the changes and selects the correct file based on the build type.

v2: Updated to make the changes Windows only.

### Motivation and Context

I want to be able to build OBS Studio in Debug mode.

### How Has This Been Tested?

Windows:
After build OBS-Deps with the following changes: [obs-deps - PR#210](https://github.com/obsproject/obs-deps/pull/210)
I built OBS Studio with (Debug, Release, RelWithDebInfo, MinSize) and all launched OBS Successfully 

Macos, Linux:
Needs Tests.

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Rather than modifying the whole finder behavior just for Windows, try to replace `Libqrcodegencpp::Libqrcodegencpp` (our finder) by `qrcodegencpp::qrcodegencpp` (available CMake package) for Windows-only which should use the debug build automatically.

The finder is only meant to avoid having Ubuntu causing issue.

**Comment by PatTheMav** [comment]
This PR is superfluous, as Windows builds should never use the finder and using a `d` suffix for debug variants is a Windows-specific thing.

**Comment by RytoEX** [comment]
> This PR is superfluous, as Windows builds should never use the finder and using a `d` suffix for debug variants is a Windows-specific thing.

How is this superfluous? obs-studio cannot be built in Debug even with both qrcodegencpp.lib and qrcodegencppd.lib in the deps/lib folder. This is the same problem that we had with AJA and VPL, so why aren't changes necessary?

**Comment by PatTheMav** [comment]
The library is called `qrcodegencpp` for Windows and macOS and is shipped as a CMake package with a `qrcodegencpp-targets-release.cmake` and `qrcodegencpp-targets-debug.cmake` file (with the associated `obs-deps` PR merged).

`libqrcodegencpp` and its finder can only be used on Linux.

**Comment by RytoEX** [comment]
> The library is called `qrcodegencpp` for Windows and macOS and is shipped as a CMake package with a `qrcodegencpp-targets-release.cmake` and `qrcodegencpp-targets-debug.cmake` file (with the associated `obs-deps` PR merged).
> 
> `libqrcodegencpp` and its finder can only be used on Linux.

Then something isn't working correctly, because even with those targets files, I cannot build in Debug on Windows.

**Comment by PatTheMav** [comment]
https://github.com/obsproject/obs-websocket/blob/ec2cdc84759d737e8612fdd0b3c3fcec6ac89761/CMakeLists.txt#L21

Needs to be changed into:

```
if(OS_MACOS OR OS_WINDOWS)
  find_package(qrcodegencpp REQUIRED)
else()
  find_package(Libqrcodegencpp REQUIRED)
endif()
```

Alternatively the finder needs to be updated to work as a drop-in replacement when the CMake package cannot be found, which means changing the name from "FindLibqrcodegencpp" to "FindQrcodegencpp" and ensure the target names match as well.

**Comment by tytan652** [comment]
> Alternatively the finder needs to be updated to work as a drop-in replacement when the CMake package cannot be found,

The name was made different since there was zero guarantee that they work the same way (e.g. behavior if a version is put as find_package argument).

Maybe if `qrcodegencpp::qrcodegencpp` was not found (QUIET in find_package), fallback to `Libqrcodegencpp::Libqrcodegencpp`.

> which means changing the name from "FindLibqrcodegencpp" to "FindQrcodegencpp" and ensure the target names match as well.

"FindQrcodegencpp" does not work since it's awaiting for a `Qrcodegencpp` (uppercase Q) target.

**Comment by RytoEX** [comment]
Going to go with #9601 instead. Apparently, the Finder should never have been invoked on Windows and was only being invoked due to an oversight.

**Pull request closed without merging**
