### PR TITLE
obs-filters: Add loudness normalization filter

### PR DESCRIPTION
**Pull request by tleydxdy**
uses [libebur128](https://github.com/jiixyj/libebur128) to normalize audio to a target level

### CODE REVIEW

**Comment by dodgepong** [comment]
FYI, once you are done with your changes, you will need to squash them into a single commit.

**Comment by tleydxdy** [comment]
yeah I got it, just that I don't know why the windows build is failing, right now I'm just writing down were the header file is directly in the .c file, and the build is working it seems

**Comment by tleydxdy** [comment]
somehow one of my earier version just passed on appveyor but not the others, someone that have a windows machine could prrbably solve this in minutes. so I'm just gonna leave it like this then, at least it builds

**Comment by jp9000** [comment]
We can't use this due to the library used.  I just don't really feel like it's worth it.  We already use too many dependencies as it is.

**Pull request closed without merging**
