### PR TITLE
UI: Add preview/program labels in studio mode

### PR DESCRIPTION
**Pull request by cg2121**
screenshot from 2019-02-28 15 28 52

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
How does this look in vertical mode?

**Comment by cg2121** [comment]
Vertical Mode:
screenshot from 2019-02-28 15 42 23

**Comment by eliasthompson** [comment]
This would be pretty useful to use with the suggestion to (allow switching their places)[https://github.com/obsproject/obs-studio/pull/1695].

**Comment by Warchamp7** [comment]
Preview / Program is obviously the known production terminology but I'm wondering if it's better for us to do Preview / Live. Savvy users will understand and it will also be more clear to the average person

**Comment by cg2121** [comment]
The others labels I was thinking of doing was Edit/Live, but the multiview has Preview/Program as well.

**Comment by WizardCM** [comment]
Should this also be configurable in Settings -> General -> Preview, so that people who want to be as space efficient as possible can disable these?

**Comment by cg2121** [comment]
I have made the labels smaller, so they don't take up as much space.
screenshot from 2019-03-03 01-41-35

**Comment by SuslikV** [comment]
Bug: https://obsproject.com/mantis/view.php?id=1393

**Pull request merged**
