### PR TITLE
UI: Clarify use of new NVENC if available

### PR DESCRIPTION
**Pull request by Gol-D-Ace**
This PR concerns the following Mantis case: https://obsproject.com/mantis/view.php?id=1399

If you have a better idea for the wording then please reply in the comments here.

### CODE REVIEW

**Comment by SuslikV** [comment]
I think that "new" itself should be avoided here. If this is only available option then no sense to change it.

Anyway, my variant:
`Hardware (NVENC), via SDK or FFmpeg`

**Comment by Gol-D-Ace** [comment]
This change is mainly intended for end users which think they have to switch from simple output to advanced output mode.

While your suggestion is fine to a technical advanced user a novice will not know what the VideoSDK or FFmpeg is.

They just want to use the "new stuff that NVIDIA is advertising".

**Comment by SuslikV** [comment]
Maybe add tip here? That the SDK is new implementation (by Jim) of famous NVENC and will be used by default, and FFmpeg is here only for compatibility reasons. While for Output Mode: Advanced, the FFmpeg also allows Rescaling.

**Comment by Gol-D-Ace** [comment]
Issue with a tooltip is discoverability, before they see the tooltip they will change the output mode to advanced, and we are back to the point why I'm making a PR for this.

To avoid users changing to advanced mode when it isn't necessary for them.

**Comment by Vainock** [comment]
"Uses newest available implementation" is much better I think.

**Comment by SuslikV** [comment]
> ...
> To avoid users changing to advanced mode when it isn't necessary for them.

I know the solution... In this case obs should show popup when user tries to change the _Output Mode_ to _Advanced_. LOL It so simple. Everybody will see it. It cannot be ignored! Same to surround sound warning. LOL People don't read the messages and clicking the buttons faster than you thinking and you expecting that someone will read the option's long description? I still think that if you mention that there are two or more variants of the encoder - who read the message, unavoidably would like to get the full control over the available encoder's type (no matter if it supported or not, has their video driver specific NVENC's bug or not). People want to force the option always. So, it doesn't prevent user from switching to _Advanced_ when option just renamed.

**Comment by Gol-D-Ace** [comment]
Perhaps
Automatically determines best available method?

**Comment by DDRBoxman** [comment]
Uses newest possible encoder
?

**Comment by Fenrirthviti** [comment]
I think "(prefer new)" is the correct phrasing here. We need to keep this simple and to the point.

**Comment by jp9000** [comment]
How about this:  add a new string, "Hardware (New NVENC)", which is used if on windows 8/10+,  otherwise it uses the old string.

**Comment by Fenrirthviti** [comment]
I think it's important to imply that using the new encoder is not guaranteed even when selected. Our detection methods and prevention of fallback is not foolproof at this time.

**Comment by Warchamp7** [comment]
If we feel any need to be verbose here, it should be an advanced option.

My input is that Simple mode should just say something as straightforward as "NVENC (Automatic)" or (Auto-select), and imply that Advanced mode would let them choose

**Comment by Fenrirthviti** [comment]
I like "NVENC (Automatic)".

**Comment by Gol-D-Ace** [comment]
I still have the feeling that it should somehow mention new.

From my understanding people use Advanced Output Mode because it doesn't say New.

Something like Automatic might not give the feeling it's "New".

**Comment by Gol-D-Ace** [comment]
I have the feeling that renaming this is probably not the best solution and is only concealing the issue.

Having this "solved" with the output ui remake is probably better.

**Pull request closed without merging**
