### PR TITLE
docs: Add transition duration changed event

### PR DESCRIPTION
**Pull request by cowboy**
### Description

PR https://github.com/obsproject/obs-studio/pull/2053 didn't update the OBS Studio Frontend API `obs_frontend_event` list to mention the `OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED` event that was added, which made it a bit difficult to find. So I've added it 😉 

### Types of changes
What types of changes does your PR introduce? Uncomment all that apply
- Documentation (a change to documentation pages)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
The only change I'd request here is to use this wording:

> Triggered when the transition duration has been changed by the
> user.

**Comment by cowboy** [comment]
> Triggered when the transition duration has been changed by the
> user.

For wording changes, GH suggestions work well, but no worries, I've got it!

**Comment by cowboy** [comment]
Done in 9e4f278c7a043e0ce38032e1c1d300e6751d73c5

**Comment by RytoEX** [comment]
> 
> 
> > Triggered when the transition duration has been changed by the
> > user.
> 
> For wording changes, GH suggestions work well, but no worries, I've got it!

I avoid GitHub Suggestions if only because they produce extra commits. Since we usually ask be squashed to make reviewing easier, and rebasing, squashing, and force pushing is not a process all git users are familiar with, I just use the normal review tools.

**Pull request merged**
