### PR TITLE
decklink: Release COM objects

### PR DESCRIPTION
**Pull request by hellowanda**
### Description

Some COM objects are not released in Decklink module.

### Motivation and Context

When OBS exits, these un-released decklink COM object may cause crash inside an unknown thread which started by decklink driver.

### How Has This Been Tested?

Tested on Windows

### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
Just nitpick comments for the commit message.
- What is `COM objects`? Could you be accurate to describe in the commit message?
- The first line should start from `decklink: ` (first letter should be lowercase).

**Comment by Ftlvr35** [comment]
Chaturbate live streaming

**Comment by mufunyo** [comment]
> * What is `COM objects`?

COM means the Microsoft Component Object Model. I think it's fair to assume knowledge of the acronym in the commit message.

**Comment by hellowanda** [comment]
> Just nitpick comments for the commit message.
> 
> * What is `COM objects`? Could you use an accurate term to describe in the commit message?
> * The first line should start from `decklink: ` (first letter should be lowercase).

The commit message has been modified.
As to the 'COM objects', @mufunyo (Thanks) has explained, I think it's more like 'SDK', 'GPU'... .Of course, if necessary, I can change it to its full name.

**Comment by cg2121** [comment]
Does Decklink use any RAII to auto release the COM objects? I believe the main reason this is being held up is that @jp9000 wants these to be auto released, as OBS is starting to use RAII more in its code.

**Pull request closed without merging**
