### PR TITLE
Windows: Taskbar icon & colour

### PR DESCRIPTION
**Pull request by WizardCM**
### Description
This adds a taskbar colour & status icon on Windows 8 and above.
image image
**No output**: normal. **Live output**: green. **Paused recording**: yellow.

Not actually sure if the overlay icons should be configurable by the theme. **Feedback welcome in this area.**

### Motivation and Context
Users often mention that live/recording/paused status is not visually obvious enough. Colour at a glance, along with an icon, should help.

### How Has This Been Tested?
* Launch OBS on Windows 8 or above
* Start Recording. Notice the colour of the taskbar button changes to green, and 🔴 appears on top.
* Pause the recording. Notice the taskbar button changes to yellow, and the 🔴 changes to a yellow paused icon.

### Types of changes
 - New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jp9000** [comment]
Could you choose one feature and make a PR for the other feature?  I don't like having two features in one PR, I feel like we should cut down on those sort of things.

**Comment by WizardCM** [comment]
Not a problem, I simply included them together because they both depend on the existence of QWinTaskbarButton and Qt5WinExtras, so I felt it'd be cleaner as one.

Would you prefer both contain the changes to import Qt5WinExtras, or just make one PR dependent on the other @jp9000?

**Comment by jp9000** [comment]
Well I can merge the one you need to be merged first, then after that, create a PR for the other one and then we'll merge that one.

**Comment by WizardCM** [comment]
Will do! I'll split them up tonight. :)

**Comment by WizardCM** [comment]
PR has been split. Starting off with the taskbar itself. Note when testing, you will need to uncheck Copied Dependencies in CMake.

**Comment by xcasxcursex** [comment]
This is great, but why green? Recording traditionally has a red light and that's for good reason - it's a warning - that one should be quiet, that one might be recording over existing material, etc, etc.

**Comment by WizardCM** [comment]
That's something I wasn't fully sold on too, it could work either way:
1. People want better visibility that OBS is recording. Red, or green, either way would be better than nothing
2. Green in terms of things happening in the _taskbar specifically_ means "it's working". Red is usually an indicator of "there was an error", but in other situations red means "it's recording"
3. Note that the same colour is used regardless of recording, streaming or replay buffer.

I'm not sure what you mean by recording over existing material?

**Comment by xcasxcursex** [comment]
>     1. People want better visibility that OBS is recording. Red, or green, either way would be better than nothing

Absolutely, I'm all for this change, either way.

>     2. Green in terms of things happening in the _taskbar specifically_ means "it's working" (as it's based on a progress bar). Red is usually an indicator of "there was an error", but in other situations red means "it's recording"

This is the problem I guess, there's a conflict here between how to interpret the 'traffic light' colours; (green = it's going, red = it's stopped) and recording industry standards (red = it's recording, so stop doing that thing you would normally do)

>     3. Note that the same colour is used regardless of recording, streaming or replay buffer.

This occurred to me and I hadn't brought it up but it would be an extra nice thing if it had a different indicator depending on behaviour. 

> I'm not sure what you mean by recording over existing material?

This 'red=recording' thing goes all the way back to the days of tape (and probably further but I'm not that old) where one might be recording a new take over an old take, thus destroying data they wanted to keep. I guess the modern application of this would be if you have a fixed filename you record to, and you might be recording over an existing file. 

Anyway, the point I'm trying to make there is that the red colour is chosen as a warning because recording is serious business fraught with threats that don't apply when not recording. I could invent lots of examples like "Ooh the scary red light is on, don't swear on the live stream" ;) But I'm just trying to point out in various ways, that red is the traditional colour, because it is meant to be a warning.


As you say I'm not fully sold either way. I have a lot of time in recording studios so green=recording jumped out at me as being bizarre (so I commented), but then I have even more programming experience and I get that the green progress bar in the taskbar is a Windows standard, so... Yeh I just thought I'd ask the question, why this colour?

And yes, either way is better than nothing. Even better than that, is an option - one person's "useful indicator" is another person's "annoying light". But now I'm just opening a can of worms.

**Comment by WizardCM** [comment]
Well, that's exactly why PRs have a comment section - to garner feedback like this!

In terms of using the same colour regardless of session type, I'm leaning towards keeping it this way purely because while right now we do only have 3 core methods, in future we'd like to have more (dynamically, for eg. streaming to two services at once) - and plugins (I don't think) are currently counted (NDI, VirtualCam, Decklink, etc). Keeping it consistent & dead simple will help us in the long run. I literally hijacked the tray icon's functions to update the taskbar, both for consistent behaviour and less unnecessary logic in the code overall.

I think adding a config option to choose red vs green is a bit unnecessary, purely because in most cases (imo), people won't care, and it's just _yet another_ obscure, edge case setting (we have a fair few number of those). Again, dead simple here probably works best?

Question in that case - if we keep it as green, is the red dot 🔴 in the corner of the icon helpful enough to explain what's going on to someone more used to red being the primary indicator?

**Comment by xcasxcursex** [comment]
Yep the KISS approach is popular for good reason ;)

> I think adding a config option to choose red vs green is a bit unnecessary, purely because in most cases (imo), people won't care, and it's just _yet another_ obscure, edge case setting (we have a fair few number of those). Again, dead simple here probably works best?

Oh yes totally, I don't think an option to choose colour would be worth it at all. Sorry I wasn't clear, what I meant was an option to colour the taskbar at all, or not. I mean to say, not a 'red or green' option, but a 'colour or not' option. 

But again yeh that's a can of worms. I didn't really mean to bring that into discussion, it just kinda incidentally occurred to me because for example I know of some media players that show a green progress bar in the taskbar, to show how far through the movie you are - and all it does is distract from the movie. I can imagine that being the same for gamers. For some it would be nice to have a green light letting us know that recording is working OK, for others it would be a distraction from the game on screen.

Anyway, trying not to stray too far into that can of worms (sorry about that!)


> Question in that case - if we keep it as green, is the red dot 🔴 in the corner of the icon helpful enough to explain what's going on to someone more used to red being the primary indicator?

Yes I think it's enough. 
It might strike some people (edge-case recording studio nerds) as being strange to see red and green but I'm sure they can figure it out, if the red dot is there.
And probably easier than a normal, non-edge-case end-user trying to figure out why red means something good is happening ;)

**Comment by xcasxcursex** [comment]
By the way, a quick demonstration of how this feature can be useful (obvious in the case of OBS, hence this commit) but also can be intrusive:

Watching a movie without the taskbar colour:
image
Note the minimal distraction from the content. Pretty much everything is black, and what isn't, is static.

Watching a movie with the taskbar colour:
image
Not only is there now a bright area of colour, it is also dynamic, presenting a twofold distraction from the content.

Fortunately, this option can be disabled in this player quite easily:
image

The player, MPC-HC, is open source, so perhaps referencing their code may be helpful if you wish to make such an option available in OBS to avoid distraction from the content being streamed.
The taskbar colouring seems to happen [here](https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/PlayerSeekBar.cpp#L200)
(Most of this function is just syncing the taskbar mouseover thumbnail to the video, but this part also updates the taskbar progress bar)

Frankly, I don't see that changing the taskbar icon would be a problem in any way, since it's small, there is colour there anyway, and it is static, but that colouring can be a distraction sometimes.

**Comment by WizardCM** [comment]
I have rebased this PR and resolved the merge conflicts.

**Comment by notr1ch** [comment]
After using this in development for a while now, I'm starting to dislike the taskbar color changes. I don't think they are necessary when we have the icon, and it becomes quite distracting when they aren't used for temporary progress-related notifications - eg while OBS is recording I find myself constantly looking at the taskbar icon due to the green progress bar.

**Comment by xcasxcursex** [comment]
Please keep in mind that I have near-zero experience with OBS's codebase and this is a genuine question: Wouldn't it be simple to add a checkbox in the settings, to enable or disable this feature? I guess if you wanted to be really fancy you'd have four - one for each mode (stopped, paused, recording, buffering). I've read the code to add the checkbox and it's a cakewalk, and then wouldn't it just be a matter of surrounding the calls to paint the taskbar with conditions of those values? Strikes me as easier than answering a flood of posts about how it can't be disabled ;) But I don't know anything so please forgive me if I'm miles off the mark here.

**Comment by Fenrirthviti** [comment]
The primary issue with using the task bar color change here is that it's an abuse of a feature that was not intended to be use this way, and breaks paradigms established by the Windows UI in general. I get that it is supposed to be distracting so users know that OBS is active, but I feel this is taking things a bit too far, and it should be made optional with it disabled by default, or removed entirely. I understand the intentions here are good, we need better ways to properly notify when the program is active, but this feels like an ugly hack that is not likely to really help anyone. We should look in to other solutions.

**Comment by xcasxcursex** [comment]
> a feature that was not intended to be use this way, and breaks paradigms established by the Windows UI in general

Am I missing something? https://docs.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#progress-bars

**Comment by Fenrirthviti** [comment]
> Am I missing something? https://docs.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#progress-bars

Yes. To quote that documentation:

```This feature can be used to track file copies, downloads, installations, media burning, or any operation that's going to take a period of time.```

OBS doesn't have a "progress" here, or a period of time. It is an active state, which is not what a progress bar should be used to convey. It's an abuse of a feature to use it this way, and not what the feature was intended to indicate.

**Comment by xcasxcursex** [comment]
Ahh I see where you're coming from. I mean, I suppose there is 'progress', toward your disk being full, and if the bar showed that, or was in the '[indeterminate state](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate#tbpf_indeterminate-0x00000001)', then that would strictly meet the definition or the feature's intended use.... but that's a stretch at best, I don't think this PR was ever intended to indicate diskspace ;)

So yeh, it's definitely not the intended usage of the feature.... And I get why you seem kinda passionate about it, breaking UI/UX conventions is bad mkay (don't ask me how I feel about keyboards with Fn keys in the bottom left/right modifier clusters, grrr!) but what else does Windows provide that does the job so well as this? Frankly, after a few "OMG I wasn't recording" moments, I'd take anything up to and including a UFC fighter who repeatedly slaps me on the head and shouts "you're not recording, dummy' ;)

**Comment by jp9000** [comment]
I have been smacked upside the head because of vocal disagreements about changing the color in such a way, and thus this has been reverted.

**Comment by xcasxcursex** [comment]
> I have been smacked upside the head because of vocal disagreements about changing the color in such a way, and thus this has been reverted.

Well that's a real shame, I thought it was a really good change and I'm sure that as many people took issue with it, there would be an equal number would have applauded it. 
It just needed that one option :( Then everyone would be happy....

**Pull request merged**
