### PR TITLE
Encoder error feedback

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Similar to how outputs can store errors in their internal structure, this PR extends the same functionality to encoders. WIP for critique on the design and usefulness of this change as the cases where this is most useful (failed NVENC initialization) are hampered by the fact that jim-nvenc automatically falls back to ffmpeg nvenc which has far less useful error messages.

### Motivation and Context
When an encoder fails, the only clues are in the log file. By storing the most recent error, this can be passed to the output, and eventually back to the UI, allowing a more useful user-facing error message than "Starting the output failed".

### How Has This Been Tested?
I injected faults into jim-nvenc and ffmpeg nvenc encoders and verified the errors appeared in the UI. Example screenshot of a failed NVENC recording output: https://i.imgur.com/pfbyleP.png

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
I notice this is still in draft status. @notr1ch what, if anything, is this waiting on? Might be worth making a checklist - I'd at least like to see it tested with AMF and VAAPI. I've also added the Request for Comments label to help in that regard.

In terms of usefulness, I think this is incredibly useful, and requires less "digging through the log file". A lot of users are often confused by the "[...] if you are using the NVENC or AMD encoders, make sure your video drivers are up to date" error text, and this'd go a long way towards improving that. My only concern, and this may be a minor one, is localisation. As the text is coming direct from the encoder,  not only may it be incredibly technical at times (looking at AMF's "Profile" error), but non-English users who don't know English often ignore messages that aren't in their native language.

**Comment by notr1ch** [comment]
I just didn't think it was useful in its current state due to the ffmpeg NVENC fallback, which hides the most actionable errors from the user. Was hoping maybe to start a discussion about whether the fallback is still necessary.

**Comment by jp9000** [comment]
I think it's important to have error feedback.  For the fallback issue, that's sort of an unavoidable thing right now, unless someone wants to reimplement all that non-texture specific code path in the newer nvenc implementation.  I don't think the fallback issue should prevent us from trying to get normal error feedback.

I'd say maybe we should treat the whole fallback thing as a warning rather than an error, something that would fall outside of the scope of this particular PR because it would have to be communicated in a different way.  Although the fallback issue is sort of complicated, because on systems where texture-based NVENC isn't available for whatever reason, I'm not sure of the value of showing such a warning, especially considering there's rarely anything the user can do about it.  And especially considering the performance impact is a relatively insignificant change, so I can't help but to wonder if there's really that much value in communicating that particular thing to the user.

I don't think handling the fallback case should preclude us from having error feedback, or cause us to hesitate giving feedback in those sort of hard error cases where the encoder didn't start.  I can't help but feel that the fallback case is just something we should make note of and discuss and/or solve as a separate issue after that, rather than try to bundle it in with this particular PR.

Well, at least in my humble opinion.

**Comment by notr1ch** [comment]
Perhaps I wasn't being clear about the issue with the fallback issue here. There are a couple of key cases where the texture-based NVENC startup fails with actionable errors:

- User has too many concurrent NVENC sessions (user can close game DVR or whatever else)
- Outdated driver (user can update driver)

When using the NVENC SDK directly it gives us these specific error codes, but due to the fallback, the encoder is restarted with ffmpeg-nvenc. ffmpeg-nvenc startup also fails due to the same problems that caused the texture-based NVENC to fail, but being limited to ffmpeg return values, these errors are now returned as "invalid parameter" or "generic error in external library" error messages which are pointless to show the user.

**Comment by jp9000** [comment]
Oh I see, so basically what you're saying is we shouldn't fall back automatically on any error.  Sorry about that, I understand what you mean now.  So basically what you're saying is we should fix that up first?

**Comment by jp9000** [comment]
I'll see what I can do to fix it up.

**Comment by notr1ch** [comment]
The NVENC fallback to ffmpeg version is planned to be removed, so opening this up for merging when that happens.

**Pull request merged**
