### PR TITLE
rtmp-services: Add wasd.tv

### PR DESCRIPTION
**Pull request by keylase**
### Description

Added wasd.tv to streaming services drop down.

### Types of changes
New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by notr1ch** [comment]
Is there a specific reason you requested main profile? Unless needed for compatibility with very old devices, it's best to leave it unset so OBS defaults to high profile.

**Comment by notr1ch** [comment]
Several of the servers added appear to be invalid:

```
ERROR: Couldn't resolve 'ru-moscow.rtmp.wasd.tv' for 'WASD.TV' / 'Russia, Moscow'
ERROR: Couldn't resolve 'de-frankfurt.rtmp.wasd.tv' for 'WASD.TV' / 'Germany, Frankfurt'
ERROR: Couldn't resolve 'fi-helsinki.rtmp.wasd.tv' for 'WASD.TV' / 'Finland, Helsinki'
```

**Comment by keylase** [comment]
> fi-helsinki.rtmp.wasd.tv

fixed

**Comment by keylase** [comment]
> Is there a specific reason you requested main profile? Unless needed for compatibility with very old devices, it's best to leave it unset so OBS defaults to high profile.

Sounds logical. Fixed

**Comment by keylase** [comment]
conflicts resolved 
@WizardCM @notr1ch is it ok now?

**Comment by Fenrirthviti** [comment]
No, you still need to squash your commits. You have three. Rebase your branch and force push and the PR will automatically update.

**Comment by keylase** [comment]
> No, you still need to squash your commits. You have three. Rebase your branch and force push and the PR will automatically update.

done

**Pull request merged**
