### PR TITLE
UI: Add source icons

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This adds icons in the add source menu and in the sources list.

### Motivation and Context
This makes it easier for users to differentiate between different sources.
https://ideas.obsproject.com/posts/24/have-icons-for-source-types
Screenshot from 2019-08-03 04-50-45

### How Has This Been Tested?
This has been tested on Linux and Windows. Mac needs testing because it can weird with UI stuff.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

The gamepad icon is from Font Awesome
https://fontawesome.com/

The camera, globe and monitor icons are from Octicons
https://octicons.github.com/

The default icon is from Feather Icons
https://feathericons.com/

The rest of the icons are from Open Iconic
https://github.com/iconic/open-iconic

### CODE REVIEW

**Comment by DDRBoxman** [comment]
Do the themes intentionally not define default icon?

It might be a better idea to let sources define another function that returns an enum with a "source category" and then themes can map those categories to icons. eg, camera, window, audio input, screen, etc.

**Comment by Xaymar** [comment]
> It might be a better idea to let sources define another function that returns an enum with a "source category" and then themes can map those categories to icons. eg, camera, window, audio input, screen, etc.

Expanding on that idea, perhaps allow it to set two const char**, the first one is the category, and the second one is the path to a default icon in case of a plugin adding new sources.

`obs_get_source_category_and_icon(const char* source_id, const char** category, const char** default_icon)`

**Comment by cg2121** [comment]
The reason for not having a default icon in the themes, is that I couldn't find an icon that I liked for it, so I just left it blank for now. Any suggestions for an icon would be greatly appreciated.

**Comment by cg2121** [comment]
I've now added the ability for sources to define an icon type. I've also added a default icon.

**Comment by WizardCM** [comment]
On Windows 10, the following sources are using the default page icon at the moment:
* Browser Source (I'd recommend a globe, personally)
* Display Capture/Duplicator (Should be the same as XSHM)
* Image (must work differently than the linux one, I suppose?)

The Group and Text icons feels very large compared to the others, and the Scene icon is aligned along the top which looks strange.

I wonder if it'd be worth using an official SVG for the VLC source.

I also noticed that you seem to have adjusted the margins on items in the sources and scenes lists so that the icons (which seem to be 16x16) don't get too close to the edges. While I get the thinking behind this, I feel most people who stick to the System/Default theme are not interested in the larger margins provided by Acri, and prefer the benefits of fitting more items. I'd lower the margins down a bit, at least 1 or 2px. They add up.

I think it'd be worth describing a bit more about how it works in the original PR, so those of us who are able to test can make sure we're covering all the bases. Things like "icon priority is based on theme first, then the source's definition, then a fallback." Could also check with @Fenrirthviti and @Warchamp7 to see if they have icon sets they'd like to use in Rachni and Acri.

**Comment by cg2121** [comment]
I have no idea why some icons don't work. These image icon doesn't work on Linux either. I can't find anything in my code that would cause this. It has been driving me nuts.

**Comment by cg2121** [comment]
I've fixed the issue where some icons wouldn't work. Everything should be good to go now. After this is merged I'll make a PR for the browser source to add the icon type to that plugin.

**Comment by WizardCM** [comment]
Reminder: this PR has merge conflicts.

**Comment by cg2121** [comment]
The merge conflicts have been resolved.

**Pull request merged**
