### PR TITLE
libobs: add missing multimedia hotkeys for Windows

### PR DESCRIPTION
**Pull request by ujifgc**
### Description

This PR adds missing multimedia and OEM keycodes for Windows.

image

### Motivation and Context

Before this PR OBS could not register multimedia keys as hotkeys. Such hotkeys are common on extended keyboards and supported by Windows. Example: Next Track, Volume Up, Volume Down, Launch Calc, Browser Next, Browser Stop.

### How Has This Been Tested?

Tested on Windows 8.1

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Why do you include vast swaths of unassigned key codes and skip assigned keycodes within those blocks? E.G. 0x16 is included, this is officially unassigned. 0x015 is not included, but is officially assigned VK_HANGUL.

**Comment by ujifgc** [comment]
I don't include 0x15 VK_HANGUL because it's already included in OBS https://github.com/obsproject/obs-studio/blob/66967b7a550d114b0a2b0ef37611d5c2fab6c61f/libobs/obs-windows.c#L640

I include 0x16 because if some custom keyboard would send 0x16 keycode it would not register in OBS.

**Comment by jp9000** [comment]
Was it necessary to add unnamed VK keys?

**Comment by ujifgc** [comment]
It's limiting not to add them. Modern extended keyboards can send any custom virtual key to OS. By extended keyboard I mean programmable KBD75-like and keypads with controllers.

**Pull request merged**
