### PR TITLE
libobs/UI: Add option for automatic cropping to bounding box

### PR DESCRIPTION
**Pull request by derrod**
### Description

Adds the option to automatically crop a sceneitem to its bounding box.

Demo:

https://github.com/obsproject/obs-studio/assets/3123295/0a04deeb-0c77-4d88-83d0-82083728254a

(The clip is from an older revision with some floating-point precision related bugs, these have been fixed.)

### Motivation and Context

Useful to scale an image to a predefined size without stretching or having to manually calculate the crop. Also Alt-cropping with bounding boxes is awkward at best.

Has been requested by users a number of times, including on the ideas page:
- https://ideas.obsproject.com/posts/1181/add-option-to-crop-to-bounding-box-in-source-transform
- https://ideas.obsproject.com/posts/1895/cropping-source-to-predefined-bounding-box (Partially, this user also wants zoom + pan within the box)
- (Probably more)

### How Has This Been Tested?

Cropped some sources.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Penwy** [comment]
Having the sceneitem flipped (negative value for the scale) creates markedly unexpected behaviour as soon as the flipped dimension gets cropped (sceneitem getting outside of the bound, with wrong crop value).

**Comment by derrod** [comment]
> Having the sceneitem flipped (negative value for the scale) creates markedly unexpected behaviour as soon as the flipped dimension gets cropped (sceneitem getting outside of the bound, with wrong crop value).

Should be fixed now, tested with both horizontal and vertical flip as well as both at the same time.

**Comment by Penwy** [comment]
Latest build has no issues I could find

**Review by Warchamp7 — APPROVED** [review]
Lots of discussion off-thread. I think there are deeper changes we should look into for bounding boxes, but they're out of scope for this PR and not worth blocking it over.

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
