### PR TITLE
ADD Media Source Speed playback Shortcut

### PR DESCRIPTION
**Pull request by MrOizo79**
As per object, i think it's very frustrating when you have to change speed of a media source video, you have to right click mouse , choose property and use the slider to set the speed.
Also it should be a real time modification instead of reloading the video from beginning when you change speed.

### CODE REVIEW

**Comment by WizardCM** [comment]
Feature requests should be submitted via the [Ideas site](https://ideas.obsproject.com/). GitHub Issues is only for bug reports.

**Comment by tt2468** [comment]
Looks like you've got an invalid PR branch. Your merge branch should use the commits from `master` and not a release branch.

**Comment by MrOizo79** [comment]
The one i'm suggesting it  is a new feature isn't it? I created a new pull didn't i?

**Comment by jp9000** [comment]
If you're adding your own feature, you have to do it from your own branch from your own fork. You made a pull request from our `release/27.2` branch, which is very likely not what you intended to do.

**Comment by gxalpha** [comment]
@MrOizo79 pull requests are for getting code that you have written into OBS, not for suggesting that someone else should add a new feature. For that, please refer to [our ideas page](https://ideas.obsproject.com).

**Comment by MrOizo79** [comment]
Thank you for your explanation guys.

**Pull request closed without merging**
