### PR TITLE
UI: Block Elgato Stream Deck plugin before 5.5.2.0 to avoid crashes

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

The Elgato Stream Deck plugin older than 5.5.2.0 invokes undefined behavior that results in application crashes. Let's block older versions to prevent the crashes.

### Motivation and Context

Requested by @notr1ch . Want less crashes.

### How Has This Been Tested?

I've built this locally on Windows 11, but I have not tested this, nor am I sure how I would test it.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
The only suggestion I have is to download the fixed Stream Deck version and verify the timestamp is outside of this range, otherwise LGTM.

**Comment by RytoEX** [comment]
> The only suggestion I have is to download the fixed Stream Deck version and verify the timestamp is outside of this range, otherwise LGTM.

@Fenrirthviti confirmed that this at least blocks version 5.5.0.0 (dated March 3, 2023) and does not block the latest version (5.5.2.16). I'm not sure that we can specifically get the first version where this was fixed.

However, I've noticed that I blocked `streamdeckpluginqt6.dll` instead of the main `streamdeckplugin.dll`, so I might have to fix that.

**Review by derrod — APPROVED** [review]

**Comment by RytoEX** [comment]
For what it's worth, I can confirm that Stream Deck 6.5.0 ships plugin version 5.5.0.0 dated March 3, 2023, and that plugin crashes OBS Studio 30.1.0-rc1. Stream Deck 6.5.1 and 6.5.2 ship StreamDeckPlugin.dll version 5.5.2.16 with StreamDeckPluginQt5.dll version 5.5.2.16 and StreamDeckPluginQt6.dll version 5.5.2.0 all dated February 14, 2024.

**Comment by RytoEX** [comment]
Changed to block `streamdeckplugin.dll` instead of the Qt-version-specific variant. Re-tested against both known broken and working plugin versions and this seems to work as expected.

**Pull request merged**
