### PR TITLE
Publish to the correct Flathub branches

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
### Description

Publish beta releases to Flathub Beta's `beta` branch, and stable releases to Flathub's `stable` branch.

### Motivation and Context

The publishing jobs only account for the Flathub repository, but they do not account for the branch within these repositories. We should publish to the correct branches of the correct repositories (`beta` branch for the `beta` repo, and `stable` branch for the `stable` repo).

### How Has This Been Tested?

 - I've created a fake beta release in my repo
 - [With this branch, it correctly built and (tried to) publish to the `beta` branch of Flatpak Beta](https://github.com/GeorgesStavracas/obs-studio/runs/4669361217?check_suite_focus=true)
 - [With this branch, the `stable` build was entirely skipped](https://github.com/GeorgesStavracas/obs-studio/runs/4669361193?check_suite_focus=true)

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Adding to almost each publish steps:
```yaml
if: "matrix.branch == 'beta' || (matrix.branch == 'stable' && !contains(github.ref, '-beta') && !contains(github.ref, '-rc'))"
```
Could allow to avoid building a bundle within the `stable` job when releasing a beta/RC with the `beta` job.

**Comment by GeorgesStavracas** [comment]
> Could allow to avoid building a bundle within the stable job when releasing a beta/RC with the beta job.

I've done basically this, but using an extra step - please let me know what you think!

**Comment by tytan652** [comment]
LGTM

**Review by bilelmoussaoui — APPROVED** [review]
With the maintainer of the flatpak actions hat, lgtm

**Pull request merged**
