### PR TITLE
UI: Correct browse behavior in non-empty input edit line

### PR DESCRIPTION
**Pull request by tuduweb**
### Description

Correct browse behavior in non-empty input edit line,
to keep single-file and multi-file (selected) behavior consistent

### Motivation and Context

Found when debugged

before:

https://user-images.githubusercontent.com/30559085/218437695-31b663bb-35bf-421f-818e-06c7a8b86c4d.mp4

after:

https://user-images.githubusercontent.com/30559085/218437754-34fbde2a-7c1c-41b3-ba53-63542d376b42.mp4

### How Has This Been Tested?

Just run again
win10, latest branch

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Could you please put in writing what the observed behaviour is vs. the expected behaviour? The videos left me confused about what the supposed issue is (I'd also like to not exclude maintainers with disabilities).

**Comment by tuduweb** [comment]
I'm sorry for confusing you.
The observed behaviour:
When click the non-empty row *browse* button, the file(s) selected via dialog:
files > 1:
input file in current row will be **replaced** by new one, and other files will be appended

file == 1:
just be appended, but not replaced.

This behavior make me confused. I think this is a bug.

And after this PR, those two cases will be similar, **be replaced**.

@PatTheMav

**Comment by PatTheMav** [comment]
Got it, so it fixes the browse-button of existing entries to replace the given entry instead of appending by default?

@RytoEX would you agree that this is the expected behaviour for that button?

**Comment by tuduweb** [comment]
> Got it, so it fixes the browse-button of existing entries to replace the given entry instead of appending by default?
> 
> @RytoEX would you agree that this is the expected behaviour for that button?

Yes. and this PR fixes it.

**Comment by tuduweb** [comment]
Just fix the browse-button of existing entries when selecting one file.

And when selecting more than one file, it already replaced the given entry.

**Review by RytoEX — APPROVED** [review]
Looks good to me.

**Pull request merged**
