### PR TITLE
obs-ffmpeg: Add mxf extension to open file dialog filters

### PR DESCRIPTION
**Pull request by mvji**
### Description

Add .mxf extension to local file dialog extension filters.

### Motivation and Context

Let choose an MXF file in Obs FFmpeg source, using the open file selector

### How Has This Been Tested?

Mac os 11.6.2
Mac intel
Xcode

Tested with trying to load mxf file with and without the patch

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Per our [Contributing guildelines](https://github.com/obsproject/obs-studio/blob/b3870476324e2dc79a9d30371a1199376bcd0ad7/CONTRIBUTING.rst), please make these changes:
1. Use the correct commit prefix, in this case "obs-ffmpeg: ". Please note that there is no space between the prefix term ("obs-ffmpeg") and the colon after it.
2. Properly capitalize the first word after the commit prefix.

**Comment by WizardCM** [comment]
An example file would be useful, as I'd like to see this tested on all platforms.

Additionally, should this also be supported in drag and drop?

**Comment by mvji** [comment]
> An example file would be useful, as I'd like to see this tested on all platforms.

You can download two MXF test files here (One dnxhd, and one XDcam HD 422) : 
https://www.swisstransfer.com/d/57a12a04-b6cc-42c1-bdba-9b21270dd89b

> Additionally, should this also be supported in drag and drop?
Mxf files are already work (before this patch) if we drag and drop a media in the sources panel.

**Review by RytoEX — APPROVED** [review]

**Comment by RytoEX** [comment]
Will merge after CI completes successfully.

**Pull request merged**
