### PR TITLE
obs-ffmpeg: Add FFmpeg Options for VA-API

### PR DESCRIPTION
**Pull request by nowrep**
### Description

Add FFmpeg Options for VA-API.

### Motivation and Context

Add option to set custom FFmpeg options for VA-API encoder, which is already available for other FFmpeg encoders.

### How Has This Been Tested?

Checked the options were applied correctly. ArchLinux.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Personally, I would rather see PRs working on resolving acceleration device selection issues in the custom ffmpeg encoder than attempting to turn our supported encoder into the custom ffmpeg encoder. Options like this are precisely why the custom ffmpeg is unsupported, so I'm not sure I would agree with adding this,

**Comment by nowrep** [comment]
> Personally, I would rather see PRs working on resolving acceleration device selection issues in the custom ffmpeg encoder than attempting to turn our supported encoder into the custom ffmpeg encoder

Custom ffmpeg encoder isn't available as stream encoder, so that wouldn't help.

> Options like this are precisely why the custom ffmpeg is unsupported, so I'm not sure I would agree with adding this,

There are already encoders (x264, AMF, ...) that allow to set more options than only what is available in GUI, so I don't see how VAAPI encoder would be a different case here.

**Comment by kkartaltepe** [comment]
> Custom ffmpeg encoder isn't available as stream encoder, so that wouldn't help.

This is precisely the reason "Output to URL" was added, so this doesnt seem like blocker to me.

**Comment by nowrep** [comment]
> This is precisely the reason "Output to URL" was added, so this doesnt seem like blocker to me.

Then you can't stream and record locally at the same time, so it doesn't seem to be usable alternative.

**Pull request merged**
