### PR TITLE
UI: Connect replay buffer stopping to signal instead of slot

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Fixes a typo that resulted in a wrong connection, where the controls dock slot would attempt to connect to the main window slot instead of signal, which of course doesn't work.
To the user, this would mean that the replay buffer button text wouldn't change to "Stopping" when pressing "Stop", instead staying on "Stop" while stopping and then going to "Start" directly.

30.2 regression.

### Motivation and Context

Saw obsproject/loganalyzer#163 that excluded an `OBSBasic`, which looked suspicious. No log should contain `OBSBasic`.
Turns out that Qt logged a warning that a signal couldn't be found. Looking into that further , this makes sense since the signal that the slot was connected to wasn't a signal.

### How Has This Been Tested?

macOS 14.5
Firstly, made sure the bug indeed exists (see observation in Description).
Tested that with this patch, the button does show "Stopping".

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by tytan652 — APPROVED** [review]
LGTM, my fault with autocomplete.

**Review by RytoEX — CHANGES_REQUESTED** [review]
The change itself is fine, but the commit message could use some clarification.

**Review by WizardCM — APPROVED** [review]

**Review by Lain-B — APPROVED** [review]
Approved, but yea, I agree with Ryan, probably needs a better commit name

**Comment by derrod** [comment]
I think it was meant to say "UI: Connect replay buffer stopping to signal instead of **slot**"

**Comment by gxalpha** [comment]
> I think it was meant to say "UI: Connect replay buffer stopping to signal instead of slot"

Yes. Fixed.

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
