### PR TITLE
rtmp-services: add nanoStream Cloud / bintu profiles

### PR DESCRIPTION
**Pull request by nanocosmos-ol**
### Description

This PR adds adds presets for [nanoStream Cloud / bintu](https://info.nanocosmos.de) to OBS's services list of streaming services. 

### Motivation and Context

Easier use of OBS with nanoStream Cloud with settings for ultra-low-latency live streaming.
More and more users are using OBS with nanoStream Cloud
 
### How Has This Been Tested?

Tested the service profiles updated to the latest OBS release to nanoStream cloud (rtmp and rtmps)
(Copied over obs-plugins/rtmp-services/services.json )

### Types of changes

 * New streaming service profile for rtmp plugin, no OBS source code changes
 
### Checklist:
* [x]  I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
* [x]  My code is not on the master branch.
* [x]  The code has been tested.
* [x]  All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by derrod** [comment]
Don't forget to increment the version in `package.json` and also make sure the commit title matches our guidelines (see other rtmp-services PRs).

**Comment by dodgepong** [comment]
Cain you explain why you need the baseline profile and tune=zerolatency? What devices are you targeting that can't decode at even the main profile, much less high profile? And is the minimal latency reduction of tune=zerolatency really worth the [significant quality degradation](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=a8cb00ac-55c9-11eb-83c8-ebb5d6f907df)?

**Comment by jp9000** [comment]
Hi, we're still waiting on your response.

**Comment by nanocosmos-ol** [comment]
> Cain you explain why you need the baseline profile and tune=zerolatency? What devices are you targeting that can't decode at even the main profile, much less high profile? And is the minimal latency reduction of tune=zerolatency really worth the significant quality degradation?

Thanks for asking! We target for all browsers and need to ensure that the latency stays ultra-low around 1 second end-to-end, to enable interactive use cases. As far as I can see, the zerolatency flag mainly disables b-frames, which has a high impact on latency (about 0.5 seconds).
I trust that users may override the settings themselves if they do not need this tradeoff.

**Comment by nanocosmos-ol** [comment]
> Hi, we're still waiting on your response.

Thanks for the reminder. I hope everything is now ok.

**Comment by jp9000** [comment]
Manually merging, you'll see something like "closed via [commit]"

**Pull request closed without merging**
