### PR TITLE
rtmp-services : Change the server URL of AfreecaTV to SOOP Korea

### PR DESCRIPTION
**Pull request by Taeski-SOOP**
### Description

Effective October 15th, our service has been rebranded from Afreecatv to SOOP Korea.
We are planning to change the server URL of AfreecaTV to SOOP Korea.

### Motivation and Context

We aim to adapt the current Afreecatv configurations to be compatible with SOOP.

### How Has This Been Tested?

Locally tested and is working properly.

### Types of changes

Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
`alt_names` is intended to be used for migration from old service names - in this case, `alt_names` should be `Afreeca.TV` and `AfreecaTV` as these are the only prior names this service is known as.

**Comment by Taeski-SOOP** [comment]
@notr1ch  I revised it to one comment. Thank you.

**Comment by Taeski-SOOP** [comment]
@notr1ch 
Hi, notr1ch. I have a question.
I wonder if that request can be included in OBS Studio 31.
Also, I would like to know the release date of OBS Studio 31.

**Comment by notr1ch** [comment]
The alt_names are still not correct and the commits should be squashed and correctly formatted to the [service submission guidelines](https://github.com/obsproject/obs-studio/wiki/service-submission-guidelines).

**Comment by Fenrirthviti** [comment]
As an additional note, services are updated independently of OBS releases. This does not need to be merged for a specific release, and would be live 24~ hours after merging.

**Comment by Taeski-SOOP** [comment]
@notr1ch  I fixed it. Please review it.

**Comment by Taeski-SOOP** [comment]
I'm requesting a new one because the commit arrangement is complicated. (#11550)

**Comment by Taeski-SOOP** [comment]
@Fenrirthviti  Sorry, This was my first time working on it. I'll keep the guide well from now on.

**Pull request closed without merging**
