### PR TITLE
aja: Fix input/output selections on devices with discrete ANALOG/HDMI ports.

### PR DESCRIPTION
**Pull request by paulh-aja**
### Description

Two things fixed in this PR per request of AJA QA:
1.  Rename HDMI Monitor In/Out selections as well as Analog In/Out to to HDMI IN/OUT and ANALOG IN/OUT respectively, to match what is shown on those devices. (io4K+, IOXT, etc.)
3. Hide HDMI1 input selection on devices with a discrete HDMI IN port. This was essentially a duplicate menu entry.

### Motivation and Context

"HDMI Monitor" In and Out were not officially used terms in the AJA products. QA requested those list items be changed to HDMI IN/OUT.

Additionally, certain cards which have those discrete HDMI IN and OUT ports should not show the numbered HDMI input selections. Those are reserved for Kona HDMI, or any future cards that have multiple HDMI input or output ports.

### How Has This Been Tested?
Tested by developer on io4K+. QA will verify on all of the applicable cards/firmwares:
- io4k
- io4k (UFC)
- kona_hdmi
- io4k_plus
- ioxt
- lhi
- iox3

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by WizardCM — CHANGES_REQUESTED** [review]
These two changes should be separate commits. Additionally, the commit title is too long.

**Comment by paulh-aja** [comment]
> These two changes should be separate commits. Additionally, the commit title is too long.

Does it need to be two separate PRs or just two commits?

**Comment by WizardCM** [comment]
One PR is fine.

**Comment by paulh-aja** [comment]
I've broken the PR up into 2 separate commits and shortened the commit messages per the guidelines.

**Review by WizardCM — APPROVED** [review]
Much appreciated.

**Comment by paulh-aja** [comment]
I appreciate your time and consideration in reviewing these.

**Pull request merged**
