### PR TITLE
Fix audio buffering for devices like GV-USB2

### PR DESCRIPTION
**Pull request by jpark37**
This PR attempts to address buffering and audio loss problems with GV-USB2 in a robust way.

See https://obsproject.com/mantis/view.php?id=1269

### CODE REVIEW

**Comment by jpark37** [comment]
These changes seem to work in testing, but I'm starting this in draft status because I'm not confident I understand the audio system well enough.

**Comment by jpark37** [comment]
The change to make win-dshow decoupled is obviously limited to Windows, which is the only OS I personally care about. A similar change might be warranted for Mac/Linux video capture plugins.

Also, should decoupling be on a toggle? I noticed the DeckLink plugin enables it globally. Fewer options is more user-friendly, but maybe there's a device where this breaks things and coupling needs to be enabled.

**Comment by jpark37** [comment]
Jim says that we can't force decoupling in win-dshow, so I'll try to whitelist GV-USB2 specifically.

**Comment by jpark37** [comment]
Force-pushed the decouple only if whitelisted change. I'll mark the review ready after some more testing.

**Comment by jpark37** [comment]
Tested 8+ hours separately with GV-USB2 and SC-512N1-L/DVI. Audio was still active, and seemed to be sync'd to video. I saw a one-off message for 42ms of buffering added when long-testing GV-USB2, but the slow creep toward failure is probably resolved.

**Comment by DatXFire** [comment]
Tested this myself with my GV-USB2, 4 hour stream with no interruptions. Seems to work great!

**Comment by furious** [comment]
Thanks @jpark37, you are a legend :pray:

**Pull request merged**
