### PR TITLE
Media playback fixes

### LINKED ISSUE #3057: yuv444p16 video sources have bad chroma conversion
## Platform
Operating system and version: Arch Linux
OBS Studio version: 25.0.8
ffmpeg version n4.2.2

## Expected Behavior
Videos that decode to yuv444p16 or yuva444p16 (e.g. ProRes 4444 stuff) should be correctly converted to other pixel formats.

## Current Behavior
It seems every other chroma sample is dropped, and replaced with the previous one. This creates fairly nasty chroma artifacts.

Correct output on the top, incorrect output on the bottom:

image

## Steps to Reproduce

Try one of these files in a media source and observe the result vs. other media players:

* https://mrcn.st/t/chromasiting_prores.mov
* https://mrcn.st/t/chromasiting_v1.mov

You can try other pixel formats like this:

`ffmpeg -i chromasiting_prores.mov -pix_fmt yuv422p -c:v ffv1 chromasiting_v1_yuv422p.mov`

## Additional information
yuv444p works well, so it's something specific about the yuv444p16 variant.
yuv422p displays as intended too (half horizontal chroma res, looks better than the mangled output from yuv444p16), but crashes OBS after stopping and starting the source a few times, so it seems there's likely a memory corruption bug in there somewhere too.

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Avoid using FFmpeg swscale for YUV(A)444P to RGB conversion. Also switch SWS_FAST_BILINEAR filter to SWS_POINT.

### Motivation and Context
Fixes #3057

### How Has This Been Tested?
Videos from linked issue now display correctly.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
@jp9000 Do you remember why SWS_FAST_BILINEAR was selected?

**Comment by jpark37** [comment]
Jim says he doesn't remember, which is good enough for me.

**Comment by marcan** [comment]
Is swscale ever used to upscample chroma, even without scaling overall dimensions? e.g. a 4:2:0 format to a 4:4:4 format. If so, SWS_POINT might just do point upsampling of the chroma, which is not what you usually want. Might be worth testing at least bilinear with 4:2:0 sources and seeing whether it makes a difference.

**Comment by jpark37** [comment]
That's a good point, but we do have coverage for most YUV formats in our switch block, which will cause the conversion to go through our shaders, which do perform a form of bilinear upsampling on chroma. MSDN even demonstrates a bicubic upsampling of chroma, but I think what we have is fine.

OBS is also not always accurate when it comes to chroma siting either. I made some fixes in code I was optimizing anyway, but it's hard to justify spending time on otherwise. I don't think any Twitch streamer is losing money because their chroma info might be offset by half of a pixel.

**Comment by marcan** [comment]
I think this is mostly important when trying to align multiple images together to produce layouts without weird edges or artifacts. Especially with non-subsampled content (that's why I filed the original bug), but potentially also with. Offsets aren't a big deal on their own, but if you're trying to line up different sources that offset differently you get boundary artifacts.

Then again Apple also gets h.264 chroma siting wrong in Final Cut Pro X output (and probably others)... and I'm the kind of person who notices these things :)

**Pull request merged**
