### PR TITLE
libobs: Pulseaudio audio-monitoring list sinks

### PR DESCRIPTION
**Pull request by marcnnn**
List Pulse Sinks not Sink monitors in Settings DropDown

### Description
It is Listig sinks instead of sink monitors.
Now
After

Before
Before

### Motivation and Context
In the drop Down in the Audio Monitor Settings the Monitors of sinks where display instead of the sinks.
With string manipulation the monior was changed to the actual sink to connect audio.
So it was working but not easy to understand.
For me as a user.

### How Has This Been Tested?
I checked it on my ArchLinux Pulseaudio Jack setup.
I am able to Monitor audio form Media.

### Types of changes
No breaking changes.
Bug fix
I am not sure if there is more Documentation i need to chage?

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [?] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Would this not be a breaking change for existing setups? If a user previously set up a monitoring device then updated to this, would their monitoring device reset to default or update to the correct item?

**Comment by marcnnn** [comment]
You are right.
I addressed that better now.
image
Old config will work but you if you change some thing it will save in the new way.

**Comment by marcnnn** [comment]
Is something missing getting the fix into master?

**Comment by kkartaltepe** [comment]
This doesnt work on my machine. Loading an old configuration actually did work but trying to choose one of the new options didnt on one try and segfaulted on a 2nd try.

**Comment by WizardCM** [comment]
I can confirm this doesn't seem to work

```
nfo: pulse-am: Server name: 'pulseaudio 14.2'
error: pulse-am: An error occurred while getting the source info!
```

**Review by WizardCM — CHANGES_REQUESTED** [review]
Hi, just a reminder that I ran into an issue with this PR last time I tested it.

**Pull request closed without merging**
