### PR TITLE
Add support for custom file poll interval

### PR DESCRIPTION
**Pull request by gmjosack**
### Description
Adds a config option when using Read from file to choose a custom poll interval

##### Without Read From File
text

##### With Read From File
read-from-file

### Motivation and Context
A tool I use for tracking speedrun categories in a game has an option
to write it's state to a file but the Text source is very slow to update
to the point people think the tracker is slow when it is in fact the OBS
source.

### How Has This Been Tested?
I ran this change locally changing the option and inspected that OBS updated more or less quickly after editing my file. This was tested on a Windows 10 Desktop PC

### Types of changes
 - New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gmjosack** [comment]
Two open questions from me on how to complete this PR:
* What is the process for updating the i18n strings for other languages
* Are these settings documented somewhere? I'm not too familiar with the codebase.

**Comment by dodgepong** [comment]
This is probably the fifth or sixth time this feature has been PR'd. As with the previous times, rather than changing the poll interval, you should change the implementation to use an event-based system for detecting file changes based on operating system calls.

**Comment by gmjosack** [comment]
Apologies, I didn't see the previous PRs. I image you continue to get them because the 1 second poll is unsatisfactory to users of the Source. I only looked into adding this PR because multiple people using a tool I wrote complained about the latency.

While I agree an event/notify based approach would be better it's also a decent amount more work to make cross platform. Do you know if there is already a cross platform abstraction OBS uses for any other components that I could look to for reference?

I personally think 1 second is extremely conservative especially when it's also watching mtime on the file.

**Comment by gmjosack** [comment]
Some PRs found for context: https://github.com/obsproject/obs-studio/pull/1192 https://github.com/obsproject/obs-studio/pull/1566 https://github.com/obsproject/obs-studio/pull/3010 https://github.com/obsproject/obs-studio/issues/3012

I'm seeing that this source is Windows only so it would be fine to use windows only APIs for this?

**Comment by WizardCM** [comment]
Yes, the GDI+ text source is Windows only, whereas the Freetype text source is cross-platform.

**Pull request closed without merging**
