### PR TITLE
UI: Add per-scene volume

### PR DESCRIPTION
**Pull request by cg2121**
https://ideas.obsproject.com/posts/232/let-us-lock-source-audio-in-each-scene-independently

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Also resolves: https://obsproject.com/mantis/view.php?id=904

**Comment by WizardCM** [comment]
Right, after a session of experimentation, I have some feedback. Mostly on feedback to the user.

1. In the current PR state, the 'Global' toggle is available for Settings -> Audio sources, but it doesn't do anything. I recommend defaulting them to checked ✅ but disabled so the user cannot toggle them.
2. When the 'Global' toggle is clicked, the fader in the current scene continues to show the global fader value. Switching to another scene then back shows the correct current-scene value. I vote it updates immediately when the toggle is clicked to avoid user confusion.
3. In the mixer itself, there is no visual indicator that an audio source is global. A simple visual change for this could be a different colour of the fade bar and grip (currently blue and white respectively in the Dark theme)
4. I also personally think the global option should be accessible through the context menu for the specific source via the gear ⚙ button. This would mean one less click to reach the option. However, I can see the reasoning behind putting the option into Advanced Audio: you don't want users accidentally changing the setting.
5. For a new user, they may not exactly know what a "Global" checkbox does. I'd recommend some hover text with a brief summary of what will change when the user changes the option.


It also seems this PR breaks/removes the slider for audio balance in the advanced audio properties. The area is just blank.

**Comment by skeletonbow** [comment]
If Scene A contains a per-scene audio device and gets included multiple times in Scene B for producing special effects (kaleidoscope, ghost images, tiled grids, etc.), the per scene audio from scene A gets included multiple times in Scene B and an increase in volume is heard which often causes clipping.  There is only a single volume fader present so no way to mute the duplicate copies of the audio either.  Not sure if that is relevant to this particular PR, but WizardCM asked me to comment about it here.

Reproduction case:
1) Create scene with an image/video source, and one or more per-scene audio sources.
2) Create a second scene which includes 2 or more copies of the first scene.  4+ makes it really obvious.

The scene 1 audio will be very loud and clipping with no way to control it, even if you turn it down it is still distorted.  The multiple audio copies are not always in sync either depending on what the audio source is.  Browser source containing audio can be... weird.

**Comment by cg2121** [comment]
I have now added the ability to track the global audio channels. (Desktop, Mic/Aux).

@WizardCM I've implemented most of your suggestions except the context menu (I agree that users might accidentally click this) and the indicator showing whether the volume is global or not (trying to think of a better way of accomplishing this). The balance sliders are fine on my end.

@skeletonbow I haven't been able to reproduce your bug.

**Comment by cg2121** [comment]
@skeletonbow I can now reproduce your bug. I can make it also happen on OBS master, so it is not this PR that causing the issue.

**Comment by ntoff** [comment]
>the indicator showing whether the volume is global or not (trying to think of a better way of accomplishing this).

What about a divider in the mixer for global sources? Global mixer as a separate dock?

**Comment by WizardCM** [comment]
> > the indicator showing whether the volume is global or not (trying to think of a better way of accomplishing this).
> 
> What about a divider in the mixer for global sources? Global mixer as a separate dock?

I wouldn't put it in a separate dock, but putting global sources at the top of the list and then a separator could work really well.

**Comment by ntoff** [comment]
top or left please (for those of us who use vertical mixers), so the global source(s) is/are always the first in the list and don't get shoved around as the scenes change.

**Comment by cg2121** [comment]
I'm going to close this because it needs a better implementation, where there needs more backend control, so things like audio fades work between scenes.

**Pull request closed without merging**
