### PR TITLE
UI: Log available encoders on load

### PR DESCRIPTION
**Pull request by Penwy**
### Description

This logs all available audio and video encoders when launching

### Motivation and Context

It can often be challenging for support volunteers to remember which encoders are available on which hardware, especially with AMD.
This would greatly simplify the flow of some support interactions.

### How Has This Been Tested?

Ran obs, checked that available encoders were correctly listed and no memory leak happened.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please provide a sample log with this change applied for reference.

**Comment by Penwy** [comment]
[here](https://obsproject.com/logs/QVOoB3lIxRTleZAy)'s a sample.

**Comment by Penwy** [comment]
I'll wait for warchamp's review on it to make changes, but yeah I agree that rod's version is more readable, especially with the right tabulation to match.

I do similarly disagree about putting it to debugging, as the whole purpose is for ease of support, and asking an user to enable it is quite the same amount of work than asking for a screenshot of the encoders dropdown, if not more.

A solution to reduce verbosity could be to only list video encoders, since those are the one with the most variability, and most actual impact on support.

**Comment by WizardCM** [comment]
I vote this doesn't need to be hidden behind a verbose flag. It is useful for all known use cases for reading the log file.

**Comment by derrod** [comment]
This should probably not show deprecated/internal encoders, see the flags for those: https://github.com/obsproject/obs-studio/blob/01610d8c06edb08d0cc3155cb91b3e52e9a6473e/UI/window-basic-settings.hpp#L120-L121

**Review by Warchamp7 — APPROVED** [review]
Fine with adding this info, I don't think this needed a UX stamp.

Agree with Fenrir on fixing up the indentation. I defer to others if we want to explicitly separate video and audio encoders as Rodney suggested.

I don't think it's necessary to hide this behind verbose.

**Comment by Penwy** [comment]
Modified according to rod's suggestions.
[Here](https://obsproject.com/logs/Q5hDlrUZvYDEwJ60) is an example of a log with it.

**Pull request merged**
