### PR TITLE
[WIP] UI: Show a message in the Sources list to new users

### PR DESCRIPTION
**Pull request by WizardCM**
This adds a text label and background image if a user has launched OBS without any sources. The most common use case is when launching OBS Studio for the first time.

This makes use of a function introduced by #1344, CountVideoSources().

This is a first pass, mainly to get opinions and feedback (first C++ PR, yay!).

Known behaviour, on purpose:
* The message will remain if a new scene is created
* The message will appear if a new user closes OBS then reopens it without adding sources
* The message will disappear only if a source is added, or if the user switches to a scene collection that contains sources
* Themes without a background image defined will only show the text - though, this should be OK as Dark is default. All built-in themes contain an image of some kind.
* Users can "click through" the text label as if it was part of the background
* The text is part of a label, and therefore can be translated for every language. Currently, it is one label with 2 lines, but if needed I can change this.
* The image is fully controlled by the theme, and therefore can be customized - as can any styling of an empty sources list

Current bugs:
* The message will not re-appear when all sources have been deleted (as that event isn't tracked in window-basic-main) or if a user creates a new, empty scene collection
* Though text is centered, alignment isn't accurate due to the sources box initially being 100px wide, then after loading is complete, changes to 180px
* Resizing the source box (or any surrounding elements) will not adjust the size of the label, and therefore the text will not be centered properly

Current design concerns:
* Might move the initial label creation into OBS::Load directly rather than having it as part of the function
* The label is currently attached to the top of the sources list, and while this looks fine at default sizes (at least on Windows), it becomes.. disconnected from the image as it centered vertically. I might center it with an offset/margin from the center

Notes:
* Per @Warchamp7's suggestion, I will research ways to enable adding sources through **left** click in empty scenes. Currently only right click is supported.

Screenshots as of initial PR:

Dark: (what 99% of new users will see)

"Default" on Widows: (System-style, for any users who installed before Dark became default)

Acri: (I do need to adjust the height of the label a little more here)

Rachni:

To test this yourself:
* Run your local build once
* Close OBS
* Create a portable_mode.txt file in the relevant rundir
* Every time you want to test from scratch (reset layout and all settings), delete the config directory created by portable mode

### CODE REVIEW

**Comment by WizardCM** [comment]
@SuslikV I agree it shouldn't be, but as OBS doesn't have a concept of fallback styles, it's cleaner to style it in the code rather than every theme having to define it manually - being a QLabel it'd stick out as a sore thumb.

**Comment by SuslikV** [comment]
Also, users rarely read the messages, so the annoying remainder in the sources list will be skipped by major number of new users.

The default behavior of obs is to add 2 audio sources on first run (devices at Settings>Audio) and this feature used by users, so, "You don't have **any** sources..." is not correct.

And I think (obviously, the intention to keep the application from changes) that the feature not needed, there is one - warning message when you start the output, it already exist in obs.

**Comment by Heufneutje** [comment]
> And I think (obviously, the intention to keep the application from changes) that the feature not needed, there is one - warning message when you start the output, it already exist in obs.

I don't agree with this statement. There is a big difference between both features. The message you're talking about doesn't show up until after the user has already (presumably) set everything up and hits the stream/record button, while this feature uses a visual indication that immediately draws the user's attention to the source list, one of the most logical places to start when first starting up OBS.

**Comment by Heufneutje** [comment]
I'm not really sure what you're trying to tell me. Your original point was that this feature wasn't necessary because of the message box that shows up when hitting record/stream without any sources. But now you're telling me that this doesn't draw enough attention. I'm thoroughly confused.

**Comment by WizardCM** [comment]
@SuslikV Even with all the existing indicators (and the new dialog in v22) we still have multiple people **every day** join the support channel and ask "how to fix the black screen", because they're new and don't know they need to add a source.

To quote Jim from the development channel:

> Here is the equation of how to calculate my happiness for any given pull request, idea, or improvement:
> [how many users benefit] x
> [simplicity and cleanliness of code] x
> (1 + [how much it benefits new users])

This is exclusively designed to benefit new users, and it's only the first step. Much more is planned.


In relation to your comment on so much code to add a simple label, I originally tried to do it in OBSBasic.ui, which would have been much cleaner, but unfortunately that doesn't support floating labels, as far as I can tell.

This PR was my first time using C++ ever - I'm a JavaScript developer by trade - so any feedback is appreciated, and suggestions on how to use less code are always great (the less code the better!).

I agree that we should cut down on visual noise, and you're welcome to PR/suggest ways to do that, but making core OBS features more obvious to new users is a high priority too.

**Comment by SuslikV** [comment]
@Heufneutje I say that I don't like this option. And it looks like it will be implemented sooner or later. It should be a way better if this not just a knot on the box.

@WizardCM 
It doesn't matter who you are (@jp9000  makes mistakes too, and more often in simple things) - I just don't like the:
`sourcesLabelInitial->setStyleSheet("background: transparent;");`
string from your PR, that's all. I don't care about the logic, code time etc. When you said about clearness, I said that is not clear... - You may not take it into account at all (each programmer has its own style). For example, you add background to one widget in one place (.qss) and modifying transparency of the other widget in other place (.cpp), right where you modifying properties of the object - it is acceptable, but for me - it is strange behavior.

**Comment by Warchamp7** [comment]
@WizardCM You probably don't need to touch the height on Acri, just set the padding to 0 for that element

**Comment by jp9000** [comment]
Hm, the text doesn't seem to center.  I feel like it should center right above the icons.  Other than that I love it.

Additionally, the text should probably just say "Right-click here to add a source" or something.

I think you should consider doing this differently however.  Instead of making it a child of the sources widget, I think you should probably hide the sources list, then insert the label and whatever other widget you need above the sources list in to the layout, then delete them when no longer needed and unhide the sources widget.  Might be a bit complicated, but I think that should solve the problems you seem to be having with how the text doesn't center.  This would allow you to control the dimensions of the label and/or bitmap widget (if you choose to use one) as well.  What do you think?

I definitely feel this is useful to have for the brand new users who are just getting started with the program.  A great little improvement to user experience.

**Comment by WizardCM** [comment]
My only concern with hiding the main sources widget for a new user, is that the moment they use it for the first time the look/feel/behaviour would change slightly. They already barely know what's up. I'll experiment with the idea and see how it feels.

**Comment by WizardCM** [comment]
I had a tiny bit of a chance to play with the existing implementation this weekend, and couldn't figure out how to make the QLabel resize itself when the user resizes the window, so the text still doesn't look centered. If anyone could help on this aspect, that'd be great.

I still plan on experimenting with Jim's idea but just haven't had a lot of time to do something this big from scratch.

**Comment by WizardCM** [comment]
Closed in favour of #1766

**Pull request closed without merging**
