### PR TITLE
rtmp-services: Add CamSoft

### PR DESCRIPTION
**Pull request by wolf247**
rtmp-services: Add CamSoft

### Description
I created an entry for CamSoft to be added to the Services list, this is for our live streaming server to be used by our clients who are going to use OBS Studio.

### Motivation and Context
To be able to include CamSoft to the Service list.

### How Has This Been Tested?
Server is working properly when tested in custom settings.

### Types of changes

New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by ElectronicWar** [comment]
Please follow the naming convention for Pull Requests in the form of `rtmp-services: Add <name>`.
It is also required to update the version in package.json

There is also a small formatting issue in your description.

**Comment by wolf247** [comment]
Changes done.  Please check if I get it right, sorry I am new on Github.

**Comment by ElectronicWar** [comment]
services.json and package.json must be updated in the same pull request. Please close #2014 in favor of this one here.

**Comment by wolf247** [comment]
#2014 closed.

**Comment by Fenrirthviti** [comment]
Please update your commit titles and squash the 3 commits you have currently. You updated the PR title, but not the commits which is the important part. The single commit with title `rtmp-services: Add CamSoft` should be sufficient.

Once the commit titles are updated and squashed, this should be good to go.

**Comment by wolf247** [comment]
Did I got it right?

**Comment by dodgepong** [comment]
Not quite. Commits should be squashed such that there is only 1 commit in this pull request with your two changes.

**Comment by dodgepong** [comment]
Also it looks like the current changeset in this has 0 actual changes. The PR diff is empty.

**Comment by dodgepong** [comment]
Also, what exactly is CamSoft? I can't find any information about it.

**Comment by wolf247** [comment]
Can I just delete this PR and start over again?  I am really confused 
since I am new to Git, much better for me to start from a clean PR instead.

**Comment by wolf247** [comment]
The name of the developer group for Chathostess sites.

**Comment by dodgepong** [comment]
Sure, you can do that.

**Comment by Fenrirthviti** [comment]
Is this service public, or only for internal development? Can you elaborate what exactly it's used for?

**Comment by wolf247** [comment]
It is public and being used by our cam sites models for live streaming.

**Pull request closed without merging**
