### PR TITLE
obs-ffmpeg: Use event to cancel media source reconnect sleep (first dropped frames fix)

### LINKED ISSUE #7521: Loading any SRT stream via Media Source causes rendering freeze
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/fT1FBuieL943kCZW

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

SRT streams via Media Source should be loaded asynchronously in the background.

### Current Behavior

Loading any SRT stream via Media Source causes temporary freeze. UI thread is not affected.

### Steps to Reproduce

1. Create a Media Source
2. Input any srt:// URL (valid or invalid)
3. Observe the preview (and recording) freezing for a temporary amount of time

### Anything else we should know?

live video demonstration: https://www.youtube.com/watch?v=wnEnUQtoG-Y

my best guess is that SRT initialization logic is accidentally running on the main graphics thread

### PR DESCRIPTION
**Pull request by tt2468**
### Description
Fixes an issue where update/destroy of a media source during reconnect would block the parent thread until the next reconnect attempt. This would result in significant quantities of dropped frames, delayed OBS shutdown, or frozen UI during this period.

Fixes #7521

### Motivation and Context
We should avoid blocking the graphics thread for meaningless tasks. Blocking the UI thread also is not very desirable.

### How Has This Been Tested?
- Create media source
- Specify invalid network-based playback URL (like `rtmp://stream.global.irl.run/ingest/invalidkey`)
- Click Ok
- Immediately open properties dialog of media source
- Click Ok
- UI will freeze until the reconnect delay is over, and the graphics thread will too

With this PR, it no longer happens.

With time measurement attached to `pthread_join()` call in `ffmpeg_source_update()` callback:
- Current master: `info: time taken to join: 5733ms`
- This PR: `info: time taken to join: 0ms`

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
There's a potential race condition that this could exacerbate, `ffmpeg_source_tick` creates the reconnect thread and then sets `s->reconnect_thread_valid = true`. When the reconnect thread finishes, it will set `reconnect_thread_valid` to `false` but there's a risk it will be set back to `true` by `ffmpeg_source_tick` depending how quickly the thread completes.

**Comment by notr1ch** [comment]
https://github.com/obsproject/obs-studio/blob/3c584279a8d21e6823a14bd4618f5e055705132f/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L395-L405

Shouldn't the rest of the code also be in the first branch?

**Comment by tt2468** [comment]
> https://github.com/obsproject/obs-studio/blob/3c584279a8d21e6823a14bd4618f5e055705132f/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L395-L405
> 
> Shouldn't the rest of the code also be in the first branch?

Could you elaborate?

**Comment by notr1ch** [comment]
Nevermind I misunderstood the purpose of this variable, it's just to avoid filling the log with reconnect attempts.

**Review by notr1ch — APPROVED** [review]
I think this is good to go now.

**Pull request merged**
