### PR TITLE
win-dshow: fix H264 to mjpeg issue

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by wanhongqing123** [comment]
win-dshow

**Comment by dodgepong** [comment]
Please fill out the rest of the PR template. What does this change do? Why was this change necessary? How have you tested this change?

**Comment by wanhongqing123** [comment]
if you use custom format , when you set the video format H264 then change video format mjpg,the OnEncodeVideo Function will not work because the codec id not changed.

**Comment by Fenrirthviti** [comment]
Please update the original PR template to explain this change. It should be fully completed before submitting a PR.

Your code is also failing clang-format checks. Make sure that you format the code with clang-format and update the commit where appropriate. I would also recommend that you move the changes to a branch rather than master.

Additionally, your commit message does not follow our [contribution guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) as the first word should be capitalized.

**Pull request merged**
