### PR TITLE
Revert "plugins/win-dshow: Add CUDA decoder"

### LINKED ISSUE #10906: Could not dynamically load CUDA (nvcuda.dll). On a AMD build.
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

30.2.0-beta4

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/FRHAZKTvIxR3LroE

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Should notice that Nvidia is not installed and not load CUDA/nvcuda.dll. Or see that AMD is installed and not load CUDA.

### Current Behavior

Will infinitely try to load nvcuda.dll and flood the log file, making the log file size large.

### Steps to Reproduce

1. Open OBS
2. Look at log file
3. Done
...

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

This reverts commit ce4c99be4e52950a4bd49eb68d99ccdda2e87f96 (partially reverts #10607).

This was causing infinitely looping log errors in systems with no CUDA-capable hardware when hardware decoding was enabled on video capture devices with custom config enabled.

### Motivation and Context

Fixes #10906

### How Has This Been Tested?

I haven't tested this yet, but I am fairly confident this is the cause of the log spam in #10906.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
To be clear, the infinite loop still happens, it just has no output. But that's something that will need to be fixed separately.

**Comment by RytoEX** [comment]
> To be clear, the infinite loop still happens, it just has no output. But that's something that will need to be fixed separately.

Fair point.

**Comment by RytoEX** [comment]
Going to merge this for now to stabilize 30.2. We can re-explore adding CUDA decoding back to win-dshow devices and preventing the non-logged infinite loop another time.

**Comment by RytoEX** [comment]
Going to merge this for now to stabilize 30.2. We can re-explore adding CUDA decoding back to win-dshow devices and preventing the non-logged infinite loop another time.

**Pull request merged**
