### PR TITLE
CI: Improve formatcode.sh efficiency

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description
Batch files into clang-format to prevent needless processes. Now its
twice as fast in real time and uses 4x less resources. The old
implementation is also slower (but pretty close to) running a single
invocation of clang-format on all files.

before
time ./formatcode.sh
real	0m3.860s
user	0m20.975s
sys	0m6.694s

after
time ./formatcode.sh
real	0m1.486s
user	0m5.426s
sys	0m0.203s

(single threaded performance, all files on commandline)
real	0m3.511s
user	0m3.420s
sys	0m0.036s

### Motivation and Context
The old code was probably significantly slower on less beefy machines. This brings resource usage inline with running single threaded but actually runs faster with more cores. 100 was chosen arbitrarily but since we have about 800 files to format it should make good use of up to 8 cores. Going as low as 15 is also pretty reasonable with a bit more overhead but in either case we only get about twice as fast as single threaded so I chose to reduce overhead by going with a larger batch.

### How Has This Been Tested?
I ran it.

### Types of changes
Performance Enhancement for CI

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
> 100 was chosen arbitrarily but since we have about 800 files to format it should make good use of up to 8 cores

Just figured I'd point out that the CI images only have 2 vCPUs per the current documentation from Azure and GitHub Actions.

**Comment by kkartaltepe** [comment]
> Just figured I'd point out that the CI images only have 2 vCPUs per the current documentation from Azure and GitHub Actions.

Right but contributors may run this themselves so letting them use more cores (even though it doesnt perform better on my machine) seems fine. On CI i see linux format check going from 6-7s to 3s, mac seems mostly unaffected by this change.

**Comment by ioangogo** [comment]
I do have a question, does it need to be run on the whole project or could it be possible to only run it on the files that changed with the commit?

**Comment by kkartaltepe** [comment]
Its fast enough for CI (and my personal formatting honestly). The majority of the CI time is spent preparing the environment anyway. And in case of weird PRs i think its preferable to check everything instead of a potentially fragile git magic command.

That said something like this git magic command should be fine for most PRs
```
git diff $(git merge-base HEAD master) --name-only | grep -E '\.(h|c|hpp|cpp|m|mm)$' | xargs clang-format -i -style=file  -fallback-style=none
```
Or you can look up clang-format-diff.py which also works well.

**Pull request merged**
