### PR TITLE
obs-filters: Add Garbage matte

### PR DESCRIPTION
**Pull request by alicemargatroid**
### Description
This provides an easy way to block out hard to color/chroma areas of video.

### Motivation and Context
This is fairly self explanatory, so I'll just provide some screenshots.

#### Circle Matte ####
circle_matte

#### Ellipse Matte ####
ellipse_matte

#### Rectangle Matte ####
rectangle_matte

### How Has This Been Tested?
Tests on Windows 10 and OSX

### Types of changes
This is a new feature.

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by mufunyo** [comment]
What about custom polygons? I think Premiere has something like 8 control points that you can drag around the scene.

**Comment by alicemargatroid** [comment]
@munfunyo Does OBS have a better way to specify points? Perhaps a screen based picker?
Are we allowed to write filters in C++?

Honestly, I couldn't get trapezoids to function properly, so I just implemented what was easy and provided value.

**Comment by Xaymar** [comment]
Interaction is limited to the interact capability, which is only provided for actual sources, so the control points being draggable will require an actual OBS Studio change to work.

**Comment by alicemargatroid** [comment]
Then custom control points, especially 8 of them, sounds like a nightmare.

**Comment by Xaymar** [comment]
They are, I have the code for Stream Effects somewhere. The best I could do was make the control point selection a slider and show/hide properties for each control point. But it's pretty hacky at best.

**Comment by alicemargatroid** [comment]
Probably a good idea to just support these to start.

**Comment by kkartaltepe** [comment]
Why do you feel this is necessary when alpha masks are already available and can be arbitrary masks? I feel this is substantially less useful than the available masking filter.

**Comment by mufunyo** [comment]
Good point @kkartaltepe, with the super basic shapes available in the current PR, even just spending 1 minute doodling an external matte in MS Paint and saving it as a bmp file will probably yield a more useful garbage matte.

**Comment by alicemargatroid** [comment]
@kkartaltepe @mufunyo I strongly disagree, especially if I could get trapazoids working. By all means, an image mask is great, but why should anyone need to open an image editor to do something so basic? While streaming, no one wants to stop their stream to open up an image editor, carefully carve out an image, save it properly, then go to the filter and add it in.

Often a few minutes before streaming, it turns out a green screen isn't working perfectly and some simple rectangle or trapezoidal masks are just the thing.

Why do you feel that such a feature isn't necessary, given it's low cost?

**Comment by dodgepong** [comment]
I'm of two minds on this.

On one hand, I don't see this as a feature that will be leveraged in the middle of a stream, but rather something people would set up beforehand. In that case, while it may be easier for simple shapes, I don't think the argument that it's less clumsy to use in the middle of a stream necessarily holds up in practice.

On the other hand, one of the biggest downsides of the image mask filter is that, for the mask to look correct, the image that is loaded has to match the aspect ratio of the source that the mask is being applied to. If this filter doesn't care about that, then this filter would have that advantage.

I think the other matter to consider is that this adds a new filter that has _neighboring_ functionality with the image mask filter, which makes it feel like there's overlap and thus could introduce user confusion over different types of mask filters. What about changing this PR to modify the Image Mask filter, and renaming it to just "Mask"? Make "Image" one of the options in the dropdown alongside the different shapes? Just an idea, not sure how feasible it is.

**Comment by alicemargatroid** [comment]
@dodgepong I don't think anyone would be confused by the presence of two different filters, and I've often had to change my mattes in the middle of the stream. I may be unusual in this, but it's something I've seen on other streams too.

**Comment by kkartaltepe** [comment]
>  I don't think anyone would be confused by the presence of two different filters

You severely underestimate the average user's technical prowess. Remember you are proficient enough to navigate the code base and create filters and PRs in OBS. You are not the average user.

As to the usability issue, I agree with you that using the existing mask filter could be improved in several ways. Perhaps the most obvious after looking at this PR, and something that might be coloring your perspective, is that your filter is "interactive" while the existing image mask requires you to reload it every time you change the image. This is fairly easily fixable by making the image mask reload on changes like image/text sources. This way users can simply doodle in MS paint and watch the changes appear in obs.

Most users are content creators and will be much more comfortable with this workflow than trying to guess pixels and shapes etc. Especially as these users are likely to be more proficient in A/V tooling like image editors given they know what a "image mask" or "matte" even is.

While this feature may seem simple to you, there is a cost to maintaining and supporting every single line of code in OBS. You may ask why we push back, but again what users are looking for this functionality except for you personally? I have never once heard a user ask for the functionality to enter a precise pixel coordinate of a trapezoid to block some portion of their source, but ive heard plenty of people ask for image mattes and masks. And any user who is trying to form a custom mask is typically more than happy to create it in their image editor of choice.

**Comment by alicemargatroid** [comment]
@kkartaltepe I don't disagree that I am an expert user, but I do programming work for a living and work in UX from time to time; I don't think this will be a problem based on my experience. By all means, we can do a user study if you prefer. Perfectly happy to change the name as well, or change the functionality as much as asked. _I just want to improve OBS_.

I don't dispute your experience, but please don't also dispute mine. The reason I even decided to make such a feature is because people have requested such features. By all means, I don't have a thousand people study to confirm it, but an informal study of around 10-20 people showed that these were lacking features (along with many others), so I decided to try implementing them. 

I've had plenty of people complain about the time it takes to set up simple mattes to cover their green screen errors; no one wants to have to render an image matte 5 minutes before they are about to go live. Certainly, no one is "happy" about it; while an image matte is much more flexible, it takes time that you don't always have. It's a better solution, but having both is better than just one.

By all means, it's not my project. But the idea that such a simple and obviously useful tool would be called a "cost" is somewhat silly. This commit clocks in at 350 lines, nearly all of which is boilerplate; the filter itself is simple enough to implement in a single afternoon.

More than that, OBS _is very clearly lacking in basic filter features_, and while this is not the _best_ solution, it's a standard one that would also be much improved once some way to select areas on the screen is implemented. Even if you guys are only going to support the OpenFX standard (your API looks broadly similar to it and it also doesn't support pixel selection), this is still an essential part of compositing that can be improved upon further with time.

**Comment by kkartaltepe** [comment]
> I don't dispute your experience, but please don't also dispute mine.

Im sorry if that was your interpretation. I hope its clear that I agree with you that the use case you present is troublesome in OBS as is.

**Comment by mufunyo** [comment]
Closing this until a more intuitive way to interact with shapes or control points in the filter UI is added to OBS.

**Pull request closed without merging**
