### PR TITLE
Update Elbrus (e2k) support

### PR DESCRIPTION
**Pull request by makise-homura**
### Description

Added support for building on typical OSes used in Elbrus (E2K): OS Elbrus and Alt Linux, both for legacy build and modern build.

### Motivation and Context

Should solve #10575 to the extend of making OBS buildable on E2K again.

### How Has This Been Tested?

Tested on:

1. Ubuntu: Ubuntu 22.04.3 LTS (Jammy Jellyfish), gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
* Modern build preset/options: `--preset ubuntu -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DENABLE_RNNOISE=OFF`
* Legacy build CMake options: `-DENABLE_AJA=OFF -DENABLE_NATIVE_NVENC=OFF -DENABLE_VLC=ON -DENABLE_WAYLAND=ON -DENABLE_WEBRTC=OFF -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DENABLE_RNNOISE=OFF -DCEF_ROOT_DIR=...`
* Result: 41 warnings on legacy build; 16 warnings on modern build.

2. OS Elbrus: OS Elbrus-Linux 7.2, lcc:1.26.22:Jan-10-2024:e2k-v4-linux
* Modern build preset/options: ` --preset e2k-osl7.2`
* Legacy build CMake options: `-DENABLE_WAYLAND=OFF -DENABLE_PIPEWIRE=OFF -DENABLE_VST=OFF -DENABLE_QSV11=OFF -DENABLE_BROWSER=OFF -DENABLE_WEBSOCKET=OFF -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DENABLE_NATIVE_NVENC=OFF -DENABLE_AJA=OFF -DENABLE_WEBRTC=OFF -DENABLE_DECKLINK=OFF -DENABLE_UI=OFF`
* Result: 7 warnings on legacy build; 4 warnings on modern build.

3. Alt Linux: ALT Server 10.2 (Mendelevium), lcc:1.25.23:Apr--7-2022:e2k-v4-linux
* Modern build preset/options: ` --preset e2k-alt10`
* Legacy build CMake options: `-DENABLE_QSV11=OFF -DENABLE_BROWSER=OFF -DENABLE_WEBSOCKET=OFF -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DENABLE_AJA=OFF -DENABLE_WEBRTC=OFF -DENABLE_UI=OFF`
* Result: 7 warnings (except mentioned below) on legacy build; 4 warnings on modern build.
* With legacy build, there are a lot of warnings `lcc: Command-line warning #1819: "..." was specified as both a system and non-system include directory -- the non-system entry will be ignored`; this is typical behavior of slightly outdated versions of LCC. No such warnings on modern build, though.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Thank you for the time and effort put in to this, but we are opting to decline support for e2k going forward.

If there is any code currently that implies e2k support, feel free to open a new PR (or modify this one to remove it and I can reopen).

**Comment by makise-homura** [comment]
@Fenrirthviti But what's the reason to prefer removing it instead of fixing?
Also, what do you mean to "remove" support? Do you wish that your code should be forcibly unbuildable on E2K in any situation, or you just leave it to be supported with patches? (e.g. is it ok to continue supporting this branch in my fork to save time porting OBS for E2K owners?)

**Comment by derrod** [comment]
You're of course welcome to maintain patches on your fork and/or provide builds for people. It's just that we do not want to maintain this upstream due to the irrelevance of the platform comapred to x86/ARM (even PPC to some extent).

We do not intend to make changes that would prevent building it, we just don't want to maintain cmake and/or code changes to support it.

**Comment by RytoEX** [comment]
> But what's the reason to prefer removing it instead of fixing?

See the comment from submitter of Issue #10575:
> It's better to delete this code, you won't be able to maintain it. And those distributions that work with this architecture will patch it themselves.

> Also, what do you mean to "remove" support? Do you wish that your code should be forcibly unbuildable on E2K in any situation, or you just leave it to be supported with patches? (e.g. is it ok to continue supporting this branch in my fork to save time porting OBS for E2K owners?)

We have no issue with people maintaining their own patches or packages for this architecture. We are just no longer convinced that it's worth it for us to maintain compatibility ourselves. In any case, we'll update SIMDe in due time as a separate matter, which seems to be the bulk of the changes here.

**Pull request closed without merging**
