### PR TITLE
libobs: Add transition duration functions

### PR DESCRIPTION
**Pull request by Andersama**
Adds functions to return the duration of a transition.

### CODE REVIEW

**Comment by CDshenwa** [comment]
Thanks

**Comment by DDRBoxman** [comment]
What's the intended use for these?

**Comment by Andersama** [comment]
For transitions where the percentage of a transition having been passed isn't an ideal metric to work with.

**Comment by dodgepong** [comment]
Can you give an example of what you mean? I'm still not quite sure I understand the use case. What is the problem that this PR solves, and how does it solve that problem?

**Pull request closed without merging**
