### PR TITLE
rtmp-services: Add LiveStreamerCafe

### PR DESCRIPTION
**Pull request by Tophicles**
### Description

Add Live Streamer Cafe as an RTMP service

### Motivation and Context

Ease of use for our streamers to have built in support

### How Has This Been Tested?

Tested local build successfully

### Types of changes

Tweak

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please use the present tense "Add" in the commit message subject, per our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/e9a401d89859a10d125d8aee3ef23f4719164e4d/CONTRIBUTING.rst#commit-guidelines).

**Comment by Tophicles** [comment]
> Please use the present tense "Add" in the commit message subject, per our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/e9a401d89859a10d125d8aee3ef23f4719164e4d/CONTRIBUTING.rst#commit-guidelines).

Apologies - totally a newb to the GIT scene. 
I *think* I changed it properly now :)

**Comment by RytoEX** [comment]
You changed the PR title, but not the commit message.

**Comment by Tophicles** [comment]
> Also, apologies for missing in the first review, but please also increment the version number in package.json, per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).

Oh man, changed.
I'm sure you're screen capturing this and laughing! Haha.
So sorry for the confusion.

**Comment by RytoEX** [comment]
> > Also, apologies for missing in the first review, but please also increment the version number in package.json, per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).
> 
> Oh man, changed. I'm sure you're screen capturing this and laughing! Haha. So sorry for the confusion.

Not at all. My goal is simply to get the PR into a mergeable state.

**Comment by Tophicles** [comment]
> > > Also, apologies for missing in the first review, but please also increment the version number in package.json, per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).
> > 
> > 
> > Oh man, changed. I'm sure you're screen capturing this and laughing! Haha. So sorry for the confusion.
> 
> Not at all. My goal is simply to get the PR into a mergeable state.

I totally get it... I was kidding.
Thanks for your patience :)
I hope we're good now!

**Review by Fenrirthviti — APPROVED** [review]

**Pull request merged**
