### PR TITLE
Virtual Camera: Custom placeholder.png - Advanced Settings and mac-virtualcam

### PR DESCRIPTION
**Pull request by pedanticdan**
### Description
This change adds the ability (on MacOS) to replace the default placeholder.png file with a user-specified file through an Advance Setting item. A new "Virtual Cam" section is added to the Advanced Settings tab for the user to specify the custom png file to use when the Virtual Cam is stopped. Also, a backup directory can be specified to saving a backup copy of the current placeholder.png file. When the user clicks on "Start Virtual Camera" and OBS checks if it is necessary to install placeholder.png, the code in this change also checks for a specified PNG file. If a backup directory is configured, the current placeholder.png file is backup to that directory. Then, the configured custom PNG file is used to replace placeholder.png.
A screen shot fo the new setting is attached.
VirtualCam Advanced Setting

### Motivation and Context
When the Virtual Cam features was first introduced, my first reaction was, "Cool! How do I replace the image that is used when Virtual Cam is stopped?" I checked the forums and found that others had the same question.  This change adds the ability to use a custom PNG file by just changing a setting, than looking for the diretory location of the existing file and replacing it manually every time OBS is upgraded.

I did not find an open issue on this subject, nor did I find a suggestion on the ideas page, but I added one under a different account here: https://ideas.obsproject.com/posts/1325/add-setting-to-replace-placeholder-png

### How Has This Been Tested?
I tested by installing on a machine with no prior OBS version installed, and installing it over 26.1.2. I tested with Zoom and Skype:
1) Start Virtual Camera with new settings left blank
2) Start Virtual Camera with new PNG specified, backup dir blank
3) Start Virtual Camera with back dir specified, new PNG blank
4) Start Virtual Camera new settings both blank (after previously not being blank)
5) Start Virtual Camera when no setting has changed (verified current png file not backed up or replaced needlessly).

I have tested this change only on BigSur on a 215 MacBook Pro and a 2018 MacBook.
This change only adds a setting, plus some code when the Virtual Camera is started on a Mac. There is not interaction with any other part of OBS.

### Types of changes
- New feature

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [X] The code has been tested.
- [?] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

I think my commit message are properly formatted, but are not squashed.

### CODE REVIEW

**Comment by notr1ch** [comment]
I think the backup path is a bit confusing and modifying existing installed files seems unnecessary. Why not have the vcam plug-in use the custom placeholder if it's specified and fall back to default if it's not?

**Comment by Fenrirthviti** [comment]
Is this really necessary as an option? What workflow is changing this file so often that an option in the UI is required for it? I would much rather prefer a wiki article explaining the location of the file and how to just replace the .png manually is made instead. This feels completely unnecessary to me for a very niche use case that is already possible without it.

**Comment by pedanticdan** [comment]
> I think the backup path is a bit confusing and modifying existing installed files seems unnecessary. Why not have the vcam plug-in use the custom placeholder if it's specified and fall back to default if it's not?

I see what you mean. Now that I'm more familiar with the code, I should be able to do it that way.

**Comment by pedanticdan** [comment]
@Fenrirthviti , part of why I did this is because it's irritating to have to track down the placeholder.png file and replace it every time theres a new code drop. Wy NOT make it easier?

**Comment by pedanticdan** [comment]
After looking deeper into the mac-virtualcam code in light of @notr1ch's comment, I've concluded that this modification was done with the wrong approach. I'm closing this pull request and starting over.

**Pull request closed without merging**
