### PR TITLE
CI: Update to clang-format 16

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update to clang-format 16. I used clang-format 16.0.5 for the formatting because that's what VS 2022 17.7 ships.

This does not cover submodules (obs-browser, libdshowcapture, obs-websocket). Those can be done in tandem with this or separately.

### Motivation and Context

Want to stop pinning to clang-format 13.

### How Has This Been Tested?

Ran the formatter. I didn't do build tests, but CI will.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
There are an number of currently commented out options like https://github.com/obsproject/obs-studio/blob/master/.clang-format#L147-L149 that we could probably enable as part of an update.

The namespace comments could be turned off via `FixNamespaceComments` (added in clang-format 5!) but I'd almost prefer explicitly turning that on to see if it will then also add those in C++ code (right now it's just ObjC++).

**Comment by RytoEX** [comment]
> There are an number of currently commented out options like https://github.com/obsproject/obs-studio/blob/master/.clang-format#L147-L149 that we could probably enable as part of an update.
> 
> The namespace comments could be turned off via `FixNamespaceComments` (added in clang-format 5!) but I'd almost prefer explicitly turning that on to see if it will then also add those in C++ code (right now it's just ObjC++).

That last highlighted line has no version marker. Should we uncomment it or ignore it?

**Comment by derrod** [comment]
Seems like the line immediately afterwards sets it to a different value that's not valid based on the documentation (https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakbeforeconceptdeclarations), maybe the values changed with newer versions? Would be a question for @PatTheMav

**Comment by RytoEX** [comment]
I've pushed the enablement of `FixNamespaceComments` for C++ as a fixup commit for now (to be squashed, if acceptable). I think I'll defer any ObjC adjustments to a separate PR to keep this scope down and also because clang-format on my Windows machine does not run with the ObjC options enabled. Specifically, I get this error:
```
error: unknown key 'QualifierOrder'
```

**Comment by RytoEX** [comment]
> I've pushed the enablement of `FixNamespaceComments` for C++ as a fixup commit for now (to be squashed, if acceptable). I think I'll defer any ObjC adjustments to a separate PR to keep this scope down and also because clang-format on my Windows machine does not run with the ObjC options enabled. Specifically, I get this error:
> 
> ```
> error: unknown key 'QualifierOrder'
> ```

Figured this out with off-thread help from @tytan652 . We would need to change `QualifierAlignment` to `Custom`. Will still defer the ObjC changes to later, but this PR at least unblocks those changes.

**Comment by PatTheMav** [comment]
> > I've pushed the enablement of `FixNamespaceComments` for C++ as a fixup commit for now (to be squashed, if acceptable). I think I'll defer any ObjC adjustments to a separate PR to keep this scope down and also because clang-format on my Windows machine does not run with the ObjC options enabled. Specifically, I get this error:
> > ```
> > error: unknown key 'QualifierOrder'
> > ```
> 
> Figured this out with off-thread help from @tytan652 . We would need to change `QualifierAlignment` to `Custom`. Will still defer the ObjC changes to later, but this PR at least unblocks those changes.

I suggest removing `QualifierOrder` entirely as their docs themselves say that `clang-format` does not have the necessary semantics to make this a non-breaking formatting change.

**Comment by PatTheMav** [comment]
> Seems like the line immediately afterwards sets it to a different value that's not valid based on the documentation (https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakbeforeconceptdeclarations), maybe the values changed with newer versions? Would be a question for @PatTheMav
> 
> Edit: Indeed seems that it was changed from a bool to having multiple options somewhere between 14 and 16: https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html

Yeah I think I commented out the variant that was _compatible_ with 16 only because I used 16.0.6 as the baseline and then commented out stuff not supported by 13 or used the old value type supported by that specific version.

**Comment by RytoEX** [comment]
Approved off-thread. We'll handle submodules separately.

**Pull request merged**
