### PR TITLE
image-source: Correctly assign to variable next_hotkey instead of prev_hotkey

### PR DESCRIPTION
**Pull request by tuduweb**
### Description

correctly variable next_hotkey instead of prev_hotkey
this variable should be `ss->next_hotkey`

https://github.com/obsproject/obs-studio/blob/8ef134be7955d3436282c85ff7e806bab2e6f28b/plugins/image-source/obs-slideshow.c#L657-L664

### Motivation and Context

correctly the variable which assigned to `NextSlide` hotkey

### How Has This Been Tested?

Hasn't, is just a variable name change.

### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
Commit prefix should be `image-source:`. Rest is probably good to merge.

**Comment by tuduweb** [comment]
> Commit prefix should be `image-source:`. Rest is probably good to merge.



> Commit prefix should be `image-source:`. Rest is probably good to merge.

thanks for the correction.

**Comment by gxalpha** [comment]
@tuduweb I'm terribly sorry I didn't notice the second part, which just says `Correctly next instead of prev`, could you perhaps change it to something with a verb (for example `Correctly assign hotkey to next instead of prev`)?

Again, really sorry for not spotting it the first time.

**Comment by tuduweb** [comment]
> @tuduweb I'm terribly sorry I didn't notice the second part, which just says `Correctly next instead of prev`, could you perhaps change it to something with a verb (for example `Correctly assign hotkey to next instead of prev`)?
> 
> Again, really sorry for not spotting it the first time.

It's OK. I update this commit just now.
I will pay more attention next time.
thx again~ have a nice day.

**Pull request merged**
