### PR TITLE
UI: Add "Interact" button on the source list item

### PR DESCRIPTION
**Pull request by furious**
### Description

This adds a new button (cursor icon) on the sources list to bring the interaction window quickier than using the context menu. Also middle-click on the source item will trigger it.
Clicking the cursor icon will open the interact window

### Motivation and Context

Browser source is used a lot in online speedruns marathons/races/randomizers, they usually put Twitch embeds or randomizer trackers and interact with those sources a lot, because it's simplier. That's why I've made that

### How Has This Been Tested?

Yes, tested on Windows 7 and 10, everything working fine.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
You have changed the PR title, but not the commit.

**Comment by Hoishin** [comment]
+1 for this feature. It is great enhancement for those who use browser sources and need to interact with it. Even if it's designed so "you should not be interacting with the browser source", in real world you have to interact sometimes, and sometimes have to be done quickly.
And the fact that this doesn't affect other sources there isn't much downside.

**Comment by Heufneutje** [comment]
> And the fact that this doesn't affect other sources there isn't much downside.

This doesn't seem correct to me seeing as it adds an icon to the sources list that's not used by any other source.

**Comment by dunqi** [comment]
What about just the Option to Open the Interaction-Window with a Hotkey?

**Comment by ImportTaste** [comment]
My only criticism is that it could fool some people into thinking that's their cursor. Maybe make it a bullseye instead? ◎

**Comment by Warchamp7** [comment]
Browser Source Interact is ultimately an unsupported feature right now. If it works, it works and that's great. If it doesn't, nothing is really going to be done to fix that.

I share Fenrir's sentiment that we should not be making what is effectively a hidden and unsupported feature more accessible, as it will lead to increased usage and visibility of something we don't really want people using anyway

**Comment by dodgepong** [comment]
I wouldn't go so far to say it's unsupported, but I would say that the feature is added as a concession to the fact that sometimes it's necessary to interact with the browser to get something to appear correct. However, the intention is that you should largely use the browser as a rendering surface for read-only purposes, and if you need to change it, you should change it using some other external means other than browser interaction directly in OBS.

**Comment by jp9000** [comment]
I understand it would be nice to have these extra conveniences, but I would prefer something like a keyboard combo shortcut which would accomplish the same thing without adding extra icon clutter to the UI.

**Comment by dunqi** [comment]
yeah, please make a keyboard combo

**Comment by ImportTaste** [comment]
@jp9000 Should a new issue be opened for the keyboard shortcut then?

**Pull request closed without merging**
