### PR TITLE
* Added OnlyFans streaming support.

### PR DESCRIPTION
**Pull request by vitalybulganin**
### Description

Added a new streaming support, which is called OnlyFans into rtmp-services plugin.
This extension sends a GET request to server for getting a list of supported servers. Also, I added a simple algorithms which helps to select an ingest for streaming content, which is optimal for a streamer location. This will be work, if streamer chooses Auto in servers list (Settings -> Stream).
The main idea for selection algorithm is to get RTT for each ingests and select with minimal value. Calculating RTT is based on checking HTTP connection time to test URL, which provides with supported servers list.

### Motivation and Context

This solution was high recommended, because it helps to improve streaming quality. Our tests showed a perfect result in production area.

### How Has This Been Tested?

I tested this solution in two OS's. The first OS was Ubuntu 18.04 and Ubuntu 20.04 and the second one was Windows 10. Also, our QA tested this plugin on their environments.

### Types of changes

- New feature (non-breaking change which adds functionality)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Reminder to follow the [commit guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidelines)

**Comment by notr1ch** [comment]
Are you affiliated with Onlyfans? This is a lot of code to add for a single service and I would like to make sure it is properly maintained should it be merged. I am not too keen on the idea of HTTP pinging all servers, services should ideally provide an endpoint that returns the best route as determined by BGP or similar, or use geo DNS or other methods for an "Auto" server. There's a few code issues too but I don't have time for a full review at the moment.

**Comment by vitalybulganin** [comment]
> Are you affiliated with Onlyfans? This is a lot of code to add for a single service and I would like to make sure it is properly maintained should it be merged. I am not too keen on the idea of HTTP pinging all servers, services should ideally provide an endpoint that returns the best route as determined by BGP or similar, or use geo DNS or other methods for an "Auto" server. There's a few code issues too but I don't have time for a full review at the moment.

Yes, I'm a stuff of this company. It looks like a lot of code, but it's simple. I thought about calculating algorithm RTT or use to another method to get optimal ingest, and this solution is the best way to get it one. 
I really hope, you will find time to review my solution. 

I am looking forward to hearing from you,

**Comment by derrod** [comment]
Due to the complexity and maintenance cost we will not merge this PR. Feel free to submit your service as a regular RTMP service per our [service submission guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).

**Pull request closed without merging**
