### PR TITLE
mac-avcapture: Add additional capture presets

### PR DESCRIPTION
**Pull request by vangdfang**
### Description

This adds additional capture presets, including 3840x2160 and 1920x1080, in addition to the preset "High." There's no reason these can't be supported, they just haven't been added.

### Motivation and Context

Newer capture hardware is capable of supporting these capture modes, so there's no reason that I can see to not include them.

### How Has This Been Tested?

Verified the capture is successful on a MacBook Pro running macOS Big Sur Public Beta (11.2 - 20D5029f) when paired with an Elgato HD60 S+ interface over USB.  This interface could only capture 4K at 30fps, which I verified using a 4K/30Hz source. 1080p@60Hz capture was also verified.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
These aren't added till 10.15, will need a version check.

**Comment by jp9000** [comment]
Actually I might have prematurely merged this one. @DDRBoxman informed me that this needs to be a runtime check, not a compile time check, and he's correct. These resolutions will get compiled into our binaries, and they will show on 10.13/10.14, but will not work because they aren't available on those operating system versions. So this needs to be changed to a runtime version check.

**Comment by jp9000** [comment]
I'm going to revert this for now -- after I revert, please make a PR that does a version check at runtime instead.

**Comment by vangdfang** [comment]
Sure thing.

**Pull request merged**
