### PR TITLE
Add support for YUV alpha formats

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Enable OBS to convert YUV alpha formats to RGBA on the GPU to free up CPU.

### Motivation and Context
The GPU is much faster at processing images than the CPU.

### How Has This Been Tested?
Breakpoint inspection to verify old path (swscale MMX) has been replaced by new code paths.

Tested dancer1.webm and soccer1.webm from Google blog on Windows and Mac using Media Source. Converted those yuva420p videos to yuva422p and yuva444p using FFmpeg. AYUV tested with custom plugin since FFmpeg does not support.

Performance was measured using a custom plugin source at 1080p.

I40A -> RGBA, 1080p, CPU
swscale (MMX), Intel i7-6700: 1910 us -> 0 us

GPU measurements used Intel GPA with SetStablePowerState.

I40A -> RGBA, 1080p, GPU
Intel HD Graphics 530: 0 us -> 677 us
NVIDIA RTX 2080 Ti: 0 us -> 43 us

### Types of changes
- New feature (non-breaking change which adds functionality)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jp9000** [comment]
Where on earth did you encounter YUVA?

**Comment by jpark37** [comment]
People in the Discord were talking about alpha videos and I found this: https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video

Which points to two videos that can be downloaded here: https://simpl.info/videoalpha/

Actually, I see VLC's fourcc list calls the 4:2:0 variant "I40A", so I'll update this in a bit.

**Comment by jpark37** [comment]
Rename complete.

**Comment by mufunyo** [comment]
I do know about AYUV, which is 4:4:4:4, but other than its use in subpictures (pre-rendered subtitles) I haven't encountered it in the wild.

**Comment by jpark37** [comment]
Reading up a bit more, it seems like WebM never officially added alpha support. It just got hacked in, and is usable by FFmpeg and Chrome (and Adobe After Effects?).

These are from the VLC list. "I42A" and "YUVA" should be straightforward to add if desired although I haven't tried to create videos using those formats to know if they work yet.

B(VLC_CODEC_YUVA, "Planar YUV 4:4:4 Y:U:V:A"), A("YUVA"),
B(VLC_CODEC_YUV420A, "Planar YUV 4:2:0 Y:U:V:A"), A("I40A"),
B(VLC_CODEC_YUV422A, "Planar YUV 4:2:2 Y:U:V:A"), A("I42A"),

**Comment by mufunyo** [comment]
For reference, AYUV is documented here (it's a packed/interleaved format): https://docs.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering

**Comment by jpark37** [comment]
FFmpeg does not appear to support 8-bit AYUV judging from the header and this wiki page: https://en.wikipedia.org/wiki/FFmpeg#cite_ref-55. I wouldn't mind adding it, but I don't have a device that outputs that format; it would be custom plugin tested only.

**Comment by jpark37** [comment]
Ok, support for yuva420p/yuva422p/yuva444p and AYUV has been added and tested.

**Comment by jp9000** [comment]
Oh, so this is an optimization for webms with alpha?

**Comment by jpark37** [comment]
It was originally when I just had yuva420p. FFmpeg doesn't want to produce WebM files with yuva422p or yuva444p, so I created some FFV1 MKVs to test those. I checked AYUV with my format testing plugin.

**Pull request merged**
