### PR TITLE
cmake: Enable full optimizations for RelWithDebInfo MSVC builds

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Windows builds are not compiled with the best possible optimizations due to poor CMake defaults. Let's fix that!

This PR adds the following compiler flags for MSVC RelWithDebInfo builds:
`/Ob2` (automatic inline expansion)

And linker flags:
`/OPT:ICF` (identical COMDAT folding)

Ref: https://gitlab.kitware.com/cmake/cmake/-/issues/20812

### Motivation and Context
Gotta go fast!

### How Has This Been Tested?
Built OBS. It still ran.

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
Neato. Any chance you've been able to do any profiling to see what kind of difference we might be able to expect?

**Comment by jp9000** [comment]
`/O2` should already do `/Ob2` by default. So they were overriding it with `/Ob1`? I wonder why on earth they would do that.

**Comment by jpark37** [comment]
Judging from this isn't `/Gy` implied by `/O2`?
`string(APPEND CMAKE_${lang}_FLAGS_RELWITHDEBINFO_INIT "${_MD} /Zi /O2 /Ob1 /DNDEBUG"`

MSDN says `/O2` = `/Og /Oi /Ot /Oy /Ob2 /GF /Gy`
https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?view=msvc-160

**Comment by notr1ch** [comment]
Looks like it, I've pushed an update removing `/Gy`

**Comment by notr1ch** [comment]
On a related note, [IPO / LTCG]( https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-160) made a large difference in terms of code generation, however some of our dep .lib files are not compatible with it. Would be nice to see if we can get IPO-enabled builds in the future.

**Comment by jpark37** [comment]
You may also want to consider /fp:fast, which is good enough for games (on by default on Xbox).

Maybe a separate PR, but we should probably compile -O3 for non-Windows builds.

I am somewhat doubtful overall about how much performance this saves given that I assume most heavy lifting is done in third-party libraries like Qt/FFmpeg, but better is better. At least make sure performance doesn't mysteriously regress though, e.g. more aggressive inlining could be harmful if MSVC is bad at it. And maybe I'm speaking to the obvious, but each option should probably be checked against perf regression individually and then altogether.

**Comment by notr1ch** [comment]
`/Ob2` did cause some small increase in binary sizes, which is expected with inlining. Given that this is the default in `/O2` I would hope performance doesn't suffer. When combined with partial IPO, the binary sizes actually got smaller in some cases vs `/Ob1` as many accessor function calls could be entirely eliminated. It'd be worth checking out how all our deps are built too and make sure we aren't missing any easy gains from compiler options there.

**Comment by jp9000** [comment]
I think the deps are all built with their respective release defaults that they set on their own. Nothing particularly special or out of the ordinary.

**Pull request merged**
