### PR TITLE
obs-qsv: Fixing QSV failed initialization

### PR DESCRIPTION
**Pull request by brittneysclark**
QSV is not initializing with DCH graphics drivers under certain conditions when
the graphics adapter 0 is not set to iGFX due to outdated MSDK
dispatcher. Updating MSDK APIs to 1.27 with new dispatcher to enable
proper initialization of QSV encoder.

### CODE REVIEW

**Comment by SuslikV** [comment]
I think it is wise to link it here:
https://obsproject.com/mantis/view.php?id=1372

**Comment by Fenrirthviti** [comment]
This is probably not related. The issue in that Mantis report is with other changes that enabled b-frame support and changed default settings. This PR does not fix that crash, and does not seem related.

That said, if there is any input that can be provided on the Intel side on what the issue in that Mantis report is, we would be happy for it.

**Comment by SuslikV** [comment]
It includes all changes that was reverted by:
https://github.com/obsproject/obs-studio/commit/4c7860056e5b4473932aef0200b61538de024fba

Also, the report:
https://obsproject.com/forum/threads/quicksync-not-working-properly.101227/#post-395651
says that the change itself not very helpful. So, despite mix (unfortunately) of the issues and solutions it is all related - if this merged, the mentioned above changes of the code changes will be reinstated.

**Comment by dlunch** [comment]
Applying this PR fixes quick sync for my pc (skylake igpu)

**Comment by SuslikV** [comment]
@dlunch In which way it fixes?

**Comment by dlunch** [comment]
After installing dch driver, qsv encoding fails with following log: 
```
17:03:25.977: [qsv encoder: 'msdk_impl'] Unsupported configurations, parameters, or features (MFX_ERR_UNSUPPORTED)
17:03:25.990: [qsv encoder: 'simple_h264_recording'] qsv failed to load
```
But after applying this PR manually, qsv encoding works fine with dch driver.

**Comment by dlunch** [comment]
also, intel says updating dispatcher solves the problem.

https://software.intel.com/en-us/forums/intel-media-sdk/topic/800921

**Comment by brittneysclark** [comment]
Updating the MSDK dispatcher should solve the issue. However, I found few other clean up items that need to be addressed with this PR, so closing for now. Please wait for updates soon.

**Pull request closed without merging**
