### PR TITLE
Add Mac WindowCapture.ShowCursor

### PR DESCRIPTION
**Pull request by kilinbox**
### Description
Add cursor display function to window capture.

### Motivation and Context
Cursor display in window capture is available in Windows but not in Mac, and even in Mac, cursor display is available in Display Capture but not in window capture. So, we will implement the cursor display in window capture.

### How Has This Been Tested?
macOS 12.0.1 Montere, Mac mini(M1, 2020)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
You need to squash your commits into a single commit. Also, the only locale file you need to update is English, as the rest is handled by CrowdIn.

**Comment by kilinbox** [comment]
Sorry. Should I cancel this request?

**Comment by dodgepong** [comment]
You don't need to close the PR. Just revert the non-English locale changes, squash the commits, and force-push your branch.

**Comment by dodgepong** [comment]
Actually, it looks like this PR is from your `master` branch on your fork. It would be better to close this PR and make a new PR from a branch on your fork. You can squash into one commit at the same time.

**Pull request closed without merging**
