### PR TITLE
rtmp-services: Update Taryana | Apachat service

### PR DESCRIPTION
**Pull request by Don-Stive**
rtmp-services: Update Taryana | Apachat service

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please properly fill out the PR template.

**Comment by Don-Stive** [comment]
> 
> 
> Please properly fill out the PR template.

What is wrong mate ?

**Comment by Fenrirthviti** [comment]
> What is wrong mate ?

You deleted the PR template, meaning that there is no confirmation that you followed our PR process. For example, your code is on the master branch which is not recommended. In the future, when submitting code to another project's repository, it is a good idea to read the contribution guidelines (which are linked in the template in our case). I understand that the template might seem unnecessary for a small change, but deleting the template sends the message that following our process is not worth your time, which is a bad message to send.

**Comment by Don-Stive** [comment]
> 
> 
> > What is wrong mate ?
> 
> You deleted the PR template, meaning that there is no confirmation that you followed our PR process. For example, your code is on the master branch which is not recommended. In the future, when submitting code to another project's repository, it is a good idea to read the contribution guidelines (which are linked in the template in our case). I understand that the template might seem unnecessary for a small change, but deleting the template sends the message that following our process is not worth your time, which is a bad message to send.

alright mate, i will do it. please close this thread and don't accept it, thanks for your comment

**Pull request closed without merging**
