### PR TITLE
win-dshow: Add installer scripts for manual Virtual Cam registration

### PR DESCRIPTION
**Pull request by Fenrirthviti**
### Description
This adds two batch scripts to install and uninstall the virtual cam
devices for installations where the installer could not be useed.
Most commonly, this is for portable installations or those who prefer
the .zip file.

### Motivation and Context
We had several people ask how to register virtual camera on portable
installations with the RC for v26.

### How Has This Been Tested?
Tested the script logic for all scenarios on the installer:

- No cam registered
- Only 32bit registered
- Only 64bit registered
- Both already registered
- All the above in the root of the obs-studio folder
- All the above in the win-dshow plugin folder

Script functioned as expected. Tested uninstaller, devices were unregistered.
### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
I would suggesting using the OBS CLSID directly instead of searching the registry to avoid issues when forks inevitably use the same DLL name.

**Comment by Fenrirthviti** [comment]
Thanks, I wasn't sure if that would be safe to use or not, so I went for the most-specific search path otherwise. I'll update to use the full ID.

**Comment by notr1ch** [comment]
I've also suggested to Jim that we set the CLSID via a cmake variable to avoid a hardcoded one in the source (that will also likely get used by a fork at some point and cause some kind of terrible conflicts). So be aware that the CLSID may change and the script may need updating if that goes ahead.

**Comment by SuslikV** [comment]
Hmmm, the `net session >nul 2>&1` check may fail (as it does for me) in Safe Mode etc., related links:
https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights#comment29802533_11995662
https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights#comment44292875_11995662

Possible workaround is `openfiles.exe 1>nul 2>&1`, link:
https://stackoverflow.com/a/24270170

**Pull request merged**
