### PR TITLE
rtmp-services: Add Steam

### PR DESCRIPTION
**Pull request by ElectronicWar**
The "common" value can be argued about.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Adding this for reference: https://partner.steamgames.com/doc/store/broadcast/setting_up#3

Also, since this is still in beta, and opt-in only, it should definitely not be marked as a common service right off the bat.

**Comment by ElectronicWar** [comment]
`common` has been set to `false`

**Comment by wallrik** [comment]
Regarding the server locations: ISO 3166 specifies Sweden as `SE`, not `SW`. (Yes, Valve got it wrong) 😎

**Comment by ElectronicWar** [comment]
Server names are implemented as provided from the official sources to stay on-par with provided documentation

**Comment by wallrik** [comment]
Should be corrected now. [[1]](https://user-images.githubusercontent.com/10890923/59216684-64a29580-8bbc-11e9-92e1-98f940fc5694.png)

**Comment by ElectronicWar** [comment]
Server name for Sweden has been updated to match new Valve name again.

**Pull request merged**
