### PR TITLE
CI: Use Windows obs-deps release

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Use the Windows obs-deps release on CI instead of the current dependencies2019.zip.

### Motivation and Context

Let's us distribute test builds via CI and eventually use obs-deps for all CI builds.

### How Has This Been Tested?

While I have been testing these locally, we'd like to make testing more easily available to a wider audience.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Verified that this launches, so it's ready for greater testing.

* [Windows x64](https://github.com/obsproject/obs-studio/suites/4348595472/artifacts/114099793)
* [Windows x86](https://github.com/obsproject/obs-studio/suites/4348595472/artifacts/114099792)

**Comment by jp9000** [comment]
Huh, how'd this get a conflict so fast

**Comment by jp9000** [comment]
Seems that there's a conflict that might need to be resolved first

**Comment by RytoEX** [comment]
> Seems that there's a conflict that might need to be resolved first

Fixed the conflict, and also changed the deps for the 32-bit build, which I had somehow missed previously.

**Comment by RytoEX** [comment]
It's worth noting that this is just the original obs-deps Windows release.  We will have to update again once we introduce more obs-deps changes, but I'm in favor of merging this as-is now to put the changes into the slightly wider audience that runs nightlies versus those who test PRs.

**Pull request merged**
