### PR TITLE
UI: Hotkey improvements

### PR DESCRIPTION
**Pull request by cg2121**
Before:
Screenshot from 2019-04-23 01-29-27

After:
Screenshot from 2019-04-23 01-28-29

### CODE REVIEW

**Comment by Son9o** [comment]
Ouchie, truncation hurts to look you can't be serious, hope there is a full hint/tool-tip text at least?

**Comment by cg2121** [comment]
I have now added tool tips showing the full name.

**Comment by WizardCM** [comment]
I second the notion that the truncation is unnecessary. At the very least, I'd raise the limit from 40 to 60 or 70. The text box could safely have a minimum width of 130px as most hotkeys are pretty short, which'd provide more space for the labels. Could even lock the width of the + and - buttons to half of what they are now.

**Comment by SuslikV** [comment]
TRUNCATE_TEXT_LENGTH is too low but the option itself may become useful in case of drag-n-dropped sources (sometimes files can has long names).

**Comment by cg2121** [comment]
I have now increased to truncated text length to 50 instead of 40. I have also now changed the buttons to use icons, so they don't take up as much space.

Screenshot from 2019-04-29 12-59-01

**Comment by WizardCM** [comment]
I think all the icons except "Revert" look good, as I had to look up what it was before to know what it means. I'm not sure what icon would be good instead.

And if they're going to be icons, 50 is still too short. The width of that text box can safely be half the size that it is in that screenshot. I previously suggested "60 or 70", I'd suggest 70 or 80 now, *however* I'd recommend naming a source in ALL CAPS as those characters are wider and give a better indication. I assume if two sources both have truncated names and one is visually wider than the other, they'll both be truncated at different points?

**Comment by cg2121** [comment]
OK, I've now changed the length to 80 characters.

**Comment by cg2121** [comment]
I've now combined this with #1859

**Pull request closed without merging**
