### PR TITLE
mac-videotoolbox: Set default keyframe interval to 2 seconds, Remove CRF 0 second keyint override

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

0 seconds means "auto" according to the [documentation](https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_maxkeyframeinterval), but this appears
to be broken in many configurations (more than just CRF mode on Apple
Silicon). With some encoders it means that the encoder sets a keyframes
every 31st frame, other times it just doesn't set any keyframes at all
after the first one, only rarely does the "auto" interval actually
appear to work.
Lets just set the default to 2 seconds and be happy. In theory this is
the maximum keyframe interval and encoders are allowed to set more if
they so wish, but they never appear to do so.

Also removes the 0 second keyint override in CRF mode.
The 0 second default interval no longer happens per default, if
someone explicitly sets the interval to 0 seconds ("auto"), we should
allow them to do that.

This change will effect existing configurations, but probably for the better.

### Motivation and Context

Videos without keyframes, from various encoders (Intel, Apple Silicon) and in various rate control configurations, still come up in support way too often.
This change should mostly eliminate them.

### How Has This Been Tested?

macOS 14
Tested that in Advanced the default is now 2 seconds; and in Simple the encoder always has 2 seconds.
Verified that recordings come out with a 2 second keyframe interval via ffprobe.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
IIRC the setting actually sets keyframes according to actual scene changes (detected with some heuristics), so setting it to an automatic value will not do what people expect it to for the most part.

I think we reported this to Apple but I'm not aware if there will be any meaningful change to this behaviour on macOS 14.

**Review by derrod — COMMENTED** [review]
On other encoders we use a nonzero keyframe default so that I'm not opposed to, but I'm wondering if this could break things for some users using CRF mode already and now would no longer have the safety blanket of a forced minimum keyframe interval.

**Comment by gxalpha** [comment]
I think the impact would be pretty low? Seeing as we don't store defaults anyone who was set at the default 0/auto seconds is now at 2, it'd only be people who purposefully put it back to 0 probably?

**Comment by basisbit** [comment]
+1 for changing the `default` keyframe setting value from 0 to 2. This change will improve simplicity of using OBS for many common use cases, thus also reducing support overhead, and it is one less setting which probably every video live streamer has to change every time they pick an encoder in the OBS video settings.

**Comment by derrod** [comment]
In that case it's probably fine? Not a fan of even allowing the broken combination of a keyframe interval of 0 and CRF though.

**Comment by gxalpha** [comment]
In that case I’d argue we should remove 0 completely. The point of this PR is that it’s *not* just 0 and CRF, but that the broken behavior as happened in various configurations with any rate control method.

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
