### PR TITLE
CI: Update macOS CLI build script

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Fixes bugs and remedies usability issues discovered by @WizardCM:

* Adds support for `BUILD_DIR` env variable to change the build directory used by the script (which is a new `build` directory under the checkout directory by default)
* Adds support for the `-d` switch to skip dependency checks and downloads (use at your own peril)
* Adds check for macOS versions earlier than 10.15 (with support for v11.0 coming up) to install and use `curl` via Homebrew
* Adds progress bar to `curl` downloads for increased transparency for when the script might seem otherwise to be "stuck"
* Remove step to install `packagesbuild` which is not needed for OBS builds
* Fixes capitalisation error in bundling step that could occur on case-sensitive file systems
* Adds additional step output for fetching OBS git tags

Fixes https://github.com/obsproject/obs-studio/issues/3244.

### Motivation and Context
As described in https://github.com/obsproject/obs-studio/issues/3244 older versions of `curl` shipped up to macOS 10.14 Mojave exited with a non-zero return code when trying to continue an already-completed file. This was fixed in `curl` sometime in 2017, but only macOS 10.15 Catalina ships with a recent-enough version that contains this fix. Using `curl` via Homebrew allows a "clean" approach to still continue downloads, but also fail on actual errors.

All other changes are for convenience, transparency and broader system configuration support.

### How Has This Been Tested?
* Tested locally

@WizardCM pls run some checks yourself if possible.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Tested in my 10.14 VM, both with and without `-b -s`. Works perfectly.

**Comment by PatTheMav** [comment]
@WizardCM did you run it multiple times? The `curl` bug only happens when dependencies were fully downloaded once before.

**Comment by WizardCM** [comment]
@PatTheMav Yep, ran it multiple times just in case.

**Comment by PatTheMav** [comment]
Nice, might not fix everything, but seems a good iteration on the script then. 👍🏻

**Pull request merged**
