### PR TITLE
UI/installer: Silently install Visual C++ Redistributables

### PR DESCRIPTION
**Pull request by WizardCM**
### Description

During the installation process, silently installs the Visual C++ redistributables if they are not already installed.

Requires redistributables in the install build directory.

**Important note:** this implementation would require the installer itself ship with the Visual C++ redistributable EXE. If it's decided that we'd rather not ship these and instead download them from the web behind the scenes (or with user confirmation), this can be achieved using the [Inetc plugin](https://nsis.sourceforge.io/Inetc_plug-in) for NSIS and the following change:

```diff
	vs2019Missing_64:
-		File VC_redist.x64.exe
+		inetc::get /SILENT https://cdn-fastly.obsproject.com/downloads/VC_redist.x64.exe "$PLUGINSDIR\VC_redist.x64.exe" /END
		ExecWait '"$PLUGINSDIR\VC_redist.x64.exe" /quiet /norestart'
```

The downside of requiring a download is that it turns this into an online installer, which may not be wanted.

### Motivation and Context

This solves two issues:
- failed installation when launching the OBS installer from the command line (especially with the `/S` flag).
- user confusion during installation. this comes up very often in support channels - users see the dialog asking them to install the redistributables and have no idea what to do

### How Has This Been Tested?

1. Download the redistributables manually from [here](https://obsproject.com/visual-studio-2019-runtimes) and place them in `UI/installer/`
2. Build the installer using NSIS
3. Run the installer on a fresh installation of Windows - this is best done in Windows Sandbox
4. Notice that the installation succeeds and OBS launches without issue

### Types of changes
 - New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
> users see the dialog asking them to install the redistributables and have no idea what to do

Classic

**Comment by tommyvct** [comment]
Maybe I can do something like this on ARM64 Windows

**Comment by dodgepong** [comment]
So it seems pretty unambiguous that [we can't distribute the redists ourselves](https://www.gnu.org/licenses/gpl-faq.html#WindowsRuntimeAndGPL). The part I'm uncertain of is whether or not the installer going out to download the redists counts as aggregate distribution the same way as shipping the redists with the app itself. It seems like splitting hairs in a meaningless way, but I'm not a lawyer.

**Comment by tommyvct** [comment]
Sometimes, if not most of the time, you can't just prevent people from skipping what you wrote on the dialog. 

From the HCI standpoint, one way of doing it is to pop the browser directly, without showing a dialog, to download the runtime directly from Microsoft and install it (direct link to `vcredist.exe` so that user have lesser chance of downloading the wrong thing or getting confused), instead of letting our installer download it. 

Legal wise, I don't see there's any problem with this way. We are not distributing it and it would be insane if we still have legal issue.

Here's some reference:
https://devblogs.microsoft.com/oldnewthing/20030901-00/?p=42723

**Comment by dodgepong** [comment]
The goal is to create an installer that requires absolutely zero interaction and zero additional UI. They should be able to run the installer with `/S`, walk away, and when the come back, OBS is installed and working. I don't think a browser pop-up would be acceptable in this case.

**Comment by jp9000** [comment]
Could you change this so it includes the redist in the installer depending on the build options? Rather than download separately.

**Comment by dodgepong** [comment]
After doing some research, I think the concerns about shipping the redists is overly paranoid. Several other well-known GPL applications (Blender, Audacity, Krita) are doing it and no one seems to have any issue. It's pretty silly anyway, honestly.

**Comment by Fenrirthviti** [comment]
As a final question, do we make this step silent for everyone installing, or still provide the prompt when not launched with /S? I'm in favor of just doing it, because users don't typically care, but some might disagree with installing a system-wide dependency without at least prompting the user first.

**Comment by dodgepong** [comment]
I say we try to detect if they are already installed, and install them if they are not.

**Comment by tommyvct** [comment]
The user should be informed on what's going to be installed, including the VC++ runtime. It can be done right before the actual installation,  show another licence of VC++ redistributable after the LGPLv2 licence, or show the VC++ in the component chooser in NSIS; the user can choose to not install VC++, then we should warn the user that the program will not ba able to run without it.

Or we can use the way I said above. Not a good solution but a safe one.

As @dodgepong said, we can also follow how other GPL projects dealing with this situation. If they are safe, then we are safe too.

Then in the case of people questioning why VC++ is installed "without their permission" we can bring this up and show them they did agreed to install VC++ during the installation.

**Comment by WizardCM** [comment]
> I say we try to detect if they are already installed, and install them if they are not.

This is what this PR does already, for reference.

I'm going to make one definite change, which is to get it to also install the 32bit redist in 64bit mode, as it is sometimes required.

Final question from me is whether we want a UI screen notifying the user that we're about to install the redistributables. This can be either a page or dialog in non-silent mode to notify the user that they are required. However, I personally don't think it's necessary as it's very common for apps to silently install dependencies anyway.

**Comment by Fenrirthviti** [comment]
Let's go with no then. Simpler the better.

**Pull request merged**
