### PR TITLE
Add planar 4:2:2 video support; Use FFmpeg MJPEG decoder instead of DirectShow

### PR DESCRIPTION
**Pull request by jpark37**
The former change supports the latter. Better CPU usage, and lower latency on my webcam.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Is this only in the cpu decoding case? Are dshow filters hw accelerated on other platforms/formats where this might cause a serious regression?

**Comment by jpark37** [comment]
Both DirectShow (before) and FFmpeg (after) were using CPU for MJPEG decompression when I tried on my PC. There shouldn't be a risk to the handling of other video formats, or non-Windows operating systems if the code works as designed.

**Comment by jpark37** [comment]
This change is smaller than the description may suggest. There is a filter that comes with DirectShow called "MJPEG Decompressor Filter," which OBS uses to auto-translate to RGB. I am swapping out just that piece with FFmpeg, which is already integrated into the win-dshow plugin to handle H264 decoding. Everything else about DirectShow usage is the way it was before.

**Comment by kkartaltepe** [comment]
Sorry by platforms i meant hardware not OS

**Comment by jpark37** [comment]
I see MJPEG support for VAAPI and NVDEC in the FFmpeg codebase. My guess is that it's not automatic opt-in since I have a recent NVIDIA card as my primary adapter, but I don't know for sure if that's the case on all OS/GPU combinations.

**Pull request merged**
