### PR TITLE
Add CALM_DEPRECATION cmake option and fix some warnings

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Contains a rework of #8113

Add an option `CALM_DEPRECATION` to enable `-Wno-error=deprecated-declarations` for Linux users that might use bleeding-edge dependencies compared to obs-deps.

Fix a few other warning/errors.

### Motivation and Context

Improve #6759 and fix warnings/errors.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Changes themselves look correct - can you educate me how a developer might end up in a situation necessitating this?

**Comment by tytan652** [comment]
On Linux (non-Flatpak), we could end up with a new FFmpeg (Python …) version which add can add deprecations.

This option enable the use to allows those deprecations.

**Comment by jp9000** [comment]
Confirmed working, thank you very much

**Comment by jp9000** [comment]
@PatTheMav to be more specific, I asked tytan to add something like this because I'm building locally with a newer version of ffmpeg and am getting unexpected deprecation warnings. This just makes it more convenient to bypass the warning if by chance you just so happen to use a newer version of some library that just so happens to deprecate functions we're currently using.

**Pull request merged**
