### PR TITLE
[WIP, TESTING NEEDED] Bump Flatpak KDE Platform Ver to 6.7

### PR DESCRIPTION
**Pull request by sudopluto**
### Description

Bumps the KDE Platform Version from 6.6 to 6.7, since 6.6 is marked as EOL.

### Motivation and Context

Moves the flatpak off of an EOL runtime onto a currently maintained runtime.

### How Has This Been Tested?

TODO, will build flatpak locally and validate changes when I get home.

### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
There were some regressions with 6.7 which is why we held off. We'll update Qt for Flatpak together with all other platforms once it's viable (possibly straight to 6.8, who knows).

**Comment by sudopluto** [comment]
@derrod can you link me to the discussions of qt 6.7 / qt 6.8 & the observed regressions? i'd like to do my homework : ) thanks!

**Comment by sudopluto** [comment]
https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/1bf9bc50163ae70cc4ed3459ee3509a5c57497da

kde runtime is updated to 6.8.1, which fixes the bugs that caused the rollback to qt 6.6

**Comment by derrod** [comment]
Yeah but it introduced new bugs like https://github.com/obsproject/obs-studio/issues/11649

**Pull request closed without merging**
