### PR TITLE
UI: Fix Chinese font on Windows

### PR DESCRIPTION
**Pull request by Aira-Sakuranomiya**
### Description

Add Microsoft YaHei (Microsoft YaHei UI) to font-family
Before
After

### Motivation and Context

Default Chinese font on Windows Vista+ should not be the old SimSun, it should be Microsoft YaHei.

### How Has This Been Tested?

Replace the qss and verified it was fixed.

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Does Microsoft YaHei UI contain latin glyphs? Because the way CSS works, on a system without Arial installed (as obscure as that might be), people would get YaHei instead of the default shell dialog font, which would definitely be seen as a "bug" by those users.

**Comment by Aira-Sakuranomiya** [comment]
> Does Microsoft YaHei UI contain latin glyphs? Because the way CSS works, on a system without Arial installed (as obscure as that might be), people would get YaHei instead of the default shell dialog font, which would definitely be seen as a "bug" by those users.



> Does Microsoft YaHei UI contain latin glyphs? Because the way CSS works, on a system without Arial installed (as obscure as that might be), people would get YaHei instead of the default shell dialog font, which would definitely be seen as a "bug" by those users.

yes it does
https://docs.microsoft.com/en-ca/typography/font-list/microsoft-yahei

**Comment by Aira-Sakuranomiya** [comment]
> Does Microsoft YaHei UI contain latin glyphs? Because the way CSS works, on a system without Arial installed (as obscure as that might be), people would get YaHei instead of the default shell dialog font, which would definitely be seen as a "bug" by those users.

yes it does
https://docs.microsoft.com/en-ca/typography/font-list/microsoft-yahei

**Comment by TianQiBuTian** [comment]
Can also add to other themes that have not been added.

**Comment by Aira-Sakuranomiya** [comment]
> Can also add to other themes that have not been added.

added👌

**Comment by Fenrirthviti** [comment]
Is this a locale issue that should really be upstreamed as a bug to Qt? Why is the default not being selected properly? Surely there must be a reason.

I'm not entirely opposed to this change if it is a real issue, but I feel this might have unintended consequences as a manually defined font for non-Chinese locales, and would like to understand why it's choosing a legacy font in the first place. Do we know if this currently affects all users with a Chinese locale setting, or if it might something environment specific?

**Comment by Aira-Sakuranomiya** [comment]
new pull request that put Microsoft YaHei after sans-serif
#7390

**Pull request closed without merging**
