### PR TITLE
OBS official website cannot be opened. What's the matter?

### PR DESCRIPTION
**Pull request by tea1111980**
Excuse me, OBS official website cannot be opened. What's the matter?

noaccess

It's already open.
thanks!

qq 20180608140957

### CODE REVIEW

**Comment by RytoEX** [comment]
@tea1111980 We are aware that the website is down.  In the future, this is not the best way to try to find out what is wrong with the website.  Please check the OBS Discord or IRC if you have trouble accessing the website.

Discord:  https://discord.gg/obsproject

**Comment by RytoEX** [comment]
The website seems to be back up now.

**Comment by Gol-D-Ace** [comment]
Like RytoEX already mentioned...

Please don't use PRs as support request.

**Comment by tea1111980** [comment]
@RytoEX  Thank you for your help. I've been there.

**Pull request closed without merging**
