### PR TITLE
UI: Try closing remux before initiating shutdown

### LINKED ISSUE #4522: Remuxing process continues instead of stopping
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

26.1.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/IJVvvaiYcrwhERo7

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

The program should not close when clicking "No" to the dialog box indicating that remuxing is in progress after trying to close OBS.

### Current Behavior

The main program closes but leaves the remux recording dialog opened and freezes (does not fully crash but is not responsive).

### Steps to Reproduce

1. Click "File -> Remux Recordings"
2. Select a file for OBS Recording and Target File then click "Remux"
3. Before remuxing finishes, close OBS in any way
4. Click "No" to "Remuxing is not finished, stopping now may render the target file unusable. Are you sure you want to stop remuxing?"
5. Repeat step 4 again one more time (same dialog message reappears) then go to step 6
6. Program closes, remux recordings dialog box still shows but is unresponsive and must be killed

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Makes OBS try to close the remux dialog before Clearing Scene data since
in case a remux might still be going on and the user does want to abort
closing OBS.

### Motivation and Context

Fixes #4522

### How Has This Been Tested?

macOS 12 Beta 6, compiled and run

Pressing *No* when the dialog pops up will now correctly abort the shutdown process and keep OBS open (without asking a second time).
Pressing *Yes* will still shut down OBS and stop the remux.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
@Warchamp7 Is this new UX okay?
@notr1ch Since you commented on the linked Issue, does this adequately fix the described issue?

**Comment by Warchamp7** [comment]
Would like the phrasing on this dialog to conclude with "Are you sure you want to close OBS", but otherwise LGTM

**Comment by gxalpha** [comment]
> Would like the phrasing on this dialog to conclude with "Are you sure you want to close OBS"

While I haven't looked at this PR in months, doing this might make the PR significantly more complicated. How important would this be to you? @Warchamp7

**Comment by Warchamp7** [comment]
> > Would like the phrasing on this dialog to conclude with "Are you sure you want to close OBS"
> 
> While I haven't looked at this PR in months, doing this might make the PR significantly more complicated. How important would this be to you? @Warchamp7

Is this not just a matter of adjusting the localization string?

**Comment by Warchamp7** [comment]
After speaking with @RytoEX I've gotten it clarified that this is the general warning for the Remux being closed during a remux specifically, not a dialog warning for this specific example.

As such, fine with the verbiage as is.

**Review by Warchamp7 — APPROVED** [review]

**Pull request merged**
