### PR TITLE
obs-outputs: RAMP protocol support

### PR DESCRIPTION
**Pull request by SoftwareArchitector**
Add ramp-sdk submodule and support new Restream.io RAMP protocol

### Description

Support new RAMP protocol for Restream.io

### Motivation and Context

RAMP protocol is rtmp based protocol wrapped to udp tunnel with lost packet correction/fec/encryption functions. It helps users with "not-good" internet connections stream video more stable and with a higher bandwidth

### How Has This Been Tested?

It has been tested under Windows 32/64 and Linux. Closed user beta test (a few dozens of users) has been made.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
It's strange that if this were merged, OBS would essentially have librtmp compiled twice, once with your changes and once with OBS's. Can you offer a more comprehensive rationale for why this protocol was necessary to create instead of using a more established protocol?

**Comment by jp9000** [comment]
> It helps users with "not-good" internet connections stream video more stable and with a higher bandwidth [to restream.io]

I feel a bit uncomfortable with this as a rationale behind including two copies of librtmp to be compiled with the project.  I can't help but feel I'd need to see hard data to back this up, but even then, I still would hesitate because I can't help but wonder why you'd want RTMP with it.  RTMP is a garbage protocol that needs to be replaced due to newer codecs coming out.

**Comment by Xaymar** [comment]
Don't we have SRT for this exact purpose of allowing people with "not-good internet" to stream? What's the point of wrapping RTMP in UDP if SRT does it better and with broader format support?

**Comment by SoftwareArchitector** [comment]
> It's strange that if this were merged, OBS would essentially have librtmp compiled twice, once with your changes and once with OBS's. Can you offer a more comprehensive rationale for why this protocol was necessary to create instead of using a more established protocol?

The classic librtmp works with tcp sockets only, and I don't want to modify it. Second (internal) librtmp has been modified to generate packets and to parse responses using memory buffers

**Comment by SoftwareArchitector** [comment]
> I feel a bit uncomfortable with this as a rationale behind including two copies of librtmp to be compiled with the project. I can't help but feel I'd need to see hard data to back this up, but even then, I still would hesitate because I can't help but wonder why you'd want RTMP with it. RTMP is a garbage protocol that needs to be replaced due to newer codecs coming out.

New protocols will require a significant change in server software. That is why we need classic rtmp to wrap in new transport and after unwrap on server side and continue to work with the video stream with existing software

**Comment by SoftwareArchitector** [comment]
> Don't we have SRT for this exact purpose of allowing people with "not-good internet" to stream? What's the point of wrapping RTMP in UDP if SRT does it better and with broader format support?

SRT is not supported widely, we can't say that it will work good for our users, SRT implementation and tests require more time (significantly)

**Comment by pkviet** [comment]
Thanks for this submission. I have a few comments :
- is Restream.io aware of the dynamic bitrate capability (I worked on it with Jim). I'm using it in prod in sometimes very bad internet and it works quite well. Isn't your ramp proto redundant with it ? have you tested one against the other ?
- Merging this into master creates some maintainer burden on obs devs which is difficult to justify since the feature benefits a very small user base. It's not the case of dynamic bitrate which is not restricted to a single service but can work directly on Twitch, YT, FB including Restream.io etc.
- Given the very specific scope of your internal plugin, have you considered turning it into an external plugin ?
Obs users are used to adding plugins. Packaging your code from internal to external plugin is really not much work (check for instance obs-ndi or obs-websocket for examples). If you need help, you can ask help from obs devs in discord. We'll be happy to help.
This would entail that the maintainance burden would be on Restream.io , which imo only seems fair given that the plugin caters to the needs of its users exclusively. Obs is an open source project manned by very few people (mostly unpaid) so any addition to the source code requires strong justification.

**Comment by jp9000** [comment]
I apologize for not being very constructive in my criticism.  Truth be told however, I don't really know how to be constructive in this particular case.  Perhaps I could provide more details on why I am frustrated.

My primary grievance with this PR is you're asking me to merge a slightly modified duplicate library for a benefit that I personally am not so sure about.  I've never heard of RAMP before this PR.  I'm unsure of librtmp can reasonably be modified to accommodate both functionalities, but I feel like that would be something I'd prefer rather than having to maintain two duplicates of an entire library, with all potential hidden flaws it may have.  Anything that needs to be modified will then need to be modified in both.  We already have enough code duplication as it is, and this is code duplication on a much larger scale than in the past.  This is not a healthy practice to allow.

But even were that situation solved, I'm not sure how to feel about it.  Does it have an RFC/specs written out somewhere?  Does it have data to back it up?  How many people does it actually help? 
 Why not just transmux from another protocol that's already UDP?

My absolute anguish is that any code we merge becomes our responsibility, and any code we add brings a maintenance cost.  And when I say maintenance cost, it means that you should never assume that when you submit code to a project, that you will be able to maintain it forever or that it will never need to be touched again.

**Comment by SoftwareArchitector** [comment]
> * is Restream.io aware of the dynamic bitrate capability (I worked on it with Jim). I'm using it in prod in sometimes very bad internet and it works quite well. Isn't your ramp proto redundant with it ? have you tested one against the other ?

If you mean decreasing bitrate if the channel quality if not enough to transfer specified bitrate by user - yes, we have "back pressure" functionality. The sens of using udp+lost packet recovery is to keep bitrate high where tcp can't do it

> Merging this into master creates some maintainer burden on obs devs which is difficult to justify since the feature benefits a very small user base

50% of our beta testers noted improvement in video delivery (stable bitrate, stable fps)

> Given the very specific scope of your internal plugin, have you considered turning it into an external plugin ?

Yes, it is possible. But it is simpler just to use ready external tcp->udp tunnel applications without any efforts to make OBS more flexible and more functional. But we want to keep streaming for our users as simple as possible

P.S. rtmplib is helper inside our ramp-sdk module. It is not inside original OBS project. Our sdk exports several functions like ftl-sdk (start/stop/add video packet after encoder, add audio packet). Simple integration, simple support.

**Comment by SoftwareArchitector** [comment]
> I've never heard of RAMP before this PR. I'm unsure of librtmp can reasonably be modified to accommodate both functionalities, but I feel like that would be something I'd prefer rather than having to maintain two duplicates of an entire library,

original librtmp can be modified, but we preffer our library/sdk doesn't depend on another libraries in OBS, we need to keep simple integration for another projects

RAMP is "work name" for our udp tunnel that accepts h264/aac packets. It is not a new video protocol/container

**Comment by pkviet** [comment]
> > * is Restream.io aware of the dynamic bitrate capability (I worked on it with Jim). I'm using it in prod in sometimes very bad internet and it works quite well. Isn't your ramp proto redundant with it ? have you tested one against the other ?
> 
> If you mean decreasing bitrate if the channel quality if not enough to transfer specified bitrate by user - yes, we have "back pressure" functionality. The sens of using udp+lost packet recovery is to keep bitrate high where tcp can't do it
> 

I was referring to this in obs-studio :  Settings > Advanced > Network: Dynamically change bitrate to manage congestion .
How does it compare to RAMP when there is a network congestion ?

> > Merging this into master creates some maintainer burden on obs devs which is difficult to justify since the feature benefits a very small user base
> 
> 50% of our beta testers noted improvement in video delivery (stable bitrate, stable fps)
> 

I'm not talking of your users per se; what I meant is that the feature is of no immediate benefit to most of obs users since they don't use restream.io.
This is why in my opinion your work is better as an external plugin.

**Comment by jp9000** [comment]
The problem with it being an external plugin is distribution.  Until we implement our plans for the plugin management they won't really have much to gain by making it a plugin like that.  Besides, it wouldn't work with the current services listing because the services listing has no way of knowing if it's installed or not right now.

Anyway, as for the protocol issue.  Is there no alternative?

**Comment by jp9000** [comment]
I apologize, but I am not merging this.  You should have consulted me, consulted someone on the project, or made an RFC before starting any work on this.  The primary issue I have here is I am just not interested in having a duplicate RTMP library, especially when it's just to *supposedly* help with something that isn't our problem in the first place.  We already have too much duplicated code in the project that needs cleaning up.  If librtmp has a bug, both versions will have the bug.  Then both versions will have to be fixed.  If one needs a modification of some sort, then they'll both need the modification.  It's just absolutely bad programming practice; it's a terrible, terrible thing to do.  And no, you can't just excuse this just because it's in a submodule.

Which leads to my second issue:  one of the harsh lessons I've learned is that even if code is within a submodule, I have some level of responsibility for that code whether any of us like it or not.  It'll always be something I have to deal with if something goes wrong.  I have to pick my submodules wisely (hopefully never again).  The fact that you would even say "but it is hidden inside our library/module" is a huge warning flag for me.  Why would you say that?  Why would you even try to imply that's fine because of that?  Even if your librtmp module is within the submodule, I'm still responsible for dealing with any issues it has.  Compiling it.  Making sure its bugs are fixed.  Merging any pull requests related to it.  Getting reports from users that have issues with it.  Everything.

Submodules are not a "maintainer gets out of jail free" card.  They're the opposite.  That's a very dangerous thing to imply.  No maintainer should *ever* look at that statement without becoming very worried.

The third issue I have is somehow I -- respectfully -- doubt this is as significant as you make it sound, especially considering my own prior experiences over the years dealing with this *exact* issue: users with bad internet connections.

Let's go over the data, or lack thereof.

You say "50% of our beta testers," which at first glance *sounds* great, but it's very misleading for a number of reasons.  Firstly, this is of Restream beta testers.  Restream is arguably a pretty niche use-case as it is, so if you were to limit the sample pool to all Restream users, then it's already going to be a somewhat limited sample pool of users.  But this isn't the entire Restream userbase; we're talking about Restream *beta testers*.  So that limits the sample pool further: a percentage of a percentage.  For all I know it could have been less than 100 users.  Or maybe even it was just a few dozen.  Or maybe even less than that, I have no idea.  But it doesn't even really matter that much because of the following:

Secondly, somehow I doubt that this was a double-blind test.  So, let's say you tested 30 people with bad internet connections.  Let's say 15 people note improvements, 15 still have problems.  That's already a lot that still have problems, and should already indicate just how inconsistent these results are.  Now, out of those hypothetical 15 that had problems, how many of those would unintentionally give a placebo answer due to inconsistency of their internet connections?  How many are going to say "Hey, I think it's better!  I think I'm dropping less frames!" when in reality it's just inconsistent and misleading them?  Or, of those who claimed to stop having problems at first, how many are going to come back later and say, "hey I guess I'm still having problems after all?"

This is a bit of an anecdote, but back in the early days of OBS, I used to test various frame drop algorithms with various coefficients on various users with bad internet connections.  Some algorithms super complex, some super simple, some dynamic with many coefficients, some strict with few coefficients.  All just to try and find something that would drop the least amount of frames for the most amount of users.  One thing that I noticed with a notable amount of users is I'd get a response like "Hey that worked!  I'm not dropping frames anymore, thanks!", then some time later (maybe hours, maybe days), they'd come back saying "Nevermind I still have problems!"  Or, I'd see something like "I think it's working!  I think it's dropping less!" when in actuality it didn't really do anything.  Unsurprisingly, it would appear that no matter what I tried to do to reduce frame drops, ultimately, those who had bad internet connections would have issues at some point again, or different amounts at different frequencies instead.  Because they have bad internet connections.  And because of that, the results were *inconsistent*.

And thirdly: because of the inconsistency, because of the likely small sample pool of testers, because of the possibility of placebo responses, and because of the likely lack of long-term analysis, it makes that 50% number almost entirely meaningless.  That 50% should have *big* hint in the first place at just how inconsistent the issue we're dealing with here is in the first place.

Everything we do client-side for the people with poor internet connections are rarely going to actually solve their problems.  That's an absolute fact as far as I'm concerned at this point.  They always are just going to be bandaids, or desperate attempts that -- ultimately -- have little guarantee; all to try to solve something that was not our responsibility to fix in the first place.  That's what this entire thing feels like to me.  A desperate attempt to deal with something that was never our problem, or yours, to deal with.  It's unfortunate, but you are not responsible for the poor infrastructure in many parts of the world.  You are not responsible when so many cities are corrupt, enforcing a strict one-ISP-per-district rule; inhibiting infrastructure upgrades and stifling innovation.  For those who need to stream for a living, sometimes the only real option for them is to just move (4head).  It's a sad reality.

I would love to make everyone's bad internet magically not bad, but this is beyond crazy.  Everything about this feels unproven, overboard. and unnecessary.  It's ridiculous.

For normal users of restream, if they have no choice but to stream on an unstable internet connection, try to have them use dynamic bitrate instead or something.  It gauges how much throughput the user can send over a period of time and adjusts the bitrate according to the estimate based upon without dropping frames.

I apologize for the harsh response.  I know you mean well for your customers.  But I have enough to deal with as it is.  You can't just put something like 20,000 lines (including submodule) on my desk and expect me to merge it without being as critical as humanly possible.  I am going to pick everything apart down to the *bone* until I am absolutely *certain* that I want to take responsibility.  I have to be this way, otherwise I will end up in a mental ward.

At this point, the only way I'd ever approve this is if it was peer-reviewed and encouraged by other major industry players.  And the duplicate library thing was solved.

I'm sorry.  I'm not going to do it.

**Pull request closed without merging**
