### PR TITLE
UI: Add profile/scene collection rename events

### PR DESCRIPTION
**Pull request by cg2121**
### Description
Events make it more clear when profiles or scene collection are renamed.

### Motivation and Context
Found issue when making a plugin.

### How Has This Been Tested?
Tested with plugin I've made.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Does the same change need to be made for renaming profiles?

As this was introduced in 27.2, I'd be happy marking this as a bug fix for a 27.2 patch.

**Comment by tt2468** [comment]
I disagree. Since scene collections are only defined by their names, removing this event would make it very difficult to statefully track what's going on.

At the very least, I would suggest adding a new event like `SCENE_COLLECTION_RENAMED` to replace this functionality.

**Comment by cg2121** [comment]
@WizardCM profiles were fixed with https://github.com/obsproject/obs-studio/commit/2720e6d00fb6600f16714700acd24f980157b694

**Comment by gxalpha** [comment]
As far as I can tell, the events in #5945 were not removed, just deduplicated. They are still being emitted.

**Comment by cg2121** [comment]
@tt2468 I think that what's the LIST_CHANGING events are for.

**Comment by cg2121** [comment]
`@WizardCM profiles were fixed with https://github.com/obsproject/obs-studio/commit/2720e6d00fb6600f16714700acd24f980157b694`
Never mind with this.

I've updated to include profiles as well.

**Comment by tytan652** [comment]
> Don't call the changing and changed event when renaming a scene
> collection or profile, as they are not changed.

The path and name of the profile get changed and a way to notify about this to plugins is necessary to avoid issues.

Maybe `_RENAMING` and `_RENAMED` events.

**Comment by cg2121** [comment]
I've now added events for when profiles and scene collections are renamed.

**Comment by tt2468** [comment]
Looks good to me

**Pull request merged**
