### PR TITLE
UI: Use input validator on advance resolution line edit

### LINKED ISSUE #7991: Rescale output box doesn't error when invalid
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

28.1.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/ww8IlRgnwsHwvYbp

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When rescale output is checked in settings>output, it should error if the resolution entered is invalid or not allow you to enter invalid characters as it behaves in settings>video.

### Current Behavior

It does not error and allows you to start output, I believe it behaves as if the rescale output box isn't checked.

### Steps to Reproduce

1. Enable rescale output, add a space in the resolution such as "1280 x 720"
2. OBS will start the output at the resolution set in settings>video
3.
...

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by tuduweb**
### Description

Add input validator to other resolution edit line also.

### Motivation and Context

Fixes #7991

### How Has This Been Tested?

Cant input invalid character to combo edit line.
Close *Settings Dalog* then reopen, repeat the above steps, validator also work fine.

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
In the video tab, we additionally display an error when a currently invalid resolution is entered:

image
image

Depending on how easy or difficult that would be to implement I think it would be a nice to have, but perfect might the enemy of good here.


Besides that, this PR fixes the issue as advertised.

**Comment by tuduweb** [comment]
Update the PR, as the line edit in `FFmpeg` panel is ignored.

**Comment by tuduweb** [comment]
There is no unified warning/error notification mechanism (code/program framework) in obs-core in my view.
And I think it's hard to add message display with uniform style in UI-front.

In this case, where to add property message display make me a little confused.

If add message QLabel with the same style as `videoMsg`, it looks a bit ugly.



So I think if it needs to be further perfected, maybe some visual suggestions are needed.

Thanks for your reply. Look forward to your suggestions and further follow-up "perfect" development if possible.

@gxalpha

**Comment by gxalpha** [comment]
If it’s too complicated, it could be fine as-is. Don’t worry about it for now.

**Pull request merged**
