### PR TITLE
rtmp-services: Update AfreecaTV

### PR DESCRIPTION
**Pull request by karenkim-AfreecaTV**
### Description

Add Brazil server to the service

### Motivation and Context

Added server for users in South America.

### How Has This Been Tested?

Locally tested and is working properly.

### Types of changes

Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
Please update the commit message according to the [contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst)

**Comment by Fenrirthviti** [comment]
And more specifically, please make sure you read: https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines

**Comment by karenkim-AfreecaTV** [comment]
Hello, I updated the title and commit message according to the guideline. Sorry if I missed anything.

**Comment by gxalpha** [comment]
From what I can tell, you updated the PR title, but not the commit message title (they are two different things). You can change the commit message by amending the commit and then force pushing it.

**Comment by karenkim-AfreecaTV** [comment]
Thanks so much for the comment. Would it be against the guideline if I close this pull request and reopen it with a revised commit message title?

**Comment by gxalpha** [comment]
It probably wouldn't be against the guidelines, but it's much easier if you update this PR instead of opening a new one

**Comment by karenkim-AfreecaTV** [comment]
Thanks! I tried to update this pull request, but it seems like I'm doing it all wrong. I'll reopen the PR this time. Sorry for the inconvenience I caused.

**Pull request closed without merging**
