### PR TITLE
UI: Various visual improvements

### PR DESCRIPTION
**Pull request by cg2121**
I found these to be very ugly, especially with the dark themes.

Before:
Screenshot from 2019-04-29 13-37-42
Screenshot from 2019-04-29 13-38-25

After:
Screenshot from 2019-04-29 13-32-39
Screenshot from 2019-04-29 13-31-59

### CODE REVIEW

**Comment by WizardCM** [comment]
I considered doing something to this effect as part of #1641 but ended up not (at least for Output) due to the planned refactor to support multiple outputs. I am all for this change though.

**Comment by cg2121** [comment]
I've now added a couple more visual changes:
-make Dark theme flat
-remove icons from settings button box

Before:
Screenshot from 2019-04-29 16-48-30
Screenshot from 2019-04-29 16-48-55

After:
Screenshot from 2019-04-29 16-42-20
Screenshot from 2019-04-29 16-46-08

**Comment by garoto** [comment]
Is the left-alignment in the title of the 'docks' intentional?

**Comment by jp9000** [comment]
The before of the main window is better than the after.

**Comment by WizardCM** [comment]
I second that dock headings should remain centered. I do like the lack of gradients though.

**Comment by cg2121** [comment]
I've now combined this with #1845

**Comment by cg2121** [comment]
I've now added Kbps suffix to the bitrate spinboxes, and also added the ability for properties to set a suffix.
Screenshot from 2019-04-30 09-45-18

**Pull request merged**
