### PR TITLE
obs-websocket: Update version to 5.3.3

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update obs-websocket version to 5.3.3.

### Motivation and Context

Fixes a test mode being enabled by default that we previously missed. See OBS Studio 30.0.0-beta1 to 30.0.0-rc1:
```
15:58:12.994: [obs-websocket] [test_register_vendor] Registering test vendor...
15:58:12.994: [obs-websocket] [test_register_vendor] obs-websocket plugin API version: 2
15:58:12.994: [obs-websocket] [test_register_vendor] Called GetVersion. Status Code: 100 | Comment: (null) | Response Data: {"availableRequests":["GetHotkeyList","OpenInputInteractDialog","SaveSourceScreenshot","GetVersion","SetInputName","SetSceneName","GetStats","TriggerStudioModeTransition","SetInputAudioSyncOffset","GetSceneCollectionList","BroadcastCustomEvent","Sleep","SetSceneSceneTransitionOverride","CallVendorRequest","CreateSceneCollection","SetStudioModeEnabled","TriggerHotkeyByName","OpenVideoMixProjector","TriggerHotkeyByKeySequence","GetPersistentData","SetSceneItemIndex","SetPersistentData","SetCurrentSceneCollection","SetInputMute","SetCurrentPreviewScene","SetCurrentProgramScene","OpenSourceProjector","GetProfileList","SetCurrentProfile","RemoveProfile","CreateProfile","GetProfileParameter","SetProfileParameter","GetInputPropertiesListPropertyItems","GetInputAudioBalance","GetStreamServiceSettings","GetVideoSettings","SetVideoSettings","SetInputAudioBalance","SetInputVolume","SetStreamServiceSettings","GetInputDefaultSettings","GetSpecialInputs","GetInputKindList","GetRecordDirectory","SetSourceFilterEnabled","SetRecordDirectory","GetInputList","GetSceneList","GetInputMute","GetCurrentPreviewScene","GetReplayBufferStatus","GetSourceActive","GetSourceScreenshot","GetSourcePrivateSettings","SetSourcePrivateSettings","GetGroupList","SetInputSettings","GetCurrentProgramScene","GetSceneItemId","RemoveScene","CreateScene","GetSceneSceneTransitionOverride","RemoveInput","CreateInput","GetSceneItemLocked","GetInputSettings","ToggleInputMute","SetCurrentSceneTransition","GetInputVolume","GetInputAudioSyncOffset","GetInputAudioMonitorType","SetInputAudioMonitorType","StartVirtualCam","GetInputAudioTracks","SetInputAudioTracks","PressInputPropertiesButton","GetTransitionKindList","GetSceneItemTransform","GetSceneTransitionList","GetVirtualCamStatus","GetCurrentSceneTransition","SetCurrentSceneTransitionDuration","SetCurrentSceneTransitionSettings","GetCurrentSceneTransitionCursor","SetTBarPosition","StopOutput","ToggleOutput","GetSourceFilterList","GetSourceFilterDefaultSettings","CreateSourceFilter","RemoveSourceFilter","SetSourceFilterName","GetSourceFilter","StopRecord","ToggleRecord","SetSourceFilterIndex","SetSourceFilterSettings","SetSceneItemTransform","GetSceneItemList","GetGroupSceneItemList","CreateSceneItem","RemoveSceneItem","DuplicateSceneItem","GetSceneItemEnabled","SetSceneItemEnabled","SetSceneItemLocked","GetSceneItemIndex","StartReplayBuffer","GetSceneItemBlendMode","SetSceneItemBlendMode","GetSceneItemPrivateSettings","SetSceneItemPrivateSettings","StopVirtualCam","ToggleVirtualCam","StopReplayBuffer","ToggleReplayBuffer","SaveReplayBuffer","GetLastReplayBufferReplay","GetOutputList","GetOutputStatus","StartOutput","GetOutputSettings","SetOutputSettings","GetStreamStatus","StopStream","ToggleStream","StartStream","SendStreamCaption","GetRecordStatus","StartRecord","ToggleRecordPause","PauseRecord","ResumeRecord","SetMediaInputCursor","GetMediaInputStatus","OffsetMediaInputCursor","TriggerMediaInputAction","GetStudioModeEnabled","OpenInputPropertiesDialog","OpenInputFiltersDialog","GetMonitorList"],"obsVersion":"30.0.0","obsWebSocketVersion":"5.3.1","platform":"windows","platformDescription":"Windows 11 Version 22H2","rpcVersion":1,"supportedImageFormats":["bmp","cur","icns","ico","jpeg","jpg","pbm","pgm","png","ppm","tif","tiff","wbmp","webp","xbm","xpm"]}
15:58:12.995: [obs-websocket] [test_register_vendor] Post load completed.
```

### How Has This Been Tested?

Configured and built locally on Windows 11.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by tt2468 — APPROVED** [review]

**Comment by gxalpha** [comment]
Should this maybe update to master instead? The difference is that master has localization updates (and a few inconsequential docs changes), and it would allow for future localization updates to be automatic

**Comment by RytoEX** [comment]
> Should this maybe update to master instead? The difference is that master has localization updates (and a few inconsequential docs changes), and it would allow for future localization updates to be automatic

If another update to obs-websocket is required, I would rather re-tag it.

**Comment by WizardCM** [comment]
> > Should this maybe update to master instead? The difference is that master has localization updates (and a few inconsequential docs changes), and it would allow for future localization updates to be automatic
> 
> If another update to obs-websocket is required, I would rather re-tag it.
> 
> I also don't see anything consequential between 5.3.2 and current HEAD that allows automatic localization updates. Are you thinking of [obsproject/obs-websocket@132d4ba](https://github.com/obsproject/obs-websocket/commit/132d4bafddcc077f8d46f05dd920591fa2bc87e6)?

The obs-studio repo automatically updates submodules if they're currently in-sync and a translation update is pulled, to ensure all submodules remain in sync (ie. it pushes translation commits to both obs-studio and all submodules, then pulls submodules - unless the submodules != master).

**Comment by gxalpha** [comment]
> I also don't see anything consequential between 5.3.2 and current HEAD that allows automatic localization updates. Are you thinking of https://github.com/obsproject/obs-websocket/commit/132d4bafddcc077f8d46f05dd920591fa2bc87e6?

Didn’t see the edit in the comment, but yes, as Matt is saying.

**Comment by RytoEX** [comment]
Re-tagged latest obs-websocket commit as 5.3.3 and updated this PR. Please wait for this to be merged before re-running translation syncs.

**Pull request merged**
