### PR TITLE
Cherry Picks for 29.1.3

### PR DESCRIPTION
**Pull request by derrod**
### Description

Cherry picks for 29.1.3:

- https://github.com/obsproject/obs-studio/pull/8977
- https://github.com/obsproject/obs-studio/pull/8979
- https://github.com/obsproject/obs-studio/pull/9009
- https://github.com/obsproject/obs-studio/pull/8991
- https://github.com/obsproject/obs-studio/pull/9034
- https://github.com/obsproject/obs-studio/pull/7319
- https://github.com/obsproject/obs-studio/pull/9042
- https://github.com/obsproject/obs-studio/pull/9041
- https://github.com/obsproject/obs-studio/pull/9052
- https://github.com/obsproject/obs-studio/pull/9045
- https://github.com/obsproject/obs-studio/pull/9058
- https://github.com/obsproject/obs-studio/pull/9046
- https://github.com/obsproject/obs-studio/pull/9047
- https://github.com/obsproject/obs-studio/pull/8093
- https://github.com/obsproject/obs-studio/pull/9044
- https://github.com/obsproject/obs-studio/pull/7950
- https://github.com/obsproject/obs-studio/pull/9087

### Motivation and Context

Want to fix some things before the next major version.

### How Has This Been Tested?

N/A

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Personally I'd also like to include the following:

- https://github.com/obsproject/obs-studio/pull/9003
- https://github.com/obsproject/obs-studio/pull/7246

Would like to hear opinions on those.

**Comment by tytan652** [comment]
> Would like to hear opinions on those.

For the first, the lack of sorting is not a bug.
For the second, it adds a new feature/option.
There is also #8985, that is not a bug fix but a tweak to fix consistency.

29.1.3 is a patch version which is meant only for bug fixes.

**Comment by RytoEX** [comment]
> Personally I'd also like to include the following:
> 
>     * [UI: Sort encoders alphabetically #9003](https://github.com/obsproject/obs-studio/pull/9003)
> 
>     * [UI: allow side docks to be tall #7246](https://github.com/obsproject/obs-studio/pull/7246)
> 
> 
> Would like to hear opinions on those.

I don't think either of those belong in a patch release.

I'm not sure that #8985 belongs in a patch release either, but will defer to @Warchamp7 on its severity.

**Comment by derrod** [comment]
Added #9034 and removed #8985

**Comment by derrod** [comment]
Added #5066, #8996, and #7319

**Comment by RytoEX** [comment]
#5066 is probably a breaking change (it's a behavior change at least) since where before a minimized window would render a freeze frame, it will now render nothing, revealing whatever is underneath it.

I'm not sure if #8996 is something necessary for a patch release. I can't tell what problem it's fixing that we need to alleviate by backporting it.

#7319 is fine.

**Comment by derrod** [comment]
> #5066 is probably a breaking change (it's a behavior change at least) since where before a minimized window would render a freeze frame, it will now render nothing, revealing whatever is underneath it.

It is a bug fix that brings behvaiour in line with other sources (e.g. game capture) but I agree that it might be a behaviour people rely on, so I have removed that and #8996 for now.

Added #9041 and #9042.

**Comment by RytoEX** [comment]
#9034 is the only one I'm not sure about. I'll need to look at this on an AMD system to see if it's safe for a hotfix.

**Comment by derrod** [comment]
Added #8093 based on conversation off-thread.

**Comment by RytoEX** [comment]
#9044 and #7950 were also previously added.

I've also updated obs-websocket here.

**Comment by RytoEX** [comment]
Added #9087.

**Review by RytoEX — APPROVED** [review]
Looks good to me.

**Pull request merged**
