### PR TITLE
UI/obs-ffmpeg: Update NVENC internal ids

### PR DESCRIPTION
**Pull request by derrod**
> [!Important]
> This PR includes #10122 and #10133 as it is based on those changes. Only the last two commits are what's actually being changed compared to those.

### Description

Updates NVENC encoder ID from `jim_nvenc` to more neutral `obs_nvenc` and brings them in line with the new non-texture encoder. Maintains backwards compatibility by registering a deprecated encoder with the old ID to not break existing configs.

### Motivation and Context

Clean up naming schemes.

### How Has This Been Tested?

Verified old encoder id is still usable, but that only new ones are used in the UI.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by ma3uk** [comment]
There is a problem with starting the encoding process on a multi-GPU system if OBS is running on a graphics card from another manufacturer
image

**Comment by derrod** [comment]
> There is a problem with starting the encoding process on a multi-GPU system if OBS is running on a graphics card from another manufacturer

That's probably just due to me forgetting to update the ID in the non-texture encoder fallback, should be fixed now.

**Comment by WizardCM** [comment]
I wonder if we should perform automatic migration, and provide a way to have "alternate/legacy" codes that are exposed via the API, otherwise a user manually switching from the legacy ID to the new one would clear their encoder settings.

**Comment by derrod** [comment]
> I wonder if we should perform automatic migration, and provide a way to have "alternate/legacy" codes that are exposed via the API, otherwise a user manually switching from the legacy ID to the new one would clear their encoder settings.

Migrations could probably be done reasonably simple. I just didn't want to do it.

**Comment by derrod** [comment]
Added a simple migration, won't be backwards compatible, i.e. loading the profile in a previous OBS version will not find the encoder, but that's the best we can do.

**Comment by derrod** [comment]
Leavint this to be figured out with the NVENC refactor for 31.0.

**Pull request closed without merging**
