### PR TITLE
vlc-video: Add "VLC options"

### PR DESCRIPTION
**Pull request by andyli**
Add "VLC options", which is a list of options that will be added to each item in the VLC playlist.

One use case is to use the VLC Video Source as an alternative to Display Capture:

 1. Add a VLC Video Source
 2. Add an URL, `screen://`, in the Playlist.
 3. Add VLC options:
    * `:screen-fps=25`
    * `:screen-mouse-image=path/to/cursor.png`

I do not code in C often. Let me know if there is any room to improve or suggestion.

### CODE REVIEW

**Comment by pkviet** [comment]
Hello, thanks for this pr.
You don't need to include other locale files than en-US.ini because they will be translated in crowdin.
Remove them and force push to your branch.
This will automatically update the PR.

**Comment by jp9000** [comment]
Hi.  Please state the specific reason you decided to make this particular PR.  VLC should definitely not be used as an alternative screen/etc capture.

**Comment by andyli** [comment]
>You don't need to include other locale files than en-US.ini because they will be translated in crowdin.
Remove them and force push to your branch.

Removed the other locale files changes as suggested.

> Hi. Please state the specific reason you decided to make this particular PR. VLC should definitely not be used as an alternative screen/etc capture.

Actually it is the only screen capture method that works for my Windows 10 machine with an old graphic card (Quadro 600, no Intel integrated graphics). Neither Display Capture or Game Capture works. Setting Windows compatibility mode didn't help. I understand VLC Video Source `screen://` is probably not the right way to do it, but at least it satisfy my need of streaming non-game content (just coding).

Other than using `screen://`, this PR would be useful for any other scenarios that uses VLC options, e.g. 
https://obsproject.com/forum/threads/changing-vlc-preferences-for-obs.86438/

**Comment by jp9000** [comment]
Does display capture just generate a black/blank output?  Or does it not list your monitor?  I'd like to see a log file from it.  I'm likely not going to merge this just to fix niche cases, but I would like to have more information on your specific issue.

**Comment by andyli** [comment]
Here is my log: https://gist.github.com/andyli/3d4d92494a46f2e29964b3ce10039368

Choosing "Display Capture" did show the screen, but the screen is not refreshing (i.e. showing the same frame) until my cursor moves.

**Comment by andyli** [comment]
Here is a recording of my issue: https://youtu.be/BtV93obOzUo
And the log file during the capture of the above video: https://gist.github.com/andyli/2b047ba5c52c5c3049e5c2d362542981

**Comment by jp9000** [comment]
## The problem with PRs like this

**For the problem it's was made to alleviate, this PR only helps one person.**

This is going to seem like a bit of a harsh response, please bear with me because that's not my intention.  I want to state that even I could very well have done the same thing you're doing were I in your position without realizing it.  I just want you (and hopefully others reading this) to understand why I don't feel comfortable accepting PRs like this.

I want you to step back and think about this pull request for a moment:  why did you make it?  Now, you could say "to provide more VLC options", but let's face it:  the reason why you made it was because you wanted the ability to use an alternate means of capturing your display, because apparently your adapter doesn't support the modern display capture properly (I've never seen this issue before, so maybe there's something else going on there).  **The reason this PR was made was not really to provide extra VLC options.**

Now I want you to ask yourself this specific question:  let's be generous and say there are 10000 other people who have the same problem you do, where the adapter doesn't support the display capture method.  How many of those people are going are going to use the feature in this PR to fix that specific problem?  It would likely not help any of them.  This is because none of those people are going to know to use this feature, and type in those specific values unless they find instructions in some obscure place like on the forums.  And that is just not an acceptable way to solve the problem.

So, this PR probably should have been titled "add alternate means of capturing display via VLC".  However, because the user has to type in those specific options and know those options even exist for VLC in the first place, only one person benefits for that specific fix, which would be the person who made the PR.  That's what this comes down to:  other people affected by that adapter issue will not really be helped.  That is an unfortunate fact that you need to realize, and that is why I'm not comfortable with this sort of PR.

Sure, you want to sell me on this PR by saying this option could be useful for other options as well, but unfortunately, for the adapter issue which this PR was really made for, this PR will only really benefit one person.  This will not provide an adequate solution for that specific issue, and that's something you need to realize.

And I know that sounds harsh, that's not my intent.  I know that you probably didn't realize that when making it.  This is just something that people sometimes don't think about or consider when they make pull requests.

## What would have been a better solution

If you view the source code for display capture, you'll see that there are two methods:  the `duplicator-monitor-capture.c` file, which uses the modern one which is only available on windows 8/10+ that uses `IDXGIOutputDuplication` class via DXGI, and `monitor-capture.c`, which is the older one usually only used when on windows 7, that captures using the old `GetDC()` and `BitBlt()` functions via GDI.

First, it would be prudent to understand the problem, so you'd need to at least run OBS through the debugger to see why/how the duplicator is failing for your specific adapter.  After debugging has been done, if there's a bug, you'd want to patch it (although I don't *think* there is a bug).  If it's just an incompatibility for your adapter, you'd maybe want to try to implement an automatic fallback if someone has this card or something.  It has a built-in fallback in `plugin-main.c` if it detects OBS is running on windows 7, or running on the OpenGL renderer.

Although that would also be a bit precarious because you'd really want to verify that it was the card at fault, and not necessarily drivers or something.  The problem is probably non-trivial, but spending time on this could at least have a chance of going somewhere.

## Another workaround you can use for the time being

If it turns out your video adapter just simply does not properly support the DXGI display capture method, then instead, try this:

* Open the `global.ini` file in `%appdata%/obs-studio`
* In the `global.ini` file, go to (or add if not present) the `[Video]` section, then in that section, add `Renderer=OpenGL`.

This is an undocumented feature which will cause OBS to launch with the OpenGL renderer on windows, and use the GDI display capture, because the duplicator method is only available when OBS is running with Direct3D.  It'll likely solve the problem for your PC.

------------

Again, I just want to emphasize that you likely did not realize this all when making the PR.  This happens every so often with people submitting PRs (more often than I'd like), and even I could very well have done the same thing were I in your shoes, so don't think I'm necessarily chastising you or anyone over it.

But I wanted to write this all out to help ensure others are more cautious and aware in the future.

It's just a case where we need to be more aware of we're attempting to submit to a project, and where we need to be aware of whether we're actually fixing the problem adequately or not.

**Pull request closed without merging**
