### PR TITLE
UI: Adjust Yami (Classic) styling

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
Many of the changes to Yami had some unintended side effects to the Classic variant that were not properly accounted for before.

### Motivation and Context
Trying to match the old Dark theme more closely

### How Has This Been Tested?
Before:
image

After:
image

Before:
image

After:
image

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by derrod — CHANGES_REQUESTED** [review]
The "active" colour for buttons still is wrong

controls dock

**Comment by Warchamp7** [comment]
> The "active" colour for buttons still is wrong
> 
> controls dock

That was more or less a deliberate change

**Comment by derrod** [comment]
It does look pretty out of place

**Comment by Warchamp7** [comment]
> It does look pretty out of place

It's using the 'Primary' color of the theme, same as the Scene and Source lists (Which also had a minor visual behaviour change from stable). It's a more consistent use of 'Selected' or Active

**Comment by derrod** [comment]
None of the other buttons use that colour when pressed and it looks out of place imo.

**Comment by Warchamp7** [comment]
> None of the other buttons use that colour when pressed and it looks out of place imo.

It's the checked state versus pressed, it's meant to be different

**Comment by derrod** [comment]
The blue still looks weird though, I'd rather just have the old dark grey.

**Comment by RytoEX** [comment]
> The blue still looks weird though, I'd rather just have the old dark grey.

It looks like the blue is part of beta4, so this is not an issue with this PR per se, but rather something else that you would also like to see changed. Is that correct? If so, I don't want to block this PR on additional changes we'd like to see, and I'd like to get this merged to fix the issues that it _does_ fix.

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
