### PR TITLE
Cube LUT file support

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Support Cube LUT files, and add a couple samples to the data folder.

It should be noted that I copied the implementation of MIT-licensed XMConvertFloatToHalf from https://github.com/microsoft/DirectXMath.

### Motivation and Context
People are asking for it, and I myself would like to attempt better calibration of my capture video.

https://ideas.obsproject.com/posts/184/provide-3dlut-support-via-cube-files

### How Has This Been Tested?
Tested Cube LUT examples from Photoshop, Adobe spec, and some homebrew, and examined LUT textures in RenderDoc captures. 1D and 3D LUT variants were tested.

Tested PNG -> PNG, PNG -> CUBE, CUBE -> PNG, PNG -> empty, and CUBE -> empty transitions did not crash or leak obviously.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jpark37** [comment]
Let me know of there's a better spot for the MS license text. I copied it awkwardly next to the relevant function.

**Comment by DrConflict** [comment]
Big YES to this!

**Comment by jp9000** [comment]
I'd prefer the code associated with the license (as well as that license text) be moved to separate c/h files if that's okay.

**Comment by ragesaq** [comment]
Very interested and would be available for helping test. I create my LUTs with Davinci Resolve and would like to have a higher quality CUBE one vs the PNG method.

**Comment by DrConflict** [comment]
Could .3dl LUT formats be added as well? .CUBE will be a very nice addition though.

**Comment by jpark37** [comment]
I'll move the DirectXMath logic to separate files.

I'm not too hot on 3dl files mostly because there doesn't seem to be a specification for ii, so it's possible for it to have diverged between applications, and that we'd need to support multiple vendor-specific flavors.

**Comment by ragesaq** [comment]
Ran the PR build last night for a ~4 hour stream. 
My 66 point 3d luts exported from davinci worked beautifully. Love it!

Other observations of this build:
1: Stability was fine
2: Changing scene collections was a little slower than usual
3: Switching scenes to activate cameras was also a little slower than usual
4: XRGB video source gets flipped horizontally, the others I tried were YUY2 and I420 and they were both fine.

**Comment by jpark37** [comment]
The half float logic has been moved into its own header.

@ragesaq I am not able to reproduce 2 or 3, and 4 does not seem to be a regression involving this PR. We did merge in #2072 not too long ago to follow DirectShow specification more accurately. It's possible your device may not be compliant, and requires the vertical flip checkbox, which shouldn't be a big deal.

**Comment by ragesaq** [comment]
I just reproduced it with two different devices on a fresh scene with freshly added (not duplicated) sources.
Add video device, say custom reoslution, set resolution, set video format to XRGB. Both a logitech c920 (usb) and an Elgato HD60Pro with both a GoPro Hero Black 6 and Sony A6400 mirrorless camera were tested. All 3 exhibit the identical behavior, they work with other modes just not XRGB.

**Pull request merged**
