### PR TITLE
UI: Fix typo; ideal is an absolute.

### PR DESCRIPTION
**Pull request by robertdebock**
### Description
The UI displays "most ideal", but `ideal` is an [absolute](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_m&page=9nntQuSXcUiI.html#:~:text=Ideal%20is%20an%20absolute%20and,ideal%20vacation%20spot%20in%20summer.). There is no `more`, `less` or `most` for `ideal`.

### Motivation and Context
Just a small change to improve English.

### How Has This Been Tested?
No tests, spelling error.

### Types of changes

- Documentation (a change to documentation pages)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
While you are correct that "ideal" is an absolute, removing the "most" in there suggests that AutoConfig is perfect (which it isn't, you won't be able to find the best settings just by running AutoConfig).
I do agree that the wording isn't the best here, the "most" is a sign that the settings found are the best that AutoConfig could find. The problem is that what these locales are trying to express would need an entire paragraph, and can't be perfectly described in one sentence. The locales are supposed to summarise this, and in my opinion removing the "most" in there makes the summary worse (even if the grammar is better).

**Comment by mufunyo** [comment]
If you want to be pedantic here the correct form is "closest to ideal".

**Comment by PatTheMav** [comment]
Wouldn't "optimised defaults" be the common term for what it does?

**Comment by Gol-D-Ace** [comment]
Just a note. The en-gb file will be overwritten by the next Crowdin pull.

Please only change the en-us file.

**Pull request merged**
