### PR TITLE
Fix FFmpeg deprecations up to FFmpeg 4.4 and current FFmpeg git

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

These commits address various FFmpeg changes, and deprecations.  They also address removals of deprecated code post FFmpeg 4.x.

Details about the changes and why they are needed are in each commit message.  As far as I can tell, these changes are compatible for the entire FFmpeg 4.x series, and _should_ be fine for FFmpeg 3.2+ releases.

Big thanks to @pkviet who helped me with this!

### Motivation and Context

These changes allow us to use FFmpeg 4.4+ up to FFmpeg to FFmpeg/FFmpeg@9d4989f2e17c11d4ee9daa489b6e4f5195d80b99.

### How Has This Been Tested?

On Windows 10 with FFmpeg 4.2.4, FFmpeg 4.4.1, and FFmpeg git (ffmpeg-N-104473-g9d4989f2e1, FFmpeg/FFmpeg@9d4989f2e17c11d4ee9daa489b6e4f5195d80b99), I successfully tested:
* streaming to Twitch with NVENC and x264
* recording to MKV and MP4 with NVENC, x264, and QSV
* Color Source with Color Correction filter
* Media Source with local files (MP4; WEBM with transparency)
* Media Source with Chroma Key filter
* Image Source with JPG and animated GIF
* Text Source (both GDI+ and FreeType2)
* Video Capture Device
* VLC Source with multiple files selected

Resulting recordings seems fine in VLC.

Needs additional testing on macOS and Linux, for which assistance would be appreciated.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Needs testing on Linux and macOS before being merged.

**Comment by ezette** [comment]
Yes

**Comment by kkartaltepe** [comment]
There are still a lot of warnings related to av_init_packet usage in obs-ffmpeg and the media-playback module when compiling on linux against ffmpeg 4.4.1. And one warning about codec usage. Thanks for all the cleanup.

```
plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:443:9: warning: ‘av_init_packet’ is deprecated
plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c:788:9: warning: ‘av_init_packet’ is deprecated
plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c:406:9: warning: ‘codec’ is deprecated
plugins/obs-ffmpeg/obs-ffmpeg-output.c:729:9: warning: ‘av_init_packet’ is deprecated
plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c:443:9: warning: ‘av_init_packet’ is deprecated
deps/media-playback/media-playback/decode.c:373:33: warning: ‘av_init_packet’ is deprecated
```

**Comment by RytoEX** [comment]
> 
> 
> There are still a lot of warnings related to av_init_packet usage in obs-ffmpeg and the media-playback module when compiling on linux against ffmpeg 4.4.1, some examples below. And one warning about codec usage. Thanks for all the cleanup.
> 
> ```
> plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:443:9: warning: ‘av_init_packet’ is deprecated
> plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c:788:9: warning: ‘av_init_packet’ is deprecated
> plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c:406:9: warning: ‘codec’ is deprecated
> plugins/obs-ffmpeg/obs-ffmpeg-output.c:729:9: warning: ‘av_init_packet’ is deprecated
> plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c:443:9: warning: ‘av_init_packet’ is deprecated
> deps/media-playback/media-playback/decode.c:373:33: warning: ‘av_init_packet’ is deprecated
> ```

I think I get those warnings on Windows as well, but I wanted to get compilation errors fixed more than anything for now.

It looks like the simple replacement for `av_init_packet` is `av_packet_unref`.  For `AVStream->codec`, it's removed in avformat 59, and that code is ifdef'd for that.  We could instead provide an ifdef to use `AVStream->codecpar`, which has been available since `AVStream->codec` was deprecated in FFmpeg 3.1 (https://github.com/FFmpeg/FFmpeg/commit/9200514ad8717c63f82101dc394f4378854325bf).  Or we assume (assert?) that only FFmpeg 3.4+ are supported in our codebase from now on (Ubuntu 18.04, see the first commit's commit message) and replace it entirely.

That said, I believe those warnings exist in current builds (FFmpeg 4.2.x on Windows and macOS), and I don't want to hold this up to address those.  If I get to them before this gets reviewed/tested/merged, then I might push those changes here, but if not, they can be addressed in a separate PR.

----

Thinking more on the existing changes in this PR, I do wonder if it would be better to ifdef the `const`'d functions instead of casting their results to non-const.

All that said, do let me know if everything seems to be working fine with these changes.

**Comment by kkartaltepe** [comment]
> I think I get those warnings on Windows as well, but I wanted to get compilation errors fixed more than anything for now.

Got it, there were no 4.4 changes that prevented compilation on linux for me at least. I assumed this was just to avoid deprecations.

> That said, I believe those warnings exist in current builds (FFmpeg 4.2.x on Windows and macOS), and I don't want to hold this up to address those. If I get to them before this gets reviewed/tested/merged, then I might push those changes here, but if not, they can be addressed in a separate PR.

Sounds good to me.

> Thinking more on the existing changes in this PR, I do wonder if it would be better to ifdef the const'd functions instead of casting their results to non-const.

Looking at ffmpeg source the output_format pointers returned are pointers to static lists, so it seems we should respect the const'ness and copy these. But i didn't happen to find any errors in my short recording tests.

> All that said, do let me know if everything seems to be working fine with these changes.

I didnt see anything wrong with doing a couple recordings in nvenc and x264.

**Comment by ezette** [comment]
Ok

**Comment by pkviet** [comment]
My own checks were on windows with FFmpeg 4.2, 4.4 and master. Streaming, recording and remuxing with nvenc were all fine.

**Comment by RytoEX** [comment]
Pushed two fixup commits to replace the const-to-nonconst casts with ifdefs. This also meant I had to revert some changes and ifdef those. Details are in the commit messages.

I've retested on FFmpeg git (ffmpeg-N-104473-g9d4989f2e1), but we'll probably need to retest on 4.2.4.

**Comment by RytoEX** [comment]
I've force pushed new changes:
* make the ifdef version checks more specific
* avoid casts
* respect const returns from the FFmpeg API

I've retested with FFmpeg 4.2.4 (current deps) and ffmpeg-N-104629-g18f22bfb27.

There are some items I'm still wondering about, but should not hold this up.  I wonder if this is sufficient for all cases, but I wanted to keep changes to current code paths minimal.
https://github.com/obsproject/obs-studio/pull/5501/files#diff-494928bd63dbef2d1f5dd72786864775b9b4383a0aa5db3548484dc3d12fd0f5R615-R622

I don't think we need to ifdef this because the relevant FFmpeg change is so old, but can ifdef it if needed.
https://github.com/obsproject/obs-studio/pull/5501/files#diff-aeaf37f34fce8f1e5cf42a1becbef3128057033f28899e4c844ec38def5a8cfaL380-R380

I don't understand why this was necessary, though the latest FFmpeg seems to be fine without it.
https://github.com/obsproject/obs-studio/pull/5501/files#diff-2bc93e6134b6ecd1adb0405b942d41f65adf5b7e57da02845ab3b7e3eac4116dR676-R679

That said, I'm satisfied with the changes enough to remove the Draft status.  Hopefully others can (re)test, and hopefully someone can address the points above if need be.

**Pull request merged**
