### PR TITLE
obs-qsv11: Set preference for encode to iGPU in case of i+i

### PR DESCRIPTION
**Pull request by cmlin2**
### Description

This change sets the preference for encoding to the integrated GPU over the discrete GPU on Intel systems with both iGPU and dGPU.

### Motivation and Context

The motivation is to give streaming customers the best hardware encoding experience when there are both iGPU and dGPU options on Intel systems.

### How Has This Been Tested?

This patch has been tested with 3 different versions of graphics drivers (both internal and external) on 3 different platforms to verify HW encoding on the iGPU over the dGPU.

### Types of changes

Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
Could you elaborate on why the performance would be better using the iGPU over the dGPU? This goes against common logic.

**Comment by cmlin2** [comment]
We found that with our first offering of discrete graphics, offloading the encoding from the dGPU to the iGPU dedicates the dGPU to gaming and can improve the E2E FPS for game streaming. This may not always be the case, but we want to provide the best experience for the end user.

**Comment by mufunyo** [comment]
> We found that with our first offering of discrete graphics, offloading the encoding from the dGPU to the iGPU dedicates the dGPU to gaming and can improve the E2E FPS for game streaming. This may not always be the case, but we want to provide the best experience for the end user.

I was under the impression that QSV encoding was done by a dedicated portion of ASIC silicon on the GPU and that it does not utilise the graphics/compute hardware. Or is it a memory/bandwidth constraint? If OBS compositing is done on the dGPU, I would expect that having to copy the image buffer to the iGPU would be slower than keeping it in dGPU VRAM and encoding it there.

**Comment by cmlin2** [comment]
There are two encoding modes on Intel's GPU: High Quality and Low Power. We recommend High Quality mode for game streaming which shares the HW resources with game rendering. Offloading encoding to the iGPU in this mode can get the best end to end game streaming FPS.

**Pull request merged**
