### PR TITLE
mac-virtualcam: Mark parameters as unused

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Marks function parameters as unused, removing compiler warnings

### Motivation and Context

These warnings bothered me in Xcode as they made real problems less clear.
Also less warnings = better, I suppose.

### How Has This Been Tested?

Successfully compiled (Xcode 12.2, macOS 11.1), warnings are gone.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by gxalpha** [comment]
uhhm, ill check the formatting again

**Comment by PatTheMav** [comment]
@gxalpha Thank you, had that on my list as well. If you don't mind, check the debug output by the DAL plugin when using Cameo, it's quite chatty. Especially when OBS sends input but you don't have an output active there'll be massive spam about the frame queue being full or something along those lines.. 😬

**Comment by gxalpha** [comment]
> If you don't mind and got time, also check the debug output by the DAL plugin when using Cameo, it's quite chatty. Especially when OBS sends input but you don't have an output active there'll be massive spam about the frame queue being full or something along those lines.. 😬

That would belong into another PR though, right?

**Comment by PatTheMav** [comment]
Yep, just occurred to me while reading this one.

**Comment by gxalpha** [comment]
Btw consider this not ready to merge as there is stuff in the DAL-plugin as well, just one question:
Since the DAL-plugin can't access libobs - Is it better to
- just leave everything as it is
- tag the arguments with __attribute__((unused)) (this would work, but makes it look somewhat ugly) or
- define a UNUSED_PARAMETER macro in one of the DAL plugins header files?

**Comment by WizardCM** [comment]
I'd say either option 2 or 3 is fine. Might just be worth defining it in the header just so we're consistent about how we define unused parameters.

**Comment by gxalpha** [comment]
so, im not sure if using the existing logging.h file is correct here, but i personally also feel like creating a new header just for this might be overkill

**Pull request merged**
