### PR TITLE
rtmp-services: Add Manyvids.com

### PR DESCRIPTION
**Pull request by mavtek-streaming**
### Description
Add Manyvids to rtmp services list

image

### Motivation and Context
Manyvids.com starts to provide static rtmp URL. To facilitate our users, we want to add Manyvids to the rtmp service list. 

### How Has This Been Tested?
Local build

### Types of changes
 - New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by mavtek-streaming** [comment]
> Do you have a page where your stream settings/requirements are listed on your site?

Our RTMP service is currently in "beta". Once officially launched (soon!), there will be a page which will provide the settings and requirements.

**Comment by derrod** [comment]
Just two notes:

1. 720p30 seems a bit low considering the 10 Mbps bitrate
2. It's probably a good idea to specify a keyframe interval (`keyint`) that matches your requirements

**Comment by mavtek-streaming** [comment]
> Just two notes:
> 
> 1. 720p30 seems a bit low considering the 10 Mbps bitrate
> 2. It's probably a good idea to specify a keyframe interval (`keyint`) that matches your requirements

Good idea, I've updated PR

**Comment by derrod** [comment]
FYI there's a merge conflict with your current commit due to another service being merged.

We will merge this once your service has reached general-availability and public documentation is available. I will mark your PR as a draft for now. Feel free to un-draft it once the service is ready.

We are working on finalising proper documentation for service submissions that will include such requirements.

**Comment by dodgepong** [comment]
I see you've already taken this back out of draft. Does that mean the service is now publicly available, as specified by @derrod?

**Comment by mavtek-streaming** [comment]
It is now back to Draft.  Sorry about that.   We are coordinating with our Marketing and Customer Support departments to make sure the documentation is ready for the official launch.   We will re-open this PR when they are ready to go.  Thanks for your feedback.

**Comment by mavtek-streaming** [comment]
Hello, our service is available to the public. Here are the documents:

https://mv-support.knowledgeowl.com/help/how-to-use-obs-on-mv-live
https://mv-support.knowledgeowl.com/help/obs-troubleshooting

Please review. Thank you.

**Comment by derrod** [comment]
The max video bitrate in the documentation is 5000 kbps, but the JSON entry says 4000. Please make sure that's correct.

**Comment by mavtek-streaming** [comment]
> The max video bitrate in the documentation is 5000 kbps, but the JSON entry says 4000. Please make sure that's correct.

The max video bitrate in the documentation has been fixed. Thank you for pointing this out.

**Pull request merged**
