### PR TITLE
UI: Match Windows taskbar state to tray icon (v2)

### PR DESCRIPTION
**Pull request by WizardCM**
### Description

This adds a status icon overlay for active/paused outputs. It is shown in the bottom right corner of the icon in the taskbar. This is consistent with other apps like Discord (notification count) and Chrome (current profile, if multiple available).
Note: this status icon isn't visible when the taskbar is in "small icon" mode.

Example from other apps:
image
image

Stripped down version of #2442

### Motivation and Context

While the coloured taskbar may have been considered overkill, I believe it's still worth including a visual on the taskbar when an output is active. It is common enough for users in support channels (especially Twitter) to mention that they either forgot to hit record, or didn't realise that they had stopped recording. The icons are large enough to be noticeable, but small enough to not be distracting.

### How Has This Been Tested?

Windows 10. Start an output, pause it, then stop it.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Rebased to latest master, ready for review.

**Comment by Buzzker** [comment]
I updated OBS today and now that red dot is shown on TaskBar. Can I disable it?

**Comment by Technetium1** [comment]
There should definitely be a way to toggle this.

**Comment by gxalpha** [comment]
What would the reason behind disabling it be?

**Comment by Technetium1** [comment]
@gxalpha The reason is that a couple of my friends are very annoyed by it. If you make something change colors or stand out even when not in focus, there should be a way to toggle it. I have already confirmed there's not a way to remove badges from the taskbar individually, so adding the ability to toggle it in OBS is the only way to stop it.

**Pull request merged**
