### PR TITLE
rtmp-services: Update Mixcloud

### PR DESCRIPTION
**Pull request by matclayton**
### Description

Updating Mixcloud Service settings to be more compatible

### Motivation and Context

We're seeing a number of users repeatedly using settings which cause problems, so this addresses those and provides better defaults

### How Has This Been Tested?

Followed convention, these are also known best configurations on Mixcloud (I work there and lead that team)

### Types of changes

Amending Mixcloud services configuration to be more compatible with our infrastructure

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
What kind of issues are you seeing that require main profile? Any device produced in the last ~10 years should support high.

**Comment by matclayton** [comment]
We're not specifically seeing issues with main, more 60fps and 1080p are causing issues. We noted however a significant number of other services we're requiring the main profile in services.json

**Comment by matclayton** [comment]
@notr1ch Have amended and squashed.

**Comment by jp9000** [comment]
Max width/height was not released yet. I already removed it from the code because we're doing a different approach.

**Comment by jp9000** [comment]
I don't want to approve this PR yet because we're still testing the waters with the width/height/fps thing with facebook. Come back in a month or two before making another PR if there is an issue and you are sure that you need this.

**Comment by matclayton** [comment]
No worries, the issue we have is we don't fully support 60fps (the size is less of an issue) and it will cause buffering issues due to starvation of the transcoding cpus on our end, so we were hoping to push this to OBS to protect users from having these problems.

**Pull request closed without merging**
