### PR TITLE
Typo correction (underscore that breaks compilation)

### PR DESCRIPTION
**Pull request by twdragon**

### CODE REVIEW

**Comment by twdragon** [comment]
Absence of QAction header ruins the compilation using bleeding-edge Qt.

**Comment by SuslikV** [comment]
1. Similar PR already exist: https://github.com/obsproject/obs-studio/pull/1238
2. Typo? Are you sure?

**Comment by twdragon** [comment]
I am sure about the PR #1238 it is on the same issue.

On underscore in obspython target: it shows very strange behavior so now I might to check my compilation pipeline strictly.

**Comment by SuslikV** [comment]
Please, look at the: https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#coding-guidelines (commits headers, look at most recent changes in "cmake" folder for example)

**Comment by jp9000** [comment]
The underscore is intentional -- it doesn't break compilation on any of our builds.

**Pull request closed without merging**
