### PR TITLE
UI: Refactor replay buffer

### PR DESCRIPTION
**Pull request by cg2121**
With simple and advanced modes now having the replay buffer,
it makes sense to enable its checkbox by default. It also
helps out new users by not having to do several steps
to enable the replay buffer. Now they just have to set
the save hotkey.

### CODE REVIEW

**Comment by SuslikV** [comment]
It's too late for this change.

**Comment by Fenrirthviti** [comment]
I'm not quite sure I think this is a good idea. Replay buffer uses the recording encoder, meaning that turning this on will result in a encoder being active when OBS is launched. By default, we use the x264 encoder, which will have a significant performance impact just having OBS open. I'm curious what others think, but my gut on this says this is a bad idea.

**Comment by WizardCM** [comment]
@Fenrirthviti Enabling the ability to use the Replay Buffer is separate from enabling the Replay Buffer's encoder. The latter still has to be enabled from the main OBS window with this PR.

**Comment by Fenrirthviti** [comment]
Gotcha, my mistake. I have no concerns then.

Should we just remove the option completely then and have it always on? Is there a reason to disable it?

**Comment by WizardCM** [comment]
I would agree. We don't allow the ability to disable Streaming/Recording, why can users disable the Replay Buffer.
One reason may be "well, I don't want the button in the Controls section because I don't use it". I'd vote we completely remove the Replay Buffer toggle, and then create a second PR with the ability for people to hide/show individual buttons in Controls. It'd just be a context menu with the list of buttons and clicking the relevant item in the context menu would toggle that button in the controls.

**Comment by cg2121** [comment]
I have now removed the check boxes from the settings.

TODO:
-Ability to hide control buttons

**Comment by cg2121** [comment]
I've now added the ability to hide/unhide control buttons.

**Comment by cg2121** [comment]
I've now added a save replay buffer button.
Screenshot from 2019-07-16 07-37-04

**Comment by WizardCM** [comment]
Looks good and works well.

One thing to note is that the Start Replay Buffer button lights up but doesn't do anything if you're using Custom FFmpeg Output mode. I vote the button should hide in that situation.

**Comment by cg2121** [comment]
I've now set the replay buffer button to hidden when using FFmpeg output.

**Comment by SuslikV** [comment]
I'm seeing "download" button and don't know what to do with it. Is this really "save the replay file" feature? More over, it is so small...

**Comment by jp9000** [comment]
I'm unsure how I feel about making the replay buffer active all the time.  What does everyone else think about having the replay buffer button always visible, versus having it be explicitly enabled by the user when they want to use it like it currently is on master?

For one, I don't really like confusing new users that much.  Having "start streaming", "start recording", and "start replay buffer" feels like it adds a bit of intimidation factor for the completely new and inexperienced users.  My preference has always been to hide more advanced features by default and keep things as simple and straightforward as possible for new users as we can.

On the flipside, the UX is poorer for people who want to use the replay buffer because they have to explicitly enable it if they want to use it.  I'm a bit conflicted.

I feel like I would prefer the former rather than the latter though.  What does everyone else think?

**Comment by WizardCM** [comment]
Personally, I think this change enables better discoverability of the replay buffer, which a lot of people currently have no idea exists, both because it's hidden in Settings -> Output, and because of its name (most know it as "flashback recording" and "clips"). I do not think most users would consider this an "advanced" feature by any means, simply another capability alongside recording/streaming - one that some users want *instead* of a full-length recording.

In terms of adding complexity to the UI, I agree that it might, but I'd also argue it'll allow more people to learn about the feature's existence, which makes it worth it. Maybe it'd be worth adding a dialog the first time they click the button to explain what the feature is and how to set the length?

**Comment by cg2121** [comment]
I've now moved hiding of the control buttons to the view menu so users are less likely to hide the buttons by mistake.

**Comment by WizardCM** [comment]
@cg2121 It may be worth updating the title and description of the PR based on the changes since its original posting (including pictures). There also seem to be some new merge conflicts.

**Pull request closed without merging**
