### PR TITLE
mac-videotoolbox: Add ProRes 4444 (XQ) support

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Also add P216/P416 formats to pair with ProRes.

Augment I210/I412 formats with PQ/HLG support for media source playback.

### Motivation and Context
Want to retain precision when outputting ProRes.

### How Has This Been Tested?
- Checked Rec. 709, Rec. 2100 (PQ), and Rec. 2100 (HLG) file output, and media source input for ProRes 422, 4444, and 4444 XQ.
- Debugger inspection for all file diffs.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
This is ready, but merge #7850 first.

**Review by PatTheMav — APPROVED** [review]
Looks good to me.

**Comment by PatTheMav** [comment]
@RytoEX, @gxalpha - if there are no objections from your end, I'd merge this.

**Comment by gxalpha** [comment]
No objections from my side.

**Pull request merged**
