### PR TITLE
Game capture typeless textures

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Support typeless shared textures for game capture.

### Motivation and Context
Necessary for aliasing between SRGB and non-SRGB views.

### How Has This Been Tested?
Tested all APIs with new game capture DLL against branch, and 26.1.

GL, 32-bit: Counter-Strike
D3D8, 32-bit: Barkley, Shut Up and Jam: Gaiden
D3D9, 32-bit: Counter-Strike: Source
D3D10, 32-bit: Mega Man X Legacy Collection
D3D11, 64-bit: MS sample
D3D12, 64-bit: MS sample
Vulkan, 64-bit: vkcube

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
If you want me to bump version numbers, I can do that. Otherwise, I think these changes should be fine.

**Comment by jp9000** [comment]
Pretty clever, you were able to utilize an extra byte that was already there but unused due to alignment padding to fit in an additional bool.

Sure, feel free to bump the game capture version number up by one whenever you make changes to the graphics hook. I can do it this time though too though, I don't mind. Whichever is fine with me

**Comment by jpark37** [comment]
Should this be minor or patch?

**Comment by jp9000** [comment]
We don't really follow semantic versioning too tightly, it's more like "if major or potentially breaking changes increment major, if minor changes/features increment minor, if it's just a fix increment patch", so whichever you feel is most applicable. Seems like it'd be minor to me.

**Comment by jpark37** [comment]
K, I'll bump the minor version, but I'm having second thoughts about using TYPELESS. Apparently, there are performance implications: https://gpuopen.com/performance/

"Avoid using TYPELESS or MUTABLE formats on render targets, depth targets, and UAVs/storage buffers."

The feature in question is probably DCC, which is not likely to be a problem for game capture shared textures, but I had plans for the sRGB PR (#2067) to also use typeless resources for all textures, so I need to rethink both PRs now.

**Comment by jpark37** [comment]
TYPELESS textures should be fine for game capture at least, marking review as ready.

I just noticed GL was falling back to shared memory capture because it doesn't like TYPELESS. Switched it back to UNORM, and updated the commit comment.

Not sure what's going on with the Mac build.

**Comment by jpark37** [comment]
Also bumped the version up to 1.3.0

**Pull request merged**
