### PR TITLE
CI: Remove automatic annotation of macOS Apple Silicon builds

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Removes automatic annotation done by scheduled GitHub builds.

### Motivation and Context
Annotation does not work as expected on GitHub, which means that the usability of the feature is diminished if not nonexistent.

Removing the code reduces code complexity.

### How Has This Been Tested?
Needs testing on CI.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — COMMENTED** [review]
Looks fine. Are the other changes in #9529 being kept for some reason?

**Comment by PatTheMav** [comment]
Still looking into incorporating flame charts for builds which uses xclogparser. In theory it could be reverted entirely and reintroduced later, I'm open to either.

**Comment by RytoEX** [comment]
> Still looking into incorporating flame charts for builds which uses xclogparser. In theory it could be reverted entirely and reintroduced later, I'm open to either.

Do they need the additional permissions? Mostly, I'm looking to keep down additional code slipping by that we don't use/need.

**Comment by PatTheMav** [comment]
Changed the PR to consist entirely of reverts for the commits contained in the original PR that added the feature.

**Review by RytoEX — APPROVED** [review]
Looks good to me.

**Pull request merged**
