### PR TITLE
libobs: Return target instead of current in calc_torquef

### PR DESCRIPTION
**Pull request by tt2468**
### Description

If the previously calculated torque value is too close to 1.0 (but not considered 1.0), it would be impossible for the TBar to finish its transition since it returned the old value, causing desync.

### Motivation and Context

Makes TBar much more reliable

### How Has This Been Tested?

Fiddled with the TBar for a *very* long time.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
Are we certain this is a case where the API needs to change, or could this also be a situation where the usage needs to change? i.e. swap `transition->transition_manual_val` and `transition->transition_manual_target` here: https://github.com/obsproject/obs-studio/blob/5722710f0a1da1e1c10a6659739341fd54b8b975/libobs/obs-source-transition.c#L218-L219

It doesn't appear like this function is used anywhere else, but the libobs function has existed this way for 7 years whereas the calling code has only existed for 5 months. Seems like @jp9000 might need to weigh in on this.

If we do indeed end up changing the API, the commit/PR title will need to change to indicate that this is specifically fixing an implementation bug in `calc_torquef`, and note in the commit's detailed description that the motivation for this change was to fix a bug with the TBar.

**Comment by dodgepong** [comment]
Scratch that, `val1` and `val2` are treated pretty differently in `calc_torquef` so it wouldn't be a matter of just swapping them in the invocation, my bad.

**Comment by jpark37** [comment]
Should calc_torque be modified the same way?

**Comment by tt2468** [comment]
@jpark37 Depends. `calc_torque` is not used by any part of OBS.

**Comment by jpark37** [comment]
It's marked for export, so it could be used by a plugin I think.

**Pull request merged**
