### PR TITLE
win-update: Use correct winhttp proxy type

### PR DESCRIPTION
**Pull request by eebssk1**
### Description

The legacy type may not work on some setups, use new one on 8.1+  instead.

### Motivation and Context

Updater does not go through my system proxy.
The legacy type seems do not check system proxy settings throughly.

### How Has This Been Tested?

I haven't test compile the changes,but should not break since it's a rather simple change.

### Types of changes

Tweak

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by derrod — CHANGES_REQUESTED** [review]
We don't support anything below Windows 10 so you can just replace the constant, no need to overcomplicate things.

**Review by derrod — APPROVED** [review]

**Comment by RytoEX** [comment]
> We don't support anything below Windows 10 so you can just replace the constant, no need to overcomplicate things.

The updater does run on Windows 7/8/8.1, but bails out pretty early.
https://github.com/obsproject/obs-studio/blob/a9082de880adaca7d10706b3d750c9ebfddf1e2d/UI/win-update/updater/updater.cpp#L1925-L1935

I guess in this case, since these paths are never reached on those older Windows versions, the change is safe?

**Comment by derrod** [comment]
> > We don't support anything below Windows 10 so you can just replace the constant, no need to overcomplicate things.
> 
> The updater does run on Windows 7/8/8.1, but bails out pretty early.

Yeah but we don't support it, hence the bailout.

> I guess in this case, since these paths are never reached on those older Windows versions, the change is safe?

Yes. Even if it wasn't, I couldn't care less if it crashes on unsupported Windows versions.

**Comment by norihiro** [comment]
Just a nitpick,
The commit a9082de88 has a 2nd line which is not empty.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Do not use merge commits to catch up on git history. Use `git rebase`.

**Comment by eebssk1** [comment]
> Do not use merge commits to catch up on git history. Use `git rebase`.

done

**Pull request merged**
