### PR TITLE
 UI: Warn when audio track bitrate is > max streaming bitrate 

### PR DESCRIPTION
**Pull request by cg2121**
Screenshot from 2019-06-10 09-11-13
Screenshot from 2019-06-10 09-11-59

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
This should inherit the warningLabel property as well, so that it can be consistently styled across themes. See: https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-settings.cpp#L4446 and https://github.com/obsproject/obs-studio/blob/master/UI/properties-view.cpp#L1276

**Comment by cg2121** [comment]
The labels are now consistent with other warning labels.
Screenshot from 2019-07-10 23-53-05
Screenshot from 2019-07-10 23-53-05

**Comment by pkviet** [comment]
the max audio bitrate is presumably for stereo; for surround, higher bitrates are mandatory. Since Twitch supports surround sound, an additional check might be necessary.

**Comment by jp9000** [comment]
I'm fairly certain that the streaming encoder in advanced output mode now always uses an independent encoder from the recording encoders after the pause update, because otherwise it would have broken pause functionality.  So basically this PR is now redundant.

**Pull request closed without merging**
