### PR TITLE
UI: Run Autoconfig Wizard on New Profile Creation

### PR DESCRIPTION
**Pull request by JohannMG**
### Description

New profile state is similar to first start: settings are wiped, encoders not
setup. It may make sense to show the auto configuration wizard when a
new profile is made as well.

Checkbox is only shown on New profile dialog, and shown default On first run. If a profile is created with the checkbox ticked off, the checkbox will be off next time the dialog is used as well. 

Screen Shot 2020-10-29 at 11 24 19 AM

Screen Shot 2020-10-26 at 4 15 35 PM

### Motivation and Context

New profile consistency. Make the wizard configuration more visible. 

### How Has This Been Tested?

Compiled and tested on Macbook Pro, MacOS 10.15.7 

### Types of changes

- New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
I think this might work better as an option on the new profile dialog, it will reduce user dialog fatigue.

Bad example:
7pkNNeX 1

**Comment by Fenrirthviti** [comment]
I agree, with the caveat that it's enabled by default and the state is persisted for each new profile created. I.e. if it's on, it's always on, if it's off, it's always off.

**Comment by JohannMG** [comment]
I considered it, my worry is possible dialog fatigue is replaced by creating an uninformed decision point, but the wizard explains what it is.  
Will circle back to.

**Comment by JohannMG** [comment]
Added checkbox and setting memory. 
Screen Shot 2020-10-29 at 11 24 19 AM

**Comment by jp9000** [comment]
Tested, works great.

**Comment by dodgepong** [comment]
Neat. My only feedback is that I think the option should say "Run" instead of "Show", but it's not a hill I would die on. I just think "Run" is slightly more clear about what will happen when the option is checked.

**Comment by JohannMG** [comment]
@dodgepong I picked "show" to make a little more clear that nothing will automatically be set

**Pull request merged**
