### PR TITLE
flatpak: Enable obs-libfdk

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Enable obs-libfdk since Freedesktop runtime provides it.

### Motivation and Context

Enable an available feature and do some fixup.

### How Has This Been Tested?

Builds fine and obs-libfdk is correctly loaded.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Do you know if the libfak version included in the runtime is the stripped-down Fedora one?

They removed some features that their lawyers believed still were subject to patents (though they have since expired iirc) and I'm not sure if that gutted version actually still is better than frmpeg aac.

**Comment by tytan652** [comment]
Here is Freedesktop fork branch in use: https://cgit.freedesktop.org/~wtay/fdk-aac/log/?h=stripped4

> They removed some features that their lawyers believed still were subject to patents (though they have since expired iirc) and I'm not sure if that gutted version actually still is better than frmpeg aac.

I don't know either.

**Comment by tytan652** [comment]
Moved CMake change to another PR (#8461).

**Comment by derrod** [comment]
Since we now allow users to select which AAC encoder they want to use this is probably fine to merge to get some feedback during the beta.

**Pull request merged**
