### PR TITLE
UI: Add ability to style preview background color

### PR DESCRIPTION
**Pull request by cg2121**
screenshot from 2018-08-30 15-16-10

### CODE REVIEW

**Comment by jp9000** [comment]
This doesn't change the style when the user changes the style.  You can use the OBSApp::StyleChanged signal to get notified when the user does that.

**Comment by jp9000** [comment]
What do you mean?  The signal didn't fire?  It definitely fires, so I'm confused.

For example:

```cpp
connect(App(), SIGNAL("StyleChanged()"), this, SLOT("MySlot()"));
```

**Comment by cg2121** [comment]
The display color is only set during the render_display_begin function in obs-display.c, so you can't set the color when the display is in use.

**Comment by cg2121** [comment]
Never mind, I got it working now.

**Comment by jp9000** [comment]
Looking good, glad you got it working.  Seems there are some conflicts here.  Might need to be resolved first.

**Comment by cg2121** [comment]
Conflicts are now fixed.

**Pull request merged**
