### PR TITLE
CI: Enable checker for non master branch

### PR DESCRIPTION
**Pull request by TianQiBuTian**
### Description

Enable checker for non master branch.
### Motivation and Context

Before the merged of #8881, contributors were changing their code and pushing it. The checker would check if there were issues with the code and alert them via email when filling out PR information. (Assuming that the contributor's Action and email reminder are turned on)
### How Has This Been Tested?

https://github.com/TianQiBuTian/obs-studio/actions/runs/5772840234
### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
That is by design - development should not happen on the master branch, instead forks should do their development on feature-specific branches and open local pull requests to check if the changes pass CI validation.

Once development is finished, a pull request can be opened on the main fork with the same feature branch. This also ensures one of our requirements in the contribution guidelines (mainly that changes are not on the master branch).

The master branch should only be kept in sync with the upstream master branch and feature development branched off from that.

**Comment by WizardCM** [comment]
I agree with the intent in the PR. Authoring a PR can be stressful and complex enough. It can be embarrassing thinking you've gotten everything right (including formatting), only to be thrown back by CI **after** you open the PR, even though everything succeeded when you initially pushed to your fork. I disagree that this should be exclusively tested on the user's local machine, as there can be too many outside factors that influence the development environment. CI is designed to be clean and with simple intent.

**Comment by PatTheMav** [comment]
> I agree with the intent in the PR. Authoring a PR can be stressful and complex enough. It can be embarrassing thinking you've gotten everything right (including formatting), only to be thrown back by CI **after** you open the PR, even though everything succeeded when you initially pushed to your fork. I disagree that this should be exclusively tested on the user's local machine, as there can be too many outside factors that influence the development environment. CI is designed to be clean and with simple intent.

That's what a PR on the local fork is for - it will run all the checks that will be run upstream, but without the publicity of it. Once the PR's checks are all green, a PR can be opened with the same base branch upstream and because it's the same workflow, the checks should succeed all the same.

**Comment by TianQiBuTian** [comment]
This only enabled the most basic code check for other branches to detect and notify careless contributors of code formatting errors through email faster.
Although not suitable for large changes, it is suitable for minor changes, such as changing rtmp service.
It also makes https://github.com/obsproject/obs-studio/blob/release/29.1/.github/workflows/clang-format.yml return.

**Comment by PatTheMav** [comment]
Using CI runs just to run code checking during development seems incredibly wasteful to me given that many of these checks can be run locally (and _should_ be run locally) and easily has the potential to run into the allowance limits of free runners.

Formatting can be enforced automatically using pre-commit hooks  and there is even a bespoke framework for that (https://pre-commit.com) that has lots of linters and formatting checkers built-in. Using the pre-commit hook for this is the common solution to this problem, so there really is no need to abuse CI for this.

There is obviously nothing that would prohibit someone who forked the project to add their own workflow that runs checks on every push to every branch, but that is up to anyone maintaining a fork. IMO the main repo has no need for this and it's a bad practise to begin with.

**Comment by PatTheMav** [comment]
Closing this for the reasons outlined in prior comments - this change would not only affect all forks but also the main repository as well and would result in any push to any branch spinning up CI for checks. The checks are meant as a guard against merging unformatted PRs and getting failures from those checks is very common and updating a PR to pass those checks is nothing to be worried about.

**Pull request closed without merging**
