### PR TITLE
UI: Control scene item rotations with shift click

### PR DESCRIPTION
**Pull request by Andersama**
Adds ability to control rotations by shift clicking

### CODE REVIEW

**Comment by RytoEX** [comment]
This sort of addresses [Mantis 541](https://obsproject.com/mantis/view.php?id=541), but uses Shift instead of Control.

Fails to build on Ubuntu 14, Ubuntu 16, and macOS CI.

**Comment by Andersama** [comment]
I used shift because control is already being used for selecting multiple scene items, and the previous behavior of using shift to stretch w/o the aspect ratio still works you just have to hold shift after dragging.

**Comment by jp9000** [comment]
This is well programmed, but the problem I envision is that a user could use this by accident, shift a source to a non-90 degree angle by mistake, and then either they can't figure out how they did that and it stays slightly skewed, or they try to shift it back manually and it's also slightly skewed.  It's just putting more exposure to a very niche feature to users who would never actually "need" a non-90 degree angle under almost every circumstance.

See the way I *tried* to design things in the program are that the most easily accessible things are the things that are the most common/simple tasks, and the more uncommon/rare/advanced tasks are specifically not accessible without some specific purposeful effort, but still available.  That's sort of why the option to rotate to a non-90 degree angle exists within the program, but is within the transform dialog, which is more of an advanced dialog.  You need to gauge these sort of things when making a feature exposed to user:  how many people actually "need" some feature, how could said feature could have unintended consequences, and then gauge how exposed you want it to be.

Another reason why I may not accept something is due to maintenance costs.  If we have to make major changes to the preview, then we have to gauge these sort of features would need tweaking to accommodate that hypothetical change.  Grouping was a good example where maintenance costs came in to play in a very serious way, because every transform task had to be reprogrammed to accommodate group sub-items seamlessly.  There is always those sort of risks and unintended consequences that many may not always realize at first glance.

Again however, this is very well programmed and I like the way you added arrows, you just made it very well.  Please don't let my criticism and the fact that I decline here discourage you from making more features, because you are quite skilled.  It's inevitable that some will eventually be respectfully declined even despite being very well-made, just simply due to user experience concerns.  I hope you understand where I'm coming from with this.

**Comment by dodgepong** [comment]
I don't think that the ability to easily rotate a source in non-90-degree increments is niche, personally. It's a very common operation in image editing software and the UI for such a thing is very familiar to people. Oftentimes, it's represented with an extra handle sticking out from one of the middle handles on the source, with a different shape, like so:

Rotation handle mockup

Anyway, I think you may be misjudging how many users would appreciate being able to rotate a source outside the transform dialog. Rotating by typing numbers or scrolling a spindown is extremely awkward, and having a quick and easy way to rotate arbitrarily without opening the transform dialog is much better UX.

**Comment by VodBox** [comment]
As of this moment, I can think of at least one decently common one, one slightly niche one, and one super niche one.

If someone cannot get a camera to be placed somewhere level, being able to rotate it easily at non-90 angles can help to alleviate that.

Someone may wish to have a text source sit on the edge of some overlay graphic or background element.

Someone could be trying make their camera group and border match the style of a particular game's UI that has rotation or have some kind of lens distortion that makes elements look rotated.

**Comment by VodBox** [comment]
Additionally, I feel that while something like rotation indicators can have an unintended consequence that people use it when they shouldn't, producing a bad looking stream, those who don't need it and are aware they don't need it aren't exactly inconvenienced by the option being there. It doesn't take up more space and doesn't demand attention, but still gives an option to people who would make use of it.

Also, if we wanted to prevent people making bad looking streams, then scaling without respecting aspect ratio should also be hidden in the transform dialog, but instead we have a shortcut for it. For people who know what they're doing, it's useful and speed things up. For people who don't need it, they're not inconvenienced by it being an option. I feel as though rotation fits in the same space.

**Comment by Fenrirthviti** [comment]
To take care of the accidental movement, maybe a checkbox in the transform dialog to "Lock Free Rotation" would be useful?

**Comment by Andersama** [comment]
@dodgepong I think adding a handle would be nicer, especially if it was just a regular mouse click to get it going. I could go back and give it a shot.

**Comment by DDRBoxman** [comment]
Just a few thoughts:

*  Rotation should be from the center of the source and not the top left.
*  Instead of changing the drag boxes would it make sense to change the cursor to a rotation cursor?
*  In other rotate mode apps you can drag from anywhere once you are in rotate mode and not just the corners, this would make rotation easier since we are already in "rotate mode" with the modifier key

**Comment by VodBox** [comment]
@DDRBoxman The reason rotation happens from the top left, is due to all sources having the top left as their anchor point by default. Changing the alignment in transform properties will change where the rotation happens from.

**Pull request closed without merging**
