### PR TITLE
UI: Simplify FindTransition function

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This simplifies the FindTransition function by using obs_get_transition_by_name().

### Motivation and Context
Simpler code

### How Has This Been Tested?
Did stuff with transitions to make sure everything worked.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by exeldro** [comment]
obs_get_transition_by_name might get you a source transition or a transition from the Aitum Vertical plugin

**Comment by cg2121** [comment]
Transition names shouldn't be duplicated anyways. If they were, obs_get_transition_by_name might always return the wrong transition.

**Comment by exeldro** [comment]
Transition names can be duplicated as they are private sources. They are duplicated for Aitum Vertical to allow the use transition overrides on scenes.
If a source is referenced multiple times in a scene or in multiple scenes the source transitions will also have the same name.
In my opinion `obs_get_transition_by_name` should be deprecated as there is no guaranteed single transition for a name.

**Comment by gxalpha** [comment]
I vaguely remember being at fault for `obs_get_transition_by_name` existing but thought that the PR that added that was rewritten not to use it, specifically for the reasons Exeldro mentioned above; so I'm confused how it made it in (it really shouldn't have). I'll take a deeper look later.

**Comment by cg2121** [comment]
As pointed out, this doesn't work like I thought it would.

**Pull request closed without merging**
