### PR TITLE
UI: Add menu bar control widget

### PR DESCRIPTION
**Pull request by cg2121**
### Description
Move studio mode and settings buttons to top menu bar. Also added enable/disable preview and lock/unlock preview checkboxes.

Screenshot_20200519_124231

### Motivation and Context
This declutters the controls dock.

RFC: https://github.com/obsproject/rfcs/pull/12

### How Has This Been Tested?
Toggled the controls to make sure they worked as expected. I've only tested on Linux.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by skeletonbow** [comment]
Fantasic, that's a nice improvement to the UI look and feel for sure!

**Comment by emaste** [comment]
I merged this locally to test and had trouble finding the studio mode option. I finally found it, but I see it as just an unlabeled checkbox to the left of the gear settings icon.

**Comment by unknowndomain** [comment]
It would be interesting to understand how this will translate to macOS as this operating system does not have a window based menu bar.

I wonder if this is the start of an interesting idea similar to many applications like Adobe Photoshop/Illustrator and many CAD programmes.

Perhaps we need a thin dock of icons that can go down the left of the video, or be flipped and go horizontally across the top as a preference, that way you can have lots of configurable icons.

macOS already has this concept of customisable tool bars, I am not sure if there is a way to support this on all platforms?:

Screenshot 2020-05-19 at 22 15 08

**Comment by Warchamp7** [comment]
I don't think the eye and lock icon are good choices for the purpose they serve here.

Slightly off topic:
I like the idea of decluttering the Controls dock, but I think any work on that front should work towards removing the dock entirely, not just some of it. I have some ideas for addressing that but I haven't had time to add those thoughts to the RFC yet

**Comment by cg2121** [comment]
I'm planning on doing stuff to remove the controls dock completely. This is just a first step.

**Comment by unknowndomain** [comment]
Does removing the controls dock really mean rebuilding it as an Outputs Dock of some kind?

**Comment by cg2121** [comment]
Yes, possibly. I just think the stream/recording buttons should be in a more permanent place in the UI.

**Comment by cg2121** [comment]
Closing until RFC is finalized.

**Pull request closed without merging**
