### PR TITLE
UI: Redesign hotkeys interface

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This overhauls the hotkeys interface with better organization with tabs and drop downs to select the scene, source, etc. Filter hotkeys have also been added.

Screenshot from 2019-10-17 21-47-28
Screenshot from 2019-10-17 21-48-09
Screenshot from 2019-10-17 21-47-01

### Motivation and Context
Hotkeys were a mess.

Filter hotkeys:
https://ideas.obsproject.com/posts/67/allow-hotkeys-to-be-setup-for-filters

### How Has This Been Tested?
Tested by running program to see if hotkeys UI looked better.

### Types of changes
- New feature (non-breaking change which adds functionality)
- UI overhaul

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by exeldro** [comment]
I think this is a step in the right direction.

In other parts of the OBS interface groups are in the sources category, so I think I would think that should be here too.
With the filters there is no good way to see which source they belong to.
Maybe don't put filters in a tab, but show them under the source or scene they belong to.
Now if you have the same filter twice on different sources you get the enable and disable double:
image

**Comment by cg2121** [comment]
I've now redone the filters section so each source is in the drop down instead of each filter. This makes it easier to tell which source is associated with each filter.

Screenshot from 2019-10-18 13-58-25

**Comment by dodgepong** [comment]
As long as we're doing a whole redesign, can we still have a Search/Filter? Perhaps above the tabs we could still have the search box, and when you type into it, it creates a new tab called "Search Results", selects it automatically, and shows hotkeys that match the search like the current system does.

That said, I just realized the current search functionality is really weird because if you search for the name of a scene, it won't show you any of the hotkeys for that scene. For example, if I have a scene called "BRB" and I search for "BRB" in the current search filter, it will show that there is a group of hotkeys for a scene called "BRB", but it will not show me any of the actual hotkeys (including the "Switch to scene" hotkey for the BRB scene). It seems like there are a few opportunities for improvement in the search system.

Anyway, searching/filtering is still useful for people who have huge numbers of sources/scenes, as scrolling through a dropdown can be tedious. Furthermore, removing a search/filter would be removing functionality that I'm certain people currently appreciate, even in context of tabbed organization.

**Comment by ntoff** [comment]
>can we still have a Search/Filter? Perhaps above the tabs we could still have the search box,

Maybe an "All" tab, that just shows everything in the old format, with the search box in that tab. A bit like how a music app has playlists (the new tab system), and a "library", where the library shows everything

**Comment by Fenrirthviti** [comment]
Adding back all would defeat the purpose of this PR, which is that enumerating everything can take several minutes in some large and complex scene setups. Filtering should be possible without needing all, though. I like the idea dodgepong proposed, where it could have a search tab with a filter, and return results on submission of the search, rather than realtime.

**Comment by WizardCM** [comment]
I also agree the search & filter system makes sense, keep it filtered to the current tab - though I do like the sound of Fenrir's suggestion too.
The tab system is a very good way to organise the hotkeys, and overall works quite well.

A couple thoughts of my own:

* The Filters tab makes a lot more sense now. Nice work!
* Would it be worth making the dropdowns capable of having their own search? Similar to the Settings -> Video resolution fields, but when you type it filters down the contents of the dropdown with a partial search. I say this for some creators who have hundreds of scenes, which results in the Settings dialog taking minutes to even appear because Qt is generating a full list of keys.
* Looks like you've fixed the scrollbars since I first tested this, too. Excellent!
* Another discussion we had in the Discord is the idea of not showing any hotkeys by default, rather having a way to click +, choose the purpose of the hotkey, then set the hotkey. That way only entries for user-defined hotkeys appear, rather than the full list. I wonder if combining that with what you've got so far would be useful, or whether it'd just be extra cruft. Worth thinking about..

**Comment by cg2121** [comment]
I've now added the ability the search the drop down menus.

**Comment by JohannMG** [comment]
This is great! I have a lot of pain points here. 

Some thoughts I think could make this a more user-beneficial UI change: 

 - At-scene option: I think a good part of this or follow up to make the dropdown for scenes more appealing would be adding "set hotkey" and "remove hotkeys" to the scene right click menu OR a "edit hotkeys" there to keep it more compact

 - Add Clear All Button: Right now clearing all hotkeys after a set/show is important. It’s already a bit of pain going through the list and removing all but the workflow here would  additionally require going through every item in the dropdown. (Later we can maybe work on an Save Presets button.)

 - Change name of first tab: "Frontend" is a dev term, I would suggest something closer to the main use of the frontend UI like "Broadcast", "Live", "Main"

 - Logical grouping: In Can you add vertical spacers/Titles between the Streaming, Recording, Buffer, And Studio Mode settings to cluster them similar to the way that Scenes are segments by bold titles now.

**Comment by WizardCM** [comment]
Friendly bump: there are currently merge conflicts.

**Comment by Warchamp7** [comment]
Just curious: Does this overhaul allow me to set a toggle hotkey for a sources visibility in all scenes at once? Or do I still need to set it for every scene the source is in?

It's a common workflow for us and I'm a fan of any system that streamlines it

Even if picking the source in the Source tab just lists every scene it's in all in one place, that alone would make it easier

**Comment by WizardCM** [comment]
A few extra notes:
* Loading the Hotkeys tab the first time adds a scrollbar that goes away when you switch to Sources/Filters/Outputs (Hotkeys), and does not return when you switch back to Frontend/Scenes
* Said scrollbar also scrolls the tabs. Any scrollbar on this page should scroll the hotkeys themselves and not the tabs
* Switching to a Hotkey tab should auto-focus the first input within the tab

**Comment by virtunite** [comment]
Are there any plans that this is going to be added to OBS?
I would really need this.

**Comment by cg2121** [comment]
Code here is a mess and needs to be rewritten. There should also be a RFC for this as well, since it is a major change.

Closing until then.

**Pull request closed without merging**
