### PR TITLE
rtmp-services: Add GameSee

### PR DESCRIPTION
**Pull request by HimanshuMenon**
### Description
Added a new streaming service, GameSee, to the RTMP services list.

### Motivation and Context
To publish a new streaming service, GameSee to RTMP services list.

### How Has This Been Tested?
Tested by modifying local OBS json files.

### Types of changes

 New feature (non-breaking change which adds functionality) 

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
Please fill out the PR template in the description

**Comment by HimanshuMenon** [comment]
Hi, Sir/mam do I still need to fill out the PR template in the description?
If yes could ye please tell me with the screenshot exactly what I need to
fill? Thank you.

**Comment by gxalpha** [comment]
Yes, you still have to fill it out. You will have to edit the current description via the three small dots.

image

Please also confirm that you're a representative of GameSee.

Also note that per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines#general-rules--requirements), "If your service is available to the public, some adoption should be visible to warrant the inclusion in OBS". While I'm not the one to make this call, there still is the possibility that we may come to the conclusion that your service does not fulfill this requirement.

**Comment by HimanshuMenon** [comment]
> Yes, you still have to fill it out. You will have to edit the current description via the three small dots.
> 
> image
> 
> Please also confirm that you're a representative of GameSee.
> 
> Also note that per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines#general-rules--requirements), "If your service is available to the public, some adoption should be visible to warrant the inclusion in OBS". While I'm not the one to make this call, there still is the possibility that we may come to the conclusion that your service does not fulfill this requirement.

Yes, I am a representative of GameSee and what sort of adoption should I give to warrant the inclusion in OBS?

**Comment by Fenrirthviti** [comment]
I've checked this site a few times since this PR was submitted, and there hasn't been a single live stream active at any point when checking. Parts of the website are also broken/unfinished (like the VOD viewer). The site feels more like a project than an actual service as it sits right now. Please resubmit this PR once there is a level of steady adoption, and we can review it again at that time. Thanks for your understanding.

**Comment by HimanshuMenon** [comment]
> I've checked this site a few times since this PR was submitted, and there hasn't been a single live stream active at any point when checking. Parts of the website are also broken/unfinished (like the VOD viewer). The site feels more like a project than an actual service as it sits right now. Please resubmit this PR once there is a level of steady adoption, and we can review it again at that time. Thanks for your understanding.

Most of our users are mostly Indian and are active in the morning according to IST and we also have an app with the same name with approx 5,00,000 downloads. Please reconsider once.

**Comment by Fenrirthviti** [comment]
We will monitor over the next few days and if there appears to be sufficient activity, we can reconsider. If you have any other supporting evidence of adoption than an app, feel free to provide it.

**Comment by HimanshuMenon** [comment]
> We will monitor over the next few days and if there appears to be sufficient activity, we can reconsider. If you have any other supporting evidence of adoption than an app, feel free to provide it.

What type of evidence would you consider? I could give a list of streams that were done during a day on the platform.

**Pull request closed without merging**
