### PR TITLE
Remove deprecated stuff

### PR DESCRIPTION
**Pull request by derrod**
### Description

Remove a whole bunch of things that have been deprecated anywhere between 10 years and 5 months ago.

### Motivation and Context

We're bad at removing stuff. Let's be less bad and remove stuff.

Removals are grouped into separate commits so we can omit some if we think that e.g. the deprecations made in 30.1 are too recent to fully remove already.

### How Has This Been Tested?

Still compiles.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
There has been some discussion around what to do with `OBS_NIX_PLATFORM_X11_GLX`, removing it would shift the other enum values, but if we do a major bump then apparently on Linux plugins might not load anymore until recompiled against the new release so it *should* be fine?

Personally I think just keeping the values the same would be the easiest way forward though to not break anything. Alternatively we could also replace the first item with `OBS_NIX_PLATFORM_INVALID`.

**Comment by tytan652** [comment]
> Personally I think just keeping the values the same would be the easiest way forward though to not break anything. Alternatively we could also replace the first item with `OBS_NIX_PLATFORM_INVALID`.

I'm not against the idea.

> There has been some discussion around what to do with `OBS_NIX_PLATFORM_X11_GLX`, removing it would shift the other enum values, but if we do a major bump then apparently on Linux plugins might not load anymore until recompiled against the new release so it _should_ be fine?

If a clean ABI is not planned and I mean by that we only want to break plugins that use old symbols, some changes needs to be made on how the SOVERSION is handled so be closer to how Windows and macOS are handled to avoid necessary breakage.

**Comment by RytoEX** [comment]
I'm fine with most/all of these changes, though I would like to hear @GeorgesStavracas opinion on the `OBS_NIX_PLATFORM_X11_GLX` issue.

**Review by GeorgesStavracas — APPROVED** [review]
The GLX commit LGTM

**Comment by RytoEX** [comment]
> the deprecations made in 30.1 are too recent to fully remove already.

The 30.1 deprecations might be too soon to remove, but I'm open to be convinced otherwise.

**Comment by derrod** [comment]
> > the deprecations made in 30.1 are too recent to fully remove already.
> 
> The 30.1 deprecations might be too soon to remove, but I'm open to be convinced otherwise.

I don't feel particularly strongly about any of those. I can just drop those commits.

**Comment by RytoEX** [comment]
> > > the deprecations made in 30.1 are too recent to fully remove already.
> > 
> > 
> > The 30.1 deprecations might be too soon to remove, but I'm open to be convinced otherwise.
> 
> I don't feel particularly strongly about any of those. I can just drop those commits.

Let's drop the commits for removing the 30.x (30.0 and 30.1) deprecations. We can drop those in the eventual OBS Studio 32.

**Comment by derrod** [comment]
> > > > the deprecations made in 30.1 are too recent to fully remove already.
> > > 
> > > 
> > > The 30.1 deprecations might be too soon to remove, but I'm open to be convinced otherwise.
> > 
> > 
> > I don't feel particularly strongly about any of those. I can just drop those commits.
> 
> Let's drop the commits for removing the 30.x (30.0 and 30.1) deprecations. We can drop those in the eventual OBS Studio 32.

Removed them.

**Pull request merged**
