### PR TITLE
obs-text: text transform add locale and start case

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Add text transform option: Start case
Support transform accented characters.
image

### Motivation and Context
I want to make the title I get from an other program display in title case. But in code it is hard to filter out conjunctions and prepositions to make them not have capital letters. So the next best thing is to have every word start with a capital letter.

### How Has This Been Tested?
On windows x64

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dodgepong** [comment]
Thanks for this! Can you split these two changes into separate commits? One for the new feature, and one for the fix.

**Comment by jp9000** [comment]
This makes every word capitalized.  What's the motivation for this?

**Comment by exeldro** [comment]
I want to make the title I get from an other program display in title case. But in code it is hard to filter out conjunctions and prepositions to make them not have capital letters. So the next best thing is to have every word start with a capital letter.

**Comment by dodgepong** [comment]
I think it's a valid use case -- uncommon, but definitely valid. For example, suppose you have an overlay that is intended to display people's names, and the text files backing the overlay are fed from a source that always gives you names in ALLCAPS, but you want them with normal capitalization. This would allow for that without having to create some sort of automated system inbetween parsing the files.

**Comment by jp9000** [comment]
What's with the locale commit?  Everything should be in UTF8 just for the record.  `obs_get_locale()` returns the IETF language code.

**Comment by exeldro** [comment]
Per language there are different definitions for which upper case character is connected to which lowercase character.
A example is Turkey, where the upper case of "i" isn't "I".
As seen in the screenshot I tested it with the character "é", that should become "É", with towupper it does not.

**Comment by jp9000** [comment]
Ah I see, so it does take IETF language codes.  I misunderstood.  Well, whatever.  I guess we're putting another niche feature in the repo.  Wonderful.

**Pull request merged**
