### PR TITLE
win-capture: Replace CS:GO references with Counter-Strike 2

### PR DESCRIPTION
**Pull request by prgmitchell**
### Description

This replaces the compatibility message for CS:GO with one for Counter-Strike 2. As CS:GO servers are no longer online, I figured it made more sense to replace this rather than add another.

image

### Motivation and Context

CS:GO is no more, and someone mentioned this in the community discord server.

### How Has This Been Tested?

Replaced the compatibility json, loaded up CS2, made sure the message appeared as seen in the screenshot above.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by derrod — CHANGES_REQUESTED** [review]
Don't forget to increment the version in `package.json`.

**Comment by prgmitchell** [comment]
> Don't forget to increment the version in `package.json`.

Is this expected to be a separate commit or should I squash it?

**Comment by TianQiBuTian** [comment]
Suggest retaining CSGO.
Reason: Due to the immature community plugins in CS2, many community servers remain in CSGO, and players also choose to downgrade to CSGO through Steam's branch to play on CSGO's community servers.

See:
https://github.com/alliedmodders/source2mod/issues/2

(And I have already added CS2 in the #8617)

**Comment by prgmitchell** [comment]
> Suggest retaining CSGO. Reason: Due to the immature community plugins in CS2, many community servers remain in CSGO, and players also choose to downgrade to CSGO through Steam's branch to play on CSGO's community servers.
> 
> See: [alliedmodders/source2mod#2](https://github.com/alliedmodders/source2mod/issues/2)
> 
> (And I have already added CS2 in the #8617)

I did not realize you had an open PR, I had not seen one recently and didn't consider someone had opened one that long ago considering CS2 just officially released. I think your PR covers this, I will close this once yours is merged as it sounds like it is good to go from the comments on your PR.

**Comment by prgmitchell** [comment]
Closing as #8617 has been merged

**Pull request closed without merging**
