### PR TITLE
obs-ffmpeg: Fix logic in one of the AMF preset fallback checks

### PR DESCRIPTION
**Pull request by rhutsAMD**
### Description

There was a typo in the last change to the AMF quality preset fallback logic. This change fixes that typo.

### Motivation and Context

This is needed to fix a typo in the earlier PR #9034.

### How Has This Been Tested?

Tested on Windows 10 with an AMD Radeon RX 7900 XTX.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please use the word "logic" instead of "typo". I think the word typo is a bit too simplified here.

**Comment by rhutsAMD** [comment]
> Please use the word "logic" instead of "typo". I think the word typo is a bit too simplified here.

Thanks, I updated the commit message and title

**Comment by RytoEX** [comment]
This seems okay as-is. I would still like some elaboration in the future, per [my comment](https://github.com/obsproject/obs-studio/pull/9034#issuecomment-1592029842) on #9034.

**Review by RytoEX — APPROVED** [review]
Looks okay.

**Pull request merged**
