### PR TITLE
UI: Add option to automatically delete autoremux files

### PR DESCRIPTION
**Pull request by gxalpha**
*Edited to reflect newest version of this PR*

### Description

Adds a setting to Advanced that lets OBS automatically move recordings
to trash after being autoremuxed. Requires autoremux to be enabled as
well as QT 5.15 (and the OS to have a trash).

Screenshots:
image
image
image

### Motivation and Context

Autoremux is a great feature for anyone who wants to record MP4, but still wants to be safe of recordings being corrupted.
Unfortunately, it leaves you with a recording folder looking like this:
image
Besides being unpleasing to work with, the storage required on your hard drive is doubled if you don't always delete the original file yourself.
This is a QOL change making it easier (and maybe a little more appealing) to use autoremux and not record directly to MP4, since the result is the same - an MP4-File. The difference would be that well, your protected against corruptions.

### How Has This Been Tested?

macOS 12, Intel

If the option is selected, once the recording is ended, the MP4 gets created and the (in my case) .mkv moved to the trash bin, leaving only the MP4.
If the box is not ticked, both files will stay, as they currently do.
If autoremux is disabled all together, the checkbox is greyed out, but will remember its state.
Manual remux isn't affected by this change, as expected.

While I can't test Windows and Linux, it should behave the same since only QT functions are used.
With QT older than 5.15, the option shouln't be available in the first place.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
The main reason we don't already have this option is that there's currently no way for OBS to be sure that the remux was fully successful. I'm not sure if that's still a concern, or whether there's some extra code that could be written to validate the file once the automatic remux is completed before deleting the original.

**Comment by Fenrirthviti** [comment]
I'm personally against this unless a way can be found to validate that the remux completely successfully, and the resulting file is not corrupt.

**Comment by notr1ch** [comment]
How about moving it to the recycle bin or equivalent pending-delete storage?

**Comment by RytoEX** [comment]
> 
> 
> I'm personally against this unless a way can be found to validate that the remux completely successfully, and the resulting file is not corrupt.

I agree with @Fenrirthviti on this.


> 
> 
> How about moving it to the recycle bin or equivalent pending-delete storage?

This might be an acceptable middle ground, though then storage is still being used on disk, and I fear most users will just empty the bin without checking the remuxed file.  Not sure.

**Comment by TeroKeso** [comment]
MKV autoremove is maybe too risky, but one solution for clogging up one folder with MKV and mp4 is to have a way to move MKV to a different folder. In educational environments where you have a different tier of storage, you could save MKV "somewhere else" and use good secure storage for mp4. 

Maybe not full-on function of OBS but the unpleasing view has moved some of the people to just strait to write to mp4. A little bit out of the topic but is in the same line of motivation.

**Comment by gxalpha** [comment]
There actually is a result that is passed to the remuxFinished function that I think could be used. I just didn't notice it since for autoremux, it got ignored (which is an issue in itself that should get addressed).
https://github.com/obsproject/obs-studio/blob/a9352985c797a3a0fe75ae8ba89013f30dc4b5ab/UI/window-remux.cpp#L923

here's a log with me recording at 1000000 Kbps to make my drive run full, and indeed it fails and sets success to false (See the `Remux successful:` lines I added in the remuxFinish function).
https://obsproject.com/logs/HTByoP-E7T6Xc1zC

I'm not 100% convinced though - when I yesterday tried to get an error out of it by throwing an mkv file I purposefully corrupted at it, no errors occurred. I guess from FFMPEGs side everything went correctly?
(I tried to throw errors this way yesterday and only came up with the idea of running out of storage today, which is why I'm bringing all this up only now and not earlier).

The question here is whether were trusting FFMPEG to report the truth - yesterday I was about to close this PR since I couldn't get it to error, now that I know that in the event of an error, it gets reported, I personally feel pretty confident.
I think we can ignore the issue of not erroring on corrupt files, since OBS not producing corrupt files is the main goal of recording to mkv, so that shouldn't happen (and if the mkv file is corrupt, not deleting it won't save it anyways).

Other thoughts? (If you happen to agree, I'd add that check)

**Comment by Fenrirthviti** [comment]
I'm making an executive call to decline this at this time. Thank you for the work and for all the discussion, but this isn't really a problem we should be solving in OBS. There's plenty of tools and other methods for managing your filesystem outside of OBS, and this is just too dangerous and risky to include as a programmatic feature inside OBS. Not only can we not be super confident a remux completed successfully, from what I can tell we can't even validate if the file was successfully deleted, and this probably breaks if someone has the recycle bin disabled, etc. etc.

**Comment by gxalpha** [comment]
A little sad since I thought most of those things were sorted out, but ultimately understandable since there always is a risk. Maybe I'll write a plugin or script or something

**Pull request closed without merging**
