### PR TITLE
UI: Fix undo stack uninitialized ui warning

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Fix this warning by ~~turning~~ moving `undo_s` after `ui` in the class definition. ~~into a pointer and initialized it inside `OBSBasic` constructor~~.

```
obs-studio/UI/window-basic-main.cpp: In constructor ‘OBSBasic::OBSBasic(QWidget*)’:
OBS/obs-studio/UI/window-basic-main.cpp:231:41: warning: member ‘OBSBasic::ui’ is used uninitialized [-Wuninitialized]
  231 |         : OBSMainWindow(parent), undo_s(ui), ui(new Ui::OBSBasic)
      |                                         ^~

```

### Motivation and Context

Just remembered that this warning was there and wanted to get rid of it.

### How Has This Been Tested?

Tried to use Undo/Redo feature and no issue.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
An alternative fix is to move the definition of `undo_s` below that of `ui` since they are initialized based on the order in the class.

**Comment by tytan652** [comment]
> An alternative fix is to move the definition of `undo_s` below that of `ui` since they are initialized based on the order in the class.

Will retest, but I remember trying this and did not work.

**Comment by tytan652** [comment]
I didn't about the definition order, I tried to keep `ui` at the end of the class definition.

**Comment by RytoEX** [comment]
Is there any particular reason to take the approach here over the patch that @notr1ch linked to?

**Comment by tytan652** [comment]
> Is there any particular reason to take the approach here over the patch that @notr1ch linked to?

I just thought that `ui` was purposely put there for some reason.

**Comment by RytoEX** [comment]
If @notr1ch is sold on this, then this looks good to me.

**Pull request merged**
