### PR TITLE
CI: Add LAME/MP3 to ffmpeg

### PR DESCRIPTION
**Pull request by Jamie0**
### Description
This change includes the LAME/MP3 codec. All patents relevant to this codec expired in April 2017, so I don't believe there should be any issue including MP3 codecs in builds of OBS. 

### Motivation and Context
I work with many small and not-for-profit radio broadcasters, who are adapting to work from home. In particular, a lot of these users are Mac users, and the majority of radio broadcasting software (especially free ones) are Windows specific. Currently, OBS doesn't build the LAME encoder in its embedded ffmpeg build. As a result, it's not possible to use ffmpeg in OBS to stream up to, for example, an Icecast server. Indeed one can achieve it with other formats, but compatibility issues with older internet radios, which are (annoyingly) still very common, mean that Icecast and MP3 are very much still the living standard. 

### How Has This Been Tested?
I have tested this on macOS, but I don't currently have the capacity to test this on Windows or other platforms. This PR adds codecs to those build scripts, I'd appreciate any changes/help mirroring these on Windows and other platforms. 

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Once CI finishes, test builds should be available for this PR.

**Comment by WizardCM** [comment]
Please check the contributing guidelines and correct your commit title (with a CI prefix).

I second that this is an appropriate change.

**Comment by RytoEX** [comment]
We no longer actually use these files for CI.  The work on scripts to pre-build dependencies has moved to https://github.com/obsproject/obs-deps.

**Comment by PatTheMav** [comment]
Added to obs-deps as part of https://github.com/obsproject/obs-deps/pull/35.

**Pull request closed without merging**
