### PR TITLE
linux-pipewire: Provide the parent_window identifier to the portal

### PR DESCRIPTION
**Pull request by Sodivad**
### Description
Send the parent_window specifier as described in https://flatpak.github.io/xdg-desktop-portal/#parent_window
On X for this the window id is used. on Wayland a handle
acquired from the compositor via the xdg-foreign protocol.

### Motivation and Context

This enables the system to associate any windows/dialogs opened
by the portal with the OBS main window. For example positioning
them on/near the OBS window instead randomly somewhere on the
screen.

### How Has This Been Tested?

Tested on Plasma Wayland,  the portal dialog is not placed somewhere randomly but on top
of obs.

### Types of changes

 - Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Sodivad** [comment]
Can I see why the cmake-format check failed somewhere? 
When I run the script on my machine it doesn't complain

**Comment by WizardCM** [comment]
Forgive me as my Linux knowledge (especially around Pipewire) is limited, but this seems like a lot of work to just grab the parent window. I think it'd be worth attempting a method that doesn't require importing Qt Widgets unnecessarily.

**Comment by Sodivad** [comment]
>Forgive me as my Linux knowledge (especially around Pipewire) is limited, but this seems like a lot of work to just grab the parent window. I think it'd be worth attempting a method that doesn't require importing Qt Widgets unnecessarily.

That's fair. On X the winId is enough (aka `obs_frontend_get_main_window_handle`), but on Wayland need to access somehow the `wl_surface` of the window.

**Comment by GeorgesStavracas** [comment]
The reason I have decided against this in the past is that this is a massive layering violation; qt-wayland itself should implement this protocol, and there should be explicit APIs on Qt side that we can use from `obs_frontend_get_main_window_handle`.

**Comment by RytoEX** [comment]
> The reason I have decided against this in the past is that this is a massive layering violation; qt-wayland itself should implement this protocol, and there should be explicit APIs on Qt side that we can use from `obs_frontend_get_main_window_handle`.

I agree with this, and I would rather work went into Qt on this issue by anyone interested in getting this resolved.

**Comment by Sodivad** [comment]
FWIW I have also a MR to implement for Qt to implement xdg-foreign when it uses portals itself. Once that's in we can  probably figure out a way to access it.
https://codereview.qt-project.org/c/qt/qtwayland/+/400122

**Comment by GeorgesStavracas** [comment]
We've discussed the changes in this PR, and I think the approach taken here is not ideal, in the sense that this is a layering violation. Once the appropriate APIs land in Qt, I'd love to see a PR passing the parent_window handler using that. For now, let's keep an eye on the progress of the Qt contributions you've linked in here.

Thanks for your contribution, looking forward seeing your next ones! :slightly_smiling_face:

**Pull request closed without merging**
