### PR TITLE
obs-qsv: Enable HW scaling

### PR DESCRIPTION
**Pull request by brittneysclark**
Enabled the option to use HW scaling with Media SDK VPP

### CODE REVIEW

**Comment by pkviet** [comment]
could you give more detailed explanations as to what this commit (and the others you offered) do ? It would help the reviewing from Jim and other devs.

**Comment by brittneysclark** [comment]
Sure, @pkviet. 
This PR will improve performance and reduce CPU load. This is achieved by offloading scaling operations to HW (fixed function block) on iGPU and removes memory copies to GPU.

**Comment by cristisilaghi** [comment]
@brittneysclark I've tried this PR, but it seems I cannot check "Use HW Scale" in Streaming tab, but in Recording tab I can (seems useless, the tick seems to not get remembered). Perhaps incomplete PR?

**Comment by cristisilaghi** [comment]
Oh, this works only for QuickSync, my bad.

**Comment by jp9000** [comment]
Hi there Brittney, you'll have to forgive me, but this PR has a number of issues:

1. You are adding a whole lot of code to improve a niche feature for when a user only has a specific hardware/software configuration.  The use-case for this particular PR is narrow:
    - They must be using the "rescale" feature, which is in advanced output mode, which by itself, is a niche feature that is only used in certain specific use-cases (when a user wants to stream and record at the same time, but with different resolutions).
    - They must be using QuickSync with that output that's using the "rescale" feature.
1. Your changes comprise of a number of related, though separate changes in a single commit:
    - Updating libmfx should probably have been a separate commit, likely the first commit
    - Adding support for hardware rescaling to libobs should probably have been a separate commit, likely the second commit
    - Adding support for hardware rescaling to the UI probably should have been a separate commit, likely the third commit
    - Updating obs-qsv should probably have been the last commit.
1. In your main code changes, you sometimes used spaces instead of tabs.  This is partly my fault because I do not have clang-format support yet.  When I add clang-format support, this process will be mostly automated for you.  So you don't have to stress on that too much.

The reason why I don't want to merge this PR is mostly because I think it's an overkill change to already niche feature, and requires using QSV, which while not niche, is not quite as common.  It's a useful change for that specific niche case, but I don't feel that the work put in here is really necessary.  So my line of thinking is because this feature and this hardware combination is so niche and uncommon, I would rather you learn from the issues above, and spend time focusing on more important tasks and more important PRs.  This is also partly due to the fact that I do not want to spend time fixing this PR myself due to time constraints, and would rather you not spend time on it either.  This particular feature is not worth spending time on for anybody.

**Pull request closed without merging**
