### PR TITLE
deps/media-playback: layout converted by AVChannelLayout mask

### PR DESCRIPTION
**Pull request by wanhongqing123**
### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by wanhongqing123** [comment]
get audio layout by AVChannelLayout mask.

**Comment by WizardCM** [comment]
Please fill out the full PR template.

**Comment by wanhongqing123** [comment]
你的邮件已收到，我会尽快的回复你

**Comment by pkviet** [comment]
yes please fill the template. It's unclear to me what's being solved by that PR

**Pull request closed without merging**
