### PR TITLE
CI: Use xcrun notarytool instead of xcnotary

### PR DESCRIPTION
**Pull request by norihiro**
### Description

This PR replaces the third party tool `xcnotary` with Apple's `xcrun notarytool`.

The command `xcnotary precheck` implements these check points. However there is no equivalent steps provided by notarytool so that the checks are omitted. Though the checks are omitted, at least some of them are checked on the notarization server so that it should not be a critical issue.
- DeveloperIdCheck
- HardenedRuntimeCheck
- NoGetTaskAllowCheck
- SecureTimestampCheck

### Motivation and Context

`xcnotary` is discontinued since Apple now provides `xcrun notarytool`. See their README.md for details.
https://github.com/akeru-inc/xcnotary

### How Has This Been Tested?

Run the flow with my own credential and confirm the notarization succeeded.
https://github.com/norihiro/obs-studio/actions/runs/2761096817

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by PatTheMav — APPROVED** [review]
Changes look fine by themselves.

**Comment by PatTheMav** [comment]
Very convenient - you should also remove the installation of Xcnotary on the system if it's not needed anymore (it's either part of the Brew environment or added in some other dependency installation check).

**Comment by RytoEX** [comment]
> Very convenient - you should also remove the installation of Xcnotary on the system if it's not needed anymore (it's either part of the Brew environment or added in some other dependency installation check).

As far as I can tell, the only place in our scripts that tries to install xcnotary is in `CI/macos/03_package_obs.sh`. That section is already removed in this PR.

What is the reason that this is draft?

**Comment by norihiro** [comment]
I was looking for how I can test the notarization and stapling with the package but couldn't find. However the log says `The staple and validate action worked!` so that it should be ok.

**Review by RytoEX — APPROVED** [review]
Looks okay at a glance. Will leave to @PatTheMav to merge.

**Comment by PatTheMav** [comment]
Worked fine locally, got a fully notarised app bundle.

**Pull request merged**
