### PR TITLE
libobs: Fix format wide characters on windows

### PR DESCRIPTION
**Pull request by GkvJwa**
### Description

Fix printf wide characters on windows(zh)
vsnprintf cannot format wide chinese characters(1 char has 2 bytes usually)

can also be used setlocale(LC_ALL, ...) to support wide char*
but it's not clear if there are other effects
### Motivation and Context

The log is found in the windows environment(zh) as follows:
12:37:44.371: Sec. Software Status:
12:37:44.372: 
12:37:44.372: 
12:37:44.373: Current Date/Time: 2022-11-10, 12:37:44
Then I read the code and found that vsnprintf goes to format wide characters and utf8 strings at the same time
But if it contains wide chinese characters, vsnprintf will return -1 
### How Has This Been Tested?

Checked that the log analyser continues to correctly read the Windows version
### Types of changes

Bug fix (non-breaking change which fixes an issue)
### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Could you please provide a log from before and after these changes?

**Comment by GkvJwa** [comment]
> Could you please provide a log from before and after these changes?

Of course, but it will take some time
Can Take a look at this unittest first:
[test.zip](https://github.com/obsproject/obs-studio/files/9996457/test.zip)

**Comment by GkvJwa** [comment]
> Could you please provide a log from before and after these changes?

here is log before and after
[log.zip](https://github.com/obsproject/obs-studio/files/10020424/log.zip)

**Comment by GkvJwa** [comment]
When debugging due to wgc capture failure, I found that the log was not printed in Chinese environment. Check the code because the api failed(Maybe if we had a log we'd know more quickly what's causing it).So that's how this pull came about
But I didn't get any feedback after I provided the log and decided to close it.

**Comment by RytoEX** [comment]
PRs are reviewed as time allows. I have been busy this week and have not had time to circle back around to this. In the future, I'd ask for a little more patience. Thank you for your understanding.

**Pull request closed without merging**
