### PR TITLE
image-source: Move checkboxes to playback mode setting

### PR DESCRIPTION
**Pull request by derrod**
### Description

Changes image slideshow properties to use a combobox (displayed as radio buttons) for the playback mode to make it more obvious that "randomize" and "loop" are mutually exclusive.

screenshit

### Motivation and Context

Users get confused, e.g. #9342

### How Has This Been Tested?

Checked that settings get set and migrated correctly.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by GeorgesStavracas — COMMENTED** [review]
UI / UX review:

 * Rename "Random" to "Shuffle"
 * Use a combo box

**Comment by derrod** [comment]
Also needs to be updated now that #10088

**Comment by derrod** [comment]
Updated for Mk.2

**Comment by cg2121** [comment]
I still have a couple of problems with it.
- Shuffle and random are two completely different things
- Shuffling is reordering the list of images in a random order, and they can only be shown once when going through the list of images
- Random is picking a image randomly out of the list, and in theory the same image can be twice in a row
- It should be like the VLC source where it uses a shuffle and has the ability to loop independent of that
- The slideshow source currently uses random selection and not shuffle

**Comment by derrod** [comment]
Renamed back to "Random" because that's what it is.

**Comment by Jacien** [comment]
Out of curiosity, the playback mode "Random" no longer loops a slideshow, it just plays it once and ends.  Curious if this is related to it.

**Comment by Fenrirthviti** [comment]
Unrelated, that was a known issue that has a pending fix already: https://github.com/obsproject/obs-studio/pull/11629

**Pull request merged**
