### PR TITLE
rtmp-services: Rebranding Utreon to Playeur

### PR DESCRIPTION
**Pull request by Laurinmueller190507**
### Description

Rebranding Utreon to Playeur

### Motivation and Context

Rebranding Utreon to Playeur

### How Has This Been Tested?

Manually applied the json entry to my local installation.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
You should also add an entry to `alt_names` to avoid breaking existing setups.

**Comment by Laurinmueller190507** [comment]
> You should also add an entry to `alt_names` to avoid breaking existing setups.

@notr1ch done. THX

**Comment by norihiro** [comment]
Shouldn't we have incremented `version`?

**Comment by notr1ch** [comment]
Yeah. We really need a services PR validator :(.

**Comment by DeepDiver1975** [comment]
Which version are you referring to? The version in package.json has been incremented. THX

**Comment by norihiro** [comment]
The PR was correct but another PR was merged first as 5ad60809. When this PR was merged as 3ac08303b54, the version number was not incremented.
The usual validator would not be able to catch this because the validator runs when a PR is made or a new commit is pushed to the PR branch.

**Comment by Lain-B** [comment]
Yea, I should have rebased the branch first before merging, the original diff did have a version change but when rebased the version change was automatically removed it seems. My apologies.

**Pull request merged**
