### PR TITLE
UI: Add option to invert polarity of Audio

### PR DESCRIPTION
**Pull request by PicoCentauri**
Adds the ability in the advanced audio options to invert the polarity of an audio source.

### CODE REVIEW

**Comment by TheMuso** [comment]
I had to google what reversing the polarity of audio was... Seems that it is similar, if not the same to inverting phase. Maybe referring to it as affecting the audio phase would make it more explanable to more people.

Secondly, I think this should also have setter/getter functions, similar to almost all other advanced audio controls, mute, volume, monitoring type, etc.

Finally, a quick glance, and I found the below hunk.

@@ -2624,6 +2635,11 @@ static void process_audio(obs_source_t *source,
 
 	if (!mono_output && (source->flags & OBS_SOURCE_FLAG_FORCE_MONO) != 0)
 		downmix_to_mono_planar(source, frames);
+		//printf("%s audio mono\n", obs_source_get_name(source));
+
+	if ((source->flags & OBS_SOURCE_FLAG_INVERT_POLARITY) != 0)
+		invert_polarity(source, frames);
+		//printf("%s audo inverted\n", obs_source_get_name(source));
 }
 
 void obs_source_output_audio(obs_source_t *source,

Seems you forgot to remove some commented out debug printf statements.

If you want to leave them in there, libobs does have facilities for debug logging, maybe you could use those.

**Comment by PicoCentauri** [comment]
@TheMuso Sorry to correct you but inverting the phase makes no sense. You can shift the phase by some specific value and you get the same result as for inverting the polarity. If you want you can take a look at [this link](https://www.justmastering.com/article-phase-and-polarity.php). But if its more clear we can call it "Polarity/Phase invert".

I'm not sure if I get you point correctly but currently its just a flag like `OBS_SOURCE_FLAG_FORCE_MONO` which can be set.

No you are right I forgot to delete the print statements, should be fixed.

**Comment by TheMuso** [comment]
I don't mind being corrected. Like I said, I googled it, and it was a quick google. and without reading a lot more, I couldn't be sure what I read was accurate anyway.

In terms of setters/getters, I am thinking from a consistancy point of view, but I guess calling obs_source_set_flags with appropriate flags is ok.

**Comment by jp9000** [comment]
Why specifically do you want to invert the polarity?  I could understand this in say music where you could have situations where specific audio is phasing each other out, but in recording/streaming?  Please explain in detail your use case.

**Comment by jp9000** [comment]
Alrighty, I don't mind adding this if you really want just as long as it's contained to the advanced audio properties and doesn't use extra CPU usage when off.

Seems there's a bit of a conflict on this though.  Are you willing to resolve the conflict?  If you're not experienced wit hthis and worried about losing work, remember you can always duplicate a branch to back up your previous changes.  Or if you need help let me know.

**Comment by PicoCentauri** [comment]
No there is no extra Cpu usage if its turned off.

I tried to fix the conflicts and get the branch up to date. I don't know if this is correct since it involves all the latter commits...

**Comment by pkviet** [comment]
@PicoCentauri you need to rebase; it's definitely wrong to have all these commits in your PR.
First go back in history: git reflog ==> spot the hash you want to go back to (before all your current operations), git reset --hard hash (the hash you spotted)
Then git fetch upstream (if upstream is the name for obsproject/obs-studio remote ), git rebase -i upstream/master

**Comment by PicoCentauri** [comment]
@pkviet awesome! Thanks for the hints. I rebased the changes and now it should work.

**Comment by jp9000** [comment]
I actually decided to modify this and make it a filter instead -- that way it reduces clutter in the advanced audio properties, and allows the user to choose where in the filtering process you want to invert polarity.  See commit 7cfbdcf.

**Comment by PicoCentauri** [comment]
I'm totally fine with this. Still the advanced audio properties are really crowded and probably hard to find for new users. But this a topic for the future I think.

**Pull request merged**
