### PR TITLE
rtmp-service: for dacast display encoder key label

### PR DESCRIPTION
**Pull request by mediamagic-dev**
### Description

For Dacast display Encoder Key label instead of Stream Key label

### Motivation and Context

Dacast provides Encoder Key to users, which is then used to fetch the Stream Key, username, password, and RTMP url. Stream Key Label would create confusion

### How Has This Been Tested?

Made sure Encoder Key Label is displayed only for Dacast, for the rest Stream Key label is displayed. Validated all translations are displayed correctly

### Types of changes

UI tweak

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by bershanskiy** [comment]
@mediamagic-dev Where did you get translations for `Basic.AutoConfig.StreamPage.EncoderKey`? I looked over two languages I'm familiar with and translations make no sense. Note that you don't have to add translations yourself, OBS uses Crowdin here:
https://crowdin.com/project/obs-studio

**Comment by WizardCM** [comment]
For languages other than en-US, translations are added via Crowdin and will overwrite your text. Please remove those.

Additionally, we generally do not recommend using additional terminology if it's possible to avoid. This is not me denying your PR, just a side note.

**Comment by mediamagic-dev** [comment]
@WizardCM, by `remove those` do you mean to keep it blank or remove the entry altogether

**Comment by mediamagic-dev** [comment]
@WizardCM removed languages translation other then en-US

**Comment by RytoEX** [comment]
> Additionally, we generally do not recommend using additional terminology if it's possible to avoid. This is not me denying your PR, just a side note.

We've previously rejected changes like this, so this would be an uphill battle.
https://github.com/obsproject/obs-studio/pull/2838#pullrequestreview-438353110

It introduces yet more service-specific code which is an additional maintenance burden to us.

**Comment by lmbsht** [comment]
@jp9000 just a quick follow-up per our email discussion so your team can move forward with merging this PR. Let me know if you need anything else.

**Comment by Fenrirthviti** [comment]
@lmbsht In the future, please do not email maintainers directly for discussion regarding pull requests. Use the public communication channels.

**Pull request merged**
