### PR TITLE
obs-ffmpeg: Additional NVENC parameters+VBR fix

### PR DESCRIPTION
**Pull request by Dusre**
This adds couple missing features of NVENC and fixing VBR max rate limit.

clean

(Should be now much cleaner and simpler then my previous implementation.)

### CODE REVIEW

**Comment by jp9000** [comment]
Hi, did you read my prior message about this?

**Comment by Dusre** [comment]
Yes i fixed those things in here.

**Comment by jp9000** [comment]
In my response in your previous pull request, what I had tried to say was that I preferred these to be an extra opt string property, similar to x264's "x264opts", which you would then feed in to FFmpeg, instead of being new extra properties for each FFmpeg property at this point.  I think that would be the most extensible course of action to take in this case.

Additionally, it seems the code in this pull request hasn't been compiled or tested before being submitted, as it fails to build.

**Comment by Dusre** [comment]
The thing is that same argument could be made for why there is options for Level, Profile and Preset. Especially Level i would say that doesnt benefit 99.9% users which Spatial AQ and others would but i guess you have made your mind.

**Pull request closed without merging**
