### PR TITLE
[WIP] UI: Add headphone checkbox to mixer + Refactoring

### PR DESCRIPTION
**Pull request by Himura2la**
I based my work on the #1253 and performed a refactoring in order to get rid of the `monitoring_type` struct, because it does not reflect the UI anymore.

Also I find it very dangerous to hide the stream muting checkbox into the context menu, because it never shows that the stream is muted.

I prepared two versions:

1. In this one, the `source->user_muted` behavior differs: in the `OBS_MONITORING_TYPE_MONITOR_ONLY` state the `source->user_muted == true`.
But seems like it works with [the following changes](https://github.com/Himura2la/obs-studio/blob/headphone-checkbox/libobs/obs-source.c#L1310). 
2. The second version introduces another field `source->display_muted`, which strictly follows the checkbox, and [this code](https://github.com/Himura2la/obs-studio/blob/virtual-mute/libobs/obs-source.c#L1301) behaves as expected without affecting the original states of the `source->user_muted`. But I don't like the idea of [creating a new virtual state](https://github.com/Himura2la/obs-studio/blob/virtual-mute/UI/volume-control.cpp#L77), this code looks bad IMHO.

It's WIP because the [monitoring on Stinger transition](https://github.com/Himura2la/obs-studio/blob/headphone-checkbox/plugins/obs-transitions/transition-stinger.c#L73) does not work for some reason. I think I need help with this.

I didn't follow the commit messagges conventions, because I expect them to be squashed.

### CODE REVIEW

**Comment by jp9000** [comment]
Hi.  You appear to have created another PR that modifies and existing PR that hadn't been merged yet.

I realize now that you commented on the other PR that you were going to "PR in to this PR".  It probably would have been more ideal to discuss changes with @cg2121 rather than necessarily attempt to correct his changes with another PR right away.

Additionally, I believe this should probably have been a PR in to @cg2121's fork rather than a fork to the master repository (at least if github gives the option).

**Comment by cg2121** [comment]
He did make a PR to my repo here: https://github.com/cg2121/obs-studio/pull/2
I wasn't sure what to do with it though because it made modifications to libobs, and significantly changed the monitoring type code. @jp9000 what are your thoughts on the libobs changes?

**Comment by cg2121** [comment]
@Himura2la I repopened your PR on my repo again, so you can push to that one instead. Sorry for all of the confusion.

**Comment by jp9000** [comment]
I don't agree with changing API, regardless of whether or not the original API being changed is flawed.

**Comment by Himura2la** [comment]
OK, in this case, my code is not useful. I'll try to fix the **stream muting checkbox inside the context menu** issue without affecting the libobs API. I did not know someone uses it separately from the UI

**Comment by Himura2la** [comment]
By the way, the original question about `source->user_muted == true` still exists. I reworked my code in order to preserve the API, but there's still two ways. I chose my favorite -- the one that changes the original satates

https://github.com/cg2121/obs-studio/pull/2/commits/20c283016043bad06bf7081c9f8d76d87e2e9543#diff-dacc5c76347b805359fc1792c222b324R1310

**Comment by jp9000** [comment]
Perhaps I got a bit tunnel-visioned on the API changes -- why specifically do you want to mark it as muted in that state?  To communicate to the user that the source itself is muted?

**Comment by Himura2la** [comment]
@jp9000 I want it very much. The only reason is that I don't know about possible side effects. I changed only one condition with respect to the monitor-only situation and it somehow works. If it's OK, the code is perfect.

**Pull request closed without merging**
