### PR TITLE
UI: Fix Auto-Config Wizard for custom server with no stream key

### LINKED ISSUE #10087: Auto-Configuration Wizard with custom Server but no Stream key Next option greyed out
### Operating System Info

Other

### Other OS

NixOS

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/Y08WKduNR25HD45b

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

I expect to be able to run the Auto-Configuration Wizard with a custom server with no authentication.

### Current Behavior

When Custom is selected in the Auto-Configuration Wizard but your Server doesn't use a stream key then you can't proceed with the Wizard

image

adding a dummy auth key makes the wizard fail

### Steps to Reproduce

1. Open Wizard
2. Select Custom
3. Enter Server URL
4. Next Button greyed out

### Anything else we should know?

my log is from NixOS but this also happens on Windows and other distros

### PR DESCRIPTION
**Pull request by mar10iana**
### Description
The issue reported on GitHub involves the OBS Studio Auto-Configuration Wizard becoming non-functional when a custom server is selected without requiring a stream key, preventing further progress. To address this, I included the !custom constraint in the if condition within the UpdateCompleted() function, aiming to handle cases where a custom server is used without a stream key, thereby allowing the wizard to proceed as expected.

### Motivation and Context
This change improves the user experience in OBS Studio, especially for those utilizing custom streaming services. It solves the problem outlined in this issue: [obsproject/obs-studio#10087](https://github.com/obsproject/obs-studio/issues/10087), where the setup wizard would inaccurately report readiness due to not considering custom services without a provided stream key.

Fixes #10087

### How Has This Been Tested?
This has been tested using a macOS environment.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by mar10iana** [comment]
Thank you! I will make those changes now

**Comment by mar10iana** [comment]
I've updated the PR template and commit message. Please excuse any oversights, as this is my first contribution. If there's anything else that needs adjustment or inclusion, I'll address it as soon as possible. Thank you!

**Review by RytoEX — CHANGES_REQUESTED** [review]
This does seem to fix the issue as described.

Commit message nit:
* Use a verb as the first word after the prefix

I have provided a commit message that addresses that nit and clarifies the reason for the change:
```
UI: Fix Auto-Config Wizard for custom server with no stream key

The Auto-Configuration Wizard cannot progress when selecting a custom
service that does not require a stream key. Since we have no way to
validate if a custom service requires a stream key, we should just not
require a stream key is custom service is selected. To fix this, check
if a custom service has not been selected when checking if the stream key
is empty.
```

**Comment by mar10iana** [comment]
Thank you! Do I squash the previous commit?

**Comment by mar10iana** [comment]
Thank you! Do I squash the previous commit?

**Comment by mar10iana** [comment]
Thank you! I have update the commit and the title of the PR

**Comment by norihiro** [comment]
In the commit message, the line
`if a custom service has not been selected when checking if the stream key`
contains 73 characters. Please fold between `stream` and `key`.

**Pull request merged**
