### PR TITLE
UI: Remove Twitch from MultichannelWarning message

### PR DESCRIPTION
**Pull request by IainCole**
Remove Twitch from the list of supported platforms for multichannel audio.

Not all Twitch clients support the playback of multichannel audio, so we should remove Twitch from the warning here until such time that it is supported.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
For future reference purposes, can you list which clients do and which do not?

**Comment by IainCole** [comment]
The iOS client can't play back streams with multichannel audio. I'm not 100% sure about others, but we'll need to do a full test of everything again.

**Comment by pkviet** [comment]
Why not list the platforms where surround is supported by Twitch ? On desktop players, surround worked last I checked. Didn't think of checking on smartphones to be honest. I'll recheck at least on desktop.

**Comment by Fenrirthviti** [comment]
I agree. Adjusting the message to exclude the platforms that don't support it would be a better solution. I'd wager desktop viewing is majority traffic, where this should be supported.

**Comment by IainCole** [comment]
That's an option, but I worry about information overload. Conceptually a broadcaster shouldn't need to care about the viewability of a stream on different clients of a platform and then have to make a trade-off decision based on what devices your viewers may or may not be using, it should just work or not work. From a Twitch standpoint it simply isn't supported but results vary by client because we don't trasncode everything (160p / 360p streams work ok on iOS since the audio is transcoded to 2 channels on these renditions)

To be clear, there are zero platforms that "support" multichannel audio, it might work on some but it's definitely not supported.

**Comment by Fenrirthviti** [comment]
That's fair. If it is not an official supported feature, and more incidental where it works than where it doesn't work, I would agree with removing it. We can add the notes to our documentation.

**Pull request merged**
