### PR TITLE
libobs: Fix image source not loading upper case file extensions

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

file name like "xxx.GIF" can't be loaded as animated image.

### Motivation and Context

xxx.GIF can be loaded normally

### How Has This Been Tested?

rename xxx.gif with xxx.GIF, make sure it can be loaded

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by walker-WSH** [comment]
I am not clear about the compile error on MAC and Linux.
Anyone help confirm ?

**Comment by WizardCM** [comment]
> `error: implicit declaration of function 'astrcmpi' is invalid in C99`

This usually means that function isn't imported in the current file.

**Comment by notr1ch** [comment]
This doesn't seem to affect image-source so the commit title needs updating.

**Comment by walker-WSH** [comment]
> This doesn't seem to affect image-source so the commit title needs updating.

It affects image source，loading GIF as animated image

**Comment by Fenrirthviti** [comment]
Commit titles reference the files or libraries being changed, not the logical impacts. A better commit title would be something like:

`libobs: Fix image source not loading upper case file extensions`

**Review by RytoEX — CHANGES_REQUESTED** [review]
Please make the required commit message change per comments from @notr1ch and @Fenrirthviti .

**Pull request merged**
