### PR TITLE
win-capture: Fix bug sometimes UWP window can't be found

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

Some UWP window can't be found while using WGC mode.
Such as Microsoft.Photo window.

According to my test result, this situation can't be reproduced on every PC, not related with OS version.
As the issue, Microsoft.Photo can be found in the window list. But when you choose this item, window can't be found in window-plugin.Tick (using Auto/WGC capture mode).

### Motivation and Context

find uwp window correctly

### How Has This Been Tested?

add window source and use WGC capture mode;
choose Microsoft.Photo/Calculate.exe;
check result: no video is captured even photo window is not minimized;

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I can find and capture Photos just fine. Is there a particular scenario in which it cannot be found in the window list?

**Comment by walker-WSH** [comment]
> I can find and capture Photos just fine. Is there a particular scenario in which it cannot be found in the window list?

According to my test result, this situation can't be reproduced on every PC.

As the issue, Microsoft.Photo can be found in the window list. But when you choose this item, window can't be matched in window-plugin.Tick.

**Comment by RytoEX** [comment]
Could you please provide some detailed reproduction steps for reproducing the issue? We're having trouble reproducing the issue, and we'd like to confirm the behavior before and after this PR.

**Comment by walker-WSH** [comment]
> Could you please provide some detailed reproduction steps for reproducing the issue? We're having trouble reproducing the issue, and we'd like to confirm the behavior before and after this PR.

the steps is so simple. add window source and choose photo window & WGC method，then check captured view.

this seems to be related with environment, sorry I have no more tips. I verified it on 5 PC，only 2 computers hold this bug.

even photo window is normally captured on your PC，if you debug the window_rating, you can find only title is matched since exe and class are gotten from host window of UWP

**Comment by walker-WSH** [comment]
I am not sure if you can understand my bad English. Maybe @jpark37 or @jp9000 knows me ？

**Comment by RytoEX** [comment]
Just to confirm: does this actually happen in OBS Studio, or does this only happen in other apps that load this plugin?

**Comment by walker-WSH** [comment]
> Just to confirm: does this actually happen in OBS Studio, or does this only happen in other apps that load this plugin?

In OBS, including master branch

**Comment by walker-WSH** [comment]
hi  @RytoEX    

Now this issue can be reproduced 100% on my WIN11 PC
here is detail for version and recording:

[2023-07-27 15-14-38.zip](https://github.com/obsproject/obs-studio/files/12180391/2023-07-27.15-14-38.zip)

**Comment by PatTheMav** [comment]
The underlying implementation has changed since this PR was authored (the window-helper has moved to `libobs`) and was also changed to accommodate UWP applications as well.

As such this PR attempts to change a non-existing/moved file.

Please check if the issue persists with OBS v30 and open a new issue with reproduction steps or a new PR with mitigating code changes.

**Pull request closed without merging**
