### PR TITLE
UI: Shorten Stats labels wording

### PR DESCRIPTION
**Pull request by SuslikV**

### CODE REVIEW

**Comment by SuslikV** [comment]
By the way, the strings concatenation is slower than few raw constants.

**Comment by jp9000** [comment]
This replaces #1801

**Comment by ntoff** [comment]
Is dropping frames due to the network, the same thing as packet loss? Or is network frames dropped, more due to over saturation of the connection and would be fixed by lowering the bitrate? Packet loss suggests a network issue that may be out of the users control in some situations.

Why not combine them all under one heading 

image

**Comment by dodgepong** [comment]
The phrase "dropped frames" is common enough parlance at this point that it as a specific, well-defined meaning, and that meaning specifically refers to frames dropped due to network issues. Describing other frames as "dropped" could end up making things more confusing if people come into support channels and say "I'm having dropped frames" and we have to ask what kind.

**Comment by SuslikV** [comment]
The lines of each output (from left to right) shows network related info: Frames dropped because of network issues; Amount of send information - useful for metered connections; Bitrate - for overall connection speed to the destination. That was the logic for the new names. Also, some recording types (Custom FFmpeg Output) can transfer the data over the network. So, it was an attempt to make the "Output" abstract. Similar to "File" in meaning of the FFmpeg where it can be regular file, pipe, network stream, grabbing device, etc.

**Comment by ntoff** [comment]
Yeah, I realised that after I posted and re-did the image to make more sense but since it might cause more confusion lumping them all together, I didn't bother posting it.

**Comment by SuslikV** [comment]
Nobody reads or checks the PRs :)

**Comment by SuslikV** [comment]
It may look like this (my view, so don't think a lot about):

Stats labels toggled 02 cropped_result

brute force solution was used.

**Comment by SuslikV** [comment]
There are number of stylesheet entries in the obs code instead of qss, I think it needs to be removed one by one in number of  following fixes (not here of course). Because it causes styling  difficulties, when simple tooltip inherits font-weight: **bold** property and so on.

I can use qss:
```
QLabel QToolTip {
	font-weight: bold;
}

QLabel {
	font-weight: normal;
}
```
or similar to style the widgets. But stylesheet in the code - it is bad practice it overrides everything. When there is qss and themes, the _setStyleSheet()_ should be removed from the code completely.

While this PR still uses _setStyleSheet()_ , the single PR can lead to rewriting number of issues that are now deep into the code. The complexity will increase and... time will froze. Because there is no deadline for this PR the number of rebases unpredictable. Maybe Microsoft can implement some kind of timed PRs - if it weren't merged in time - they should be removed automatically as unneeded feature? What sense to keep something useful that cannot be used? Because of its beauty? Or because it reminds something?

**Comment by SuslikV** [comment]
Should look almost like on the screenshot (see few posts above).

History modified.

**Comment by Fenrirthviti** [comment]
Transmitted would show/hide the network-related stats (i.e. dropped frames)? I would prefer that renamed to Network instead of Transmitted.

**Comment by SuslikV** [comment]
Transmitted tooltip

**Comment by SuslikV** [comment]
Word wrapping for some tooltips was changed. "Averaging" etc.

**Comment by SuslikV** [comment]
In week I will remove this as unneeded stuff.

**Pull request closed without merging**
