### PR TITLE
UI: Update OSX to macOS in English translation

### PR DESCRIPTION
**Pull request by unknowndomain**
### Description
Apple changed the name of it's operating system in 2016 from OS X to macOS, this change is a US English language change only.

### Motivation and Context
Apple changed the name of it's operating system in 2016 from OS X to macOS, it is time to update this as it will help with understanding the context of what these checkboxes do.

### How Has This Been Tested?
This is a localisation change only. Built on macOS 10.15.4 only.

Screenshot 2020-04-23 at 23 57 02

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by unknowndomain** [comment]
I don't really understand what 'My code is not on the master branch.' means so I've not checked it.

I understand what the master branch is, I just don't understand the context of what you are asking me for, where to commit into as it's not in the guide.

**Comment by Fenrirthviti** [comment]
You shouldn't commit directly to master when working with a fork that you intend to submit back to the main repository. The reason we ask for "my code is not on master" is because your code *shouldn't* be on master. It makes it difficult to sync back up and rebase to upstream, and is good practice for how git is supposed to be used to make a branch for changes.

**Comment by unknowndomain** [comment]
Oh, sorry I see, without context I wasn't really getting the question.

Yeah I figured as this was just tiny a localisation change it wasn't really worth it.

Can this be accepted as is, or should I redo this?

**Comment by Fenrirthviti** [comment]
It should be fine, just keep it in mind for the future. You don't need to resubmit the PR.

**Pull request merged**
