### PR TITLE
RFC: Add support for unit testing with CMocka

### PR DESCRIPTION
**Pull request by computerquip-streamlabs**
I made a small setup using CMocka and CMake's ExternalProject functionality to get some tests up and running. It's extremely bare bones right now but I'd like to get this in and see if there's any general issues people have with it before really diving into implementing tests. There's a README included to explain use and implementing tests. 

Also note that this removes the previous tests. Those are more examples than they are tests and use wrappers/higher-level functionality which should probably be avoided in unit-tests.

### CODE REVIEW

**Comment by computerquip-streamlabs** [comment]
Seems Ninja is still broken. CMocka places both shared and static libraries into the same directory. That doesn't work on Windows since they'll both generate .lib files. Ninja then gets confused since there's two producers of the same file and runs the rule for shared libraries by chance to generate the dependency. Will have to fix....

**Comment by computerquip-streamlabs** [comment]
Since the bug is in CMocka and I can't seem to work around the bug otherwise, I've made a custom repository with the fix. Currently, it just changes the static library name from `cmocka.lib` to `cmocka_static.lib`.

**Comment by computerquip-streamlabs** [comment]
Corresponding issue upstream cmocka [issue](https://open.cryptomilk.org/issues/80). Not sure if it will be acknowledged or not yet.

**Comment by DDRBoxman** [comment]
Closing this for now, worth bringing up again in say 6 months to a year.

**Pull request closed without merging**
