### PR TITLE
obs-filters/expander: Various improvements

### PR DESCRIPTION
**Pull request by pkviet**
This improves the expander especially in the ballistics phase.
- Make envelope per channel.
- Move ballistics (attack/release) to log domain and after gain stage.
(some code clean up too)
cf Josh Reiss, Uni. London, [pdf](http://c4dm.eecs.qmul.ac.uk/audioengineering/compressors/documents/Reiss-Tutorialondynamicrangecompression.pdf)
Thanks to Dedrick for very useful feedback.

### CODE REVIEW

**Comment by SuslikV** [comment]
The mentioned document suggesting "Peak" as default rather then "RMS" detector. Why it was chosen RMS then?

**Comment by pkviet** [comment]
> The mentioned document suggesting "Peak" as default rather then "RMS" detector. Why it was chosen RMS then?

I followed Dedrick recommendation. For the expander for short release time, RMS gives you time to speak while Peak gets choppy. (the pdf deals with compressor so small differences are to be expected)

**Comment by SuslikV** [comment]
Is this new expander filter intended to work as described here:
https://www.mediacollege.com/audio/processing/expansion/
or it doing something different?..

**Comment by pkviet** [comment]
> Is this new expander filter intended to work as described here:
> https://www.mediacollege.com/audio/processing/expansion/
> or it doing something different?..

it's a regular downward expander; you can test it in the RC1 and RC2

**Comment by SuslikV** [comment]
After modern digital meter was implemented in obs, I see new filter that was transferred to digital world using analog metrics of amplitude and RMS calculations. The question was - what it should do rather then what it does.

**Pull request merged**
