### PR TITLE
libobs: Ensure all graphics tasks can be handled before exiting graphics thread

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

In graphics thread, both tick_sources() and output_frame() will invoke obs_source_release, which may cause source::destroy invoked in defer-thread or any thread.  For source::destroy of window/monitor plugin,  freeing WGC is posted into graphcis thread.

### **That is to say, tick_sources() or output_frame() can cause new graphics task be posted.**
So, It is better to check remaining tasks before stopping graphics thread. 

@jpark37   It should be reviewed by you.

### Motivation and Context

before stopping graphics thread, make sure stored WGC tasks can be handled

### How Has This Been Tested?

add window source and display source based on WGC mode;
exit OBS;
make sure all actual destroy can be handled from graphics thread

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
@jp9000 Is this problem solved by the deferred destroy changes?

**Review by jpark37 — CHANGES_REQUESTED** [review]
The message pump happens before tick, so we can draw changes on the same frame. Is there an actual problem here?

**Comment by walker-WSH** [comment]
> The message pump happens before tick, so we can draw changes on the same frame. Is there an actual problem here?

@jpark37 
no issue, this is the reason of this PR:

**Comment by jpark37** [comment]
We already run the graphics thread one extra loop on thread teardown:
```
	/* defer loop break to clean up sources */
	const bool stop_requested = video_output_stopped(obs->video.video);
```

The only way for this to be a problem is if you somehow modify a setting that requires graphics thread recreation, and delete a source at the same time. If we want to be paranoid, we can add another execute_graphics_tasks() call somewhere, but I don't think reordering the existing function calls is the solution we want.

**Comment by jpark37** [comment]
Actually, do this order:

[message pump]
output_frame
render_displays
execute_graphics_tasks

@jp9000 Does that order look reasonable to you?

**Comment by jp9000** [comment]
Does this PR take into account the new defer destroy code? It seems like in your example, you're referencing obs_source_destroy() occurring in the graphics thread, but it shouldn't be happening in the graphics thread anymore.

But yea, that seems fine to me @jpark37.

**Comment by walker-WSH** [comment]
> Does this PR take into account the new defer destroy code? It seems like in your example, you're referencing obs_source_destroy() occurring in the graphics thread, but it shouldn't be happening in the graphics thread anymore.
> 
> But yea, that seems fine to me @jpark37.



This commit only ensure all graphics tasks can be handled before ending obs_graphics_thread. There is nothing with obs_source_destroy.

Even obs_source_actual_destory is invoked in defer-thread, posted graphics task from window::destroy and monitor::destroy should still be handled in graphic thread. 

If this commit is not easy to understand, I can chang it as Jpark37 said:

**Comment by jpark37** [comment]
We changed our mind. Can you do this ordering instead?

[message pump]
output_frame
render_displays
execute_graphics_tasks

**Comment by walker-WSH** [comment]
@jpark37 

code has been updated as your order

**Review by jpark37 — APPROVED** [review]

**Pull request merged**
