### PR TITLE
decklink: Fix automatic pixel format detection

### LINKED ISSUE #3872: Decklink issues on OBS 26.1
Decklink Quad HDMI corrupted input with latest RC. Bouncing Mode, Colour space / range, or Pixel Format did not result in a usable image. 

## Platform
OBS Studio version: OBS 26.1.0-rc2-22-g00f0d5eb4 

## Expected Behavior
Clean HDMI capture from PC. 

## Current Behavior
Corrupted HDMI capture from PC.

## Steps to Reproduce
Create BlackMagic source with Decklink Quad HDMI. Auto or manual. 

1. Screenshots https://imgur.com/a/5kASjmD

## Additional information
The device functions correctly with OBS 26.0.2-66-gb9a151625 as shown in the screenshots. Only occurs when capturing from PC, a DSLR HDMI input worked as expected. 

## Log
[2020-12-12 15-44-52.txt](https://github.com/obsproject/obs-studio/files/5683774/2020-12-12.15-44-52.txt)

### PR DESCRIPTION
**Pull request by DDRBoxman**
### Description

Be smarter about picking the input pixel format. Stick to 8 bit unless the user specifies 10 bit since we only need that for captions. Also now we only do frame conversions for 10 bit to 8 bit and not say RGB -> YUV

### Motivation and Context

Fixes #3872 

### How Has This Been Tested?

Hooked up a PS4 pro to an intensity 4k
Hooked up a 10 bit sdi source to a decklink duo

### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by DreadWingKnight** [comment]
Confirmed working under following conditions:
1> Decklink Studio 4k
2> Chromecast, nintendo switch, ps4, Xbox 1 set to 8-bit color depth, standard color space (PC RGB causes color distortion)

**Comment by LGCW** [comment]
This is working with the Decklink Quad HDMI and Intensity Pro 4K. 

**Screens**
https://imgur.com/a/RNpSoVx

**Comment by DDRBoxman** [comment]
@edwinr I just pushed up some changes that should fix 8 bit once it finishes building.

**Comment by edwinr** [comment]
> 
> 
> @edwinr I just pushed up some changes that should fix 8 bit once it finishes building.

Not sure if I should reply here or in #3872 now 😅. I just tested it but it seems to do the same for me on the 8-bit YUV pixel format. 10-bit works for component input, the same as in the previous build. I'm not insisting on using 8-bit so 10-bit would be fine as well for me at least.

However I thought I'd test some more with other devices so I connected up an HDMI source and I'm also unable to capture its video, which did work in 26.0.2.

Source: Raspberry pi 4, set to 720p60: hdmi_group=1, hdmi_mode=4. None of the pixel format settings work this time.
This is the new build I just downloaded, but the previous one gives the same result:
afbeelding
And with 26.0.2 it works fine:
afbeelding


If you think it is not related and I should open a separate issue please tell me, as I don't want to hijack the other report. To me it still seems related especially with the change you made actually helping in the case of component input.

**Comment by DDRBoxman** [comment]
@edwinr Pushed some more code, once that finished building mind giving it a spin?

We now don't do RGB->YUV conversions, and we only do 10bit yuv if the user has enabled or asked for it

**Comment by edwinr** [comment]
@DDRBoxman It works for all cases I previously tested 👍

**Comment by djchateau** [comment]
image

On Ubuntu Linux x64, tested with a Black Magic Design Infinity Pro 4K and was able to use 8-bit BGRA again when utilizing my Nintendo Switch. Video no longer appears distorted.

**Pull request merged**
