### PR TITLE
UI: Clean the Audio menus redundancy

### PR DESCRIPTION
**Pull request by brunolopesdsilv**
### Description
- Removes Unhide All entry from volume context menu
- Removes Vertical Layout entry from volume context menu
- Removes Advanced Audio Properties entry from volume context menu
- Improves discoverability of these options in the mixer toolbar

### Motivation and Context
Until today, OBS audio options are few, however, repeated too much in different parts of the interface (e.g., it is possible to access Advanced Audio Options from 4 different places). 
While it is understandable and common for professional programs to have more than one way to access a function, as it is currently implemented., however, it doesn't makes to the user experience better, just duplicated.

---

One way to better "please everyone" would be to 1) keep the menu bar entry; 2) remove redundant entries of volume's context menu; 3) improve the mixer toolbar turning entries into buttons and with the mixer context menu order, like this:

https://github.com/obsproject/obs-studio/assets/136904537/33ab56d2-7e69-41ee-bb20-0d2aad0180de

(Ignore the wrong icons, they are not in the final version of MR)

### How Has This Been Tested?
Compiled via new cmake commands and tested
Windows 11

### Types of changes
- Tweak (non-breaking change to improve existing functionality)
- Documentation (a change to documentation pages)

### Checklist:
- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Removing options without improving discoverability of the existing options seem unlikely to be accepted as a change.

I don't disagree that the current situation isn't ideal, but this feels like a step in the wrong direction and like it's not actually solving a problem.

**Comment by brunolopesdsilv** [comment]
Yes. One way to **improve** (as that's good enough without the redundancy) the discovery would be turn the redundant options into buttons as they are currently accessed via a 3-dot button below.

However, doesn't feel wise for me propose such a thing right now without a prior initial discussion limited to audio menus redundancy. Changing more than one design concept at once always makes it difficult for the maintainer to analyze calmly the merge request.

**Comment by Warchamp7** [comment]
> Removing options without improving discoverability of the existing options seem unlikely to be accepted as a change.
> 
> I don't disagree that the current situation isn't ideal, but this feels like a step in the wrong direction and like it's not actually solving a problem.

We improved discoverability by adding Advanced Audio Properties to the toolbar.

I am fine with removing it from some of the extra places now. We'll get a few spacebar heaters but it'll pass.

**Review by GeorgesStavracas — APPROVED** [review]
This cleanup is appreciated from a UI / UX perspective. Please split this change in 2 commits, one for each menu option being removed.

**Comment by GeorgesStavracas** [comment]
Seems like something went wrong with your rebase. The first 3 commits of this branch can be dropped, leaving only the two split commits we asked for.

**Comment by RytoEX** [comment]
> Removes the Advanced Audio Properties from the Edit menu

I strongly disagree with this specific change. The Edit menu is where this feature is most easily accessible when using OBS on macOS, with or without VoiceOver (the macOS built-in screen reader). For items in any menu bar submenu, a macOS user can simply go to Help -> Search and type to search all menu items.
Screenshot 2023-07-05 at 10 41 30 AM
Screenshot 2023-07-05 at 10 41 42 AM

Search does not include custom in-app context menus.

Furthermore, VoiceOver cannot easily read or navigate menu items in these context menus:
Screenshot 2023-07-05 at 11 47 57 AM
Screenshot 2023-07-05 at 11 48 08 AM

You can get VoiceOver to read them, but you cannot filter it the same way you can with items in the Menu Bar.

VoiceOver _can_ read the "Advanced Audio Properties" button in the Audio Mixer Dock, but it is a massive pain to navigate to with VoiceOver. Meanwhile, it is trivial to navigate to "Advanced Audio Properties" in the Edit Menu.

Removing the entry in the Edit Menu seems just makes getting to this feature more difficult for anyone using macOS, and much more difficult for anyone using VoiceOver and possibly other screen readers. Aside from removing a single menu duplicate menu item, what benefit does this removal actually bring?

**Comment by brunolopesdsilv** [comment]
> Seems like something went wrong with your rebase. The first 3 commits of this branch can be dropped, leaving only the two split commits we asked for.

Yes. I was used to the Gitlab workflow with Web IDE, but ended up messing up the Git history here.

**Comment by brunolopesdsilv** [comment]
> > Removes the Advanced Audio Properties from the Edit menu
> 
> I strongly disagree with this specific change. The Edit menu is where this feature is most easily accessible when using OBS on macOS, with or without VoiceOver (the macOS built-in screen reader). For items in any menu bar submenu, a macOS user can simply go to Help -> Search and type to search all menu items. Screenshot 2023-07-05 at 10 41 30 AM Screenshot 2023-07-05 at 10 41 42 AM
> 
> Search does not include custom in-app context menus.
> 
> Furthermore, VoiceOver cannot easily read or navigate menu items in these context menus: Screenshot 2023-07-05 at 11 47 57 AM Screenshot 2023-07-05 at 11 48 08 AM
> 
> You can get VoiceOver to read them, but you cannot filter it the same way you can with items in the Menu Bar.
> 
> VoiceOver _can_ read the "Advanced Audio Properties" button in the Audio Mixer Dock, but it is a massive pain to navigate to with VoiceOver. Meanwhile, it is trivial to navigate to "Advanced Audio Properties" in the Edit Menu.
> 
> Removing the entry in the Edit Menu seems just makes getting to this feature more difficult for anyone using macOS, and much more difficult for anyone using VoiceOver and possibly other screen readers. Aside from removing a single menu duplicate menu item, what benefit does this removal actually bring?

Your point seems fair about the menu bar. And excuse me for answering with another question, but... and the many entries that OBS doesn't show in this menu until today?
(When arguing for the need for this specific entry, I can conclude that many others should be present, as is usual in programs with a menu bar.)

**Comment by brunolopesdsilv** [comment]
> > Your point seems fair about the menu bar. And excuse me for answering with another question, but... and the many entries that OBS doesn't show in this menu until today?
> > (When arguing for the need for this specific entry, I can conclude that many others should be present, as is usual in programs with a menu bar.)
> 
> "Bad stuff happens elsewhere" is not a good reason to "do more bad stuff".

I didn't say that the status quo of fewer entries justifies removing entries. Your point just made me curious what approach OBS should take with regard to accessibility in the menu bar (more entries or fewer entries?).

If you don't want to talk here, that's fine, but don't simply rate the whole MR as "bad stuff".

**Comment by RytoEX** [comment]
> > > Your point seems fair about the menu bar. And excuse me for answering with another question, but... and the many entries that OBS doesn't show in this menu until today?
> > > (When arguing for the need for this specific entry, I can conclude that many others should be present, as is usual in programs with a menu bar.)
> > 
> > 
> > "Bad stuff happens elsewhere" is not a good reason to "do more bad stuff".
> 
> I didn't say that the status quo of fewer entries justifies removing entries. Your point just made me curious what approach OBS should take with regard to accessibility in the menu bar (more entries or fewer entries?).
> 
> If you don't want to talk here, that's fine, but don't simply rate the whole MR as "bad stuff".

I apologize for being curt. I was in the middle of another task and just wanted to give a quick reply.

The simple answer is that UI efforts are not always aligned, and sometimes things get added/changed/removed without a comprehensive review or study of the implications. My understanding was that we (the project) wanted less stuff in context menus in general and less items that _only_ appeared in context menus. Personally, I agree with that stance, and I think that items currently only available in context menus (or widget menus) should be available in the top level menu bar. Perhaps things have changed, and I am mistaken.

With respect to this PR, specifically, I simply wanted to voice my feedback here before it got merged and I missed the opportunity to provide that feedback.

**Comment by brunolopesdsilv** [comment]
> > > > Your point seems fair about the menu bar. And excuse me for answering with another question, but... and the many entries that OBS doesn't show in this menu until today?
> > > > (When arguing for the need for this specific entry, I can conclude that many others should be present, as is usual in programs with a menu bar.)
> > > 
> > > 
> > > "Bad stuff happens elsewhere" is not a good reason to "do more bad stuff".
> > 
> > 
> > I didn't say that the status quo of fewer entries justifies removing entries. Your point just made me curious what approach OBS should take with regard to accessibility in the menu bar (more entries or fewer entries?).
> > If you don't want to talk here, that's fine, but don't simply rate the whole MR as "bad stuff".
> 
> I apologize for being curt. I was in the middle of another task and just wanted to give a quick reply.
> 
> The simple answer is that UI efforts are not always aligned, and sometimes things get added/changed/removed without a comprehensive review or study of the implications. My understanding was that we (the project) wanted less stuff in context menus in general and less items that _only_ appeared in context menus. Personally, I agree with that stance, and I think that items currently only available in context menus (or widget menus) should be available in the top level menu bar. Perhaps things have changed, and I am mistaken.
> 
> With respect to this PR, specifically, I simply wanted to voice my feedback here before it got merged and I missed the opportunity to provide that feedback.

Excellent. I understand you very well now.

**Comment by Fenrirthviti** [comment]
For clarity, I believe the only option we have a concern about removing as part of this PR is the Edit menu. All other removals (without the need for additional improved discoverability) should be fine for this.

I'll ultimate defer the rest to @Warchamp7, but I wanted to be absolutely clear just how much removing the option from the Edit menu harms *current* accessibility, with no replacement or alternative provided.

**Comment by brunolopesdsilv** [comment]
The different points of view gave me a way better overview to improve the MR. While I don't fix the commit history, I leave a patch so the reviewer's time isn't wasted. (The pratical result of the patch is the video above)

[clean_audio.patch](https://github.com/obsproject/obs-studio/files/11973721/clean_audio.patch)

**Comment by brunolopesdsilv** [comment]
Finally, I fixed the git history. What slowed me down the most was the new build script that apparently doesn't cache any of the submodules on Windows. It was real torture.

**Comment by RytoEX** [comment]
I don't recall the new vertical/horizontal layout button being part of the original changeset. At least, it's not in the initial screenshots. If those are changes since any previous approvals, reviews will need to be re-requested.

> Ccompiled via new PowerShell script and tested
> the new build script that apparently doesn't cache any of the submodules on Windows

If you mean `.github/scripts/Build-Windows.ps1`, don't use that for building locally. Please refer to our newly updated [Build Instructions for Windows](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows).

**Comment by brunolopesdsilv** [comment]
> If you mean `.github/scripts/Build-Windows.ps1`, don't use that for building locally. Please refer to our newly updated [Build Instructions for Windows](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows).

I directly called Cmake with the CCACHE option from the new build instructions, but there was no difference. I even modified CMakePresets.json to see if it would solve it, but nothing did. Submodules continue to be recompiled.

**Comment by RytoEX** [comment]
> > If you mean `.github/scripts/Build-Windows.ps1`, don't use that for building locally. Please refer to our newly updated [Build Instructions for Windows](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows).
> 
> I directly called Cmake with the CCACHE option from the new build instructions, but there was no difference. I even modified CMakePresets.json to see if it would solve it, but nothing did. Submodules continue to be recompiled.

I'm fairly certain that CCACHE does not work on Windows presently, but that is neither here nor there.

**Comment by brunolopesdsilv** [comment]
> I'm fairly certain that CCACHE does not work on Windows presently, but that is neither here nor there.

Makes sense. I probably felt that the previous version of the script performed better because fewer submodules were loaded.

**Pull request closed without merging**
