### PR TITLE
obs-ffmpeg: Align both NVENC implementations

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Set aspect ratio after av_reduce, e.g. 1920:1080 becomes 16:9.

Modify dts computation to offset by number of bframes to match FFmpeg.

Hard-code various H264 config values as they appear in FFmpeg.

Don't set maxEncodeWidth/maxEncodeHeight since FFmpeg doesn't, and we
don't support resolution changes.

Force-enable lookahead if nvEncGetEncodePresetConfig says to.

If Psycho Visual Tuning is on, switch aqStrength to from 0 to 8 to match
FFmpeg default.

Set vbvBufferSize to match FFmpeg behavior.

Compute buffer count according to FFmpeg logic.

Fix various static analysis warnings about variable size.

Plumb Psycho Visual Tuning setting into fallback encoder.

### Motivation and Context
Cleaning things up before a future NVENC upgrade.

### How Has This Been Tested?
Various experiments with modified FFmpeg to simulate OBS encodes against lossless Sintel trailer source. PSNR/VMAF are pretty close to identical on my personal set of settings.

Inspected all diffs under debugger to make sure values are applied as expected. Verified NVENC init params match FFmpeg behavior as needed.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by pkviet — CHANGES_REQUESTED** [review]
the repeat headers option should not be removed. It implements necessary stuff to follow mpegts spec. Some broadcast decoders have issues when the streams are not compliant with spec. (ex: srt streams to haivision decoders)

**Comment by jpark37** [comment]
I put the SPS/PPS/AUD code back the way it was.

**Comment by jp9000** [comment]
Hm, seems there's a lot of individual changes in the commit. Would it be worth it to split into multiple commits for better bisecting, or do you feel confident that there won't be any unforeseen issues because it's basically the same as FFmpeg now?

**Comment by jpark37** [comment]
It wouldn't be that much work to split up the commits. Better safe than sorry.

**Comment by jpark37** [comment]
I'm done with the changes now. Also caught a mistake where I was still setting up init params after calling initialize.

**Comment by jpark37** [comment]
Verified that lookahead is processed on/off as expected. I checked the result videos frame-by-frame in Avidemux, and they looked fine.

**Pull request merged**
