### PR TITLE
UI: Change ellipses to correct version

### PR DESCRIPTION
**Pull request by Vainock**
Changed "..." (the 3 normal dots as 3 characters) and ".." to " …" (3 dots as 1 character).
There was used "...", ".." and "…", I have changed everything to this ellipsis, because there needs to be a static one. Also ".." was not really an official variant.
Also I have added one space between the ellipsis and the word because when there is no one it means that this word is uncompleted.

-> https://en.wikipedia.org/wiki/Ellipsis

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Did you intend to add a space before each ellipsis? That seems incorrect to me.

**Comment by DDRBoxman** [comment]
KDE and apple also don't use a space in their examples.

https://hig.kde.org/components/navigation/menubar.html

https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

I do know that German works differently so the OS uses a space before the ellipsis when the OS is in that language on OSX at least.

**Comment by Vainock** [comment]
@Fenrirthviti
The space is not incorrect. There are different styles on how and where you place the space and which ellipsis you use.

But I see that I have not really a chance. I will change it because of the consistency.

**Comment by SuslikV** [comment]
Currently, Windows uses 3 separate dots in their menus as I see.

**Comment by Vainock** [comment]
I have updated the fork again. It is now I think the best solution.

**Comment by jp9000** [comment]
I fixed the commit message of this pull request and will merge shortly (should be something like `UI: Fix inconsistent use  of ellipsis`.  I also squashed the commits.  You'll see "closed in [commit]".

**Pull request closed without merging**
