### PR TITLE
libobs/UI: Add Transition Previews

### PR DESCRIPTION
**Pull request by VodBox**
This PR adds a preview to the properties window for transitions. The preview will play back the transition at the global transition duration or the transitions fixed duration, between two private scenes with an A and B label, and different background colors.

### CODE REVIEW

**Comment by SuslikV** [comment]
The both scenes should be more complex, has colorblindness safe colors, and clear meaning "from" the scene "to" the scene.

**Comment by SuslikV** [comment]
Ideally, there should be progress bar implemented of the transition itself (later it can be placed in Studio Mode as helper object). It would help to visualize duration and progress of the Stinger transition too. My thoughts.

**Comment by VodBox** [comment]
I changed this to have a "Preview Transition" button, instead of constantly just playing a loop that would sometimes take a few moments after changing a property to actually start playing.

preview button

**Comment by WizardCM** [comment]
I've tested this myself with a variety of filters, and have run into no issues with the PR itself or any overall stability issues due to these changes. 👍

As a side note, I did run into a small quirk with the [motion-effect](https://obsproject.com/forum/resources/motion-effect.668/) transition, but that's due to the fact that it's a different text source in each scene and so the visual behaviour that occurs is to be expected.

**Comment by SuslikV** [comment]
I don't like how "Preview Transition" button is placed. Insert the button before the spacer (so it appear right under the last property option, here it named "invert") and align it by wrapping it into the same layout widget.

**Comment by VodBox** [comment]
Relocated the button to inside the transitions property layout.

**Pull request merged**
