### PR TITLE
CI: Update deps to 2023-03-04 release

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Notable changes:
 * deps.windows: Add Zstandard
 * deps.windows: Add nlohmann JSON
 * deps.windows: Add WebSocket++
 * deps.windows: Add Asio
 * deps.windows: Add VLC
 * deps.macos: Add nlohmann JSON
 * deps.macos: Add WebSocket++
 * deps.macos: Add Asio
 * deps.macos: Add Sparkle
 * deps.macos: Add VLC
 * deps.macos: Ready macOS deps for new CMake

All dependency versions are the same as what obs-studio currently uses. No other changes are being made at this time, as I don't want to complicate this PR. Dependency updates and further workflow changes will come later.

### Motivation and Context

Unblock:
   * #8074
   * #8194 
   * obsproject/obs-websocket#1097
   * #6927
   * #8247

### How Has This Been Tested?

I've built this locally on Windows, but I will want to see CI pass and test the artifacts.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Built on CI. The Windows build loads my test scene collection and my scripting tests passed, so this should be fine to merge as there are no actual dependency updates and @PatTheMav had already tested the macOS deps.

**Comment by gxalpha** [comment]
Could you double-check the Qt version on Mac? The `QT_VERSION_MAC` variable wasn't changed here, but with https://github.com/obsproject/obs-deps/commit/b227eeeb22c1a22e0c4647f235842599c1942f66 merged and still intact (and confirmed by me downloading and building with the deps) this is a Qt downgrade to 6.3.1 (we currently ship 6.4.1 as the deps release with the above commit never got shipped with an OBS release on macOS).
I can see this potentially breaking plugins that link against Qt, as Qt is not promised to be reverse-binary-compatible.

**Comment by RytoEX** [comment]
> Could you double-check the Qt version on Mac? The `QT_VERSION_MAC` variable wasn't changed here, but with [obsproject/obs-deps@b227eee](https://github.com/obsproject/obs-deps/commit/b227eeeb22c1a22e0c4647f235842599c1942f66) merged and still intact (and confirmed by me downloading and building with the deps) this is a Qt downgrade to 6.3.1 (we currently ship 6.4.1 as the deps release with the above commit never got shipped with an OBS release on macOS). I can see this potentially breaking plugins that link against Qt, as Qt is not promised to be reverse-binary-compatible.

Ah, yes, that is probably the case. Unfortunately, we do need the rest of the updates in this, so I will have to rebuild another obs-deps release another day.

**Comment by derrod** [comment]
> Ah, yes, that is probably the case. Unfortunately, we do need the rest of the updates in this, so I will have to rebuild another obs-deps release another day.

Would you still consider merging this for now to unblock/merge affected PRs and then update obs-deps again when dependencies have actually been updated?

**Comment by RytoEX** [comment]
> > Ah, yes, that is probably the case. Unfortunately, we do need the rest of the updates in this, so I will have to rebuild another obs-deps release another day.
> 
> Would you still consider merging this for now to unblock/merge affected PRs and then update obs-deps again when dependencies have actually been updated?

The problem is that macOS obs-studio builds currently use Qt 6.4.1 due to an oversight back in December/January where I forgot to switch macOS builds to the new 2023-01-06 obs-deps build. However, obs-deps itself had reverted Qt on macOS back to 6.3.1, so this update would have accidentally rolled obs-studio macOS builds from Qt 6.4.1 to 6.3.1. To avoid that disruption, I'll fix obs-deps to match obs-studio, make a new release there, and update this PR. I'll take care of that today since I missed this.

**Comment by RytoEX** [comment]
I have now adjusted this to point to the 2023-03-04 obs-deps release which should resolve the Qt version complaints.

**Pull request merged**
