### PR TITLE
UI: Improve look of adv audio control dialog

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This improves the look of the dialog by making the header labels bold, left aligning widgets and increasing the horizontal spacing.

Before:
Screenshot from 2019-07-17 12-28-39
After:
Screenshot from 2019-07-17 12-20-34

### Motivation and Context
IMO, this makes the advanced audio controls dialog more visually pleasing.

### How Has This Been Tested?
This has been tested by running the program and seeing what the dialog looks like.

### Types of changes
-Visual change (improves look of UI)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I like everything but the left justified checkbox for mono downmix.

**Comment by WizardCM** [comment]
I agree with Fenrir.

Also, as you've added a suffix to Sync Offset, may be worth removing the (ms).

Finally, I feel by adding so much spacing, the Balance slider has less leeway. Not sure about the best solution there.

**Comment by cg2121** [comment]
After some tweaking, this is what it currently looks like. Feedback is always welcomed.

Screenshot from 2019-07-18 01-01-40

**Comment by mufunyo** [comment]
While you're improving the UI, I'd suggest swapping out "inf" for the proper Unicode symbol for infinity (∞).

**Comment by Fenrirthviti** [comment]
I'm still not a big fan of the left justified checkbox, but the reduced whitespace is a significant improvement.

**Pull request merged**
