### PR TITLE
Fix desktop entry for GNOME shell without file renaming

### PR DESCRIPTION
**Pull request by AlexWayfer**
### Description

Combination of #2100 and #2130.

`.desktop` file can be renamed for fix, but here are file name references must be changed too.

@eszlari suggested an `StartupWMClass=obs` option for desktop entry.

### Motivation and Context

Make OBS addable to favorites applications in GNOME shell, and without desktop file renaming.

### How Has This Been Tested?

Manually.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
I'm not sure should I squash commits but I can if needed.

**Comment by Fenrirthviti** [comment]
They should stay separate, IMO, as they are doing two different things. You will need to preface the actual change commit with `UI:` however, as this is technically a UI change. That commit being reverted should have had the same prefix, looks like an oversight cause of how simple the change was.

**Comment by dionney** [comment]
Tested on Fedora XFCE. Works for me.

**Comment by AlexWayfer** [comment]
> They should stay separate, IMO, as they are doing two different things. You will need to preface the actual change commit with `UI:` however, as this is technically a UI change. That commit being reverted should have had the same prefix, looks like an oversight cause of how simple the change was.

Thank you, my bad. I didn't think that (outer) desktop entry is UI part of Application, but you're right, especially if look to base directory.

By the way, @jp9000 already changed it.

> Tested on Fedora XFCE. Works for me.

Thank you.

**Comment by AlexWayfer** [comment]
Here is a regression with OBS 26.0.0 somewhy. Where can I investigate a reason?

**Pull request merged**
