### PR TITLE
obs-ffmpeg: Add missing translable string for "Profile"

### PR DESCRIPTION
**Pull request by sn-o-w**
### Description
There's a missing translable string in advanced output mode, NVENC coder settings. "Profile" is not translable because there's no translation key defined in obs-ffmpeg locale files for "Profile".

42t2fvdsas

### Motivation and Context
PR fixes this issue by adding string in obs-ffmpeg locale file~~s~~ **(EDIT: I've changed only for en-US.ini)** where it should be.

### How Has This Been Tested?
I had a look at obs-ffmpeg-nvenc.c, there is a translation key as you can see here: https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L558
Then I made sure to add Profile in en-US.ini. ~~Furthermore, I added translations for other languages by importing all existing translations from obs-x264.~~ **(EDIT: Meanwhile I removed all other locale files as requested)**

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Please read through the [Contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst), especially the Commit Guidelines (you're missing the prefix primarily).

Additionally, only upload the en-US entry, the rest of the languages are only imported via Crowdin directly.

**Comment by sn-o-w** [comment]
> Please read through the [Contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst), especially the Commit Guidelines (you're missing the prefix primarily).
> 
> Additionally, only upload the en-US entry, the rest of the languages are only imported via Crowdin directly.

I just added prefix, sorry for that.

As to all languages, I thought I would make it easier for translators and you by adding relevant translations that we already have.

**Comment by Gol-D-Ace** [comment]
With the next crowdin import all changes will get overwritten. The change needs to be made on Crowdin itself.

**Comment by sn-o-w** [comment]
> With the next crowdin import all changes will get overwritten. The changes need to be made on Crowdin itself.

So should I just update en-US.ini and leave the rest to translators?

**Comment by Gol-D-Ace** [comment]
Exactly.

**Comment by sn-o-w** [comment]
@Gol-D-Ace @WizardCM I made the requested changes. I hope now everything is okay.

**Pull request merged**
