### PR TITLE
RFC 45-2: Add protocol in Services API and enum functions in Outputs API

### PR DESCRIPTION
**Pull request by tytan652**
### Description

**This PR is about the [RFC 45](https://github.com/obsproject/rfcs/pull/45).**

Depends on:
- #5104

Additions (those will be used in other parts of RFC 45 implementation):
- Adds `get_protocol` to services
- Add three enumeration functions:
  - `obs_enum_output_protocols` to enumerate protocols
  - `obs_enum_output_types_with_protocol` to enumerate outputs with the given protocol.

### Motivation and Context

Part of the implementation of the RFC 45.

### How Has This Been Tested?

Testing by logging enumeration functions outputs and through other part of RFC 45 implementation.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by jp9000 — APPROVED** [review]

**Comment by jp9000** [comment]
I generally approve of this, although one note is that twitch uses an API that can generate a new server list whenever the program is run. when that happens, it might switch it internally to RTMPS rather than RTMP.

In general, RTMP/RTMPS are fairly interchangeable. So I'm not sure what to do about that. What do you think?

**Comment by jp9000** [comment]
Another thing Rodney pointed out is that it might have been nice to make it default to RTMP/RTMPS if a service doesn't have that item. Not sure how you feel about that one though.

**Comment by jp9000** [comment]
Actually exclude the last message, seems that was an intentional decision.

**Comment by tytan652** [comment]
- Renamed `obs_enum_output_service_types` to `obs_enum_output_protocols` with a refactor to avoid strlist allocation.
- Refactored `obs_enum_output_protocols` based on RFC 45-1 recent changes.

**Comment by tytan652** [comment]
Refactor of `obs_enum_output_types_with_protocol` based on #8095 review.

**Pull request closed without merging**
