### PR TITLE
CI: Build CEF on Linux

### PR DESCRIPTION
**Pull request by cg2121**

### CODE REVIEW

**Comment by derrod** [comment]
Instead of doing

```bash
curl -L -O "http://opensource.spotify.com/cefbuilds/cef_binary_73.1.12%2Bgee4b49f%2Bchromium-73.0.3683.75_linux64_minimal.tar.bz2"
tar -xjf "./cef_binary_73.1.12%252Bgee4b49f%252Bchromium-73.0.3683.75_linux64_minimal.tar.bz2"
mv "/cef_binary_73.1.12%252Bgee4b49f%252Bchromium-73.0.3683.75_linux64_minimal" "cef"
```
Do 
```bash
curl -L -o cef.tar.bz2 "http://opensource.spotify.com/cefbuilds/cef_binary_73.1.12%2Bgee4b49f%2Bchromium-73.0.3683.75_linux64_minimal.tar.bz2"
tar -xjf "./cef.tar.bz2"
```
To make updating a little easier and avoid having to deal with URL escape sequences in the filename.

**Comment by cg2121** [comment]
Thanks, it works now.

**Comment by derrod** [comment]
Not quite yet, you'll also have to enable the browser being built at all in OBS: https://github.com/obsproject/obs-studio/blob/8b936a1575bda91813f8746338319604195b99db/plugins/CMakeLists.txt#L51
Right now it builds CEF, but then doesn't build obs-browser because that's still windows only in the CMake file.

**Comment by cg2121** [comment]
I have a PR for that https://github.com/obsproject/obs-studio/pull/1759

**Comment by derrod** [comment]
Oh I see, nvm then 👍

**Comment by cg2121** [comment]
I combined this with #1759

**Pull request closed without merging**
