### PR TITLE
Adjustments to YouTube Broadcast Setup

### PR DESCRIPTION
**Pull request by derrod**
### Description
Changes the broadcast button to be always visible when a service that uses a broadcast based flow is selected.

The broadcast button now allows the user to set up the broadcast before hitting start streaming, effectively "readingy" it. Start streaming itself will still open the broadcast setup screen as well, but without the option to "ready" a broadcast and just the traditional options.

"Start Streaming" will now show an info box if no broadcast has been prepared, and offer the user the option to open the broadcast setup dialog.

### Motivation and Context
The current YouTube UX is somewhat confusing as it breaks from the existing flow of how starting a stream in OBS works. By showing the user that there is a different option to setup the broadcast we hope to make it clearer what the user has to do.

Additionally it would be nice to be able to set up or "ready" a broadcast without going live immediately, or be able to schedule an event and not have to manually select it again afterwards, that's why the new flow "readies" an event instead.

### How Has This Been Tested?
- Tested going live and scheduling events for later

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Demo of the flow of readying an event and then starting a broadcast:

https://user-images.githubusercontent.com/3123295/132114790-4a1ba9d0-31c7-4b00-ad22-e33e329bc61b.mp4

**Comment by RytoEX** [comment]
How does this mesh with #5228?

**Comment by derrod** [comment]
I haven't looked at that, although I expect that it wouldn't take more than a rebase and a few tweaks to be compatible.

**Comment by derrod** [comment]
Well this has gotten messy... (but that what drafts are for!)

Anyway here's the latest version of the broadcast setup window, now with a static title rather than using your username (we can add that back, but it seemed silly) and an option to remember the settings based on @cg2121's PR:
2021-09-06_01-00-39_KOcWXT

**Comment by derrod** [comment]
Cleaned up and squashed the commits. As far as my testing goes it should more or less work now.

**Review by Warchamp7 — CHANGES_REQUESTED** [review]
# Feedback

**"Reconfigure Broadcast"** does not really "reconfigure" anything. The event that's been selected doesn't get deleted or edited. Probably just maintain the existing **"Setup Broadcast"** text* (See below string change suggestions)

When a stream has been readied and the the broadcast window is opened, default it to the Select tab and mark off the currently readied event


# Bugs

The **"Schedule and ready event"** button doesn't get properly enabled/disabled when a required field is missing and gets filled in or vice versa. Only the schedule checkbox properly updates it. Switching tabs between Create/Select also does not update it, just forces it to disabled.

**"Create and ready stream"** treats the broadcast as if auto-start and auto-stop are both OFF. **"Create and go live"** treats the broadcast as if auto-start and auto-stop are both ON. It should be both auto setting ON for both.

Scheduled a stream with auto-start and auto-stop both off. Broadcast button said (Auto-stop) but was in disabled state so I couldn't click it to stop. After ending my stream output, the button became enabled and the text changed to **"Reconfigure Broadcast"**. Clicking it prompted me to stop the stream. Button then still had "Reconfigure Broadcast" after stopping instead of resetting to **"Setup Broadcast"**.

Scheduled a stream with auto-stop only. Same issue as above except that the disabled (Auto-stop) button is correct during that. However after ending stream output, the button became enabled and was still responsible for stopping, instead of actually auto-stopping

Scheduled a stream with auto-start only. Stream auto-started but gave the warning that auto-start was off, and the broadcast button was changed to **"Go Live"**. Clicking that button seemingly did nothing, since it actually auto-started. After ending stream output, the broadcast button was once again readied and said **"Reconfigure broadcast"** instead of **"End Broadcast"**. Clicking it prompted to stop the stream.

Related note: When clicking that broken broadcast button, the checked/unchecked state is getting toggled. This means if the button is checked, it gets unchecked when popping up the warning dialog. If you click no on the dialog, the button has now changed visual states but should not have

Second related note: If I click no on that dialog after stopping stream output, and then start streaming again, the button text properly updates to **"End Broadcast"**. Stopping stream output will then incorrectly revert it back to saying **"Reconfigure Broadcast"**, even though the broadcast still needs to be ended.

# String Changes
This might be out of scope for this particular PR kinda maybe not really sorta but leaving it here anyway since verbiage changes are technically related to the UX flow.

Setup Broadcast -> Manage Broadcast


## Create New Tab
Create New Event -> Create New Broadcast

Create and ready stream -> Create broadcast
Create and go live -> Create broadcast and start streaming


## Select Existing Tab

Select Existing Event -> Select Existing Broadcast
Ready selected event -> Select broadcast
Go live with selected event -> Select broadcast and start streaming

**Comment by derrod** [comment]
>  "Reconfigure Broadcast" does not really "reconfigure" anything. The event that's been selected doesn't get deleted or edited. Probably just maintain the existing "Setup Broadcast" text* (See below string change suggestions)

That makes sense, I'll just remove that.

> When a stream has been readied and the the broadcast window is opened, default it to the Select tab and mark off the currently readied event

I thought about this, but haven't done it yet due to the amount of changes I'd expect this to require.

> The "Schedule and ready event" button doesn't get properly enabled/disabled when a required field is missing 

This should be fixed now, the button state wasn't being updated unless scheduling was disabled.

> Create and ready stream" treats the broadcast as if auto-start and auto-stop are both OFF

Silly me expecting the global `autostart` and `autostop` variables to be updated... Turns out they were only set when selecting an existing event, this is now fixed.

> Scheduled a stream with auto-start and auto-stop both off. Broadcast button said (Auto-stop) but was in disabled state so I couldn't click it to stop

There was an `if (!autoStopBroadcast)` instead of `if (autoStopBroadcast)`, also fixed.

Some of the issues with autop-stop being disabled should also be fixed by only resetting the broadcast button if the broadcast is no longer active (i.e. auto-stop enabled or "End Broadcast" button clicked).

**Comment by derrod** [comment]
Okay that wasn't too hard, the downside is of course that it takes a bit for the events to load.

**Comment by derrod** [comment]
I have tested the mentioned scenarios now to confirm that everything appears to work correclty now. I squashed and force-pushed it now.

As for the string changes, there are two I don't think work entirely for me:
> Create and ready stream -> Create broadcast
> Ready selected event -> Select broadcast

Changing those does not seem to convey what the button actually does, which is not just creating the event, but also configuring OBS to start streaming to that event without having to go through the dialog again, which I referred to as "readying".

**Comment by derrod** [comment]
How about the following? Also changes the "YouTube Studio..." string because that doesn't really make sense does it.

```ini
YouTube.Actions.Create_Ready="Create broadcast"
YouTube.Actions.Create_GoLive="Create broadcast and start streaming"
YouTube.Actions.Choose_Ready="Select broadcast"
YouTube.Actions.Choose_GoLive="Select broadcast and start streaming"
YouTube.Actions.Create_Schedule="Schedule broadcast"
YouTube.Actions.Create_Schedule_Ready="Schedule and select broadcast"
YouTube.Actions.Dashboard="Open YouTube Studio"
```

In this case I changed the button for scheduling and readying a stream to say "Schedule and select" to be consistent with how the manual flow for this would work (Choose existing -> select broadcast).

**Comment by Warchamp7** [comment]
> How about the following? Also changes the "YouTube Studio..." string because that doesn't really make sense does it.
> 
> ```ini
> YouTube.Actions.Create_Ready="Create broadcast"
> YouTube.Actions.Create_GoLive="Create broadcast and start streaming"
> YouTube.Actions.Choose_Ready="Select broadcast"
> YouTube.Actions.Choose_GoLive="Select broadcast and start streaming"
> YouTube.Actions.Create_Schedule="Schedule broadcast"
> YouTube.Actions.Create_Schedule_Ready="Schedule and select broadcast"
> YouTube.Actions.Dashboard="Open YouTube Studio"
> ```
> 
> In this case I changed the button for scheduling and readying a stream to say "Schedule and select" to be consistent with how the manual flow for this would work (Choose existing -> select broadcast).

I'm fine with this and I think we should stick with the broadcast verbiage. While it may potentially cause confusion with people used to YouTube calling these things "Streams", I think ultimately it will create less issues than people who have a question and support volunteers have to wrestle with people about what either person means when they say "Stream"

My last nitpick is to swap the position of the two schedule buttons so that the Schedule and Select one is on the right. In all other situations, the left button is the single action create/select and the right button is the double action create/select + stream.

**Comment by derrod** [comment]
> My last nitpick is to swap the position of the two schedule buttons so that the Schedule and Select one is on the right. In all other situations, the left button is the single action create/select and the right button is the double action create/select + stream.

Unfortunately that would be rather annoying, because you'd either have to swap what the buttons do (and reconnect the events) or somehow physically swap them...

> Side nitpick, the option in settings to ask for confirmation when starting a stream currently pops up at weird times during the YouTube flow, since I think it just fires when the Start Streaming button is clicked, regardless of whether it's going to start output

I added a commit to suppress the start confirmation if clicking the button is just going to open the broadcast configuration dialog.

**Comment by derrod** [comment]
After some more deliberations we wanted to go with showing a message box when the user clicks "Start Streaming" rather than opening the configuration dialog to teach them the broadcast flow (as used by YouTube). For the purposes of easier revision it's still a separate commit but will be squashed later.

new dialog

**Comment by Gol-D-Ace** [comment]
Hmm one thing I noticed.
The Manage Broadcast Button only shows up after I started and ended a stream.

What if I don't want to commit to the choosen settings in my first broadcast and want to change something / create a new broadcast?

**Comment by derrod** [comment]
I genuienly don't know how you got into that state, the button should always be visible, and is set to be visible as soon as the OAuth implementation loads.

**Comment by Gol-D-Ace** [comment]
> I genuienly don't know how you got into that state, the button should always be visible, and is set to be visible as soon as the OAuth implementation loads.

Appears to happen when you use autoconfig instead of setting up through the OBS stream settings.

Can confirm this.

Autoconfig no manage broadcast button.
OBS stream settings and the button shows instantly up.

**Review by Warchamp7 — APPROVED** [review]

**Pull request merged**
