### PR TITLE
UI: add option to show all sources to adv audio dialog

### PR DESCRIPTION
**Pull request by exeldro**
### Description
In the advanced audio dialog added the option to show all sources.
image

### Motivation and Context
To adjust audio sync or other audio properties on multiple sources on different scenes at the same time.

### How Has This Been Tested?
On windows 64 bit checking and unchecking the new checkbox.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
Hmm, couple of clarity questions:

* If the user has selected "Hide" in the mixer (via the context menu), does this show those hidden sources?
* Would it be worth having Stinger sources appear when the user toggles this option? I'd vote it would make sense, and finally expose volume control for stingers, but I'm not sure how best to do it - only show when it's the "active" transition, or just list all stingers?
* These are sorted alphabetically, yeah? I worry that it'd be a very long list that's hard to keep track of. Maybe worth grouping them? Active first, then a separator, then hidden on the current scene, then a separator, stingers, separator, then the rest? Not sure.

**Comment by exeldro** [comment]
- It always shows hidden sources, nothing changed there.
- I could add transitions with the OBS_SOURCE_AUDIO flag, but currently no transitions have that flag set, not even the stinger transition. And the stinger transition has an extra property for audio monitoring, which is not changed by calling obs_source_set_monitoring_type. If it is wanted I think it should be a separate pull request.
- The list of sources is sorted alphabetically.

**Comment by jp9000** [comment]
The title and description of the PR feel somewhat incorrect considering the fact that there is no "show all sources" option added.

**Comment by jp9000** [comment]
Ah I see, you just changed the wording from "show all" to "show active only", the feature is still essentially the same.

**Comment by exeldro** [comment]
Updated the screenshot in the first post to show the changes @jp9000 made.

**Comment by jp9000** [comment]
I put the option at the bottom because there was free unused whitespace there, it didn't seem sense to put it at the top because it just created extra unnecessary whitespace and reduced space for the main controls.  I also slightly simplified the text a bit.  I see you asked about that elsewhere earlier but didn't see it until just now.

I changed the active/inactive states on the control from checkboxes to labels because the checkboxes seemed a bit confusing.  I was even confused at first when reviewing it.  Using labels instead makes the meaning much more clear to the user.

I split the PR in to two commits because the changes -- although very relevant to the goal of the PR in this case -- were still separate.  It's very important to try to split things in to as many individual, compilable commits as possible because it makes it much easier to review and makes bugs related to individual changes much easier to track down in case they happen.  Make sure to especially keep that one in mind for future reference because it just makes merging PRs much quicker and much more painless.

**Pull request merged**
