### PR TITLE
CI: Update deps to obs-deps 2022-07-29 release

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

CI: Update deps to obs-deps 2022-07-29 release

Notable changes:
 * Use VS2022
 * Update zlib to 1.2.12
 * Update opus to ab04fbb1b7
 * Update libvpx to 1.12.0
 * Update SVT-AV1 to 1.1.0
 * Update aom to 3.4.0
 * Update x264 to r3095
 * Update mbedTLS to 3.2.1
 * Update libsrt to 1.5.0
 * Update librist to 809390b3b7
 * Update AMF to 1.4.24
 * Update FFmpeg to 5.0.1
 * Update FreeType to 2.12.1
 * Update LuaJIT to 2.1 3065c910ad
 * Update SpeexDSP to 1.2.1
 * macOS: Update Jansson to 2.14
 * Windows: Update libogg to 1.3.5
 * Windows: Update libvorbis to 84c023699c
 * Windows: Update cmocka to bbf5ff7dd5
 * Windows: Update curl to 7.84.0
 * Windows: Update nasm to 2.15.05
 * Windows: Update Python to 3.8.10
 * Qt: Update Qt5 to Qt 5.15.5 for Windows
 * Qt: Update Qt6 to Qt 6.3.1 for Windows
 * Qt: Update Qt5 to Qt 5.15.5 for macOS
 * Qt: Update Qt6 to Qt 6.3.1 on macOS
 * Qt: Backport Windows native scale factor fix

### Motivation and Context

Updated deps fix bugs and require less backported patches. We want these for OBS Studio 28.

### How Has This Been Tested?

I've tested Windows 64-bit builds of OBS against these dependencies with as many tests as I can manage. I only ran into one issue with mbedTLS that has since been fixed in OBS Studio. See https://github.com/obsproject/obs-deps/pull/127 for more details. I have not yet tested these on macOS, so testing there would be appreciated.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Vulkan changed how their SDK installer behave since 1.2.189.2, now 32 bit lib seems have to be installed afterward apparently. 

https://vulkan.lunarg.com/doc/sdk/1.2.189.2/windows/release_notes.html

**Comment by tytan652** [comment]
https://vulkan.lunarg.com/doc/sdk/1.3.216.0/windows/getting_started.html

Seems we have to use the installer in a shell to have 32bit.

**Comment by RytoEX** [comment]
> https://vulkan.lunarg.com/doc/sdk/1.3.216.0/windows/getting_started.html
> 
> Seems we have to use the vulkan installer in a shell to have 32bit libs.
> 
> Edit: Or downgrade to the latest executable that have 32bit libs by default.

I'm just going to revert it. Too much trouble.

**Comment by RytoEX** [comment]
Re-added VulkanSDK 1.3.216.0 update for Windows as requested.

**Pull request merged**
