### PR TITLE
UI: Use styled tray icons

### PR DESCRIPTION
**Pull request by SuslikV**
More like concept than actual solution, but...

### CODE REVIEW

**Comment by dodgepong** [comment]
Can you include a screenshot of what this looks like in the PR description?

**Comment by Vainock** [comment]
@dodgepong it is needed to make the complete PR as 1 commit?

**Comment by dodgepong** [comment]
I just mean that, when it comes to reviewing PRs, it's nice to be able to have a preview of what it is what we are reviewing. It also lets people who can't build the PR see what this change adds.

**Comment by Vainock** [comment]
I'm sorry for my bad wording. I mean generally, it is needed to make the complete PR as one commit? I fully understand why do you want to have a screenshot to see the changes.

**Comment by dodgepong** [comment]
It's not mandatory to make PRs 1 commit. Rather, we ask that you group logical changes together into single commits. So, for example, if you make a change, commit it, and then change it again and commit it again, those two commits should be squashed together. Commits should be thought of as individual sets of logically grouped changes. Sometimes that means one commit for the PR, sometimes it means multiple if the PR does several different things.

**Comment by Vainock** [comment]
@dodgepong I understand. Thank you very much!

**Comment by SuslikV** [comment]
The tray icon is small picture of OBS Studio emblem placed at place where the watches usually shown:

DarkNormal_result
DarkActive_result

AcriNormal_result
AcriActive_result

RachniNormal_result
RachniActive_result

Actually, it was never asked and never mentioned (maybe just few times) that tray icon should be styled in obs. And I just drawn new tray icons for themes to test if it updates the values, and to show possible syntax. Images not accurate (ugly, yeah) and should be replaced by better pictures. It is not about pictures itself but rather about the used method. It is not perfect but I didn't found a better one. Maybe mark this PR with "question" label?

So, is this needed in obs? I mean the possibility to specify system tray icon for any obs theme? And what about the invisible labels near the central widget that is placed there just to store pixmaps and .qss for importing pixmaps - are you OK with this?

The PR will be removed sooner or later.

**Comment by SuslikV** [comment]
I can use these instead:
obs-tray-icon-01-08

If you like it, you can say which would you like to see for which theme. Two icons per theme - active and normal (themes: Default, Dark, Acri, Rachni). Any thoughts? (I'll attach .svg source later)

**Comment by SuslikV** [comment]
1. Logic to update icons on Theme change was fixed (to use System's icons, if OS supports them, instead of ignoring them).
2. Icons pictures was updated to SVG files (instead of PNG) and replaced with mentioned above variants:
>(01, 02) - Dark;
>(03, 04) - Rachni;
>(07, 08) - Acri;
>Default - uses internal resources storage.

History was modified... :(

**Comment by jp9000** [comment]
I personally would prefer not to modify the tray icon for themes.  Thanks though.

**Pull request closed without merging**
