### PR TITLE
rtmp-services: Add sympla

### PR DESCRIPTION
**Pull request by vfernandes-sympla**
### Description
Add rtmp input configuration with recomendation

### Motivation and Context
We would like to add sympla on obs with facility

### How Has This Been Tested?
Choose Sympla Input and add private key 
78f75ccb-3fa3-fc7d-7085-f060bb28fa99

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Please amend your commit:
- `feat:` is not a valid prefix. `rtmp-services:` is more accurate.
- The package.json version number must be incremented. Example: <https://github.com/obsproject/obs-studio/commit/cfd8b2daf1f6ac36c82f358515f58a3d0dd497cf>

**Comment by RytoEX** [comment]
Please review the [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).

**Comment by RytoEX** [comment]
> > Please amend your commit:
> > 
> > * `feat:` is not a valid prefix. `rtmp-services:` is more accurate.
> > * The package.json version number must be incremented. Example: [cfd8b2d](https://github.com/obsproject/obs-studio/commit/cfd8b2daf1f6ac36c82f358515f58a3d0dd497cf)
> 
> fixed

You changed the Pull Request title, not the git commit message prefix. Please squash your commits and use the correct prefix as requested above.

**Comment by norihiro** [comment]
You don’t need to close and create another pull request. You can “force push” your revised commit.

**Pull request closed without merging**
