### PR TITLE
obs-amf: Enables a pipeline for texture-based encoding with AMF.

### PR DESCRIPTION
**Pull request by OvchinnikovDmitrii**
### Description
Adds h264 and hevc texture-based encoders that work via AMF. They are available for selection in advanced settings and does not affect existing AMF encoders.

Updated version of https://github.com/obsproject/obs-studio/pull/4228
-Fixed remarks on the previous version
-Changed the default values of some properties
-Removed unnecessary logging

### Motivation and Context
To increase the encoding speed.

### How Has This Been Tested?
Hardware: Radeon RX Vega 64 | AMD
Operating System: Windows ver. 1809
I recorded the video using new encoders and different settings, and checked the result

### Types of changes
New feature
Performance enhancement

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
Usually we recommend force-pushing to the original branch which updates the original PR, rather than opening a second PR.

**Comment by Pablomx2** [comment]
This PR doesn't 100% work on my 6700 XT using 21.6.1 drivers. Only the recording and low latency presets work and they don't work when you downscale in video settings
If you change something in their settings, DirectX breaks and it doesn't start the encoder, then OBS hangs, here's a log of when it hangs: [2021-08-16 14-31-05.txt](https://github.com/obsproject/obs-studio/files/6995904/2021-08-16.14-31-05.txt)

**Comment by Pablomx2** [comment]
Also, I noticed that the quality of the encoder does improve a lot by how VBAQ works with the newer SDK. Hopefully you can update this to v1.4.21.0

**Comment by flaeri** [comment]
Hello! :)

Driver: 21.6.1
AMD Ryzen 5 4500U APU

I've compiled this PR togheter with the laters master as of 16.08.2021 (yesterday).

1. Really needs to log information about the encoder settings/options. This is crucial for support, as we need to know what options have been selected.
2. Missing some critical features like user set QP in CQP mode
3. pre-encode option hangs the encoder. (which is enabled by default in the Streaming preset)
Log: https://obsproject.com/logs/OYBV_IxdnEpjwz5t
4. OBS crashes if you attempt to use i444 color format -> encode.
	https://hastebin.com/ocipicusaj.apache

As for @Pablomx2's findings, I have no problems scaling, or changing settings. Only the pre-encode option makes it blow up.

**Comment by OvchinnikovDmitrii** [comment]
Hello! thank you for your review and research. I added logging of properties, from obs_data_t and the encoder itself for LOG_LEVEL >= DEBUG and corrected some places in the code. In the next commit, I will try to fix the other issues as well.

**Comment by cs9kc** [comment]
Hello!  I'll try to see if I can get a build going with the current changes in it, to test things out.  I have an RX 6900 XT on 21.12.1.  

It appears that you have incorporated AMF 1.4.21 into this code, which is excellent!  Keep up the good work, @OvchinnikovDmitrii!  I'm looking forward to this being rolled into OBS Studio proper, as well any newer versions of AMF that you may work on.  <3

**Comment by e00E** [comment]
Since this came up on Discord again today. I also made a rewrite of this plugin. See https://github.com/obsproject/obs-amd-encoder/issues/426 .
Btw I feel this PR should go to that repository too (obsproject/obs-amd/-encoder) instead of directly to this repository as the other one is already submoduled into here and the code in this PR builds on the code in the other repo.

**Comment by WizardCM** [comment]
> Btw I feel this PR should go to that repository too (obsproject/obs-amd/-encoder) instead of directly to this repository as the other one is already submoduled into here and the code in this PR builds on the code in the other repo.

Our goal is to phase out submodules where they're not strictly necessary. I'm personally ok with archiving the amd encoder submodule and merging this pr directly once it's reviewed and in a good state.

**Comment by Zeioth** [comment]
Currently I can encode videos with AMF on arch linux after installing the package amf-amdgpu-pro.

But I can't select it for video streaming on twitch (only x264/vaapi are listed)

**Comment by RytoEX** [comment]
Superseded by #6508.

**Pull request closed without merging**
