### PR TITLE
UI: Fix portable mode detection on Linux

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Fixes broken portable mode detection for configuration file resolution introduced by the CMake rework.

### Motivation and Context
UI code uses both simple checks for a preprocessor define as well as boolean checks inside an `if`-conditional.

The define will be always set however (albeit using an empty string if the build flag is not enabled), which breaks both kinds of checks (an empty string always resolves as `true` and "defined").

With this change, the variable is not set if the build flag is not enabled and only simple `ifdef` checks are used.

### How Has This Been Tested?
* Tests on Linux VM pending

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Checked the code in my VM - without `LINUX_PORTABLE` the app uses the default config path (in my case at `${HOME}/.config`) regardless of the command line switch.

With `LINUX_PORTABLE` enabled, only passing `--portable` triggers the desired behaviour: OBS uses a config subdirectory two levels above the binary.

**Review by RytoEX — APPROVED** [review]
@notr1ch approved off-thread. Looks fine to me too.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Ah, one commit message nit:
maco -> macro

**Comment by PatTheMav** [comment]
> Ah, one commit message nit:
> maco -> macro

Should be fixed now.

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
