### PR TITLE
libobs: Fix reading memory past size of string

### PR DESCRIPTION
**Pull request by Aries1989**
### Description

(edited by Jim)

Fixes a crash.

### Motivation and Context

The depad functions haven't been tested with cases where the padding is at the front of the string, thus when padding at the front of the string, it could read more memory than it was supposed to, causing a possible crash.

### How Has This Been Tested?

Tested with a string that had spaces in the front.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please use the Discord or Forums for support.

https://obsproject.com/help

**Comment by Fenrirthviti** [comment]
Apologies, I thought this was an issue based on the title. Please correct this PR to include a description, motivation, testing, etc. and update to follow our contribution guidelines.

**Comment by Aries1989** [comment]
the first time to contribute. may be don't konw how.
wish you help fix it;

**Comment by Fenrirthviti** [comment]
Start by properly filling out the issue template, and reading through the contribution guidelines (linked in the template) and we can go from there.

**Comment by Aries1989** [comment]
got it. 3ks

**Comment by exeldro** [comment]
For the title of the pull request and the commit message you can look at previous changes on the same file.
For this PR I would set it to something like: `libobs/util: Fix memmove size in depad functions`

**Comment by jpark37** [comment]
wcsdepad seems to consider fewer characters as padding. Might be worth aligning the two functions.

**Pull request merged**
