### PR TITLE
libobs: Cleanup uses of objc_msgSend in Objective-C code

### PR DESCRIPTION
**Pull request by tbodt**
### Description

- Use objective-c message syntax instead of calls to objc_msgSend. The resulting code is much shorter.
- Remove use of deprecated [NSProcessInfo operatingSystem]. It always returns NSMACHOperatingSystem.
- Stop parsing [NSProcessInfo operatingSystemVersionString]. The documentation explicitly says "not for parsing".

### Motivation and Context
It reduces the number of lines of code in the project

### How Has This Been Tested?
Build and run on macOS 10.15

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Could you please fill out the PR template?

**Comment by tbodt** [comment]
Sorry I missed that. I created the PR with the `hub` CLI tool which apparently ignores the template.

**Comment by PatTheMav** [comment]
Overall compiles fine, OS version is printed correctly but I'm not entirely sure how to test the mouse button press thing, but I didn't notice any weird behaviour.

**Comment by tbodt** [comment]
I think you would set up a hotbed on a mouse button? Not sure how that works.

**Comment by jp9000** [comment]
If you hotkey a mouse button you should be able to test it.

**Pull request merged**
