### PR TITLE
UI: Use more descriptive tooltips

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This makes the scene/source tooltips easier to
understand.

Add -> Add Scene, Add Source
Remove -> Remove Selected Scene, Remove Selected Source(s)
MoveUp -> Move Scene Up, Move Source(s) Up
MoveDown -> Move Scene Down, Move Sources(s) Down
Properties -> Open Source Properties
Filters -> Open Source Filters

### Motivation and Context
The tooltips were vague.

### How Has This Been Tested?
Made sure the tooltips showed up as expected.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Does this just affect visual tooltips or will screen readers also read this new text?

**Review by Warchamp7 — APPROVED** [review]
I think as long as we're being more verbose with this, it may be worthwhile to have Properties and Filters as a full phrase such as "Open Source Properties"

Otherwise LGTM

**Comment by WizardCM** [comment]
> I think as long as we're being more verbose with this, it may be worthwhile to have Properties and Filters as a full phrase such as "Open Source Properties"
> 
> Otherwise LGTM

@cg2121 I second this review. Outside of that, I've tested this PR and it works well.

**Comment by cg2121** [comment]
Updated to 'Open Source Properties' and 'Open Source Filters'

**Review by RytoEX — APPROVED** [review]
Discussed off-thread. Reviewed local build and approved.

**Pull request merged**
