### PR TITLE
libobs: Render audio for all views

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Render audio for all views

### Motivation and Context
At the moment you can add views to obs via `obs_view_add` or `obs_view_add2`, but the audio for those views was not rendered.
Not rendered audio causes transitions not to finish and scenes to forever wait on audio to deactivate sources.

### How Has This Been Tested?
With the vertical plugin on windows

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Wouldn't this mean that audio for a source on one view and not on the main program mix would play anyway on the audio feed from that mix?

**Comment by exeldro** [comment]
No, all audio stays on its own view.
All audio sources are always rendered, this only makes scenes and transitions that are on other views mix their audio so that view works correctly and allows to use the audio for that view (which is not required).

**Comment by exeldro** [comment]
comment style fixed and empty newlines added

**Review by tt2468 — APPROVED** [review]

**Comment by PatTheMav** [comment]
If I understand correctly, this change ensures that audio is rendered (but not output) for all sources even if they are not visible or part of an active output, because many sources rely on the audio render loop happening?

**Comment by derrod** [comment]
This PR still skips inactive sources, but checks all views instead of only the main one. So if you happen to have another view, say with the [vertical output plugin](https://obsproject.com/forum/resources/aitum-vertical.1715/), it will also render the audio on that view.

**Comment by PatTheMav** [comment]
Yep I saw the check for inactive sources, so I guess this should be good to merge?

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
