### PR TITLE
obs-ffmpeg: Remove unexposed vaapi parameters

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

In ffmepg 4.2 setting qp overrides bitrate, this option isnt exposed
currently so users cannot disable it.

### Motivation and Context

https://obsproject.com/mantis/view.php?id=1534

### How Has This Been Tested?

Tested on ubuntu 18.04 with ffmpeg 4.1, no regression when recording. Someone with an affected device on ffmpeg 4.2 has confirmed this resolves the issue.

### Types of changes

Removal of some settings, users might have tried to use them via json but they probably wouldnt have worked.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by dribbleondo** [comment]
I can confirm that QP overrides bitrate, and removing QP makes the videos more stable. I found this out when working on a patch to add more vaapi properties (VBR and profile support!) to properties. No matter what I tried, QP would _always_ override bitrate, even when CBR or VBR was set as the encoder.

I tried extensively to disable it when the other two encoders were active, but had no luck. I Think i'll make a commit of this tomorrow if I can.

**Comment by kkartaltepe** [comment]
Thanks. Profile support was removed because the most common AMD hardware on the most common platforms (ubuntu/debian) didn't (still doesn't as of a few weeks ago) support any other profiles and no one upstream (ffmpeg/radeonsi) appears to care enough to disable it (ffmpeg) or properly report profile support (radeonsi). Though it does make a significant performance and quality difference on most platforms that support it unfortunately.

If you happen to be have AMD hardware that supports initializing non-baselineconstrained profiles may I ask what you are using?

**Comment by dribbleondo** [comment]
> If you happen to be have AMD hardware that supports initializing non-baselineconstrained profiles may I ask what you are using?

AMD Ryzen 5 1500x and an RX 470. It's possible the profiles don't work correctly due the code (it's literally `FF_PROFILE_H264_MAIN` and `FF_PROFILE_H264_HIGH` added to the profiles dropdown in obs-ffmpeg-vaapi.c, which should be enough to enable said options). Most of my testing was done prior to this ["vaapi profiles fix" commit](https://github.com/obsproject/obs-studio/pull/2168). I'm currently re-testing the profile settings to see if a stress-test breaks support, or if it's just using constrained baseline as a fallback. I'll report back.

**Comment by kkartaltepe** [comment]
Please provide your tests that its working on your machine and how others may test. Per https://github.com/obsproject/obs-studio/pull/1256#issuecomment-380642787 we used this as a simple test of functionality https://gist.github.com/kkartaltepe/401b79556950a123f22f09aaec9a8fee (100 is main, 77 is high). Id be happy to replicate any tests on intel hardware if you find more profiles working on your AMD hardware. But we also need users of the RX 500 series before at least I feel comfortable giving AMD users more footguns.

This really isnt the best place to discuss this. Feel free to make a mantis ticket or a WIP/Draft PR for somewhere to discuss this.

**Comment by CaffeinatedTech** [comment]
I've got an RX580 I can help test with.  I did have trouble with the portable build of this branch not loading the linuxbrowser sources, but its probably something I'm doing wrong.  The VAAPI encoding was good though.  Let me know what you want me to try.

**Comment by aufkrawall** [comment]
At this occasion: It would be nice if all VAAPI options offered by ffmpeg would be available in the OBS UI.
E.g. you can't select HEVC, global quality bitrate mode etc.

**Comment by jp9000** [comment]
If anyone could report back how this is working, we would be grateful.

**Comment by CaffeinatedTech** [comment]
We've already reported back on the mantis ticket https://obsproject.com/mantis/view.php?id=1534 2 weeks ago.

**Comment by dribbleondo** [comment]
@aufkrawall Someone tried commiting HEVC support, but was denied due to not wanting to support HEVC as an industry standard (which it kind-of already is), in favor of VP9 (which VAAPI supports regardless.)

**Pull request merged**
