### PR TITLE
Expose more levels and profiles for FFmpeg VAAPI

### PR DESCRIPTION
**Pull request by dgcampea**
### Description
This change adds Profile and Extra options to FFmpeg VAAPI output.
Profile
Level

### Motivation and Context

With certain resolutions (such as 3440x1440), using an inappropriate level not only fails to produce output, it can trigger strange behavior on the kernel (witnessed with dmesg, using level 4.2, the highest supported before this patch).
FFmpeg allows specifying level -99 (defined by FF_LEVEL_UNKNOWN macro) which instructs it to decide the appropriate level automatically.
The level names were removed since they are not accurate representation of what the level means. This assumes that whoever decides to tune with it knows what they're doing.
Encoding profiles were also exposed to allow more flexibility (instead of being restricted to CONSTRAINED_BASELINE).

### How Has This Been Tested?

Fedora 31, Mesa 20.0.1, AMD Fury X.
Recorded desktop and HDMI capture card.

### Types of changes

- New feature

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Before id be willing to support this we would need a diverse number of testers specifically on amd hardware (rx480, rx580, and whatevers popular now) and various kernels (debian (10 and testing), ubuntu(18.04 and 20.04 if possible), arch/fedora). Testers on intel hardware will also help.

Specifically testing 720p30/60,1080p30/60 with automatic level select (as well as the compatibility 4.0)  at each of the profiles now exposed. Recordings should then be tested in players like `mpv` to see that the resulting stream is not corrupt. 

Id prefer the results in a table noting if the recording was successful, recording was corrupted, or encoder failed to initialize. Also include your Distribution, Kernel version, GPU model, and Driver and version (All of these are available near the top in the OBS log if you run from terminal or via  the gui in Help -> Log Files -> View current logfile)


e.g. a good report would look like:
```
(from obs logfile)
Kernel Version: Linux 5.5.13-arch1-1
Distribution: "Arch Linux" Unknown
info: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 440.64, shading language 3.30 NVIDIA via Cg compiler

Res, fps, level, 
720, 60, auto, baselineconstrained, Works 
720, 30, auto, baselineconstrained, Works
720, 60, auto, main, Corrupt
4k, 60,  4.0, high, Failed
...
...
```

**Comment by kkartaltepe** [comment]
Known broken configurations include basically any `high` profile on R9 200 through RX580 series hardware producing corrupt streams that might play on software decoders but break in most every other setting.

**Comment by dribbleondo** [comment]
Since I have some free time, I'll get on testing this.

I'm on Mint 19.3, running an a Ryzen 5 1500x and a RX470 4GB. I'll test this on the latest stable kernel I can (5.3-45) and i'll report back with a log in the coming days.

**Comment by kkartaltepe** [comment]
Here is my report for intel hardware, ubuntu 19.10. 
Testing against twitch.tv streaming.

```
info: Kernel Version: Linux 5.3.0-45-generic
info: Distribution: "Ubuntu" "19.10"
info: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
info: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 19.2.8, shading language 4.50

Res, fps, level,  profile, result
720, 30, auto, blc, ok
720, 30, 4.0,  blc, ok
720, 30, auto, main, ok
720, 30, 4.0,  main, ok
720, 30, auto, high, ok
720, 30, 4.0,  high, ok
720, 60, auto, blc, ok
720, 60, 4.0,  blc,  ok
720, 60, auto, main, ok
720, 60, 4.0,  main, ok
720, 60, auto, high, ok
720, 60, 4.0,  high, ok
1080, 60, auto, blc, ok
1080, 60, 4.0,  blc, ok
1080, 60, auto, main, ok
1080, 60, 4.0,  main, ok
1080, 60, auto, high, ok
1080, 60, 4.0,  high, ok
```

Looks good for intel hardware, though that was the least of my concerns unfortunately.

**Comment by sat3ll** [comment]
In the case of H.264, AMD decoders only seem to go up to 5.2 (https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support). It's possible that Intel also only goes so far.
Levels 6.0 and above only make sense for HEVC which there is no support. 
I went ahead and amended the commit to reflect this.

**Comment by dgcampea** [comment]
In the case of H.264, AMD decoders only seem to go up to 5.2 (https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support). It's possible that Intel also only goes so far.
Levels 6.0 and above only make sense for HEVC which there is no support.
I went ahead and amended the commit to reflect this.

**Comment by admshao** [comment]
`info: CPU Name: AMD Ryzen 7 3800X 8-Core Processor
info: CPU Speed: 3682.172MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 32113MB Total, 6854MB Free
info: Kernel Version: Linux 5.5.13-arch2-1
info: Distribution: "Antergos Linux" Unknown
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: OBS 25.0.3-20-gdbb453d00 (linux)
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD NAVI10 (DRM 3.36.0, 5.5.13-arch2-1, LLVM 9.0.1)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.4, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: DEPENDS
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available

Res, fps, level,  profile, result
720, 30, auto, blc, ok
720, 30, 4.0,  blc, ok
720, 30, auto, blc, ok
720, 30, 4.0,  main, ok
720, 30, auto, high, ok
720, 30, 4.0,  high, ok
720, 60, auto, blc, ok
720, 60, 4.0,  blc,  ok
720, 60, auto, main, ok
720, 60, 4.0,  main, ok
720, 60, auto, high, ok
720, 60, 4.0,  high, ok
1080, 60, auto, blc, ok
1080, 60, 4.0,  blc, ok
1080, 60, auto, main, ok
1080, 60, 4.0,  main, ok
1080, 60, auto, high, ok
1080, 60, 4.0,  high, ok`

**Comment by kkartaltepe** [comment]
Thanks a lot shaolin. Im hoping we can get some older kernels and cards tested as well. Its very promising that we newer cards dont appear to have the high profile issues and can stream to twitch successfully.

**Comment by dribbleondo** [comment]
Also tested with MPV: 

I've known for a while doing 60FPS recording at 720p is very much game-dependant (the results below are from just 20 seconds clips of me shaking the OBS window around), and 1080p 30/60 has encoding lag regardless. It may be something to do with upstream FFMPEG, or perhaps with Mesa.

Hope this helps!

```
CPU Name: AMD Ryzen 5 1500X Quad-Core Processor
Physical Cores: 4, Logical Cores: 8
Physical Memory: 7973MB Total, 3012MB Free
Kernel Version: Linux 5.3.0-45-generic
Distribution: "Linux Mint" "19.3"
OBS 25.0.3-15-gd002345a (linux)
Loading up OpenGL on adapter X.Org AMD Radeon (TM) RX 470 Graphics (POLARIS10, DRM 3.33.0, 5.3.0-45-generic, LLVM 9.0.1)
OpenGL loaded successfully, version 4.2 (Core Profile) Mesa 20.1.0-devel (git-7df7520 2020-03-29 bionic-oibaf-ppa), shading language 4.20

-------------------------------------------

Res - fps - level - profile - bitrate - result
720, 30,    auto,    cbl,      2500       ok 
720, 30,     4.0,    cbl,      2500       ok
720, 30,    auto,   main,      2500       ok
720, 30,     4.0,   main,      2500       ok
720, 30,    auto,   high,      2500       ok
720, 30,     4.0,   high,      2500       ok
720, 60,    auto,    cbl,      2500       ok
720, 60,     4.0,    cbl,      2500       ok
720, 60,    auto,   main,      2500       ok
720, 60,     4.0,   main,      2500       ok
720, 60,    auto,   high,      2500       ok
720, 60,     4.0,   high,      2500       ok
1080, 60,   auto,    cbl,      2500       frame drops
1080, 60,    4.0,    cbl,      2500       severe frame drops
1080, 60,   auto,   main,      2500       severe frame drops
1080, 60,    4.0,   main,      2500       frame drops
1080, 60,   auto,   high,      2500       severe frame drops
1080, 60,    4.0,   high,      2500       severe frame drops
```

**Comment by kkartaltepe** [comment]
Please also test some of the high profiles streaming to twitch or youtube to ensure they are accepted by ingests. Thanks a bunch for testing.

**Comment by dribbleondo** [comment]
I can confirm all the profiles you added get accepted by Twitch's ingest, though I fail to see a need to go so high (6.0+ is normally for 4K recording, which seems like overkill).

**Comment by jonhoo** [comment]
I can confirm that High works well on my end on a AMD Radeon RX 5500 XT. Also seeing some major wins in video quality and file size!

**Pull request merged**
