### PR TITLE
UI: Implement UI collections

### PR DESCRIPTION
**Pull request by Programatic**
### Description
This adds ui collections commonly referred to as "workspaces". It allows you to create mutliple different formats and easily switch between them.

### Motivation and Context
It simply allows for more flexibility when using OBS for different purposes. It implements the suggestion found here: https://ideas.obsproject.com/posts/615/ui-collections

### How Has This Been Tested?
I tested it on my Linux machine but nothing else yet.

### Todo
- Needs testing
- Implementing Import/Export (foundation is there from scene collection but I haven't touched it yet)
- Need to add more configurables being saved
- Need to work on how the configs are saved and loaded
- Rename to workspaces
- Add API
- Possibly will implement hotkeys

### Known Bugs
- [x] Misbehaves when working with custom browser docks
- [x] Startup gives unnecessary reset ui notification
- [x] Stores window position as well
- [x] completely ignores old configuration so user would have to start from scratch
- [x] Memory Leaks

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
Brainstorming names would be a good idea too:
* UI layouts
* Dock Layouts (I like this one, personally)
* UI Collections
* Workspaces

**Comment by dodgepong** [comment]
I want to be careful around the "layout" terminology because it can be misconstrued as a layout for the scene itself (i.e. source layouts/templates). I like "Workspaces", though I admit "Dock Layouts" may also work.

Another possibility might be related to "Workflow", as I envision many people wanting to have a "Pre-production" setup and a "Live" setup, such that docks are in different places with different visibilities based on whether you're live or not.

Just some brainstorming. Very cool feature (though admittedly I haven't tested it yet).

**Comment by Programatic** [comment]
I really like the 'Workflow' idea because that is what I would imagine would be the dominant use case

**Comment by mufunyo** [comment]
Just want to throw it out there that Adobe calls this function "Workspace" as well in its products.

**Comment by jp9000** [comment]
- Clang-format wasn't run on all the files.
- If you modify a UI collection, then switch away, then switch back, the modifications don't appear to have been saved.

I don't really know how I feel about this PR.  I feel like this feature is going a bit too far beyond what I'd prefer.  That and having three different save data collections (profiles, scenes, and now UI).  It makes things more confusing for users than it already is.  I feel like this moves away from my personal goal of improving UX, which makes me feel very uncomfortable.

**Comment by dodgepong** [comment]
I think the feature absolutely has value, and is a feature found in many other similar creative programs. I think working out a way to simplify profiles vs. scene collections vs. workspaces is reasonable but I don't think that's a reason to deny this feature.

I would argue that it improves UX by giving users a way to customize the tools available to them depending on the context of how they are using the program. It will help users _simplify_ their UI, not make it more complex.

**Comment by jp9000** [comment]
Give me an example of how it helps simplify their UI.

**Comment by jp9000** [comment]
Nevermind, I looked at the ideas page and I suppose I can see how this would be useful in some circumstances.  But I can't help but to feel uncomfortable with adding another menu to the main menu bar.  The experience a new user has is one of my personal concerns.  I feel like I'd rather this be a part of the docks menu, or something that's inherently linked up to profiles.

It may have to be something that's profile-based anyway, because there's already a separate UI save mechanism for profiles when connecting accounts.  I think making it a profile-specific thing makes more sense for that reason and streamlines the entire thing.

**Comment by dodgepong** [comment]
If a new user completely ignores this menu then they will have the exact same experience that they have now. This is why I want to make sure it's named something that will be familiar to new users so that if they see the menu item, they will be more likely to understand what the feature is without having it explained to them.

> I think making it a profile-specific thing makes more sense for that reason and streamlines the entire thing.

Do you mean that the set of available UI collections should be tied to a profile?

**Comment by jp9000** [comment]
I mean that it makes more sense to me that a UI configuration is bundled with a profile, rather than it being a completely separate thing.  That seems to make the most sense judging upon what people seem to use these dock configurations for.  For example on the ideas page, they say they'd like to have it small so it's specific to recording, and that feels like it'd make more sense to just be a part of the profile in that case rather than a separate menu.

Regardless of what it's named, the problem I have with it being a separate menu is that any extra thing on the main UI can intimidate the user.  I already feel somewhat uncomfortable with the separation of profiles and scene collections as it is.  I feel like scene collections should really have been its own dock if anything.

**Comment by WizardCM** [comment]
I agree that tying it to the Profile is a fair compromise. The main downside would be the inability to have "Editing" and "Live" layouts tied to one profile, but that could be worked around by having a dummy profile with the same canvas resolution as the live one.

**Comment by jp9000** [comment]
Anyway, that's not the sole reason why I want to tie it to profiles.  The other reason is as previously stated, account connections basically invoke their own profile-specific UI layout due to the fact that account connections add chat docks and things like that.  So already there's going to be a conflict between having a separate one and having the existing pseudo-profile one.  I think from a architectural point of view it makes more sense to just utilize the existing pseudo-profile UI layout and make it non-pseudo instead.

**Comment by dodgepong** [comment]
Whatever happens, what I don't want is a one-to-one mapping of one workspace per profile, such that changing to a different workspace would require changing profiles. That would utterly defeat the whole point of the feature.

**Comment by jp9000** [comment]
Listen, the problem is that there's already a workspace associated with the file, and it has to do with account connections.  They can't easily be unlinked.  Architecturally with the way it's currently designed it makes more sense for it to be stored as profile data, because technically it already is if you have an account connected.

**Comment by dodgepong** [comment]
If we can't switch workspaces without switching profiles, then perhaps we should shelve this until that design flaw can finally be rectified, probably as part of the long-awaited outputs refactor.

**Comment by mufunyo** [comment]
Yeah tying workspaces to profiles seems like a stifling limitation.

**Comment by RytoEX** [comment]
I agree with @dodgepong and @mufunyo that tying workspaces to profiles would not be ideal.  I only have a handful of profiles, and I think that it would be too cumbersome to have to create duplicate profiles for each workspace.  UI layouts (workspaces) should not be dependent on what profile you've selected or what account you've linked.  If that can't be done with the way profiles and accounts work now, then maybe it needs to wait until account connections are not tied to profiles or are otherwise reworked.

**Comment by Programatic** [comment]
I apologies for the neglect on this, I have 3 finals day after day so I am busy atm. If you would prefer, I can draft up a RFC with some possible solutions. I can understand why you would prefer to link it to profiles. The reason I put it in its separate tab is because I was thinking that you could have multiple different configurations setup that would be usable across different profiles. This prevents redundancy and reduces the mental overhead for the user. I understand your reservations, I just think it would be a pleasant productivity boost for users who use OBS for various different purposes and it allows them for much more flexibility.

**Comment by Fenrirthviti** [comment]
I'd also like to throw in my support for these being separate. They could potentially be nested in the View menu to keep clutter down, but I think keeping a UI collection separate from profile is an important aspect of the feature. We had someone in the Discord who wanted to be able to save different layouts for their multiview, which might make sense to live as part of the workspace or whatever it will be called.

**Pull request closed without merging**
