### PR TITLE
UI: Add overload notifications

### PR DESCRIPTION
**Pull request by cg2121**
If the OBS window is visible then a message box pops up, else if the window is not visible a system tray notification will appear.

screenshot from 2018-11-12 20-24-45
screenshot from 2018-11-12 20-19-54
screenshot from 2018-11-12 20-18-08

### CODE REVIEW

**Comment by Heufneutje** [comment]
I would argue having them opt-out would be better since these can be extremely helpful for new users.

**Comment by SuslikV** [comment]
Not needed at all. User should use _Stats_ window.
You can implement this as huge tooltip for the Stats or Status bar, for example.

**Comment by Heufneutje** [comment]
A new user may not necessarily think to look at the stats window is what I'm thinking. A status bar notification sounds look a good solution though. That's less intrusive than a message box while still informing the user there's a problem.

**Comment by SuslikV** [comment]
@Heufneutje but the status bar warning already exist...

**Comment by WizardCM** [comment]
Personally I feel this is a good step in the right direction, but it should only be considered the first step.

I agree with @kkartaltepe that popups are bad, and that there should be an option to disable it (but enabled by default is important!). Popups require attention. I do like that this system uses the system notifications instead of the popup if OBS isn't focused, however Windows 10 (for example) automatically silences notifications when a game is running, so the user wouldn't see these.

I vote for the end result being a toolbar, either at the top or the bottom, that has to be manually dismissed. It should be a bright colour that stands out, so that if/when the streamer looks over to OBS, it's immediately noticeable, or if OBS is in the corner of their eye, it stands out and grabs their attention.

Other people on Discord mentioned that when we eventually have an in-game overlay that this would be a great thing to have there, and I agree - showing something to the user mid-stream is tricky as their attention is taken up by the game + alerts + chat + any voice chat they're in. Doing it in an overlay would also mean it'd be front-and-center for the user AND it wouldn't be visible to viewers.

@SuslikV The status bar only warns about the encoder overloading, not about dropped frames or low FPS. It also doesn't stand out enough, and isn't long enough to fit informative messages.

**Comment by DDRBoxman** [comment]
What about integrating into the OS specific toast APIs instead of an alert dialog?

**Comment by SuslikV** [comment]
@WizardCM so, you missed the green/red square of the status bar, that only means that is not required too, and has unknown meaning for the end user.

In general, - how it can help to the user, these notifications I mean?
Let's learn the users to use the stats. At least, it's dockable window now... What sense was to make it dockable then?

**Comment by Heufneutje** [comment]
That's like saying the stats window's only reason for being dockable is to teach new users what the stats are for. Which is surely not the case.

**Comment by jp9000** [comment]
Dialogs could be bad, and could take a user out of a fullscreen game or something unintentionally.  I think having some sort of system alert or toast thing like @DDRBoxman was saying would be ideal -- a big but very noticeable notification.  I would encourage you (or anyone willing) to experiment to see what they feel works best.

**Comment by jp9000** [comment]
Additionally, it's important that the frequency of the notifications isn't high.  Also, we may have to try to find a way to do it without sound, so the user can see it pop up noticeably, but not necessarily have it be captured on a stream or recording.  I'm not entirely sure how to approach that however.  Any ideas/suggestions would be welcome in that regard.  (We could also make our own toast/notification popup widgets for example)

**Comment by dodgepong** [comment]
> Any ideas/suggestions would be welcome in that regard.

In-game overlay? 😐

**Comment by jp9000** [comment]
We absolutely need a solution to this, but popups aren't ideal.  We need to try something else.

**Comment by jp9000** [comment]
Let me clarify: modal popup message boxes aren't ideal.  Maybe a pop up window might work, but we need to try other things than modal message boxes.

**Pull request closed without merging**
