### PR TITLE
Only register available PipeWire captures

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
### Description

Don't register captures (window, desktop) that are not supported by the portal implementation. Also, don't create new D-Bus connections and proxies for each capture - do it only once, globally, and reuse these objects.

### Motivation and Context

This was originally noticed at https://github.com/obsproject/obs-studio/issues/4815 - we shouldn't show captures that are not supported by the portal implementation. The fix for this issue made realize we could add an extra optimization on top of it.

### How Has This Been Tested?

 - Open OBS Studio on any wlroots-based compositor (e.g. Sway)
 - Observe that "Window capture (PipeWire)" is not shown

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)
 - Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Would you say that this fixes #4815 as far as OBS is concerned?  Or is there something more we should do?

**Comment by GeorgesStavracas** [comment]
I was hesitant to claim this PR *fixes* it, because it can only truly be fixed by xdg-desktop-portal-wlr implementing window capture. However, I guess it can be considered wrong to allow adding capture sources that are not supported by the compositor - it makes people think it should work, when in fact it shouldn't. I don't think there's anything else that can be done on OBS side beyond this.

**Comment by RytoEX** [comment]
If this fixes it on the OBS side as much as we can, then I would consider the remaining issue to be an upstream feature request, which is out of scope for our GitHub Issues.

**Comment by Omar007** [comment]
Tested on Sway + xdg-desktop-portal-wlr; https://github.com/obsproject/obs-studio/issues/4815#issuecomment-860859978  
LGTM.

@RytoEX  This was more of a tangent. I.r.t. the OG issue of said ticket, I was going to close it if I was able to reproduce it outside of OBS but hadn't gotten around to setting that up yet. If you want to close it now I suppose I can also just re-open it when it turns out it can't be reproduced outside of OBS :thinking:

**Comment by RytoEX** [comment]
> 
> 
> Tested on Sway + xdg-desktop-portal-wlr; [#4815 (comment)](https://github.com/obsproject/obs-studio/issues/4815#issuecomment-860859978)
> LGTM.
> 
> @RytoEX This was more of a tangent. I.r.t. the OG issue of said ticket, I was going to close it if I was able to reproduce it outside of OBS but hadn't gotten around to setting that up yet. If you want to close it now I suppose I can also just re-open it when it turns out it can't be reproduced outside of OBS 🤔

Yes, I read that comment.  I think it's fine to close that issue after this is merged, or after it's confirmed that #4815 is definitively not an OBS issue.

**Pull request merged**
