### PR TITLE
UI: Add Grid Mode to Scenes Widget

### PR DESCRIPTION
**Pull request by VodBox**
### Description

This PR adds an option to the right click menu in the scenes widget to switch modes. When in regular list mode, it'll let you select grid mode, and in grid mode, it'll let you select list mode. Grid mode changes the scenes widget to have a grid of buttons for scenes rather than a list, much like XSplit.

### Motivation and Context

To provide a familiar look and feel to people coming over from XSplit, and to show more scenes compactly in certain situations.

### How Has This Been Tested?

This has been tested on a Windows 10 PC using all 4 themes shipped with OBS.

### Types of changes

 - New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by jp9000** [comment]
Reordering in grid mode works, but reordering scenes via dragging in the normal listbox mode appears to have stopped functioning.

**Comment by dodgepong** [comment]
Is the lack of a grid layout for scene selection a complaint we hear from people moving over from Xsplit? I'm hesitant about feeling enthusiastic about this change in context of a wider discussion we need to have about scene organization, particularly for people with large amounts of scenes.

**Comment by mufunyo** [comment]
Possibly nitpicking, but is it impossible to have the selection size for the native theme match the other themes?

**Comment by VodBox** [comment]
@dodgepong It's not really an issue of people moving right now per se, but just maybe a slight benefit to the change. The big benefit is just that a grid can more compactly show a lot of scenes than a list, can help with scene switching since you don't need to scroll, and you can remember where scenes are spatially rather than repeatedly searching the list. It also allows more freedom in the dock layout, since scenes can make use of horizontal space instead of just vertical space.

@mufunyo My issue with the native theme was that any styling I applied would get rid of the native look of the element, and would then require me to try match it to all operating systems. I tried to just simply affect the size of the label, but I had no luck.

**Comment by VodBox** [comment]
I've now fixed the issue where drag n' drop broke for list mode.

**Comment by cg2121** [comment]
IMO, I think it would look better if the button mode had the same background color as the controls dock.

**Pull request merged**
