### PR TITLE
UI: Update Facebook get stream key URL

### PR DESCRIPTION
**Pull request by JohannMG**
Old URL is being phased out for the cleaner interface. Changed in both
the settings pane and the wizard.

### Description

Old URL is being phased out for the cleaner interface. Changed in both
the settings pane and the wizard. Old URL doesn't work is user is in Dark Mode on facebook. 

### Motivation and Context

Allows people to get the stream key correctly and faster. The old URL will be removed later as well. 

### How Has This Been Tested?

 - Open URL from button in Settings
 - Open URL from button in Wizard
MacOS Catalina. Chrome. 

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Looks like this fails clang-format, you'll need to format the variable similar UI/window-basic-auto-config.cpp#L592

**Comment by JohannMG** [comment]
yeah already on it . forgot you have to tell it master. pushing now

**Comment by JohannMG** [comment]
clang fixed

**Comment by Fenrirthviti** [comment]
Can merge once checks clear '.')b

**Comment by RytoEX** [comment]
For posterity, could you please point to documentation from Facebook on this change?

**Comment by JohannMG** [comment]
Sure


Live Producer - Facebook Live

https://www.facebook.com/business/help/593310264553282
"Live Producer is the new way to go Live on Facebook using higher-end
production equipment and streaming software. Live Producer can be accessed
from any entry point to Live from a Page and at facebook.com/live/producer."

"You can manage your Live post(s), scheduling and certain broadcast
Settings in the left-hand column. Critical functions such as Source Details
and Stream Health, plus interactive features like Polls, are located in the
top navigation bar. A small stream preview is available in the bottom
right-hand corner; simply scroll up to access a larger stream preview."

**Pull request merged**
