### PR TITLE
text-freetype2: Use cached glyph advances

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

We had these advances laying around but didnt use them here. Loading the glyphs from the fonts is extremely slow, so lets avoid that since we take the time to cache these already.

### Motivation and Context

Makes this function ~4000x times faster. Everyone loves fast.

### How Has This Been Tested?

It didnt crash, but also this is used in the other width computation so it should be fine.

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
This looks okay, but I am not really familiar with this patch of code. cc @norihiro ?

**Comment by norihiro** [comment]
This looks good to me.

https://github.com/obsproject/obs-studio/blob/46c6efbd24cb0158286395e7765c9a3a46fb1440/plugins/text-freetype2/text-functionality.c#L579-L583

The function `get_ft2_text_width` always called after `cache_glyphs`. So, the cached width will be used for most cases. The `else` closure will be reached only if "Out of space trying to render glyphs" has happened in `cache_glyphs`. I tested both cases and the rendering looks ok.

**Comment by RytoEX** [comment]
Tested this briefly on Windows 11 and it seems fine. Though, I did notice that there are apparently a few fonts that we cannot actually load (e.g., System, Courier), but that also occurs in 30.1.2 and is unrelated to the changes here.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Commit message nits:
* didnt -> didn't
* lets -> let's

This will make the first line of the commit message body too long, so the line wrapping will need to be adjusted.

**Review by RytoEX — APPROVED** [review]

**Review by Lain-B — APPROVED** [review]

**Pull request merged**
