### PR TITLE
obs-qsv: updating MSDK APIs and license headers

### PR DESCRIPTION
**Pull request by brittneysclark**
- Updating MSDK APIs from version 1.17 to 1.26

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Hey! Thanks for the big update. Is there any additional information you are able to provide that explains what the major changes are? Is it performance, overall compatibility/support, etc.?

This is a very major change, so it would be helpful to understand the reasoning behind it.

**Comment by brittneysclark** [comment]
Hi! The major changes are for overall compatibility/support to align with the current Intel Media SDK and Intel Media SDK samples. There is an ongoing effort to improve quality of this plug-in and this update could help with enabling features to do so.

**Comment by bushwookieee** [comment]
May I ask why I'm getting messages from you guys?

**Comment by dodgepong** [comment]
@bushwookieee Probably because you are watching the `obs-studio` repository on GitHub.

**Comment by jp9000** [comment]
I would prefer not to update the library until there is a change that requires it to be updated.  When that time comes, feel free to add the library update as a commit to that PR if needed.

**Pull request closed without merging**
