### PR TITLE
clang-format: Increase column limit from 80 to 120

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Increase the column limit in clang-format from 80 to 120.

### Motivation and Context

Want to have longer lines. Others have asked us to use longer lines.

### How Has This Been Tested?

I haven't done any build testing with this. This is a formatting change, so hopefully all CI builds will pass.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by Lain-B — APPROVED** [review]
Dew it.

**Review by PatTheMav — APPROVED** [review]
Looks fine to me overall - some instances of initialiser syntax indentation look weird in the diff view because of tab widths (looks like the diff uses 3 spaces per tab stop).

**Comment by derrod** [comment]
oh no

**Comment by PatTheMav** [comment]
> oh no

aocjx

**Pull request merged**
