### PR TITLE
CI: Update macOS dependencies

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

CI: Update macOS dependencies
* Update VLC from 3.0.4 to 3.0.8
* Update Sparkle from 1.20.0 to 1.23.0

### Motivation and Context

Per conversation with @DDRBoxman , let's update the macOS deps.

Sparkle added support for EdDSA (ed25519) signatures and phased update rollouts.

### How Has This Been Tested?

I can confirm that CI successfully builds with these changes, but I have not tested the resulting build since I do not have a macOS device.  We'll need to build OBS with the new deps, including obsproject/obs-deps#3 and obsproject/obs-deps#4, and test that to make sure everything works.

### Types of changes

- CI update (dependencies)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by PatTheMav** [comment]
@RytoEX I can quickly check out and build/run your branch on my machine. Will report back later today.

**Comment by PatTheMav** [comment]
With the fixes mentioned in https://github.com/obsproject/obs-deps/pull/4 and this PR I successfully built and can run OBS 25.0.3 well so far.

**Comment by dodgepong** [comment]
@PatTheMav Can you test things like SRT output and OBS control of browser audio?

**Comment by PatTheMav** [comment]
@dodgepong I haven't dabbled in SRT so far, but I take it this guide should get me started: https://obsproject.com/wiki/Streaming-With-SRT-Protocol?

I will take a look at both later tonight.

**Comment by PatTheMav** [comment]
So with the build I created SRT was not possible, using the Stream source I got the following error:

```
Invalid Path or Connection URL. Please check your settings to confirm that they are valid.
```

Using FFmpeg I got the following error (for that I might need to check if FFmpeg has SRT support enabled in the first place):

```
An unspecified error occurred while recording.

Couldn't open 'srt://127.0.0.1:8080', Protocol not found
```

Browser audio is correctly routed through OBS when selected in the source' properties, if monitoring is enabled audio is correctly routed to the monitoring device.

Volume control and audio filters also work correctly with browser source audio.

**Comment by PatTheMav** [comment]
@dodgepong So I managed to build a new `obsdeps` package containing ffmpeg libraries with `srt` support, I will still need to clean it up, because I threw `openssl` in there as well (it's an `srt` dependency as well as `srt` itself - I will check later if that's all necessary).

When using the `listener` mode switch, the "Start Streaming" button will stay in the "clicked" state without text and OBS isn't listening on the specified port (I checked with `lsof`) and OBS is not in the streaming state either (those buttons and their hover states behave weird in other ways, but I have to investigate that further).

The log just shows the output of the streaming encoder settings, but that's it. I can still change scenes and use the program as before, the "Start Streaming" button is just out of order for the rest of the session. Also quitting the app keeps it running in an unresponsive state (the UI is gone though).

The FFmpeg route works fine though, that just required having FFmpeg with `libsrt` support compiled in.

**Comment by dodgepong** [comment]
> I will still need to clean it up, because I threw openssl in there as well (it's an srt dependency as well as srt itself - I will check later if that's all necessary

You should use mbedtls, not OpenSSL for SRT.

**Comment by PatTheMav** [comment]
Yep.. it's possible with a `cmake` switch that's not properly documented, but I saw that @pkviet also had issues with that same topic at first. FWIW it's the same switch as on Windows.. 🤷🏻‍♂️

Only problem is that when building obsdeps everything needs to be available by `pkg-config`, yet `mbedtls` doesn't create the necessary `pc` files (there are open issues and broken pull requests for this), so when including `srt`, `FFmpeg` looks for `mbedtls` via `pkg-config` and comes up empty.

Looks like the file(s) have to be added manually..

**Comment by RytoEX** [comment]
> Yep.. it's possible with a `cmake` switch that's not properly documented, but I saw that @pkviet also had issues with that same topic at first. FWIW it's the same switch as on Windows.. 🤷🏻‍♂️

I assume you mean `-DUSE_ENCLIB=mbedtls` or `--use-enclib="mbedtls"` (for configure)?

**Comment by PatTheMav** [comment]
Yep, that's the one.

**Comment by EwoutH** [comment]
Wouldn't it be better for a consistent user experience to use the same dependencies and packages on Windows and macOS?

**Comment by dodgepong** [comment]
Ideally, yes. The reason we have stayed on 5.10 on Windows for so long is largely because upgrading would break plugins that reply on Qt. I think we tried upgrading to 5.12 or 5.13 and we got some serious DPI-related bugs. I can't remember if we've tested 5.14 or not.

The reason we updated to 5.14 on Mac is because something happened between last release and now that cause properties windows to render completely weird, and upgrading Qt versions was the thing that fixed it.

If it can be demonstrated that 5.14 is stable, especially with regard to varying DPI levels, then I would be in favor of upgrading. It's a band-aid we're going to have to rip off at some point.

**Comment by EwoutH** [comment]
I think with the recent major 25.0 release now is the moment, while we still have a long window to the next major release. I'm willing to put some effort in testing #2646.

**Comment by EwoutH** [comment]
Aside from Qt, VLC and Sparkle, there are more dependencies which need an update, including Opus, libvpx, Jansson and FFmpeg. Maybe we could create a small task force to implement an easy maintainable dependency structure.

**Comment by PatTheMav** [comment]
@EwoutH Those dependencies are handled by this side-project and we just updated a bunch of those libraries you mentioned: https://github.com/obsproject/obs-deps

**Comment by EwoutH** [comment]
Nice! I was looking at these scripts, are they still used? https://github.com/obsproject/obs-studio/tree/master/CI/util

**Comment by DDRBoxman** [comment]
Newer versions of those live in the obs deps repo now. Still working on getting the windows ones up to date.

**Pull request merged**
