### PR TITLE
Fix virtual camera can only be started once on Linux

### LINKED ISSUE #4808: Virtual Camera will start one time and will not restart until reboot
### Operating System Info

Ubuntu 21.04

### Other OS

_No response_

### OBS Studio Version

27.0.0

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/Cy96Hu3XHeD7c-Zb

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

I should be able to toggle Virtual Camera on and off.

### Current Behavior

I'm able to start and stop Virtual Camera one time.  After that, it will not start again until my next reboot.  Each click on the "Start Virtual Camera" button inserts a single line of text into the log:
`04:00:54 PM.094: Failed to start virtual camera`

### Steps to Reproduce

1. Reboot
2. Launch OBS
3. Click "Start Virtual Camera"
4. Click "Stop Virtual Camera"
5. Click "Start Virtual Camera".  The button text remains the same ("Start Virtual Camera") and the VC is never started.

### Anything else we should know?

This began happening immediately after an OS upgrade from Ubuntu 20.10 to 21.04.  Things worked fine in Ubuntu 20.10 using the same version of OBS (27.0.0).

The attached log shows me launching OBS immediately after a reboot.
I click to start the virtual camera.
I enter my sudo pw.
I click to stop the virtual camera.
So far so good.
I click to start the virtual camera - three times - and all three times result in failure and an error message in the log: "Failed to start virtual camera."

The output of `v4l2-ctl --list-devices` immediately after reboot:
```
UVC Camera (046d:0821) (usb-0000:00:14.0-8.4):
	/dev/video4
	/dev/video5

Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-9):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
```

The output of `v4l2-ctl --list-devices` after I've tried and failed to get the Virtual Camera to start:
```
OBS Virtual Camera (platform:v4l2loopback-000):
    /dev/video6

UVC Camera (046d:0821) (usb-0000:00:14.0-8.4):
    /dev/video4
    /dev/video5

Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-9):
    /dev/video0
    /dev/video1
    /dev/video2
    /dev/video3
```

This is on a Dell XPS 13 laptop, model 9300.  If it matters, I'm not using the integrated webcam, I'm using Logitech C910 USB cam.

### PR DESCRIPTION
**Pull request by shoffmeister**
### Description

Fix #4808 by applying insights found at https://github.com/floe/backscrub/issues/133#issuecomment-1085598710

At the same time, apply more logging and improve error handling to said module such that any future challenging behaviour can be identified more easily.

### How Has This Been Tested?

* Build OBS from git, install as portable, on Fedora 36
* Start OBS, load scene collection
* Click "Start Virtual Camera" 
* Click "Stop Virtual Camera" 

--> works; now demonstrating that this fixes the reported problem, do

* Click "Start Virtual Camera" 
* Click "Stop Virtual Camera" 

... and this now works.

Video does work, too - tested with Firefox 103 and the Slack (https://slack.com/) web interface, device configuration -> OBS.

### Types of changes

Fixes #4808

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by shoffmeister** [comment]
There are reports that some fixes for the underlying challenge in the v4l2loopback module exist, and that those fixes have been applied in various repository, possibly in some distributions.

As I am writing this, no changes can be found upstream (https://github.com/umlaeute/v4l2loopback), and neither are they applied to Fedora 36 (which is in fact running upstream).

**Comment by tytan652** [comment]
> All commit messages are properly formatted and commits squashed where appropriate.

You commits are not properly formatted, check the contributing document link in the description.

And don't close this PR to open a new one just amend your commits and forced push.

**Comment by tytan652** [comment]
For the formatting, you'll need clang-format 14 and at least the `format-code.sh` script in the CI folder to format your code.

**Comment by tytan652** [comment]
If you have the bug with the latest version of the module it change everything on how I see it.

And I just gave my point of view, I'm not the one in charge for what is merged or not.

**Comment by kkartaltepe** [comment]
This was already resolved upstream with https://github.com/umlaeute/v4l2loopback/pull/477

**Comment by shoffmeister** [comment]
My local system is Fedora 36, it is up-to-date, and I have this package installed:
```
rpm -qa v4l2loopback
v4l2loopback-0.12.7-1.fc36.noarch
```

This package has been built via https://koji.rpmfusion.org/koji/buildinfo?buildID=23032 which points to https://pkgs.rpmfusion.org/cgit/free/v4l2loopback.git/

Version 0.12.7 is also what is published on https://github.com/umlaeute/v4l2loopback/tags as the most current release.

My running driver (debug=99) logs as
```
[33875.719261] /tmp/akmodsbuild.xR0XYRW0/BUILD/v4l2loopback-kmod-0.12.7/_kmod_build_5.18.17-200.fc36.x86_64/v4l2loopback.c:1943[v4l2_loopback_open]
```

This specific version is supposed to contain plenty of fixes, including the linked PR above.

I can assure you - on my system, as it is, OBS 27.2.4 (`obs-studio-27.2.4-4.fc36.x86_64`) has "can only be started once" behaviour.

I had a very quick gander at trying to fix OBS 27.2.4, but ran into known problems there (https://github.com/obsproject/obs-studio/issues/5622) which simply did not appear for when working with OBS git. So, for the sake of simplicity and my own sanity, I worked on OBS git, and this pull request allows me to start/stop the OBS git virtual camera any number of times, thanks to the second commit in this PR.

(Plus, as it happens, it is much more helpful in debug and warning logs, which is the first commit of this PR).

**Comment by kkartaltepe** [comment]
> This specific version is supposed to contain plenty of fixes, including the linked PR above.

Im afraid im not sure I follow, given the information provided i reach the opposite conclusion.

**Comment by shoffmeister** [comment]
My local testing with a very much up-to-date Fedora 36

* `uname -a` == `Linux fedora 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC`
*  `rpm -qa v4l2loopback` == `v4l2loopback-0.12.7-1.fc36.noarch`

- where `v4l2loopback-0.12.7-1.fc36.noarch` would include the changes referred to - suggests that

* OBS git master == virtual camera can only be started once; unwanted behaviour
* this PR == virtual camera can be started and stopped an arbitrary number of times

The key material difference in this PR is 07fc858d4b63b00abb46b4a7fd8de570498b32da; the other commit is diagnostics, maintainability and (removal of) resource leakage that I applied in my quest to track down the problem.

I have not root caused the unwanted behaviour of OBS git master to a specific implementation detail in `v4l2loopback-0.12.7-1.fc36.noarch` (or https://github.com/umlaeute/v4l2loopback/releases/tag/v0.12.7)

**Comment by shoffmeister** [comment]
For the record, I have now tested consumption of video through the OBS virtual camera on

* Fedora 36 (`Linux fedora 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC`)
* KDE -> Wayland

for the following applications:

* Microsoft Teams "1.5.00.10453 (64-bit)" off the Microsoft official repository (video appears mirrored in preview; do note that Microsoft Teams apparently only is happy with 720p output resolutions; 1080p does not work, and reportedly has never worked)
* Chromium (chromium-freeworld) 104.0.5112.79 (Discord, Slack web site) off rpmfusion.org repositories
* Firefox (103.0.2) (Slack web site) off the main Fedora repositories

All applications appeared to exhibit no regression relative to OBS git master.

I have not tested X11, but would expect any regression there, either.

**Comment by kkartaltepe** [comment]
Sorry I think we are speaking past each other. As I said there is a commit in upstream with the fix, and as you said you are on the latest release. But if you look at the repository you will see that no released tag includes the fix mentioned and this is confirmed looking at the commit log.

Of course you could go around and convince every tool using v4l2 to update with some patches and hope that they trickle down to you soon enough. But I think you would agree the best solution for everyone would be to ask for upstream to release a version with the fix, maybe next best would be to ask for your package manager to include a backport, and failing all else you can ask every tool you use to include a patch. It doesnt seem like either the first two have been tried yet so that is what im trying to suggest.

**Comment by shoffmeister** [comment]
Upstream formally releasing a fix is optimal. The next step then is that all these upstream changes need to trickle down into distributions, and from distributions onto user systems.

I tend to recollect reading that the problem was introduced around version 0.12.5 of v4l2loopback, so roughly around April 2020. Any distribution using a plain release version of v4l2loopback starting with 0.12.5 is broken, to this date. (Some distros actively *patching* v4l2loopback is a different story)

So, for example, right now Arch Linux will have been broken, and continues to be broken, since April 2020 - at least when looking at https://archlinux.org/packages/community/any/v4l2loopback-dkms/

It is indeed a decision for the OBS project to make whether they want to carry the stream-on/off change in talking to v4l2loopback. 

(IMHO) Semantically this change (07fc858d4b63b00abb46b4a7fd8de570498b32da) even makes sense (beware: I have barely any experience with v4l2). From https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-streamon.html?highlight=vidioc_streamon: 
> The VIDIOC_STREAMON and VIDIOC_STREAMOFF ioctl start and stop the capture or output process during streaming ([memory mapping](https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/mmap.html#mmap), [user pointer](https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/userp.html#userp) or [DMABUF](https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/dmabuf.html#dmabuf)) I/O.

The v4l2loopback module does not offer any particular API documentation of its own. The next best source, the V4L2 generic documentation has this example of an application driving a video grabber device: https://linuxtv.org/downloads/v4l-dvb-apis/userspace-api/v4l/v4l2grab.c.html?highlight=vidioc_streamon. This example uses stream on/off (see highlighting). In the OBS context, the v4l2loopback module acts in a role of a video grabber device.

**Comment by kkartaltepe** [comment]
Can you leave the debug information in the 2nd commit to https://github.com/obsproject/obs-studio/pull/7395 and just leave 4196abb7e5c6b64111657d79a1ed368b40ffa38b and we can try and merge this for 28.1 (also fixup the format complaints)

**Comment by jp9000** [comment]
Hi there, make sure not to check the `I have read the contributing document` checkbox if you haven't read the contributing document.

**Comment by norihiro** [comment]
I have two suggestion for your change.

- Code format need to be fixed. Please run command below.
 ```
clang-format -i plugins/linux-v4l2/v4l2-output.c
```
- Is it necessary to check the error by `ioctl(...) == -1`? Other lines with `ioctl` have `ioctl(...) < 0` so that I feel the error check condition should be the same as other lines so that it is easier for other people to read the code.

**Pull request merged**
