### PR TITLE
Update of E2k support

### PR DESCRIPTION
**Pull request by makise-homura**
### Description
As of support for Elbrus has been introduced in PR #3288, this pull request improves support for building obs-studio on Elbrus hardware platform (which is based on Russian [Elbrus](https://en.wikipedia.org/wiki/Elbrus-8S) CPU family) with its native lcc (eLbrus Compiler Collection) compiler.

### Motivation and Context
It allows current master of OBS be built on Elbrus out-of-the-box (and use SIMD functionality with altered version of SIMDE as of [this PR](https://github.com/simd-everywhere/simde/pull/700)).

### How Has This Been Tested?
Build and testing plan:

* Build on Elbrus workstation (e2k-linux-gnu) and run there.
* Build on x86_64 workstation (x86_64-linux-gnu) and run there (to be sure that nothing is broken on x86_64).

Details of Elbrus workstation:

* CPU: Elbrus-8C (formerly Elbrus-8S) running on 1300 MHz
* Motherboard: E8C-EATX
* OS: OS Elbrus 6.0.0
* GPU: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere Radeon RX 580 (rev e7)
* Kernel: 5.4.0-2.3-e8c
* Compiler: lcc:1.25.09:Oct--1-2020:e2k-v4-linux gcc (GCC) 7.3.0 compatible

Details of x86_64 workstation:

* CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor running at 3.0 GHz
* Motherboard: MSI X399 SLI PLUS (MS-7B09)
* GPU: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]
* OS: Ubuntu 20.04.1 LTS
* Kernel:  5.4.0-54-generic #60-Ubuntu
* Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Results:

* Successfully performed `mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release .. && make -j16 && sudo make install`, and ran `obs` on both workstations; no suspicious behavior found.

### Types of changes
* New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
simde changes to support elbrus should be submitted upstream to the simde project (https://github.com/simd-everywhere/simde) , then we can update our simde version once those changes have been submitted. Feel free to submit a PR just for fixing the libcaption warnings.

**Comment by makise-homura** [comment]
Ok. So should I rewind this branch to ff523ab , and then force-push this branch with the only one that commit?

**Comment by kkartaltepe** [comment]
If you want to do that and rewrite the PR description thats fine too.

**Comment by makise-homura** [comment]
Okay @kkartaltepe , I filed a PR for SIMDE, and force-pushed this branch to leave only SIMDE-unrelated commit.

**Comment by jp9000** [comment]
Those libcaption warnings are already fixed on master, so this PR basically does nothing now. When your E2k changes go through and are ready, then you should make a new PR (can probably copy this PR mostly word for word when that happens). If that's okay at least.

**Comment by makise-homura** [comment]
Uh, right, I haven't checked master recently to see this commit is already there. Thanks.
I guess it's ok here then.
By the way, will there be need in a specific PR for updating SIMDE in obs-studio once my changes land into its upstream?

**Comment by jp9000** [comment]
I believe so yes. Whenever they update it, then would it be okay if you could recreate this PR with those changes? Sorry for the trouble

**Comment by makise-homura** [comment]
Yes, looks ok for me. So I'll wait till they accept my changes and then create a PR for obs-studio to pull files from updated vesrsion of SIMDE.

**Pull request closed without merging**
