### PR TITLE
build-aux: Add usbmuxd socket in Flatpak

### PR DESCRIPTION
**Pull request by aramg**
### Description
Makes usbmuxd socket available in the Flatpak sandbox.

### Motivation and Context
Plugins may use usbmuxd to communicate with iOS devices via USB. Currently this is not working with the Flatpak variant due to sandboxing. This change makes it possible to access the usbmuxd socket. This change is based on a similar issue [here](https://github.com/flathub/org.blender.Blender/pull/131).

### How Has This Been Tested?
Launching OBS with this flag correctly maps the socket in the sandbox,
`flatpak run --filesystem=/run/usbmuxd:ro com.obsproject.Studio`

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
Please provide reference to your discussions with the flatpak community about exposing sockets via your extension. If this is a lacking feature of flatpaks, I'm sure they would like to be aware and may even provide you a solution that doesnt require OBS to randomly have access to usbmuxd when it doesnt use it.

**Comment by tytan652** [comment]
If plugins use such a socket, it is up to the plugin to explain to the user how to add a hole in the sandbox.

Adding more holes in the Flatpak is not plan at all.

**Comment by aramg** [comment]
Thanks for the feedback. Going through a discussion with the Flatpak community and waiting on a resolution would probably be the correct path. Its just that having users start OBS with special parameters until that is resolved creates bad UX; the change seemed benign, hence the quick PR.

**Comment by aramg** [comment]
A relevant issue / feature-req: https://github.com/flatpak/flatpak/issues/5211

**Comment by hadess** [comment]
Out of curiosity, which OBS plugins would there be that need usbmuxd access?

**Comment by tytan652** [comment]
@hadess likely only one, Droidcam.

**Pull request closed without merging**
