### PR TITLE
Remove Aero-related code

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
As we no longer support Windows 7, remove all code related to toggling and logging Aero.

### Motivation and Context
Remove obsolete code.

### How Has This Been Tested?
Built and ran OBS.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
I'm not sure what the consequences for it are in context of OBS, but it *is* technically possible to disable aero in Windows 10+ by switching to one of the high-contrast accesibility themes.

**Comment by mufunyo** [comment]
> I'm not sure what the consequences for it are in context of OBS, but it _is_ technically possible to disable aero in Windows 10+ by switching to one of the high-contrast accesibility themes.

Are you sure about that?

> Desktop composition for all themes
> In Windows Vista and Windows 7, desktop composition is enabled only with the AERO Glass Theme. Hence users of Windows Classic and high contrast themes cannot use experiences enabled by desktop composition such as Windows Flip, automatic scaling for high resolution (DPI) scaling, thumbnail Preview and full screen magnifier. In addition, in these earlier versions of Windows, app developers must write and maintain multiple code paths – one where desktop composition is enabled and another where desktop composition is disabled.

> With Windows 8, desktop composition is enabled for all themes. Users of Windows Classic and high contrast themes can use the experiences enabled by desktop composition such as Windows Flip, automatic scaling for high resolution (DPI) scaling, thumbnail previews, and full screen magnifier. In addition, developers don’t need to write and maintain multiple code paths, thereby simplifying development.

**Comment by derrod** [comment]
I haven't looked into this too deeply, but turning on high-contrast does make OBS log aero as being disabled at least.

**Comment by derrod** [comment]
It would appear that on a recent Windows 10 build (2009) this is no longer the case. I perhaps it was just a bug with their API to begin with.

**Pull request merged**
