### PR TITLE
obs-qsv11: Use translatable strings for target usage

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

For Target Usage, instead of doing string comparisons against long descriptive strings, use translatable strings for descriptive UI text and simple designations for values used for comparisons and storage. This is similar to what we do for NVENC Presets.

### Motivation and Context

Having to do string comparisons against the full descriptive text all the time seems not ideal. We do something similar to this change for NVENC Presets, though we use a macro there.
https://github.com/obsproject/obs-studio/blob/5dda04ad5ee8733cf5b3073d8906f080647a9139/plugins/obs-ffmpeg/data/locale/en-US.ini#L44-L50
https://github.com/obsproject/obs-studio/blob/5dda04ad5ee8733cf5b3073d8906f080647a9139/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L547-L557

### How Has This Been Tested?

Tested locally and checked the stored values in my test profile's `recordEncoder.json`.
Before:
```
{"target_usage":"TU4: Balanced (Medium Quality)"}
```
After:
```
{"target_usage":"TU4"}
```
Verified that the updated string comparisons work as expected.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Possible alternatives:
* Use an implementation like the `qsv_rate_control_info` struct
* Use a macro

I mostly just submitted this because it's what I wrote first.

**Comment by kkartaltepe** [comment]
Seems ok to me, but now users of the beta might have broken presets since we dont upgrade those just the original preset names?

**Comment by RytoEX** [comment]
> Seems ok to me, but now users of the beta might have broken presets since we dont upgrade those just the original preset names?

We generally consider settings in beta to be unstable and in-flux. The only upgrades we worry about are between stable releases.

**Comment by RytoEX** [comment]
Received approvals off-thread. No major objections. I don't think we've historically handled settings migrations for anything except stable releases. Going to merge this as-is because I want to avoid the existing settings strings ending up in a stable release.

**Pull request merged**
