### PR TITLE
Fix svt-av1 and libaom-av1 CQP ratecontrol

### PR DESCRIPTION
**Pull request by flaeri**
### Description
This makes the CQP rate control QP value be respected, which it is currently not. `global_quality` does not get respected by the encoders, and this is remedied by specifying via `priv_data`.

### Motivation and Context
Fixes https://github.com/obsproject/obs-studio/issues/7784

Want CQP rate control to work properly.

### How Has This Been Tested?
Tested on Win 11 22H2.

Confirmed QP value gets respected by encoding and checking the files produced (one file qp 10 one qp 50).

Made sure other rate control methods still work for both encoders.

Also tested ffmpeg deps 59.37.100 from https://github.com/obsproject/obs-deps/pull/141

CQP mode still works for both encoders with this PR.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by flaeri** [comment]
I split this up into two commits. My thinking was that if one of the encoder changes is bad, you dont have to revert both, "unfixing" the other encoder in the revert process.

**Comment by flaeri** [comment]
Also tested ffmpeg deps `59.37.100` from https://github.com/obsproject/obs-deps/pull/141

CQP mode still works for both encoders with this PR.

**Review by RytoEX — APPROVED** [review]

**Comment by notr1ch** [comment]
Commit prefix should be "obs-ffmpeg" in the future.

**Comment by RytoEX** [comment]
> Commit prefix should be "obs-ffmpeg" in the future.

Yeah, I was in a bit too much of a hurry to merge this and did not notice until right after merging. We collectively sighed in disgust once we saw it.

**Pull request merged**
