### PR TITLE
rtmp-services: Increase FB max bitrate to 6Mbps

### PR DESCRIPTION
**Pull request by JohannMG**
Facebook Live now recommends 6000kbps for most streamers and the auto
capping is clamping users to 4000kpbs. This fixes the new suggested
setting.

### Description

Gaming streamers are now recommended to stream at 6Mbps on FB Live so updating the recommendation. 

### Motivation and Context

If the streamer doesn't find the way to turn off rate limit enforcement they'll still stream at 4mbps even with 6mbps entered into the form. This fixes that. 

### How Has This Been Tested?

Can now stream at 6mbps with enforcer on. 

### Types of changes

 - Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by WizardCM** [comment]
Do you have a source or official documentation we could reference for this?

**Comment by JohannMG** [comment]
The new FBGaming page has 1080 @ 6mpbs recommend
Link
https://www.facebook.com/fbgaminghome/creators/best-practices

**Comment by WizardCM** [comment]
Excellent, thank you!

Two minor notes:
1. You'll need to bump the version numbers. Check past services updates for reference.
2. You typo'd the component in the commit title: it's `rtmp-services` not `rmpt`.

**Comment by JohannMG** [comment]
> You typo'd the component in the commit title: it's rtmp-services not rmpt.

Thanks. And Thanks @jp9000 for the quick rename fix. 
I only type rtmp 32709 times a week hahaha.

**Pull request merged**
