### PR TITLE
Fix MSVC warnings

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Clean up various warnings seen with MSVC.

### Motivation and Context
I hate warning spam.

### How Has This Been Tested?
OBS still runs. I did not test every feature.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jp9000** [comment]
Seems to have some conflicts, I think I merged some other warning fixes before this one.

**Comment by jpark37** [comment]
Fixed the conflict.

**Comment by jpark37** [comment]
Fixed the other sneaky non-overlapping conflict.

**Comment by RytoEX** [comment]
Is it worth submitting the RNNoise changes as a PR to their repo?  It seems the RNNoise repo isn't updated often, but I don't know what their plans are.

**Comment by jpark37** [comment]
Nah, a real fix would be to remove all accidental double usage. I just did the minimum to get rid of the warnings.

**Pull request merged**
