### PR TITLE
UI: Add ability to resize output based on source size

### PR DESCRIPTION
**Pull request by cg2121**

### CODE REVIEW

**Comment by RytoEX** [comment]
Could you please explain what this is actually used for?  What does it do?

**Comment by CatxFish** [comment]
I am not sure what is the purpose of this commit, but you shouldn't just check buttons of stream and record , there are still some custom output plugins do not expect resolution change when they are active.

**Comment by dodgepong** [comment]
For reference, the purpose of this feature is to be able to adjust the canvas size to exactly match the resolution of a particular source. For most people this isn't useful, but for some people who want to record exact windows or exact sources without having to manually change the resolution, then this is useful.

**Comment by RytoEX** [comment]
Wouldn't this fail to update if encoding is active?

**Comment by SuslikV** [comment]
I think, that dynamic bitrate, size and frame rate is part of the encoding. And any controllers (like source size) should be implemented later.

**Comment by cg2121** [comment]
If the output is active, the resize output function is disabled.

**Comment by jp9000** [comment]
I feel like this needs a dialog box (with a warning icon) associated with this action, explaining to the user in detail what it will do, and asking them whether they're sure they want to do that or not.  I just can see this as something that would be very frustrating if a user hit it by accident -- even in the off-chance.

**Comment by cg2121** [comment]
I have now added the confirmation box.

**Comment by DDRBoxman** [comment]
Oh, I found the script I wrote a while back that does this.

https://gist.github.com/DDRBoxman/e9b057388e0590d9a435688b1b100a95

**Comment by jp9000** [comment]
One more thing: needs to check to make sure that neither the width nor height is 0.  Certain sources (image sources with no image set for example, or audio sources, things like that) will return a 0x0 size.

**Comment by cg2121** [comment]
I have now set the action to be disabled if the source size is 0.

**Pull request merged**
